# Scrape data for Japanese Translation Activity project

In [100]:
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import requests
import re
from tqdm import tqdm
from ast import literal_eval # convert string list back to list from csv

In [2]:
BASE_URL = "https://bunpro.jp"
GRAMMAR_POINTS_URL = "https://bunpro.jp/grammar_points"
headers = {}

In [3]:
grammar_points_page = requests.get(GRAMMAR_POINTS_URL)

soup = BeautifulSoup(grammar_points_page.text, 'html.parser')

grammar_points_list = []

for child in soup.find_all(attrs={"class":"u-position_absolute u-inset_0"}, recursive=True):
    grammar_points_list.append(child.attrs["href"])

In [ ]:
print(grammar_points_list)

grammar_data_df = pd.DataFrame(columns=["level", "grammar_point_jp", "meaning_en", "description"])


# "text" field format: [["word", "furigana"], ["word", "furigana"], ...]
# "grammar_char_location": indeces where the grammar point appears in the text, for later highlighting

['/grammar_points/%E3%81%A0', '/grammar_points/%E3%81%A7%E3%81%99', '/grammar_points/%E3%81%AF', '/grammar_points/%E3%82%82', '/grammar_points/%E3%81%93%E3%82%8C', '/grammar_points/%E3%81%9D%E3%82%8C', '/grammar_points/%E3%81%82%E3%82%8C', '/grammar_points/%E3%81%AE', '/grammar_points/%E3%81%84%E3%81%84', '/grammar_points/%E3%81%84-adjectives', '/grammar_points/%E3%81%AA-adjectives', '/grammar_points/%E3%81%8B', '/grammar_points/%E3%81%8C', '/grammar_points/%E3%82%88', '/grammar_points/%E3%81%AD', '/grammar_points/%E3%82%8B-Verbs', '/grammar_points/%E3%81%86-Verbs', '/grammar_points/%E3%82%92', '/grammar_points/polite-verb-endings', '/grammar_points/%E3%82%8Bverb-%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%86verb--%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%A8-and', '/grammar_points/%E3%81%93%E3%81%93', '/grammar_points/%E3%81%9D%E3%81%93', '/grammar_points/%E3%81%82%E3%81%9D%E3%81%93', '/grammar_points/%E3%81%A7', '/grammar_points/%E3%81%AB', '/grammar_points/%E3%81%8B-or', '/grammar_points/%E3%81%A8-with', '/grammar_points/%E3%81%A7%E3%81%97%E3%82%87%E3%81%86', '/grammar_points/%E3%81%A0%E3%82%8D%E3%81%86', '/grammar_points/%E3%81%8C%E3%81%82%E3%82%8B', '/grammar_points/%E3%81%8C%E3%81%84%E3%82%8B', '/grammar_points/%E3%81%93%E3%81%AE', '/grammar_points/%E3%81%9D%E3%81%AE', '/grammar_points/%E3%81%82%E3%81%AE', '/grammar_points/-%E3%82%93%E3%81%A7%E3%81%99-%E3%81%AE%E3%81%A7%E3%81%99', '/grammar_points/past-tense-%E3%81%84-adjectives', '/grammar_points/%E3%81%AE%E3%81%AF', '/grammar_points/%E3%81%84-adjective-noun', '/grammar_points/%E3%81%AA-adjective-noun', '/grammar_points/%E3%81%B8%E3%81%84%E3%81%8F', '/grammar_points/%E3%81%99%E3%82%8B', '/grammar_points/%E3%81%8F%E3%82%8B', '/grammar_points/%E3%82%8B-verb-past', '/grammar_points/%E3%81%86-verb-past', '/grammar_points/%E3%81%99%E3%81%8D', '/grammar_points/%E3%81%8D%E3%82%89%E3%81%84', '/grammar_points/%E3%81%AE%E3%81%8C%E3%81%99%E3%81%8D', '/grammar_points/%E3%81%8C%E3%81%82%E3%82%8B-noun', '/grammar_points/negative-%E3%81%84-adjectives', '/grammar_points/%E3%81%A7-by', '/grammar_points/%E3%81%AE%E3%81%A7', '/grammar_points/%E3%81%8B%E3%82%89-because', '/grammar_points/%E3%81%8B%E3%82%89', '/grammar_points/%E3%81%91%E3%81%A9-%E3%81%A0%E3%81%91%E3%81%A9', '/grammar_points/%E3%81%8C-but', '/grammar_points/%E3%82%8B-verb-neg-past', '/grammar_points/%E3%81%86-verb-neg-past', '/grammar_points/verb-%E3%81%A6', '/grammar_points/%E3%81%A6%E3%81%84%E3%82%8B1', '/grammar_points/%E3%81%B8', '/grammar_points/verb-%E3%81%AB%E3%81%84%E3%81%8F', '/grammar_points/%E3%81%A0%E3%82%8C', '/grammar_points/%E3%81%84-adjective-predicate', '/grammar_points/%E3%81%AA-adjective-predicate', '/grammar_points/%E3%81%A0%E3%81%A3%E3%81%9F-%E3%81%A7%E3%81%97%E3%81%9F', '/grammar_points/%E3%81%98%E3%82%83%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%98%E3%82%83%E3%81%AA%E3%81%8B%E3%81%A3%E3%81%9F', '/grammar_points/%E3%81%84-Adjective-%E3%81%8F%E3%81%AA%E3%81%8B%E3%81%A3%E3%81%9F', '/grammar_points/%E3%81%A8', '/grammar_points/%E3%81%A3%E3%81%A6', '/grammar_points/verb-non-past', '/grammar_points/verb-%E3%81%9F-noun', '/grammar_points/%E3%81%AE-noun-ommission', '/grammar_points/%E3%81%AA', '/grammar_points/%E3%81%A0%E3%81%91', '/grammar_points/%E3%81%A9%E3%82%8C', '/grammar_points/%E3%81%A9%E3%81%93', '/grammar_points/%E3%81%A9%E3%81%AE', '/grammar_points/%E3%81%A6%E3%81%84%E3%82%8B2', '/grammar_points/%E3%81%A6%E3%81%8B%E3%82%89', '/grammar_points/verb-%E3%81%A6-b', '/grammar_points/%E3%82%82%E3%81%86', '/grammar_points/%E3%81%BE%E3%81%A0', '/grammar_points/%E3%81%BE%E3%81%A0-%E3%81%A6%E3%81%84%E3%81%BE%E3%81%9B%E3%82%93', '/grammar_points/%E3%81%A6%E3%82%82%E3%81%84%E3%81%84', '/grammar_points/%E3%81%9F%E3%81%84', '/grammar_points/%E3%81%9F%E3%82%8A-%E3%81%9F%E3%82%8A%E3%81%99%E3%82%8B', '/grammar_points/%E3%81%91%E3%81%A3%E3%81%93%E3%81%86', '/grammar_points/%E3%81%9F%E3%81%8F%E3%81%95%E3%82%93', '/grammar_points/%E3%81%BE%E3%81%88%E3%81%AB', '/grammar_points/%E3%81%8F%E3%82%89%E3%81%841', '/grammar_points/noun-%E3%81%BE%E3%81%A7', '/grammar_points/v-%E3%81%BE%E3%81%A7', '/grammar_points/%E3%81%99%E3%81%8E%E3%82%8B', '/grammar_points/%E3%81%AB%E3%81%99%E3%82%8B', '/grammar_points/%E3%81%AB%E3%81%AA%E3%82%8B-%E3%81%8F%E3%81%AA%E3%82%8B', '/grammar_points/%E3%81%AE%E3%81%AA%E3%81%8B%E3%81%A7-%E3%81%8C%E3%81%84%E3%81%A1%E3%81%B0%E3%82%93', '/grammar_points/%E3%82%88%E3%82%8A-%E3%81%AE%E3%81%BB%E3%81%86%E3%81%8C', '/grammar_points/%E3%81%AA%E3%81%AB%E3%81%8B-%E3%81%AA%E3%81%AB%E3%82%82', '/grammar_points/%E8%AA%B0%E3%81%8B-%E3%81%A9%E3%81%93%E3%81%8B-%E8%AA%B0%E3%82%82-%E3%81%A9%E3%81%93%E3%82%82', '/grammar_points/%E3%81%BE%E3%81%97%E3%82%87%E3%81%86', '/grammar_points/%E3%81%BE%E3%81%97%E3%82%87%E3%81%86%E3%81%8B', '/grammar_points/%E3%81%BE%E3%81%9B%E3%82%93%E3%81%8B', '/grammar_points/verb-%E3%81%A6%E3%82%82%E3%81%84%E3%81%84', '/grammar_points/%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84', '/grammar_points/%E3%81%AA%E3%81%84%E3%81%A7%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84', '/grammar_points/%E3%81%A6%E3%81%AF%E3%81%84%E3%81%91%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%AA%E3%81%8F%E3%81%A6%E3%81%AF%E3%81%84%E3%81%91%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%AA%E3%81%8F%E3%81%A6%E3%81%AF%E3%81%AA%E3%82%89%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%9F%E3%81%BB%E3%81%86%E3%81%8C%E3%81%84%E3%81%84', '/grammar_points/%E3%81%AA%E3%81%84%E3%81%BB%E3%81%86%E3%81%8C%E3%81%84%E3%81%84', '/grammar_points/%E3%81%AA%E3%81%8F%E3%81%A1%E3%82%83-%E3%81%AA%E3%81%8D%E3%82%83', '/grammar_points/%E3%82%84', '/grammar_points/%E3%81%9F%E3%81%93%E3%81%A8%E3%81%8C%E3%81%82%E3%82%8B', '/grammar_points/%E3%81%A6%E3%81%84%E3%82%8B3', '/grammar_points/adjective-%E3%81%A6-noun-%E3%81%A7', '/grammar_points/adjective-%E3%81%A6-b', '/grammar_points/%E3%81%AE%E3%81%8C%E3%81%B8%E3%81%9F', '/grammar_points/%E3%81%AE%E3%81%8C%E3%81%98%E3%82%87%E3%81%86%E3%81%9A', '/grammar_points/adjective-%E3%81%AE-%E3%81%AF', '/grammar_points/%E3%81%82%E3%81%92%E3%82%8B', '/grammar_points/%E3%81%8F%E3%82%8C%E3%82%8B', '/grammar_points/%E3%82%82%E3%82%89%E3%81%86', '/grammar_points/%E3%81%91%E3%82%8C%E3%81%A9%E3%82%82', '/grammar_points/%E3%81%A4%E3%82%82%E3%82%8A%E3%81%A0', '/grammar_points/%E3%81%A7%E3%82%82', '/grammar_points/%E3%82%84%E3%81%99%E3%81%84', '/grammar_points/%E3%81%AB%E3%81%8F%E3%81%84', '/grammar_points/%E3%81%A0%E3%82%93%E3%81%A0%E3%82%93', '/grammar_points/%E3%81%A9%E3%82%93%E3%81%A9%E3%82%93', '/grammar_points/%E3%82%89', '/grammar_points/%E3%81%A6%E3%81%84%E3%81%8F', '/grammar_points/%E3%81%A6%E3%81%8F%E3%82%8B', '/grammar_points/%E3%81%8B%E3%81%9F', '/grammar_points/%E3%81%A0%E3%81%91%E3%81%A7', '/grammar_points/%E3%81%A0%E3%81%8C%E3%83%BB%E3%81%A7%E3%81%99%E3%81%8C', '/grammar_points/%E3%81%AA%E3%81%8F%E3%81%A6-conjunction', '/grammar_points/%E3%81%AA%E3%81%8F%E3%81%A6', '/grammar_points/%E3%81%AA%E3%81%84%E3%81%A7', '/grammar_points/Verb%5Bpassive%5D', '/grammar_points/transitive-intransitive-verbs', '/grammar_points/%E3%81%AA%E3%81%8A%E3%81%99', '/grammar_points/%E3%81%A8%E3%81%84%E3%81%86%E3%81%93%E3%81%A8', '/grammar_points/%E3%81%A8%E3%81%8D', '/grammar_points/%E3%81%BE%E3%81%9A', '/grammar_points/%E3%81%BE%E3%81%A7', '/grammar_points/%E3%81%BE%E3%81%A7%E3%81%AB', '/grammar_points/%E3%81%BE%E3%81%9F', '/grammar_points/%E3%81%AF%E3%81%98%E3%82%81%E3%82%8B', '/grammar_points/%E3%81%8A%E3%82%8F%E3%82%8B', '/grammar_points/%E3%81%94%E3%82%8D', '/grammar_points/%E3%81%82%E3%81%A8%E3%81%A7', '/grammar_points/%E3%81%A6%E3%81%84%E3%81%9F', '/grammar_points/%E3%81%AB-frequency', '/grammar_points/%E3%81%A8%E3%81%86%E3%81%A8%E3%81%86', '/grammar_points/%E3%82%88%E3%82%8A', '/grammar_points/%E3%81%94%E3%81%A8%E3%81%AB', '/grammar_points/%E3%81%AA%E3%82%8B%E3%81%B9%E3%81%8F', '/grammar_points/%E3%82%8B%E3%81%A8%E3%81%93%E3%82%8D%E3%81%A0', '/grammar_points/%E3%81%AE%E3%81%AB-despite', '/grammar_points/%E3%81%A8%E3%81%8A%E3%82%82%E3%81%86', '/grammar_points/%E3%81%AA%E3%81%A9', '/grammar_points/%E3%81%BF%E3%81%9F%E3%81%84', '/grammar_points/%E3%81%93%E3%81%A8', '/grammar_points/%E3%81%9D%E3%81%86', '/grammar_points/%E3%81%95', '/grammar_points/%E3%81%A8%E3%81%8B-%E3%81%A8%E3%81%8B', '/grammar_points/%E3%81%9D%E3%81%86%E3%81%84%E3%81%86', '/grammar_points/%E3%82%88%E3%81%86-%E3%81%8A%E3%81%86', '/grammar_points/%E3%82%88%E3%81%86%E3%81%A0', '/grammar_points/%E3%81%9C%E3%82%93%E3%81%9C%E3%82%93', '/grammar_points/%E3%81%8B%E3%81%AA', '/grammar_points/%E3%81%82%E3%81%BE%E3%82%8A-%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%B0', '/grammar_points/%E3%81%AA%E3%82%89', '/grammar_points/%E3%81%8C%E3%82%8B', '/grammar_points/%E3%81%8C%E3%81%99%E3%82%8B', '/grammar_points/%E3%81%9F%E3%81%8C%E3%82%8B', '/grammar_points/%E3%81%8B%E3%82%82%E3%81%97%E3%82%8C%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%BF%E3%81%9F%E3%81%84%E3%81%AB-%E3%81%BF%E3%81%9F%E3%81%84%E3%81%AA', '/grammar_points/%E3%81%9D%E3%81%86%E3%81%AB-%E3%81%9D%E3%81%86%E3%81%AA', '/grammar_points/%E3%81%AE%E3%82%88%E3%81%86%E3%81%AB-%E3%81%AE%E3%82%88%E3%81%86%E3%81%AA', '/grammar_points/%E3%82%88%E3%81%86%E3%81%A8%E6%80%9D%E3%81%86-%E3%81%8A%E3%81%86%E3%81%A8%E6%80%9D%E3%81%86', '/grammar_points/describing-verbs', '/grammar_points/%E3%81%AB%E3%81%99%E3%82%8B-%E3%81%8F%E3%81%99%E3%82%8B', '/grammar_points/%E3%81%A8%E3%81%84%E3%81%84', '/grammar_points/%E3%82%88%E3%81%86%E3%81%AB%E3%81%AA%E3%82%8B', '/grammar_points/%E3%81%BE%E3%81%84-%E3%81%AE%E3%82%88%E3%81%86%E3%81%AB', '/grammar_points/%E3%81%98%E3%82%83%E3%81%AA%E3%81%84%E3%81%8B', '/grammar_points/%E3%82%89%E3%81%97%E3%81%841', '/grammar_points/%E3%81%A6%E3%81%8A%E3%81%8F', '/grammar_points/%E3%81%8C%E3%81%BB%E3%81%97%E3%81%84', '/grammar_points/%E3%81%A6%E3%81%BB%E3%81%97%E3%81%84', '/grammar_points/%E3%81%A8%E3%81%8D%E3%81%84%E3%81%9F', '/grammar_points/%E8%81%9E%E3%81%93%E3%81%88%E3%82%8B', '/grammar_points/%E8%A6%8B%E3%81%88%E3%82%8B', '/grammar_points/%E3%81%A0%E3%81%99', '/grammar_points/%E4%BB%A3', '/grammar_points/number-%E3%82%82', '/grammar_points/%E3%81%BB%E3%81%A8%E3%82%93%E3%81%A9', '/grammar_points/%E3%81%9D%E3%82%93%E3%81%AA-%E3%81%93%E3%82%93%E3%81%AA-%E3%81%82%E3%82%93%E3%81%AA-%E3%81%A9%E3%82%93%E3%81%AA', '/grammar_points/%E5%90%84', '/grammar_points/%E4%BB%A5%E4%B8%8A1', '/grammar_points/%E3%81%84%E3%81%8B', '/grammar_points/%E3%81%84%E3%81%8C%E3%81%84', '/grammar_points/%E3%81%9A%E3%81%A3%E3%81%A81', '/grammar_points/%E3%81%A0%E3%81%84%E3%81%9F%E3%81%84', '/grammar_points/%E3%81%AE%E3%81%AA%E3%81%8B%E3%81%A7', '/grammar_points/%E3%82%88%E3%81%86%E3%81%AB-%E3%82%88%E3%81%86%E3%81%AA', '/grammar_points/number-amount-%E3%81%AF', '/grammar_points/%E3%81%AA%E3%82%93-counter-%E3%81%8B', '/grammar_points/%E7%9C%9F(%E3%81%A3)', '/grammar_points/number-%E3%81%97%E3%81%8B-%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%AF-%E3%81%AE%E4%B8%80%E3%81%A4%E3%81%A0', '/grammar_points/%E3%81%AA%E3%81%84-%E3%81%AF%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%99%E3%81%93%E3%81%97%E3%82%82-%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%99%E3%81%8F%E3%81%AA%E3%81%8F%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%B0%E3%81%82%E3%81%84%E3%81%AF', '/grammar_points/verb%E3%81%A6-request', '/grammar_points/%E3%81%A6%E3%82%88%E3%81%8B%E3%81%A3%E3%81%9F', '/grammar_points/causative', '/grammar_points/%E3%81%A8%E3%81%84%E3%81%A3%E3%81%A6%E3%82%82%E3%81%84%E3%81%84', '/grammar_points/%E3%81%A6%E3%82%82', '/grammar_points/%E3%81%A6%E3%81%97%E3%81%BE%E3%81%86-%E3%81%A1%E3%82%83%E3%81%86', '/grammar_points/verb%E3%81%A6-b2', '/grammar_points/causative-passive', '/grammar_points/verb-%E3%81%A6-noun-%E3%81%A7-b', '/grammar_points/%E3%81%A6%E3%81%82%E3%82%8B', '/grammar_points/%E3%82%88%E3%81%86%E3%81%AB-%E3%81%A6%E3%81%BB%E3%81%97%E3%81%84', '/grammar_points/%E3%81%A6%E3%81%84%E3%82%8B%E3%81%82%E3%81%84%E3%81%A0%E3%81%AB', '/grammar_points/%E3%81%AA%E3%81%8F%E3%81%A6%E3%82%82%E3%81%84%E3%81%84', '/grammar_points/%E3%81%A6%E3%81%BF%E3%82%8B', '/grammar_points/%E3%81%A6%E3%81%99%E3%81%BF%E3%81%BE%E3%81%9B%E3%82%93', '/grammar_points/%E3%81%A6%E3%81%82%E3%81%92%E3%82%8B', '/grammar_points/%E3%81%A6%E3%81%8F%E3%82%8C%E3%82%8B', '/grammar_points/%E3%81%A6%E3%82%82%E3%82%89%E3%81%86', '/grammar_points/%E3%81%AA%E3%81%95%E3%81%84', '/grammar_points/verb%E3%81%A6-b', '/grammar_points/verb-%E3%81%AA%E3%81%84%E3%81%A7', '/grammar_points/%E3%81%A6%E3%81%8F%E3%82%8C%E3%81%A6%E3%81%82%E3%82%8A%E3%81%8C%E3%81%A8%E3%81%86', '/grammar_points/%E3%81%A6%E3%81%8F%E3%82%8C%E3%81%AA%E3%81%84-%E3%81%A6%E3%82%82%E3%82%89%E3%81%88%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%AE%E3%81%A0%E3%82%8D%E3%81%86%E3%81%8B', '/grammar_points/%E3%81%8A-%E3%81%AB%E3%81%AA%E3%82%8B', '/grammar_points/%E3%81%AA%E3%81%95%E3%82%8B', '/grammar_points/%E3%81%8A-%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84', '/grammar_points/%E3%81%84%E3%82%89%E3%81%A3%E3%81%97%E3%82%83%E3%82%8B', '/grammar_points/%E3%81%94%E3%81%96%E3%81%84%E3%81%BE%E3%81%99', '/grammar_points/%E3%81%A7%E3%81%94%E3%81%96%E3%81%84%E3%81%BE%E3%81%99', '/grammar_points/%E3%81%8A-%E3%81%99%E3%82%8B', '/grammar_points/%E3%81%84%E3%81%9F%E3%81%99', '/grammar_points/%E3%81%A6%E3%81%84%E3%81%9F%E3%81%A0%E3%81%91%E3%81%BE%E3%81%9B%E3%82%93%E3%81%8B', '/grammar_points/%E3%81%9F%E3%82%89', '/grammar_points/%E3%81%BB%E3%81%8B%E3%81%AB%E3%82%82-%E3%81%BB%E3%81%8B%E3%81%AB%E3%81%AF', '/grammar_points/%E3%81%8C%E3%81%B2%E3%81%A4%E3%82%88%E3%81%86', '/grammar_points/%E3%81%9D%E3%82%93%E3%81%AA%E3%81%AB', '/grammar_points/%E3%81%B2%E3%81%A4%E3%82%88%E3%81%86%E3%81%8C%E3%81%82%E3%82%8B', '/grammar_points/%E3%81%9F%E3%81%A8%E3%81%88%E3%81%B0', '/grammar_points/Verb%5Bpotential%5D', '/grammar_points/%E3%82%93%E3%81%A0%E3%81%91%E3%81%A9-%E3%82%93%E3%81%A7%E3%81%99%E3%81%8C', '/grammar_points/%E3%81%AF%E3%81%9A%E3%81%A0', '/grammar_points/%E3%81%8B%E3%81%A9%E3%81%86%E3%81%8B', '/grammar_points/%E3%81%A8-conditional', '/grammar_points/%E3%81%AA%E3%81%84%E3%81%A8', '/grammar_points/%E3%81%AF%E3%81%9A%E3%81%8C%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%97%E3%81%8B-%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%A0%E3%81%91%E3%81%A7%E3%81%AA%E3%81%8F', '/grammar_points/%E3%81%93%E3%81%A8%E3%81%8C%E3%81%A7%E3%81%8D%E3%82%8B', '/grammar_points/%E3%81%8B%E3%81%84', '/grammar_points/%E3%82%82%E3%81%97', '/grammar_points/%E3%81%97-%E3%81%97', '/grammar_points/%E3%81%A7%E3%81%A7%E3%81%8D%E3%82%8B-%E3%81%8B%E3%82%89%E3%81%A7%E3%81%8D%E3%82%8B', '/grammar_points/%E3%81%AA%E3%81%8C%E3%82%89', '/grammar_points/%E3%81%9F%E3%81%A8%E3%81%93%E3%82%8D%E3%81%A0', '/grammar_points/%E3%81%A6%E3%81%84%E3%82%8B%E3%81%A8%E3%81%93%E3%82%8D%E3%81%A0', '/grammar_points/%E3%81%A8-%E3%81%A8-%E3%81%A9%E3%81%A1%E3%82%89%E3%81%8C', '/grammar_points/%E3%82%88%E3%81%86%E3%81%AB%E3%81%99%E3%82%8B', '/grammar_points/%E3%81%AA%E3%81%91%E3%82%8C%E3%81%B0%E3%81%84%E3%81%91%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%AA%E3%81%91%E3%82%8C%E3%81%B0%E3%81%AA%E3%82%89%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%A4%E3%81%A5%E3%81%91%E3%82%8B', '/grammar_points/%E3%82%88%E3%81%86%E3%81%AB%E3%81%84%E3%81%86', '/grammar_points/%E3%82%88%E3%81%A6%E3%81%84%E3%81%A0', '/grammar_points/%E3%82%88%E3%81%86%E3%81%AB%E3%81%84%E3%81%AE%E3%82%8B', '/grammar_points/%E3%81%9F%E3%81%B0%E3%81%8B%E3%82%8A', '/grammar_points/%E5%8C%96%E3%81%99%E3%82%8B', '/grammar_points/%E5%91%BD%E4%BB%A4%E5%BD%A2', '/grammar_points/%E3%82%88%E3%81%86%E3%81%AB', '/grammar_points/%E3%81%8B%E3%81%97%E3%82%89', '/grammar_points/%E3%82%89%E3%81%97%E3%81%842', '/grammar_points/%E3%81%AB%E3%81%BF%E3%81%88%E3%82%8B', '/grammar_points/%E3%81%A8%E3%81%BF%E3%81%88%E3%82%8B', '/grammar_points/%E9%A2%A8', '/grammar_points/%E3%81%8C%E3%81%BF%E3%82%89%E3%82%8C%E3%82%8B', '/grammar_points/%E3%81%AB%E3%81%8D%E3%81%8C%E3%81%A4%E3%81%8F', '/grammar_points/%E3%81%A7%E3%82%82-%E3%81%A7%E3%82%82', '/grammar_points/%E3%81%9D%E3%82%8C%E3%81%AB', '/grammar_points/%E3%81%9D%E3%82%8C%E3%81%A7', '/grammar_points/question-phrase-%E3%81%8B', '/grammar_points/%E3%81%9D%E3%82%8C%E3%81%A7%E3%82%82', '/grammar_points/%E3%81%9F%E3%82%89%E3%81%A9%E3%81%86', '/grammar_points/%E3%81%A8%E3%81%8B%E3%82%93%E3%81%8C%E3%81%88%E3%82%89%E3%82%8C%E3%81%A6%E3%81%84%E3%82%8B', '/grammar_points/%E3%81%A8%E3%81%95%E3%82%8C%E3%81%A6%E3%81%84%E3%82%8B', '/grammar_points/%E3%81%A8%E3%81%84%E3%82%8F%E3%82%8C%E3%81%A6%E3%81%84%E3%82%8B', '/grammar_points/%E3%81%B0%E3%82%88%E3%81%8B%E3%81%A3%E3%81%9F', '/grammar_points/%E3%81%B0%E3%81%84%E3%81%84', '/grammar_points/%E3%81%9F%E3%82%89%E3%81%84%E3%81%84-%E3%81%A8%E3%81%84%E3%81%84', '/grammar_points/%E4%B8%AD', '/grammar_points/%E3%81%AE%E9%96%93%E3%81%AB', '/grammar_points/%E3%81%86%E3%81%A1%E3%81%AB', '/grammar_points/%E3%81%AA%E3%81%84%E3%81%86%E3%81%A1%E3%81%AB', '/grammar_points/%E3%81%B9%E3%81%8D', '/grammar_points/%E3%81%B9%E3%81%8D%E3%81%A7%E3%81%AF%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%A3%E3%81%A6-slang', '/grammar_points/%E3%81%AA%E3%81%8B%E3%81%AA%E3%81%8B', '/grammar_points/%E3%81%82%E3%81%BE%E3%82%8A', '/grammar_points/%E3%81%AA%E3%81%8B%E3%81%AA%E3%81%8B-%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%AB%E3%82%88%E3%82%8B%E3%81%A8-%E3%81%AB%E3%82%88%E3%82%8C%E3%81%B0', '/grammar_points/%E3%81%AB%E3%82%88%E3%81%A3%E3%81%A6-%E3%81%AB%E3%82%88%E3%82%8B', '/grammar_points/%E5%85%A8%E3%81%8F-%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%93%E3%81%A8%E3%81%A0', '/grammar_points/%E3%81%9D%E3%81%86%E3%81%A0', '/grammar_points/%E3%81%99%E3%82%8B%E3%81%A8', '/grammar_points/%E3%81%9D%E3%81%86%E3%81%99%E3%82%8B%E3%81%A8', '/grammar_points/%E3%81%AE%E3%81%AFx%E3%81%AE%E6%96%B9%E3%81%A0', '/grammar_points/noun-%E5%9E%8B', '/grammar_points/%E3%81%A6%E3%81%94%E3%82%89%E3%82%93', '/grammar_points/particle-%E3%81%AE', '/grammar_points/%E3%81%A7%E3%81%82%E3%82%8B', '/grammar_points/%E3%81%A8%E3%81%93%E3%82%8D%E3%81%8C', '/grammar_points/%E3%81%A8%E3%81%93%E3%82%8D%E3%81%A7', '/grammar_points/%E3%81%BB%E3%81%A9', '/grammar_points/%E3%81%B0-%E3%81%BB%E3%81%A9', '/grammar_points/%E3%81%BB%E3%81%A9%EF%BD%9E%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%A7%E3%81%AF-%E3%81%9D%E3%82%8C%E3%81%A7%E3%81%AF-%E3%81%98%E3%82%83%E3%81%82', '/grammar_points/%E3%81%AE%E3%81%AB', '/grammar_points/%E3%81%9F%E3%82%81-%E3%81%AB', '/grammar_points/%E3%81%9F%E3%82%81%E3%81%AB', '/grammar_points/%E3%81%A8%E3%81%84%E3%81%86-called', '/grammar_points/%E3%81%A8%E3%81%84%E3%81%86%E3%81%93%E3%81%A8%E3%81%A0', '/grammar_points/%E3%81%A8%E3%81%84%E3%81%86%E3%81%AE%E3%81%AF', '/grammar_points/%E7%9A%84', '/grammar_points/%E3%82%82%E3%81%AE-%E3%82%82%E3%82%93', '/grammar_points/%E3%82%82%E3%81%AE%E3%81%A0', '/grammar_points/%E6%9C%80%E4%B8%AD%E3%81%AB', '/grammar_points/%E4%B8%8A%E3%81%A7', '/grammar_points/%E3%81%8A%E3%81%8B%E3%81%92%E3%81%A7', '/grammar_points/%E3%81%AB%E3%82%82%E3%81%A8%E3%81%A5%E3%81%84%E3%81%A6', '/grammar_points/%E7%82%B9', '/grammar_points/%E3%81%AA%E3%81%9C%E3%81%AA%E3%82%89-%E3%81%8B%E3%82%89', '/grammar_points/%E3%81%93%E3%81%9D', '/grammar_points/%E3%81%8B%E3%82%89%E3%81%93%E3%81%9D', '/grammar_points/%E3%81%B0%E3%81%8B%E3%82%8A', '/grammar_points/%E3%81%B0%E3%81%8B%E3%82%8A%E3%81%A0', '/grammar_points/%E3%81%B0%E3%81%8B%E3%82%8A%E3%81%AB', '/grammar_points/%E3%81%93%E3%81%A8%E3%81%8C%E3%81%82%E3%82%8B', '/grammar_points/%E3%81%93%E3%81%A8%E3%81%AB%E3%81%99%E3%82%8B', '/grammar_points/%E3%81%93%E3%81%A8%E3%81%AA%E3%81%AE', '/grammar_points/%E3%81%93%E3%81%A8%E3%81%AB%E3%81%AA%E3%82%8B', '/grammar_points/%E3%81%AF-%E3%81%A7%E6%9C%89%E5%90%8D', '/grammar_points/%E3%81%93%E3%81%A8%E3%81%AF%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%A8%E8%A8%80%E3%81%A3%E3%81%A6%E3%82%82', '/grammar_points/%E3%81%A8%E3%81%84%E3%81%88%E3%81%B0', '/grammar_points/%E5%90%88%E3%81%86', '/grammar_points/%E3%81%AB%E5%90%88%E3%82%8F%E3%81%9B%E3%81%A6-%E3%81%AB%E5%90%88%E3%81%A3%E3%81%9F', '/grammar_points/%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6', '/grammar_points/%E3%81%AE%E5%A7%BF', '/grammar_points/%E3%81%A8%E8%A8%80%E3%81%88%E3%82%8B', '/grammar_points/%E3%81%A1%E3%82%83%E3%82%93%E3%81%A8-%E3%81%8D%E3%81%A1%E3%82%93%E3%81%A8', '/grammar_points/%E3%81%9D%E3%81%AE%E3%81%9F%E3%82%81-%E3%81%AB', '/grammar_points/%E3%81%9D%E3%81%AE%E7%B5%90%E6%9E%9C', '/grammar_points/%E

In [ ]:
def extract_text(ex: str, example=False):
    ###
    # RETURNS: a 2d-array containing all sentence segments - in the format [[kanji, furigana, hira, grammar_char], [kanji, furigana, hira, grammar_char], ...]
    #          either kanji and furigana are None when the segment is hira text, and hira is None when the segment is a kanji word with furigana

    text = []
    tag_starts = [m.start() for m in re.finditer('<', ex)]
    tag_closes = [m.start() for m in re.finditer('>', ex)]
    word = ''
    furigana = ''
    hira = ''
    find_text = False

    for i in range(len(tag_starts)-1):
        current_text = [None, None, None, None]
        current_tag = ex[tag_starts[i]+1:tag_closes[i]]

        if example: # get the start and end indeces of grammar point characters in current example
            if 'text-primary-accent' in current_tag:
                find_text = True # look for next text to assign as a grammar character
            if '/span' in current_tag and find_text: # if the grammar character styling tag has finished, stop assigning text as grammar character
                find_text = False

        if current_tag == 'ruby': # upcoming word has furigana attached
            word = ex[tag_closes[i]+1:tag_starts[i+1]]
        elif current_tag == 'rt':
            furigana = ex[tag_closes[i]+1:tag_starts[i+1]]
            current_text[0] = word # append the kanji and furigana after furigana appears
            current_text[1] = furigana
            if find_text:
                current_text[3] = True

            word = '' # reset these for new kanji word and furigana
            furigana = ''
        else:
            if not current_tag == 'rp': # rp is a tag that is only used around parentheses so do not need it
                hira = ex[tag_closes[i]+1:tag_starts[i+1]] # regular hiragana text appears

                if not hira == '' and not hira == '\n': # all tags produce some text, even if it is empty, so filter it out
                    current_text[2] = hira
                    if find_text:
                        current_text[3] = True



        if not all(x is None for x in current_text):
            text.append(current_text) 
          
    return text

In [ ]:
for url in tqdm(grammar_points_list):
    
    full_url = BASE_URL + url
    # full_url = "https://bunpro.jp/grammar_points/%E3%82%92"
    # full_url = "https://bunpro.jp/grammar_points/%E8%81%9E%E3%81%93%E3%81%88%E3%82%8B"
    page_data = requests.get(full_url)

    soup = BeautifulSoup(page_data.text, "html.parser")

    # TODO: FILL IN GRAMMAR POINT INFORMATION AND ADD TO grammar_data_df
    # USE THAT ID FOR examples_df ENTRIES

    level = soup.find("p", {"class": "text-primary-contrast md:text-primary-fg"})
    level = str(level.text)[1:2]

    grammar_point_jp = soup.find("span", {"class": "bp-ddw undefined"})
    grammar_point_jp = extract_text(str(grammar_point_jp))

    meaning_en = soup.find("span", {"class": "mt-4 block text-body text-primary-contrast md:text-subtitle md:text-primary-fg"})
    meaning_en = meaning_en.text

    description = soup.find("div", {"class": "bp-ddw bp-writeup-body prose"})
    description = extract_text(str(description))

    grammar_data = {"level": level, "grammar_point_jp": grammar_point_jp, "meaning_en": meaning_en, "description": description}

    grammar_data_df.loc[len(grammar_data_df)] = grammar_data

[[None, None, 'For the most part, '], [None, None, 'だ'], [None, None, " is the equivalent of 'is' in English. Its role is to strongly express determination or assertion. It is a casual grammar structure, which means that you won't see it in polite sentences."], [None, None, 'Technically, '], [None, None, 'だ'], [None, None, ' is an '], [None, None, 'auxiliary verb'], [None, None, ', a group of words that attach themselves to other words to give them meaning. '], [None, None, 'です'], [None, None, ' has the same role as '], [None, None, 'だ'], [None, None, ', but '], [None, None, 'です'], [None, None, ' is the one that will be used in polite sentences, and is also one of the first Japanese grammar patterns many people are exposed to.'], [None, None, 'だ'], [None, None, ' will always follow nouns, or words that behave like nouns, such as '], [None, None, 'な-Adjectives'], [None, None, '.'], [None, None, 'Caution'], [None, None, 'だ'], [None, None, ' should never be attached to the end of '], [None, None, 'い-Adjectives'], [None, None, '. In these cases, it is considered more correct to attach a polite equivalent, like '], [None, None, 'です'], [None, None, '.'], [None, None, 'Caution'], [None, None, 'While '], [None, None, 'だ'], [None, None, " is often thought of as the 'casual form' of "], [None, None, 'です'], [None, None, ', that is actually not entirely true. '], [None, None, 'です'], [None, None, ' is a '], [None, None, 'polite speech'], [None, None, " word. The official 'formal version' of "], [None, None, 'だ'], [None, None, ' is '], [None, None, 'である'], [None, None, '. We will learn this grammar point a bit later. '], [None, None, 'である'], [None, None, ' can often be seen in articles, and formal writing, while '], [None, None, 'です'], [None, None, ' is more common in '], [None, None, 'polite speech'], [None, None, '.']]
[[None, None, 'Similarly to '], [None, None, 'だ'], [None, None, ', '], [None, None, 'です'], [None, None, ' is an '], [None, None, 'auxiliary verb'], [None, None, " that is an expression of determination or assertion. It states that something 'is' a certain way. "], [None, None, 'です'], [None, None, ' is considered to be the polite variation of '], [None, None, 'だ'], [None, None, '. Keep in mind though that although their roles are similar, both '], [None, None, 'だ'], [None, None, ' and '], [None, None, 'です'], [None, None, ' are standalone structures.'], [None, None, 'です'], [None, None, ' connects to words in exactly the same way as '], [None, None, 'だ'], [None, None, ', but is also regularly seen attached to the end of '], [None, None, 'い-Adjectives'], [None, None, '.'], [None, None, 'Caution'], [None, None, 'Although '], [None, None, 'です'], [None, None, ' is regularly attached to the end of '], [None, None, 'い-Adjectives'], [None, None, ', some may actually consider this incorrect Japanese, and it should not be used in formal writing. In daily spoken language/texting, however, it is completely normal.'], [None, None, 'The above example technically should not be used in formal writing. Despite this, in recent years, it is starting to become the norm.']]
[[None, None, 'は'], [None, None, ' (pronounced わ) is often considered to be one of the most difficult particles to master in Japanese, alongside '], [None, None, 'が'], [None, None, '. '], [None, None, 'は'], [None, None, ' marks the topic of the sentence, and describes the whole sentence broadly. However, '], [None, None, 'が'], [None, None, ' primarily marks single actions or statements. We will explore this distinction in more detail when covering '], [None, None, 'が'], [None, None, '.'], [None, None, 'In many sentences (especially short ones), either '], [None, None, 'は'], [None, None, ' or '], [None, None, 'が'], [None, None, ' would be considered perfectly natural. This depends on whether someone is simply stating something ('], [None, None, 'は'], [None, None, '), or highlighting it especially ('], [None, None, 'が'], [None, None, ').'], [None, None, ' '], [None, None, 'In the first sentence, '], [None, None, 'は'], [None, None, ' broadly describes what the sentence is about (curry). In the second sentence, '], [None, None, 'は'], [None, None, " again describes the whole sentence being about 'me', but "], [None, None, 'が'], [None, None, ' highlights one specific piece of information (wine being the thing that is hated).'], [None, None, 'Caution'], [None, None, 'は'], [None, None, " cannot be used to describe things that you are seeing or experiencing 'in the moment' (right now). This is due to 'in the moment' events being considered part of a larger experience (your whole day for example)."], [None, None, 'Caution'], [None, None, 'は'], [None, None, " has 2 main functions. The first marks the topic of the sentence, the second is used for contrast or making comparisons. Although there are no 'strict' rules for this, when "], [None, None, 'は'], [None, None, ' is used toward (or after) the middle of a sentence, it will usually have the nuance of contrast.'], [None, None, 'In the second sentence, '], [None, None, 'は'], [None, None, ' will give the listener the impression that there is a comparison being made.']]
[[None, None, 'も'], [None, None, " can mean 'too/also', or 'even', or 'neither/either', depending on if the sentence is affirmative or negative. Multiple meanings like this are quite common for Japanese particles, as there is no need to use different words simply to agree with other statements in the sentence (unlike English)."], [None, None, "As you can see here, English requires 'either/neither (when negative)', or 'too/also', but Japanese only requires "], [None, None, 'も'], [None, None, ". You can think of it as simply meaning 'Whatever is true for (A), is also true for (B)'."], [None, None, 'も'], [None, None, ' is part of many other compound grammar structures in which it keeps its original meaning, but shifts the nuance a little bit. Some of these include '], [None, None, 'でも'], [None, None, ', '], [None, None, 'にも～ない'], [None, None, ', '], [None, None, 'とも'], [None, None, '. As we can see, it is frequently paired with other particles!'], [None, None, 'Here, '], [None, None, 'も'], [None, None, ' can be seen pairing with '], [None, None, 'で'], [None, None, ". This suggests that 'With (A), (B) also'. This is regularly translated simply as 'but' in English, despite the nuance being closer to 'and also'."]]
[[None, None, 'これ'], [None, None, " is often thought to be equal to 'this' in English, which is basically correct. "], [None, None, 'これ'], [None, None, ' will always be used to highlight something that is close to the speaker either emotionally, or physically.'], [None, None, "Despite being translated as a '"], [None, None, 'pronoun'], [None, None, "' in English, it might be easier to think of "], [None, None, 'これ'], [None, None, ' as a '], [None, None, 'substitute noun'], [None, None, ' (the literal meaning in Japanese), as this is always its function. '], [None, None, 'これ'], [None, None, ' substitutes for something that has its own name, but is not required in the context of the sentence, or is simply unknown by the speaker.']]
[[None, None, 'Just like '], [None, None, 'これ'], [None, None, ', '], [None, None, 'それ'], [None, None, ' is considered to be a '], [None, None, 'pronoun'], [None, None, ' in Japanese (more accurately it is a '], [None, None, 'substitute noun'], [None, None, '). '], [None, None, 'それ'], [None, None, " translates roughly to 'that' and highlights something that is closer to the listener (physically or emotionally) than the speaker."], [None, None, 'In these sentences, we can see '], [None, None, 'それ'], [None, None, ' highlighting things that the speaker is identifying as being closer to the listener, or about the listener.'], [None, None, 'それ'], [None, None, ' is also used to point back to things that have been mentioned previously in the conversation. This can be something that was said earlier within the same sentence, or something that someone else said.']]
[[None, None, 'あれ'], [None, None, ', just like '], [None, None, 'これ'], [None, None, ' and '], [None, None, 'それ'], [None, None, ", is one of several 'pronoun-like' words in Japanese ("], [None, None, 'substitute nouns'], [None, None, '). '], [None, None, 'あれ'], [None, None, " translates roughly to 'that' in English. However, unlike "], [None, None, 'それ'], [None, None, ', '], [None, None, 'あれ'], [None, None, " is used to highlight things that are away from both the speaker and the listener. Due to this, it is also often translated as 'that over there'."], [None, None, 'Caution'], [None, None, 'Be careful not to mix up '], [None, None, 'あれ'], [None, None, " with the common spoken expression あれ, which means 'huh?', or 'oh?'. These are not the same words. The difference will usually be clear from context within a sentence, and the way the word is said. あれ as 'huh?' has a rising tone, and sounds like a question."]]
[[None, None, 'From the perspective of English, '], [None, None, 'の'], [None, None, " has several different meanings. It can indicate possession, like putting (A)'s on the end of a word. In Japanese, however, the meaning is a bit broader, and shows that (B) is an attribute/possession of (A)."], [None, None, 'In the first sentence, we can see that '], [None, None, 'の'], [None, None, ' is showing ownership, however in the second sentence, it is simply showing a relationship between (A) and (B).'], [None, None, 'の'], [None, None, ' is also often used in the same way as '], [None, None, 'が'], [None, None, ', to highlight the subject of a statement. Our lesson for '], [None, None, 'が'], [None, None, ' will be covered separately.'], [None, None, "\n\nBoth of these examples are slightly advanced and use adjectives, but don't worry, we will be covering them next!"], [None, None, 'Caution'], [None, None, 'の'], [None, None, ' is usually used after nouns, but can also be used after other types of words, specifically when it is transforming them into a noun-like phrase. This is called '], [None, None, 'nominalization'], [None, None, ' in English. We will cover this in detail in the '], [None, None, 'の - Nominalization'], [None, None, ' grammar point.']]
[[None, None, 'いい'], [None, None, " is an adjective that means 'good' in Japanese. It can be a little bit difficult to use at first, as it conjugates differently to other "], [None, None, 'い-Adjectives'], [None, None, '.'], [None, None, 'In these sentences, we can see that the first い in '], [None, None, 'いい'], [None, None, ' changes to よ, depending on the form. This is unique to '], [None, None, 'いい'], [None, None, ', and does not happen with other adjectives.'], [None, None, 'いい'], [None, None, ' can sometimes be seen as '], ['良', 'よ', None], [None, None, 'い'], [None, None, ', in these cases, the kanji is likely to be read as よい, and not いい. There is technically no difference between these two meanings, but '], [None, None, 'よい'], [None, None, ' does sound more formal/old-fashioned.'], [None, None, 'Caution'], [None, None, 'When used as an adverb, よく should not be confused as a conjugation of '], [None, None, 'いい'], [None, None, '. よく has several possible kanji that it may stem from, and means frequently/often/well.']]
[[None, None, 'In Japanese, '], [None, None, 'い-Adjectives'], [None, None, " are known as 'form containing words', and are used to describe nouns. All "], [None, None, 'い-Adjectives'], [None, None, ' end in い in their base form.'], [None, None, ' '], [None, None, 'As mentioned, all '], [None, None, 'い-Adjectives'], [None, None, ' end in い in their base form. However, not all words ending in い are '], [None, None, 'い-Adjectives'], [None, None, ". Let's take a look at some of the words that are commonly mistaken for "], [None, None, 'い-Adjectives'], [None, None, '.'], [None, None, 'In addition to きらい above, there is also きれい. きれい actually comes from the kanji structure '], ['綺麗', 'きれい', None], [None, None, ', with い being part of the kanji itself. This is never the case with '], [None, None, 'い-Adjectives'], [None, None, ', where the い will always be outside of the kanji. Due to the kanji for '], ['綺麗', 'きれい', None], [None, None, ' being somewhat difficult, this word is often written in hiragana or katakana, which leads to confusion for learners. Unfortunately there is no rule for distinguishing which words ending in い are not '], [None, None, 'い-Adjectives'], [None, None, ", but thankfully, there are not very many of them, so it won't be long before you become familiar with them."], [None, None, 'Caution'], [None, None, 'Unlike '], [None, None, 'な-Adjectives'], [None, None, ', '], [None, None, 'い-Adjectives'], [None, None, ' must never be followed by '], [None, None, 'だ'], [None, None, '. This is due to '], [None, None, 'だ'], [None, None, ' only being able to conjugate with nouns (which '], [None, None, 'な-Adjectives'], [None, None, ' originally are). Instead, '], [None, None, 'です'], [None, None, ' is used with '], [None, None, 'い-Adjectives'], [None, None, ' to make them sound more polite.'], [None, None, 'Fun Fact'], [None, None, 'Although using '], [None, None, 'です'], [None, None, ' with '], [None, None, 'い-Adjectives'], [None, None, ' is very common, it is actually incorrect Japanese. As '], [None, None, 'です'], [None, None, ' is simply a polite variation of '], [None, None, 'だ'], [None, None, ', it follows all of the same conjugation rules as '], [None, None, 'だ'], [None, None, '. This means that it should only be attached to nouns and '], [None, None, 'な-Adjectives'], [None, None, '. However, as most Japanese natives do not know this rule, it is widely considered natural to use.']]
[[None, None, 'In Japanese, the vast majority of '], [None, None, 'な-Adjectives'], [None, None, ' are originally nouns, and differ from nouns only in that they have their own set of conjugation rules. The dictionary form of a '], [None, None, 'な-Adjective'], [None, None, ' will always be followed by '], [None, None, 'だ'], [None, None, '. な is only attached when describing another noun.'], [None, None, 'As we can see from these examples, '], [None, None, 'だ'], [None, None, ' or '], [None, None, 'です'], [None, None, ' is required at the end of a sentence, but な will be required when using a '], [None, None, 'な-Adjective'], [None, None, ' to describe a noun.'], [None, None, 'な-Adjectives'], [None, None, ' are mostly words of foreign (Chinese/English) origin. This is why they have evolved to require unique conjugation rules.'], [None, None, 'Fun Fact'], [None, None, 'As a learner, it can be very difficult to identify what a '], [None, None, 'な-Adjective'], [None, None, ' is, compared to a regular noun. Nouns conjugate with '], [None, None, 'の'], [None, None, ', while '], [None, None, 'な-Adjectives'], [None, None, ' conjugate with な. A very simple trick that Japanese children learn is using the adverb '], [None, None, 'とても'], [None, None, " 'very'. If "], [None, None, 'とても'], [None, None, ' sounds natural with a word, then it is probably a '], [None, None, 'な-Adjective'], [None, None, ', if it sounds unnatural, then the word is likely to be a regular noun.'], [None, None, 'From this example, we can see that '], [None, None, 'とても'], [None, None, ' can be used to help identify '], [None, None, 'な-Adjectives'], [None, None, ". Basically, this is due to adjectives being measurable 'very big', 'very small', while nouns are not measurable 'very dog', 'very boat'."]]
[[None, None, 'か'], [None, None, ' is a particle that frequently comes at the end of sentences in Japanese, and carries the same meaning as a question mark in English. (It is not limited to appearing at the end of sentences, however). In addition to questions, '], [None, None, 'か'], [None, None, ' can also express uncertainty about something, without strictly being a question.'], [None, None, 'か'], [None, None, ' regularly comes after the polite form of words, such as ～'], [None, None, 'です'], [None, None, 'か'], [None, None, ', ～ます'], [None, None, 'か'], [None, None, '. However, in casual conversation, '], [None, None, 'か'], [None, None, ' can be used directly after the word that the speaker is showing uncertainty about.'], [None, None, 'Both examples are grammatically correct, but the sentence without '], [None, None, 'です'], [None, None, ' may be considered rude by some people (as it sounds too familiar/direct).']]
[[None, None, 'が'], [None, None, ' is considered to be the subject marker in Japanese. This means that it marks someone or something that is performing an action, or it identifies someone or something as having a specific feature (this is usually a feature that the listener is not aware of).'], [None, None, 'In both of these sentences, '], [None, None, 'が'], [None, None, ' puts focus on the thing performing an action/existing in some way (as opposed to any other thing). Because of this, '], [None, None, 'が'], [None, None, ' is usually said to highlight what comes before it, while '], [None, None, 'は'], [None, None, ' highlights what comes after it.'], [None, None, 'が'], [None, None, " always shows the 'target' of a statement, when other targets also exist. This is why "], [None, None, 'が'], [None, None, " is used to describe situations that are happening either 'in the moment', or 'individually of other things'."], [None, None, "Because the group in this sentence is only one group out of many possible 'groups of people' that could be described, "], [None, None, 'が'], [None, None, ' will be used.'], [None, None, 'Caution'], [None, None, 'が'], [None, None, " is not usually used to describe something about yourself, unless you are intentionally describing yourself compared to other people. If you want to talk about yourself 'in general terms', "], [None, None, 'は'], [None, None, ' will sound more natural (there are exceptions).']]
[[None, None, 'よ'], [None, None, ' is classified as a '], [None, None, 'sentence ending particle'], [None, None, ' in Japanese. In most cases, it is used to convey new information to the listener, or just to add a bit of emphasis. Like most sentence ending particles, it is simply added to the end of almost any sentence.'], [None, None, 'Despite the standard use of '], [None, None, 'よ'], [None, None, ' being to convey new information, it is also very regularly paired with '], [None, None, 'ね'], [None, None, ", to convey the meaning of 'right?!'. This more literally means something closer to 'I think (A), and I bet you think (A) too!'."], [None, None, 'Caution'], [None, None, 'Did you notice that there is a '], [None, None, 'だ'], [None, None, ' after the noun, but not the '], [None, None, 'い-Adjective'], [None, None, '? This is not a unique rule for '], [None, None, 'よ'], [None, None, ', but just one of the regular conjugation rules introduced in the lessons for '], [None, None, 'い-Adjectives'], [None, None, ' and '], [None, None, 'な-Adjectives'], [None, None, '. It is also acceptable to use '], [None, None, 'です'], [None, None, 'よ'], [None, None, ' after either type of adjective (or noun).']]

In [47]:
grammar_data_df['page_url'] = grammar_points_list

In [48]:
grammar_data_df.to_csv('grammar_points.csv', encoding='utf-16', header=False)

In [86]:
df = pd.read_csv('grammar_points.csv', encoding='utf-16', index_col=0, names=["level", "grammar_point_jp", "meaning_en", "description", "page_url"])

examples_df = pd.DataFrame(columns=["grammar_id", "text", "grammar_char_locations"])

def get_grammar_char_locs(text: list):
    locs = []
    char_index = 0
    scan = False
    for i in range(len(text)):
        if text[i][3] is not None:
            if not scan:
                scan = True
                current_loc = []
                current_loc.append(char_index)
        else:
            if scan:
                scan = False
                current_loc.append(char_index)
                locs.append(current_loc)

        if text[i][0] is not None:
            char_index += len(text[i][0])
        else:
            char_index += len(text[i][2])
    if len(current_loc) == 1: # in case text ends with the grammar characters, add the end index manually
        current_loc.append(char_index)
        locs.append(current_loc)    
    
    return locs

In [88]:
print(df)
for rec in tqdm(range(len(df))):
    url = BASE_URL + df.loc[rec]['page_url']
    grammar_id = df.index[rec]

    page_data = requests.get(url)

    soup = BeautifulSoup(page_data.text, "html.parser")
    
    for ex in soup.find_all("p", {"class": "bp-ddw prose text-large md:text-subtitle"}):
        text = extract_text(str(ex), example=True) 
        print(text)
        grammar_char_locations = get_grammar_char_locs(text)
        data = {"grammar_id": grammar_id, "text": text, "grammar_char_locations": grammar_char_locations}
        examples_df.loc[len(examples_df)] = data

    level         grammar_point_jp  \
0       5      [[None, None, 'だ']]
1       5     [[None, None, 'です']]
2       5      [[None, None, 'は']]
3       5      [[None, None, 'も']]
4       5     [[None, None, 'これ']]
..    ...                      ...
933     o    [[None, None, 'かろう']]
934     o     [[None, None, 'やや']]
935     o   [[None, None, 'いずれも']]
936     o  [[None, None, 'あわよくば']]
937     o     [[None, None, 'むず']]

                                            meaning_en  \
0                                            To be, Is
1                                            To be, Is
2                As for... (Highlights sentence topic)
3            Also, Too, As well, Even, Either, Neither
4                                                 This
..                                                 ...
933                                   Probably, Right?
934                 A little bit, Marginally, Slightly
935  All (positive), None (negative), Both, Whateve...
936  If luck is on my side, If the time is right, I...
937                         Shall, Isn't it?, I wonder

                                           description  \
0    [[None, None, 'For the most part, '], [None, N...
1    [[None, None, 'Similarly to '], [None, None, '...
2    [[None, None, 'は'], [None, None, ' (pronounced...
3    [[None, None, 'も'], [None, None, " can mean 't...
4    [[None, None, 'これ'], [None, None, " is often t...
..                                                 ...
933  [[None, None, 'かろう is an old-fashioned grammar...
934  [[None, None, 'やや is an adverb in Japanese tha...
935  [[None, None, 'いずれ is a formal adverb commonly...
936  [[None, None, "あわよくば is a combination of the o...
937  [[None, None, "むず is a combination and abbrevi...

                                              page_url
0                            /grammar_points/%E3%81%A0
1                   /grammar_points/%E3%81%A7%E3%81%99
2                            /grammar_points/%E3%81%AF
3                            /grammar_points/%E3%82%82
4                   /grammar_points/%E3%81%93%E3%82%8C
..                                                 ...
933        /grammar_points/%E3%81%8B%E3%82%8D%E3%81%86
934                 /grammar_points/%E3%82%84%E3%82%84
935  /grammar_points/%E3%81%84%E3%81%9A%E3%82%8C%E3...
936  /grammar_points/%E3%81%82%E3%82%8F%E3%82%88%E3...
937                 /grammar_points/%E3%82%80%E3%81%9A

[938 rows x 5 columns]

  0%|          | 1/938 [00:00<08:10,  1.91it/s]

[['私', 'わたし', None, None], [None, None, 'だ', True], [None, None, '。', None]]
[['本', 'ほん', None, None], [None, None, 'だ', True], [None, None, '。', None]]
[['猫', 'ねこ', None, None], [None, None, 'だ', True], [None, None, '。', None]]
[['学生', 'がくせい', None, None], [None, None, 'だ', True], [None, None, '。', None]]
[['綺麗', 'きれい', None, None], [None, None, 'だ', True], [None, None, '。', None]]

  0%|          | 2/938 [00:01<08:08,  1.91it/s]

[[None, None, 'あなた', None], [None, None, 'です', True], [None, None, '。', None]]
[[None, None, 'ペン', None], [None, None, 'です', True], [None, None, '。', None]]
[[None, None, 'さくら', None], [None, None, 'です', True], [None, None, '。', None]]
[['友達', 'ともだち', None, None], [None, None, 'です', True], [None, None, '。', None]]
[['暑', 'あつ', None, None], [None, None, 'い', None], [None, None, 'です', True], [None, None, '。', None]]

  0%|          | 3/938 [00:01<08:10,  1.91it/s]

[['私', 'わたし', None, None], [None, None, 'は', True], [None, None, 'トム', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'あなた', None], [None, None, 'は', True], [None, None, 'ジム', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'トム', None], [None, None, 'は', True], ['先生', 'せんせい', None, None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'カバン', None], [None, None, 'は', True], ['汚', 'きたな', None, None], [None, None, 'い', None], [None, None, '。', None]]
[[None, None, 'カレンダー', None], [None, None, 'は', True], ['必要', 'ひつよう', None, None], [None, None, 'です', None], [None, None, '。', None]]

  0%|          | 4/938 [00:02<08:16,  1.88it/s]

[[None, None, 'あなた', None], [None, None, 'も', True], [None, None, 'トム', None], [None, None, 'です', None], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'も', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'も', True], ['先生', 'せんせい', None, None], [None, None, 'です', None], [None, None, '。', None]]
[['服', 'ふく', None, None], [None, None, 'も', True], ['古', 'ふる', None, None], [None, None, 'い', None], [None, None, '。', None]]
[['君', 'きみ', None, None], [None, None, 'も', True], [None, None, '、', None], ['忙', 'いそが', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, '。', None]]

  1%|          | 5/938 [00:02<08:21,  1.86it/s]

[[None, None, 'これ', True], [None, None, 'は', None], [None, None, 'ペン', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'これ', True], [None, None, 'は', None], ['本', 'ほん', None, None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'これ', True], [None, None, 'は', None], ['寿司', 'すし', None, None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'これ', True], [None, None, 'も', None], ['寿司', 'すし', None, None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'これ', True], [None, None, 'は', None], [None, None, '、', None], ['海', 'うみ', None, None], [None, None, 'です', None], [None, None, '。', None]]

  1%|          | 6/938 [00:03<08:22,  1.86it/s]

[[None, None, 'それ', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'それ', True], [None, None, 'も', None], [None, None, 'エアコン', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'それ', True], [None, None, 'は', None], ['本', 'ほん', None, None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'それ', True], [None, None, 'も', None], ['本', 'ほん', None, None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'それ', True], [None, None, 'は', None], [None, None, '、', None], ['水', 'みず', None, None], [None, None, 'です', None], [None, None, '。', None]]

  1%|          | 7/938 [00:03<08:25,  1.84it/s]

[[None, None, 'あれ', True], [None, None, 'は', None], ['何', 'なに', None, None], [None, None, '？', None]]
[[None, None, 'あれ', True], [None, None, 'は', None], [None, None, 'コンビニ', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'あれ', True], [None, None, 'は', None], [None, None, 'ホテル', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'あれ', True], [None, None, 'は', None], [None, None, '、', None], ['電車', 'でんしゃ', None, None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'あれ', True], [None, None, 'は', None], [None, None, '、', None], ['兄', 'あに', None, None], [None, None, 'です', None], [None, None, '。', None]]

  1%|          | 8/938 [00:04<08:34,  1.81it/s]

[[None, None, 'あれ', None], [None, None, 'は', None], ['私', 'わたし', None, None], [None, None, 'の', True], [None, None, 'ペン', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'も', None], ['私', 'わたし', None, None], [None, None, 'の', True], [None, None, 'ペン', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'は', None], ['私', 'わたし', None, None], [None, None, 'の', True], ['猫', 'ねこ', None, None], [None, None, 'です', None], [None, None, '。', None]]
[['先生', 'せんせい', None, None], [None, None, 'の', True], ['傘', 'かさ', None, None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'あなた', None], [None, None, 'の', True], ['名前', 'なまえ', None, None], [None, None, 'は', None], [None, None, '？', None]]

  1%|          | 9/938 [00:04<08:52,  1.74it/s]

[[None, None, 'いい', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'は', None], [None, None, 'いい', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'は', None], [None, None, 'いい', True], ['本', 'ほん', None, None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'も', None], [None, None, 'いい', True], ['本', 'ほん', None, None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'は', None], [None, None, 'いい', True], ['音', 'おと', None, None], [None, None, 'だ', None], [None, None, '。', None]]

  1%|          | 10/938 [00:05<08:42,  1.77it/s]

[['暑', 'あつ', None, True], [None, None, 'い', True], [None, None, 'です', None], [None, None, '。', None]]
[['今日', 'きょう', None, None], [None, None, 'は', None], ['暑', 'あつ', None, True], [None, None, 'いです', True], [None, None, '。', None]]
[['寒', 'さむ', None, True], [None, None, 'いです', True], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'は', None], ['楽', 'たの', None, True], [None, None, 'しいです', True], [None, None, '。', None]]
[['新', 'あたら', None, True], [None, None, 'しい', True], ['車', 'くるま', None, None], [None, None, '。', None]]

  1%|          | 11/938 [00:06<08:44,  1.77it/s]

[['綺麗', 'きれい', None, None], [None, None, 'な', True], ['絵', 'え', None, None], [None, None, '。', None]]
[['綺麗', 'きれい', None, None], [None, None, 'な', True], ['女', 'おんな', None, None], [None, None, 'の', None], ['人', 'ひと', None, None], [None, None, '。', None]]
[['暇', 'ひま', None, True], [None, None, 'な', True], ['一日', 'いちにち', None, None], [None, None, '。', None]]
[['静', 'しず', None, True], [None, None, 'かな', True], ['部屋', 'へや', None, None], [None, None, '。', None]]
[[None, None, 'あれ', None], [None, None, 'は', None], ['綺麗', 'きれい', None, True], [None, None, 'です', True], [None, None, '。', None]]

  1%|▏         | 12/938 [00:06<08:34,  1.80it/s]

[[None, None, 'これ', None], [None, None, 'は', None], ['本', 'ほん', None, None], [None, None, 'です', None], [None, None, 'か', True], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'は', None], [None, None, 'あなた', None], [None, None, 'の', None], ['本', 'ほん', None, None], [None, None, 'です', None], [None, None, 'か', True], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'も', None], [None, None, 'あなた', None], [None, None, 'の', None], ['本', 'ほん', None, None], [None, None, 'です', None], [None, None, 'か', True], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'は', None], [None, None, 'ペン', None], [None, None, 'です', None], [None, None, 'か', True], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'は', None], [None, None, 'いい', None], [None, None, 'です', None], [None, None, 'か', True], [None, None, '。', None]]

  1%|▏         | 13/938 [00:07<10:11,  1.51it/s]

[[None, None, 'お', None], ['茶', 'ちゃ', None, None], [None, None, 'が', True], ['冷', 'つめ', None, None], [None, None, 'た', None], [None, None, 'い', None], [None, None, 'です', None], [None, None, '。', None]]
[['何', 'なに', None, None], [None, None, 'が', True], [None, None, 'いい', None], [None, None, '？', None]]
[[None, None, 'それ', None], [None, None, 'が', True], [None, None, 'いい', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'カレー', None], [None, None, 'が', True], ['辛', 'から', None, None], [None, None, 'い', None], [None, None, '。', None]]
[['木', 'き', None, None], [None, None, 'が', True], ['高', 'たか', None, None], [None, None, 'い', None], [None, None, '。', None]]

  1%|▏         | 14/938 [00:08<10:36,  1.45it/s]

[[None, None, 'トム', None], [None, None, 'は', None], ['足', 'あし', None, None], [None, None, 'が', None], ['速', 'はや', None, None], [None, None, 'い', None], [None, None, 'よ', True], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], ['背', 'せ', None, None], [None, None, 'が', None], ['高', 'たか', None, None], [None, None, 'い', None], [None, None, 'よ', True], [None, None, '。', None]]
[['野球', 'やきゅう', None, None], [None, None, 'は', None], ['楽', 'たの', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'よ', True], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'は', None], [None, None, 'ケーキ', None], [None, None, 'だ', None], [None, None, 'よ', True], [None, None, '。', None]]
[[None, None, 'それ', None], [None, None, 'は', None], [None, None, 'いい', None], [None, None, 'よ', True], [None, None, '。', None]]

  2%|▏         | 15/938 [00:08<10:34,  1.45it/s]

[[None, None, 'いい', None], [None, None, 'です', None], [None, None, 'ね', True], [None, None, '。', None]]
[['美味', 'おい', None, None], [None, None, 'しい', None], [None, None, 'ね', True], [None, None, '。', None]]
[['寒', 'さむ', None, None], [None, None, 'い', None], [None, None, 'ね', True], [None, None, '！', None]]
[[None, None, 'いい', None], ['質問', 'しつもん', None, None], [None, None, 'です', None], [None, None, 'ね', True], [None, None, '。', None]]
[['自転車', 'じてんしゃ', None, None], [None, None, 'は', None], [None, None, 'いい', None], [None, None, 'ね', True], [None, None, '。︎', None]]

  2%|▏         | 16/938 [00:09<09:55,  1.55it/s]

[['見', 'み', None, None], [None, None, 'る', None], [None, None, ' → ', None], ['見', 'み', None, True], [None, None, 'ます', True]]
[['寝', 'ね', None, True], [None, None, 'る', True], [None, None, ' → ', None], ['寝', 'ね', None, None], [None, None, 'ます', None]]
[['覚', 'おぼ', None, None], [None, None, 'え', None], [None, None, 'る', None], [None, None, ' → ', None], ['覚', 'おぼ', None, True], [None, None, 'えます', True]]
[[None, None, ' ', None], ['食', 'た', None, True], [None, None, 'べる', True], [None, None, ' → ', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'ます', None]]
[['浴', 'あ', None, None], [None, None, 'び', None], [None, None, 'る', None], [None, None, ' → ', None], ['浴', 'あ', None, True], [None, None, 'びます', True]]

  2%|▏         | 17/938 [00:10<09:21,  1.64it/s]

[['聞', 'き', None, None], [None, None, 'く', None], [None, None, ' → ', None], ['聞', 'き', None, True], [None, None, 'きます', True]]
[['座', 'すわ', None, None], [None, None, 'る', None], [None, None, ' → ', None], ['座', 'すわ', None, True], [None, None, 'ります', True]]
[['飲', 'の', None, True], [None, None, 'む', True], [None, None, '→ ', None], ['飲', 'の', None, None], [None, None, 'み', None], [None, None, 'ます', None]]
[['打', 'う', None, True], [None, None, 'つ', True], [None, None, ' → ', None], ['打', 'う', None, None], [None, None, 'ちます', None]]
[['会', 'あ', None, None], [None, None, 'う', None], [None, None, ' → ', None], ['会', 'あ', None, True], [None, None, 'います', True]]

  2%|▏         | 18/938 [00:10<09:35,  1.60it/s]

[['漢字', 'かんじ', None, None], [None, None, 'を', True], ['覚', 'おぼ', None, None], [None, None, 'え', None], [None, None, 'る', None], [None, None, '。', None]]
[['何', 'なに', None, None], [None, None, 'を', True], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'ます', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'バター', None], [None, None, 'を', True], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'る', None], [None, None, '。', None]]
[[None, None, 'スポーツ', None], [None, None, 'を', True], ['見', 'み', None, None], [None, None, 'る', None], [None, None, '。', None]]
[['時計', 'とけい', None, None], [None, None, 'を', True], ['見', 'み', None, None], [None, None, 'る', None], [None, None, '。', None]]

  2%|▏         | 19/938 [00:11<09:52,  1.55it/s]

[['私', 'わたし', None, None], [None, None, 'は', None], ['寝', 'ね', None, True], [None, None, 'ます', True], [None, None, '。', None]]
[['僕', 'ぼく', None, None], [None, None, 'も', None], ['遊', 'あそ', None, True], [None, None, 'びます', True], [None, None, '。', None]]
[[None, None, 'このマッサージは', None], ['効', 'き', None, True], [None, None, 'きます', True], [None, None, '。', None]]
[['母', 'はは', None, None], [None, None, 'は', None], ['映画', 'えいが', None, None], [None, None, 'を', None], ['見', 'み', None, True], [None, None, 'ます', True], [None, None, '。', None]]
[['桜', 'さくら', None, None], [None, None, 'の', None], ['花', 'はな', None, None], [None, None, 'が', None], ['咲', 'さ', None, True], [None, None, 'きます', True], [None, None, '。', None]]

  2%|▏         | 20/938 [00:11<09:23,  1.63it/s]

[['寿司', 'すし', None, None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べない', True], [None, None, '。\n\n', None], ['寿司', 'すし', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'ない', None], [None, None, 'です', None], [None, None, '。', None], ['寿司', 'すし', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べません', None], [None, None, '。', None]]
[[None, None, 'テレビ', None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'ない', None], [None, None, '。', None], [None, None, 'テレビ', None], [None, None, 'を', None], ['見', 'み', None, True], [None, None, 'ないです', True], [None, None, '。\n\n', None], [None, None, 'テレビ', None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'ません', None], [None, None, '。\n', None]]
[[None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'を', None], ['借', 'か', None, True], [None, None, 'りない', True], [None, None, '。\n\n', None], [None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'を', None], ['借', 'か', None, None], [None, None, 'りない', None], [None, None, 'です', None], [None, None, '。', None], [None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'を', None], ['借', 'か', None, None], [None, None, 'りません', None], [None, None, '。', None]]
[[None, None, 'パン', None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べない', None], [None, None, ' ', None], [None, None, '。', None], [None, None, 'パン', None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べないです', True], [None, None, '。\n\n', None], [None, None, 'パン', None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べません', None], [None, None, '。', None]]
[[None, None, 'ホラー', None], ['映画', 'えいが', None, None], [None, None, 'は', None], ['見', 'み', None, True], [None, None, 'ない', True], [None, None, '。', None], [None, None, 'ホラー', None], ['映画', 'えいが', None, None], [None, None, 'は', None], ['見', 'み', None, None], [None, None, 'ない', None], [None, None, 'です', None], [None, None, '。', None], [None, None, 'ホラー', None], ['映画', 'えいが', None, None], [None, None, 'は', None], ['見', 'み', None, None], [None, None, 'ません', None], [None, None, '。', None]]

  2%|▏         | 21/938 [00:12<09:06,  1.68it/s]

[[None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'は', None], [None, None, 'ない', True], [None, None, '。\n\n', None], [None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'は', None], [None, None, 'ない', None], [None, None, 'です', None], [None, None, '。', None], [None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'は', None], [None, None, 'あり', None], [None, None, 'ません', None], [None, None, '。', None]]
[[None, None, ' ', None], ['車', 'くるま', None, None], [None, None, 'は', None], ['持', 'も', None, None], [None, None, 'たない', None], [None, None, '。', None], ['車', 'くるま', None, None], [None, None, 'は', None], ['持', 'も', None, None], [None, None, 'たない', None], [None, None, 'です', None], [None, None, '。', None], ['車', 'くるま', None, None], [None, None, 'は', None], ['持', 'も', None, True], [None, None, 'ちません', True], [None, None, '。', None]]
[['木', 'き', None, None], [None, None, 'は', None], ['歩', 'ある', None, True], [None, None, 'かない', True], [None, None, '。\n\n', None], ['木', 'き', None, None], [None, None, 'は', None], ['歩', 'ある', None, None], [None, None, 'かない', None], [None, None, 'です', None], [None, None, '。', None], ['木', 'き', None, None], [None, None, 'は', None], ['歩', 'ある', None, None], [None, None, 'きません', None], [None, None, '。', None]]
[[None, None, 'トミー', None], [None, None, 'は', None], ['話', 'はな', None, True], [None, None, 'さない', True], [None, None, '。\n\n', None], [None, None, 'トミー', None], [None, None, 'は', None], ['話', 'はな', None, None], [None, None, 'さない', None], [None, None, 'です', None], [None, None, '。', None], [None, None, 'トミー', None], [None, None, 'は', None], ['話', 'はな', None, None], [None, None, 'しません', None], [None, None, '。', None]]
[[None, None, 'ボール', None], [None, None, 'を', None], ['打', 'う', None, True], [None, None, 'たない', True], [None, None, '。\n\n', None], [None, None, 'ボール', None], [None, None, 'を', None], ['打', 'う', None, None], [None, None, 'た', None], [None, None, 'ない', None], [None, None, 'です', None], [None, None, '。', None], [None, None, 'ボール', None], [None, None, 'を', None], ['打', 'う', None, None], [None, None, 'ち', None], [None, None, 'ません', None], [None, None, '。', None]]

  2%|▏         | 22/938 [00:13<09:20,  1.63it/s]

[['魚', 'さかな', None, None], [None, None, 'と', True], [None, None, 'バナナ。', None]]
[[None, None, 'トム', None], [None, None, 'と', True], [None, None, 'ジェリー。', None]]
[[None, None, 'コーヒー', None], [None, None, 'と', True], ['牛乳', 'ぎゅうにゅう', None, None], [None, None, '。', None]]
[['川', 'かわ', None, None], [None, None, 'と', True], ['滝', 'たき', None, None], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'と', True], [None, None, 'それ', None], [None, None, 'は', None], ['私', 'わたし', None, None], [None, None, 'の', None], [None, None, 'もの', None], [None, None, 'です', None], [None, None, '。', None]]

  2%|▏         | 23/938 [00:13<09:42,  1.57it/s]

[[None, None, 'ここ', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'ここ', True], [None, None, 'が', None], [None, None, 'いい', None], [None, None, '。', None]]
[[None, None, 'ここ', True], [None, None, 'も', None], [None, None, 'いい', None], [None, None, '。', None]]
[[None, None, 'ここ', True], [None, None, 'が', None], [None, None, 'いい', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'ここ', True], [None, None, 'が', None], [None, None, 'いい', None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]

  3%|▎         | 24/938 [00:14<09:54,  1.54it/s]

[[None, None, 'そこ', True], [None, None, 'が', None], [None, None, 'いい', None], [None, None, '。', None]]
[[None, None, 'そこ', True], [None, None, 'の', None], [None, None, 'パソコン。', None]]
[[None, None, 'たぶん、', None], [None, None, 'そこ', True], [None, None, '。', None]]
[[None, None, 'そこ', True], [None, None, 'の', None], [None, None, 'レストラン', None], [None, None, 'は', None], ['美味', 'おい', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'ここ', None], [None, None, 'と', None], [None, None, 'そこ', True], [None, None, 'も', None], ['明', 'あか', None, None], [None, None, 'る', None], [None, None, 'い', None], [None, None, '。', None]]

  3%|▎         | 25/938 [00:15<10:08,  1.50it/s]

[[None, None, 'あそこ', True], [None, None, 'が', None], [None, None, 'いい', None], [None, None, '。', None]]
[[None, None, 'あそこ', True], [None, None, 'も', None], ['楽', 'たの', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, '。', None]]
[[None, None, 'そこ', None], [None, None, 'と', None], [None, None, 'あそこ', True], [None, None, '。', None]]
[[None, None, 'あそこ', True], [None, None, 'が', None], ['広', 'ひろ', None, None], [None, None, 'い', None], [None, None, '。', None]]
[[None, None, 'あそこ', True], [None, None, 'の', None], ['店', 'みせ', None, None], [None, None, '。', None]]

  3%|▎         | 26/938 [00:15<09:38,  1.58it/s]

[[None, None, 'そこ', None], [None, None, 'で', True], ['寝', 'ね', None, None], [None, None, 'る', None], [None, None, '。', None]]
[[None, None, 'ホテル', None], [None, None, 'で', True], ['寝', 'ね', None, None], [None, None, 'る', None], [None, None, '。', None]]
[[None, None, 'ここ', None], [None, None, 'で', True], ['曲', 'ま', None, None], [None, None, 'が', None], [None, None, 'ります', None], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], [None, None, 'ここ', None], [None, None, 'で', True], [None, None, 'サッカー', None], [None, None, 'を', None], [None, None, 'する', None], [None, None, '。', None]]
[[None, None, 'そこ', None], [None, None, 'で', True], ['泳', 'およ', None, None], [None, None, 'ぎ', None], [None, None, 'ます', None], [None, None, 'か', None], [None, None, '。', None]]

  3%|▎         | 27/938 [00:16<10:02,  1.51it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], [None, None, 'あそこ', None], [None, None, 'に', True], [None, None, 'います。', None]]
[[None, None, 'ここ', None], [None, None, 'に', True], ['本', 'ほん', None, None], [None, None, 'を', None], ['置', 'お', None, None], [None, None, 'く', None], [None, None, '。', None]]
[[None, None, 'この', None], ['机', 'つくえ', None, None], [None, None, 'の', None], ['上', 'うえ', None, None], [None, None, 'に', True], ['座', 'すわ', None, None], [None, None, 'る', None], [None, None, '。', None]]
[['駅', 'えき', None, None], [None, None, 'に', True], ['行', 'い', None, None], [None, None, 'く', None], [None, None, '。', None]]
[['病院', 'びょういん', None, None], [None, None, 'に', True], ['行', 'い', None, None], [None, None, 'く', None], [None, None, '。', None]]

  3%|▎         | 28/938 [00:17<10:13,  1.48it/s]

[[None, None, 'ここ', None], [None, None, 'か', True], [None, None, 'そこ', None], [None, None, '。', None]]
[['赤', 'あか', None, None], [None, None, 'か', True], ['青', 'あお', None, None], [None, None, '。', None]]
[['寝', 'ね', None, None], [None, None, 'る', None], [None, None, 'か', True], ['遊', 'あそ', None, None], [None, None, 'ぶ', None], [None, None, '。', None]]
[['今日', 'きょう', None, None], [None, None, 'か', True], ['明日', 'あした', None, None], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'は', None], ['私', 'わたし', None, None], [None, None, 'の', None], [None, None, 'ペン', None], [None, None, 'か', True], [None, None, 'あなた', None], [None, None, 'の', None], [None, None, 'ペン', None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]

  3%|▎         | 29/938 [00:17<10:06,  1.50it/s]

[[None, None, 'トム', None], [None, None, 'と', True], ['話', 'はな', None, None], [None, None, 'す', None], [None, None, '。', None]]
[['僕', 'ぼく', None, None], [None, None, 'は', None], ['友達', 'ともだち', None, None], [None, None, 'と', True], [None, None, 'ごはん', None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'る', None], [None, None, '。', None]]
[[None, None, 'ゆうこさん', None], [None, None, 'は', None], [None, None, 'みおさん', None], [None, None, 'と', True], [None, None, 'コーヒー', None], [None, None, 'を', None], ['飲', 'の', None, None], [None, None, 'む', None], [None, None, '。', None]]
[[None, None, 'タキ', None], [None, None, 'は', None], [None, None, 'ミツハ', None], [None, None, 'と', True], ['走', 'はし', None, None], [None, None, 'る', None], [None, None, '。', None]]
[['田中', 'たなか', None, None], [None, None, 'さん', None], [None, None, 'は', None], ['山田', 'やまだ', None, None], [None, None, 'さん', None], [None, None, 'と', True], ['話', 'はな', None, None], [None, None, 'す', None], [None, None, '。', None]]

  3%|▎         | 30/938 [00:18<10:12,  1.48it/s]

[[None, None, 'これ', None], [None, None, 'は', None], [None, None, 'あなた', None], [None, None, 'の', None], ['本', 'ほん', None, None], [None, None, 'でしょう', True], [None, None, '。', None]]
[[None, None, 'いい', None], [None, None, 'でしょう', True], [None, None, '。', None]]
[['明日', 'あした', None, None], [None, None, 'は', None], ['寒', 'さむ', None, None], [None, None, 'い', None], [None, None, 'でしょう', True], [None, None, '。', None]]
[[None, None, 'あなた', None], [None, None, 'は', None], [None, None, 'トム', None], [None, None, 'でしょう', True], [None, None, '？', None]]
[[None, None, 'これ', None], [None, None, 'は', None], [None, None, '、', None], [None, None, 'いい', None], ['車', 'くるま', None, None], [None, None, 'でしょう', True], [None, None, '。', None]]

  3%|▎         | 31/938 [00:19<10:25,  1.45it/s]

[[None, None, 'ここ', None], [None, None, 'が', None], [None, None, 'いい', None], [None, None, 'だろう', True], [None, None, '？', None]]
[[None, None, 'あなた', None], [None, None, 'だろう', True], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'は', None], [None, None, 'ペン', None], [None, None, 'だろう', True], [None, None, '。', None]]
[['今夜', 'こんや', None, None], [None, None, 'は', None], [None, None, '、', None], ['忙', 'いそが', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'だろう', True], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'は', None], [None, None, '、', None], ['水', 'みず', None, None], [None, None, 'だろう', True], [None, None, '。', None]]

  3%|▎         | 32/938 [00:19<10:29,  1.44it/s]

[['本', 'ほん', None, None], [None, None, 'がある', True], [None, None, '。', None]]
[[None, None, 'ペン', None], [None, None, 'がない', True], [None, None, '。', None]]
[['時間', 'じかん', None, None], [None, None, 'があります', True], [None, None, '。', None]]
[['仕事', 'しごと', None, None], [None, None, 'がない', True], [None, None, '。', None]]
[[None, None, 'エレベータ', None], [None, None, 'があります', True], [None, None, '。', None]]

  4%|▎         | 33/938 [00:20<10:24,  1.45it/s]

[['私', 'わたし', None, None], [None, None, 'がいる', True], [None, None, '。', None]]
[[None, None, 'トム', None], [None, None, 'がいます', True], [None, None, '。', None]]
[['田中', 'たなか', None, None], [None, None, 'さん', None], [None, None, 'と', None], [None, None, 'トム', None], [None, None, 'がいます', True], [None, None, '。', None]]
[['先生', 'せんせい', None, None], [None, None, 'がいます', True], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'と', None], ['友達', 'ともだち', None, None], [None, None, 'がいます', True], [None, None, '。', None]]

  4%|▎         | 34/938 [00:21<10:19,  1.46it/s]

[[None, None, 'この', True], ['本', 'ほん', None, None], [None, None, 'が', None], [None, None, 'いい', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'この', True], [None, None, 'ケーキ', None], [None, None, 'は', None], ['大', 'おお', None, None], [None, None, 'きい', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'この', True], ['写真', 'しゃしん', None, None], [None, None, 'は', None], ['私', 'わたし', None, None], [None, None, 'のです', None], [None, None, '。', None]]
[[None, None, 'この', True], ['犬', 'いぬ', None, None], [None, None, 'は', None], ['私', 'わたし', None, None], [None, None, 'の', None], ['犬', 'いぬ', None, None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'この', True], ['動物', 'どうぶつ', None, None], [None, None, 'は', None], [None, None, '、', None], ['猫', 'ねこ', None, None], [None, None, 'です', None], [None, None, '。', None]]

  4%|▎         | 35/938 [00:22<10:54,  1.38it/s]

[[None, None, 'その', True], ['本', 'ほん', None, None], [None, None, 'が', None], [None, None, 'いい', None], [None, None, '。', None]]
[[None, None, 'その', True], ['映画', 'えいが', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'る', None], [None, None, '。', None]]
[[None, None, 'その', True], ['店', 'みせ', None, None], [None, None, 'は', None], ['安', 'やす', None, None], [None, None, 'い', None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'その', True], ['動物', 'どうぶつ', None, None], [None, None, 'は', None], ['猿', 'さる', None, None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'その', True], ['時計', 'とけい', None, None], [None, None, 'は', None], ['高', 'たか', None, None], [None, None, 'い', None], [None, None, 'でしょう', None], [None, None, '。', None]]

  4%|▍         | 36/938 [00:22<11:02,  1.36it/s]

[[None, None, 'あの', True], ['人', 'ひと', None, None], [None, None, 'は', None], [None, None, 'トム', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'あの', True], ['犬', 'いぬ', None, None], [None, None, 'が', None], ['可愛', 'かわい', None, None], [None, None, 'い', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'あの', True], [None, None, 'ラーメン', None], ['屋', 'や', None, None], [None, None, 'は', None], ['美味', 'おい', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'あの', True], ['綺麗', 'きれい', None, None], [None, None, 'な', None], ['人', 'ひと', None, None], [None, None, 'は', None], [None, None, '、', None], ['田中', 'たなか', None, None], [None, None, 'さん。', None]]
[[None, None, 'あの', True], ['店', 'みせ', None, None], [None, None, 'でもいい', None], [None, None, '。', None]]

  4%|▍         | 37/938 [00:23<10:08,  1.48it/s]

[[None, None, 'いい', None], [None, None, 'んです', True], [None, None, 'か', None], [None, None, '。', None]]
[['赤', 'あか', None, None], [None, None, 'が', None], [None, None, 'いい', None], [None, None, 'んです', True], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'いい', None], [None, None, 'のです', True], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'が', None], [None, None, 'いい', None], [None, None, 'のです', True], [None, None, 'か', None], [None, None, '。', None]]
[['川', 'かわ', None, None], [None, None, 'がある', None], [None, None, 'んです', True], [None, None, '。', None]]

  4%|▍         | 38/938 [00:24<09:53,  1.52it/s]

[['寒', 'さむ', None, True], [None, None, 'かった', True], [None, None, '。', None]]
[[None, None, 'それ', None], [None, None, 'は', None], [None, None, '、', None], ['高', 'たか', None, True], [None, None, 'かった', True], [None, None, '。', None]]
[['田中', 'たなか', None, None], [None, None, 'さん', None], [None, None, 'は', None], ['強', 'つよ', None, True], [None, None, 'かった', True], [None, None, 'です', None], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['姉', 'あね', None, None], [None, None, 'の', None], ['家', 'いえ', None, None], [None, None, 'が', None], ['古', 'ふる', None, True], [None, None, 'かった', True], [None, None, 'です', None], [None, None, '。', None]]
[['動物園', 'どうぶつえん', None, None], [None, None, 'は', None], ['楽', 'たの', None, True], [None, None, 'しかった', True], [None, None, '。', None]]

  4%|▍         | 39/938 [00:24<09:13,  1.63it/s]

[['読', 'よ', None, None], [None, None, 'む', None], [None, None, 'のは', True], ['私', 'わたし', None, None], [None, None, 'です', None], [None, None, '。', None]]
[['君', 'きみ', None, None], [None, None, 'を', None], ['愛', 'あい', None, None], [None, None, 'する', None], [None, None, 'のは', True], [None, None, '、', None], ['私', 'わたし', None, None], [None, None, 'だ', None], [None, None, '。', None]]
[[None, None, 'この', None], ['仕事', 'しごと', None, None], [None, None, 'を', None], [None, None, 'する', None], [None, None, 'のは', True], ['私', 'わたし', None, None], [None, None, 'だ', None], [None, None, '。', None]]
[['寿司', 'すし', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'る', None], [None, None, 'のは', True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'だ', None], [None, None, '。', None]]
[['漢字', 'かんじ', None, None], [None, None, 'を', None], ['覚', 'おぼ', None, None], [None, None, 'え', None], [None, None, 'る', None], [None, None, 'のは', True], [None, None, '、', None], ['彼女', 'かのじょ', None, None], [None, None, 'です', None], [None, None, '。', None]]

  4%|▍         | 40/938 [00:25<09:40,  1.55it/s]

[['新', 'あたら', None, True], [None, None, 'しい', True], ['車', 'くるま', None, None], [None, None, '。', None]]
[['可愛', 'かわい', None, True], [None, None, 'い', True], ['女', 'おんな', None, None], [None, None, 'の', None], ['子', 'こ', None, None], [None, None, 'がいる', None], [None, None, '。', None]]
[[None, None, 'かっこいい', True], ['先輩', 'せんぱい', None, None], [None, None, '。', None]]
[['寒', 'さむ', None, True], [None, None, 'い', True], ['夜', 'よる', None, None], [None, None, '。', None]]
[['面白', 'おもしろ', None, True], [None, None, 'い', True], [None, None, 'ゲーム', None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'い', None], [None, None, 'ます', None], [None, None, '。', None]]

  4%|▍         | 41/938 [00:25<10:00,  1.49it/s]

[['暇', 'ひま', None, True], [None, None, 'な', True], ['一日', 'いちにち', None, None], [None, None, '。', None]]
[['旭', 'あさひ', None, None], [None, None, 'が', None], ['丘', 'おか', None, None], [None, None, 'は', None], ['静', 'しず', None, True], [None, None, 'かな', True], ['街', 'まち', None, None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'たなかさん', None], [None, None, 'は', None], ['親切', 'しんせつ', None, True], [None, None, 'な', True], ['人', 'ひと', None, None], [None, None, 'だ', None], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'は', None], ['便利', 'べんり', None, True], [None, None, 'な', True], [None, None, 'ツール', None], [None, None, 'です', None], [None, None, '。', None]]
[['綺麗', 'きれい', None, True], [None, None, 'な', True], [None, None, 'タオル', None], [None, None, 'は', None], [None, None, 'トイレ', None], [None, None, 'に', None], [None, None, 'ある', None], [None, None, '。', None]]

  4%|▍         | 42/938 [00:26<10:19,  1.45it/s]

[['学校', 'がっこう', None, None], [None, None, 'へいく', True], [None, None, '。', None]]
[['駅', 'えき', None, None], [None, None, 'へいく', True]]
[['東京', 'とうきょう', None, None], [None, None, 'へいく', True], [None, None, '。', None]]
[['教室', 'きょうしつ', None, None], [None, None, 'へいく', True], [None, None, '。', None]]
[['道', 'みち', None, None], [None, None, 'へいきます', True], [None, None, '。', None]]

  5%|▍         | 43/938 [00:27<10:26,  1.43it/s]

[[None, None, 'サッカー', None], [None, None, 'を', None], [None, None, 'する', True], [None, None, '。', None]]
[[None, None, 'サッカー', None], [None, None, 'を', None], [None, None, 'します', True], [None, None, '。', None]]
[['何', 'なに', None, None], [None, None, 'を', None], [None, None, 'します', True], [None, None, 'か', None], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], ['勉強', 'べんきょう', None, None], [None, None, 'を', None], [None, None, 'する', True], [None, None, '。', None]]
[['掃除', 'そうじ', None, None], [None, None, 'を', None], [None, None, 'する', True], [None, None, '。', None]]

  5%|▍         | 44/938 [00:28<10:28,  1.42it/s]

[[None, None, 'トム', None], [None, None, 'は', None], [None, None, 'ここ', None], [None, None, 'に', None], [None, None, 'くる', True], [None, None, '。', None]]
[[None, None, 'バス', None], [None, None, 'が', None], [None, None, 'くる', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], [None, None, 'バス', None], [None, None, 'で', None], [None, None, 'きます', True], [None, None, '。', None]]
[['友達', 'ともだち', None, None], [None, None, 'も', None], [None, None, 'きます', True], [None, None, 'か', None], [None, None, '。', None]]
[['明日', 'あした', None, None], [None, None, 'きます', True], [None, None, '。', None]]

  5%|▍         | 45/938 [00:28<10:19,  1.44it/s]

[['疲', 'つか', None, True], [None, None, 'れた', True], [None, None, '。', None], ['疲', 'つか', None, None], [None, None, 'れました', None], [None, None, '。', None]]
[['早', 'はや', None, None], [None, None, 'く', None], ['起', 'お', None, None], [None, None, 'きた', None], [None, None, '。', None], ['早', 'はや', None, None], [None, None, 'く', None], ['起', 'お', None, True], [None, None, 'きました', True], [None, None, '。', None]]
[[None, None, 'シャワー', None], [None, None, 'を', None], ['浴', 'あ', None, True], [None, None, 'びた', True], [None, None, '。', None], [None, None, 'シャワー', None], [None, None, 'を', None], ['浴', 'あ', None, None], [None, None, 'びました', None], [None, None, '。', None]]
[['昨日', 'きのう', None, None], [None, None, '、', None], [None, None, 'テレビ', None], [None, None, 'を', None], ['見', 'み', None, True], [None, None, 'た', True], [None, None, '。', None], ['昨日', 'きのう', None, None], [None, None, '、', None], [None, None, 'テレビ', None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'ました', None], [None, None, '。', None]]
[['日本', 'にほん', None, None], [None, None, 'で', None], ['寿司', 'すし', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べた', None], [None, None, '。', None], ['日本', 'にほん', None, None], [None, None, 'で', None], ['寿司', 'すし', None, None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べました', True], [None, None, '。', None]]

  5%|▍         | 46/938 [00:29<09:39,  1.54it/s]

[['昨日', 'きのう', None, None], [None, None, '、', None], ['本', 'ほん', None, None], [None, None, 'を', None], ['読', 'よ', None, True], [None, None, 'んだ', True], [None, None, '。', None], ['昨日', 'きのう', None, None], [None, None, '、', None], ['本', 'ほん', None, None], [None, None, 'を', None], ['読', 'よ', None, None], [None, None, 'みました', None], [None, None, '。', None]]
[['牛乳', 'ぎゅうにゅう', None, None], [None, None, 'を', None], ['飲', 'の', None, True], [None, None, 'んだ', True], [None, None, '。', None], ['牛乳', 'ぎゅうにゅう', None, None], [None, None, 'を', None], ['飲', 'の', None, None], [None, None, 'みました', None], [None, None, '。', None]]
[[None, None, 'ロンドン', None], [None, None, 'へ', None], ['飛', 'と', None, True], [None, None, 'んだ', True], [None, None, '。', None], [None, None, 'ロンドン', None], [None, None, 'へ', None], ['飛', 'と', None, None], [None, None, 'びました', None], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'たち', None], [None, None, 'の', None], [None, None, 'チーム', None], [None, None, 'は', None], ['勝', 'か', None, None], [None, None, 'った', None], [None, None, '！', None], ['私', 'わたし', None, None], [None, None, 'たち', None], [None, None, 'の', None], [None, None, 'チーム', None], [None, None, 'は', None], ['勝', 'か', None, True], [None, None, 'ちました', True], [None, None, '！', None]]
[[None, None, 'メアリー', None], [None, None, 'は', None], ['日本', 'にほん', None, None], [None, None, 'に', None], ['帰', 'かえ', None, True], [None, None, 'った', True], [None, None, '。', None], [None, None, 'メアリー', None], [None, None, 'は', None], ['日本', 'にほん', None, None], [None, None, 'に', None], ['帰', 'かえ', None, None], [None, None, 'りました', None], [None, None, '。', None]]

  5%|▌         | 47/938 [00:30<09:38,  1.54it/s]

[['好', 'す', None, True], [None, None, 'き', True], [None, None, '？', None]]
[[None, None, 'うん、', None], ['好', 'す', None, True], [None, None, 'き', True], [None, None, 'だ', None], [None, None, '。', None]]
[['好', 'す', None, True], [None, None, 'きな', True], ['人', 'ひと', None, None], [None, None, 'がいます', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'はい、', None], ['山田', 'やまだ', None, None], [None, None, 'さん', None], [None, None, 'が', None], ['好', 'す', None, True], [None, None, 'き', True], [None, None, 'です', None], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['家', 'いえ', None, None], [None, None, 'が', None], ['好', 'す', None, True], [None, None, 'き', True], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]

  5%|▌         | 48/938 [00:30<09:03,  1.64it/s]

[[None, None, 'パイナップル', None], [None, None, 'が', None], ['嫌', 'きら', None, True], [None, None, 'い', True], [None, None, '？', None]]
[[None, None, 'うん、', None], ['大', 'だい', None, None], ['嫌', 'きら', None, True], [None, None, 'い', True], [None, None, 'だ', None], [None, None, '。', None]]
[['嫌', 'きら', None, True], [None, None, 'いな', True], ['食', 'た', None, None], [None, None, 'べ', None], ['物', 'もの', None, None], [None, None, 'があります', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'はい、', None], ['納豆', 'なっとう', None, None], [None, None, 'が', None], ['嫌', 'きら', None, True], [None, None, 'い', True], [None, None, 'です', None], [None, None, '。', None]]
[['嫌', 'きら', None, True], [None, None, 'いな', True], ['色', 'いろ', None, None], [None, None, 'は', None], [None, None, 'ありません。', None]]

  5%|▌         | 49/938 [00:31<09:18,  1.59it/s]

[['私', 'わたし', None, None], [None, None, 'は', None], [None, None, 'サッカー', None], [None, None, 'を', None], [None, None, 'する', None], [None, None, 'のが', True], ['好', 'す', None, True], [None, None, 'き', True], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], ['本', 'ほん', None, None], [None, None, 'を', None], ['読', 'よ', None, None], [None, None, 'む', None], [None, None, 'のが', True], ['好', 'す', None, True], [None, None, 'き', True], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], [None, None, 'ラーメン', None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'る', None], [None, None, 'のが', True], ['好', 'す', None, True], [None, None, 'き', True], [None, None, 'です', None], [None, None, '。', None]]
[['犬', 'いぬ', None, None], [None, None, 'と', None], ['遊', 'あそ', None, None], [None, None, 'ぶ', None], [None, None, 'のが', True], ['好', 'す', None, True], [None, None, 'き', True], [None, None, '。', None]]
[['旅行', 'りょこう', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'のが', True], ['好', 'す', None, True], [None, None, 'き', True], [None, None, 'でしょう', None], [None, None, '？', None]]

  5%|▌         | 50/938 [00:31<09:27,  1.56it/s]

[[None, None, 'ベッド', None], [None, None, 'がある', True], ['部屋', 'へや', None, None], [None, None, '。', None]]
[[None, None, 'たくさん', None], ['休', 'やす', None, None], [None, None, 'み', None], [None, None, 'がある', True], ['５', 'ご', None, None], ['月', 'がつ', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, '。', None]]
[['綺麗', 'きれい', None, None], [None, None, 'な', None], ['池', 'いけ', None, None], [None, None, 'がある', True], ['公園', 'こうえん', None, None], [None, None, '。', None]]
[['家', 'いえ', None, None], [None, None, 'がある', True], ['人', 'ひと', None, None], [None, None, '。', None]]
[['冷蔵庫', 'れいぞうこ', None, None], [None, None, 'がある', True], ['台所', 'だいどころ', None, None], [None, None, '。', None]]

  5%|▌         | 51/938 [00:32<09:50,  1.50it/s]

[['暑', 'あつ', None, True], [None, None, 'くないです', True], [None, None, '。', None]]
[['今日', 'きょう', None, None], [None, None, 'は', None], ['寒', 'さむ', None, True], [None, None, 'くない', True], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'は', None], ['楽', 'たの', None, True], [None, None, 'しくない', True], [None, None, 'です', None], [None, None, '。', None]]
[['新', 'あたら', None, True], [None, None, 'しくない', True], [None, None, 'コンピューター。', None]]
[[None, None, 'それ', None], [None, None, 'は', None], ['安', 'やす', None, True], [None, None, 'くないです', True], [None, None, '。', None]]

  6%|▌         | 52/938 [00:33<09:16,  1.59it/s]

[[None, None, 'バス', None], [None, None, 'で', True], ['行', 'い', None, None], [None, None, 'く', None], [None, None, '。', None]]
[[None, None, 'バス', None], [None, None, 'で', True], ['学校', 'がっこう', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, '。', None]]
[['自転車', 'じてんしゃ', None, None], [None, None, 'で', True], [None, None, '、', None], [None, None, 'いい', None], [None, None, 'です', None], [None, None, '。', None]]
[['自転車', 'じてんしゃ', None, None], [None, None, 'で', True], [None, None, '。', None]]
[['電車', 'でんしゃ', None, None], [None, None, 'で', True], ['来', 'き', None, None], [None, None, 'ます', None], [None, None, 'か', None], [None, None, '。', None]]

  6%|▌         | 53/938 [00:33<08:53,  1.66it/s]

[['私', 'わたし', None, None], [None, None, 'は', None], ['寿司', 'すし', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'ではない', None], [None, None, 'ので', True], [None, None, '、', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'ない', None], [None, None, '。', None]]
[['今日', 'きょう', None, None], [None, None, 'は', None], ['時間', 'じかん', None, None], [None, None, 'がない', None], [None, None, 'ので', True], [None, None, '、', None], ['明日', 'あした', None, None], [None, None, 'に', None], ['漢字', 'かんじ', None, None], [None, None, 'を', None], ['教', 'おし', None, None], [None, None, 'え', None], [None, None, 'ます', None], [None, None, '。', None]]
[['今日', 'きょう', None, None], [None, None, 'は', None], ['先生', 'せんせい', None, None], [None, None, 'が', None], ['休', 'やす', None, None], [None, None, 'み', None], [None, None, 'なので', True], [None, None, '、', None], ['授業', 'じゅぎょう', None, None], [None, None, 'が', None], [None, None, 'な', None], [None, None, 'くなった', None], [None, None, '。', None]]
[['土曜日', 'どようび', None, None], [None, None, 'なので', True], [None, None, '、', None], ['旅行', 'りょこう', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'き', None], [None, None, 'たい', None], [None, None, '。', None]]
[['今日', 'きょう', None, None], [None, None, 'は', None], ['一月', 'いちがつ', None, None], ['二十日', 'はつか', None, None], [None, None, 'なので', True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'の', None], ['誕生日', 'たんじょうび', None, None], [None, None, 'です', None], [None, None, '。', None]]

  6%|▌         | 54/938 [00:34<08:44,  1.69it/s]

[['私', 'わたし', None, None], [None, None, 'は', None], ['犬', 'いぬ', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'ですから', True], [None, None, '。', None]]
[[None, None, 'お', None], ['菓子', 'かし', None, None], [None, None, 'だから', True], [None, None, '、', None], ['甘', 'あま', None, None], [None, None, 'い', None], [None, None, '。', None]]
[['辛', 'から', None, None], [None, None, 'い', None], [None, None, 'から', True], [None, None, '、カレー', None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, '。', None]]
[['楽', 'たの', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'から', True], [None, None, '、スポーツ', None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'る', None], [None, None, '。', None]]
[['学生', 'がくせい', None, None], [None, None, 'がいる', None], [None, None, 'から', True], [None, None, '、', None], ['学校', 'がっこう', None, None], [None, None, 'がある', None], [None, None, 'だろう', None], [None, None, '。', None]]

  6%|▌         | 55/938 [00:35<09:33,  1.54it/s]

[['駅', 'えき', None, None], [None, None, 'から', True], [None, None, 'バス', None], [None, None, 'で', None], ['来', 'き', None, None], [None, None, 'た', None], [None, None, '。', None]]
[[None, None, 'アメリカ', None], [None, None, 'から', True], ['来', 'き', None, None], [None, None, 'ました', None], [None, None, '。', None]]
[[None, None, 'この', None], ['靴', 'くつ', None, None], [None, None, 'は', None], [None, None, 'お', None], ['母', 'かあ', None, None], [None, None, 'さん', None], [None, None, 'から', True], [None, None, 'です', None], [None, None, '。', None]]
[['学校', 'がっこう', None, None], [None, None, 'から', True], [None, None, '、パーティに', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, '。', None]]
[['仕事', 'しごと', None, None], [None, None, 'から', True], ['帰', 'かえ', None, None], [None, None, 'る', None], [None, None, '。', None]]

  6%|▌         | 56/938 [00:35<09:12,  1.60it/s]

[['便利', 'べんり', None, None], [None, None, 'だけど', True], [None, None, '、', None], ['高', 'たか', None, None], [None, None, 'い', None], [None, None, '。', None]]
[[None, None, 'その', None], ['赤', 'あか', None, None], [None, None, 'い', None], ['Ｔ', 'ティー', None, None], [None, None, 'シャツ', None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'だけど', True], [None, None, '、', None], ['青', 'あお', None, None], [None, None, 'い', None], ['Ｔ', 'ティー', None, None], [None, None, 'シャツ', None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'う', None], [None, None, '。', None]]
[[None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'が', None], [None, None, 'ある', None], [None, None, 'けど', True], [None, None, '、', None], ['買', 'か', None, None], [None, None, 'い', None], [None, None, 'ません', None], [None, None, '。', None]]
[['豚肉', 'ぶたにく', None, None], [None, None, 'は', None], ['嫌', 'きら', None, None], [None, None, 'い', None], [None, None, 'だけど', True], [None, None, '、', None], ['鶏肉', 'とりにく', None, None], [None, None, 'は', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'ます', None], [None, None, '。', None]]
[[None, None, 'その', None], ['店', 'みせ', None, None], [None, None, 'は', None], ['高', 'たか', None, None], [None, None, 'い', None], [None, None, 'けど', True], [None, None, '、', None], ['美味', 'おい', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'でしょう', None], [None, None, '。', None]]

  6%|▌         | 57/938 [00:36<10:17,  1.43it/s]

[['早', 'はや', None, None], [None, None, 'いです', None], [None, None, 'が', True], [None, None, '、', None], ['起', 'お', None, None], [None, None, 'きます', None], [None, None, '。', None]]
[['難', 'むずか', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'です', None], [None, None, 'が', True], [None, None, '、', None], ['頑張', 'がんば', None, None], [None, None, 'ります', None], [None, None, '。', None]]
[['寒', 'さむ', None, None], [None, None, 'い', None], [None, None, 'です', None], [None, None, 'が', True], [None, None, '、', None], ['外', 'そと', None, None], [None, None, 'へ', None], ['行', 'い', None, None], [None, None, 'きます', None], [None, None, '。', None]]
[[None, None, 'ロイさん', None], [None, None, 'の', None], ['携帯', 'けいたい', None, None], [None, None, 'は', None], ['古', 'ふる', None, None], [None, None, 'い', None], [None, None, 'です', None], [None, None, 'が', True], [None, None, '、', None], ['速', 'はや', None, None], [None, None, 'い', None], [None, None, 'です', None], [None, None, '。', None]]
[['綺麗', 'きれい', None, None], [None, None, 'です', None], [None, None, 'が', True], [None, None, '、', None], ['危', 'あぶ', None, None], [None, None, 'な', None], [None, None, 'い', None], [None, None, 'です', None], [None, None, '。', None]]

  6%|▌         | 58/938 [00:37<10:27,  1.40it/s]

[['寿司', 'すし', None, None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べなかった', True], [None, None, '。', None], ['寿司', 'すし', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べなかった', None], [None, None, 'です', None], [None, None, '。', None], ['寿司', 'すし', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べませんでした', None], [None, None, '。', None]]
[[None, None, 'テレビ', None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'なかった', None], [None, None, '。', None], [None, None, 'テレビ', None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'なかった', None], [None, None, 'です', None], [None, None, '。', None], [None, None, 'テレビ', None], [None, None, 'を', None], ['見', 'み', None, True], [None, None, 'ませんでした', True], [None, None, '。', None]]
[[None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'を', None], ['借', 'か', None, True], [None, None, 'りなかった', True], [None, None, '。', None], [None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'を', None], ['借', 'か', None, None], [None, None, 'りなかった', None], [None, None, 'です', None], [None, None, '。', None], [None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'を', None], ['借', 'か', None, None], [None, None, 'りませんでした', None], [None, None, '。', None]]
[['早', 'はや', None, None], [None, None, 'く', None], ['起', 'お', None, None], [None, None, 'きなかった', None], [None, None, '。', None], ['早', 'はや', None, None], [None, None, 'く', None], ['起', 'お', None, None], [None, None, 'きなかった', None], [None, None, 'です', None], [None, None, '。', None], ['早', 'はや', None, None], [None, None, 'く', None], ['起', 'お', None, True], [None, None, 'きませんでした', True], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'は', None], ['教', 'おし', None, True], [None, None, 'えなかった', True], [None, None, '。', None], [None, None, 'これ', None], [None, None, 'は', None], ['教', 'おし', None, None], [None, None, 'えなかった', None], [None, None, 'です', None], [None, None, '。', None], [None, None, 'これ', None], [None, None, 'は', None], ['教', 'おし', None, None], [None, None, 'えませんでした', None], [None, None, '。', None]]

  6%|▋         | 59/938 [00:37<09:59,  1.47it/s]

[['昨日', 'きのう', None, None], [None, None, '、', None], ['行', 'い', None, True], [None, None, 'かなかった', True], [None, None, '。', None], ['昨日', 'きのう', None, None], [None, None, '、', None], ['行', 'い', None, None], [None, None, 'かなかった', None], [None, None, 'です', None], [None, None, '。', None], ['昨日', 'きのう', None, None], [None, None, '、', None], ['行', 'い', None, None], [None, None, 'きませんでした', None], [None, None, '。', None]]
[['遊', 'あそ', None, None], [None, None, 'ば', None], [None, None, 'なかった', None], [None, None, '。', None], ['遊', 'あそ', None, None], [None, None, 'ば', None], [None, None, 'なかった', None], [None, None, 'です', None], [None, None, '。', None], ['遊', 'あそ', None, True], [None, None, 'びませんでした', True], [None, None, '。', None]]
[[None, None, 'はなこさん', None], [None, None, 'は', None], ['話', 'はな', None, True], [None, None, 'さなかった', True], [None, None, '。', None], [None, None, 'はなこさん', None], [None, None, 'は', None], ['話', 'はな', None, None], [None, None, 'さなかった', None], [None, None, 'です', None], [None, None, '。', None], [None, None, 'はなこさん', None], [None, None, 'は', None], ['話', 'はな', None, None], [None, None, 'しませんでした', None], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['事故', 'じこ', None, None], [None, None, 'で', None], ['死', 'し', None, None], [None, None, 'ななかった', None], [None, None, '！', None], ['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['事故', 'じこ', None, None], [None, None, 'で', None], ['死', 'し', None, None], [None, None, 'ななかった', None], [None, None, 'です', None], [None, None, '！', None], ['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['事故', 'じこ', None, None], [None, None, 'で', None], ['死', 'し', None, True], [None, None, 'にませんでした', True], [None, None, '！', None]]
[[None, None, 'それも', None], ['知', 'し', None, True], [None, None, 'らなかった', True], [None, None, '。', None]]

  6%|▋         | 60/938 [00:38<09:26,  1.55it/s]

[[None, None, '（', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'る', None], [None, None, '）→ ', None], ['食', 'た', None, True], [None, None, 'べて', True], [None, None, ' ', None]]
[[None, None, '（', None], ['洗', 'あら', None, None], [None, None, 'う', None], [None, None, '）→ ', None], ['洗', 'あら', None, True], [None, None, 'って', True], [None, None, ' ', None]]
[[None, None, '（', None], ['返', 'かえ', None, None], [None, None, 'す', None], [None, None, '）→ ', None], ['返', 'かえ', None, True], [None, None, 'して', True], [None, None, ' ', None]]
[[None, None, '（', None], ['歩', 'ある', None, None], [None, None, 'く', None], [None, None, '）→ ', None], ['歩', 'ある', None, True], [None, None, 'いて', True], [None, None, ' ', None]]
[[None, None, '（', None], ['泳', 'およ', None, None], [None, None, 'ぐ', None], [None, None, '）→ ', None], ['泳', 'およ', None, True], [None, None, 'いで', True], [None, None, ' ', None]]

  7%|▋         | 61/938 [00:39<10:05,  1.45it/s]

[['何', 'なに', None, None], [None, None, 'を', None], [None, None, 'している', True], [None, None, '？', None]]
[['寿司', 'すし', None, None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べている', True], [None, None, '。', None]]
[['今', 'いま', None, None], [None, None, '、', None], ['勉強', 'べんきょう', None, None], [None, None, 'していない', True], [None, None, 'よ。', None]]
[['今', 'いま', None, None], [None, None, '、', None], ['兄', 'あに', None, None], [None, None, 'は', None], ['寝', 'ね', None, True], [None, None, 'ていません', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['図書館', 'としょかん', None, None], [None, None, 'で', None], ['日本語', 'にほんご', None, None], [None, None, 'を', None], ['勉強', 'べんきょう', None, None], [None, None, 'している', True], [None, None, 'だろう', None], [None, None, '。', None]]

  7%|▋         | 62/938 [00:39<10:29,  1.39it/s]

[['大阪', 'おおさか', None, None], [None, None, 'へ', True], [None, None, 'ようこそ。', None]]
[[None, None, 'ここ', None], [None, None, 'へ', True], [None, None, '？', None]]
[['神戸', 'こうべ', None, None], [None, None, 'へ', True], ['行', 'い', None, None], [None, None, 'く。', None]]
[['家', 'いえ', None, None], [None, None, 'へ', True], ['帰', 'かえ', None, None], [None, None, 'る', None], [None, None, '。', None]]
[['道', 'みち', None, None], [None, None, 'へ', True], ['走', 'はし', None, None], [None, None, 'る', None], [None, None, '。', None]]

  7%|▋         | 63/938 [00:40<10:15,  1.42it/s]

[[None, None, 'ラーメン', None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べにいく', True], [None, None, '。', None]]
[[None, None, 'サッカー', None], [None, None, 'を', None], [None, None, 'しにいく', True], [None, None, '。', None]]
[['日本語', 'にほんご', None, None], [None, None, 'を', None], ['勉強', 'べんきょう', None, None], [None, None, 'しにいきます', True], [None, None, '。', None]]
[['公園', 'こうえん', None, None], [None, None, 'へ', None], ['遊', 'あそ', None, True], [None, None, 'びにいった', True], [None, None, '。', None]]
[['本', 'ほん', None, None], [None, None, 'を', None], ['買', 'か', None, True], [None, None, 'いにいきます', True], [None, None, '。', None]]

  7%|▋         | 64/938 [00:41<10:22,  1.40it/s]

[['誰', 'だれ', None, True], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[['誰', 'だれ', None, True], [None, None, 'がいます', None], [None, None, 'か', None], [None, None, '。', None]]
[['誰', 'だれ', None, True], [None, None, 'が', None], [None, None, 'します', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'は', None], ['誰', 'だれ', None, True], [None, None, 'の', None], [None, None, 'パソコン', None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['誰', 'だれ', None, True], [None, None, 'でしょう', None], [None, None, '。', None]]

  7%|▋         | 65/938 [00:42<10:20,  1.41it/s]

[['暑', 'あつ', None, None], [None, None, 'い', None], [None, None, '。', None], ['暑', 'あつ', None, True], [None, None, 'いです', True], [None, None, '。', None]]
[['寒', 'さむ', None, None], [None, None, 'い', None], [None, None, '。', None], ['寒', 'さむ', None, True], [None, None, 'いです', True], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'は', None], ['楽', 'たの', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, '。', None], [None, None, 'これ', None], [None, None, 'は', None], ['楽', 'たの', None, True], [None, None, 'しいです', True], [None, None, '。', None]]
[['猫', 'ねこ', None, None], [None, None, 'は', None], [None, None, 'かわい', None], [None, None, 'い', None], [None, None, '。', None], ['猫', 'ねこ', None, None], [None, None, 'は', None], [None, None, 'かわいいです', True], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['家', 'いえ', None, None], [None, None, 'は', None], ['近', 'ちか', None, None], [None, None, 'い', None], [None, None, '。', None], ['私', 'わたし', None, None], [None, None, 'の', None], ['家', 'いえ', None, None], [None, None, 'は', None], ['近', 'ちか', None, True], [None, None, 'いです', True], [None, None, '。', None]]

  7%|▋         | 66/938 [00:42<10:21,  1.40it/s]

[['夜', 'よる', None, None], [None, None, 'の', None], ['海', 'うみ', None, None], [None, None, 'は', None], ['静', 'しず', None, None], [None, None, 'か', None], [None, None, 'だ', None], [None, None, '。', None], ['夜', 'よる', None, None], [None, None, 'の', None], ['海', 'うみ', None, None], [None, None, 'は', None], ['静', 'しず', None, True], [None, None, 'かです', True], [None, None, '。', None]]
[[None, None, 'さいき', None], [None, None, 'さん', None], [None, None, 'は', None], ['親切', 'しんせつ', None, True], [None, None, 'だ', True], [None, None, '。', None], [None, None, 'さいき', None], [None, None, 'さん', None], [None, None, 'は', None], ['親切', 'しんせつ', None, None], [None, None, 'です', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['静', 'しず', None, None], [None, None, 'か', None], [None, None, 'だ', None], [None, None, '。', None], ['彼', 'かれ', None, None], [None, None, 'は', None], ['静', 'しず', None, True], [None, None, 'かです', True], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], ['暇', 'ひま', None, True], [None, None, 'だ', True], [None, None, '。', None], ['私', 'わたし', None, None], [None, None, 'は', None], ['暇', 'ひま', None, None], [None, None, 'です', None], [None, None, '。', None]]
[['海', 'うみ', None, None], [None, None, 'が', None], ['綺麗', 'きれい', None, None], [None, None, 'だ', None], [None, None, '。', None], ['海', 'うみ', None, None], [None, None, 'が', None], ['綺麗', 'きれい', None, True], [None, None, 'です', True], [None, None, '。', None]]

  7%|▋         | 67/938 [00:43<10:05,  1.44it/s]

[['綺麗', 'きれい', None, None], [None, None, 'だった', True], [None, None, '。', None]]
[[None, None, 'トム', None], [None, None, 'だった', True], [None, None, '。', None]]
[[None, None, 'それ', None], [None, None, 'は', None], [None, None, '、', None], ['昨日', 'きのう', None, None], [None, None, 'でした', True], [None, None, '。', None]]
[['猫', 'ねこ', None, None], [None, None, 'が', None], ['大', 'だい', None, None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'だった', True], [None, None, '。', None]]
[['大変', 'たいへん', None, None], [None, None, 'だった', True], [None, None, '。', None]]

  7%|▋         | 68/938 [00:44<09:22,  1.55it/s]

[['犬', 'いぬ', None, None], [None, None, 'じゃない', True], [None, None, '。', None]]
[['先生', 'せんせい', None, None], [None, None, 'じゃない', True], [None, None, '。', None]]
[['牛肉', 'ぎゅうにく', None, None], [None, None, 'じゃない', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'この', None], ['絵', 'え', None, None], [None, None, 'は', None], [None, None, '、', None], ['綺麗', 'きれい', None, None], [None, None, 'じゃありません', True], [None, None, '。', None]]
[['好', 'す', None, None], [None, None, 'き', None], [None, None, 'な', None], [None, None, 'スポーツ', None], [None, None, 'は', None], [None, None, '、サッカー', None], [None, None, 'ではありません', True], [None, None, '。', None]]

  7%|▋         | 69/938 [00:44<08:57,  1.62it/s]

[[None, None, 'りんご', None], [None, None, 'じゃなかった', True], [None, None, '。', None]]
[['先生', 'せんせい', None, None], [None, None, 'じゃなかった', True], [None, None, '。', None]]
[['晩', 'ばん', None, None], [None, None, 'ごはん', None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'ではなかった', True], [None, None, '。', None]]
[[None, None, 'その', None], ['動物', 'どうぶつ', None, None], [None, None, 'は', None], [None, None, '、', None], ['牛', 'うし', None, None], [None, None, 'じゃなかった', True], [None, None, '。', None]]
[['宿題', 'しゅくだい', None, None], [None, None, 'は', None], ['大変', 'たいへん', None, None], [None, None, 'ではありませんでした', True], [None, None, '。', None]]

  7%|▋         | 70/938 [00:45<09:10,  1.58it/s]

[[None, None, 'コーヒー', None], [None, None, 'は', None], ['熱', 'あつ', None, True], [None, None, 'くなかった', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'それ', None], [None, None, 'は', None], [None, None, '、', None], ['安', 'やす', None, True], [None, None, 'くありませんでした', True], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['犬', 'いぬ', None, None], [None, None, 'は', None], ['強', 'つよ', None, True], [None, None, 'くなかった', True], [None, None, 'です', None], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['姉', 'あね', None, None], [None, None, 'の', None], ['家', 'いえ', None, None], [None, None, 'が', None], ['高', 'たか', None, True], [None, None, 'くなかった', True], [None, None, 'です', None], [None, None, '。', None]]
[['漫画', 'まんが', None, None], [None, None, 'を', None], ['読', 'よ', None, None], [None, None, 'む', None], [None, None, 'のは', None], ['難', 'むずか', None, True], [None, None, 'しくなかった', True], [None, None, '。', None]]

  8%|▊         | 71/938 [00:45<08:52,  1.63it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], [None, None, 'とても', None], ['親切', 'しんせつ', None, None], [None, None, 'だと', True], ['聞', 'き', None, True], [None, None, 'きました', True], [None, None, '。', None]]
[[None, None, '「', None], ['彼', 'かれ', None, None], [None, None, 'は', None], [None, None, 'ここ', None], [None, None, 'に', None], ['来', 'き', None, None], [None, None, 'ます', None], [None, None, 'か', None], [None, None, '」', None], [None, None, 'と', True], ['聞', 'き', None, True], [None, None, 'いた', True], [None, None, '。', None]]
[[None, None, '「', None], ['晩', 'ばん', None, None], [None, None, 'ごはん', None], [None, None, 'を', None], ['作', 'つく', None, None], [None, None, 'った', None], [None, None, '」', None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'った', True], [None, None, '。', None]]
[[None, None, '「', None], ['重', 'おも', None, None], [None, None, 'い', None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '」', None], [None, None, 'と', True], ['聞', 'き', None, True], [None, None, 'きました', True], [None, None, '。', None]]
[['先生', 'せんせい', None, None], [None, None, 'が', None], [None, None, '「', None], ['危', 'あぶ', None, None], [None, None, 'ない」', None], [None, None, 'と', True], ['書', 'か', None, True], [None, None, 'いた', True], [None, None, '。', None]]

  8%|▊         | 72/938 [00:46<08:31,  1.69it/s]

[[None, None, '「', None], ['乾杯', 'かんぱい', None, None], [None, None, '！」', None], [None, None, 'って', True], ['言', 'い', None, None], [None, None, 'い', None], [None, None, 'たい', None], [None, None, '。', None]]
[['先生', 'せんせい', None, None], [None, None, 'は', None], [None, None, '「おはよう！」', None], [None, None, 'って', True], ['言', 'い', None, None], [None, None, 'った', None], [None, None, '。', None]]
[[None, None, '「', None], ['明日', 'あした', None, None], [None, None, 'は', None], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'ります', None], [None, None, 'か', None], [None, None, '」', None], [None, None, 'って', True], ['聞', 'き', None, None], [None, None, 'い', None], [None, None, 'た', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], [None, None, '「', None], ['晩', 'ばん', None, None], [None, None, 'ごはん', None], [None, None, 'を', None], ['捨', 'す', None, None], [None, None, 'て', None], [None, None, 'た', None], [None, None, '」', None], [None, None, 'って', True], ['言', 'い', None, None], [None, None, 'った', None], [None, None, '。', None]]
[[None, None, '「', None], ['何時', 'なんじ', None, None], [None, None, 'から', None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '」', None], [None, None, 'って', True], ['聞', 'き', None, None], [None, None, 'いた', None], [None, None, '。', None]]

  8%|▊         | 73/938 [00:46<08:26,  1.71it/s]

[['鳥', 'とり', None, None], [None, None, 'は', None], ['飛', 'と', None, None], [None, None, 'ぶ', None], [None, None, '。', None], ['鳥', 'とり', None, None], [None, None, 'は', None], ['飛', 'と', None, True], [None, None, 'びます', True], [None, None, '。', None]]
[[None, None, 'ロック', None], [None, None, 'を', None], ['時々', 'ときどき', None, None], ['聞', 'き', None, None], [None, None, 'く', None], [None, None, '。', None], [None, None, ' ロック', None], [None, None, 'を', None], ['時々', 'ときどき', None, None], ['聞', 'き', None, True], [None, None, 'きます', True], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], ['九', 'く', None, None], ['時', 'じ', None, None], [None, None, 'に', None], [None, None, 'バナナ', None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べる', None], [None, None, '。', None], ['私', 'わたし', None, None], [None, None, 'は', None], ['九', 'く', None, None], ['時', 'じ', None, None], [None, None, 'に', None], [None, None, 'バナナ', None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べます', True], [None, None, '。', None]]
[[None, None, 'ヴァンパイア', None], [None, None, 'は', None], ['血', 'ち', None, None], [None, None, 'を', None], ['飲', 'の', None, None], [None, None, 'む', None], [None, None, '。', None], [None, None, 'ヴァンパイア', None], [None, None, 'は', None], ['血', 'ち', None, None], [None, None, 'を', None], ['飲', 'の', None, True], [None, None, 'みます', True], [None, None, '。', None]]
[[None, None, 'たなか', None], [None, None, 'さん', None], [None, None, 'は', None], ['毎週', 'まいしゅう', None, None], ['車', 'くるま', None, None], [None, None, 'を', None], ['洗', 'あら', None, None], [None, None, 'う', None], [None, None, '。', None], [None, None, 'たなか', None], [None, None, 'さん', None], [None, None, 'は', None], ['毎週', 'まいしゅう', None, None], ['車', 'くるま', None, None], [None, None, 'を', None], ['洗', 'あら', None, True], [None, None, 'います', True], [None, None, '。', None]]

  8%|▊         | 74/938 [00:47<08:13,  1.75it/s]

[['洗', 'あら', None, True], [None, None, 'った', True], ['服', 'ふく', None, None], [None, None, '。', None]]
[[None, None, 'たくさん', None], ['勉強', 'べんきょう', None, None], [None, None, 'を', None], [None, None, 'した', True], ['生徒', 'せいと', None, None], [None, None, '。', None]]
[['日本', 'にほん', None, None], [None, None, 'に', None], ['住', 'す', None, True], [None, None, 'んでいる', True], ['外国人', 'がいこくじん', None, None], [None, None, '。', None]]
[['友達', 'ともだち', None, None], [None, None, 'から', None], ['借', 'か', None, True], [None, None, 'りた', True], [None, None, 'ペン。', None]]
[['私', 'わたし', None, None], [None, None, 'が', None], ['作', 'つく', None, True], [None, None, 'った', True], ['椅子', 'いす', None, None], [None, None, '。', None]]

  8%|▊         | 75/938 [00:47<08:06,  1.77it/s]

[[None, None, 'その', None], ['帽子', 'ぼうし', None, None], [None, None, 'は', None], ['娘', 'むすめ', None, None], [None, None, 'の', True], [None, None, '(', None], ['帽子', 'ぼうし', None, None], [None, None, ')', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'あの', None], [None, None, 'パソコン', None], [None, None, 'は', None], ['君', 'きみ', None, None], [None, None, 'の', True], [None, None, '(', None], [None, None, 'パソコン', None], [None, None, ')', None], [None, None, 'でしょう', None], [None, None, '？', None]]
[['木綿', 'もめん', None, None], [None, None, 'の', None], [None, None, 'スカーフ', None], [None, None, 'は', None], ['私', 'わたし', None, None], [None, None, 'の', True], [None, None, '(スカーフ)', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, '「', None], [None, None, 'この', None], ['本', 'ほん', None, None], [None, None, 'は', None], ['誰', 'だれ', None, None], [None, None, 'の', True], [None, None, '(', None], ['本', 'ほん', None, None], [None, None, ')？」', None], [None, None, '「', None], ['先週', 'せんしゅう', None, None], [None, None, 'に', None], ['来', 'き', None, None], [None, None, 'た', None], [None, None, 'お', None], ['客', 'きゃく', None, None], [None, None, 'さん', None], [None, None, 'の', True], [None, None, '(', None], ['本', 'ほん', None, None], [None, None, ')。」', None]]
[[None, None, 'この', None], ['駐車場', 'ちゅうしゃじょう', None, None], [None, None, 'も', None], [None, None, 'あなた', None], [None, None, 'の', None], ['会社', 'かいしゃ', None, None], [None, None, 'の', True], [None, None, '(', None], ['駐車場', 'ちゅうしゃじょう', None, None], [None, None, ')', None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]

  8%|▊         | 76/938 [00:48<08:02,  1.79it/s]

[['行', 'い', None, True], [None, None, 'くな', True], [None, None, '。', None]]
[[None, None, 'ここ', None], [None, None, 'で', None], [None, None, 'サッカー', None], [None, None, 'を', None], [None, None, 'するな', True], [None, None, '。', None]]
[['泣', 'な', None, True], [None, None, 'くな', True], [None, None, '。', None]]
[['一人', 'ひとり', None, None], [None, None, 'で', None], [None, None, 'するな', True], [None, None, '。', None]]
[[None, None, '「', None], [None, None, 'これ', None], [None, None, 'は', None], ['不味', 'まず', None, None], [None, None, 'い', None], [None, None, '！」', None], [None, None, 'って', None], ['言', 'い', None, True], [None, None, 'うな', True], [None, None, '。', None]]

  8%|▊         | 77/938 [00:49<07:54,  1.81it/s]

[['一人', 'ひとり', None, None], [None, None, 'だけ', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'それ', None], [None, None, 'だけ', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'サッカー', None], [None, None, 'だけ', True], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'だけ', True], ['行', 'い', None, None], [None, None, 'きます', None], [None, None, '。', None]]
[[None, None, 'その', None], ['映画', 'えいが', None, None], [None, None, 'は', None], ['長', 'なが', None, None], [None, None, 'い', None], [None, None, 'だけ', True], [None, None, '。', None]]

  8%|▊         | 78/938 [00:49<07:57,  1.80it/s]

[[None, None, 'どれ', True], [None, None, 'が', None], [None, None, 'いい', None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'どれ', True], [None, None, 'でもいい', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'どれ', True], [None, None, 'を', None], ['選', 'えら', None, None], [None, None, 'びます', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'どれ', True], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'どれ', True], [None, None, 'で', None], [None, None, 'も', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'だ', None], [None, None, '。', None]]

  8%|▊         | 79/938 [00:50<08:50,  1.62it/s]

[[None, None, 'どこ', True], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'きます', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'すみません', None], [None, None, 'が', None], [None, None, '、', None], [None, None, 'この', None], ['本', 'ほん', None, None], [None, None, 'は', None], [None, None, 'どこ', True], [None, None, 'に', None], [None, None, 'あります', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'ここ', None], [None, None, 'は', None], [None, None, 'どこ', True], [None, None, '？', None]]
[[None, None, 'どこ', True], [None, None, 'が', None], [None, None, 'いい', None], [None, None, '？', None]]
[['美味', 'おい', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'レストラン', None], [None, None, 'は', None], [None, None, 'どこ', True], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]

  9%|▊         | 80/938 [00:50<08:28,  1.69it/s]

[[None, None, 'どの', True], ['寿司屋', 'すしや', None, None], [None, None, 'が', None], [None, None, 'いい', None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'どの', True], [None, None, 'レストラン', None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, '？', None]]
[[None, None, 'どの', True], [None, None, 'ブランド', None], [None, None, 'を', None], ['選', 'えら', None, None], [None, None, 'びます', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'どの', True], [None, None, 'パソコン', None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'どの', True], [None, None, 'お', None], ['茶', 'ちゃ', None, None], [None, None, 'を', None], ['飲', 'の', None, None], [None, None, 'み', None], [None, None, 'ます', None], [None, None, 'か', None], [None, None, '。', None]]

  9%|▊         | 81/938 [00:51<08:22,  1.71it/s]

[[None, None, 'あの', None], [None, None, 'カバ', None], [None, None, 'は', None], ['太', 'ふと', None, True], [None, None, 'っていない', True], [None, None, '。', None]]
[[None, None, 'バス', None], [None, None, 'は', None], ['今', 'いま', None, None], ['大阪', 'おおさか', None, None], [None, None, 'に', None], ['来', 'き', None, True], [None, None, 'ています', True], [None, None, '。', None]]
[[None, None, 'パーティー', None], [None, None, 'は', None], ['始', 'はじ', None, True], [None, None, 'まっている', True], [None, None, '。', None]]
[['電車', 'でんしゃ', None, None], [None, None, 'は', None], ['東京', 'とうきょう', None, None], [None, None, 'に', None], ['行', 'い', None, True], [None, None, 'っています', True], [None, None, '。', None]]
[[None, None, 'ななさん', None], [None, None, 'の', None], [None, None, 'バナナ', None], [None, None, 'は', None], ['腐', 'くさ', None, True], [None, None, 'っています', True], [None, None, '。', None]]

  9%|▊         | 82/938 [00:52<08:11,  1.74it/s]

[['日本語', 'にほんご', None, None], [None, None, 'の', None], ['勉強', 'べんきょう', None, None], [None, None, 'を', None], [None, None, 'してから', True], [None, None, '、', None], ['日本', 'にほん', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'きます', None], [None, None, '。', None]]
[['日本', 'にほん', None, None], [None, None, 'に', None], ['行', 'い', None, True], [None, None, 'ってから', True], [None, None, '、', None], ['日本語', 'にほんご', None, None], [None, None, 'の', None], ['勉強', 'べんきょう', None, None], [None, None, 'を', None], [None, None, 'します', None], [None, None, '。', None]]
[[None, None, 'この', None], ['本', 'ほん', None, None], [None, None, 'を', None], ['読', 'よ', None, True], [None, None, 'んでから', True], [None, None, '、', None], ['返', 'かえ', None, None], [None, None, 'す', None], [None, None, '。', None]]
[['暇', 'ひま', None, None], [None, None, 'に', None], [None, None, 'なってから', True], [None, None, '、ゆっくり', None], ['旅行', 'りょこう', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'き', None], [None, None, 'たい', None], [None, None, '。', None]]
[['雪', 'ゆき', None, None], [None, None, 'が', None], ['降', 'ふ', None, True], [None, None, 'ってから', True], [None, None, '、スキーに', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, '。', None]]

  9%|▉         | 83/938 [00:52<08:02,  1.77it/s]

[['晩', 'ばん', None, None], [None, None, 'ご', None], ['飯', 'はん', None, None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べて', True], ['歯', 'は', None, None], [None, None, 'を', None], ['磨', 'みが', None, None], [None, None, 'いた', None], [None, None, '。', None]]
[[None, None, 'ともこ', None], [None, None, 'は', None], ['鍵', 'かぎ', None, None], [None, None, 'を', None], [None, None, 'かけて', True], ['出', 'で', None, None], [None, None, 'かけました。', None]]
[['明日', 'あした', None, None], [None, None, 'は', None], ['９時', 'くじ', None, None], [None, None, 'に', None], ['起', 'お', None, None], [None, None, 'き', None], [None, None, 'て', True], [None, None, '、', None], ['朝', 'あさ', None, None], [None, None, 'ごはん', None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'て', True], ['買', 'か', None, None], [None, None, 'い', None], ['物', 'もの', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'きます', None], [None, None, '。', None]]
[[None, None, '「', None], ['東京', 'とうきょう', None, None], [None, None, 'に', None], ['行', 'い', None, True], [None, None, 'って', True], ['何', 'なに', None, None], [None, None, 'を', None], [None, None, 'し', None], [None, None, 'た', None], [None, None, 'の？」', None]]
[[None, None, 'ひとみさん', None], [None, None, 'の', None], [None, None, 'お', None], ['母', 'かあ', None, None], [None, None, 'さん', None], [None, None, 'に', None], ['会', 'あ', None, True], [None, None, 'って', True], ['一緒', 'いっしょ', None, None], [None, None, 'に', None], ['戻', 'もど', None, None], [None, None, 'り', None], [None, None, 'ました', None], [None, None, '。', None]]

  9%|▉         | 84/938 [00:53<07:53,  1.80it/s]

[[None, None, 'もう', True], ['学校', 'がっこう', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'き', None], [None, None, 'ました', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'もう', True], [None, None, 'その', None], ['本', 'ほん', None, None], [None, None, 'を', None], ['読', 'よ', None, None], [None, None, 'んだ', None], [None, None, '。', None]]
[[None, None, 'もう', True], [None, None, 'コーヒー', None], [None, None, 'を', None], ['作', 'つく', None, None], [None, None, 'り', None], [None, None, 'ました', None], [None, None, '。', None]]
[[None, None, 'もう', True], [None, None, 'し', None], [None, None, 'ました', None], [None, None, '。', None]]
[[None, None, 'もう', True], ['帰', 'かえ', None, None], [None, None, 'った', None], [None, None, '。', None]]

  9%|▉         | 85/938 [00:53<07:42,  1.85it/s]

[['冷蔵庫', 'れいぞうこ', None, None], [None, None, 'に', None], [None, None, 'ケーキが', None], [None, None, 'まだ', True], [None, None, 'あります', None], [None, None, '。', None]]
[[None, None, 'まだ', True], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'ています', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, '「お', None], ['前', 'まえ', None, None], [None, None, 'に', None], [None, None, 'は', None], [None, None, 'まだ', True], ['早', 'はや', None, None], [None, None, 'い', None], [None, None, 'よ', None], [None, None, '。」', None]]
[[None, None, 'まだ', True], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'っ', None], [None, None, 'ている', None], [None, None, 'の', None], [None, None, '？', None]]
[[None, None, 'まだ', True], ['足', 'あし', None, None], [None, None, 'が', None], ['痛', 'いた', None, None], [None, None, 'い', None], [None, None, '。', None]]

  9%|▉         | 86/938 [00:54<07:41,  1.85it/s]

[[None, None, 'まだ', True], ['食', 'た', None, True], [None, None, 'べていません', True], [None, None, '。', None]]
[[None, None, 'その', None], ['本', 'ほん', None, None], [None, None, 'を', None], [None, None, 'まだ', True], ['読', 'よ', None, True], [None, None, 'んでいません', True], [None, None, '。', None]]
[[None, None, 'まだ', True], ['勉強', 'べんきょう', None, True], [None, None, 'していません', True], [None, None, '。', None]]
[[None, None, 'この', None], ['漢字', 'かんじ', None, None], [None, None, 'を', None], [None, None, 'まだ', True], ['習', 'なら', None, True], [None, None, 'っていません', True], [None, None, '。', None]]
[['学校', 'がっこう', None, None], [None, None, 'に', None], [None, None, 'まだ', True], ['行', 'い', None, True], [None, None, 'っていません', True], [None, None, '。', None]]

  9%|▉         | 87/938 [00:54<07:45,  1.83it/s]

[['高', 'たか', None, True], [None, None, 'くてもいい', True], [None, None, '。', None]]
[['何', 'なん', None, None], [None, None, 'でもいい', True], [None, None, 'です', None], [None, None, '。', None]]
[['誰', 'だれ', None, None], [None, None, 'でもいい', True], [None, None, '。', None]]
[['水曜日', 'すいようび', None, None], [None, None, 'でもいい', True], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[['冷', 'つめ', None, True], [None, None, 'たくてもいい', True], [None, None, '。', None]]

  9%|▉         | 88/938 [00:55<07:51,  1.80it/s]

[['日本', 'にほん', None, None], [None, None, 'に', None], ['行', 'い', None, True], [None, None, 'きたい', True], [None, None, '。', None]]
[['来年', 'らいねん', None, None], ['日本', 'にほん', None, None], [None, None, 'に', None], ['行', 'い', None, True], [None, None, 'きたい', True], [None, None, '。', None]]
[['早', 'はや', None, None], [None, None, 'く', None], ['食', 'た', None, True], [None, None, 'べたい', True], [None, None, '。', None]]
[[None, None, 'サッカー', None], [None, None, 'を', None], [None, None, 'したい', True], [None, None, 'です', None], [None, None, '。', None]]
[['文法', 'ぶんぽう', None, None], [None, None, 'を', None], ['勉強', 'べんきょう', None, None], [None, None, 'したい', True], [None, None, 'です', None], [None, None, '。', None]]

  9%|▉         | 89/938 [00:55<07:56,  1.78it/s]

[['家', 'いえ', None, None], [None, None, 'で', None], [None, None, 'ゲーム', None], [None, None, 'を', None], [None, None, 'し', None], [None, None, 'たり', True], [None, None, '、', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'たり', True], [None, None, 'した', None], [None, None, '。', None]]
[['音楽', 'おんがく', None, None], [None, None, 'を', None], ['聞', 'き', None, None], [None, None, 'い', None], [None, None, 'たり', None], [None, None, '、', None], ['本', 'ほん', None, None], [None, None, 'を', None], ['読', 'よ', None, True], [None, None, 'んだりしました', True], [None, None, '。', None]]
[['掃除', 'そうじ', None, None], [None, None, 'を', None], [None, None, 'し', None], [None, None, 'たり', True], [None, None, '、', None], ['洗濯', 'せんたく', None, None], [None, None, 'を', None], [None, None, 'し', None], [None, None, 'たり', True], [None, None, 'した', None], [None, None, '。', None]]
[['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, True], [None, None, 'ったり', True], [None, None, '、', None], ['止', 'や', None, None], [None, None, 'ん', None], [None, None, 'だりする', None], [None, None, 'ね', None], [None, None, '。', None]]
[['今日', 'きょう', None, None], [None, None, 'は', None], [None, None, '、', None], ['勉強', 'べんきょう', None, None], [None, None, 'し', None], [None, None, 'たり', True], [None, None, '、', None], ['練習', 'れんしゅう', None, None], [None, None, 'し', None], [None, None, 'たり', True], [None, None, 'する', None], [None, None, '。', None]]

 10%|▉         | 90/938 [00:56<07:53,  1.79it/s]

[[None, None, 'いいえ、', None], [None, None, 'けっこう', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'この', None], [None, None, 'カバン', None], [None, None, 'は', None], [None, None, 'けっこう', True], ['高', 'たか', None, None], [None, None, 'い', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'それ', None], [None, None, 'は', None], [None, None, 'けっこう', True], ['面白', 'おもしろ', None, None], [None, None, 'い', None], [None, None, 'です', None], [None, None, 'ね', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], [None, None, '、', None], [None, None, 'けっこう', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'この', None], ['公園', 'こうえん', None, None], [None, None, 'は', None], [None, None, 'けっこう', True], ['広', 'ひろ', None, None], [None, None, 'い', None], [None, None, 'です', None], [None, None, '。', None]]

 10%|▉         | 91/938 [00:56<07:52,  1.79it/s]

[[None, None, 'たくさん', True], [None, None, 'あります', None], [None, None, 'から', None], [None, None, '。', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'てください', None], [None, None, '。', None]]
[[None, None, 'たくさん', True], ['雪', 'ゆき', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'り', None], [None, None, 'ました', None], [None, None, '。', None]]
[[None, None, 'たくさん', True], ['仕事', 'しごと', None, None], [None, None, 'を', None], [None, None, 'します', None], [None, None, '。', None]]
[['日本語', 'にほんご', None, None], [None, None, 'の', None], ['勉強', 'べんきょう', None, None], [None, None, 'を', None], [None, None, 'たくさん', True], [None, None, 'し', None], [None, None, 'ました', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], [None, None, 'たくさんの', True], ['本', 'ほん', None, None], [None, None, 'を', None], ['読', 'よ', None, None], [None, None, 'む', None], [None, None, '。', None]]

 10%|▉         | 92/938 [00:57<08:18,  1.70it/s]

[['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'る', None], [None, None, 'まえに', True], [None, None, '「いただ', None], [None, None, 'きます', None], [None, None, '」', None], [None, None, 'と', None], ['言', 'い', None, None], [None, None, 'う。', None]]
[['帰', 'かえ', None, None], [None, None, 'る', None], [None, None, 'まえに', True], ['勉強', 'べんきょう', None, None], [None, None, 'を', None], [None, None, 'する', None], [None, None, '。', None]]
[[None, None, 'まえに', True], [None, None, 'ここ', None], [None, None, 'に', None], ['来', 'き', None, None], [None, None, 'ました', None], [None, None, '。', None]]
[['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'る', None], [None, None, 'まえに', True], ['手', 'て', None, None], [None, None, 'を', None], ['洗', 'あら', None, None], [None, None, 'います', None], [None, None, '。', None]]
[[None, None, 'テレビ', None], [None, None, 'のまえに', True], [None, None, '、', None], ['机', 'つくえ', None, None], [None, None, 'があります', None], [None, None, '。', None]]

 10%|▉         | 93/938 [00:58<08:17,  1.70it/s]

[['何時', 'なんじ', None, None], [None, None, 'ぐらい', True], [None, None, 'に', None], ['来', 'き', None, None], [None, None, 'ます', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'あと', None], ['３０', 'さんじゅっ', None, None], ['分', 'ぷん', None, None], [None, None, 'ぐらい', True], [None, None, 'で', None], ['行', 'い', None, None], [None, None, 'きます', None], [None, None, '。', None]]
[['毎週', 'まいしゅう', None, None], [None, None, 'コーヒー', None], [None, None, 'は', None], [None, None, 'どの', None], [None, None, 'くらい', True], ['飲', 'の', None, None], [None, None, 'む', None], [None, None, '？', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['１０', 'じゅっ', None, None], ['歳', 'さい', None, None], [None, None, 'くらい', True], [None, None, 'だろう', None], [None, None, '。', None]]
[['一週間', 'いっしゅうかん', None, None], [None, None, 'に、', None], ['五', 'ご', None, None], ['時間', 'じかん', None, None], [None, None, 'ぐらい', True], [None, None, 'スポーツ', None], [None, None, 'を', None], [None, None, 'する', None], [None, None, '。', None]]

 10%|█         | 94/938 [00:58<08:10,  1.72it/s]

[[None, None, 'どこ', None], [None, None, 'まで', True], ['行', 'い', None, None], [None, None, 'く', None], [None, None, '？', None]]
[['７', 'しち', None, None], ['時', 'じ', None, None], [None, None, 'まで', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'この', None], [None, None, 'セール', None], [None, None, 'は', None], ['金曜日', 'きんようび', None, None], [None, None, 'まで', True], [None, None, 'です', None], [None, None, '。', None]]
[['朝', 'あさ', None, None], [None, None, 'まで', True], ['寝', 'ね', None, None], [None, None, 'ました', None], [None, None, '。', None]]
[['８', 'はち', None, None], ['時', 'じ', None, None], [None, None, 'まで', True], [None, None, '、テレビ', None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'る', None], [None, None, '。', None]]

 10%|█         | 95/938 [00:59<08:02,  1.75it/s]

[['映画', 'えいが', None, None], [None, None, 'が', None], ['始', 'はじ', None, None], [None, None, 'ま', None], [None, None, 'る', None], [None, None, 'まで', True], [None, None, '、', None], ['友達', 'ともだち', None, None], [None, None, 'と', None], ['話', 'はな', None, None], [None, None, 'した', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'が', None], ['来', 'く', None, None], [None, None, 'る', None], [None, None, 'まで', True], [None, None, '、', None], ['日本語', 'にほんご', None, None], [None, None, 'を', None], ['勉強', 'べんきょう', None, None], [None, None, 'します', None], [None, None, '。', None]]
[[None, None, 'カタカナ', None], [None, None, 'を', None], ['覚', 'おぼ', None, None], [None, None, 'え', None], [None, None, 'る', None], [None, None, 'まで', True], [None, None, '、', None], ['私', 'わたし', None, None], [None, None, 'は', None], ['寝', 'ね', None, None], [None, None, 'ない', None], [None, None, '。', None]]
[[None, None, 'その', None], ['漢字', 'かんじ', None, None], [None, None, 'を', None], ['覚', 'おぼ', None, None], [None, None, 'え', None], [None, None, 'る', None], [None, None, 'まで', True], [None, None, '、', None], ['辞書', 'じしょ', None, None], [None, None, 'を', None], ['使', 'つか', None, None], [None, None, 'う', None], [None, None, '。', None]]
[[None, None, 'お', None], ['風呂', 'ふろ', None, None], [None, None, 'に', None], ['入', 'はい', None, None], [None, None, 'る', None], [None, None, 'まで', True], [None, None, '、ゆっくりし', None], [None, None, 'たい', None], [None, None, '。', None]]

 10%|█         | 96/938 [00:59<08:07,  1.73it/s]

[[None, None, 'ここ', None], [None, None, 'は', None], [None, None, 'ゴミ', None], [None, None, 'が', None], ['多', 'おお', None, None], [None, None, 'すぎる', True], [None, None, '。', None]]
[[None, None, 'この', None], ['寿司', 'すし', None, None], [None, None, 'は', None], ['美味', 'おい', None, True], [None, None, 'しすぎる', True], [None, None, '。', None]]
[[None, None, 'その', None], ['冗談', 'じょうだん', None, None], [None, None, 'は', None], ['面白', 'おもしろ', None, True], [None, None, 'くなさすぎた', True], [None, None, '。', None]]
[[None, None, 'いつも', None], ['週末', 'しゅうまつ', None, None], [None, None, 'に', None], ['寝', 'ね', None, True], [None, None, 'すぎます', True], [None, None, '。', None]]
[['漢字', 'かんじ', None, None], [None, None, 'を', None], ['書', 'か', None, True], [None, None, 'きすぎた', True], [None, None, 'から', None], [None, None, '、', None], ['手', 'て', None, None], [None, None, 'が', None], ['痛', 'いた', None, None], [None, None, 'い', None], [None, None, '。', None]]

 10%|█         | 97/938 [01:00<08:07,  1.72it/s]

[['何', 'なに', None, None], [None, None, 'にする', True], [None, None, '？', None]]
[['今日', 'きょう', None, None], [None, None, 'の', None], ['晩', 'ばん', None, None], [None, None, 'ごはん', None], [None, None, 'は', None], ['何', 'なに', None, None], [None, None, 'にする', True], [None, None, '？', None]]
[[None, None, 'この', None], [None, None, 'かばん', None], [None, None, 'にします', True], [None, None, '。', None]]
[['明日', 'あした', None, None], [None, None, 'の', None], ['朝', 'あさ', None, None], [None, None, 'ごはん', None], [None, None, 'は', None], ['魚', 'さかな', None, None], [None, None, 'にします', True], [None, None, '。', None]]
[[None, None, 'この', None], [None, None, 'レストラン', None], [None, None, 'にします', True], [None, None, '。', None]]

 10%|█         | 98/938 [01:01<08:00,  1.75it/s]

[['難', 'むずか', None, True], [None, None, 'しくなる', True], [None, None, '。', None]]
[['嬉', 'うれ', None, True], [None, None, 'しくなる', True], [None, None, '。', None]]
[['早', 'はや', None, True], [None, None, 'くなる', True], [None, None, '。', None]]
[[None, None, 'よくなる', True], [None, None, '。', None]]
[['綺麗', 'きれい', None, True], [None, None, 'になる', True], [None, None, '。', None]]

 11%|█         | 99/938 [01:01<08:09,  1.71it/s]

[[None, None, 'この', None], ['中', 'なか', None, None], [None, None, 'で', None], ['一番', 'いちばん', None, True], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'な', None], [None, None, ' ', None], ['食', 'た', None, None], [None, None, 'べ', None], ['物', 'もの', None, None], [None, None, 'は', None], ['何', 'なに', None, None], [None, None, '？', None]]
[['中華', 'ちゅうか', None, None], ['料理', 'りょうり', None, None], [None, None, 'の', True], ['中', 'なか', None, True], [None, None, 'で', True], ['何', 'なに', None, None], [None, None, 'が', None], ['一番', 'いちばん', None, None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[['飲', 'の', None, None], [None, None, 'み', None], ['物', 'もの', None, None], [None, None, 'の', True], ['中', 'なか', None, True], [None, None, 'で', True], ['一番', 'いちばん', None, True], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'な', None], [None, None, 'のは', None], ['何', 'なん', None, None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'お', None], ['茶', 'ちゃ', None, None], [None, None, 'の', True], ['中', 'なか', None, True], [None, None, 'で', True], ['一番', 'いちばん', None, True], ['美味', 'おい', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'のは', None], ['何', 'なん', None, None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[['国', 'くに', None, None], [None, None, 'の', True], ['中', 'なか', None, True], [None, None, 'で', True], ['一番', 'いちばん', None, True], ['人口', 'じんこう', None, None], [None, None, 'が', None], ['多', 'おお', None, None], [None, None, 'い', None], [None, None, 'のは', None], [None, None, 'どれ', None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]

 11%|█         | 100/938 [01:02<08:02,  1.73it/s]

[[None, None, 'この', None], [None, None, 'パン', None], [None, None, 'より', None], [None, None, 'その', None], [None, None, 'パン', None], [None, None, 'のほうが', True], ['美味', 'おい', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'バスケットボール', None], [None, None, 'より', True], [None, None, 'サッカー', None], [None, None, 'の', None], [None, None, 'ほうが', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, '。', None]]
[[None, None, 'ユキ', None], [None, None, 'より', None], [None, None, 'リュウト', None], [None, None, 'のほうが', True], ['賢', 'かしこ', None, None], [None, None, 'い', None], [None, None, '。', None]]
[['月曜日', 'げつようび', None, None], [None, None, 'より', None], [None, None, '、', None], ['日曜日', 'にちようび', None, None], [None, None, 'のほうが', True], ['好', 'す', None, None], [None, None, 'き', None], [None, None, '。', None]]
[[None, None, 'あそこ', None], [None, None, 'の', None], [None, None, ' ', None], ['公園', 'こうえん', None, None], [None, None, 'より', None], [None, None, '、', None], ['家', 'いえ', None, None], [None, None, 'に', None], ['近', 'ちか', None, None], [None, None, 'い', None], ['公園', 'こうえん', None, None], [None, None, 'のほうが', True], ['広', 'ひろ', None, None], [None, None, 'い', None], [None, None, '。', None]]

 11%|█         | 101/938 [01:03<08:48,  1.58it/s]

[[None, None, 'なにか', True], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'る', None], [None, None, '？', None]]
[['私', 'わたし', None, None], [None, None, 'が', None], [None, None, 'なにか', True], ['嫌', 'いや', None, None], [None, None, 'な', None], [None, None, 'こと', None], [None, None, 'を', None], [None, None, 'し', None], [None, None, 'ました', None], [None, None, 'か', None], [None, None, '？', None]]
[[None, None, 'いいえ、', None], [None, None, 'なにも', True], [None, None, 'し', None], [None, None, 'てい', None], [None, None, 'ません', None], [None, None, 'よ', None], [None, None, '。', None]]
[['日本', 'にほん', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'っ', None], [None, None, 'て', None], [None, None, '、', None], [None, None, 'なにか', True], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'たい', None], [None, None, 'もの', None], [None, None, 'があります', None], [None, None, 'か', None], [None, None, '。', None]]
[['頑張', 'がんば', None, None], [None, None, 'っ', None], [None, None, 'て', None], ['勉強', 'べんきょう', None, None], [None, None, 'した', None], [None, None, 'けど', None], [None, None, 'なにも', True], [None, None, 'わから', None], [None, None, 'ない', None], [None, None, '。', None]]

 11%|█         | 102/938 [01:03<08:28,  1.64it/s]

[[None, None, '「', None], [None, None, 'どこ', None], [None, None, 'かに', True], ['友達', 'ともだち', None, None], [None, None, 'がいる', None], [None, None, 'のです', None], [None, None, 'か', None], [None, None, '。」', None], [None, None, '「', None], [None, None, 'どこ', None], [None, None, 'に', None], [None, None, 'も', None], [None, None, 'いません', None], [None, None, '。」', None]]
[[None, None, '「', None], ['誰', 'だれ', None, None], [None, None, 'か', None], [None, None, 'に', None], [None, None, 'その', None], [None, None, 'こと', None], [None, None, 'を', None], ['言', 'い', None, None], [None, None, 'い', None], [None, None, 'ました', None], [None, None, 'か', None], [None, None, '。」', None], [None, None, '「いいえ、', None], ['誰', 'だれ', None, None], [None, None, 'にも', True], ['言', 'い', None, None], [None, None, 'っ', None], [None, None, 'ていません', None], [None, None, '。」', None]]
[[None, None, '「', None], [None, None, 'どこ', None], [None, None, 'かに', True], [None, None, 'ある', None], [None, None, 'でしょう', None], [None, None, '。」', None], [None, None, '「', None], [None, None, 'どこ', None], [None, None, 'に', None], [None, None, 'も', None], [None, None, 'ありません', None], [None, None, 'よ', None], [None, None, '。」', None]]
[[None, None, '「', None], ['紙', 'かみ', None, None], [None, None, 'を', None], ['誰', 'だれ', None, None], [None, None, 'か', None], [None, None, 'に', None], ['渡', 'わた', None, None], [None, None, 'し', None], [None, None, 'ました', None], [None, None, 'か', None], [None, None, '。」', None], [None, None, '「', None], ['誰', 'だれ', None, None], [None, None, 'にも', True], ['渡', 'わた', None, None], [None, None, 'し', None], [None, None, 'ていません', None], [None, None, '。」', None]]
[[None, None, '「', None], [None, None, 'どこ', None], [None, None, 'かへ', True], ['出', 'で', None, None], [None, None, 'かけ', None], [None, None, 'ます', None], [None, None, 'か', None], [None, None, '。」', None], [None, None, '「', None], [None, None, 'どこ', None], [None, None, 'へ', None], [None, None, 'も', None], ['行', 'い', None, None], [None, None, 'き', None], [None, None, 'たくない', None], [None, None, 'よ', None], [None, None, '。」', None]]

 11%|█         | 103/938 [01:04<08:27,  1.65it/s]

[[None, None, 'サッカー', None], [None, None, 'を', None], [None, None, 'しましょう', True], [None, None, '。', None]]
[[None, None, 'この', None], [None, None, 'レストラン', None], [None, None, 'で', None], ['寿司', 'すし', None, None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べましょう', True], [None, None, '。', None]]
[[None, None, 'ごはん', None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べましょう', True], [None, None, '。', None]]
[[None, None, 'バス', None], [None, None, 'で', None], ['行', 'い', None, True], [None, None, 'きましょう', True], [None, None, '。', None]]
[['難', 'むずか', None, None], [None, None, 'し', None], [None, None, 'い', None], ['漢字', 'かんじ', None, None], [None, None, 'を', None], ['覚', 'おぼ', None, True], [None, None, 'えましょう', True], [None, None, '。', None]]

 11%|█         | 104/938 [01:04<08:11,  1.70it/s]

[['日本語', 'にほんご', None, None], [None, None, 'で', None], ['話', 'はな', None, True], [None, None, 'しましょうか', True], [None, None, '。', None]]
[['明日', 'あした', None, None], [None, None, 'ビーチに', None], ['行', 'い', None, True], [None, None, 'きましょうか', True], [None, None, '。', None]]
[[None, None, 'インド', None], ['料理', 'りょうり', None, None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べにいきましょうか', True], [None, None, '。', None]]
[['９時', 'くじ', None, None], ['前', 'まえ', None, None], [None, None, 'に', None], ['帰', 'かえ', None, True], [None, None, 'りましょうか', True], [None, None, '。', None]]
[['図書館', 'としょかん', None, None], [None, None, 'で', None], ['勉強', 'べんきょう', None, None], [None, None, 'しましょうか', True], [None, None, '。', None]]

 11%|█         | 105/938 [01:05<08:08,  1.70it/s]

[['寿司', 'すし', None, None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べに', True], ['行', 'い', None, True], [None, None, 'きませんか', True], [None, None, '。', None]]
[[None, None, 'サッカー', None], [None, None, 'を', None], [None, None, 'しませんか', True], [None, None, '。', None]]
[['一緒', 'いっしょ', None, None], [None, None, 'に', None], ['文法', 'ぶんぽう', None, None], [None, None, 'を', None], ['勉強', 'べんきょう', None, None], [None, None, 'しませんか', True], [None, None, '。', None]]
[[None, None, 'お', None], ['風呂', 'ふろ', None, None], [None, None, 'に', None], ['一緒', 'いっしょ', None, None], [None, None, 'に', None], ['入', 'はい', None, True], [None, None, 'りませんか', True], [None, None, '。', None]]
[['金曜日', 'きんようび', None, None], [None, None, 'に', None], [None, None, '、', None], ['買', 'か', None, None], [None, None, 'い', None], ['物', 'もの', None, None], [None, None, 'に', None], ['行', 'い', None, True], [None, None, 'きませんか', True], [None, None, '。', None]]

 11%|█▏        | 106/938 [01:05<08:02,  1.73it/s]

[[None, None, 'これ', None], [None, None, 'を', None], ['見', 'み', None, True], [None, None, 'てもいい', True], [None, None, '？', None]]
[['質問', 'しつもん', None, None], [None, None, 'を', None], [None, None, 'してもいい', True], [None, None, '？', None]]
[['暑', 'あつ', None, None], [None, None, 'い', None], [None, None, 'です', None], [None, None, '。', None], ['水', 'みず', None, None], [None, None, 'を', None], ['飲', 'の', None, True], [None, None, 'んでもいい', True], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'あそこ', None], [None, None, 'で', None], ['遊', 'あそ', None, True], [None, None, 'んでもいい', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'あそこ', None], [None, None, 'でスポーツ', None], [None, None, 'を', None], [None, None, 'してもいい', True], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]

 11%|█▏        | 107/938 [01:06<08:06,  1.71it/s]

[[None, None, 'この', None], ['本', 'ほん', None, None], [None, None, 'を', None], ['読', 'よ', None, True], [None, None, 'んでください', True], [None, None, '。', None]]
[['食', 'た', None, True], [None, None, 'べてください', True], [None, None, '。', None]]
[[None, None, 'やめてください', True], [None, None, '。', None]]
[[None, None, 'この', None], [None, None, 'えんぴつ', None], [None, None, 'を', None], ['使', 'つか', None, True], [None, None, 'ってください', True], [None, None, '。', None]]
[[None, None, 'ここ', None], [None, None, 'から', None], [None, None, '、', None], ['写真', 'しゃしん', None, None], [None, None, 'を', None], ['撮', 'と', None, True], [None, None, 'ってください', True], [None, None, '。', None]]

 12%|█▏        | 108/938 [01:07<08:08,  1.70it/s]

[['行', 'い', None, True], [None, None, 'かないでください', True], [None, None, '。', None]]
[[None, None, 'ここ', None], [None, None, 'で', None], [None, None, 'サッカー', None], [None, None, 'を', None], [None, None, 'しないでください', True], [None, None, '。', None]]
[['泣', 'な', None, True], [None, None, 'かないでください', True], [None, None, '。', None]]
[['一人', 'ひとり', None, None], [None, None, 'に', None], [None, None, 'しないでください', True], [None, None, '。', None]]
[[None, None, 'それ', None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べないでください', True], [None, None, '。', None]]

 12%|█▏        | 109/938 [01:07<08:00,  1.72it/s]

[[None, None, 'そこ', None], [None, None, 'に', None], ['入', 'はい', None, True], [None, None, 'ってはいけない', True], [None, None, '。', None]]
[[None, None, 'クジラ', None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べてはいけない', True], [None, None, '。', None]]
[[None, None, 'この', None], [None, None, 'ビル', None], [None, None, 'に', None], ['入', 'はい', None, True], [None, None, 'ってはいけない', True], [None, None, '。', None]]
[['晩', 'ばん', None, None], [None, None, 'ごはん', None], [None, None, 'の', None], ['前', 'まえ', None, None], [None, None, 'に', None], [None, None, '、お', None], ['菓子', 'かし', None, None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べてはいけない', True], [None, None, '。', None]]
[[None, None, 'この', None], ['池', 'いけ', None, None], [None, None, 'で', None], ['泳', 'およ', None, True], [None, None, 'いではいけません', True], [None, None, '。', None]]

 12%|█▏        | 110/938 [01:08<08:01,  1.72it/s]

[[None, None, 'テスト', None], [None, None, 'の', None], ['前', 'まえ', None, None], [None, None, 'に', None], [None, None, '、よく', None], ['寝', 'ね', None, True], [None, None, 'なくてはいけない', True], [None, None, '。', None]]
[['１２', 'じゅうに', None, None], ['月', 'がつ', None, None], [None, None, 'になっ', None], [None, None, 'てから', None], [None, None, '、', None], ['暖房', 'だんぼう', None, None], [None, None, 'を', None], [None, None, 'つけなくてはいけない', True], [None, None, '。', None]]
[['来週', 'らいしゅう', None, None], [None, None, 'は', None], ['試合', 'しあい', None, None], [None, None, 'がある', None], [None, None, 'ので', None], [None, None, '、', None], [None, None, 'たくさん', None], ['練習', 'れんしゅう', None, None], [None, None, 'しなくてはいけない', True], [None, None, '。', None]]
[['今日', 'きょう', None, None], [None, None, 'は', None], [None, None, 'いい', None], ['天気', 'てんき', None, None], [None, None, 'だ', None], [None, None, 'から', None], [None, None, '、', None], ['外', 'そと', None, None], [None, None, 'で', None], ['遊', 'あそ', None, True], [None, None, 'ばなくてはいけない', True], [None, None, '。', None]]
[[None, None, 'まだ', None], [None, None, 'やり', None], [None, None, 'たい', None], [None, None, 'ことがある', None], [None, None, 'けど', None], [None, None, '、', None], [None, None, 'もう', None], ['寝', 'ね', None, True], [None, None, 'なくてはいけない', True], [None, None, '。', None]]

 12%|█▏        | 111/938 [01:08<08:03,  1.71it/s]

[['毎日', 'まいにち', None, None], ['勉強', 'べんきょう', None, None], [None, None, 'を', None], [None, None, 'しなくてはならない', True], [None, None, '。', None]]
[['３', 'さん', None, None], ['時', 'じ', None, None], ['半', 'はん', None, None], [None, None, 'までに', None], [None, None, '、', None], ['銀行', 'ぎんこう', None, None], [None, None, 'に', None], ['行', 'い', None, True], [None, None, 'かなくてはならない', True], [None, None, '。', None]]
[[None, None, 'もう', None], ['二時', 'にじ', None, None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '！', None], [None, None, 'まだ', None], [None, None, 'お', None], ['弁当', 'べんとう', None, None], ['食', 'た', None, None], [None, None, 'べてない', None], [None, None, 'です', None], [None, None, '。', None], ['食', 'た', None, True], [None, None, 'べなくてはならない', True], [None, None, '。', None]]
[['京都', 'きょうと', None, None], [None, None, 'で', None], ['電車', 'でんしゃ', None, None], [None, None, 'を', None], ['降', 'お', None, True], [None, None, 'りなくてはならない', True], [None, None, '。', None]]
[['君', 'きみ', None, None], [None, None, 'が', None], ['決', 'き', None, True], [None, None, 'めなくてはならない', True], [None, None, 'よ', None], [None, None, '。', None]]

 12%|█▏        | 112/938 [01:09<07:53,  1.74it/s]

[[None, None, 'お', None], ['医者', 'いしゃ', None, None], [None, None, 'さん', None], [None, None, 'に', None], ['聞', 'き', None, True], [None, None, 'いたほうがいい', True], [None, None, '。', None]]
[['帰', 'かえ', None, True], [None, None, 'ったほうがいい', True], [None, None, '。', None]]
[['朝', 'あさ', None, None], [None, None, 'ごはん', None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べたほうがいい', True], [None, None, '。', None]]
[['自分', 'じぶん', None, None], [None, None, 'の', None], ['皿', 'さら', None, None], [None, None, 'を', None], ['洗', 'あら', None, True], [None, None, 'ったほうがいい', True], [None, None, '。', None]]
[[None, None, 'それ', None], [None, None, 'は', None], ['返', 'かえ', None, True], [None, None, 'したほうがいい', True], [None, None, 'だろう', None], [None, None, '。', None]]

 12%|█▏        | 113/938 [01:09<07:47,  1.76it/s]

[[None, None, 'その', None], ['肉', 'にく', None, None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べないほうがいい', True], [None, None, '。', None]]
[[None, None, 'タバコ', None], [None, None, 'を', None], ['吸', 'す', None, True], [None, None, 'わないほうがいい', True], [None, None, '。', None]]
[['汚', 'よご', None, None], [None, None, 'れ', None], [None, None, 'ないほうがいい', True], [None, None, '。', None]]
[['一人', 'ひとり', None, None], [None, None, 'で', None], ['行', 'い', None, True], [None, None, 'かないほうがいい', True], [None, None, '。', None]]
[['毎日', 'まいにち', None, None], ['肉', 'にく', None, None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べないほうがいい', True], [None, None, '。', None]]

 12%|█▏        | 114/938 [01:10<07:45,  1.77it/s]

[['日本語', 'にほんご', None, None], [None, None, 'を', None], ['勉強', 'べんきょう', None, None], [None, None, 'しなくちゃいけない', True], [None, None, '。', None]]
[['暑', 'あつ', None, None], [None, None, 'い', None], [None, None, 'ので', None], ['水', 'みず', None, None], [None, None, 'を', None], ['飲', 'の', None, True], [None, None, 'まなきゃいけない', True], [None, None, '。', None]]
[[None, None, 'もっと', None], ['文法', 'ぶんぽう', None, None], [None, None, 'を', None], ['勉強', 'べんきょう', None, None], [None, None, 'しなくちゃいけない', True], [None, None, '。', None]]
[['買', 'か', None, True], [None, None, 'いに', True], ['行', 'い', None, True], [None, None, 'かなきゃいけない', True], [None, None, '。', None]]
[['明日', 'あした', None, None], [None, None, 'テストだ', None], [None, None, 'から', None], [None, None, '、もっと', None], ['勉強', 'べんきょう', None, None], [None, None, 'しなくちゃいけない', True], [None, None, '。', None]]

 12%|█▏        | 115/938 [01:11<07:43,  1.78it/s]

[[None, None, 'コンビニ', None], [None, None, 'で', None], [None, None, 'お', None], ['水', 'みず', None, None], [None, None, 'や', True], [None, None, 'おかし', None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'った', None], [None, None, '。', None]]
[[None, None, 'ひらがな', None], [None, None, 'や', True], [None, None, 'カタカナ', None], [None, None, 'や', True], ['漢字', 'かんじ', None, None], [None, None, 'があります', None], [None, None, '。', None]]
[['京都', 'きょうと', None, None], [None, None, 'や', True], ['東京', 'とうきょう', None, None], [None, None, 'や', True], ['大阪', 'おおさか', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'き', None], [None, None, 'ました', None], [None, None, '。', None]]
[[None, None, 'サッカー', None], [None, None, 'や', True], [None, None, 'テニス', None], [None, None, 'を', None], [None, None, 'する', None], [None, None, 'のが', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, '。', None]]
[['果物', 'くだもの', None, None], [None, None, 'や', True], ['野菜', 'やさい', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'てください', None], [None, None, '。', None]]

 12%|█▏        | 116/938 [01:11<07:35,  1.81it/s]

[[None, None, 'ここ', None], [None, None, 'で', None], [None, None, 'サッカー', None], [None, None, 'を', None], [None, None, 'したことがあります', True], [None, None, 'か', None], [None, None, '。', None]]
[['日本', 'にほん', None, None], [None, None, 'に', None], ['行', 'い', None, True], [None, None, 'ったことがあります', True], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'この', None], ['本', 'ほん', None, None], [None, None, 'を', None], ['読', 'よ', None, True], [None, None, 'んだことがある', True], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['家', 'いえ', None, None], [None, None, 'を', None], ['見', 'み', None, True], [None, None, 'たことがあります', True], [None, None, 'か', None], [None, None, '。', None]]
[['６', 'ろく', None, None], ['時', 'じ', None, None], ['前', 'まえ', None, None], [None, None, 'に', None], ['起', 'お', None, True], [None, None, 'きたことがない', True], [None, None, '。', None]]

 12%|█▏        | 117/938 [01:12<07:30,  1.82it/s]

[['俺', 'おれ', None, None], [None, None, 'は', None], ['毎週', 'まいしゅう', None, None], ['金曜日', 'きんようび', None, None], [None, None, 'の', None], ['夜', 'よる', None, None], [None, None, 'に', None], [None, None, 'スーパーに', None], ['行', 'い', None, True], [None, None, 'っている', True], [None, None, 'のだ', None], [None, None, '。', None]]
[[None, None, 'ふうたろうさん', None], [None, None, 'は', None], ['毎日', 'まいにち', None, None], [None, None, 'みくさん', None], [None, None, 'と', None], ['一緒', 'いっしょ', None, None], [None, None, 'に', None], ['歴史', 'れきし', None, None], [None, None, 'を', None], ['勉強', 'べんきょう', None, True], [None, None, 'している', True], [None, None, '。', None]]
[['魔王', 'まおう', None, None], [None, None, 'さま', None], [None, None, 'は', None], [None, None, 'バーガークイーン', None], [None, None, 'で', None], ['働', 'はたら', None, True], [None, None, 'いています', True], [None, None, '。', None]]
[[None, None, 'この', None], ['公園', 'こうえん', None, None], [None, None, 'で', None], [None, None, 'は', None], ['毎週末', 'まいしゅうまつ', None, None], ['多', 'おお', None, None], [None, None, 'くの', None], ['人', 'ひと', None, None], [None, None, 'が', None], ['走', 'はし', None, True], [None, None, 'っています', True], [None, None, '。', None]]
[[None, None, 'どうしてスティーブン', None], [None, None, 'は', None], [None, None, 'いつも', None], ['黒', 'くろ', None, None], [None, None, 'い', None], [None, None, 'タートルネック', None], [None, None, 'を', None], ['着', 'き', None, True], [None, None, 'ている', True], [None, None, 'のです', None], [None, None, 'か', None], [None, None, '。', None]]

 13%|█▎        | 118/938 [01:12<07:21,  1.86it/s]

[['新', 'あたら', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, ' → ', None], ['新', 'あたら', None, True], [None, None, 'しくて', True]]
[['大', 'おお', None, None], [None, None, 'き', None], [None, None, 'い', None], [None, None, ' → ', None], ['大', 'おお', None, True], [None, None, 'きくて', True]]
[['嫌', 'きら', None, None], [None, None, 'い', None], [None, None, ' → ', None], ['嫌', 'きら', None, True], [None, None, 'いで', True]]
[['静', 'しず', None, None], [None, None, 'か → ', None], ['静', 'しず', None, True], [None, None, 'かで', True]]
[['病気', 'びょうき', None, None], [None, None, ' → ', None], ['病気', 'びょうき', None, True], [None, None, 'で', True]]

 13%|█▎        | 119/938 [01:13<07:28,  1.83it/s]

[[None, None, 'りさ', None], [None, None, 'は', None], ['背', 'せ', None, None], [None, None, 'が', None], ['高', 'たか', None, True], [None, None, 'くて', True], [None, None, 'かわい', None], [None, None, 'い', None], [None, None, 'です', None], [None, None, '。', None]]
[['静', 'しず', None, True], [None, None, 'かで', True], ['平和', 'へいわ', None, None], [None, None, 'な', None], [None, None, 'ところ', None], [None, None, 'に', None], ['住', 'す', None, None], [None, None, 'み', None], [None, None, 'たい', None], [None, None, '。', None]]
[[None, None, 'ほろさん', None], [None, None, 'は', None], ['親切', 'しんせつ', None, True], [None, None, 'で', True], ['優', 'やさ', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, '。', None]]
[[None, None, '「ルフィさん', None], [None, None, 'は', None], ['明', 'あか', None, True], [None, None, 'るくて', True], [None, None, 'いい', None], ['人', 'ひと', None, None], [None, None, 'です', None], [None, None, 'よ', None], [None, None, 'ね', None], [None, None, '。」', None], [None, None, '「そう', None], [None, None, 'です', None], [None, None, 'よ', None], [None, None, '。」', None]]
[['新田', 'にった', None, None], [None, None, 'さん', None], [None, None, 'は', None], ['悲', 'かな', None, True], [None, None, 'しくて', True], ['寂', 'さび', None, None], [None, None, 'し', None], [None, None, 'かった', None], [None, None, 'んです', None], [None, None, '。', None]]

 13%|█▎        | 120/938 [01:13<07:27,  1.83it/s]

[['私', 'わたし', None, None], [None, None, 'は', None], [None, None, 'チェス', None], [None, None, 'を', None], [None, None, 'する', None], [None, None, 'のがへた', True], [None, None, 'だ', None], [None, None, '。', None]]
[[None, None, 'カタカナ', None], [None, None, 'を', None], ['覚', 'おぼ', None, None], [None, None, 'え', None], [None, None, 'る', None], [None, None, 'のがへた', True], [None, None, '。', None]]
[[None, None, 'サッカー', None], [None, None, 'を', None], [None, None, 'する', None], [None, None, 'のがへた', True], [None, None, 'です', None], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['勉強', 'べんきょう', None, None], [None, None, 'する', None], [None, None, 'のがへた', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['漢字', 'かんじ', None, None], [None, None, 'を', None], ['書', 'か', None, None], [None, None, 'く', None], [None, None, 'のがへた', True], [None, None, '。', None]]

 13%|█▎        | 121/938 [01:14<07:47,  1.75it/s]

[[None, None, 'トム', None], [None, None, 'は', None], [None, None, 'サッカー', None], [None, None, 'を', None], [None, None, 'する', None], [None, None, 'のが', True], ['上手', 'じょうず', None, True], [None, None, 'です', None], [None, None, '。', None]]
[['漢字', 'かんじ', None, None], [None, None, 'を', None], ['覚', 'おぼ', None, None], [None, None, 'える', None], [None, None, 'のが', True], ['上手', 'じょうず', None, True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['漢字', 'かんじ', None, None], [None, None, 'を', None], ['書', 'か', None, None], [None, None, 'く', None], [None, None, 'のが', True], ['上手', 'じょうず', None, True], [None, None, 'でしょう', None], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], [None, None, '、', None], ['料理', 'りょうり', None, None], [None, None, 'を', None], [None, None, 'する', None], [None, None, 'のが', True], ['上手', 'じょうず', None, True], [None, None, 'です', None], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['歌', 'うた', None, None], [None, None, 'う', None], [None, None, 'のが', True], ['上手', 'じょうず', None, True], [None, None, '。', None]]

 13%|█▎        | 122/938 [01:15<08:19,  1.63it/s]

[['新', 'あたら', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'のは', True], ['彼', 'かれ', None, None], [None, None, 'の', None], ['車', 'くるま', None, None], [None, None, 'だ', None], [None, None, '。', None]]
[['元気', 'げんき', None, None], [None, None, 'なのは', True], ['社長', 'しゃちょう', None, None], [None, None, 'です', None], [None, None, '。', None]]
[['難', 'むずか', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'のは', True], ['歴史', 'れきし', None, None], [None, None, 'だ', None], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'が', None], ['素敵', 'すてき', None, None], [None, None, 'なのは', True], ['服', 'ふく', None, None], [None, None, 'だけ', None], [None, None, 'だ', None], [None, None, '。', None]]
[['暑', 'あつ', None, None], [None, None, 'い', None], [None, None, 'のも', True], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'だ', None], [None, None, 'から', None], [None, None, '、エアコン', None], [None, None, 'が', None], [None, None, 'なく', None], [None, None, 'てもいい', None], [None, None, '。', None]]

 13%|█▎        | 123/938 [01:15<08:02,  1.69it/s]

[[None, None, 'その', None], ['傘', 'かさ', None, None], [None, None, 'を', None], [None, None, 'あげます', True], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], ['弟', 'おとうと', None, None], [None, None, 'に', None], ['飲', 'の', None, None], [None, None, 'み', None], ['物', 'もの', None, None], [None, None, 'を', None], [None, None, 'あげた', True], [None, None, '。', None]]
[['宝箱', 'たからばこ', None, None], [None, None, 'の', None], ['鍵', 'かぎ', None, None], [None, None, 'を', None], [None, None, 'あげます', True], [None, None, '。', None]]
[['紙', 'かみ', None, None], [None, None, 'を', None], [None, None, 'あげる', True], [None, None, 'ので', None], [None, None, 'メモ', None], [None, None, 'して', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'に', None], [None, None, 'スマホ', None], [None, None, 'を', None], [None, None, 'あげましょう', True], [None, None, '。', None]]

 13%|█▎        | 124/938 [01:16<07:50,  1.73it/s]

[['母', 'はは', None, None], [None, None, 'は', None], ['僕', 'ぼく', None, None], [None, None, 'に', None], [None, None, 'かっこいいペン', None], [None, None, 'を', None], [None, None, 'くれた', True], [None, None, '。', None]]
[['兄', 'あに', None, None], [None, None, 'は', None], [None, None, '(', None], ['私', 'わたし', None, None], [None, None, 'に', None], [None, None, ')', None], ['便利', 'べんり', None, None], [None, None, 'な', None], ['箱', 'はこ', None, None], [None, None, 'を', None], [None, None, 'くれた', True], [None, None, '。', None]]
[[None, None, 'おじいちゃん', None], [None, None, 'は', None], [None, None, '(', None], ['私', 'わたし', None, None], [None, None, 'に', None], [None, None, ')', None], ['古', 'ふる', None, None], [None, None, 'い', None], ['自転車', 'じてんしゃ', None, None], [None, None, 'を', None], [None, None, 'くれた', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'が', None], [None, None, '(', None], ['私', 'わたし', None, None], [None, None, 'に', None], [None, None, ')かわい', None], [None, None, 'い', None], ['靴', 'くつ', None, None], [None, None, 'を', None], [None, None, 'くれて', True], [None, None, '、', None], ['嬉', 'うれ', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'です', None], [None, None, '。', None]]
[['友達', 'ともだち', None, None], [None, None, 'は', None], ['毎週', 'まいしゅう', None, None], ['土曜日', 'どようび', None, None], [None, None, 'に', None], ['私', 'わたし', None, None], [None, None, 'の', None], ['母', 'はは', None, None], [None, None, 'に', None], [None, None, 'クッキー', None], [None, None, 'を', None], [None, None, 'くれる', True], [None, None, '。', None]]

 13%|█▎        | 125/938 [01:16<07:32,  1.80it/s]

[['私', 'わたし', None, None], [None, None, 'は', None], [None, None, 'お', None], ['祖母', 'ばあ', None, None], [None, None, 'さん', None], [None, None, 'から', None], [None, None, 'おはし', None], [None, None, 'と', None], [None, None, 'コップ', None], [None, None, 'を', None], [None, None, 'もらった', True], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'に', None], [None, None, '(', None], ['私', 'わたし', None, None], [None, None, 'は', None], [None, None, ')', None], ['青', 'あお', None, None], [None, None, 'い', None], ['花', 'はな', None, None], [None, None, 'を', None], [None, None, 'もらいます', True], [None, None, '。', None]]
[[None, None, '(', None], ['私', 'わたし', None, None], [None, None, 'は', None], [None, None, ')', None], ['友達', 'ともだち', None, None], [None, None, 'に', None], ['暖', 'あたた', None, None], [None, None, 'か', None], [None, None, 'い', None], [None, None, 'セーター', None], [None, None, 'を', None], [None, None, 'もらった', True], [None, None, '。', None]]
[['父', 'ちち', None, None], [None, None, 'から', None], [None, None, '(', None], ['私', 'わたし', None, None], [None, None, 'は', None], [None, None, ')お', None], ['金', 'かね', None, None], [None, None, 'を', None], [None, None, 'もらった', True], [None, None, '。', None]]
[[None, None, '(', None], ['私', 'わたし', None, None], [None, None, 'は', None], [None, None, ')', None], ['明後日', 'あさって', None, None], ['給料', 'きゅうりょう', None, None], [None, None, 'を', None], [None, None, 'もらいます', True], [None, None, '。', None]]

 13%|█▎        | 126/938 [01:17<07:29,  1.81it/s]

[['私', 'わたし', None, None], [None, None, 'は', None], [None, None, 'この', None], ['本', 'ほん', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'で', None], [None, None, 'は', None], [None, None, 'ない', None], [None, None, 'けれども', True], [None, None, '、あなた', None], [None, None, 'は', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'でしょう', None], [None, None, '。', None]]
[[None, None, 'トム', None], [None, None, 'に', None], ['言', 'い', None, None], [None, None, 'った', None], [None, None, 'けれども', True], [None, None, '、トム', None], [None, None, 'は', None], ['忘', 'わす', None, None], [None, None, 'れ', None], [None, None, 'ました', None], [None, None, '。', None]]
[['掃除', 'そうじ', None, None], [None, None, 'を', None], [None, None, 'した', None], [None, None, 'けれども', True], [None, None, '、', None], [None, None, 'まだ', None], ['汚', 'きたな', None, None], [None, None, 'い', None], [None, None, '。', None]]
[['映画', 'えいが', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'る', None], [None, None, 'のは', None], ['楽', 'たの', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'けれども', True], [None, None, '、チケット', None], [None, None, 'が', None], ['高', 'たか', None, None], [None, None, 'い', None], [None, None, '。', None]]
[['電車', 'でんしゃ', None, None], [None, None, 'は', None], ['便利', 'べんり', None, None], [None, None, 'だけれども', True], [None, None, '、いつも', None], ['人', 'ひと', None, None], [None, None, 'が', None], ['多', 'おお', None, None], [None, None, 'い', None], [None, None, '。', None]]

 14%|█▎        | 127/938 [01:17<07:40,  1.76it/s]

[['日本', 'にほん', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'つもり', True], [None, None, 'だ。', None]]
[['日本語', 'にほんご', None, None], [None, None, 'を', None], ['勉強', 'べんきょう', None, None], [None, None, 'する', None], [None, None, 'つもりだ', True], [None, None, '。', None]]
[['明日', 'あした', None, None], ['早', 'はや', None, None], [None, None, 'く', None], ['起', 'お', None, None], [None, None, 'き', None], [None, None, 'る', None], [None, None, 'つもりです', True], [None, None, '。', None]]
[['車', 'くるま', None, None], [None, None, 'で', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'つもりです', True], [None, None, '。', None]]
[[None, None, 'スポーツが', None], ['上手', 'じょうず', None, None], [None, None, 'になる', None], [None, None, 'つもりだった', True], [None, None, '。', None]]

 14%|█▎        | 128/938 [01:18<07:35,  1.78it/s]

[[None, None, 'どこ', None], [None, None, 'でも', True], [None, None, 'いい', None], [None, None, 'よ', None], [None, None, '。', None]]
[[None, None, 'いつ', None], [None, None, 'でも', True], ['家', 'いえ', None, None], [None, None, 'に', None], ['来', 'き', None, None], [None, None, 'てください', None], [None, None, '。', None]]
[[None, None, 'いつ', None], [None, None, 'でも', True], ['電話', 'でんわ', None, None], [None, None, 'に', None], ['出', 'で', None, None], [None, None, 'る', None], [None, None, 'から', None], [None, None, '。', None]]
[[None, None, 'いつ', None], [None, None, 'でも', True], ['洗濯', 'せんたく', None, None], [None, None, 'でき', None], [None, None, 'ます', None], [None, None, 'よ', None], [None, None, '。', None]]
[[None, None, 'お', None], ['茶', 'ちゃ', None, None], [None, None, 'でも', True], [None, None, 'どう？', None]]

 14%|█▍        | 129/938 [01:18<07:35,  1.78it/s]

[[None, None, 'ケーキ', None], [None, None, 'は', None], ['作', 'つく', None, True], [None, None, 'りやすい', True], [None, None, '。', None]]
[[None, None, 'この', None], ['魚', 'さかな', None, None], [None, None, 'は', None], ['食', 'た', None, True], [None, None, 'べやすい', True], [None, None, 'です', None], [None, None, '。', None]]
[['昨日', 'きのう', None, None], [None, None, 'の', None], ['練習', 'れんしゅう', None, None], [None, None, 'は', None], [None, None, 'しやすかった', True], [None, None, '。', None]]
[[None, None, 'この', None], ['白', 'しろ', None, None], [None, None, 'い', None], ['服', 'ふく', None, None], [None, None, 'は', None], [None, None, '、', None], ['汚', 'よご', None, True], [None, None, 'れやすい', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'この', None], ['音楽', 'おんがく', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'だ', None], [None, None, 'から', None], [None, None, '、', None], ['踊', 'おど', None, True], [None, None, 'りやすい', True], [None, None, '。', None]]

 14%|█▍        | 130/938 [01:19<07:49,  1.72it/s]

[['甘', 'あま', None, None], [None, None, 'くない', None], [None, None, 'ケーキ', None], [None, None, 'は', None], [None, None, '、', None], ['食', 'た', None, True], [None, None, 'べにくい', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'アフリカ', None], [None, None, 'に', None], [None, None, 'は', None], ['行', 'い', None, True], [None, None, 'きにくい', True], [None, None, 'です', None], [None, None, '。', None]]
[['怖', 'こわ', None, None], [None, None, 'い', None], [None, None, 'こと', None], [None, None, 'は', None], [None, None, 'しにくい', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'と', None], [None, None, 'は', None], ['話', 'はな', None, True], [None, None, 'しにくい', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'この', None], [None, None, 'コップ、', None], ['形', 'かたち', None, None], [None, None, 'が', None], ['変', 'へん', None, None], [None, None, 'だ', None], [None, None, 'から', None], ['飲', 'の', None, True], [None, None, 'みにくい', True], [None, None, '。', None]]

 14%|█▍        | 131/938 [01:20<07:44,  1.74it/s]

[['先輩', 'せんぱい', None, None], [None, None, 'が', None], ['後輩', 'こうはい', None, None], [None, None, 'に', None], ['話', 'はな', None, None], [None, None, 'し', None], [None, None, 'ている', None], [None, None, '：「', None], ['大丈夫', 'だいじょうぶ', None, None], [None, None, '、', None], [None, None, 'だんだん', True], ['上手', 'じょうず', None, None], [None, None, 'になる', None], [None, None, 'よ', None], [None, None, '。」', None]]
[['友達', 'ともだち', None, None], [None, None, 'が', None], ['話', 'はな', None, None], [None, None, 'し', None], [None, None, 'ている', None], [None, None, '：「', None], ['秋', 'あき', None, None], [None, None, 'にな', None], [None, None, 'った', None], [None, None, 'から', None], [None, None, 'これ', None], [None, None, 'から', None], [None, None, 'だんだん', True], ['寒', 'さむ', None, None], [None, None, 'くな', None], [None, None, 'る', None], [None, None, 'よ', None], [None, None, 'ね', None], [None, None, '。」', None]]
[['英語', 'えいご', None, None], [None, None, 'の', None], ['教師', 'きょうし', None, None], [None, None, 'が', None], ['生徒', 'せいと', None, None], [None, None, 'の', None], ['親', 'おや', None, None], [None, None, 'と', None], ['話', 'はな', None, None], [None, None, 'し', None], [None, None, 'ている', None], [None, None, '、', None], ['教師', 'きょうし', None, None], [None, None, '：「', None], ['娘', 'むすめ', None, None], [None, None, 'さん', None], [None, None, 'は', None], [None, None, 'だんだん', True], ['英語', 'えいご', None, None], [None, None, 'が', None], [None, None, 'うまくなってきました。」', None]]
[['友達', 'ともだち', None, None], [None, None, 'が', None], ['話', 'はな', None, None], [None, None, 'し', None], [None, None, 'ている', None], [None, None, '：「', None], [None, None, 'だんだんと', True], [None, None, 'あの', None], [None, None, 'やつ', None], [None, None, 'の', None], ['事', 'こと', None, None], [None, None, 'が', None], ['嫌', 'きら', None, None], [None, None, 'い', None], [None, None, 'になっ', None], [None, None, 'てきて', None], [None, None, 'いて、', None], ['今', 'いま', None, None], [None, None, 'は', None], ['避', 'さ', None, None], [None, None, 'ける', None], [None, None, 'ようにし', None], [None, None, 'ている', None], [None, None, '。」', None]]
[[None, None, 'お', None], ['母', 'かあ', None, None], [None, None, 'さん', None], [None, None, 'が', None], ['子供', 'こども', None, None], [None, None, 'と', None], ['話', 'はな', None, None], [None, None, 'し', None], [None, None, 'ている', None], [None, None, '：「あなた', None], [None, None, 'は', None], [None, None, 'だんだん', True], [None, None, 'おかし', None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'たくな', None], [None, None, 'くな', None], [None, None, 'る。」', None]]

 14%|█▍        | 132/938 [01:20<07:39,  1.75it/s]

[[None, None, 'どんどん', True], ['暑', 'あつ', None, None], [None, None, 'くな', None], [None, None, 'る。', None]]
[[None, None, 'どんどん', True], ['日本語', 'にほんご', None, None], [None, None, 'が', None], ['上手', 'じょうず', None, None], [None, None, 'になり', None], [None, None, 'たい', None], [None, None, '。', None]]
[['日本', 'にほん', None, None], [None, None, 'の', None], ['人口', 'じんこう', None, None], [None, None, 'が', None], [None, None, 'どんどん', True], ['減', 'へ', None, None], [None, None, 'る', None], [None, None, '。', None]]
[['音', 'おと', None, None], [None, None, 'が', None], [None, None, 'どんどん', True], ['大', 'おお', None, None], [None, None, 'き', None], [None, None, 'くな', None], [None, None, 'る。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'が', None], [None, None, 'どんどん', True], ['綺麗', 'きれい', None, None], [None, None, 'になる', None], [None, None, '。', None]]

 14%|█▍        | 133/938 [01:21<07:36,  1.76it/s]

[['彼', 'かれ', None, None], [None, None, 'ら', True], [None, None, 'は', None], ['十分', 'じゅうぶん', None, None], [None, None, 'に', None], ['勉強', 'べんきょう', None, None], [None, None, 'を', None], [None, None, 'した', None], [None, None, 'から', None], [None, None, '、', None], ['試験', 'しけん', None, None], [None, None, 'が', None], ['簡単', 'かんたん', None, None], [None, None, 'だった', None], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'ら', True], [None, None, 'を', None], ['捨', 'す', None, None], [None, None, 'ててください', None], [None, None, '。', None]]
[[None, None, 'それ', None], [None, None, 'ら', True], [None, None, 'の', None], ['畳', 'たたみ', None, None], [None, None, 'は', None], [None, None, 'いい', None], ['匂', 'にお', None, None], [None, None, 'いがし', None], [None, None, 'ている', None], [None, None, '。', None]]
[['君', 'きみ', None, None], [None, None, 'ら', True], ['池', 'いけ', None, None], [None, None, 'に', None], ['入', 'はい', None, None], [None, None, 'る', None], [None, None, 'つもり', None], [None, None, '？', None]]
[['奴', 'やつ', None, None], [None, None, 'ら', True], [None, None, 'はプロ', None], [None, None, 'だ', None], [None, None, '。', None]]

 14%|█▍        | 134/938 [01:21<07:35,  1.77it/s]

[['大', 'おお', None, None], [None, None, 'き', None], [None, None, 'い', None], ['音', 'おと', None, None], [None, None, 'で', None], [None, None, '、', None], ['鳥', 'とり', None, None], [None, None, 'が', None], ['飛', 'と', None, True], [None, None, 'んでいく', True], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'を', None], ['先生', 'せんせい', None, None], [None, None, 'に', None], ['持', 'も', None, True], [None, None, 'っていってください', True], [None, None, '。', None]]
[['友達', 'ともだち', None, None], [None, None, 'にプレゼント', None], [None, None, 'を', None], ['買', 'か', None, True], [None, None, 'っていく', True], [None, None, '。', None]]
[['大丈夫', 'だいじょうぶ', None, None], [None, None, '！お', None], ['弁当', 'べんとう', None, None], [None, None, 'を', None], ['持', 'も', None, True], [None, None, 'っていく', True], [None, None, 'から', None], [None, None, '。', None]]
[['今日', 'きょう', None, None], [None, None, 'は', None], [None, None, 'テスト', None], [None, None, 'を', None], ['受', 'う', None, None], [None, None, 'ける', None], [None, None, 'から', None], ['鉛筆', 'えんぴつ', None, None], [None, None, 'を', None], ['持', 'も', None, True], [None, None, 'っていく', True], [None, None, '。', None]]

 14%|█▍        | 135/938 [01:22<07:33,  1.77it/s]

[[None, None, 'すぐ', None], ['帰', 'かえ', None, True], [None, None, 'ってくる', True], [None, None, 'ね', None], [None, None, '？', None]]
[[None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'が', None], [None, None, 'なくなってきた', True], [None, None, '。', None]]
[[None, None, 'トイレに', None], ['行', 'い', None, True], [None, None, 'ってきます', True], [None, None, '。', None]]
[[None, None, 'お', None], ['母', 'かあ', None, None], [None, None, 'さんに', None], ['似', 'に', None, True], [None, None, 'てきた', True], [None, None, 'ね', None], [None, None, '。', None]]
[[None, None, 'お', None], ['弁当', 'べんとう', None, None], [None, None, 'を', None], ['持', 'も', None, True], [None, None, 'ってきて', True], [None, None, 'ください', None], [None, None, '。', None]]

 14%|█▍        | 136/938 [01:22<07:31,  1.78it/s]

[['彼', 'かれ', None, None], [None, None, 'の', None], ['泳', 'およ', None, True], [None, None, 'ぎかた', True], [None, None, 'は', None], ['変', 'へん', None, None], [None, None, 'だ', None], [None, None, '。', None]]
[[None, None, 'お', None], ['菓子', 'かし', None, None], [None, None, 'の', True], ['作', 'つく', None, True], [None, None, 'りかた', True], [None, None, 'を', None], ['学', 'まな', None, None], [None, None, 'ぶ', None], [None, None, '。', None]]
[['文法', 'ぶんぽう', None, None], [None, None, 'の', None], ['勉強', 'べんきょう', None, True], [None, None, 'のしかた', True], [None, None, 'を', None], ['教', 'おし', None, None], [None, None, 'え', None], [None, None, 'てください', None], [None, None, '。', None]]
[['妻', 'つま', None, None], [None, None, 'は', None], [None, None, 'リモコン', None], [None, None, 'の', True], ['使', 'つか', None, True], [None, None, 'いかた', True], [None, None, 'が', None], ['分', 'わ', None, None], [None, None, 'からない。', None]]
[['彼', 'かれ', None, None], [None, None, 'の', None], [None, None, 'スパゲッティ', None], [None, None, 'の', True], ['食', 'た', None, True], [None, None, 'べかた', True], [None, None, 'は', None], ['良', 'よ', None, None], [None, None, 'くない。', None]]

 15%|█▍        | 137/938 [01:23<07:27,  1.79it/s]

[[None, None, 'パーティー', None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'だけで', True], ['楽', 'たの', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, '。', None]]
[['顔', 'かお', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'た', None], [None, None, 'だけで', True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'は', None], [None, None, 'いい', None], ['人', 'ひと', None, None], [None, None, 'だ', None], [None, None, 'と', None], ['分', 'わ', None, None], [None, None, 'か', None], [None, None, 'った', None], [None, None, '。', None]]
[['一緒', 'いっしょ', None, None], [None, None, 'に', None], ['時間', 'じかん', None, None], [None, None, 'を', None], ['過', 'す', None, None], [None, None, 'ごす', None], [None, None, 'だけで', True], [None, None, '、', None], ['仲良', 'なかよ', None, None], [None, None, 'くな', None], [None, None, 'りました。', None]]
[['彼', 'かれ', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'た', None], [None, None, 'だけで', True], ['性格', 'せいかく', None, None], [None, None, 'が', None], ['悪', 'わる', None, None], [None, None, 'い', None], [None, None, 'と', None], ['分', 'わ', None, None], [None, None, 'か', None], [None, None, 'った', None], [None, None, '。', None]]
[['家族', 'かぞく', None, None], [None, None, 'と', None], ['一緒', 'いっしょ', None, None], [None, None, 'に', None], ['居', 'い', None, None], [None, None, 'る', None], [None, None, 'だけで', True], [None, None, '、', None], ['幸', 'しあわ', None, None], [None, None, 'せ。', None]]

 15%|█▍        | 138/938 [01:24<07:34,  1.76it/s]

[['大統領', 'だいとうりょう', None, None], [None, None, 'が', None], ['言', 'い', None, None], [None, None, 'いました。', None], [None, None, 'ですが', True], [None, None, '、', None], ['私', 'わたし', None, None], [None, None, 'は', None], ['信', 'しん', None, None], [None, None, 'じ', None], [None, None, 'ません', None], [None, None, '。', None]]
[['毎日', 'まいにち', None, None], ['運動', 'うんどう', None, None], [None, None, 'を', None], [None, None, 'しました。', None], [None, None, 'ですが', True], [None, None, '、', None], ['痩', 'や', None, None], [None, None, 'せ', None], [None, None, 'ていません', None], [None, None, '。', None]]
[['本当', 'ほんとう', None, None], [None, None, 'は', None], ['私', 'わたし', None, None], [None, None, 'が', None], [None, None, 'し', None], [None, None, 'なくてはならない', None], [None, None, '。', None], [None, None, 'だが', True], [None, None, 'ね、', None], ['君', 'きみ', None, None], [None, None, 'にし', None], [None, None, 'てほし', None], [None, None, 'い。', None]]
[[None, None, 'これ', None], [None, None, 'が', None], ['基本', 'きほん', None, None], [None, None, 'ルール', None], [None, None, 'だ', None], [None, None, '。', None], [None, None, 'だが', True], [None, None, '、', None], ['例外', 'れいがい', None, None], [None, None, 'も', None], [None, None, 'ある。', None]]
[['明日', 'あした', None, None], [None, None, 'から', None], [None, None, '、', None], ['旅行', 'りょこう', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'き', None], [None, None, 'ます', None], [None, None, '。', None], [None, None, 'ですが', True], [None, None, '、', None], [None, None, 'まだ', None], [None, None, 'チケット', None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'っ', None], [None, None, 'ていません', None], [None, None, '。', None]]

 15%|█▍        | 139/938 [01:24<07:26,  1.79it/s]

[[None, None, 'なる → ', None], [None, None, 'ならなくて', True]]
[['嫌', 'きら', None, None], [None, None, 'い', None], [None, None, ' → ', None], ['嫌', 'きら', None, True], [None, None, 'いではなくて', True]]
[['病気', 'びょうき', None, None], [None, None, ' → ', None], ['病気', 'びょうき', None, True], [None, None, 'じゃなくて', True]]
[['高', 'たか', None, None], [None, None, 'い', None], [None, None, ' → ', None], ['高', 'たか', None, True], [None, None, 'くなくて', True]]
[[None, None, 'いい', None], [None, None, ' → ', None], [None, None, 'よくなくて', True]]

 15%|█▍        | 140/938 [01:25<07:21,  1.81it/s]

[['重病', 'じゅうびょう', None, None], [None, None, 'じゃなくて', True], [None, None, 'ホッとした。', None]]
[[None, None, '「お', None], ['茶', 'ちゃ', None, None], [None, None, 'しか', None], ['出', 'だ', None, True], [None, None, 'さなくて', True], [None, None, 'すみません', None], [None, None, '。」', None]]
[[None, None, '「', None], ['試験', 'しけん', None, None], [None, None, 'に', None], ['合格', 'ごうかく', None, None], [None, None, 'した', None], [None, None, 'か', None], ['分', 'わ', None, True], [None, None, 'からなくて', True], ['不安', 'ふあん', None, None], [None, None, 'だ', None], [None, None, 'ね', None], [None, None, '。」', None]]
[[None, None, '「', None], ['孫', 'まご', None, None], [None, None, 'が', None], [None, None, 'まだ', None], [None, None, 'きていなくて', True], ['心配', 'しんぱい', None, None], [None, None, 'です', None], [None, None, '。」', None]]
[['彼氏', 'かれし', None, None], [None, None, 'が', None], ['子猫', 'こねこ', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'じゃなくて', True], [None, None, '、がっかりした。', None]]

 15%|█▌        | 141/938 [01:25<07:16,  1.82it/s]

[['休', 'やす', None, True], [None, None, 'まないで', True], ['仕事', 'しごと', None, None], [None, None, 'を', None], [None, None, 'する', None], [None, None, '。', None]]
[[None, None, '「', None], ['後悔', 'こうかい', None, None], [None, None, 'しないで', True], ['生', 'い', None, None], [None, None, 'き', None], [None, None, 'たい', None], [None, None, '。」', None]]
[[None, None, '「', None], [None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'は', None], ['便所', 'べんじょ', None, None], [None, None, 'から', None], ['手', 'て', None, None], [None, None, 'を', None], ['洗', 'あら', None, True], [None, None, 'わないで', True], ['出', 'で', None, None], [None, None, 'てきた', None], [None, None, 'んだ', None], [None, None, 'よ', None], [None, None, '。」', None]]
[['夕食', 'ゆうしょく', None, None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べないで', True], [None, None, '、', None], ['寝', 'ね', None, None], [None, None, 'る', None], [None, None, '。', None]]
[[None, None, '「', None], ['昨日', 'きのう', None, None], [None, None, '、うちの', None], ['娘', 'むすめ', None, None], [None, None, 'は', None], ['頭', 'あたま', None, None], [None, None, 'を', None], [None, None, 'ぶつけ', None], [None, None, 'た', None], [None, None, 'けど', None], [None, None, '、', None], ['泣', 'な', None, True], [None, None, 'かないで', True], [None, None, '『', None], ['大丈夫', 'だいじょうぶ', None, None], [None, None, 'だ', None], [None, None, 'よ', None], [None, None, '』', None], [None, None, 'と', None], [None, None, 'だけ', None], ['言', 'い', None, None], [None, None, 'った', None], [None, None, 'んだ', None], [None, None, '。', None], ['本当', 'ほんとう', None, None], [None, None, 'に', None], ['驚', 'おどろ', None, None], [None, None, 'いた', None], [None, None, '。」', None]]

 15%|█▌        | 142/938 [01:26<07:20,  1.81it/s]

[['私', 'わたし', None, None], [None, None, 'の', None], [None, None, 'アイスクリーム', None], [None, None, 'を', None], ['兄', 'あに', None, None], [None, None, 'に', None], ['食', 'た', None, True], [None, None, 'べられた', True], [None, None, '。', None]]
[['変', 'へん', None, None], [None, None, 'な', None], ['話', 'はなし', None, None], [None, None, 'を', None], ['親', 'おや', None, None], [None, None, 'に', None], ['聞', 'き', None, True], [None, None, 'かれた', True], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], ['部屋', 'へや', None, None], [None, None, 'を', None], [None, None, 'きれいにして、', None], ['褒', 'ほ', None, True], [None, None, 'められた', True], [None, None, '。', None]]
[['宿題', 'しゅくだい', None, None], [None, None, 'を', None], [None, None, 'した', None], [None, None, 'けど', None], [None, None, '、', None], ['持', 'も', None, None], [None, None, 'って', None], ['来', 'く', None, None], [None, None, 'る', None], [None, None, 'の', None], [None, None, 'を', None], ['忘', 'わす', None, None], [None, None, 'れた。', None], ['何', 'なん', None, None], [None, None, 'と', None], ['言', 'い', None, True], [None, None, 'われる', True], [None, None, 'かな', None], [None, None, '。', None]]
[[None, None, '私', None], [None, None, 'は', None], [None, None, 'あいつ', None], [None, None, 'ら', None], [None, None, 'に', None], ['何', 'なに', None, None], [None, None, 'を', None], [None, None, 'されて', True], [None, None, 'もいい', None], [None, None, 'けど、あいつ', None], [None, None, 'ら', None], [None, None, 'に', None], [None, None, 'は', None], ['絶対', 'ぜったい', None, None], [None, None, 'に', None], ['君', 'きみ', None, None], [None, None, 'の', None], ['名前', 'なまえ', None, None], [None, None, 'を', None], ['教', 'おし', None, None], [None, None, 'え', None], [None, None, 'ない', None], [None, None, '。', None]]

 15%|█▌        | 143/938 [01:26<07:18,  1.81it/s]

[['虫', 'むし', None, None], [None, None, 'を', None], ['集', 'あつ', None, None], [None, None, 'め', None], [None, None, 'た', None], [None, None, '・', None], ['虫', 'むし', None, None], [None, None, 'が', None], ['集', 'あつ', None, True], [None, None, 'まった', True]]
[['探', 'さが', None, None], [None, None, 'し', None], [None, None, 'ていた', None], [None, None, 'カバン', None], [None, None, 'を', None], ['見', 'み', None, True], [None, None, 'つけた', True], [None, None, '。', None]]
[['犯人', 'はんにん', None, None], [None, None, 'が', None], ['見', 'み', None, True], [None, None, 'つかった', True], [None, None, '。', None]]
[[None, None, 'ケーキ', None], [None, None, 'の', None], ['上', 'うえ', None, None], [None, None, 'に', None], ['乗', 'の', None, None], [None, None, 'っ', None], [None, None, 'ていた', None], [None, None, 'ロウソク', None], [None, None, 'を', None], ['消', 'け', None, True], [None, None, 'した', True], [None, None, '。', None]]
[['台所', 'だいどころ', None, None], [None, None, 'の', None], [None, None, 'ライト', None], [None, None, 'が', None], ['消', 'き', None, True], [None, None, 'えた', True], [None, None, '。', None]]

 15%|█▌        | 144/938 [01:27<07:51,  1.68it/s]

[[None, None, 'この', None], ['文章', 'ぶんしょう', None, None], [None, None, 'を', None], ['書', 'か', None, True], [None, None, 'き', True], ['直', 'なお', None, True], [None, None, 'した', True], ['方', 'ほう', None, None], [None, None, 'が', None], [None, None, 'いい', None], [None, None, 'よ', None], [None, None, '。', None]]
[[None, None, '「お', None], ['前', 'まえ', None, None], [None, None, '」', None], [None, None, 'って', None], ['言', 'い', None, None], [None, None, 'う', None], [None, None, 'な', None], [None, None, '。', None], ['言', 'い', None, True], [None, None, 'い', True], ['直', 'なお', None, True], [None, None, 'してください', True], [None, None, '。', None]]
[[None, None, 'お', None], ['客', 'きゃく', None, None], [None, None, 'さん', None], [None, None, 'に', None], ['電話', 'でんわ', None, None], [None, None, 'を', None], ['掛', 'か', None, True], [None, None, 'け', True], ['直', 'なお', None, True], [None, None, 'してください', True], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'の', None], [None, None, 'こと', None], [None, None, 'を', None], ['見', 'み', None, True], ['直', 'なお', None, True], [None, None, 'しました', True], [None, None, '。', None]]
[[None, None, 'はい！', None], ['急', 'いそ', None, None], [None, None, 'いで', None], [None, None, 'やり', True], ['直', 'なお', None, True], [None, None, 'します', True], [None, None, '。', None]]

 15%|█▌        | 145/938 [01:28<07:46,  1.70it/s]

[[None, None, 'もう', None], ['別', 'わか', None, None], [None, None, 'れ', None], [None, None, 'たい', None], [None, None, 'という', True], ['事', 'こと', None, True], [None, None, '？', None]]
[[None, None, 'この', None], ['店', 'みせ', None, None], [None, None, 'は', None], ['美味', 'おい', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'という', True], ['事', 'こと', None, True], [None, None, 'を', None], [None, None, 'よく', None], ['聞', 'き', None, None], [None, None, 'き', None], [None, None, 'ます', None], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'が', None], [None, None, 'みんな', None], [None, None, 'の', None], ['分', 'ぶん', None, None], [None, None, 'を', None], ['払', 'はら', None, None], [None, None, 'う', None], [None, None, 'という', True], ['事', 'こと', None, True], [None, None, 'です', None], [None, None, 'か', None], [None, None, '？', None]]
[['私', 'わたし', None, None], [None, None, 'が', None], [None, None, '、', None], ['一人', 'ひとり', None, None], [None, None, 'でお', None], ['皿', 'さら', None, None], [None, None, 'を', None], ['洗', 'あら', None, None], [None, None, 'わ', None], [None, None, 'なくてはいけない', None], [None, None, 'という', True], ['事', 'こと', None, True], [None, None, 'です', None], [None, None, 'か', None], [None, None, '？', None]]
[['真面目', 'まじめ', None, None], [None, None, 'にな', None], [None, None, 'る', None], [None, None, 'という', True], ['事', 'こと', None, True], [None, None, 'です', None], [None, None, 'ね', None], [None, None, '。', None]]

 16%|█▌        | 146/938 [01:28<07:44,  1.71it/s]

[['散歩', 'さんぽ', None, None], [None, None, 'を', None], [None, None, 'する', None], [None, None, 'とき', True], [None, None, 'に', None], ['音楽', 'おんがく', None, None], [None, None, 'を', None], ['聴', 'き', None, None], [None, None, 'く', None], [None, None, '。', None]]
[['授業', 'じゅぎょう', None, None], [None, None, 'のとき', True], [None, None, 'は', None], ['静', 'しず', None, None], [None, None, 'かにし', None], [None, None, 'なくてはいけない', None], [None, None, '。', None]]
[[None, None, 'あの', None], ['映画', 'えいが', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'た', None], [None, None, 'とき', True], [None, None, '、', None], ['泣', 'な', None, None], [None, None, 'いた', None], [None, None, '。', None]]
[['大変', 'たいへん', None, None], [None, None, 'なとき', True], [None, None, 'に', None], ['彼', 'かれ', None, None], [None, None, 'の', None], ['親', 'おや', None, None], [None, None, 'は', None], ['亡', 'な', None, None], [None, None, 'くな', None], [None, None, 'った', None], [None, None, '。', None]]
[['寒', 'さむ', None, None], [None, None, 'い', None], [None, None, 'とき', True], [None, None, 'は', None], [None, None, '、お', None], ['風呂', 'ふろ', None, None], [None, None, 'に', None], ['入', 'はい', None, None], [None, None, 'りた', None], [None, None, 'くな', None], [None, None, 'る。', None]]

 16%|█▌        | 147/938 [01:29<08:02,  1.64it/s]

[[None, None, 'まず', True], ['踊', 'おど', None, None], [None, None, 'りに', None], ['行', 'い', None, None], [None, None, 'きましょう。', None]]
[[None, None, 'まず', True], ['壁', 'かべ', None, None], [None, None, 'を', None], ['塗', 'ぬ', None, None], [None, None, 'っ', None], [None, None, 'てください', None], [None, None, '。', None]]
[[None, None, 'まず', True], [None, None, 'これ', None], [None, None, 'だ', None], [None, None, 'よ', None], [None, None, 'ね', None], [None, None, '。', None]]
[[None, None, 'まず', True], [None, None, 'この', None], ['部分', 'ぶぶん', None, None], [None, None, 'を', None], ['仕上', 'しあ', None, None], [None, None, 'げ', None], [None, None, 'てください', None], [None, None, '。', None]]
[[None, None, 'まず', True], ['買', 'か', None, None], [None, None, 'い', None], ['物', 'もの', None, None], [None, None, 'し', None], [None, None, 'て', None], [None, None, '、', None], [None, None, 'その', None], ['後', 'あと', None, None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'き', None], [None, None, 'ましょうか', None], [None, None, '。', None]]

 16%|█▌        | 148/938 [01:29<07:43,  1.71it/s]

[[None, None, 'こっち', None], [None, None, 'まで', True], [None, None, 'イライラしてきた。', None]]
[[None, None, 'それ', None], [None, None, 'まで', True], [None, None, 'やらなくてはいけないの？', None]]
[['頭', 'あたま', None, None], [None, None, 'まで', True], ['痛', 'いた', None, None], [None, None, 'くなっ', None], [None, None, 'てきた', None], [None, None, '。', None]]
[['夜中', 'よなか', None, None], [None, None, 'まで', True], ['日本語', 'にほんご', None, None], [None, None, 'の', None], ['文法', 'ぶんぽう', None, None], [None, None, 'を', None], ['勉強', 'べんきょう', None, None], [None, None, 'し', None], [None, None, 'ている', None], [None, None, '。', None]]
[[None, None, 'お', None], ['腹', 'なか', None, None], [None, None, 'が', None], ['空', 'す', None, None], [None, None, 'い', None], [None, None, 'ている', None], [None, None, 'とき', None], [None, None, '、', None], ['熊', 'くま', None, None], [None, None, 'は', None], ['果実', 'かじつ', None, None], [None, None, 'まで', True], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'る', None], [None, None, '。', None]]

 16%|█▌        | 149/938 [01:30<07:23,  1.78it/s]

[['明日', 'あした', None, None], [None, None, 'までに', True], ['電話', 'でんわ', None, None], [None, None, 'を', None], [None, None, 'ください。', None]]
[[None, None, 'お', None], ['昼', 'ひる', None, None], [None, None, 'までに', True], [None, None, 'は', None], ['着', 'つ', None, None], [None, None, 'きます。', None]]
[['１０', 'じゅう', None, None], ['時', 'じ', None, None], [None, None, 'までに', True], ['帰', 'かえ', None, None], [None, None, 'っ', None], [None, None, 'てき', None], [None, None, 'てください', None], [None, None, '。', None]]
[['来週', 'らいしゅう', None, None], [None, None, 'までに', True], [None, None, 'は', None], ['終', 'お', None, None], [None, None, 'わります。', None]]
[['８', 'はち', None, None], ['時', 'じ', None, None], [None, None, 'までに', True], ['学校', 'がっこう', None, None], [None, None, 'に', None], [None, None, 'つか', None], [None, None, 'なくてはいけない', None], [None, None, '。', None]]

 16%|█▌        | 150/938 [01:30<07:12,  1.82it/s]

[[None, None, 'また', True], ['寝坊', 'ねぼう', None, None], [None, None, 'したの？', None]]
[[None, None, 'また', True], [None, None, 'その', None], ['夢', 'ゆめ', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'たい', None], [None, None, '。', None]]
[[None, None, 'また', True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'から', None], [None, None, 'チョコ', None], [None, None, 'を', None], [None, None, 'もらった。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], [None, None, '、', None], [None, None, 'また', True], ['旅行', 'りょこう', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'つもり', None], [None, None, 'です', None], [None, None, '。', None]]
[['明日', 'あした', None, None], [None, None, 'から', None], [None, None, '、', None], [None, None, 'また', True], ['授業', 'じゅぎょう', None, None], [None, None, 'が', None], ['始', 'はじ', None, None], [None, None, 'まり', None], [None, None, 'ます', None], [None, None, '。', None]]

 16%|█▌        | 151/938 [01:31<07:03,  1.86it/s]

[['今朝', 'けさ', None, None], [None, None, '、', None], ['雪', 'ゆき', None, None], [None, None, 'が', None], ['降', 'ふ', None, True], [None, None, 'りはじめた', True], [None, None, '。', None]]
[['明日', 'あした', None, None], [None, None, 'から', None], [None, None, '、', None], ['日本語', 'にほんご', None, None], [None, None, 'を', None], ['習', 'なら', None, True], [None, None, 'いはじめます', True], [None, None, '。', None]]
[['練習', 'れんしゅう', None, None], [None, None, 'しはじめて', True], [None, None, 'ください。', None]]
[['９', 'く', None, None], ['時', 'じ', None, None], [None, None, 'になっ', None], [None, None, 'てから', None], [None, None, '、', None], ['働', 'はたら', None, True], [None, None, 'きはじめた', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'が', None], ['話', 'はな', None, True], [None, None, 'し', True], ['始', 'はじ', None, True], [None, None, 'めて', True], [None, None, 'から', None], ['１', 'いち', None, None], ['時間', 'じかん', None, None], ['経', 'た', None, None], [None, None, 'った。', None]]

 16%|█▌        | 152/938 [01:31<07:05,  1.85it/s]

[['２', 'に', None, None], ['時間', 'じかん', None, None], [None, None, 'も', None], [None, None, 'かか', None], [None, None, 'った', None], [None, None, 'けど', None], [None, None, '、', None], ['食', 'た', None, True], [None, None, 'べおわりました', True], [None, None, '。', None]]
[['３', 'さん', None, None], ['時', 'じ', None, None], [None, None, 'ごろ', None], [None, None, 'に', None], ['作', 'つく', None, True], [None, None, 'りおわる', True], [None, None, '。', None]]
[[None, None, 'この', None], ['番組', 'ばんぐみ', None, None], [None, None, 'は', None], ['見', 'み', None, True], [None, None, 'おわった', True], [None, None, '。', None]]
[['走', 'はし', None, True], [None, None, 'りおわった', True], [None, None, 'のは', None], ['何時', 'なんじ', None, None], [None, None, 'ぐらい', None], [None, None, 'でした', None], [None, None, 'か', None], [None, None, '？', None]]
[['宿題', 'しゅくだい', None, None], [None, None, 'を', None], ['直', 'なお', None, True], [None, None, 'しおわった', True], ['人', 'ひと', None, None], [None, None, 'は', None], ['教', 'おし', None, None], [None, None, 'えてください', None], [None, None, '。', None]]

 16%|█▋        | 153/938 [01:32<07:04,  1.85it/s]

[['８', 'はち', None, None], ['時', 'じ', None, None], ['頃', 'ごろ', None, True], [None, None, 'に', None], ['帰', 'かえ', None, None], [None, None, 'りました。', None]]
[['東京', 'とうきょう', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'った', None], ['友達', 'ともだち', None, None], [None, None, 'は', None], ['今', 'いま', None, None], ['頃', 'ごろ', None, True], ['着', 'つ', None, None], [None, None, 'い', None], [None, None, 'ている', None], [None, None, 'でしょう', None], [None, None, '。', None]]
[['月曜日', 'げつようび', None, None], [None, None, 'の', None], ['夜', 'よる', None, None], ['頃', 'ごろ', None, True], [None, None, 'に、', None], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'ります。', None]]
[['何時', 'なんじ', None, None], ['頃', 'ごろ', None, True], ['帰', 'かえ', None, None], [None, None, 'って', None], ['来', 'く', None, None], [None, None, 'る', None], [None, None, '？', None]]
[['１１時', 'じゅういちじ', None, None], ['頃', 'ごろ', None, True], [None, None, 'に', None], ['帰', 'かえ', None, None], [None, None, 'って', None], ['来', 'く', None, None], [None, None, 'る', None], [None, None, 'から', None], [None, None, '、ご', None], ['飯', 'はん', None, None], [None, None, 'は', None], [None, None, 'いら', None], [None, None, 'ない', None], [None, None, 'です', None], [None, None, '。', None]]

 16%|█▋        | 154/938 [01:33<07:57,  1.64it/s]

[[None, None, 'また', None], [None, None, 'あとで', True], [None, None, '、', None], ['会', 'あ', None, None], [None, None, 'い', None], [None, None, 'ましょう', None], [None, None, '。', None]]
[[None, None, 'あとで', True], ['買', 'か', None, None], [None, None, 'い', None], ['物', 'もの', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'きます。', None]]
[['勉強', 'べんきょう', None, None], [None, None, 'した', None], [None, None, 'あとで', True], [None, None, '、', None], ['遊', 'あそ', None, None], [None, None, 'んで', None], [None, None, 'も', None], [None, None, 'いい', None], [None, None, 'よ', None], [None, None, '。', None]]
[[None, None, 'あとで', True], ['話', 'はなし', None, None], [None, None, 'がある', None], [None, None, '。', None]]
[['食事', 'しょくじ', None, None], [None, None, 'のあとで', True], [None, None, '、お', None], ['皿', 'さら', None, None], [None, None, 'を', None], ['洗', 'あら', None, None], [None, None, 'わ', None], [None, None, 'なくてはいけない', None], [None, None, '。', None]]

 17%|█▋        | 155/938 [01:33<07:49,  1.67it/s]

[['勉強', 'べんきょう', None, None], [None, None, 'を', None], [None, None, 'していた', True], [None, None, 'けど', None], [None, None, '、', None], ['今', 'いま', None, None], [None, None, 'は', None], ['休', 'やす', None, None], [None, None, 'んでいる。', None]]
[['音楽', 'おんがく', None, None], [None, None, 'を', None], ['聴', 'き', None, True], [None, None, 'いていた', True], [None, None, 'から', None], [None, None, '、', None], ['電話', 'でんわ', None, None], [None, None, 'が', None], ['聞', 'き', None, None], [None, None, 'こえ', None], [None, None, 'なかった', None], [None, None, '。', None]]
[['昨日', 'きのう', None, None], ['１', 'いち', None, None], ['時', 'じ', None, None], [None, None, 'ごろ', None], [None, None, 'に', None], ['寝', 'ね', None, True], [None, None, 'ていた', True], [None, None, '。', None]]
[['４', 'よ', None, None], ['時間', 'じかん', None, None], [None, None, 'も', None], ['椅子', 'いす', None, None], [None, None, 'に', None], ['座', 'すわ', None, True], [None, None, 'っていた', True], [None, None, 'から', None], [None, None, '、お', None], ['尻', 'しり', None, None], [None, None, 'が', None], ['痛', 'いた', None, None], [None, None, 'い', None], [None, None, '。', None]]
[[None, None, 'お', None], ['母', 'かあ', None, None], [None, None, 'さん', None], [None, None, 'が', None], ['帰', 'かえ', None, None], [None, None, 'って', None], ['来', 'き', None, None], [None, None, 'た', None], ['時', 'とき', None, None], ['私', 'わたし', None, None], [None, None, 'は', None], [None, None, 'ご', None], ['飯', 'はん', None, None], [None, None, 'を', None], ['作', 'つく', None, True], [None, None, 'っていた', True], [None, None, '。', None]]

 17%|█▋        | 156/938 [01:34<07:37,  1.71it/s]

[['一年', 'いちねん', None, None], [None, None, 'に', True], ['三回', 'さんかい', None, None], [None, None, 'ぐらい', None], ['海外旅行', 'かいがいりょこう', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, '。', None]]
[['一日', 'いちにち', None, None], [None, None, 'に', True], ['六時間', 'ろくじかん', None, None], [None, None, 'は', None], ['寝', 'ね', None, None], [None, None, 'る', None], ['必要', 'ひつよう', None, None], [None, None, 'がある。', None]]
[['一時間', 'いちじかん', None, None], [None, None, 'に', True], ['十本', 'じゅっぽん', None, None], [None, None, 'の', None], ['電車', 'でんしゃ', None, None], [None, None, 'がある', None], [None, None, '。', None]]
[['公務員', 'こうむいん', None, None], [None, None, 'は', None], ['一年', 'いちねん', None, None], [None, None, 'に', True], ['一回', 'いっかい', None, None], [None, None, 'ボーナス', None], [None, None, 'を', None], [None, None, 'もら', None], [None, None, 'う。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], [None, None, 'タバコ', None], [None, None, 'を', None], ['１', 'いち', None, None], ['日', 'にち', None, None], [None, None, 'に', True], ['４０', 'よんじゅっ', None, None], ['本', 'ぽん', None, None], [None, None, 'ぐらい', None], ['吸', 'す', None, None], [None, None, 'う。', None]]

 17%|█▋        | 157/938 [01:34<07:31,  1.73it/s]

[['到頭', 'とうとう', None, True], ['休', 'やす', None, None], [None, None, 'み', None], [None, None, 'だ', None], [None, None, '。', None]]
[['到頭', 'とうとう', None, True], [None, None, 'タバコ', None], [None, None, 'を', None], [None, None, 'やめた。', None]]
[[None, None, 'それ', None], [None, None, 'を', None], ['到頭', 'とうとう', None, True], ['捨', 'す', None, None], [None, None, 'てた。', None]]
[['今日', 'きょう', None, None], ['痛', 'いた', None, None], [None, None, 'み', None], [None, None, 'が', None], ['到頭', 'とうとう', None, True], [None, None, 'なくな', None], [None, None, 'った', None], [None, None, '。', None]]
[['到頭', 'とうとう', None, True], ['漢字', 'かんじ', None, None], [None, None, 'の', None], ['勉強', 'べんきょう', None, None], [None, None, 'ができる。', None]]

 17%|█▋        | 158/938 [01:35<07:29,  1.73it/s]

[[None, None, 'あなた', None], [None, None, 'の', None], ['絵', 'え', None, None], [None, None, 'は', None], ['私', 'わたし', None, None], [None, None, 'の', None], ['絵', 'え', None, None], [None, None, 'より', True], ['上手', 'じょうず', None, None], [None, None, '。', None]]
[['月曜日', 'げつようび', None, None], [None, None, 'より', True], ['日曜日', 'にちようび', None, None], [None, None, 'が', None], [None, None, 'いい', None], [None, None, '。', None]]
[['日本語', 'にほんご', None, None], [None, None, 'は', None], ['英語', 'えいご', None, None], [None, None, 'より', True], ['話', 'はな', None, None], [None, None, 'し', None], [None, None, 'にくい', None], [None, None, '。', None]]
[[None, None, 'いつも', None], ['飲', 'の', None, None], [None, None, 'ん', None], [None, None, 'でいる', None], ['水', 'みず', None, None], [None, None, 'より', True], ['好', 'す', None, None], [None, None, 'き', None], [None, None, '。', None]]
[[None, None, 'スポーツ', None], [None, None, 'を', None], [None, None, 'する', None], [None, None, 'より', True], [None, None, '、ゲーム', None], [None, None, 'の', None], ['方', 'ほう', None, None], [None, None, 'が', None], ['楽', 'たの', None, None], [None, None, 'しい。', None]]

 17%|█▋        | 159/938 [01:36<07:26,  1.75it/s]

[[None, None, 'あのチームは、', None], ['試合', 'しあい', None, None], [None, None, 'をする', None], ['毎', 'ごと', None, True], [None, None, 'に', True], ['強', 'つよ', None, None], [None, None, 'くなっている。', None]]
[['夏', 'なつ', None, None], ['毎', 'ごと', None, True], [None, None, 'に', True], [None, None, 'アメリカに', None], ['帰', 'かえ', None, None], [None, None, 'り', None], [None, None, 'ます', None], [None, None, '。', None]]
[['生徒', 'せいと', None, None], ['毎', 'ごと', None, True], [None, None, 'に', True], ['紙', 'かみ', None, None], [None, None, 'を', None], ['渡', 'わた', None, None], [None, None, 'した', None], [None, None, '。', None]]
[['二日', 'ふつか', None, None], ['毎', 'ごと', None, True], [None, None, 'に', True], ['友達', 'ともだち', None, None], [None, None, 'と', None], [None, None, 'サッカー', None], [None, None, 'を', None], [None, None, 'する', None], [None, None, '。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'は', None], ['会', 'あ', None, None], [None, None, 'う', None], ['人', 'ひと', None, None], ['毎', 'ごと', None, True], [None, None, 'に', True], ['笑顔', 'えがお', None, None], [None, None, 'で', None], ['握手', 'あくしゅ', None, None], [None, None, 'します', None], [None, None, '。', None]]

 17%|█▋        | 160/938 [01:36<07:14,  1.79it/s]

[[None, None, 'なるべく', True], ['速', 'はや', None, None], [None, None, 'く', None], ['行', 'い', None, None], [None, None, 'きます。', None]]
[[None, None, 'なるべく', True], ['早', 'はや', None, None], [None, None, 'めに', None], ['連絡', 'れんらく', None, None], [None, None, 'し', None], [None, None, 'てください', None], [None, None, '。', None]]
[[None, None, 'なるべく', True], ['正直', 'しょうじき', None, None], [None, None, 'に', None], ['話', 'はな', None, None], [None, None, 'し', None], [None, None, 'てください', None], [None, None, '。', None]]
[[None, None, 'なるべく', True], ['早', 'はや', None, None], [None, None, 'めに', None], ['犯人', 'はんにん', None, None], [None, None, 'を', None], ['捕', 'つか', None, None], [None, None, 'まえ', None], [None, None, 'る', None], [None, None, 'つもり', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'なるべく', True], ['沢山', 'たくさん', None, None], [None, None, 'の', None], ['人気', 'にんき', None, None], [None, None, 'な', None], ['場所', 'ばしょ', None, None], [None, None, 'へ', None], ['行', 'い', None, None], [None, None, 'き', None], [None, None, 'たい', None], [None, None, '。', None]]

 17%|█▋        | 161/938 [01:37<07:13,  1.79it/s]

[['今', 'いま', None, None], [None, None, 'から', None], ['帰', 'かえ', None, None], [None, None, 'る', None], [None, None, 'ところ', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'ちょうど', None], ['出', 'で', None, None], [None, None, 'かけ', None], [None, None, 'る', None], [None, None, 'ところ', True], [None, None, 'だ', None], [None, None, '。', None]]
[['髪', 'かみ', None, None], [None, None, 'の', None], ['毛', 'け', None, None], [None, None, 'を', None], ['切', 'き', None, None], [None, None, 'る', None], [None, None, 'ところ', True], [None, None, 'でした', None], [None, None, '。', None]]
[['出', 'で', None, None], [None, None, 'かけ', None], [None, None, 'る', None], [None, None, 'ところ', True], [None, None, 'なので', None], ['洗', 'あら', None, None], [None, None, 'い', None], ['物', 'もの', None, None], [None, None, 'が', None], [None, None, 'でき', None], [None, None, 'ない', None], [None, None, '。', None]]
[['宿題', 'しゅくだい', None, None], [None, None, 'を', None], [None, None, 'する', None], [None, None, 'ところ', True], [None, None, 'で', None], [None, None, '、', None], ['友達', 'ともだち', None, None], [None, None, 'から', None], ['電話', 'でんわ', None, None], [None, None, 'が', None], ['入', 'はい', None, None], [None, None, 'った', None], [None, None, '。', None]]

 17%|█▋        | 162/938 [01:37<07:16,  1.78it/s]

[['無理', 'むり', None, None], [None, None, 'って', None], ['言', 'い', None, None], [None, None, 'った', None], [None, None, 'のに', True], [None, None, 'まだ', None], [None, None, 'やるの？', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['忙', 'いそが', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'のに', True], [None, None, '、ゲーム', None], [None, None, 'を', None], [None, None, 'し', None], [None, None, 'ている', None], [None, None, '。', None]]
[['天気予報', 'てんきよほう', None, None], [None, None, 'は', None], ['悪', 'わる', None, None], [None, None, 'かった', None], [None, None, 'のに', True], [None, None, '、', None], ['晴', 'は', None, None], [None, None, 'れた。', None]]
[[None, None, 'あの', None], ['女', 'おんな', None, None], [None, None, 'の', None], ['人', 'ひと', None, None], [None, None, 'は', None], [None, None, 'きれい', None], [None, None, 'なのに', True], [None, None, '、', None], ['彼氏', 'かれし', None, None], [None, None, 'が', None], [None, None, 'いない。', None]]
[[None, None, 'あまり', None], ['牛乳', 'ぎゅうにゅう', None, None], [None, None, 'がない', None], [None, None, 'のに', True], [None, None, 'スーパー', None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'った', None], ['時', 'とき', None, None], ['買', 'か', None, None], [None, None, 'わ', None], [None, None, 'なかった', None], [None, None, 'の？', None]]

 17%|█▋        | 163/938 [01:38<07:17,  1.77it/s]

[[None, None, 'この', None], [None, None, 'ズボン', None], [None, None, 'は', None], [None, None, 'いい', None], [None, None, 'と', True], ['思', 'おも', None, True], [None, None, 'います', True], [None, None, '。', None]]
[['今日', 'きょう', None, None], [None, None, '、', None], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'る', None], [None, None, 'と', True], ['思', 'おも', None, True], [None, None, 'った', True], [None, None, '。', None]]
[[None, None, 'そう', None], [None, None, 'だと', True], ['思', 'おも', None, True], [None, None, 'います', True], [None, None, '。', None]]
[[None, None, 'それ', None], [None, None, 'は', None], ['凄', 'すご', None, None], [None, None, 'い', None], [None, None, 'と', True], ['思', 'おも', None, True], [None, None, 'います', True], [None, None, '。', None]]
[[None, None, 'ダメ', None], [None, None, 'だと', True], ['思', 'おも', None, True], [None, None, 'います', True], [None, None, 'よ', None], [None, None, '。', None]]

 17%|█▋        | 164/938 [01:38<07:11,  1.80it/s]

[[None, None, 'イタリア', None], [None, None, 'や', None], [None, None, 'アメリカ', None], [None, None, 'など', True], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'き', None], [None, None, 'たい', None], [None, None, '。', None]]
[[None, None, 'フルーツ', None], [None, None, 'は', None], [None, None, 'ぶどう', None], [None, None, 'など', True], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'です', None], [None, None, '。', None]]
[['趣味', 'しゅみ', None, None], [None, None, 'など', True], [None, None, 'を', None], ['教', 'おし', None, None], [None, None, 'え', None], [None, None, 'てください', None], [None, None, '。', None]]
[['明日', 'あした', None, None], [None, None, 'から', None], [None, None, '、', None], ['準備', 'じゅんび', None, None], [None, None, 'など', True], [None, None, 'を', None], [None, None, 'する', None], [None, None, 'つもり', None], [None, None, 'です', None], [None, None, '。', None]]
[['数学', 'すうがく', None, None], [None, None, 'など', True], [None, None, 'を', None], ['勉強', 'べんきょう', None, None], [None, None, 'します', None], [None, None, '。', None]]

 18%|█▊        | 165/938 [01:39<07:09,  1.80it/s]

[[None, None, 'この', None], ['犬', 'いぬ', None, None], [None, None, 'は', None], ['熊', 'くま', None, None], [None, None, 'みたい', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'は', None], ['有名人', 'ゆうめいじん', None, None], [None, None, 'みたい', True], [None, None, 'です', None], [None, None, '。', None]]
[['今日', 'きょう', None, None], [None, None, 'の', None], ['昼', 'ひる', None, None], [None, None, 'から', None], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'る', None], [None, None, 'みたい', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'あの', None], ['雲', 'くも', None, None], [None, None, 'は', None], ['馬', 'うま', None, None], [None, None, 'みたい', True], [None, None, '。', None]]
[[None, None, 'あの', None], [None, None, 'ビル', None], [None, None, 'は', None], ['会社', 'かいしゃ', None, None], [None, None, 'じゃなくて', None], ['病院', 'びょういん', None, None], [None, None, 'みたい', True], [None, None, '。', None]]

 18%|█▊        | 166/938 [01:40<07:53,  1.63it/s]

[['日本語', 'にほんご', None, None], [None, None, 'を', None], ['話', 'はな', None, None], [None, None, 'す', None], [None, None, 'こと', True], [None, None, 'は', None], ['難', 'むずか', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, '。', None]]
[[None, None, 'スポーツ', None], [None, None, 'を', None], [None, None, 'する', None], [None, None, 'こと', True], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, '。', None]]
[[None, None, 'ダンス', None], [None, None, 'を', None], [None, None, 'する', None], [None, None, 'こと', True], [None, None, 'は', None], ['楽', 'たの', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, '。', None]]
[['大', 'おお', None, None], [None, None, 'き', None], [None, None, 'い', None], ['声', 'こえ', None, None], [None, None, 'で', None], ['喋', 'しゃべ', None, True], [None, None, 'らないこと', True], [None, None, '。', None]]
[[None, None, 'フォーク', None], [None, None, 'じゃなくて', None], [None, None, '、お', None], ['箸', 'はし', None, None], [None, None, 'を', None], ['使', 'つか', None, True], [None, None, 'うこと', True], [None, None, '。', None]]

 18%|█▊        | 167/938 [01:40<07:49,  1.64it/s]

[['雪', 'ゆき', None, None], [None, None, 'が', None], ['降', 'ふ', None, True], [None, None, 'りそう', True], [None, None, 'です', None], [None, None, '。', None]]
[['先生', 'せんせい', None, None], [None, None, 'の', None], ['仕事', 'しごと', None, None], [None, None, 'は', None], ['難', 'むずか', None, True], [None, None, 'しそう', True], [None, None, 'です', None], [None, None, '。', None]]
[['今日', 'きょう', None, None], [None, None, 'の', None], ['宿題', 'しゅくだい', None, None], [None, None, 'は', None], ['簡単', 'かんたん', None, True], [None, None, 'そう', True], [None, None, 'だ', None], [None, None, '。', None]]
[[None, None, 'その', None], ['食', 'た', None, None], [None, None, 'べ', None], ['物', 'もの', None, None], [None, None, 'は', None], ['食', 'た', None, True], [None, None, 'べやすそう', True], [None, None, '。', None]]
[[None, None, 'この', None], ['教科書', 'きょうかしょ', None, None], [None, None, 'は', None], [None, None, 'とても', None], ['難', 'むずか', None, True], [None, None, 'しそう', True], [None, None, 'です', None], [None, None, '。', None]]

 18%|█▊        | 168/938 [01:41<07:32,  1.70it/s]

[[None, None, 'この', None], ['美', 'うつく', None, True], [None, None, 'しさ', True], [None, None, 'は', None], ['初', 'はじ', None, None], [None, None, 'めて', None], [None, None, 'です', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'の', None], ['元気', 'げんき', None, True], [None, None, 'さ', True], [None, None, 'は', None], ['子供', 'こども', None, None], [None, None, 'みたい。', None]]
[[None, None, 'この', None], ['甘', 'あま', None, True], [None, None, 'さ', True], [None, None, 'は', None], ['美味', 'おい', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, '。', None]]
[['箱', 'はこ', None, None], [None, None, 'の', None], ['重', 'おも', None, True], [None, None, 'さ', True], [None, None, 'を', None], ['測', 'はか', None, None], [None, None, 'ってください。', None]]
[[None, None, 'この', None], ['寒', 'さむ', None, True], [None, None, 'さ', True], [None, None, 'だけで', None], ['死', 'し', None, None], [None, None, 'ぬ', None], [None, None, 'よ', None], [None, None, '。', None]]

 18%|█▊        | 169/938 [01:41<07:37,  1.68it/s]

[['青', 'あお', None, None], [None, None, 'とか', True], ['水色', 'みずいろ', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, '。', None]]
[['明日', 'あした', None, None], [None, None, 'とか', True], ['今週末', 'こんしゅうまつ', None, None], [None, None, 'とか', True], [None, None, '、', None], ['暇', 'ひま', None, None], [None, None, 'なら', None], [None, None, '、', None], ['映画', 'えいが', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'こう', None], [None, None, '。', None]]
[[None, None, 'トム・クルーズ', None], [None, None, 'とか', True], [None, None, 'ブラッド・ピット', None], [None, None, 'とか', True], [None, None, 'が', None], [None, None, 'かっこいい', None], [None, None, 'と', None], ['思', 'おも', None, None], [None, None, 'う', None], [None, None, '。', None]]
[['日本', 'にほん', None, None], [None, None, 'とか', True], [None, None, '、', None], ['韓国', 'かんこく', None, None], [None, None, 'とか', True], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'っ', None], [None, None, 'てみ', None], [None, None, 'たい', None], [None, None, 'です', None], [None, None, 'ね', None], [None, None, '。', None]]
[['日本語', 'にほんご', None, None], [None, None, 'で', None], [None, None, '「th」', None], [None, None, 'の', None], ['音', 'おと', None, None], [None, None, 'とか', True], [None, None, 'は', None], [None, None, 'ない', None], [None, None, 'です', None], [None, None, '。', None]]

 18%|█▊        | 170/938 [01:42<07:58,  1.60it/s]

[[None, None, 'そういう', True], ['人', 'ひと', None, None], [None, None, 'も', None], [None, None, 'いる', None], [None, None, 'よ', None], [None, None, '。', None]]
[[None, None, 'どういう', True], ['意味', 'いみ', None, None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'ああいう', True], ['消', 'け', None, None], [None, None, 'しゴム', None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, '。', None]]
[[None, None, 'こういう', True], ['人形', 'にんぎょう', None, None], [None, None, 'がほし', None], [None, None, 'い。', None]]
[[None, None, 'こういう', True], ['仕事', 'しごと', None, None], [None, None, 'を', None], [None, None, 'し', None], [None, None, 'なくちゃいけない', None], [None, None, '。', None]]

 18%|█▊        | 171/938 [01:43<08:04,  1.58it/s]

[[None, None, 'あなたが好きな', None], [None, None, 'ケーキ', None], [None, None, 'を', None], ['買', 'か', None, True], [None, None, 'ってあげよう', True], [None, None, '。', None]]
[['毎日', 'まいにち', None, None], [None, None, 'スポーツ', None], [None, None, 'を', None], [None, None, 'しよう', True], [None, None, '。', None]]
[['朝', 'あさ', None, None], [None, None, 'ご', None], ['飯', 'はん', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べに', None], ['行', 'い', None, True], [None, None, 'こう', True], [None, None, '。', None]]
[[None, None, 'ここ', None], [None, None, 'に', None], [None, None, 'は', None], [None, None, 'あまり', None], [None, None, 'いい', None], [None, None, 'もの', None], [None, None, 'がない', None], [None, None, 'から', None], ['帰', 'かえ', None, True], [None, None, 'ろう', True], [None, None, '。', None]]
[['今日', 'きょう', None, None], [None, None, 'は', None], ['早', 'はや', None, None], [None, None, 'く', None], ['帰', 'かえ', None, True], [None, None, 'ろう', True], [None, None, '。', None]]

 18%|█▊        | 172/938 [01:43<08:30,  1.50it/s]

[[None, None, 'ほとんど', None], ['無', 'な', None, None], [None, None, 'くなっ', None], [None, None, 'ている', None], [None, None, 'ようだ', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], [None, None, 'ここ', None], [None, None, 'に', None], ['来', 'こ', None, None], [None, None, 'ない', None], [None, None, 'ようだ', True], [None, None, '。', None]]
[['今日', 'きょう', None, None], [None, None, 'の', None], ['天気', 'てんき', None, None], [None, None, 'は', None], ['台風', 'たいふう', None, None], [None, None, 'のようだ', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'の', None], ['話', 'はな', None, None], [None, None, 'し', None], ['方', 'かた', None, None], [None, None, 'は', None], ['歌', 'うた', None, None], [None, None, 'っ', None], [None, None, 'ている', None], [None, None, 'ようだ', True], [None, None, '。', None]]
[[None, None, 'この', None], [None, None, 'コーラ', None], [None, None, 'は', None], ['苦', 'にが', None, None], [None, None, 'い', None], [None, None, '。まるでコーヒー', None], [None, None, 'のようだ', True], [None, None, '。', None]]

 18%|█▊        | 173/938 [01:44<09:04,  1.41it/s]

[['着物', 'きもの', None, None], [None, None, 'が', None], ['全然', 'ぜんぜん', None, True], ['似合', 'にあ', None, None], [None, None, 'わ', None], [None, None, 'ない', None], [None, None, '。', None]]
[['全然', 'ぜんぜん', None, True], ['頑張', 'がんば', None, None], [None, None, 'り', None], [None, None, 'たい', None], [None, None, 'と', None], ['思', 'おも', None, None], [None, None, 'わ', None], [None, None, 'ない', None], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], ['全然', 'ぜんぜん', None, True], ['英語', 'えいご', None, None], [None, None, 'を', None], ['話', 'はな', None, None], [None, None, 'せない', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'あなた', None], [None, None, 'は', None], ['全然', 'ぜんぜん', None, True], ['理解', 'りかい', None, None], [None, None, 'が', None], ['出来', 'でき', None, None], [None, None, 'てい', None], [None, None, 'ない', None], [None, None, 'ね', None], [None, None, '。', None]]
[['今', 'いま', None, None], [None, None, '、', None], ['機嫌', 'きげん', None, None], [None, None, 'が', None], ['悪', 'わる', None, None], [None, None, 'く', None], [None, None, 'て', None], [None, None, '、', None], ['全然', 'ぜんぜん', None, True], ['嬉', 'うれ', None, None], [None, None, 'しくなら', None], [None, None, 'ない', None], [None, None, '。', None]]

 19%|█▊        | 174/938 [01:45<08:50,  1.44it/s]

[[None, None, 'もう', None], [None, None, 'すぐ', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'かな', True], [None, None, '。', None]]
[['明日', 'あした', None, None], [None, None, 'は', None], ['運動', 'うんどう', None, None], [None, None, 'を', None], [None, None, 'した', None], ['方', 'ほう', None, None], [None, None, 'がいい', None], [None, None, 'かな', True], [None, None, '。', None]]
[['今週末', 'こんしゅうまつ', None, None], [None, None, 'に', None], ['友達', 'ともだち', None, None], [None, None, 'と', None], ['会', 'あ', None, None], [None, None, 'える', None], [None, None, 'かな', True], [None, None, '。', None]]
[['冷蔵庫', 'れいぞうこ', None, None], [None, None, 'にケーキ', None], [None, None, 'まだ', None], [None, None, 'ある', None], [None, None, 'かな', True], [None, None, '。', None]]
[[None, None, 'お', None], ['母', 'かあ', None, None], [None, None, 'さん', None], [None, None, 'は', None], ['何', 'なに', None, None], [None, None, 'を', None], [None, None, 'くれる', None], [None, None, 'かな', True], [None, None, '。', None]]

 19%|█▊        | 175/938 [01:45<08:19,  1.53it/s]

[[None, None, 'この', None], [None, None, 'ケーキ', None], [None, None, 'は', None], [None, None, 'あまり', True], ['美味', 'おい', None, None], [None, None, 'し', None], [None, None, 'くない', None], [None, None, '。', None]]
[[None, None, 'あまり', True], ['肉', 'にく', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'ない', None], [None, None, '。', None]]
[[None, None, 'あまり', True], ['大変', 'たいへん', None, None], [None, None, 'な', None], [None, None, 'こと', None], [None, None, 'ではない', None], [None, None, 'から', None], [None, None, '、', None], ['心配', 'しんぱい', None, None], [None, None, 'いら', None], [None, None, 'ない', None], [None, None, 'よ', None], [None, None, '。', None]]
[['寿司', 'すし', None, None], [None, None, 'を', None], [None, None, 'あまり', True], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'たい', None], [None, None, 'と', None], ['思', 'おも', None, None], [None, None, 'わ', None], [None, None, 'ない', None], [None, None, '。', None]]
[[None, None, 'この', None], ['漢字', 'かんじ', None, None], [None, None, 'の', None], ['意味', 'いみ', None, None], [None, None, 'が', None], [None, None, 'あまり', True], ['分', 'わ', None, None], [None, None, 'かり', None], [None, None, 'ません', None], [None, None, '。', None]]

 19%|█▉        | 176/938 [01:46<08:11,  1.55it/s]

[[None, None, 'ヘルメット', None], [None, None, 'を', None], ['被', 'かぶ', None, True], [None, None, 'らなければ', True], [None, None, '、バイクに', None], ['乗', 'の', None, None], [None, None, 'れない', None], [None, None, '。', None]]
[['明日', 'あした', None, None], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, True], [None, None, 'れば', True], [None, None, '、', None], ['映画', 'えいが', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'つもり', None], [None, None, '。', None]]
[['毎日', 'まいにち', None, None], [None, None, 'サッカー', None], [None, None, 'の', None], ['練習', 'れんしゅう', None, None], [None, None, 'に', None], ['行', 'い', None, True], [None, None, 'けば', True], [None, None, '、プロ', None], [None, None, 'の', None], [None, None, 'サッカー', None], ['選手', 'せんしゅ', None, None], [None, None, 'になれる。', None]]
[['今週', 'こんしゅう', None, None], [None, None, 'の', None], ['金曜日', 'きんようび', None, None], [None, None, 'までに', None], ['出来', 'でき', None, True], [None, None, 'なければ', True], [None, None, '、', None], ['来週末', 'らいしゅうまつ', None, None], [None, None, 'に', None], ['終', 'お', None, None], [None, None, 'わ', None], [None, None, 'らせ', None], [None, None, 'なくてはいけない', None], [None, None, '。', None]]
[['展覧会', 'てんらんかい', None, None], [None, None, 'に', None], ['行', 'い', None, True], [None, None, 'けば', True], [None, None, '、', None], ['色々', 'いろいろ', None, None], [None, None, 'な', None], [None, None, 'こと', None], [None, None, 'を', None], ['学', 'まな', None, None], [None, None, 'べる', None], [None, None, '。', None]]

 19%|█▉        | 177/938 [01:47<07:59,  1.59it/s]

[['君', 'きみ', None, None], [None, None, 'なら', True], [None, None, '、でき', None], [None, None, 'る', None], [None, None, '。', None]]
[[None, None, 'そういう', None], [None, None, 'こと', None], [None, None, 'なら', True], [None, None, '、', None], ['聞', 'き', None, None], [None, None, 'かなくていい。', None]]
[['宿題', 'しゅくだい', None, None], [None, None, 'が', None], ['難', 'むずか', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'なら', True], [None, None, '、', None], ['一緒', 'いっしょ', None, None], [None, None, 'にしよう。', None]]
[[None, None, 'また', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'なら', True], [None, None, '、', None], ['帰', 'かえ', None, None], [None, None, 'って', None], ['来', 'こ', None, None], [None, None, 'ないでください', None], [None, None, '。', None]]
[['暑', 'あつ', None, None], [None, None, 'い', None], [None, None, 'なら', True], [None, None, '、', None], ['扇風機', 'せんぷうき', None, None], [None, None, 'を', None], ['点', 'つ', None, None], [None, None, 'け', None], [None, None, 'てください', None], [None, None, '。', None]]

 19%|█▉        | 178/938 [01:47<07:48,  1.62it/s]

[['私', 'わたし', None, None], [None, None, 'の', None], ['猫', 'ねこ', None, None], [None, None, 'は', None], ['怖', 'こわ', None, True], [None, None, 'がる', True], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['弟', 'おとうと', None, None], [None, None, 'は', None], ['強', 'つよ', None, True], [None, None, 'がる', True], [None, None, '。', None]]
[[None, None, 'あの', None], ['子', 'こ', None, None], [None, None, 'は', None], [None, None, 'ゲーム', None], [None, None, 'を', None], [None, None, 'ほしがる', True], [None, None, '。', None]]
[['映画', 'えいが', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'て', None], [None, None, '、', None], ['面白', 'おもしろ', None, True], [None, None, 'がっています', True], [None, None, '。', None]]
[['君', 'きみ', None, None], [None, None, 'の', None], ['車', 'くるま', None, None], [None, None, 'を', None], ['欲', 'ほ', None, True], [None, None, 'しがる', True], ['人', 'ひと', None, None], [None, None, 'は', None], [None, None, 'いない', None], [None, None, 'と', None], ['思', 'おも', None, None], [None, None, 'う', None], [None, None, '。', None]]

 19%|█▉        | 179/938 [01:48<07:42,  1.64it/s]

[['車', 'くるま', None, None], [None, None, 'の', None], ['音', 'おと', None, None], [None, None, 'がする', True], [None, None, '。', None]]
[[None, None, 'この', None], ['部屋', 'へや', None, None], [None, None, 'は', None], [None, None, 'コーヒー', None], [None, None, 'の', None], ['匂', 'にお', None, None], [None, None, 'い', None], [None, None, 'がします', True], [None, None, '。', None]]
[[None, None, 'この', None], ['料理', 'りょうり', None, None], [None, None, 'は', None], ['塩', 'しお', None, None], [None, None, 'の', None], ['味', 'あじ', None, None], [None, None, 'がします', True], [None, None, '。', None]]
[['変', 'へん', None, None], [None, None, 'な', None], ['味', 'あじ', None, None], [None, None, 'がする', True], [None, None, 'ので', None], [None, None, 'これを', None], ['捨', 'す', None, None], [None, None, 'てます。', None]]
[[None, None, 'お', None], ['砂糖', 'さとう', None, None], [None, None, 'を', None], ['入', 'い', None, None], [None, None, 'れ', None], ['過', 'す', None, None], [None, None, 'ぎた', None], [None, None, 'から', None], [None, None, '、', None], ['甘', 'あま', None, None], [None, None, 'い', None], ['味', 'あじ', None, None], [None, None, 'がする', True], [None, None, '。', None]]

 19%|█▉        | 180/938 [01:48<07:36,  1.66it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], ['動物園', 'どうぶつえん', None, None], [None, None, 'に', None], ['行', 'い', None, True], [None, None, 'きたがる', True], [None, None, '。', None]]
[['娘', 'むすめ', None, None], [None, None, 'は', None], [None, None, 'いつもスポーツ', None], [None, None, 'を', None], [None, None, 'したがる', True], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['最近', 'さいきん', None, None], [None, None, 'の', None], ['映画', 'えいが', None, None], [None, None, 'を', None], ['見', 'み', None, True], [None, None, 'たがる', True], [None, None, '。', None]]
[[None, None, 'あの', None], ['子', 'こ', None, None], [None, None, 'が', None], ['帰', 'かえ', None, True], [None, None, 'りたがる', True], [None, None, 'なら', None], [None, None, 'いい', None], [None, None, 'ん', None], [None, None, 'じゃない', None], [None, None, '？', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], [None, None, 'パソコン', None], [None, None, 'を', None], ['買', 'か', None, True], [None, None, 'いたがって', True], [None, None, '、', None], ['週末', 'しゅうまつ', None, None], [None, None, 'も', None], ['働', 'はたら', None, None], [None, None, 'いた', None], [None, None, '。', None]]

 19%|█▉        | 181/938 [01:49<07:21,  1.71it/s]

[[None, None, 'そう', None], [None, None, 'かも', True], [None, None, 'ね', None], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'が', None], [None, None, 'また', None], ['遅', 'おく', None, None], [None, None, 'れ', None], [None, None, 'る', None], [None, None, 'かもしれません', True], [None, None, '。', None]]
[['来年', 'らいねん', None, None], [None, None, 'アメリカ', None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'かもしれない', True], [None, None, '。', None]]
[[None, None, 'この', None], [None, None, 'いい', None], ['服', 'ふく', None, None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'え', None], [None, None, 'ば', None], [None, None, '、', None], ['人気', 'にんき', None, None], [None, None, 'にな', None], [None, None, 'る', None], [None, None, 'かもしれない', True], [None, None, '。', None]]
[[None, None, 'そういうこと', None], [None, None, 'を', None], ['言', 'い', None, None], [None, None, 'わ', None], [None, None, 'ないほうがいい', None], [None, None, 'かもしれない', True], [None, None, '。', None]]

 19%|█▉        | 182/938 [01:50<07:10,  1.76it/s]

[['私', 'わたし', None, None], [None, None, 'は', None], [None, None, 'あの', None], ['女', 'おんな', None, None], [None, None, 'の', None], ['人', 'ひと', None, None], [None, None, 'みたいに', True], [None, None, 'なりたい。', None]]
[[None, None, 'それ', None], [None, None, 'は', None], ['城', 'しろ', None, None], [None, None, 'みたいな', True], ['家', 'いえ', None, None], [None, None, 'です', None], [None, None, '。', None]]
[['魚', 'さかな', None, None], [None, None, 'みたいに', True], ['泳', 'およ', None, None], [None, None, 'ぎ', None], [None, None, 'たい', None], [None, None, '。', None]]
[[None, None, 'サンダル', None], [None, None, 'みたいに', True], ['履', 'は', None, None], [None, None, 'き', None], [None, None, 'やすい', None], [None, None, '。', None]]
[[None, None, 'お', None], ['金', 'かね', None, None], ['持', 'も', None, None], [None, None, 'ち', None], [None, None, 'の', None], ['人', 'ひと', None, None], [None, None, 'みたいな', True], ['生活', 'せいかつ', None, None], [None, None, 'を', None], [None, None, 'し', None], [None, None, 'たい', None], [None, None, '。', None]]

 20%|█▉        | 183/938 [01:50<07:15,  1.73it/s]

[[None, None, 'これ', None], [None, None, 'が', None], ['入', 'はい', None, True], [None, None, 'りそうな', True], ['箱', 'はこ', None, None], [None, None, 'って', None], [None, None, 'ある？', None]]
[['優', 'やさ', None, True], [None, None, 'しそうに', True], ['犬', 'いぬ', None, None], [None, None, 'を', None], ['撫', 'な', None, None], [None, None, 'でた。', None]]
[['今日', 'きょう', None, None], [None, None, 'は', None], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, True], [None, None, 'りそうな', True], ['日', 'ひ', None, None], [None, None, 'です', None], [None, None, 'ね', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['分', 'わ', None, True], [None, None, 'かりやすそうな', True], ['説明', 'せつめい', None, None], [None, None, 'をした', None], [None, None, 'が', None], [None, None, '、', None], [None, None, 'まだ', None], ['理解', 'りかい', None, None], [None, None, 'が', None], [None, None, 'できない。', None]]
[[None, None, 'つまらなそうな', True], ['話', 'はなし', None, None], [None, None, 'は', None], ['聞', 'き', None, None], [None, None, 'き', None], [None, None, 'たくない', None], [None, None, '。', None]]

 20%|█▉        | 184/938 [01:51<07:20,  1.71it/s]

[[None, None, 'スープ', None], [None, None, 'のような', True], [None, None, 'カレー。', None]]
[[None, None, 'その', None], [None, None, 'ように', True], ['使', 'つか', None, None], [None, None, 'っ', None], [None, None, 'てはいけない', None], [None, None, '。', None]]
[[None, None, 'その', None], [None, None, 'ように', True], [None, None, 'お', None], ['箸', 'はし', None, None], [None, None, 'を', None], ['使', 'つか', None, None], [None, None, 'わないで下さい。', None]]
[[None, None, 'この', None], [None, None, 'ような', True], ['洋服', 'ようふく', None, None], [None, None, 'を', None], ['探', 'さが', None, None], [None, None, 'しています。', None]]
[[None, None, 'お', None], ['箸', 'はし', None, None], [None, None, 'は', None], [None, None, 'この', None], [None, None, 'ように', True], ['使', 'つか', None, None], [None, None, 'い', None], [None, None, 'ます', None], [None, None, '。', None]]

 20%|█▉        | 185/938 [01:51<07:16,  1.72it/s]

[['明日', 'あした', None, None], [None, None, '、', None], ['勉強', 'べんきょう', None, None], [None, None, 'を', None], [None, None, 'しようと', True], ['思', 'おも', None, True], [None, None, 'う', True], [None, None, '。', None]]
[['来年', 'らいねん', None, None], [None, None, '、', None], ['家', 'いえ', None, None], [None, None, 'を', None], ['買', 'か', None, True], [None, None, 'おうと', True], ['思', 'おも', None, True], [None, None, 'う', True], [None, None, '。', None]]
[['帰', 'かえ', None, None], [None, None, 'っ', None], [None, None, 'てから', None], [None, None, '、お', None], ['菓子', 'かし', None, None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べようと', True], ['思', 'おも', None, True], [None, None, 'います', True], [None, None, '。', None]]
[['今日', 'きょう', None, None], [None, None, 'から', None], ['文法', 'ぶんぽう', None, None], [None, None, 'の', None], ['勉強', 'べんきょう', None, None], [None, None, 'を', None], ['始', 'はじ', None, True], [None, None, 'めようと', True], ['思', 'おも', None, True], [None, None, 'う', True], [None, None, '。', None]]
[['息子', 'むすこ', None, None], [None, None, 'は', None], [None, None, 'レゴ', None], [None, None, 'を', None], ['欲', 'ほ', None, None], [None, None, 'しがっ', None], [None, None, 'ている', None], [None, None, 'から', None], [None, None, '、', None], ['買', 'か', None, True], [None, None, 'ってあげようと', True], ['思', 'おも', None, True], [None, None, 'う', True], [None, None, '。', None]]

 20%|█▉        | 186/938 [01:52<07:37,  1.64it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], ['彼女', 'かのじょ', None, None], [None, None, 'に', None], ['甘', 'あま', None, True], [None, None, 'く', True], ['話', 'はな', None, None], [None, None, 'しかけた。', None]]
[['料理', 'りょうり', None, None], [None, None, 'を', None], ['軽', 'かる', None, True], [None, None, 'く', True], ['味見', 'あじみ', None, None], [None, None, 'した。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'はいつも', None], ['前向', 'まえむ', None, True], [None, None, 'きに', True], ['考', 'かんが', None, None], [None, None, 'える。', None]]
[['姉', 'あね', None, None], [None, None, 'は', None], ['丁寧', 'ていねい', None, True], [None, None, 'に', True], [None, None, 'プレゼントを', None], ['作', 'つく', None, None], [None, None, 'った。', None]]
[['試験前', 'しけんまえ', None, None], [None, None, 'の', None], ['夜', 'よる', None, None], [None, None, 'は', None], ['早', 'はや', None, True], [None, None, 'めに', True], ['寝', 'ね', None, None], [None, None, 'たほうがいい。', None]]

 20%|█▉        | 187/938 [01:53<07:40,  1.63it/s]

[['頑張', 'がんば', None, None], [None, None, 'って', None], ['部品', 'ぶひん', None, None], [None, None, 'を', None], ['小', 'ちい', None, True], [None, None, 'さくして', True], [None, None, 'ください', None], [None, None, '。', None]]
[['布団', 'ふとん', None, None], [None, None, 'を', None], ['新', 'あたら', None, True], [None, None, 'しくした', True], [None, None, 'から', None], ['気持', 'きも', None, None], [None, None, 'ちいい。', None]]
[['歯医者', 'はいしゃ', None, None], [None, None, 'さん', None], [None, None, 'で', None], ['歯', 'は', None, None], [None, None, 'を', None], ['白', 'しろ', None, True], [None, None, 'くして', True], [None, None, 'もら', None], [None, None, 'った', None], [None, None, '。', None]]
[[None, None, 'お', None], ['花見', 'はなみ', None, None], [None, None, 'に', None], [None, None, 'は', None], ['温', 'あたた', None, True], [None, None, 'かくして', True], ['行', 'い', None, None], [None, None, 'っ', None], [None, None, 'た', None], ['方', 'ほう', None, None], [None, None, 'がいい', None], [None, None, '。', None]]
[[None, None, 'この', None], ['部屋', 'へや', None, None], [None, None, 'を', None], ['大', 'おお', None, True], [None, None, 'きくしたい', True], [None, None, 'です', None], [None, None, '。', None]]

 20%|██        | 188/938 [01:53<07:35,  1.65it/s]

[['試合', 'しあい', None, None], [None, None, 'で', None], ['勝', 'か', None, None], [None, None, 'つ', None], [None, None, 'といい', True], [None, None, 'です', None], [None, None, 'ね', None], [None, None, '。', None]]
[[None, None, 'あなた', None], [None, None, 'は', None], [None, None, 'もっと', None], ['果物', 'くだもの', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'る', None], [None, None, 'といい', True], [None, None, 'です', None], [None, None, '。', None]]
[['楽', 'たの', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'といい', True], [None, None, 'ん', None], [None, None, 'ですが', None], [None, None, '。', None]]
[[None, None, 'あの', None], ['選手', 'せんしゅ', None, None], [None, None, 'が', None], ['世界', 'せかい', None, None], ['一', 'いち', None, None], [None, None, 'にな', None], [None, None, 'る', None], [None, None, 'といい', True], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'から', None], [None, None, 'も', None], [None, None, 'どんどん', None], ['強', 'つよ', None, None], [None, None, 'くな', None], [None, None, 'る', None], [None, None, 'といい', True], [None, None, 'ね。', None]]

 20%|██        | 189/938 [01:54<07:29,  1.67it/s]

[[None, None, 'ちゃんと', None], ['英語', 'えいご', None, None], [None, None, 'を', None], ['勉強', 'べんきょう', None, None], [None, None, 'すれば、', None], ['話', 'はな', None, None], [None, None, 'せる', None], [None, None, 'ようになる', True], [None, None, '。', None]]
[['泳', 'およ', None, None], [None, None, 'げる', None], [None, None, 'ようになった', True], [None, None, '。', None]]
[['理解', 'りかい', None, None], ['出来', 'でき', None, None], [None, None, 'る', None], [None, None, 'ようになった', True], [None, None, '。', None]]
[['料理', 'りょうり', None, None], [None, None, 'が', None], [None, None, 'でき', None], [None, None, 'る', None], [None, None, 'ようになりたい', True], [None, None, '。', None]]
[['１００', 'ひゃく', None, None], [None, None, 'メートル', None], [None, None, 'を', None], ['１０', 'じゅう', None, None], ['秒', 'びょう', None, None], [None, None, 'で', None], ['走', 'はし', None, None], [None, None, 'れる', None], [None, None, 'ようになった', True], [None, None, '。', None]]

 20%|██        | 190/938 [01:54<07:16,  1.71it/s]

[[None, None, 'ともきさん', None], [None, None, 'は', None], ['仕事', 'しごと', None, None], ['前', 'まえ', None, None], [None, None, 'に', None], ['毎日', 'まいにち', None, True], [None, None, 'のように', True], ['釣', 'つ', None, None], [None, None, 'り', None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'った', None], [None, None, '。', None]]
[['仕事', 'しごと', None, None], [None, None, 'を', None], ['終', 'お', None, None], [None, None, 'わ', None], [None, None, 'った', None], [None, None, 'とき', None], [None, None, 'は', None], ['毎晩', 'まいばん', None, True], [None, None, 'のように', True], [None, None, 'ジム', None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['彼', 'かれ', None, None], [None, None, 'に', None], ['出会', 'であ', None, None], [None, None, 'う', None], ['前', 'まえ', None, None], [None, None, 'は', None], [None, None, '、', None], ['毎日', 'まいにち', None, True], [None, None, 'のように', True], ['高校', 'こうこう', None, None], [None, None, 'を', None], [None, None, 'サボっ', None], [None, None, 'ていた', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], [None, None, 'その', None], ['後', 'あと', None, None], [None, None, '、', None], ['故郷', 'ふるさと', None, None], [None, None, 'に ', None], ['毎月', 'まいつき', None, True], [None, None, 'のように', True], ['帰', 'かえ', None, None], [None, None, 'った', None], [None, None, '。', None]]
[['日本', 'にほん', None, None], [None, None, 'で', None], [None, None, 'は', None], [None, None, ' ', None], ['毎年', 'まいとし', None, True], [None, None, 'のように', True], ['少', 'すく', None, None], [None, None, 'なくとも', None], ['１', 'いっ', None, None], ['回', 'かい', None, None], [None, None, 'は', None], ['地震', 'じしん', None, None], [None, None, 'が', None], ['起', 'お', None, None], [None, None, 'こる。', None]]

 20%|██        | 191/938 [01:55<07:18,  1.70it/s]

[[None, None, 'そのこと', None], [None, None, 'じゃなかったか', True], [None, None, '。', None]]
[[None, None, 'もう', None], ['終', 'お', None, None], [None, None, 'わ', None], [None, None, 'るん', None], [None, None, 'じゃないか', True], [None, None, '。', None]]
[[None, None, 'あれ', None], [None, None, 'カメラ', None], [None, None, 'じゃないか', True], [None, None, '！', None]]
[['次', 'つぎ', None, None], [None, None, 'の', None], ['駅', 'えき', None, None], [None, None, 'で', None], ['降', 'お', None, None], [None, None, 'り', None], [None, None, 'る', None], [None, None, 'んじゃないか', True], [None, None, '？', None]]
[[None, None, 'この', None], ['橋', 'はし', None, None], [None, None, 'を', None], ['渡', 'わた', None, None], [None, None, 'る', None], [None, None, 'の', None], [None, None, 'が', None], ['怖', 'こわ', None, None], [None, None, 'い', None], [None, None, 'んじゃないか', True], [None, None, '？', None]]

 20%|██        | 192/938 [01:55<07:14,  1.72it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], [None, None, 'ダイエット', None], [None, None, 'を', None], ['続', 'つづ', None, None], [None, None, 'け', None], [None, None, 'る', None], [None, None, 'らしい', True], [None, None, 'です', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['姉', 'あね', None, None], [None, None, 'の', None], [None, None, 'タイプ', None], [None, None, 'じゃない', None], [None, None, 'らしい', True], [None, None, '。', None]]
[[None, None, 'あなた', None], [None, None, 'の', None], ['元彼女', 'もとかのじょ', None, None], [None, None, 'が', None], ['婚約', 'こんやく', None, None], [None, None, 'した', None], [None, None, 'らしい', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'は', None], ['会社', 'かいしゃ', None, None], [None, None, 'の', None], ['社長', 'しゃちょう', None, None], [None, None, 'らしい', True], [None, None, 'よ', None], [None, None, '。', None]]
[['日本語', 'にほんご', None, None], [None, None, 'を', None], ['話', 'はな', None, None], [None, None, 'せ', None], [None, None, 'なくて', None], [None, None, 'も', None], [None, None, '、', None], ['日本', 'にほん', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'ける', None], [None, None, 'らしい', True], [None, None, '。', None]]

 21%|██        | 193/938 [01:56<07:14,  1.71it/s]

[[None, None, 'ここ', None], [None, None, 'にリモコン', None], [None, None, 'を', None], ['置', 'お', None, True], [None, None, 'いておく', True], [None, None, 'ね', None], [None, None, '。', None]]
[[None, None, 'ちょっと', None], ['調', 'しら', None, True], [None, None, 'べておきます', True], [None, None, '。', None]]
[['帰', 'かえ', None, None], [None, None, 'っ', None], [None, None, 'てくる', None], [None, None, 'のが', None], ['遅', 'おそ', None, None], [None, None, 'くな', None], [None, None, 'る', None], [None, None, 'から', None], [None, None, '、ご', None], ['飯', 'はん', None, None], [None, None, 'を', None], ['作', 'つく', None, True], [None, None, 'っておいた', True], [None, None, '。', None]]
[['明日', 'あした', None, None], [None, None, 'の', None], [None, None, 'パーティー', None], [None, None, 'の', None], [None, None, 'ために', None], [None, None, 'ジュース', None], [None, None, 'を', None], ['買', 'か', None, True], [None, None, 'っておきました', True], [None, None, '。', None]]
[['今夜', 'こんや', None, None], ['明日', 'あした', None, None], [None, None, 'の', None], [None, None, 'お', None], ['弁当', 'べんとう', None, None], [None, None, 'を', None], ['作', 'つく', None, True], [None, None, 'っておいて', True], [None, None, 'くれますか？', None]]

 21%|██        | 194/938 [01:57<07:05,  1.75it/s]

[['機会', 'きかい', None, None], [None, None, 'がほしい', True], [None, None, '。', None]]
[['君', 'きみ', None, None], [None, None, 'がほしい', True], [None, None, '！', None]]
[['猫', 'ねこ', None, None], [None, None, 'が', True], ['欲', 'ほ', None, True], [None, None, 'しくない', True], [None, None, 'です', None], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], [None, None, 'いい', None], ['服', 'ふく', None, None], [None, None, 'など', None], [None, None, 'がほしい', True], [None, None, 'です', None], [None, None, '。', None]]
[['使', 'つか', None, None], [None, None, 'い', None], [None, None, 'やすい', None], ['箸', 'はし', None, None], [None, None, 'がほしい', True], [None, None, '。', None]]

 21%|██        | 195/938 [01:57<07:04,  1.75it/s]

[['車', 'くるま', None, None], [None, None, 'で', None], ['来', 'き', None, True], [None, None, 'てほしかった', True], [None, None, '。', None]]
[[None, None, 'コーラ', None], [None, None, 'を', None], ['買', 'か', None, True], [None, None, 'ってほしい', True], [None, None, 'です', None], [None, None, '。', None]]
[['一緒', 'いっしょ', None, None], [None, None, 'にサッカー', None], [None, None, 'を', None], [None, None, 'してほしい', True], [None, None, '。', None]]
[['一緒', 'いっしょ', None, None], [None, None, 'に', None], ['食', 'た', None, True], [None, None, 'べに', True], ['行', 'い', None, True], [None, None, 'ってほしい', True], [None, None, 'んです', None], [None, None, '。', None]]
[['毎日', 'まいにち', None, None], [None, None, 'お', None], ['弁当', 'べんとう', None, None], [None, None, 'を', None], ['作', 'つく', None, True], [None, None, 'ってほしい', True], [None, None, 'です', None], [None, None, '。', None]]

 21%|██        | 196/938 [01:58<07:29,  1.65it/s]

[['明日', 'あした', None, None], [None, None, 'は', None], [None, None, 'テスト', None], [None, None, 'がある', None], [None, None, 'と', True], ['聞', 'き', None, True], [None, None, 'いた', True], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'は', None], ['無理', 'むり', None, None], [None, None, 'だと', True], ['聞', 'き', None, True], [None, None, 'いた', True], [None, None, '。', None]]
[[None, None, 'トム', None], [None, None, 'は', None], ['旅館', 'りょかん', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'っ', None], [None, None, 'たことがない', None], [None, None, 'と', True], ['聞', 'き', None, True], [None, None, 'いた', True], [None, None, '。', None]]
[['市内', 'しない', None, None], [None, None, 'にあるスーツ', None], ['屋', 'や', None, None], [None, None, 'が', None], ['安', 'やす', None, None], [None, None, 'い', None], [None, None, 'と', True], ['聞', 'き', None, True], [None, None, 'いた', True], [None, None, '。', None]]
[['近', 'ちか', None, None], [None, None, 'くの', None], ['映画館', 'えいがかん', None, None], [None, None, 'の', None], [None, None, 'スクリーン', None], [None, None, 'が', None], ['一番', 'いちばん', None, None], ['大', 'おお', None, None], [None, None, 'き', None], [None, None, 'い', None], [None, None, 'と', True], ['聞', 'き', None, True], [None, None, 'いた', True], [None, None, '。', None]]

 21%|██        | 197/938 [01:58<07:26,  1.66it/s]

[[None, None, '「', None], ['今', 'いま', None, None], [None, None, 'の', None], [None, None, 'ノック', None], ['聞', 'き', None, True], [None, None, 'こえ', True], [None, None, 'た', None], [None, None, '？」', None], [None, None, '「ううん、', None], ['聞', 'き', None, True], [None, None, 'こえ', True], [None, None, 'なかった', None], [None, None, 'よ', None], [None, None, '。', None], ['空耳', 'そらみみ', None, None], [None, None, 'じゃない', None], [None, None, '？」', None]]
[[None, None, '「', None], ['西山', 'にしやま', None, None], [None, None, 'さん', None], [None, None, 'は', None], ['生', 'う', None, None], [None, None, 'まれつき', None], ['耳', 'みみ', None, None], [None, None, 'が', None], ['聞', 'き', None, True], [None, None, 'こえない', True], [None, None, 'んです', None], [None, None, '。」', None]]
[['隣', 'となり', None, None], [None, None, 'の', None], [None, None, 'せきくん', None], [None, None, 'は', None], [None, None, 'うるさ', None], [None, None, 'すぎ', None], [None, None, 'る', None], [None, None, 'わ', None], [None, None, 'よ', None], [None, None, '。', None], ['彼', 'かれ', None, None], [None, None, 'が', None], ['音楽', 'おんがく', None, None], [None, None, 'を', None], ['聴', 'き', None, None], [None, None, 'く', None], [None, None, 'とき', None], [None, None, 'いつもあたし', None], [None, None, 'の', None], [None, None, 'アパートに', None], ['聞', 'き', None, True], [None, None, 'こえる', True], [None, None, 'わ！', None]]
[[None, None, '「', None], ['教師', 'きょうし', None, None], [None, None, 'の', None], ['声', 'こえ', None, None], [None, None, 'が', None], ['小', 'ちい', None, None], [None, None, 'さ', None], [None, None, 'すぎ', None], [None, None, 'る', None], [None, None, 'から', None], ['何', 'なに', None, None], [None, None, 'も', None], ['聞', 'き', None, True], [None, None, 'こえない', True], [None, None, 'んだ', None], [None, None, 'よ', None], [None, None, '。」', None]]
[[None, None, '「', None], ['外', 'そと', None, None], [None, None, 'が', None], [None, None, 'うるさ', None], [None, None, 'い', None], [None, None, 'から', None], [None, None, 'テレビ', None], [None, None, 'の', None], ['音', 'おと', None, None], [None, None, 'が', None], [None, None, 'よく', None], ['聞', 'き', None, True], [None, None, 'こえない', True], [None, None, '。」', None]]

 21%|██        | 198/938 [01:59<07:52,  1.57it/s]

[[None, None, '「', None], ['遠', 'とお', None, None], [None, None, 'すぎ', None], [None, None, 'る', None], [None, None, 'から', None], ['書', 'か', None, None], [None, None, 'かれ', None], [None, None, 'ている', None], [None, None, 'こと', None], [None, None, 'が', None], ['見', 'み', None, True], [None, None, 'えない', True], [None, None, 'よ', None], [None, None, '。」', None]]
[[None, None, '「', None], [None, None, 'あの', None], ['看板', 'かんばん', None, None], [None, None, 'は', None], ['大', 'おお', None, None], [None, None, 'き', None], [None, None, 'い', None], [None, None, 'ので、', None], [None, None, 'どこ', None], [None, None, 'から', None], [None, None, 'でも', None], [None, None, 'よく', None], ['見', 'み', None, True], [None, None, 'える', True], [None, None, '。」', None]]
[[None, None, '「', None], ['富士山', 'ふじさん', None, None], [None, None, 'は', None], [None, None, 'とても', None], ['大', 'おお', None, None], [None, None, 'き', None], [None, None, 'い', None], [None, None, 'から', None], ['遠', 'とお', None, None], [None, None, 'く', None], [None, None, 'から', None], [None, None, 'でもよく', None], ['見', 'み', None, True], [None, None, 'える', True], [None, None, '！」', None]]
[['雨', 'あめ', None, None], [None, None, 'が', None], [None, None, 'やんで、', None], ['今', 'いま', None, None], [None, None, 'で', None], [None, None, 'は', None], [None, None, 'はっきりと', None], ['見', 'み', None, True], [None, None, 'える', True], [None, None, 'よ', None], [None, None, '♪', None]]
[['田舎', 'いなか', None, None], [None, None, 'は', None], ['都会', 'とかい', None, None], [None, None, 'より', None], ['明', 'あ', None, None], [None, None, 'かりが', None], ['少', 'すく', None, None], [None, None, 'な', None], [None, None, 'い', None], [None, None, 'から', None], ['星', 'ほし', None, None], [None, None, 'が', None], [None, None, 'よく', None], ['見', 'み', None, True], [None, None, 'える', True], [None, None, '。', None]]

 21%|██        | 199/938 [02:00<07:34,  1.63it/s]

[[None, None, 'あの', None], ['子', 'こ', None, None], [None, None, 'は', None], ['急', 'きゅう', None, None], [None, None, 'に', None], ['泣', 'な', None, True], [None, None, 'き', True], ['出', 'だ', None, True], [None, None, 'した', True], [None, None, '。', None]]
[['面白', 'おもしろ', None, None], [None, None, 'いこと', None], [None, None, 'を', None], ['今', 'いま', None, None], ['思', 'おも', None, True], [None, None, 'い', True], ['出', 'だ', None, True], [None, None, 'した', True], [None, None, '。', None]]
[['晴', 'は', None, None], [None, None, 'れ', None], [None, None, 'ていた', None], [None, None, 'のに', None], [None, None, '、', None], ['雨', 'あめ', None, None], [None, None, 'が', None], ['急', 'きゅう', None, None], [None, None, 'に', None], ['降', 'ふ', None, True], [None, None, 'り', True], ['出', 'だ', None, True], [None, None, 'した', True], [None, None, '。', None]]
[['夜中', 'よなか', None, None], [None, None, 'に', None], ['夫', 'おっと', None, None], [None, None, 'が', None], ['急', 'きゅう', None, None], [None, None, 'に', None], ['餃子', 'ぎょうざ', None, None], [None, None, 'を', None], ['作', 'つく', None, True], [None, None, 'りだした', True], [None, None, '。', None]]
[['何', 'なに', None, None], [None, None, 'も', None], ['言', 'い', None, None], [None, None, 'わ', None], [None, None, 'ないで', None], ['走', 'はし', None, True], [None, None, 'り', True], ['出', 'だ', None, True], [None, None, 'した', True], [None, None, '。', None]]

 21%|██▏       | 200/938 [02:00<07:29,  1.64it/s]

[['街頭', 'がいとう', None, None], [None, None, 'インタビュー、', None], ['通行人', 'つうこうにん', None, None], [None, None, '：「', None], ['１９８０', 'せんきゅうひゃくはちじゅう', None, None], ['年代', 'ねんだい', None, True], [None, None, 'ころ', None], [None, None, 'から', None], [None, None, 'ここ', None], [None, None, 'に', None], ['住', 'す', None, None], [None, None, 'んでいます。」', None]]
[['証人', 'しょうにん', None, None], [None, None, 'が', None], ['警察官', 'けいさつかん', None, None], [None, None, 'に', None], ['言', 'い', None, None], [None, None, 'う', None], [None, None, '：「', None], ['泥棒', 'どろぼう', None, None], [None, None, 'は', None], ['３０', 'さんじゅう', None, None], ['代', 'だい', None, True], ['半', 'なか', None, None], [None, None, 'ば', None], [None, None, 'だった', None], [None, None, 'と思います。」', None]]
[['新聞記事', 'しんぶんきじ', None, None], [None, None, '：「', None], ['Ｘ', 'エックス', None, None], [None, None, 'さん', None], [None, None, 'は', None], ['昭和', 'しょうわ', None, None], ['５０', 'ごじゅう', None, None], ['年代', 'ねんだい', None, True], [None, None, 'の', None], ['終', 'お', None, None], [None, None, 'わ', None], [None, None, 'り', None], [None, None, 'ごろ', None], [None, None, 'にお', None], ['金持', 'かねも', None, None], [None, None, 'ち', None], [None, None, 'にな', None], [None, None, 'った', None], [None, None, '。」', None]]
[['漫画', 'まんが', None, None], [None, None, 'の', None], [None, None, 'ナレーター', None], [None, None, '：「イラめぐみ', None], [None, None, 'は', None], ['３０', 'さんじゅう', None, None], ['代', 'だい', None, True], ['前半', 'ぜんはん', None, None], [None, None, 'で', None], ['次長', 'じちょう', None, None], [None, None, 'にな', None], [None, None, 'った', None], [None, None, '。」', None]]
[['新聞記事', 'しんぶんきじ', None, None], [None, None, '：「', None], ['２０１０', 'にせんじゅう', None, None], ['年代', 'ねんだい', None, True], [None, None, 'の', None], ['終', 'お', None, None], [None, None, 'わ', None], [None, None, 'り', None], [None, None, 'から', None], [None, None, 'ハイエンドスマホ', None], [None, None, 'の', None], ['値段', 'ねだん', None, None], [None, None, 'が', None], ['上', 'あ', None, None], [None, None, 'がり', None], ['始', 'はじ', None, None], [None, None, 'め', None], [None, None, 'た', None], [None, None, '。」', None]]

 21%|██▏       | 201/938 [02:01<07:50,  1.56it/s]

[['１０', 'じゅう', None, None], ['万円', 'まんえん', None, None], [None, None, 'も', True], ['払', 'はら', None, None], [None, None, 'わ', None], [None, None, 'なくてはいけない', None], [None, None, '。', None]]
[['１０', 'じゅっ', None, None], ['回', 'かい', None, None], [None, None, 'も', True], [None, None, 'やった', None], [None, None, 'けど', None], [None, None, '、でき', None], [None, None, 'なかった', None], [None, None, '。', None]]
[[None, None, 'アメリカ', None], [None, None, 'まで', None], ['１５', 'じゅうご', None, None], ['時間', 'じかん', None, None], [None, None, 'も', True], [None, None, 'かかりました。', None]]
[['１０時間', 'じゅうじかん', None, None], [None, None, 'も', True], ['運転', 'うんてん', None, None], [None, None, 'した', None], [None, None, 'けど', None], [None, None, '、', None], [None, None, 'あまり', None], ['疲', 'つか', None, None], [None, None, 'れ', None], [None, None, 'ていない', None], [None, None, '。', None]]
[[None, None, '「', None], ['掃除', 'そうじ', None, None], [None, None, 'を', None], [None, None, 'して」', None], [None, None, 'って', None], ['何回', 'なんかい', None, None], [None, None, 'も', True], ['言', 'い', None, None], [None, None, 'った', None], [None, None, 'でしょう', None], [None, None, '。', None]]

 22%|██▏       | 202/938 [02:02<07:30,  1.63it/s]

[[None, None, 'みんな', None], [None, None, 'は', None], [None, None, '、', None], [None, None, 'ほとんど', True], ['帰', 'かえ', None, None], [None, None, 'りました。', None]]
[[None, None, 'ハンドバッグ', None], [None, None, 'が', None], [None, None, 'ほとんど', True], ['売', 'う', None, None], [None, None, 'り', None], ['切', 'き', None, None], [None, None, 'れ', None], [None, None, 'でした', None], [None, None, '。', None]]
[['今日', 'きょう', None, None], [None, None, 'は', None], ['宿題', 'しゅくだい', None, None], [None, None, 'が', None], [None, None, 'ほとんど', True], [None, None, 'ない', None], [None, None, '。', None]]
[[None, None, 'この', None], ['湖', 'みずうみ', None, None], [None, None, 'は', None], [None, None, 'ほとんど', True], ['浅', 'あさ', None, None], [None, None, 'い', None], [None, None, 'と', None], ['思', 'おも', None, None], [None, None, 'う', None], [None, None, '。', None]]
[[None, None, 'えっ！', None], [None, None, 'この', None], ['魚', 'さかな', None, None], [None, None, 'ほとんど', True], ['匂', 'にお', None, None], [None, None, 'い', None], [None, None, 'が', None], [None, None, 'ない', None], [None, None, '。', None]]

 22%|██▏       | 203/938 [02:02<07:18,  1.67it/s]

[[None, None, 'どんな', True], ['車', 'くるま', None, None], [None, None, 'が', None], [None, None, 'いい', None], [None, None, '。', None]]
[[None, None, 'そんな', True], ['技術', 'ぎじゅつ', None, None], [None, None, 'は', None], ['珍', 'めずら', None, None], [None, None, 'しい。', None]]
[[None, None, 'こんな', True], ['高', 'たか', None, None], [None, None, 'いの', None], [None, None, 'は', None], ['必要', 'ひつよう', None, None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'こんな', True], ['畳', 'たたみ', None, None], [None, None, 'が', None], ['大体', 'だいたい', None, None], ['寝', 'ね', None, None], [None, None, 'やすい', None], [None, None, '。', None]]
[[None, None, 'あんな', True], ['駐車場', 'ちゅうしゃじょう', None, None], [None, None, 'は', None], ['使', 'つか', None, None], [None, None, 'い', None], [None, None, 'にくい', None], [None, None, '。', None]]

 22%|██▏       | 204/938 [02:03<08:21,  1.46it/s]

[['各', 'かく', None, True], [None, None, 'ファイル', None], [None, None, 'を', None], ['各', 'かく', None, True], ['自', 'じ', None, None], [None, None, 'アップロード', None], [None, None, 'する', None], ['必要', 'ひつよう', None, None], [None, None, 'がある。', None]]
[[None, None, 'この', None], [None, None, 'バス', None], [None, None, 'は', None], ['各', 'かく', None, True], [None, None, 'バス', None], ['停', 'てい', None, None], [None, None, 'に', None], ['止', 'と', None, None], [None, None, 'まり', None], [None, None, 'ます', None], [None, None, '。', None]]
[['各', 'かく', None, True], ['自', 'じ', None, None], [None, None, 'で', None], ['弁当', 'べんとう', None, None], [None, None, 'を', None], ['持', 'も', None, None], [None, None, 'っ', None], [None, None, 'てきて', None], [None, None, 'ください', None], [None, None, '。', None]]
[[None, None, 'この', None], ['書類', 'しょるい', None, None], [None, None, 'の', None], ['各', 'かく', None, True], [None, None, 'ページ', None], [None, None, 'を', None], [None, None, 'プリントアウトし', None], [None, None, 'てください', None], [None, None, '。', None]]
[['各', 'かく', None, True], ['部屋', 'へや', None, None], [None, None, 'に', None], ['冷房', 'れいぼう', None, None], [None, None, 'が', None], [None, None, 'つい', None], [None, None, 'ている', None], [None, None, '。', None]]

 22%|██▏       | 205/938 [02:04<07:55,  1.54it/s]

[[None, None, 'その', None], ['時', 'とき', None, None], [None, None, 'に', None], ['１００', 'ひゃく', None, None], ['人', 'にん', None, None], ['以上', 'いじょう', None, True], [None, None, 'も', None], ['参加', 'さんか', None, None], [None, None, 'した。', None]]
[['六', 'ろく', None, None], ['歳', 'さい', None, None], ['以上', 'いじょう', None, True], [None, None, '。', None]]
[[None, None, 'これ', None], ['以上', 'いじょう', None, True], [None, None, 'は', None], [None, None, 'もう', None], ['聞', 'き', None, None], [None, None, 'き', None], [None, None, 'たくない', None], [None, None, '。', None]]
[[None, None, 'これ', None], ['以上', 'いじょう', None, True], ['運動', 'うんどう', None, None], [None, None, 'を', None], [None, None, 'したくない。', None]]
[[None, None, 'それ', None], ['以上', 'いじょう', None, True], ['私', 'わたし', None, None], [None, None, 'の', None], [None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'を', None], ['使', 'つか', None, None], [None, None, 'わないで。', None]]

 22%|██▏       | 206/938 [02:04<07:31,  1.62it/s]

[[None, None, 'この', None], ['家', 'いえ', None, None], [None, None, 'は', None], ['２０００', 'にせん', None, None], ['万', 'まん', None, None], ['円', 'えん', None, None], ['以下', 'いか', None, True], [None, None, 'です', None], [None, None, '。', None]]
[['五千', 'ごせん', None, None], ['円', 'えん', None, None], ['以下', 'いか', None, True], [None, None, 'の', None], [None, None, 'コーヒーメーカー', None], [None, None, 'がない', None], [None, None, 'んです', None], [None, None, 'か', None], [None, None, '。', None]]
[['残', 'のこ', None, None], [None, None, 'っ', None], [None, None, 'ている', None], [None, None, 'ジュース', None], [None, None, 'は', None], ['十', 'じゅっ', None, None], ['本', 'ぽん', None, None], ['以下', 'いか', None, True], [None, None, 'だ', None], [None, None, '。', None]]
[[None, None, 'これ', None], ['以下', 'いか', None, True], [None, None, 'の', None], ['値段', 'ねだん', None, None], [None, None, 'がありません', None], [None, None, '。', None]]
[[None, None, 'コンサート', None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'った', None], [None, None, 'のは', None], ['１００', 'ひゃく', None, None], ['人', 'にん', None, None], ['以下', 'いか', None, True], [None, None, '。', None]]

 22%|██▏       | 207/938 [02:05<07:22,  1.65it/s]

[[None, None, 'メアリー', None], ['以外', 'いがい', None, True], [None, None, '、', None], ['誰', 'だれ', None, None], [None, None, 'も', None], ['来', 'こ', None, None], [None, None, 'なかった。', None]]
[[None, None, 'それ', None], ['以外', 'いがい', None, True], [None, None, '、', None], ['聞', 'き', None, None], [None, None, 'い', None], [None, None, 'てない', None], [None, None, 'よ', None], [None, None, '。', None]]
[['納豆', 'なっとう', None, None], ['以外', 'いがい', None, True], ['何', 'なん', None, None], [None, None, 'でも', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'られる', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['言', 'い', None, None], [None, None, 'わ', None], [None, None, 'れた', None], [None, None, 'こと', None], ['以外', 'いがい', None, True], ['何', 'なに', None, None], [None, None, 'も', None], [None, None, 'しない', None], [None, None, 'よ', None], [None, None, '。', None]]
[[None, None, 'それ', None], ['以外', 'いがい', None, True], [None, None, 'に', None], ['好', 'す', None, None], [None, None, 'きなことないの？', None]]

 22%|██▏       | 208/938 [02:05<07:53,  1.54it/s]

[[None, None, '「', None], [None, None, 'ずっと', True], ['前', 'まえ', None, None], [None, None, 'から', None], ['日本', 'にほん', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'き', None], [None, None, 'たかった', None], [None, None, 'です', None], [None, None, '。」', None]]
[['朝', 'あさ', None, None], [None, None, 'から', None], [None, None, 'ずっと', True], ['忙', 'いそが', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'です', None], [None, None, 'よ', None], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], ['子供', 'こども', None, None], [None, None, 'の', None], ['頃', 'ころ', None, None], [None, None, 'から', None], ['彼', 'かれ', None, None], [None, None, 'に', None], [None, None, 'ずっと', True], ['会', 'あ', None, None], [None, None, 'っ', None], [None, None, 'ていません', None], [None, None, '。', None]]
[['私達', 'わたしたち', None, None], [None, None, 'は', None], ['結婚', 'けっこん', None, None], [None, None, 'し', None], [None, None, 'て', None], [None, None, 'から', None], [None, None, 'ずっと', True], [None, None, 'ここ', None], [None, None, 'に', None], ['住', 'す', None, None], [None, None, 'んでいます。', None]]
[['冬休', 'ふゆやす', None, None], [None, None, 'み', None], [None, None, 'は', None], [None, None, 'ノートパソコン', None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'える', None], [None, None, 'ように', None], [None, None, 'ずっと', True], ['働', 'はたら', None, None], [None, None, 'い', None], [None, None, 'ていた', None], [None, None, '。', None]]

 22%|██▏       | 209/938 [02:06<08:40,  1.40it/s]

[[None, None, '「', None], ['日本語', 'にほんご', None, None], [None, None, 'が', None], ['大体', 'だいたい', None, True], [None, None, 'わかる。」', None]]
[[None, None, '「', None], ['大体', 'だいたい', None, True], ['３', 'さん', None, None], ['時間', 'じかん', None, None], [None, None, 'くらい', None], [None, None, 'ででき', None], [None, None, 'ます', None], [None, None, '。」', None]]
[[None, None, '「', None], ['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['大体', 'だいたい', None, True], [None, None, 'の', None], ['状況', 'じょうきょう', None, None], [None, None, 'を', None], ['知', 'し', None, None], [None, None, 'っています。」', None]]
[['焼', 'や', None, None], [None, None, 'きたてパンについて', None], ['話', 'はな', None, None], [None, None, 'し', None], [None, None, 'ている', None], [None, None, 'カップル、', None], ['彼女', 'かのじょ', None, None], [None, None, '：「どう？」', None], ['彼氏', 'かれし', None, None], [None, None, '：「', None], ['大体', 'だいたい', None, True], [None, None, 'いい', None], [None, None, 'と', None], ['思', 'おも', None, None], [None, None, 'う', None], [None, None, 'んだけど', None], [None, None, '、」', None]]
[['電話', 'でんわ', None, None], [None, None, 'にで', None], [None, None, 'ている', None], ['子供', 'こども', None, None], [None, None, '：「', None], ['父', 'ちち', None, None], [None, None, 'は', None], ['大体', 'だいたい', None, True], ['５時', 'ごじ', None, None], [None, None, 'ごろ', None], ['帰', 'かえ', None, None], [None, None, 'り', None], [None, None, 'ます', None], [None, None, '。」', None]]

 22%|██▏       | 210/938 [02:07<08:23,  1.45it/s]

[[None, None, 'この', None], ['三', 'みっ', None, None], [None, None, 'つ', None], [None, None, 'の', True], ['中', 'なか', None, True], [None, None, 'で', True], [None, None, 'は、', None], ['赤', 'あか', None, None], ['色', 'いろ', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き。', None]]
[[None, None, 'フルーツ', None], [None, None, 'の', True], ['中', 'なか', None, True], [None, None, 'で', True], [None, None, '、イチゴ', None], [None, None, 'とか', None], [None, None, 'パイン', None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, '。', None]]
[[None, None, 'この', None], ['中', 'なか', None, True], [None, None, 'で', True], ['一', 'ひと', None, None], [None, None, 'つ', None], [None, None, 'を', None], ['選', 'えら', None, None], [None, None, 'んで', None], [None, None, 'ください。', None]]
[['公園', 'こうえん', None, None], [None, None, 'の', True], ['中', 'なか', None, True], [None, None, 'で', True], ['子供', 'こども', None, None], ['達', 'たち', None, None], [None, None, 'が', None], ['遊', 'あそ', None, None], [None, None, 'ん', None], [None, None, 'でいた', None], [None, None, '。', None]]
[['全部', 'ぜんぶ', None, None], [None, None, 'の', None], ['国', 'くに', None, None], [None, None, 'の', True], ['中', 'なか', None, True], [None, None, 'で', True], [None, None, '、', None], ['一番', 'いちばん', None, None], ['行', 'い', None, None], [None, None, 'っ', None], [None, None, 'てみたい', None], [None, None, 'のは', None], [None, None, 'どこ', None], [None, None, '？', None]]

 22%|██▏       | 211/938 [02:08<08:11,  1.48it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'すぎた', None], [None, None, 'ような', True], ['顔', 'かお', None, None], [None, None, 'を', None], [None, None, 'し', None], [None, None, 'ている', None], [None, None, '。', None]]
[[None, None, 'あなた', None], [None, None, 'が', None], ['言', 'い', None, None], [None, None, 'った', None], [None, None, 'ように', True], [None, None, '、', None], ['事故', 'じこ', None, None], [None, None, 'が', None], ['起', 'お', None, None], [None, None, 'こ', None], [None, None, 'った', None], [None, None, '。', None]]
[['十', 'じゅう', None, None], ['代', 'だい', None, None], [None, None, 'に', None], ['戻', 'もど', None, None], [None, None, 'った', None], [None, None, 'ように', True], ['楽', 'たの', None, None], [None, None, 'し', None], [None, None, 'かった', None], [None, None, '。', None]]
[['君', 'きみ', None, None], [None, None, 'が', None], ['言', 'い', None, None], [None, None, 'う', None], [None, None, 'ように', True], ['綺麗', 'きれい', None, None], [None, None, 'です', None], [None, None, 'ね', None], [None, None, '。', None]]
[['驚', 'おどろ', None, None], [None, None, 'く', None], [None, None, 'ような', True], ['景色', 'けしき', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'た', None], [None, None, '。', None]]

 23%|██▎       | 212/938 [02:08<07:52,  1.54it/s]

[[None, None, 'クリスマス', None], [None, None, 'ぐらいは', True], ['家', 'いえ', None, None], [None, None, 'に', None], ['帰', 'かえ', None, None], [None, None, 'って', None], ['来', 'き', None, None], [None, None, 'てね？', None]]
[['少', 'すく', None, None], [None, None, 'なくとも', None], [None, None, 'これ', None], [None, None, 'ぐらいは', True], ['持', 'も', None, None], [None, None, 'って', None], ['行', 'い', None, None], [None, None, 'ってください。', None]]
[['囚人', 'しゅうじん', None, None], [None, None, 'の', None], [None, None, 'うち', None], ['少', 'すく', None, None], [None, None, 'なくとも', None], ['６人', 'ろくにん', None, None], [None, None, 'は', True], ['逃', 'に', None, None], [None, None, 'げた', None], [None, None, 'らしい', None], [None, None, '。', None]]
[[None, None, 'この', None], ['食', 'た', None, None], [None, None, 'べ', None], ['物', 'もの', None, None], [None, None, 'は', None], ['少', 'すく', None, None], [None, None, 'なくとも', None], ['床', 'ゆか', None, None], [None, None, 'に', None], ['３', 'さん', None, None], ['秒', 'びょう', None, None], [None, None, 'は', True], ['落', 'お', None, None], [None, None, 'ち', None], [None, None, 'ていた', None], [None, None, 'から', None], ['食', 'た', None, None], [None, None, 'べられない。', None]]
[['付', 'つ', None, None], [None, None, 'き', None], ['合', 'あ', None, None], [None, None, 'っ', None], [None, None, 'ている', None], [None, None, 'んだ', None], [None, None, 'から', None], ['手', 'て', None, None], [None, None, 'ぐらいは', True], [None, None, 'つないだ', None], [None, None, 'でしょう', None], [None, None, 'ね', None], [None, None, '？', None]]

 23%|██▎       | 213/938 [02:09<07:33,  1.60it/s]

[[None, None, 'この', None], [None, None, 'アニメ', None], [None, None, 'の', None], [None, None, 'なん', True], ['話', 'わ', None, True], [None, None, 'か', True], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'た', None], [None, None, 'と', None], ['思', 'おも', None, None], [None, None, 'う', None], [None, None, '。', None]]
[['昨日', 'きのう', None, None], [None, None, 'なん', True], ['台', 'だい', None, True], [None, None, 'か', True], [None, None, 'の', None], ['車', 'くるま', None, None], [None, None, 'が', None], ['盗', 'ぬす', None, None], [None, None, 'まれた', None], [None, None, 'らしい', None], [None, None, '。', None]]
[['選手', 'せんしゅ', None, None], [None, None, 'の', None], [None, None, 'なん', True], ['人', 'にん', None, True], [None, None, 'か', True], [None, None, 'が', None], ['負傷', 'ふしょう', None, None], [None, None, 'した。', None]]
[[None, None, 'なん', True], ['冊', 'さつ', None, True], [None, None, 'か', True], [None, None, 'の', None], ['本', 'ほん', None, None], [None, None, 'が', None], ['山', 'やま', None, None], [None, None, 'のように', None], ['床', 'ゆか', None, None], [None, None, 'に', None], ['積', 'つ', None, None], [None, None, 'まれ', None], [None, None, 'ていた', None], [None, None, '。', None]]
[[None, None, 'なん', True], ['本', 'ぼん', None, True], [None, None, 'か', True], [None, None, 'の', None], ['高級', 'こうきゅう', None, None], [None, None, 'な', None], ['木', 'き', None, None], [None, None, 'の', None], ['幹', 'みき', None, None], [None, None, 'を', None], ['製材所', 'せいざいしょ', None, None], [None, None, 'に', None], ['届', 'とど', None, None], [None, None, 'けた。', None]]

 23%|██▎       | 214/938 [02:09<07:20,  1.64it/s]

[['道', 'みち', None, None], [None, None, 'の', None], ['真', 'ま', None, True], [None, None, 'ん', True], ['中', 'なか', None, True], [None, None, 'に', None], ['鹿', 'しか', None, None], [None, None, 'がいた。', None]]
[['真', 'ま', None, True], [None, None, 'ん', True], ['丸', 'まる', None, True], [None, None, 'の', None], ['円', 'えん', None, None], [None, None, 'を', None], ['描', 'か', None, None], [None, None, 'ける', None], ['人', 'ひと', None, None], [None, None, 'がいます', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'この', None], ['道路', 'どうろ', None, None], [None, None, 'を', None], ['真', 'ま', None, True], [None, None, 'っ', True], ['直', 'す', None, True], [None, None, 'ぐ', True], ['行', 'い', None, None], [None, None, 'っ', None], [None, None, 'てください', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['竹', 'たけ', None, None], [None, None, 'を', None], ['刀', 'かたな', None, None], [None, None, 'で', None], ['真', 'ま', None, True], [None, None, 'っ', True], ['二', 'ぷた', None, True], [None, None, 'つ', True], [None, None, 'に', None], ['切', 'き', None, None], [None, None, 'った', None], [None, None, '。', None]]
[['急', 'きゅう', None, None], [None, None, 'に', None], ['立', 'た', None, None], [None, None, 'った', None], [None, None, 'から', None], [None, None, '、', None], ['目', 'め', None, None], [None, None, 'の', None], ['前', 'まえ', None, None], [None, None, ' が', None], ['真', 'ま', None, True], [None, None, 'っ', True], ['暗', 'くら', None, True], [None, None, 'になっ', None], [None, None, 'てしま', None], [None, None, 'った。', None]]

 23%|██▎       | 215/938 [02:10<07:08,  1.69it/s]

[['彼女', 'かのじょ', None, None], [None, None, 'に', None], [None, None, 'は', None], [None, None, 'まだ', None], ['１回', 'いっかい', None, None], [None, None, 'しか', True], ['会', 'あ', None, True], [None, None, 'っていない', True], [None, None, '。', None]]
[['計画書', 'けいかくしょ', None, None], [None, None, 'は', None], ['１枚', 'いちまい', None, None], [None, None, 'しか', True], ['提出', 'ていしゅつ', None, True], ['出来', 'でき', None, True], [None, None, 'ない', True], [None, None, '。', None]]
[['髪', 'かみ', None, None], [None, None, 'の', None], ['毛', 'け', None, None], [None, None, 'が', None], ['３本', 'さんぼん', None, None], [None, None, 'しか', True], ['生', 'は', None, True], [None, None, 'えていない', True], [None, None, '。', None]]
[['一', 'いっ', None, None], ['ヶ月', 'かげつ', None, None], [None, None, 'しか', True], ['期間', 'きかん', None, True], [None, None, 'がない', True], [None, None, 'のに', None], [None, None, '、あなた', None], [None, None, 'は', None], ['変', 'か', None, None], [None, None, 'われる', None], [None, None, 'の？', None]]
[['彼', 'かれ', None, None], [None, None, 'に', None], [None, None, 'は', None], ['１度', 'いちど', None, None], [None, None, 'しか', True], ['勝', 'か', None, True], [None, None, 'っていない', True], [None, None, '。', None]]

 23%|██▎       | 216/938 [02:10<07:05,  1.70it/s]

[[None, None, 'ホンダ', None], [None, None, 'は', None], ['車', 'くるま', None, None], [None, None, 'の', None], [None, None, 'メーカー', None], [None, None, 'の', True], ['一', 'ひと', None, True], [None, None, 'つ', True], [None, None, 'だ', None], [None, None, '。', None]]
[[None, None, 'アイフォン', None], [None, None, 'は', None], [None, None, 'スマートフォン', None], [None, None, 'の', True], ['一', 'ひと', None, True], [None, None, 'つ', True], [None, None, 'だ', None], [None, None, '。', None]]
[[None, None, 'マクドナルド', None], [None, None, 'は', None], [None, None, 'ファストフード', None], [None, None, 'の', True], ['一', 'ひと', None, True], [None, None, 'つ', True], [None, None, 'だ', None], [None, None, '。', None]]
[[None, None, 'コカコーラ', None], [None, None, 'は', None], [None, None, 'コーラ', None], [None, None, 'の', True], ['一', 'ひと', None, True], [None, None, 'つ', True], [None, None, 'だ', None], [None, None, '。', None]]
[[None, None, 'キリスト', None], ['教', 'きょう', None, None], [None, None, 'は', None], ['宗教', 'しゅうきょう', None, None], [None, None, 'の', True], ['一', 'ひと', None, True], [None, None, 'つ', True], [None, None, 'だ', None], [None, None, '。', None]]

 23%|██▎       | 217/938 [02:11<07:01,  1.71it/s]

[['本当', 'ほんとう', None, None], [None, None, 'に', None], ['書', 'か', None, None], [None, None, 'け', None], [None, None, 'ない', None], ['漢字', 'かんじ', None, None], [None, None, 'はない', True], [None, None, 'の？', None]]
[['夢', 'ゆめ', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'ない', None], ['人', 'ひと', None, None], [None, None, 'はいない', True], [None, None, 'だろう', None], [None, None, '。', None]]
[['紙', 'かみ', None, None], [None, None, 'を', None], ['使', 'つか', None, True], [None, None, 'わない', True], ['会社', 'かいしゃ', None, None], [None, None, 'は', None], ['一', 'ひと', None, None], [None, None, 'つ', None], [None, None, 'も', None], [None, None, 'ありません', None], [None, None, '。', None]]
[[None, None, 'あそこ', None], [None, None, 'の', None], [None, None, 'カフェ', None], [None, None, 'で', None], ['美味', 'おい', None, None], [None, None, 'し', None], [None, None, 'く', None], [None, None, 'ない', None], [None, None, 'コーヒー', None], [None, None, 'は', None], ['絶対', 'ぜったい', None, None], [None, None, 'ない', True], [None, None, '。', None]]
[['勉強', 'べんきょう', None, None], [None, None, 'し', None], [None, None, 'てい', None], [None, None, 'ない', None], ['文法', 'ぶんぽう', None, None], [None, None, 'はなかった', True], [None, None, 'から', None], [None, None, '、テストに', None], [None, None, 'は', None], ['合格', 'ごうかく', None, None], [None, None, 'しました。', None]]

 23%|██▎       | 218/938 [02:12<06:56,  1.73it/s]

[[None, None, 'この', None], ['景色', 'けしき', None, None], [None, None, 'は', None], ['少', 'すこ', None, True], [None, None, 'しも', True], ['綺麗', 'きれい', None, None], [None, None, 'ではない', None], [None, None, '。', None]]
[[None, None, 'あの', None], ['店', 'みせ', None, None], [None, None, 'の', None], [None, None, 'ケーキ', None], [None, None, 'は', None], ['少', 'すこ', None, True], [None, None, 'しも', True], ['美味', 'おい', None, None], [None, None, 'し', None], [None, None, 'くない', None], [None, None, '。', None]]
[['少', 'すこ', None, True], [None, None, 'しも', True], ['暑', 'あつ', None, None], [None, None, 'く', None], [None, None, 'ない', None], [None, None, 'のに', None], [None, None, '、', None], ['汗', 'あせ', None, None], [None, None, 'を', None], [None, None, 'かい', None], [None, None, 'ている', None], [None, None, '。', None]]
[[None, None, 'ガソリン', None], [None, None, 'の', None], ['値段', 'ねだん', None, None], [None, None, 'が', None], ['少', 'すこ', None, True], [None, None, 'しも', True], ['下', 'さ', None, None], [None, None, 'がら', None], [None, None, 'ない', None], [None, None, 'ね', None], [None, None, '。', None]]
[['今', 'いま', None, None], [None, None, 'の', None], ['話', 'はなし', None, None], [None, None, 'が', None], ['少', 'すこ', None, True], [None, None, 'しも', True], ['理解', 'りかい', None, None], ['出来', 'でき', None, None], [None, None, 'なかった', None], [None, None, '。', None]]

 23%|██▎       | 219/938 [02:12<06:49,  1.76it/s]

[[None, None, 'アニメ', None], [None, None, 'と', None], ['漫画', 'まんが', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'な', None], ['人', 'ひと', None, None], [None, None, 'は', None], ['少', 'すく', None, True], [None, None, 'なくない', True], [None, None, 'です', None], [None, None, 'よ', None], [None, None, '。', None]]
[[None, None, 'ハセガワ', None], [None, None, '：「', None], ['僕', 'ぼく', None, None], [None, None, 'は', None], ['友達', 'ともだち', None, None], [None, None, 'が', None], ['少', 'すく', None, True], [None, None, 'なくない', True], [None, None, 'よ', None], [None, None, '。」', None]]
[['朝', 'あさ', None, None], [None, None, 'ごはん', None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べない', None], ['人', 'ひと', None, None], [None, None, 'も', None], ['少', 'すく', None, True], [None, None, 'なくない', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'そう', None], ['思', 'おも', None, None], [None, None, 'っ', None], [None, None, 'ている', None], ['人', 'ひと', None, None], [None, None, 'も', None], ['少', 'すく', None, True], [None, None, 'なくない', True], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'の', None], ['欲', 'ほ', None, None], [None, None, 'しがっ', None], [None, None, 'ている', None], [None, None, 'もの', None], [None, None, 'が', None], ['少', 'すく', None, True], [None, None, 'なくない', True], [None, None, 'んだ', None], [None, None, '。', None]]

 23%|██▎       | 220/938 [02:13<06:47,  1.76it/s]

[['危険', 'きけん', None, None], [None, None, 'な', True], ['場合', 'ばあい', None, True], [None, None, 'は', True], [None, None, 'ここ', None], [None, None, 'に', None], ['電話', 'でんわ', None, None], [None, None, 'を', None], [None, None, 'し', None], [None, None, 'てください', None], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['犬', 'いぬ', None, None], [None, None, 'の', True], ['場合', 'ばあい', None, True], [None, None, 'は', True], ['家族', 'かぞく', None, None], [None, None, 'と', None], ['一緒', 'いっしょ', None, None], [None, None, 'です', None], [None, None, '。', None]]
[['遊', 'あそ', None, None], [None, None, 'んでいる', None], ['場合', 'ばあい', None, True], [None, None, 'は', None], [None, None, '、', None], ['危', 'あぶ', None, None], [None, None, 'な', None], [None, None, 'い', None], [None, None, 'こと', None], [None, None, 'を', None], [None, None, 'し', None], [None, None, 'ないで', None], [None, None, '。', None]]
[[None, None, 'この', None], ['商品', 'しょうひん', None, None], [None, None, 'が', None], ['売', 'う', None, None], [None, None, 'り', None], ['切', 'き', None, None], [None, None, 'れ', None], [None, None, 'の', True], ['場合', 'ばあい', None, True], [None, None, 'は', True], ['買', 'か', None, None], [None, None, 'え', None], [None, None, 'ない', None], [None, None, 'よ', None], [None, None, '。', None]]
[['山', 'やま', None, None], [None, None, 'が', None], ['崩', 'くず', None, None], [None, None, 'れ', None], [None, None, 'ている', None], ['場合', 'ばあい', None, True], [None, None, 'は', True], ['運転', 'うんてん', None, None], [None, None, 'を', None], [None, None, 'し', None], [None, None, 'ないでください', None], [None, None, '。', None]]

 24%|██▎       | 221/938 [02:13<06:46,  1.77it/s]

[[None, None, '「', None], ['頼', 'たの', None, None], [None, None, 'む', None], [None, None, 'よ', None], [None, None, '。', None], ['落', 'お', None, True], [None, None, 'ち', True], ['着', 'つ', None, True], [None, None, 'いて', True], [None, None, '。」', None]]
[[None, None, '「こしょう', None], [None, None, 'を', None], ['取', 'と', None, True], [None, None, 'って', True], [None, None, '。」', None]]
[[None, None, '「', None], ['誰', 'だれ', None, None], [None, None, 'か', None], ['助', 'たす', None, True], [None, None, 'けて', True], [None, None, '！」', None]]
[['母親', 'ははおや', None, None], [None, None, '：「', None], ['部屋', 'へや', None, None], [None, None, 'を', None], ['片付', 'かたづ', None, True], [None, None, 'けて', True], [None, None, 'ね', None], [None, None, '。」', None], ['子供', 'こども', None, None], [None, None, '：「うん。」', None]]
[[None, None, '「', None], [None, None, 'この', None], [None, None, 'ポスター', None], [None, None, 'を', None], ['貼', 'は', None, True], [None, None, 'っておいて', True], [None, None, '。」', None]]

 24%|██▎       | 222/938 [02:14<06:41,  1.78it/s]

[[None, None, 'ダイエット', None], [None, None, 'を', None], ['諦', 'あきら', None, True], [None, None, 'めなくてよかった', True], [None, None, '。', None]]
[[None, None, 'この', None], [None, None, 'レストランに', None], [None, None, 'また', None], ['来', 'き', None, True], [None, None, 'てよかった', True], [None, None, '。', None]]
[['勉強', 'べんきょう', None, None], [None, None, 'を', None], [None, None, 'してよかった', True], [None, None, 'です', None], [None, None, '。', None]]
[['今日', 'きょう', None, None], [None, None, 'は', None], [None, None, 'デザート', None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べなく', None], [None, None, 'てよかった', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'この', None], [None, None, 'バスに', None], ['間', 'ま', None, True], [None, None, 'に', True], ['合', 'あ', None, True], [None, None, 'ってよかった', True], [None, None, 'です', None], [None, None, '。', None]]

 24%|██▍       | 223/938 [02:14<06:47,  1.75it/s]

[[None, None, 'お', None], ['兄', 'にい', None, None], [None, None, 'ちゃん', None], [None, None, 'が', None], ['妹', 'いもうと', None, None], [None, None, 'を', None], ['泣', 'な', None, True], [None, None, 'かせた', True], [None, None, '。', None]]
[['学校', 'がっこう', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'き', None], [None, None, 'たくない', None], ['子', 'こ', None, None], [None, None, 'を', None], ['行', 'い', None, True], [None, None, 'かせる', True], [None, None, '。', None]]
[['友達', 'ともだち', None, None], [None, None, 'を', None], ['朝', 'あさ', None, None], ['４時', 'よじ', None, None], [None, None, 'に', None], ['起', 'お', None, None], [None, None, 'こして、', None], ['帰', 'かえ', None, True], [None, None, 'らせた', True], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], ['生徒', 'せいと', None, None], [None, None, 'に', None], ['勉強', 'べんきょう', None, None], [None, None, 'する', None], [None, None, 'こと', None], [None, None, 'を', None], ['楽', 'たの', None, True], [None, None, 'しませます', True], [None, None, '。', None]]
[['友達', 'ともだち', None, None], [None, None, 'を', None], ['無理', 'むり', None, None], [None, None, 'やりお', None], ['化', 'ば', None, None], [None, None, 'け', None], ['屋敷', 'やしき', None, None], [None, None, 'に', None], ['行', 'い', None, True], [None, None, 'かせた', True], [None, None, 'から、', None], ['怒', 'おこ', None, None], [None, None, 'られた。', None]]

 24%|██▍       | 224/938 [02:15<06:47,  1.75it/s]

[[None, None, 'この', None], [None, None, 'ワイン', None], [None, None, 'は', None], ['飲', 'の', None, None], [None, None, 'み', None], [None, None, 'やすい', None], [None, None, 'といってもいい', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], [None, None, 'とてもいい', None], ['人', 'ひと', None, None], [None, None, 'だといってもいい', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'あの', None], ['子', 'こ', None, None], [None, None, 'は', None], [None, None, '、', None], ['魚', 'さかな', None, None], [None, None, 'のように', None], ['泳', 'およ', None, None], [None, None, 'げる', None], [None, None, 'といってもいい', True], [None, None, 'です', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['全然', 'ぜんぜん', None, None], ['日本語', 'にほんご', None, None], [None, None, 'が', None], ['出来', 'でき', None, None], [None, None, 'ない', None], [None, None, 'といってもいい', True], [None, None, '。', None]]
[[None, None, 'あの', None], ['二人', 'ふたり', None, None], [None, None, 'が', None], ['付', 'つ', None, None], [None, None, 'き', None], ['合', 'あ', None, None], [None, None, 'っ', None], [None, None, 'ている', None], [None, None, 'といってもいい', True], [None, None, 'だろう', None], [None, None, '。', None]]

 24%|██▍       | 225/938 [02:16<06:46,  1.75it/s]

[['試合', 'しあい', None, None], [None, None, 'に', None], ['負', 'ま', None, True], [None, None, 'けても', True], [None, None, '、', None], ['諦', 'あきら', None, None], [None, None, 'め', None], [None, None, 'ません', None], [None, None, '。', None]]
[[None, None, 'トレーニング', None], [None, None, 'を', None], [None, None, 'しても', True], [None, None, '、', None], ['痩', 'や', None, None], [None, None, 'せ', None], [None, None, 'ない', None], [None, None, '。', None]]
[['靴下', 'くつした', None, None], [None, None, 'を', None], ['履', 'は', None, True], [None, None, 'いても', True], [None, None, '、', None], ['足', 'あし', None, None], [None, None, 'が', None], ['冷', 'つめ', None, None], [None, None, 'た', None], [None, None, 'い', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'たくさん', None], [None, None, 'サラダ', None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べても', True], [None, None, '、お', None], ['腹', 'なか', None, None], [None, None, 'いっぱいにならない', None], [None, None, 'んです', None], [None, None, 'よ', None], [None, None, '。', None]]
[['子供', 'こども', None, None], [None, None, 'に', None], ['何回', 'なんかい', None, None], [None, None, 'も', None], ['起', 'お', None, None], [None, None, 'きて', None], [None, None, 'と', None], ['言', 'い', None, True], [None, None, 'っても', True], [None, None, '、', None], ['起', 'お', None, None], [None, None, 'き', None], [None, None, 'なかった', None], [None, None, '。', None]]

 24%|██▍       | 226/938 [02:16<06:56,  1.71it/s]

[['傘', 'かさ', None, None], [None, None, 'を', None], ['忘', 'わす', None, True], [None, None, 'れてしまった', True], [None, None, '。', None]]
[['友達', 'ともだち', None, None], [None, None, 'は', None], ['私', 'わたし', None, None], [None, None, 'の', None], [None, None, 'ケーキ', None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べてしまった', True], [None, None, '。', None]]
[[None, None, 'お', None], ['皿', 'さら', None, None], [None, None, 'が', None], ['割', 'わ', None, True], [None, None, 'れてしまった', True], [None, None, '。', None]]
[['今', 'いま', None, None], ['出', 'で', None, None], [None, None, 'ないと', None], ['遅', 'おく', None, True], [None, None, 'れてしまう', True], [None, None, 'よ', None], [None, None, '。', None]]
[[None, None, 'ごめん！', None], ['卵', 'たまご', None, None], [None, None, 'を', None], ['全部', 'ぜんぶ', None, None], ['使', 'つか', None, True], [None, None, 'ってしまった', True], [None, None, '。', None]]

 24%|██▍       | 227/938 [02:17<06:44,  1.76it/s]

[['文字', 'もじ', None, None], [None, None, 'も', None], ['小', 'ちい', None, True], [None, None, 'さすぎて', True], ['読', 'よ', None, None], [None, None, 'めない', None], [None, None, 'よ', None], [None, None, '。', None]]
[['部屋', 'へや', None, None], [None, None, 'が', None], ['綺麗', 'きれい', None, True], [None, None, 'で', True], [None, None, 'のんびりでき', None], [None, None, 'ます', None], [None, None, '。', None]]
[[None, None, 'メアリー', None], [None, None, 'が', None], [None, None, 'アメリカに', None], ['帰', 'かえ', None, True], [None, None, 'って', True], ['悲', 'かな', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'おとなしさん', None], [None, None, 'は', None], ['病気', 'びょうき', None, None], [None, None, 'で', True], ['参加', 'さんか', None, None], [None, None, 'でき', None], [None, None, 'ません', None], [None, None, 'でした。', None]]
[[None, None, 'おっちゃん', None], [None, None, 'の', None], [None, None, 'コンサート', None], [None, None, 'は', None], ['雨', 'あめ', None, None], [None, None, 'で', True], ['中止', 'ちゅうし', None, None], [None, None, 'にな', None], [None, None, 'った。', None]]

 24%|██▍       | 228/938 [02:17<06:54,  1.71it/s]

[[None, None, 'お', None], ['腹', 'なか', None, None], [None, None, 'が', None], [None, None, 'いっぱいな', None], [None, None, 'のに', None], [None, None, '、ケーキ', None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べさせられた', True], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], ['兄', 'あに', None, None], [None, None, 'に', None], ['宿題', 'しゅくだい', None, None], [None, None, 'を', None], [None, None, 'させられた', True], [None, None, '。', None]]
[[None, None, 'どんな', None], [None, None, 'こと', None], [None, None, 'を', None], [None, None, 'させられた', True], [None, None, 'の？', None]]
[['嫌', 'いや', None, None], [None, None, 'な', None], [None, None, 'こと', None], [None, None, 'を', None], [None, None, 'させられた', True], [None, None, '。', None]]
[[None, None, 'あまり', None], ['見', 'み', None, None], [None, None, 'たくない', None], ['動画', 'どうが', None, None], [None, None, 'を', None], ['見', 'み', None, True], [None, None, 'させられた', True], [None, None, 'のです', None], [None, None, '。', None]]

 24%|██▍       | 229/938 [02:18<07:27,  1.58it/s]

[[None, None, 'フライパン', None], [None, None, 'を', None], ['使', 'つか', None, True], [None, None, 'って', True], [None, None, '、', None], ['料理', 'りょうり', None, None], [None, None, 'を', None], [None, None, 'します', None], [None, None, '。', None]]
[['歩', 'ある', None, True], [None, None, 'いて', True], ['帰', 'かえ', None, None], [None, None, 'る', None], [None, None, 'つもり', None], [None, None, 'だ', None], [None, None, 'よ', None], [None, None, '。', None]]
[[None, None, 'けいまくん', None], [None, None, 'は', None], ['自転車', 'じてんしゃ', None, None], [None, None, 'に', None], ['乗', 'の', None, True], [None, None, 'って', True], ['学校', 'がっこう', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'っています。', None]]
[['総理大臣', 'そうりだいじん', None, None], [None, None, 'は', None], ['新幹線', 'しんかんせん', None, None], [None, None, 'を', None], ['利用', 'りよう', None, None], [None, None, 'して', True], ['東京', 'とうきょう', None, None], [None, None, 'に', None], ['戻', 'もど', None, None], [None, None, 'りました。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], [None, None, 'あの', None], ['船', 'ふね', None, None], [None, None, 'に', None], ['乗', 'の', None, True], [None, None, 'って', True], [None, None, 'アメリカ', None], [None, None, 'に', None], ['来', 'き', None, None], [None, None, 'た。', None]]

 25%|██▍       | 230/938 [02:19<07:06,  1.66it/s]

[[None, None, 'この', None], [None, None, 'ドア', None], [None, None, 'は', None], ['開', 'あ', None, True], [None, None, 'けてある', True], [None, None, '。', None]]
[[None, None, 'テレビ', None], ['台', 'だい', None, None], [None, None, 'の', None], ['上', 'うえ', None, None], [None, None, 'に', None], ['置', 'お', None, True], [None, None, 'いてある', True], [None, None, 'よ', None], [None, None, '。', None]]
[['明日', 'あした', None, None], [None, None, 'の', None], ['準備', 'じゅんび', None, None], [None, None, 'してある', True], [None, None, 'んです', None], [None, None, 'か', None], [None, None, '。', None]]
[['明日', 'あした', None, None], [None, None, 'の', None], ['準備', 'じゅんび', None, None], [None, None, 'を', None], [None, None, 'してある', True], [None, None, 'ので', None], [None, None, '、', None], [None, None, 'もう', None], ['寝', 'ね', None, None], [None, None, 'ます', None], [None, None, '。', None]]
[['１０００', 'せん', None, None], ['年', 'ねん', None, None], ['前', 'まえ', None, None], [None, None, 'に', None], ['建', 'た', None, None], [None, None, 'てられたビル', None], [None, None, 'が', None], [None, None, 'まだ', None], ['残', 'のこ', None, True], [None, None, 'してある', True], [None, None, '。', None]]

 25%|██▍       | 231/938 [02:19<07:01,  1.68it/s]

[[None, None, 'ブラジル', None], [None, None, 'のように', True], ['負', 'ま', None, True], [None, None, 'けて', True], ['欲', 'ほ', None, True], [None, None, 'しくない', True], [None, None, '。', None]]
[[None, None, 'どの', None], [None, None, 'ように', True], ['書', 'か', None, True], [None, None, 'いて', True], ['欲', 'ほ', None, True], [None, None, 'しい', True], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'ウサイン・ボルト', None], [None, None, 'のように', True], ['走', 'はし', None, True], [None, None, 'って', True], ['欲', 'ほ', None, True], [None, None, 'しい', True], [None, None, '。', None]]
[['頭', 'あたま', None, None], [None, None, 'が', None], [None, None, 'よ', None], [None, None, 'くな', None], [None, None, 'る', None], [None, None, 'ように', True], ['勉強', 'べんきょう', None, True], [None, None, 'して', True], ['欲', 'ほ', None, True], [None, None, 'しい', True], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'たち', None], [None, None, 'の', None], ['子供', 'こども', None, None], [None, None, 'に', None], [None, None, 'は', None], ['君', 'きみ', None, None], [None, None, 'のようになって', True], ['欲', 'ほ', None, True], [None, None, 'しい', True], [None, None, '。', None]]

 25%|██▍       | 232/938 [02:20<06:55,  1.70it/s]

[['妻', 'つま', None, None], [None, None, 'が', None], ['寝', 'ね', None, True], [None, None, 'ている', True], ['間', 'あいだ', None, True], [None, None, 'に', True], [None, None, '、', None], ['私', 'わたし', None, None], [None, None, 'は', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'な', None], [None, None, 'ことができる', None], [None, None, '。', None]]
[[None, None, 'サッカー', None], [None, None, 'を', None], [None, None, 'している', True], ['間', 'あいだ', None, True], [None, None, 'に', True], ['電話', 'でんわ', None, None], [None, None, 'が', None], [None, None, 'かかってきました。', None]]
[['勉強', 'べんきょう', None, None], [None, None, 'を', None], [None, None, 'している', True], ['間', 'あいだ', None, True], [None, None, 'に', True], [None, None, 'お', None], ['腹', 'なか', None, None], [None, None, 'が', None], ['空', 'す', None, None], [None, None, 'い', None], [None, None, 'てきた', None], [None, None, '。', None]]
[['料理', 'りょうり', None, None], [None, None, 'を', None], [None, None, 'している', True], ['間', 'あいだ', None, True], [None, None, 'に', True], ['子', 'こ', None, None], [None, None, 'ども', None], ['達', 'たち', None, None], [None, None, 'が', None], ['帰', 'かえ', None, None], [None, None, 'って', None], ['来', 'き', None, None], [None, None, 'た。', None]]
[[None, None, 'パン', None], [None, None, 'を', None], ['焼', 'や', None, True], [None, None, 'いている', True], ['間', 'あいだ', None, True], [None, None, 'に', True], [None, None, 'お', None], ['皿', 'さら', None, None], [None, None, 'を', None], ['出', 'だ', None, None], [None, None, 'した', None], [None, None, '。', None]]

 25%|██▍       | 233/938 [02:20<06:51,  1.71it/s]

[['忙', 'いそが', None, None], [None, None, 'しい', None], [None, None, 'なら', None], [None, None, '、', None], ['行', 'い', None, True], [None, None, 'かなくてもいい', True], [None, None, 'です', None], [None, None, '。', None]]
[['掃除', 'そうじ', None, None], [None, None, 'を', None], [None, None, 'しなくてもいい', True], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'その', None], ['青', 'あお', None, None], [None, None, 'い', None], [None, None, 'セーター', None], [None, None, 'を', None], ['着', 'き', None, True], [None, None, 'なくてもいい', True], [None, None, 'です', None], [None, None, 'よ', None], [None, None, '。', None]]
[[None, None, 'そんなに', None], ['怒', 'おこ', None, True], [None, None, 'らなくてもいい', True], [None, None, '。', None]]
[[None, None, 'これ', None], ['以上', 'いじょう', None, None], ['飲', 'の', None, True], [None, None, 'まなくてもいい', True], [None, None, '。', None]]

 25%|██▍       | 234/938 [02:21<06:40,  1.76it/s]

[[None, None, 'イルカ', None], [None, None, 'と', None], ['泳', 'およ', None, True], [None, None, 'いでみたい', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'まず', None], [None, None, '、', None], ['食', 'た', None, True], [None, None, 'べてみて', True], [None, None, 'ください。', None]]
[['柔道', 'じゅうどう', None, None], [None, None, 'を', None], [None, None, 'してみたい', True], [None, None, 'です', None], [None, None, '。', None]]
[['図書館', 'としょかん', None, None], [None, None, 'で', None], [None, None, '、', None], ['調', 'しら', None, True], [None, None, 'べてみる', True], [None, None, 'つもり', None], [None, None, 'です', None], [None, None, '。', None]]
[['先週末', 'せんしゅうまつ', None, None], [None, None, '、スキー', None], [None, None, 'を', None], [None, None, 'してみた', True], [None, None, '。', None]]

 25%|██▌       | 235/938 [02:21<06:33,  1.78it/s]

[[None, None, 'あなた', None], [None, None, 'の', None], [None, None, 'ケーキ', None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べてすみません', True], [None, None, '。', None]]
[['遅', 'おそ', None, None], [None, None, 'く', None], [None, None, 'なってすみません', True], [None, None, '。', None]]
[['約束', 'やくそく', None, None], [None, None, 'を', None], ['破', 'やぶ', None, True], [None, None, 'ってすみません', True], [None, None, '。', None]]
[['怒', 'おこ', None, True], [None, None, 'ってすみません', True], [None, None, '。', None], ['怒', 'おこ', None, None], [None, None, 'り', None], [None, None, 'たくな', None], [None, None, 'かった。', None]]
[['喋', 'しゃべ', None, True], [None, None, 'りすぎてすみません', True], [None, None, '。', None]]

 25%|██▌       | 236/938 [02:22<06:34,  1.78it/s]

[['母', 'はは', None, None], [None, None, 'に', None], ['花', 'はな', None, None], [None, None, 'を', None], ['買', 'か', None, True], [None, None, 'ってあげた', True], [None, None, '。', None]]
[[None, None, 'あそこ', None], [None, None, 'の', None], [None, None, 'おばあさん', None], [None, None, 'を', None], ['手伝', 'てつだ', None, True], [None, None, 'ってあげましょう', True], [None, None, 'か。', None]]
[[None, None, 'この', None], [None, None, 'プレゼント', None], [None, None, 'を', None], [None, None, 'お', None], ['父', 'とう', None, None], [None, None, 'さん', None], [None, None, 'に', None], ['渡', 'わた', None, True], [None, None, 'してあげてください', True], [None, None, '。', None]]
[[None, None, 'ユカ', None], [None, None, 'に', None], ['消', 'け', None, None], [None, None, 'しゴム', None], [None, None, 'を', None], ['貸', 'か', None, True], [None, None, 'してあげてください', True], [None, None, '。', None]]
[['寂', 'さび', None, None], [None, None, 'し', None], [None, None, 'そうに', None], [None, None, 'し', None], [None, None, 'ている', None], [None, None, 'から', None], [None, None, '、ハグ', None], [None, None, 'してあげましょう', True], [None, None, '。', None]]

 25%|██▌       | 237/938 [02:23<06:36,  1.77it/s]

[[None, None, 'あの', None], [None, None, 'グラス', None], [None, None, 'を', None], [None, None, 'ここ', None], [None, None, 'に', None], ['持', 'も', None, True], [None, None, 'ってきてくれる', True], [None, None, '？', None]]
[[None, None, 'この', None], ['漢字', 'かんじ', None, None], [None, None, 'の', None], ['意味', 'いみ', None, None], [None, None, 'を', None], ['教', 'おし', None, True], [None, None, 'えてくれますか', True], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'を', None], ['愛', 'あい', None, True], [None, None, 'してくれますか', True], [None, None, '。', None]]
[[None, None, 'ママ', None], [None, None, 'が', None], ['書', 'か', None, None], [None, None, 'き', None], [None, None, 'やすい', None], [None, None, 'ペン', None], [None, None, 'を', None], ['買', 'か', None, True], [None, None, 'ってくれた', True], [None, None, '。', None]]
[['喋', 'しゃべ', None, None], [None, None, 'ら', None], [None, None, 'ないで', None], ['黙', 'だま', None, True], [None, None, 'って', True], ['行', 'い', None, True], [None, None, 'ってくれますか', True], [None, None, '。', None]]

 25%|██▌       | 238/938 [02:23<06:42,  1.74it/s]

[['私', 'わたし', None, None], [None, None, 'は', None], ['母', 'はは', None, None], [None, None, 'に', None], ['宿題', 'しゅくだい', None, None], [None, None, 'を', None], [None, None, 'してもらった', True], [None, None, '。', None]]
[[None, None, 'クリスマスに', None], ['犬', 'いぬ', None, None], [None, None, 'を', None], ['買', 'か', None, True], [None, None, 'ってもらう', True], [None, None, 'かもしれない', None], [None, None, '。', None]]
[[None, None, '(', None], ['誰', 'だれ', None, None], [None, None, 'か', None], [None, None, 'に', None], [None, None, ')', None], [None, None, 'この', None], ['仕事', 'しごと', None, None], [None, None, 'を', None], ['手伝', 'てつだ', None, True], [None, None, 'ってもらう', True], [None, None, '。', None]]
[[None, None, 'ユカ', None], [None, None, 'は', None], ['誰', 'だれ', None, None], [None, None, 'か', None], [None, None, 'に', None], ['手伝', 'てつだ', None, True], [None, None, 'ってもらった', True], [None, None, 'かもしれない', None], [None, None, '。', None]]
[[None, None, 'まず', None], ['掃除', 'そうじ', None, None], [None, None, 'を', None], [None, None, 'してもらう', True], [None, None, 'と', None], ['思', 'おも', None, None], [None, None, 'う', None], [None, None, '。', None]]

 25%|██▌       | 239/938 [02:24<06:36,  1.76it/s]

[['勉強', 'べんきょう', None, None], [None, None, 'しなさい', True], [None, None, '。', None]]
[['早', 'はや', None, None], [None, None, 'く', None], ['帰', 'かえ', None, True], [None, None, 'りなさい', True], [None, None, '。', None]]
[['野菜', 'やさい', None, None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べなさい', True], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'をパパ', None], [None, None, 'に', None], ['渡', 'わた', None, True], [None, None, 'しなさい', True], [None, None, '。', None]]
[['注意', 'ちゅうい', None, None], [None, None, 'しなさい', True], [None, None, '。', None]]

 26%|██▌       | 240/938 [02:24<06:31,  1.78it/s]

[['昨日', 'きのう', None, None], [None, None, 'は', None], ['曇', 'くも', None, True], [None, None, 'っていて', True], ['寒', 'さむ', None, None], [None, None, 'かった', None], [None, None, '。', None]]
[[None, None, 'チトゲさん', None], [None, None, 'は', None], ['歌', 'うた', None, True], [None, None, 'って', True], [None, None, 'オノデラさん', None], [None, None, 'は', None], ['踊', 'おど', None, None], [None, None, 'っ', None], [None, None, 'ている', None], [None, None, '。', None]]
[['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, True], [None, None, 'って', True], ['雷', 'かみなり', None, None], [None, None, 'が', None], ['鳴', 'な', None, None], [None, None, 'る', None], [None, None, '。', None]]
[[None, None, 'おばあさん', None], [None, None, 'は', None], [None, None, 'いつもラジオ', None], [None, None, 'を', None], ['聴', 'き', None, True], [None, None, 'いて', True], [None, None, 'おじいさん', None], [None, None, 'は', None], [None, None, 'いつもテレビ', None], [None, None, 'を', None], ['観', 'み', None, None], [None, None, 'る', None], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], [None, None, 'ピアノ', None], [None, None, 'を', None], ['弾', 'ひ', None, True], [None, None, 'けて', True], [None, None, 'ドラム', None], [None, None, 'も', None], ['上手', 'じょうず', None, None], [None, None, 'に', None], ['叩', 'たた', None, None], [None, None, 'ける', None], [None, None, '。', None]]

 26%|██▌       | 241/938 [02:25<06:27,  1.80it/s]

[[None, None, 'あそこ', None], [None, None, 'の', None], ['公園', 'こうえん', None, None], [None, None, 'は', None], ['危', 'あぶ', None, None], [None, None, 'な', None], [None, None, 'い', None], [None, None, 'ので', None], [None, None, '、', None], ['遊', 'あそ', None, True], [None, None, 'ばないで', True], [None, None, '。', None]]
[['冷蔵庫', 'れいぞうこ', None, None], [None, None, 'にあるケーキ', None], [None, None, 'は', None], [None, None, 'まだ', None], ['食', 'た', None, True], [None, None, 'べないで', True], [None, None, 'ね', None], [None, None, '。', None]]
[['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'てから', None], [None, None, 'ジェットコースターに', None], ['乗', 'の', None, True], [None, None, 'らないで', True], [None, None, '。', None]]
[[None, None, '「バカに', None], [None, None, 'しないで', True], [None, None, 'よ', None], [None, None, '！はんだくん。」', None]]
[[None, None, 'ここ', None], [None, None, 'は', None], ['病院', 'びょういん', None, None], [None, None, 'な', None], [None, None, 'ので', None], [None, None, '、', None], ['走', 'はし', None, None], [None, None, 'っ', None], [None, None, 'たり', None], [None, None, '、', None], ['騒', 'さわ', None, None], [None, None, 'い', None], [None, None, 'だり', None], [None, None, 'しないで', True], [None, None, '。', None]]

 26%|██▌       | 242/938 [02:25<06:34,  1.77it/s]

[['手伝', 'てつだ', None, True], [None, None, 'ってくれてありがとうございました', True], [None, None, '。', None]]
[[None, None, 'いつも', None], ['一緒', 'いっしょ', None, None], [None, None, 'に', None], [None, None, 'いてくれてありがとう', True], [None, None, '。', None]]
[['駅', 'えき', None, None], [None, None, 'まで', None], [None, None, 'おくってくれてありがとうございます', True], [None, None, '。', None]]
[['晩御飯', 'ばんごはん', None, None], [None, None, 'を', None], ['作', 'つく', None, True], [None, None, 'ってくれてありがとう', True], [None, None, '！', None]]
[['遅', 'おそ', None, None], [None, None, 'くなって', None], [None, None, 'ごめん！', None], ['待', 'ま', None, True], [None, None, 'っていてくれてありがとう', True], [None, None, '。', None]]

 26%|██▌       | 243/938 [02:26<06:36,  1.75it/s]

[[None, None, 'スマホ', None], [None, None, 'を', None], ['使', 'つか', None, True], [None, None, 'わせてくれないか', True], [None, None, '？', None]]
[[None, None, 'お', None], ['茶', 'ちゃ', None, None], [None, None, 'を', None], ['入', 'い', None, True], [None, None, 'れてくれない', True], [None, None, '？', None]]
[[None, None, 'うち', None], [None, None, 'でも', None], ['働', 'はたら', None, True], [None, None, 'いてくれない', True], [None, None, '？', None]]
[[None, None, 'こっちに', None], ['醤油', 'しょうゆ', None, None], [None, None, 'を', None], ['取', 'と', None, True], [None, None, 'ってもらえない', True], [None, None, '？', None]]
[['米', 'こめ', None, None], [None, None, 'を', None], ['炊', 'た', None, True], [None, None, 'いておいてくれない', True], [None, None, '？', None]]

 26%|██▌       | 244/938 [02:27<06:40,  1.73it/s]

[['彼', 'かれ', None, None], [None, None, 'の', None], ['都合', 'つごう', None, None], [None, None, 'が', None], ['悪', 'わる', None, None], [None, None, 'い', None], [None, None, 'だろうか', True], [None, None, '。', None]]
[[None, None, 'もう', None], [None, None, 'すぐ', None], ['時間', 'じかん', None, None], [None, None, 'だろうか', True], [None, None, '。', None]]
[['練習', 'れんしゅう', None, None], [None, None, 'し', None], [None, None, 'たら', None], [None, None, '、うま', None], [None, None, 'くな', None], [None, None, 'る', None], [None, None, 'だろうか', True], [None, None, '。', None]]
[['犯人', 'はんにん', None, None], [None, None, 'が', None], ['見', 'み', None, None], [None, None, 'つかる', None], [None, None, 'だろうか', True], [None, None, '。', None]]
[[None, None, 'この', None], ['小屋', 'こや', None, None], [None, None, 'に', None], ['虫', 'むし', None, None], [None, None, 'が', None], ['居', 'い', None, None], [None, None, 'る', None], [None, None, 'のだろうか', True], [None, None, '。', None]]

 26%|██▌       | 245/938 [02:27<06:48,  1.70it/s]

[['先生', 'せんせい', None, None], [None, None, 'は', None], [None, None, 'お', True], ['帰', 'かえ', None, True], [None, None, 'りになりました', True], [None, None, '。', None]]
[[None, None, 'ハリーポッター', None], [None, None, 'を', None], [None, None, 'お', True], ['読', 'よ', None, True], [None, None, 'みになりました', True], [None, None, 'か', None], [None, None, '。', None]]
[['父上', 'ちちうえ', None, None], [None, None, 'は', None], [None, None, 'もう', None], [None, None, 'お', True], ['帰', 'かえ', None, True], [None, None, 'りになった', True], [None, None, 'んです', None], [None, None, 'ね', None], [None, None, '。', None]]
[['歯医者', 'はいしゃ', None, None], [None, None, 'が', None], [None, None, 'お', True], ['見', 'み', None, True], [None, None, 'えになる', True], [None, None, 'のは', None], ['３', 'さん', None, None], ['時', 'じ', None, None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'お', None], ['父', 'とう', None, None], [None, None, 'さん', None], [None, None, 'は', None], ['何時', 'なんじ', None, None], ['頃', 'ごろ', None, None], [None, None, 'お', True], ['帰', 'かえ', None, True], [None, None, 'りになります', True], [None, None, '？', None]]

 26%|██▌       | 246/938 [02:28<06:42,  1.72it/s]

[[None, None, 'お', None], ['飲', 'の', None, None], [None, None, 'み', None], ['物', 'もの', None, None], [None, None, 'は', None], [None, None, 'どう', None], [None, None, 'なさいます', True], [None, None, 'か', None], [None, None, '。', None]]
[['今朝', 'けさ', None, None], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'は', None], ['家', 'いえ', None, None], [None, None, 'を', None], ['留守', 'るす', None, None], [None, None, 'に', None], [None, None, 'なさいました', True], [None, None, '。', None]]
[['子供', 'こども', None, None], [None, None, 'の', None], [None, None, 'ころ', None], [None, None, 'スポーツ', None], [None, None, 'を', None], [None, None, 'なさっていた', True], [None, None, 'んです', None], [None, None, 'ね', None], [None, None, '。', None]]
[['今', 'いま', None, None], ['何', 'なに', None, None], [None, None, 'を', None], ['勉強', 'べんきょう', None, None], [None, None, 'なさっています', True], [None, None, 'か', None], [None, None, '。', None]]
[['何', 'なに', None, None], [None, None, 'を', None], [None, None, 'なさろう', True], [None, None, 'とする', None], [None, None, 'のです', None], [None, None, 'か', None], [None, None, '。', None]]

 26%|██▋       | 247/938 [02:28<06:39,  1.73it/s]

[['少', 'すこ', None, None], [None, None, 'し', None], [None, None, 'お', True], ['待', 'ま', None, True], [None, None, 'ちください', True], [None, None, '。', None]]
[[None, None, 'どうぞ', None], [None, None, 'お', True], ['召', 'め', None, True], [None, None, 'し', True], ['上', 'あ', None, True], [None, None, 'がりください', True], [None, None, '。', None]]
[[None, None, 'しばらく', None], [None, None, 'お', True], ['休', 'やす', None, True], [None, None, 'みください', True], [None, None, '。', None]]
[[None, None, 'どうぞ、', None], [None, None, 'お', True], ['掛', 'か', None, True], [None, None, 'けください', True], [None, None, '。', None]]
[['明日', 'あした', None, None], [None, None, 'までに', None], [None, None, 'お', True], ['支払', 'しはら', None, True], [None, None, 'いください', True], [None, None, '。', None]]

 26%|██▋       | 248/938 [02:29<06:37,  1.73it/s]

[['分', 'わ', None, None], [None, None, 'からない', None], ['人', 'ひと', None, None], [None, None, 'は', None], [None, None, 'いらっしゃいます', True], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'お', None], ['客', 'きゃく', None, None], [None, None, 'さん', None], [None, None, 'が', None], [None, None, 'いらっしゃいました', True], [None, None, '。', None]]
[[None, None, 'いらっしゃい', True], [None, None, '(ませ)！', None]]
[['先', 'さき', None, None], [None, None, 'に', None], [None, None, 'いらっしゃった', True], [None, None, 'んですが', None], [None, None, '。', None]]
[['鈴木', 'すずき', None, None], ['様', 'さま', None, None], [None, None, 'は', None], [None, None, 'もう', None], [None, None, 'いらっしゃらない', True], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]

 27%|██▋       | 249/938 [02:29<06:40,  1.72it/s]

[[None, None, 'おはよう', None], ['御座', 'ござ', None, True], [None, None, 'います', True], [None, None, '。', None]]
[[None, None, 'お', None], ['水', 'みず', None, None], [None, None, 'が', None], ['御座', 'ござ', None, True], [None, None, 'います', True], [None, None, '。', None]]
[['鶴', 'つる', None, None], [None, None, 'の', None], ['折', 'お', None, None], [None, None, 'り', None], ['紙', 'がみ', None, None], [None, None, 'が', None], ['御座', 'ござ', None, True], [None, None, 'います', True], [None, None, '。', None]]
[['駅', 'えき', None, None], [None, None, 'が', None], [None, None, 'あちらに', None], ['御座', 'ござ', None, True], [None, None, 'います', True], [None, None, '。', None]]
[['明', 'あ', None, None], [None, None, 'けましておめでとう', None], ['御座', 'ござ', None, True], [None, None, 'います', True], [None, None, '。', None]]

 27%|██▋       | 250/938 [02:30<06:35,  1.74it/s]

[[None, None, 'この', None], ['方', 'かた', None, None], [None, None, 'は', None], ['田中', 'たなか', None, None], [None, None, 'さん', None], [None, None, 'で', True], ['御座', 'ござ', None, True], [None, None, 'います', True], [None, None, '。', None]]
[[None, None, 'こちら', None], [None, None, 'が', None], ['先生', 'せんせい', None, None], [None, None, 'の', None], ['机', 'つくえ', None, None], [None, None, 'で', True], ['御座', 'ござ', None, True], [None, None, 'います', True], [None, None, '。', None]]
[[None, None, 'こちら', None], [None, None, 'は', None], ['図書館', 'としょかん', None, None], [None, None, 'で', True], ['御座', 'ござ', None, True], [None, None, 'います', True], [None, None, '。', None]]
[['英語', 'えいご', None, None], ['担当', 'たんとう', None, None], [None, None, 'の', None], ['浜田', 'はまだ', None, None], [None, None, 'で', True], ['御座', 'ござ', None, True], [None, None, 'います', True], [None, None, '。', None]]
[['本日', 'ほんじつ', None, None], [None, None, 'の', None], [None, None, 'スペシャル', None], [None, None, 'は', None], [None, None, 'ホットケーキ', None], [None, None, 'で', True], ['御座', 'ござ', None, True], [None, None, 'います', True], [None, None, '。', None]]

 27%|██▋       | 251/938 [02:31<06:48,  1.68it/s]

[[None, None, 'ドア', None], [None, None, 'を', None], [None, None, 'お', True], ['閉', 'し', None, True], [None, None, 'めします', True], [None, None, '。', None]]
[[None, None, 'お', True], ['任', 'まか', None, True], [None, None, 'せします', True], [None, None, '。', None]]
[['先生', 'せんせい', None, None], [None, None, 'の', None], ['分', 'ぶん', None, None], [None, None, 'も', None], [None, None, 'お', True], ['取', 'と', None, True], [None, None, 'りします', True], [None, None, '。', None]]
[[None, None, 'あなた', None], [None, None, 'の', None], ['分', 'ぶん', None, None], [None, None, 'も', None], [None, None, 'お', True], ['作', 'つく', None, True], [None, None, 'りします', True], [None, None, '。', None]]
[[None, None, 'これ', None], [None, None, 'を', None], ['彼', 'かれ', None, None], [None, None, 'に', None], [None, None, 'お', True], ['渡', 'わた', None, True], [None, None, 'しして', True], [None, None, 'ください', None], [None, None, '。', None]]

 27%|██▋       | 252/938 [02:31<07:21,  1.55it/s]

[[None, None, 'ご', None], ['案内', 'あんない', None, None], [None, None, 'いたします', True], [None, None, '。', None]]
[['拝借', 'はいしゃく', None, True], [None, None, 'しても', True], [None, None, 'よろしい', None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[['駅', 'えき', None, None], [None, None, 'の', None], ['前', 'まえ', None, None], [None, None, 'で', None], [None, None, 'お', True], ['待', 'ま', None, True], [None, None, 'ちいたします', True], [None, None, '。', None]]
[['品物', 'しなもの', None, None], [None, None, 'は', None], ['明日', 'あした', None, None], [None, None, 'お', True], ['送', 'おく', None, True], [None, None, 'りいたします', True], [None, None, '。', None]]
[[None, None, 'お', None], ['荷物', 'にもつ', None, None], [None, None, 'を', None], [None, None, 'お', True], ['持', 'も', None, True], [None, None, 'ちいたしましょうか', True], [None, None, '？', None]]

 27%|██▋       | 253/938 [02:32<07:04,  1.62it/s]

[['犬', 'いぬ', None, None], [None, None, 'を', None], ['散歩', 'さんぽ', None, None], [None, None, 'していただけませんか', True], [None, None, '。', None]]
[['夜', 'よる', None, None], ['９', 'く', None, None], ['時', 'じ', None, None], [None, None, 'までに', None], ['帰', 'かえ', None, True], [None, None, 'っていただけませんか', True], [None, None, '。', None]]
[[None, None, 'もし', None], [None, None, 'よかっ', None], [None, None, 'たら', None], [None, None, '、', None], ['明日', 'あした', None, None], [None, None, 'も', None], [None, None, 'していただけませんか', True], [None, None, '。', None]]
[['駅', 'えき', None, None], [None, None, 'まで', None], ['送', 'おく', None, True], [None, None, 'っていただけませんか', True], [None, None, '。', None]]
[['３', 'さん', None, None], ['時', 'じ', None, None], [None, None, 'ぐらい', None], [None, None, 'に', None], ['来', 'き', None, True], [None, None, 'ていただけませんか', True], [None, None, '。', None]]

 27%|██▋       | 254/938 [02:33<06:49,  1.67it/s]

[['勉強', 'べんきょう', None, None], [None, None, 'したら', True], [None, None, '、テスト', None], [None, None, 'は', None], ['簡単', 'かんたん', None, None], [None, None, 'になる', None], [None, None, '。', None]]
[[None, None, 'お', None], ['茶', 'ちゃ', None, None], [None, None, 'の', None], ['味', 'あじ', None, None], [None, None, 'が', None], ['薄', 'うす', None, True], [None, None, 'かったら', True], [None, None, '、', None], ['言', 'い', None, None], [None, None, 'っ', None], [None, None, 'てください', None], [None, None, '。', None]]
[[None, None, 'もし', None], ['食', 'た', None, None], [None, None, 'べに', None], ['行', 'い', None, True], [None, None, 'きたかったら', True], [None, None, '、', None], ['行', 'い', None, None], [None, None, 'こう', None], [None, None, '。', None]]
[['週末', 'しゅうまつ', None, None], [None, None, 'だったら', True], [None, None, '、', None], ['時間', 'じかん', None, None], [None, None, 'あり', None], [None, None, 'ます', None], [None, None, 'よ', None], [None, None, '。', None]]
[['辛', 'から', None, True], [None, None, 'かったら', True], [None, None, '、', None], ['牛乳', 'ぎゅうにゅう', None, None], [None, None, 'を', None], ['飲', 'の', None, None], [None, None, 'んで', None], [None, None, 'ください。', None]]

 27%|██▋       | 255/938 [02:33<06:42,  1.70it/s]

[['他', 'ほか', None, True], [None, None, 'は', True], [None, None, '？', None]]
[[None, None, 'いいえ、', None], ['他', 'ほか', None, True], [None, None, 'は', True], [None, None, 'い', None], [None, None, 'りません', None], [None, None, '。', None]]
[['他', 'ほか', None, True], [None, None, 'の', True], ['国', 'くに', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'っ', None], [None, None, 'たことがありますか', None], [None, None, '。', None]]
[['他', 'ほか', None, True], [None, None, 'の', True], ['方法', 'ほうほう', None, None], [None, None, 'がない', None], [None, None, 'かな', None], [None, None, '。', None]]
[[None, None, 'この', None], ['箸', 'はし', None, None], [None, None, 'の', None], ['他', 'ほか', None, True], [None, None, 'には', True], ['使', 'つか', None, None], [None, None, 'え', None], [None, None, 'ない', None], [None, None, 'んだ', None], [None, None, '。', None]]

 27%|██▋       | 256/938 [02:34<06:40,  1.70it/s]

[[None, None, 'テスト', None], [None, None, 'を', None], [None, None, 'する', None], ['時', 'とき', None, None], [None, None, 'は', None], [None, None, 'えんぴつ', None], [None, None, 'が', True], ['必要', 'ひつよう', None, True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'ケーキ', None], [None, None, 'を', None], ['作', 'つく', None, None], [None, None, 'る', None], [None, None, 'なら', None], [None, None, '、', None], ['砂糖', 'さとう', None, None], [None, None, 'が', True], ['必要', 'ひつよう', None, True], [None, None, 'です', None], [None, None, '。', None]]
[['田舎', 'いなか', None, None], [None, None, 'に', None], ['住', 'す', None, None], [None, None, 'んだら、', None], ['車', 'くるま', None, None], [None, None, 'が', True], ['必要', 'ひつよう', None, True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'スノーボード', None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'なら', None], [None, None, '、', None], ['手袋', 'てぶくろ', None, None], [None, None, 'が', True], ['必要', 'ひつよう', None, True], [None, None, 'です', None], [None, None, '。', None]]
[['何', 'なに', None, None], [None, None, 'が', True], ['必要', 'ひつよう', None, True], [None, None, 'かな', None], [None, None, '〜。', None]]

 27%|██▋       | 257/938 [02:34<06:30,  1.74it/s]

[[None, None, 'この', None], [None, None, 'ケーキ', None], [None, None, 'は', None], [None, None, 'そんなに', True], ['甘', 'あま', None, None], [None, None, 'い', None], [None, None, 'んです', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'そんなに', True], ['痛', 'いた', None, None], [None, None, 'い', None], [None, None, 'なら', None], [None, None, '、', None], ['病院', 'びょういん', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'っ', None], [None, None, 'たほうがいい', None], [None, None, 'んじゃないです', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'そんなに', True], ['頑張', 'がんば', None, None], [None, None, 'っ', None], [None, None, 'ても', None], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'みたいに', None], ['出来', 'でき', None, None], [None, None, 'ない', None], [None, None, '。', None]]
[[None, None, 'そんなに', True], ['日本', 'にほん', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'きたい', None], [None, None, 'なら', None], [None, None, '、', None], ['行', 'い', None, None], [None, None, 'って', None], ['来', 'き', None, None], [None, None, 'たら', None], [None, None, '？', None]]
[[None, None, 'そんなに', True], ['水泳', 'すいえい', None, None], [None, None, 'が', None], ['嫌', 'きら', None, None], [None, None, 'い', None], [None, None, 'なら', None], [None, None, '、', None], ['泳', 'およ', None, None], [None, None, 'がなくていいん', None], [None, None, 'じゃない', None], [None, None, '？', None]]

 28%|██▊       | 258/938 [02:35<06:27,  1.75it/s]

[['朝', 'あさ', None, None], [None, None, 'ご', None], ['飯', 'はん', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べる', None], ['必要', 'ひつよう', None, True], [None, None, 'がある', True], [None, None, '。', None]]
[[None, None, 'それ', None], [None, None, 'を', None], ['明日', 'あした', None, None], [None, None, 'までに', None], ['終', 'お', None, None], [None, None, 'える', None], ['必要', 'ひつよう', None, True], [None, None, 'がある', True], [None, None, '。', None]]
[[None, None, 'この', None], ['板', 'いた', None, None], [None, None, 'が', None], ['厚', 'あつ', None, None], [None, None, 'すぎ', None], [None, None, 'て、', None], ['切', 'き', None, None], [None, None, 'る', None], ['必要', 'ひつよう', None, True], [None, None, 'がある', True], [None, None, '。', None]]
[['痩', 'や', None, None], [None, None, 'せ', None], [None, None, 'たい', None], [None, None, 'なら', None], [None, None, '、', None], ['運動', 'うんどう', None, None], [None, None, 'する', None], ['必要', 'ひつよう', None, True], [None, None, 'がある', True], [None, None, '。', None]]
[[None, None, 'ホテルに', None], ['泊', 'と', None, None], [None, None, 'まるならカミソリ', None], [None, None, 'を', None], ['持', 'も', None, None], [None, None, 'って', None], ['行', 'い', None, None], [None, None, 'く', None], ['必要', 'ひつよう', None, True], [None, None, 'がある', True], [None, None, '。', None]]

 28%|██▊       | 259/938 [02:35<06:27,  1.75it/s]

[[None, None, 'たとえば', True], [None, None, '、「', None], ['英語', 'えいご', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。」', None], [None, None, 'と', None], ['聞', 'き', None, None], [None, None, 'い', None], [None, None, 'てみ', None], [None, None, 'たら', None], [None, None, '？', None]]
[[None, None, 'たとえば', True], [None, None, '、', None], ['翻訳者', 'ほんやくしゃ', None, None], [None, None, 'になっ', None], [None, None, 'たら', None], ['日本', 'にほん', None, None], [None, None, 'に', None], ['住', 'す', None, None], [None, None, 'む', None], [None, None, 'ことが', None], ['出来', 'でき', None, None], [None, None, 'る', None], [None, None, '。', None]]
[['漢字', 'かんじ', None, None], [None, None, 'を', None], ['覚', 'おぼ', None, None], [None, None, 'え', None], [None, None, 'る', None], [None, None, 'サイト', None], [None, None, 'が', None], [None, None, 'たくさん', None], [None, None, 'あり', None], [None, None, 'ます', None], [None, None, '。', None], [None, None, 'たとえば', True], [None, None, '、ワニカニ', None], [None, None, 'だ', None], [None, None, '。', None]]
[[None, None, 'たとえば', True], ['毎日', 'まいにち', None, None], ['日本語', 'にほんご', None, None], [None, None, 'を', None], ['話', 'はな', None, None], [None, None, 'す', None], [None, None, 'なら', None], [None, None, '、', None], ['日本語', 'にほんご', None, None], [None, None, 'の', None], [None, None, 'レベル', None], [None, None, 'が', None], ['上', 'あ', None, None], [None, None, 'がる。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], [None, None, '、', None], [None, None, 'たとえば', True], [None, None, 'あそこ', None], [None, None, 'にあるイタリアンレストラン', None], [None, None, 'のような', None], ['店', 'みせ', None, None], [None, None, 'を', None], ['作', 'つく', None, None], [None, None, 'り', None], [None, None, 'たい', None], [None, None, '。', None]]

 28%|██▊       | 260/938 [02:36<06:24,  1.77it/s]

[[None, None, 'あの', None], ['山', 'やま', None, None], [None, None, 'が', None], ['見', 'み', None, True], [None, None, 'られます', True], [None, None, 'か', None], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'の', None], ['話', 'はなし', None, None], [None, None, 'は', None], ['信', 'しん', None, True], [None, None, 'じられない', True], [None, None, '。', None]]
[['十', 'じゅっ', None, None], ['分', 'ぷん', None, None], ['待', 'ま', None, True], [None, None, 'てます', True], [None, None, 'か', None], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'な', None], ['映画', 'えいが', None, None], [None, None, 'が', None], ['見', 'み', None, True], [None, None, 'られ', True], [None, None, 'たら', None], [None, None, 'いい', None], [None, None, 'ね', None], [None, None, '。', None]]
[['見', 'み', None, True], [None, None, 'つけられなくて', True], [None, None, 'すみません', None], [None, None, 'でした。', None]]

 28%|██▊       | 261/938 [02:36<06:18,  1.79it/s]

[[None, None, '「', None], ['昨日', 'きのう', None, None], [None, None, 'の', None], ['告白', 'こくはく', None, None], [None, None, 'は', None], [None, None, 'どうな', None], [None, None, 'った', None], [None, None, 'の', None], [None, None, '？」', None], [None, None, '「こくはくした', None], [None, None, 'んだけど', True], [None, None, ' (ふられた)。」', None]]
[[None, None, 'これ', None], [None, None, 'ほし', None], [None, None, 'い', None], [None, None, 'んだけど', True], [None, None, ' (たかい)。', None]]
[[None, None, 'やせられ', None], [None, None, 'たら', None], [None, None, 'いい', None], [None, None, 'んだけど', True], [None, None, ' (', None], ['難', 'むずか', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'ね', None], [None, None, ')。', None]]
[['新', 'あたら', None, None], [None, None, 'し', None], [None, None, 'い', None], ['時計', 'とけい', None, None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'い', None], [None, None, 'たい', None], [None, None, 'のですが', True], [None, None, ' (', None], [None, None, 'どちら', None], [None, None, 'が', None], [None, None, 'いい', None], [None, None, 'でしょうか', None], [None, None, ')。', None]]
[['窓', 'まど', None, None], [None, None, 'が', None], ['開', 'あ', None, None], [None, None, 'い', None], [None, None, 'ている', None], [None, None, 'から', None], [None, None, 'ちょっと', None], ['寒', 'さむ', None, None], [None, None, 'い', None], [None, None, 'んですが', True], [None, None, ' (どうか', None], ['窓', 'まど', None, None], [None, None, 'を', None], ['閉', 'し', None, None], [None, None, 'め', None], [None, None, 'ていただけませんか', None], [None, None, '？)。', None]]

 28%|██▊       | 262/938 [02:37<06:21,  1.77it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], ['借', 'か', None, None], [None, None, 'り', None], [None, None, 'た', None], [None, None, 'ペン', None], [None, None, 'を', None], ['返', 'かえ', None, None], [None, None, 'す', None], ['筈', 'はず', None, True], [None, None, 'だ', None], [None, None, '。', None]]
[['夏', 'なつ', None, None], [None, None, 'だ', None], [None, None, 'から', None], [None, None, '、', None], ['暑', 'あつ', None, None], [None, None, 'い', None], ['筈', 'はず', None, True], [None, None, 'だ', None], [None, None, '。', None]]
[[None, None, 'ここ', None], [None, None, 'から', None], ['富士山', 'ふじさん', None, None], [None, None, 'が', None], ['見', 'み', None, None], [None, None, 'え', None], [None, None, 'る', None], ['筈', 'はず', None, True], [None, None, 'だ', True], [None, None, '。', None]]
[[None, None, 'この', None], ['港', 'みなと', None, None], [None, None, 'に', None], [None, None, 'は', None], ['船', 'ふね', None, None], [None, None, 'がある', None], ['筈', 'はず', None, True], [None, None, 'だ', True], [None, None, '。', None]]
[['脱出', 'だっしゅつ', None, None], [None, None, 'した', None], ['犯人', 'はんにん', None, None], [None, None, 'が', None], ['見', 'み', None, None], [None, None, 'つかる', None], ['筈', 'はず', None, True], [None, None, 'だ', True], [None, None, '。', None]]

 28%|██▊       | 263/938 [02:38<06:21,  1.77it/s]

[['旅行', 'りょこう', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'ける', None], [None, None, 'かどうか', True], [None, None, 'わから', None], [None, None, 'ない', None], [None, None, '。', None]]
[[None, None, 'サンタさん', None], [None, None, 'がいる', None], [None, None, 'かどうか', True], ['探', 'さが', None, None], [None, None, 'しています。', None]]
[[None, None, 'まだ', None], ['日本', 'にほん', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'ける', None], [None, None, 'かどうか', True], [None, None, '、', None], ['分', 'わ', None, None], [None, None, 'から', None], [None, None, 'ない', None], [None, None, '。', None]]
[[None, None, 'スピーチ', None], [None, None, 'が', None], [None, None, 'うまくでき', None], [None, None, 'る', None], [None, None, 'かどうか', True], ['心配', 'しんぱい', None, None], [None, None, 'している。', None]]
[['今', 'いま', None, None], [None, None, 'の', None], ['動物', 'どうぶつ', None, None], [None, None, 'は', None], ['犬', 'いぬ', None, None], [None, None, 'かどうか', True], ['分', 'わ', None, None], [None, None, 'から', None], [None, None, 'ない', None], [None, None, 'けど', None], [None, None, '、', None], ['怖', 'こわ', None, None], [None, None, 'かった', None], [None, None, '。', None]]

 28%|██▊       | 264/938 [02:38<06:18,  1.78it/s]

[['勉強', 'べんきょう', None, None], [None, None, 'を', None], [None, None, 'する', None], [None, None, 'と', True], [None, None, '、テスト', None], [None, None, 'は', None], ['簡単', 'かんたん', None, None], [None, None, 'にな', None], [None, None, 'る。', None]]
[[None, None, 'この', None], ['石', 'いし', None, None], [None, None, 'を', None], ['磨', 'みが', None, None], [None, None, 'く', None], [None, None, 'と', True], [None, None, '、', None], ['綺麗', 'きれい', None, None], [None, None, 'にな', None], [None, None, 'る。', None]]
[[None, None, 'そう', None], [None, None, 'する', None], [None, None, 'と', True], ['絶対', 'ぜったい', None, None], [None, None, 'に', None], ['失敗', 'しっぱい', None, None], [None, None, 'する', None], [None, None, 'よ', None], [None, None, '。', None]]
[[None, None, 'ここ', None], [None, None, 'から', None], ['見', 'み', None, None], [None, None, 'る', None], [None, None, 'と', True], [None, None, '、', None], ['富士山', 'ふじさん', None, None], [None, None, 'が', None], ['全然', 'ぜんぜん', None, None], ['見', 'み', None, None], [None, None, 'え', None], [None, None, 'ない', None], [None, None, '。', None]]
[['週', 'しゅう', None, None], [None, None, 'に', None], ['３', 'さん', None, None], ['回', 'かい', None, None], [None, None, 'トレーニング', None], [None, None, 'を', None], [None, None, 'する', None], [None, None, 'と', True], [None, None, 'だんだん', None], ['強', 'つよ', None, None], [None, None, 'くな', None], [None, None, 'る。', None]]

 28%|██▊       | 265/938 [02:39<06:20,  1.77it/s]

[[None, None, '「', None], ['約束', 'やくそく', None, None], [None, None, 'を', None], ['守', 'まも', None, True], [None, None, 'らないといけません', True], [None, None, '！」', None]]
[[None, None, '「なぜ、', None], ['税金', 'ぜいきん', None, None], [None, None, 'を', None], ['払', 'はら', None, True], [None, None, 'わないといけない', True], [None, None, 'のです', None], [None, None, 'か', None], [None, None, '？」', None]]
[[None, None, '「', None], ['子', 'こ', None, None], ['沢山', 'だくさん', None, None], [None, None, 'だ', None], [None, None, 'から', None], [None, None, '、', None], ['一週間', 'いっしゅうかん', None, None], [None, None, 'に', None], ['三十回', 'さんじゅっかい', None, None], [None, None, 'は', None], ['洗濯', 'せんたく', None, None], [None, None, 'しないとだめ', True], [None, None, '。」', None]]
[[None, None, '「', None], ['合格', 'ごうかく', None, None], [None, None, 'し', None], [None, None, 'たら', None], [None, None, 'まず', None], ['両親', 'りょうしん', None, None], [None, None, 'や', None], ['先生', 'せんせい', None, None], [None, None, 'に', None], ['伝', 'つた', None, True], [None, None, 'えないと', True], [None, None, '。」', None]]
[[None, None, '「ピーナッツにアレルギー', None], [None, None, 'がある', None], [None, None, 'と', None], ['言', 'い', None, True], [None, None, 'っておかないといけない', True], [None, None, 'んだ', None], [None, None, '。」', None]]

 28%|██▊       | 266/938 [02:39<06:19,  1.77it/s]

[[None, None, 'これ', None], [None, None, 'だけ', None], [None, None, 'の', True], ['筈', 'はず', None, True], [None, None, 'がない', True], [None, None, '。', None]]
[[None, None, 'それ', None], [None, None, 'は', None], [None, None, 'あなた', None], [None, None, 'の', None], [None, None, 'カバン', None], [None, None, 'の', True], ['筈', 'はず', None, True], [None, None, 'がない', True], [None, None, '。', None]]
[['夏', 'なつ', None, None], [None, None, 'に', None], ['雪', 'ゆき', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'る', None], ['筈', 'はず', None, True], [None, None, 'がない', True], [None, None, '。', None]]
[[None, None, 'あの', None], [None, None, 'ビル', None], [None, None, 'は', None], ['古', 'ふる', None, None], [None, None, 'すぎ', None], [None, None, 'な', None], [None, None, 'ので', None], [None, None, '、', None], ['病院', 'びょういん', None, None], [None, None, 'の', True], ['筈', 'はず', None, True], [None, None, 'がない', True], [None, None, '。', None]]
[[None, None, 'こんな', None], ['量', 'りょう', None, None], [None, None, 'を', None], ['一気', 'いっき', None, None], [None, None, 'に', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'られる', None], ['筈', 'はず', None, True], [None, None, 'がない', True], [None, None, 'よ', None], [None, None, '。', None]]

 28%|██▊       | 267/938 [02:40<06:16,  1.78it/s]

[['座', 'すわ', None, None], [None, None, 'るところ', None], [None, None, 'が', None], [None, None, 'ここ', None], [None, None, 'しかありません', True], [None, None, '。', None]]
[['遠', 'とお', None, None], [None, None, 'い', None], [None, None, 'ので', None], [None, None, '、', None], ['車', 'くるま', None, None], [None, None, 'で', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'こと', None], [None, None, 'しか', True], ['出来', 'でき', None, True], [None, None, 'ない', True], [None, None, '。', None]]
[[None, None, '「はい」', None], [None, None, 'と', None], [None, None, '「いいえ」', None], [None, None, 'しか', True], ['言', 'い', None, True], [None, None, 'わない', True], ['人', 'ひと', None, None], [None, None, 'と', None], [None, None, 'は', None], ['話', 'はな', None, None], [None, None, 'し', None], [None, None, 'にくい', None], [None, None, '。', None]]
[[None, None, 'すみません', None], [None, None, 'が', None], [None, None, '、', None], ['午後', 'ごご', None, None], [None, None, 'しか', True], ['空', 'あ', None, True], [None, None, 'いていない', True], [None, None, 'みたい', None], [None, None, 'です', None], [None, None, '。', None]]
[['冷蔵庫', 'れいぞうこ', None, None], [None, None, 'に', None], ['牛乳', 'ぎゅうにゅう', None, None], [None, None, 'しか', True], ['残', 'のこ', None, None], [None, None, 'って', None], [None, None, 'い', None], [None, None, 'ない', None], [None, None, '。', None]]

 29%|██▊       | 268/938 [02:40<06:20,  1.76it/s]

[[None, None, 'ぶどうは', None], ['甘', 'あま', None, None], [None, None, 'い', None], [None, None, 'だけでなく', True], [None, None, '、みずみずし', None], [None, None, 'い', None], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'だけでなく', True], [None, None, '、', None], ['私', 'わたし', None, None], [None, None, 'の', None], ['友達', 'ともだち', None, None], [None, None, 'も', None], ['日本語', 'にほんご', None, None], [None, None, 'が', None], ['喋', 'しゃべ', None, None], [None, None, 'れる', None], [None, None, '。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'は', None], ['日本語', 'にほんご', None, None], [None, None, 'だけでなく', True], [None, None, '、', None], ['韓国語', 'かんこくご', None, None], [None, None, '、', None], ['中国語', 'ちゅうごくご', None, None], [None, None, 'と', None], [None, None, 'タイ', None], ['語', 'ご', None, None], [None, None, 'も', None], ['話', 'はな', None, None], [None, None, 'せる', None], [None, None, '。', None]]
[[None, None, 'ジョニー・デップ', None], [None, None, 'は', None], [None, None, 'カナダ', None], [None, None, 'だけでなく', True], [None, None, '、', None], ['日本', 'にほん', None, None], [None, None, 'も', None], ['訪', 'おとず', None, None], [None, None, 'れ', None], [None, None, 'たことがある', None], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'だけでなく', True], [None, None, '、', None], ['私', 'わたし', None, None], [None, None, 'も', None], [None, None, 'この', None], ['映画', 'えいが', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'だ', None], [None, None, 'よ', None], [None, None, '。', None]]

 29%|██▊       | 269/938 [02:41<06:16,  1.78it/s]

[['馬', 'うま', None, None], [None, None, 'に', None], ['乗', 'の', None, None], [None, None, 'る', None], ['事', 'こと', None, True], [None, None, 'が', True], ['出来', 'でき', None, True], [None, None, 'る', True], [None, None, '。', None]]
[['泳', 'およ', None, None], [None, None, 'ぐ', None], ['事', 'こと', None, True], [None, None, 'が', True], ['出来', 'でき', None, True], [None, None, 'ます', True], [None, None, 'か', None], [None, None, '？', None]]
[['初', 'はじ', None, None], [None, None, 'めて、', None], ['漢字', 'かんじ', None, None], [None, None, 'を', None], ['書', 'か', None, None], [None, None, 'く', None], ['事', 'こと', None, True], [None, None, 'が', True], ['出来', 'でき', None, True], [None, None, 'た', True], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['姉', 'あね', None, None], [None, None, 'は', None], ['歌', 'うた', None, None], [None, None, 'う', None], ['事', 'こと', None, True], [None, None, 'が', True], ['出来', 'でき', None, True], [None, None, 'る', True], [None, None, '。', None]]
[['約束', 'やくそく', None, None], [None, None, 'を', None], ['守', 'まも', None, None], [None, None, 'る', None], ['事', 'こと', None, True], [None, None, 'が', True], ['出来', 'でき', None, True], [None, None, 'なくて', True], [None, None, 'すみません', None], [None, None, '。', None]]

 29%|██▉       | 270/938 [02:42<06:22,  1.74it/s]

[['本当', 'ほんとう', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'き', None], [None, None, 'たい', None], [None, None, 'のかい', True], [None, None, '？', None]]
[[None, None, 'これ', None], [None, None, 'だけで', None], ['十分', 'じゅうぶん', None, None], [None, None, 'なのかい', True], [None, None, '？', None]]
[[None, None, 'その', None], ['帽子', 'ぼうし', None, None], [None, None, 'を', None], ['被', 'かぶ', None, None], [None, None, 'って', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'のかい', True], [None, None, '？', None]]
[[None, None, 'どうしたの？', None], ['恥', 'は', None, None], [None, None, 'ずかし', None], [None, None, 'い', None], [None, None, 'のかい', True], [None, None, '？', None]]
[[None, None, 'この', None], ['番組', 'ばんぐみ', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'たくない', None], [None, None, 'の', None], [None, None, 'かい', True], [None, None, '？', None]]

 29%|██▉       | 271/938 [02:42<06:15,  1.77it/s]

[[None, None, 'もし', True], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'っ', None], [None, None, 'たら', None], [None, None, '、', None], ['車', 'くるま', None, None], [None, None, 'で', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, '。', None]]
[[None, None, 'もし', True], ['辛', 'から', None, None], [None, None, 'い', None], [None, None, 'ものだっ', None], [None, None, 'たら', None], [None, None, '、', None], ['食', 'た', None, None], [None, None, 'べられない。', None]]
[[None, None, 'もし', True], [None, None, 'コーヒー', None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'っ', None], [None, None, 'てくれ', None], [None, None, 'たら', None], [None, None, '、', None], ['嬉', 'うれ', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, '。', None]]
[[None, None, 'もし', True], [None, None, 'この', None], [None, None, 'パソコン', None], [None, None, 'を', None], ['彼女', 'かのじょ', None, None], [None, None, 'に', None], [None, None, 'あげ', None], [None, None, 'る', None], [None, None, 'なら', None], [None, None, '、', None], ['説明書', 'せつめいしょ', None, None], [None, None, 'も', None], ['渡', 'わた', None, None], [None, None, 'して', None], [None, None, 'ね', None], [None, None, '。', None]]
[[None, None, 'もし', True], ['君', 'きみ', None, None], [None, None, 'が', None], ['文法', 'ぶんぽう', None, None], [None, None, 'を', None], ['勉強', 'べんきょう', None, None], [None, None, 'し', None], [None, None, 'たら', None], [None, None, '、', None], ['日本語', 'にほんご', None, None], [None, None, 'を', None], ['喋', 'しゃべ', None, None], [None, None, 'れる', None], [None, None, 'ようにな', None], [None, None, 'る', None], [None, None, 'でしょう', None], [None, None, '。', None]]

 29%|██▉       | 272/938 [02:43<06:10,  1.80it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], ['掃除', 'そうじ', None, None], [None, None, 'が', None], [None, None, 'でき', None], [None, None, 'る', None], [None, None, 'し', True], [None, None, '、', None], ['料理', 'りょうり', None, None], [None, None, 'も', None], ['作', 'つく', None, None], [None, None, 'れる', None], [None, None, 'し', True], [None, None, '、', None], ['結婚', 'けっこん', None, None], [None, None, 'し', None], [None, None, 'てよかった', None], [None, None, '。', None]]
[[None, None, 'この', None], ['赤', 'あか', None, None], [None, None, 'が', None], ['可愛', 'かわい', None, None], [None, None, 'い', None], [None, None, 'し', True], [None, None, '、デザイン', None], [None, None, 'が', None], [None, None, 'いい', None], [None, None, 'し', True], [None, None, '、', None], [None, None, 'この', None], ['帽子', 'ぼうし', None, None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'い', None], [None, None, 'たい', None], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['親切', 'しんせつ', None, None], [None, None, 'だし', True], [None, None, '、', None], ['綺麗', 'きれい', None, None], [None, None, 'だし', True], [None, None, '、', None], ['本当', 'ほんとう', None, None], [None, None, 'に', None], ['大好', 'だいす', None, None], [None, None, 'き。', None]]
[[None, None, 'この', None], ['近所', 'きんじょ', None, None], [None, None, 'は', None], ['治安', 'ちあん', None, None], [None, None, 'が', None], [None, None, 'いい', None], [None, None, 'し', True], [None, None, '、スーパー', None], [None, None, 'が', None], ['近', 'ちか', None, None], [None, None, 'い', None], [None, None, 'し', True], [None, None, '、', None], ['人', 'ひと', None, None], [None, None, 'が', None], ['優', 'やさ', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'から', None], [None, None, 'ここ', None], [None, None, 'に', None], ['住', 'す', None, None], [None, None, 'ん', None], [None, None, 'でみ', None], [None, None, 'たい', None], [None, None, '。', None]]
[['僕', 'ぼく', None, None], [None, None, 'は', None], ['全然', 'ぜんぜん', None, None], [None, None, 'やり', None], [None, None, 'たくない', None], [None, None, 'し', True], [None, None, '、やること', None], [None, None, 'が', None], ['多', 'おお', None, None], [None, None, 'すぎ', None], [None, None, 'る', None], [None, None, 'し', True], [None, None, '、', None], ['諦', 'あきら', None, None], [None, None, 'めようと', None], ['思', 'おも', None, None], [None, None, 'って', None], [None, None, 'います。', None]]

 29%|██▉       | 273/938 [02:43<06:42,  1.65it/s]

[['裏面', 'りめん', None, None], [None, None, 'が', None], [None, None, 'ガラス', None], [None, None, 'でできている', True], [None, None, 'スマホ', None], [None, None, 'は', None], ['最近', 'さいきん', None, None], ['売行', 'うれゆ', None, None], [None, None, 'き', None], [None, None, 'が', None], [None, None, 'いい', None], [None, None, '。', None]]
[[None, None, 'この', None], [None, None, 'ワイン', None], [None, None, 'は', None], [None, None, 'トップクラス', None], [None, None, 'の', None], [None, None, 'ブドウ', None], [None, None, 'からできています', True], [None, None, '。どうぞ', None], ['飲', 'の', None, None], [None, None, 'んで', None], [None, None, 'ください。', None]]
[[None, None, 'スーパー', None], [None, None, 'は', None], ['木曜日', 'もくようび', None, None], [None, None, 'にミルク', None], [None, None, 'からできている', True], ['製品', 'せいひん', None, None], [None, None, 'の', None], [None, None, 'セール', None], [None, None, 'を', None], [None, None, 'する', None], [None, None, 'よ', None], [None, None, '！', None]]
[['飛行機', 'ひこうき', None, None], [None, None, 'は', None], ['軽', 'かる', None, None], [None, None, 'い', None], ['素材', 'そざい', None, None], [None, None, 'でできている', True], [None, None, '。', None]]
[[None, None, 'プラスチック', None], [None, None, 'や', None], [None, None, 'アスファルト', None], [None, None, 'は', None], ['石油', 'せきゆ', None, None], [None, None, 'からできます', True], [None, None, '。', None]]

 29%|██▉       | 274/938 [02:44<06:32,  1.69it/s]

[[None, None, 'シャワー', None], [None, None, 'を', None], ['浴', 'あ', None, True], [None, None, 'びながら', True], [None, None, 'いいアイディア', None], [None, None, 'を', None], ['思', 'おも', None, None], [None, None, 'いついた。', None]]
[['赤', 'あか', None, None], [None, None, 'ちゃん', None], [None, None, 'が', None], ['寝', 'ね', None, True], [None, None, 'ながら', True], [None, None, '、おなら', None], [None, None, 'を', None], [None, None, 'した。', None]]
[[None, None, 'バスに', None], ['乗', 'の', None, True], [None, None, 'りながら', True], [None, None, '、スマホ', None], [None, None, 'で', None], [None, None, 'ゲーム', None], [None, None, 'を', None], [None, None, 'し', None], [None, None, 'ている', None], [None, None, '。', None]]
[['友達', 'ともだち', None, None], [None, None, 'を', None], ['待', 'ま', None, True], [None, None, 'ちながら', True], [None, None, '、コーヒー', None], [None, None, 'を', None], ['飲', 'の', None, None], [None, None, 'もう。', None]]
[['運転', 'うんてん', None, None], [None, None, 'しながら', True], ['携帯', 'けいたい', None, None], [None, None, 'を', None], ['使', 'つか', None, None], [None, None, 'っ', None], [None, None, 'てはいけない', None], [None, None, '。', None]]

 29%|██▉       | 275/938 [02:44<06:22,  1.73it/s]

[['今', 'いま', None, None], ['食', 'た', None, None], [None, None, 'べ', None], ['終', 'お', None, True], [None, None, 'わったところ', True], [None, None, 'です', None], [None, None, '。', None]]
[['服', 'ふく', None, None], [None, None, 'を', None], ['脱', 'ぬ', None, True], [None, None, 'いでいたところ', True], [None, None, 'に、', None], ['母', 'はは', None, None], [None, None, 'が', None], ['部屋', 'へや', None, None], [None, None, 'に', None], ['入', 'はい', None, None], [None, None, 'っ', None], [None, None, 'てきた', None], [None, None, '。', None]]
[['新', 'あたら', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'おもちゃ', None], [None, None, 'を', None], ['渡', 'わた', None, True], [None, None, 'したところ', True], [None, None, 'で', None], ['壊', 'こわ', None, None], [None, None, 'れた。', None]]
[['友達', 'ともだち', None, None], [None, None, 'は', None], [None, None, 'たまたま', None], ['友達', 'ともだち', None, None], [None, None, 'に', None], ['会', 'あ', None, None], [None, None, 'う', None], [None, None, '：「', None], ['君', 'きみ', None, None], [None, None, 'に', None], ['会', 'あ', None, None], [None, None, 'い', None], [None, None, 'たい', None], [None, None, 'と', None], ['今', 'いま', None, None], ['思', 'おも', None, True], [None, None, 'っていたところ', True], [None, None, 'だわ！」', None]]
[['改札', 'かいさつ', None, None], [None, None, 'に', None], ['入', 'はい', None, True], [None, None, 'ったところ', True], [None, None, 'で', None], ['電車', 'でんしゃ', None, None], [None, None, 'の', None], ['扉', 'とびら', None, None], [None, None, 'が', None], ['閉', 'し', None, None], [None, None, 'ま', None], [None, None, 'った', None], [None, None, '。', None]]

 29%|██▉       | 276/938 [02:45<06:24,  1.72it/s]

[['今', 'いま', None, None], [None, None, '、', None], ['映画', 'えいが', None, None], [None, None, 'を', None], ['見', 'み', None, True], [None, None, 'ているところ', True], [None, None, 'です', None], [None, None, '。', None]]
[['今', 'いま', None, None], [None, None, '、お', None], ['父', 'とう', None, None], [None, None, 'さん', None], [None, None, 'は', None], ['富士山', 'ふじさん', None, None], [None, None, 'を', None], ['登', 'のぼ', None, True], [None, None, 'っているところ', True], [None, None, 'です', None], [None, None, '。', None]]
[['警察官', 'けいさつかん', None, None], [None, None, 'が', None], [None, None, 'パトロール', None], [None, None, 'を', None], [None, None, 'しているところ', True], [None, None, 'です', None], [None, None, '。', None]]
[['今', 'いま', None, None], [None, None, '、', None], ['先生', 'せんせい', None, None], [None, None, 'に', None], ['聞', 'き', None, True], [None, None, 'いているところ', True], [None, None, 'です', None], [None, None, '。', None]]
[['僕', 'ぼく', None, None], [None, None, 'は', None], ['今', 'いま', None, None], ['日本語', 'にほんご', None, None], [None, None, 'を', None], ['勉強', 'べんきょう', None, None], [None, None, 'しているところ', True], [None, None, 'だけど', None], [None, None, '。', None]]

 30%|██▉       | 277/938 [02:46<06:19,  1.74it/s]

[[None, None, 'コーヒー', None], [None, None, 'と', True], [None, None, 'お', None], ['茶', 'ちゃ', None, None], [None, None, 'と', True], [None, None, 'どちら', None], [None, None, 'が', None], [None, None, 'ほし', None], [None, None, 'い', None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'スポーツ', None], [None, None, 'する', None], [None, None, 'こと', None], [None, None, 'と', None], [None, None, '、ゲーム', None], [None, None, 'する', None], [None, None, 'こと', None], [None, None, '、', None], [None, None, 'どちらが', True], ['上手', 'じょうず', None, None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'ひらがな', None], [None, None, 'と', None], [None, None, 'カタカナ', None], [None, None, 'とどちらが', True], ['覚', 'おぼ', None, None], [None, None, 'え', None], [None, None, 'にくい', None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'エベレスト', None], [None, None, 'と', None], ['Ｋ', 'ケー', None, None], ['２', 'ツー', None, None], [None, None, 'とどちらが', True], ['高', 'たか', None, None], [None, None, 'い', None], [None, None, '？', None]]
[['電車', 'でんしゃ', None, None], [None, None, 'で', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'の', None], [None, None, 'と', None], ['車', 'くるま', None, None], [None, None, 'で', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'の', None], [None, None, 'とどちらが', True], ['早', 'はや', None, None], [None, None, 'い', None], [None, None, 'んです', None], [None, None, 'か', None], [None, None, '。', None]]

 30%|██▉       | 278/938 [02:46<06:23,  1.72it/s]

[['妻', 'つま', None, None], [None, None, 'にば', None], [None, None, 'れない', None], [None, None, 'ようにして', True], [None, None, 'くれ！', None]]
[['予約', 'よやく', None, None], [None, None, 'に', None], ['間', 'ま', None, None], [None, None, 'に', None], ['合', 'あ', None, None], [None, None, 'う', None], [None, None, 'ように', True], [None, None, 'し', None], [None, None, 'ましょう', None], [None, None, '。', None]]
[[None, None, 'その', None], [None, None, 'コップ', None], [None, None, 'を', None], ['落', 'お', None, None], [None, None, 'とさない', None], [None, None, 'ように', True], [None, None, 'し', None], [None, None, 'て', None], [None, None, 'ください。', None]]
[[None, None, 'あまり', None], ['音', 'おと', None, None], [None, None, 'が', None], ['出', 'で', None, None], [None, None, 'ない', None], [None, None, 'ようにして', True], [None, None, 'ください。', None]]
[['綺麗', 'きれい', None, None], [None, None, 'に', None], ['包', 'つつ', None, None], [None, None, 'む', None], [None, None, 'ようにします', True], [None, None, '。', None]]

 30%|██▉       | 279/938 [02:47<06:22,  1.72it/s]

[['仕事', 'しごと', None, None], [None, None, 'に', None], ['行', 'い', None, True], [None, None, 'かなければいけない', True], [None, None, '。', None]]
[['冬', 'ふゆ', None, None], [None, None, 'になっ', None], [None, None, 'たら', None], [None, None, '、', None], ['暖房', 'だんぼう', None, None], [None, None, 'を', None], [None, None, 'つけなければいけません', True], [None, None, '。', None]]
[['覚', 'おぼ', None, None], [None, None, 'え', None], [None, None, 'にくい', None], [None, None, 'けど', None], [None, None, '、', None], ['覚', 'おぼ', None, True], [None, None, 'えなければいけません', True], [None, None, '。', None]]
[[None, None, 'すごく', None], ['汚', 'よご', None, None], [None, None, 'れた', None], [None, None, 'から', None], ['洗', 'あら', None, True], [None, None, 'わなければいけない', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'に', None], ['会', 'あ', None, None], [None, None, 'い', None], [None, None, 'たくない', None], [None, None, 'けど', None], [None, None, '、', None], ['会', 'あ', None, True], [None, None, 'わなければいけません', True], [None, None, '。', None]]

 30%|██▉       | 280/938 [02:47<06:18,  1.74it/s]

[['先生', 'せんせい', None, None], [None, None, 'の', None], ['話', 'はなし', None, None], [None, None, 'を', None], ['聞', 'き', None, True], [None, None, 'かなければならない', True], [None, None, 'よ。', None]]
[['髪', 'かみ', None, None], [None, None, 'の', None], ['毛', 'け', None, None], [None, None, 'が', None], ['長', 'なが', None, None], [None, None, 'い', None], [None, None, 'から', None], [None, None, '、', None], ['切', 'き', None, True], [None, None, 'らなければならない', True], [None, None, '。', None]]
[['飛行機', 'ひこうき', None, None], [None, None, 'に', None], ['乗', 'の', None, None], [None, None, 'り', None], [None, None, 'たい', None], [None, None, 'なら', None], [None, None, '、', None], ['空港', 'くうこう', None, None], [None, None, 'に', None], ['行', 'い', None, True], [None, None, 'かなければならない', True], [None, None, '。', None]]
[['新', 'あたら', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'ノート', None], [None, None, 'を', None], ['買', 'か', None, True], [None, None, 'わなければならない', True], [None, None, 'かもしれない', None], [None, None, '。', None]]
[['日本語', 'にほんご', None, None], [None, None, 'が', None], ['上手', 'じょうず', None, None], [None, None, 'になり', None], [None, None, 'たい', None], [None, None, 'から', None], [None, None, '、', None], ['勉強', 'べんきょう', None, None], [None, None, 'を', None], [None, None, 'しなければならない', True], [None, None, '。', None]]

 30%|██▉       | 281/938 [02:48<06:09,  1.78it/s]

[[None, None, 'テレビ', None], [None, None, 'を', None], ['見', 'み', None, True], ['続', 'つづ', None, True], [None, None, 'ける', True], [None, None, 'つもり', None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'まっすぐ', None], ['見', 'み', None, None], [None, None, 'て', None], [None, None, '、', None], ['歩', 'ある', None, True], [None, None, 'き', True], ['続', 'つづ', None, True], [None, None, 'けなさい', True], [None, None, '！', None]]
[['文法', 'ぶんぽう', None, None], [None, None, 'の', None], ['間違', 'まちが', None, None], [None, None, 'え', None], [None, None, 'を', None], ['直', 'なお', None, True], [None, None, 'し', True], ['続', 'つづ', None, True], [None, None, 'けて', True], [None, None, 'み', None], [None, None, 'たらどう', None], [None, None, 'だ', None], [None, None, '？', None]]
[['大', 'おお', None, None], [None, None, 'き', None], [None, None, 'い', None], ['魚', 'さかな', None, None], [None, None, 'を', None], ['釣', 'つ', None, None], [None, None, 'る', None], [None, None, 'まで', None], ['釣', 'つ', None, True], [None, None, 'り', True], ['続', 'つづ', None, True], [None, None, 'けます', True], [None, None, '。', None]]
[[None, None, 'あの', None], ['警察官', 'けいさつかん', None, None], [None, None, 'は', None], ['一時間', 'いちじかん', None, None], ['以上', 'いじょう', None, None], ['見回', 'みまわ', None, True], [None, None, 'り', True], ['続', 'つづ', None, True], [None, None, 'けた', True], [None, None, '。', None]]

 30%|███       | 282/938 [02:49<06:23,  1.71it/s]

[[None, None, 'トムに', None], ['手伝', 'てつだ', None, None], [None, None, 'い', None], [None, None, 'を', None], [None, None, 'する', None], [None, None, 'ように', True], ['頼', 'たの', None, True], [None, None, 'んだ', True], [None, None, 'よ', None], [None, None, '。', None]]
[['子供', 'こども', None, None], [None, None, 'ら', None], [None, None, 'が', None], ['怖', 'こわ', None, None], [None, None, 'がら', None], [None, None, 'ない', None], [None, None, 'ように', True], ['頼', 'たの', None, True], [None, None, 'む', True], [None, None, 'よ', None], [None, None, '。', None]]
[['卵', 'たまご', None, None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'う', None], [None, None, 'ように', True], ['言', 'い', None, True], [None, None, 'った', True], [None, None, 'はずだ', None], [None, None, '。', None]]
[['明日', 'あした', None, None], ['試合', 'しあい', None, None], [None, None, 'がある', None], [None, None, 'ので', None], [None, None, '、', None], ['今夜', 'こんや', None, None], [None, None, 'よく', None], ['眠', 'ねむ', None, None], [None, None, 'る', None], [None, None, 'ように', True], ['言', 'い', None, True], [None, None, 'った', True], [None, None, '。', None]]
[['息子', 'むすこ', None, None], [None, None, 'に', None], ['本', 'ほん', None, None], [None, None, 'を', None], ['月', 'つき', None, None], [None, None, 'に1', None], ['冊', 'さつ', None, None], ['読', 'よ', None, None], [None, None, 'む', None], [None, None, 'ように', True], ['言', 'い', None, True], [None, None, 'った', True], [None, None, '。', None]]

 30%|███       | 283/938 [02:49<06:27,  1.69it/s]

[['会議', 'かいぎ', None, None], [None, None, 'は', None], ['月曜日', 'げつようび', None, None], [None, None, 'の', True], ['予定', 'よてい', None, True], [None, None, 'です', None], [None, None, '。', None]]
[['学校', 'がっこう', None, None], [None, None, 'で', None], ['研究', 'けんきゅう', None, None], [None, None, 'を', None], [None, None, 'する', None], ['予定', 'よてい', None, True], [None, None, 'です', None], [None, None, '。', None]]
[['卒業', 'そつぎょう', None, None], [None, None, 'し', None], [None, None, 'てから', None], [None, None, '、', None], ['仕事', 'しごと', None, None], [None, None, 'を', None], ['探', 'さが', None, None], [None, None, 'す', None], ['予定', 'よてい', None, True], [None, None, 'です', None], [None, None, '。', None]]
[['電気代', 'でんきだい', None, None], [None, None, 'が', None], ['高', 'たか', None, None], [None, None, 'くな', None], [None, None, 'る', None], [None, None, 'けど', None], [None, None, '、エアコン', None], [None, None, 'を', None], ['点', 'つ', None, None], [None, None, 'け', None], [None, None, 'てお', None], [None, None, 'く', None], ['予定', 'よてい', None, True], [None, None, 'だ', True], [None, None, '。', None]]
[[None, None, 'いつ', None], ['日本語', 'にほんご', None, None], [None, None, 'を', None], ['勉強', 'べんきょう', None, None], [None, None, 'し', None], ['始', 'はじ', None, None], [None, None, 'め', None], [None, None, 'る', None], ['予定', 'よてい', None, True], [None, None, 'です', True], [None, None, 'か', None], [None, None, '。', None]]

 30%|███       | 284/938 [02:50<06:23,  1.70it/s]

[['生', 'い', None, None], [None, None, 'きて', None], [None, None, 'ここ', None], [None, None, 'を', None], ['出', 'で', None, None], [None, None, 'られる', None], [None, None, 'ように', True], ['祈', 'いの', None, True], [None, None, 'っている', True], [None, None, 'んだ', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'が', None], ['安全', 'あんぜん', None, None], [None, None, 'に', None], ['帰', 'かえ', None, None], [None, None, 'れる', None], [None, None, 'ように', True], ['祈', 'いの', None, True], [None, None, 'ろう', True], [None, None, '！', None]]
[[None, None, 'うまく', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'ように', True], ['祈', 'いの', None, True], [None, None, 'って', True], [None, None, '(ください)', None], [None, None, 'ね', None], [None, None, '。', None]]
[[None, None, 'この', None], [None, None, 'ノートパソコンに', None], ['税金', 'ぜいきん', None, None], [None, None, 'が', None], [None, None, 'かから', None], [None, None, 'ない', None], [None, None, 'ように', True], ['祈', 'いの', None, True], [None, None, 'っている', True], [None, None, '。', None]]
[[None, None, 'うち', None], [None, None, 'の', None], ['娘', 'むすめ', None, None], [None, None, 'が', None], ['事故', 'じこ', None, None], [None, None, 'に', None], ['遭', 'あ', None, None], [None, None, 'わ', None], [None, None, 'ない', None], [None, None, 'ように', True], ['祈', 'いの', None, True], [None, None, 'っている', True], [None, None, 'わ。', None]]

 30%|███       | 285/938 [02:50<06:16,  1.73it/s]

[['今', 'いま', None, None], [None, None, '、', None], ['家', 'いえ', None, None], [None, None, 'を', None], ['出', 'で', None, True], [None, None, 'た', True], ['許', 'ばか', None, True], [None, None, 'り', True], [None, None, 'です', None], [None, None, '。', None]]
[['電車', 'でんしゃ', None, None], [None, None, 'に', None], ['乗', 'の', None, True], [None, None, 'った', True], ['許', 'ばか', None, True], [None, None, 'り', True], [None, None, 'の', None], ['時', 'とき', None, None], [None, None, 'に', None], ['携帯', 'けいたい', None, None], [None, None, 'を', None], ['落', 'お', None, None], [None, None, 'とした。', None]]
[[None, None, 'ユミに', None], ['彼氏', 'かれし', None, None], [None, None, 'が', None], ['出来', 'でき', None, None], [None, None, 'たと', None], ['聞', 'き', None, True], [None, None, 'いた', True], ['許', 'ばか', None, True], [None, None, 'り', True], [None, None, '。', None]]
[[None, None, 'その', None], ['漢字', 'かんじ', None, None], [None, None, 'を', None], ['習', 'なら', None, True], [None, None, 'った', True], ['許', 'ばか', None, True], [None, None, 'り', True], [None, None, 'な', None], [None, None, 'のに', None], [None, None, '、', None], [None, None, 'もう', None], ['忘', 'わす', None, None], [None, None, 'れ', None], [None, None, 'た', None], [None, None, '。', None]]
[['今', 'いま', None, None], [None, None, 'の', None], ['赤', 'あか', None, None], [None, None, 'ちゃん', None], [None, None, 'は', None], ['生', 'う', None, True], [None, None, 'まれた', True], ['許', 'ばか', None, True], [None, None, 'り', True], [None, None, 'でしょう', None], [None, None, '。', None]]

 30%|███       | 286/938 [02:51<06:08,  1.77it/s]

[[None, None, 'それ', None], [None, None, 'は', None], ['単純', 'たんじゅん', None, None], ['化', 'か', None, True], [None, None, 'した', True], ['英語', 'えいご', None, None], [None, None, 'のように', None], ['見', 'み', None, None], [None, None, 'え', None], [None, None, 'る', None], [None, None, '。', None]]
[['２０', 'にじゅっ', None, None], ['世紀', 'せいき', None, None], [None, None, 'に', None], [None, None, 'は', None], ['経済', 'けいざい', None, None], ['成長', 'せいちょう', None, None], [None, None, 'の', None], ['原因', 'げんいん', None, None], [None, None, 'の', None], ['一', 'ひと', None, None], [None, None, 'つ', None], [None, None, 'は', None], ['自動', 'じどう', None, None], ['化', 'か', None, True], [None, None, 'だ', None], [None, None, 'と', None], ['考', 'かんが', None, None], [None, None, 'えられている', None], [None, None, '。', None]]
[[None, None, 'お', None], ['父', 'とう', None, None], [None, None, 'さん、アプリ', None], [None, None, 'は', None], [None, None, 'こうやって', None], ['最小', 'さいしょう', None, None], ['化', 'か', None, True], [None, None, 'する', True], [None, None, 'の。', None]]
[[None, None, 'その', None], ['新', 'あら', None, None], [None, None, 'たなタイプ', None], [None, None, 'の', None], ['電池', 'でんち', None, None], [None, None, 'が', None], ['商品', 'しょうひん', None, None], ['化', 'か', None, True], [None, None, 'する', True], ['計画', 'けいかく', None, None], [None, None, 'がある', None], [None, None, 'と', None], ['言', 'い', None, None], [None, None, 'われている', None], [None, None, '。', None]]
[[None, None, 'プラスチック', None], [None, None, 'を', None], ['液', 'えき', None, None], ['化', 'か', None, True], [None, None, 'する', True], ['方法', 'ほうほう', None, None], [None, None, 'は', None], [None, None, 'エネルギ', None], ['産業', 'さんぎょう', None, None], [None, None, 'を', None], ['一変', 'いっぺん', None, None], [None, None, 'させ', None], [None, None, 'る', None], [None, None, 'かもしれない', None], [None, None, '。', None]]

 31%|███       | 287/938 [02:51<06:26,  1.68it/s]

[['私', 'わたし', None, None], [None, None, 'の', None], ['携帯', 'けいたい', None, None], [None, None, 'を', None], ['返', 'かえ', None, True], [None, None, 'せ', True], [None, None, '！', None]]
[[None, None, 'もっと', None], ['飲', 'の', None, True], [None, None, 'め', True], [None, None, '！', None]]
[[None, None, 'ゴミ', None], [None, None, 'は', None], [None, None, 'ゴミ', None], ['箱', 'ばこ', None, None], [None, None, 'に', None], ['捨', 'す', None, True], [None, None, 'てろ', True], [None, None, '！', None]]
[['早', 'はや', None, None], [None, None, 'く', None], ['寝', 'ね', None, True], [None, None, 'ろ', True], [None, None, '！', None]]
[['先生', 'せんせい', None, None], [None, None, 'が', None], [None, None, '「', None], ['皆', 'みな', None, None], ['静', 'しず', None, None], [None, None, 'か', None], [None, None, 'に', None], [None, None, 'しろ', True], [None, None, '！」', None], [None, None, 'と', None], ['言', 'い', None, None], [None, None, 'った', None], [None, None, '。', None]]

 31%|███       | 288/938 [02:52<06:22,  1.70it/s]

[['例', 'たと', None, None], [None, None, 'えば', None], ['風邪', 'かぜ', None, None], [None, None, 'を', None], ['引', 'ひ', None, True], [None, None, 'かないように', True], [None, None, '、', None], ['暖', 'あたた', None, None], [None, None, 'か', None], [None, None, 'い', None], ['服装', 'ふくそう', None, None], [None, None, 'を', None], [None, None, 'する', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'が', None], ['理解', 'りかい', None, None], ['出来', 'でき', None, True], [None, None, 'るように', True], ['説明', 'せつめい', None, None], [None, None, 'し', None], [None, None, 'ようと', None], ['思', 'おも', None, None], [None, None, 'っ', None], [None, None, 'ている', None], [None, None, '。', None]]
[['大事', 'だいじ', None, None], [None, None, 'な', None], [None, None, 'こと', None], [None, None, 'を', None], ['忘', 'わす', None, True], [None, None, 'れないように', True], [None, None, 'いつもメモ', None], [None, None, 'を', None], [None, None, 'し', None], [None, None, 'ている', None], [None, None, '。', None]]
[['間', 'ま', None, True], [None, None, 'に', True], ['合', 'あ', None, True], [None, None, 'うように', True], ['数分', 'すうふん', None, None], ['早', 'はや', None, None], [None, None, 'く', None], ['出', 'で', None, None], [None, None, 'る', None], [None, None, 'つもり', None], [None, None, 'だ', None], [None, None, '。', None]]
[['太陽', 'たいよう', None, None], [None, None, 'に', None], ['目', 'め', None, None], [None, None, 'が', None], [None, None, 'くらまないように', True], [None, None, '、スキーヤー', None], [None, None, 'は', None], [None, None, 'ゴーグル', None], [None, None, 'を', None], [None, None, 'かけています。', None]]

 31%|███       | 289/938 [02:53<06:13,  1.74it/s]

[['今日', 'きょう', None, None], [None, None, 'は', None], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'る', None], [None, None, 'かしら', True], [None, None, '。', None]]
[[None, None, 'すぐ', None], ['冷房', 'れいぼう', None, None], [None, None, 'を', None], [None, None, 'つけ', None], [None, None, 'てくれない', None], [None, None, 'かしら', True], [None, None, '。', None]]
[[None, None, 'ここ', None], [None, None, 'で', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'てもいい', None], [None, None, 'かしら', True], [None, None, '。', None]]
[['納豆', 'なっとう', None, None], [None, None, 'は', None], ['変', 'へん', None, None], [None, None, 'な', None], ['匂', 'にお', None, None], [None, None, 'い', None], [None, None, 'がする', None], [None, None, 'から', None], [None, None, '、', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'れる', None], [None, None, 'かしら', True], [None, None, '。', None]]
[[None, None, 'あまり', None], ['理解', 'りかい', None, None], ['出来', 'でき', None, None], [None, None, 'ていない', None], [None, None, 'みたい', None], [None, None, '。', None], ['行', 'い', None, None], [None, None, 'ける', None], [None, None, 'かしら', True], [None, None, '。', None]]

 31%|███       | 290/938 [02:53<06:20,  1.71it/s]

[[None, None, '「もっと', None], ['大人', 'おとな', None, None], [None, None, 'らしく', True], [None, None, 'し', None], [None, None, 'なさい', None], [None, None, 'よ', None], [None, None, '！」', None]]
[[None, None, '「やっと', None], ['夏', 'なつ', None, None], [None, None, 'らしい', True], ['日', 'ひ', None, None], [None, None, 'が', None], ['来', 'き', None, None], [None, None, 'た', None], [None, None, 'よ', None], [None, None, '！」', None]]
[[None, None, '「', None], [None, None, 'そんな', None], [None, None, 'こと', None], [None, None, 'を', None], ['言', 'い', None, None], [None, None, 'う', None], [None, None, 'のは', None], [None, None, '、', None], ['彼女', 'かのじょ', None, None], [None, None, 'らしい', True], [None, None, '。」', None]]
[[None, None, '「カップル', None], [None, None, 'らしく', True], ['映画', 'えいが', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'こう', None], [None, None, '！」', None]]
[[None, None, '「あなた', None], [None, None, 'の', None], ['笑顔', 'えがお', None, None], [None, None, 'の', None], ['愛', 'あい', None, None], [None, None, 'らしさ', True], [None, None, 'に', None], ['気', 'き', None, None], [None, None, 'づ', None], [None, None, 'い', None], [None, None, 'たばかり', None], [None, None, 'だ', None], [None, None, 'わ。」', None]]

 31%|███       | 291/938 [02:54<06:14,  1.73it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], ['忙', 'いそが', None, None], [None, None, 'しそう', None], [None, None, 'にみえる', True], [None, None, '。', None]]
[['先生', 'せんせい', None, None], [None, None, 'は', None], ['怒', 'おこ', None, None], [None, None, 'っ', None], [None, None, 'ている', None], [None, None, 'よう', None], [None, None, 'にみえる', True], [None, None, '。', None]]
[['水', 'みず', None, None], [None, None, 'ぼうそう', None], [None, None, 'にみえる', True], [None, None, 'ニキビ。', None]]
[[None, None, 'この', None], [None, None, 'スーツケース', None], [None, None, 'は', None], ['軽', 'かる', None, True], [None, None, 'くみえる', True], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['幸', 'しあわ', None, None], [None, None, 'せそう', None], [None, None, 'にみえる', True], [None, None, '。', None]]

 31%|███       | 292/938 [02:54<06:12,  1.73it/s]

[[None, None, 'あの', None], ['親', 'おや', None, None], [None, None, 'は', None], ['優', 'やさ', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'と', None], [None, None, 'みえる', True], [None, None, '。', None]]
[['家', 'いえ', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'った', None], [None, None, 'けど', None], ['留守', 'るす', None, None], [None, None, 'と', None], ['見', 'み', None, True], [None, None, 'えた', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], [None, None, 'マラソン', None], [None, None, 'を', None], ['走', 'はし', None, None], [None, None, 'った', None], [None, None, 'と', None], ['見', 'み', None, True], [None, None, 'えて', True], [None, None, 'ハアハア', None], ['言', 'い', None, None], [None, None, 'っ', None], [None, None, 'ている', None], [None, None, '。', None]]
[[None, None, 'テストに', None], ['落', 'お', None, None], [None, None, 'ちた', None], [None, None, 'から', None], [None, None, '、', None], ['勉強', 'べんきょう', None, None], [None, None, 'してなかった', None], [None, None, 'と', True], ['見', 'み', None, True], [None, None, 'える', True], [None, None, '。', None]]
[['水', 'みず', None, None], [None, None, 'と', True], ['見', 'み', None, True], [None, None, 'えた', True], [None, None, 'が', None], [None, None, '、ラムネ', None], [None, None, 'でした', None], [None, None, '。', None]]

 31%|███       | 293/938 [02:55<06:05,  1.77it/s]

[[None, None, 'お', None], ['母', 'かあ', None, None], [None, None, 'さん', None], [None, None, 'は', None], [None, None, 'オランダ', None], ['風', 'ふう', None, True], [None, None, 'の', True], [None, None, 'サラダ', None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'だ', None], [None, None, 'よ', None], [None, None, '。', None]]
[[None, None, 'パブ', None], [None, None, 'は', None], ['韓国', 'かんこく', None, None], ['風', 'ふう', None, True], [None, None, 'の', True], [None, None, 'ほうが', None], [None, None, 'いい', None], [None, None, 'と', None], ['思', 'おも', None, None], [None, None, 'う', None], [None, None, '。', None]]
[['中国', 'ちゅうごく', None, None], ['風', 'ふう', None, True], [None, None, 'の', True], [None, None, 'ドレス', None], [None, None, 'がほし', None], [None, None, 'い', None], [None, None, 'よ', None], [None, None, '！', None]]
[[None, None, 'この', None], [None, None, 'イラスト', None], [None, None, 'は', None], ['漫画', 'まんが', None, None], ['風', 'ふう', None, True], [None, None, 'だ', None], [None, None, 'ね', None], [None, None, '。', None]]
[[None, None, 'それ', None], [None, None, 'は', None], [None, None, 'アメリカ', None], ['風', 'ふう', None, True], [None, None, 'の', True], ['生活', 'せいかつ', None, None], [None, None, 'と', None], ['言', 'い', None, None], [None, None, 'われている', None], [None, None, '。', None]]

 31%|███▏      | 294/938 [02:56<06:43,  1.59it/s]

[['夏', 'なつ', None, None], [None, None, 'に', None], [None, None, 'は', None], [None, None, '、', None], [None, None, 'ここ', None], [None, None, 'で', None], [None, None, 'クマ', None], [None, None, 'が', True], ['見', 'み', None, True], [None, None, 'られます', True], [None, None, '。', None]]
[['最近', 'さいきん', None, None], [None, None, 'ガラス', None], [None, None, 'ででき', None], [None, None, 'ている', None], [None, None, 'スマホ', None], [None, None, 'が', True], ['見', 'み', None, True], [None, None, 'られる', True], [None, None, '。', None]]
[[None, None, 'いつか', None], ['姫路城', 'ひめじじょう', None, None], [None, None, 'が', True], ['見', 'み', None, True], [None, None, 'られる', True], [None, None, 'といい', None], [None, None, 'な。', None]]
[[None, None, 'どこ', None], [None, None, 'で', None], ['紙芝居', 'かみしばい', None, None], [None, None, 'が', True], ['見', 'み', None, True], [None, None, 'られます', True], [None, None, 'か', None], [None, None, '？', None]]
[[None, None, 'よく', None], ['見', 'み', None, None], [None, None, 'てみ', None], [None, None, 'る', None], [None, None, 'と', None], ['動物', 'どうぶつ', None, None], [None, None, 'の', None], ['足跡', 'あしあと', None, None], [None, None, 'が', True], ['見', 'み', None, True], [None, None, 'られる', True], [None, None, '。', None]]

 31%|███▏      | 295/938 [02:56<06:28,  1.65it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], ['私', 'わたし', None, None], [None, None, 'の', None], ['気持', 'きも', None, None], [None, None, 'ちに', None], ['気', 'き', None, True], [None, None, 'がついた', True], [None, None, 'のだろうか', None], [None, None, '。', None]]
[['今', 'いま', None, None], [None, None, '、お', None], ['金', 'かね', None, None], [None, None, 'を', None], ['忘', 'わす', None, None], [None, None, 'れ', None], [None, None, 'た', None], [None, None, 'ことに', True], ['気', 'き', None, True], [None, None, 'がついた', True], [None, None, 'ばかり', None], [None, None, 'だ', None], [None, None, '。', None]]
[['自分', 'じぶん', None, None], [None, None, 'の', None], [None, None, 'ミス', None], [None, None, 'に', True], ['気', 'き', None, True], [None, None, 'がつきました', True], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'わぁ！', None], ['気', 'き', None, True], [None, None, 'がついた', True], [None, None, 'の？', None], ['嬉', 'うれ', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, '！', None]]
[['今日', 'きょう', None, None], [None, None, 'は', None], ['母', 'はは', None, None], [None, None, 'の', None], ['誕生日', 'たんじょうび', None, None], [None, None, 'だ', None], [None, None, '！ ', None], ['気', 'き', None, True], [None, None, 'がついていなかった', True], [None, None, '。', None]]

 32%|███▏      | 296/938 [02:57<06:28,  1.65it/s]

[[None, None, 'これ', None], [None, None, 'でも', True], [None, None, '、', None], [None, None, 'それ', None], [None, None, 'でも', True], [None, None, '、', None], ['何', 'なん', None, None], [None, None, 'でも', True], [None, None, 'いい', None], [None, None, 'です', None], [None, None, '！', None]]
[[None, None, 'サッカー', None], [None, None, 'でも', True], [None, None, '、', None], ['卓球', 'たっきゅう', None, None], [None, None, 'でも', True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'ならスポーツ', None], [None, None, 'は', None], ['何', 'なん', None, None], [None, None, 'でも', None], [None, None, 'でき', None], [None, None, 'る', None], [None, None, '。', None]]
[['電車', 'でんしゃ', None, None], [None, None, 'でも', True], [None, None, '、バス', None], [None, None, 'でも', True], ['行', 'い', None, None], [None, None, 'ける', None], ['場所', 'ばしょ', None, None], [None, None, 'な', None], [None, None, 'ので', None], [None, None, '、', None], ['便利', 'べんり', None, None], [None, None, 'です', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'が', None], ['Ｍａｃ', 'マック', None, None], [None, None, 'でも', True], ['Ｗｉｎｄｏｗｓ', 'ウィンドウズ', None, None], [None, None, 'でも', True], ['使', 'つか', None, None], [None, None, 'える', None], [None, None, 'って', None], [None, None, '。', None]]
[[None, None, 'じゃんけん', None], [None, None, 'でも', True], [None, None, '、サイコロ', None], [None, None, 'でも', True], ['何', 'なん', None, None], [None, None, 'でも', True], [None, None, 'いい', None], [None, None, 'から', None], [None, None, '、', None], ['早', 'はや', None, None], [None, None, 'く', None], ['決', 'き', None, None], [None, None, 'めて', None], [None, None, 'よ', None], [None, None, '。', None]]

 32%|███▏      | 297/938 [02:57<06:19,  1.69it/s]

[['運動', 'うんどう', None, None], [None, None, 'は', None], ['楽', 'たの', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'です', None], [None, None, '。', None], [None, None, 'それに', True], ['体', 'からだ', None, None], [None, None, 'にいい', None], [None, None, 'です', None], [None, None, '。', None]]
[['夜', 'よる', None, None], ['遅', 'おそ', None, None], [None, None, 'く', None], [None, None, 'まで', None], ['働', 'はたら', None, None], [None, None, 'き', None], [None, None, 'ます', None], [None, None, '。', None], [None, None, 'それに', True], ['朝', 'あさ', None, None], [None, None, 'も', None], ['早', 'はや', None, None], [None, None, 'い', None], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'この', None], ['旅館', 'りょかん', None, None], [None, None, 'の', None], ['料理', 'りょうり', None, None], [None, None, 'が', None], ['美味', 'おい', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, '。', None], [None, None, 'それに', True], ['周', 'まわ', None, None], [None, None, 'り', None], [None, None, 'の', None], ['景色', 'けしき', None, None], [None, None, 'も', None], ['美', 'うつく', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, '。', None]]
[['日本', 'にほん', None, None], [None, None, 'は', None], ['住', 'す', None, None], [None, None, 'み', None], [None, None, 'やすい', None], [None, None, '。', None], [None, None, 'それに', True], ['病院代', 'びょういんだい', None, None], [None, None, 'が', None], ['安', 'やす', None, None], [None, None, 'い', None], [None, None, '。', None]]
[['山', 'やま', None, None], [None, None, 'の', None], ['上', 'うえ', None, None], [None, None, 'から', None], [None, None, 'の', None], ['景色', 'けしき', None, None], [None, None, 'が', None], ['綺麗', 'きれい', None, None], [None, None, '。', None], [None, None, 'それに', True], ['空気', 'くうき', None, None], [None, None, 'も', None], ['綺麗', 'きれい', None, None], [None, None, '。', None]]

 32%|███▏      | 298/938 [02:58<06:06,  1.74it/s]

[[None, None, '「', None], ['其', 'そ', None, True], [None, None, 'れで', True], [None, None, 'プロジェクトどうなった', None], [None, None, 'のです', None], [None, None, 'か', None], [None, None, '？」', None], [None, None, '「', None], ['期限', 'きげん', None, None], ['通', 'どお', None, None], [None, None, 'りに', None], ['終', 'お', None, None], [None, None, 'わ', None], [None, None, 'りました。」', None]]
[['ＪＬＰＴ', 'ジェーエルピーティー', None, None], [None, None, 'に', None], ['合格', 'ごうかく', None, None], [None, None, 'し', None], [None, None, 'たい', None], [None, None, 'です', None], [None, None, '。', None], ['其', 'それ', None, True], [None, None, 'で', True], ['毎日', 'まいにち', None, None], [None, None, 'しっかり', None], ['勉強', 'べんきょう', None, None], [None, None, 'し', None], [None, None, 'ています', None], [None, None, '。', None]]
[[None, None, 'この', None], ['辺', 'あた', None, None], [None, None, 'りに', None], [None, None, 'は', None], ['多', 'おお', None, None], [None, None, 'くの', None], ['桜', 'さくら', None, None], [None, None, 'が', None], ['植', 'う', None, None], [None, None, 'えられている。', None], ['其', 'それ', None, True], [None, None, 'で', True], ['外国人', 'がいこくじん', None, None], [None, None, 'が', None], ['花見', 'はなみ', None, None], [None, None, 'に', None], ['来', 'く', None, None], [None, None, 'る', None], ['人気', 'にんき', None, None], [None, None, 'の', None], ['観光', 'かんこう', None, None], [None, None, 'スポット', None], [None, None, 'にな', None], [None, None, 'った。', None]]
[[None, None, 'この', None], [None, None, 'ヘビ', None], [None, None, 'は', None], ['有毒', 'ゆうどく', None, None], [None, None, 'の', None], ['一種', 'いっしゅ', None, None], [None, None, 'です', None], [None, None, '。', None], ['其', 'それ', None, True], [None, None, 'で', True], ['非常', 'ひじょう', None, None], [None, None, 'に', None], ['危険', 'きけん', None, None], [None, None, 'だと', None], ['考', 'かんが', None, None], [None, None, 'えられています。', None]]
[[None, None, 'いずくさん', None], [None, None, 'は', None], ['子供', 'こども', None, None], [None, None, 'の', None], ['頃', 'ころ', None, None], [None, None, 'よくいじめられました。', None], ['其', 'それ', None, True], [None, None, 'で', True], ['弱', 'よわ', None, None], [None, None, 'い', None], ['者', 'もの', None, None], [None, None, 'の', None], ['味方', 'みかた', None, None], [None, None, 'になっています。', None]]

 32%|███▏      | 299/938 [02:58<06:05,  1.75it/s]

[['僕', 'ぼく', None, None], [None, None, 'が', None], [None, None, 'どこ', None], [None, None, 'にいる', None], [None, None, 'か', True], [None, None, 'わかる？', None]]
[[None, None, 'いつ', None], ['美術館', 'びじゅつかん', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'か', True], ['決', 'き', None, None], [None, None, 'めました', None], [None, None, 'か', None], [None, None, '？', None]]
[['彼', 'かれ', None, None], [None, None, 'の', None], ['好', 'この', None, None], [None, None, 'み', None], [None, None, 'の', None], ['味', 'あじ', None, None], [None, None, 'が', None], ['何', 'なに', None, None], [None, None, 'か', True], [None, None, 'わかる？', None]]
[['彼', 'かれ', None, None], [None, None, 'が', None], ['誰', 'だれ', None, None], [None, None, 'のこと', None], [None, None, 'を', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'か', True], [None, None, 'わか', None], [None, None, 'りません', None], [None, None, '。', None]]
[['何', 'なに', None, None], [None, None, 'を', None], ['消', 'け', None, None], [None, None, 'した', None], [None, None, 'か', True], ['知', 'し', None, None], [None, None, 'っ', None], [None, None, 'ている', None], [None, None, '？', None]]

 32%|███▏      | 300/938 [02:59<06:01,  1.76it/s]

[[None, None, 'この', None], [None, None, 'コーヒー', None], [None, None, 'は', None], ['甘', 'あま', None, None], [None, None, 'い', None], [None, None, 'ですが', None], [None, None, '、', None], [None, None, 'それでも', True], ['砂糖', 'さとう', None, None], [None, None, 'を', None], ['加', 'くわ', None, None], [None, None, 'えます。', None]]
[[None, None, 'タバコ', None], [None, None, 'は', None], ['体', 'からだ', None, None], [None, None, 'に', None], ['悪', 'わる', None, None], [None, None, 'い', None], [None, None, 'と', None], ['言', 'い', None, None], [None, None, 'われている', None], [None, None, '。', None], [None, None, 'それでも', True], [None, None, '、', None], ['止', 'や', None, None], [None, None, 'め', None], [None, None, 'にくい', None], [None, None, '。', None]]
[['高', 'たか', None, None], [None, None, 'い', None], [None, None, 'のに', None], [None, None, '、', None], [None, None, 'それでも', True], ['買', 'か', None, None], [None, None, 'う', None], [None, None, 'つもり', None], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'その', None], [None, None, 'カップル', None], [None, None, 'が', None], [None, None, 'ずっと', None], ['喧嘩', 'けんか', None, None], [None, None, 'し', None], [None, None, 'ている', None], [None, None, '。', None], [None, None, 'それでも', True], [None, None, '、よく', None], ['旅行', 'りょこう', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, '。', None]]
[['先生', 'せんせい', None, None], [None, None, 'が', None], [None, None, 'インフルエンザにかかった。', None], [None, None, 'それでも', True], [None, None, '、', None], ['学校', 'がっこう', None, None], [None, None, 'を', None], ['休', 'やす', None, None], [None, None, 'んでいない。', None]]

 32%|███▏      | 301/938 [03:00<06:03,  1.75it/s]

[['公園', 'こうえん', None, None], [None, None, 'に', None], ['遊', 'あそ', None, True], [None, None, 'びに', True], ['行', 'い', None, True], [None, None, 'ったらどうですか', True], [None, None, '。', None]]
[[None, None, 'あそこ', None], [None, None, 'の', None], [None, None, 'ゴミ', None], [None, None, 'を', None], ['拾', 'ひろ', None, True], [None, None, 'ったらどう', True], [None, None, 'です', None], [None, None, 'か', None], [None, None, '。', None]]
[[None, None, 'ダイエット', None], [None, None, 'を', None], [None, None, 'してみたらどう', True], [None, None, '？', None]]
[[None, None, 'そんなに', None], ['彼', 'かれ', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'だ', None], [None, None, 'っ', None], [None, None, 'たら', None], [None, None, '、', None], ['付', 'つ', None, True], [None, None, 'き', True], ['合', 'あ', None, True], [None, None, 'ったらどう', True], [None, None, '？', None]]
[['日本', 'にほん', None, None], [None, None, 'に', None], ['居', 'い', None, None], [None, None, 'て', None], ['寂', 'さび', None, None], [None, None, 'し', None], [None, None, 'い', None], [None, None, 'なら', None], [None, None, '、アメリカに', None], ['帰', 'かえ', None, True], [None, None, 'ったらどう', True], [None, None, '？', None]]

 32%|███▏      | 302/938 [03:00<06:04,  1.75it/s]

[[None, None, 'イルカ', None], [None, None, 'は', None], [None, None, 'とても', None], ['賢', 'かしこ', None, None], [None, None, 'い', None], [None, None, 'と', True], ['考', 'かんが', None, True], [None, None, 'えられている', True], [None, None, '。', None]]
[[None, None, 'この', None], ['街', 'まち', None, None], [None, None, 'に', None], ['海賊', 'かいぞく', None, None], [None, None, 'が', None], ['住', 'す', None, None], [None, None, 'ん', None], [None, None, 'でいた', None], [None, None, 'と', True], ['考', 'かんが', None, True], [None, None, 'えられている', True], [None, None, '。', None]]
[[None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'は', None], [None, None, 'どんな', None], ['人', 'ひと', None, None], [None, None, 'にも', None], ['悪', 'わる', None, None], [None, None, 'い', None], ['影響', 'えいきょう', None, None], [None, None, 'がある', None], [None, None, 'と', True], ['考', 'かんが', None, True], [None, None, 'えられている', True], [None, None, '。', None]]
[[None, None, 'この', None], ['建物', 'たてもの', None, None], [None, None, 'は', None], ['５００', 'ごひゃく', None, None], ['年', 'ねん', None, None], ['頃', 'ごろ', None, None], ['建', 'た', None, None], [None, None, 'てられた', None], [None, None, 'と', True], ['考', 'かんが', None, True], [None, None, 'えられている', True], [None, None, '。', None]]
[['一週間', 'いっしゅうかん', None, None], [None, None, 'で', None], [None, None, 'ひらがな', None], [None, None, 'を', None], ['覚', 'おぼ', None, None], [None, None, 'え', None], [None, None, 'る', None], [None, None, 'ことができる', None], [None, None, 'と', True], ['考', 'かんが', None, True], [None, None, 'えられている', True], [None, None, '。', None]]

 32%|███▏      | 303/938 [03:01<06:02,  1.75it/s]

[['論文', 'ろんぶん', None, None], [None, None, '：「', None], ['ＷＰ', 'ダブリューピー', None, None], ['４０', 'よんじゅう', None, None], [None, None, 'は', None], ['使用', 'しよう', None, None], [None, None, 'が', None], ['多', 'おお', None, None], [None, None, 'い', None], [None, None, 'とされている', True], [None, None, '。」', None]]
[['論文', 'ろんぶん', None, None], [None, None, '：「ポーランド', None], ['人', 'じん', None, None], [None, None, 'に', None], [None, None, 'は', None], ['１３', 'じゅうさん', None, None], [None, None, 'という', None], ['数字', 'すうじ', None, None], [None, None, 'は', None], ['不吉', 'ふきつ', None, None], [None, None, 'な', None], ['数字', 'すうじ', None, None], [None, None, 'とされている', True], [None, None, '。」', None]]
[['論説', 'ろんせつ', None, None], [None, None, '：「ジム・モリソン', None], [None, None, 'の', None], ['正確', 'せいかく', None, None], [None, None, 'な', None], ['死因', 'しいん', None, None], [None, None, 'は', None], ['不明', 'ふめい', None, None], [None, None, 'とされている', True], [None, None, 'のである。」', None]]
[['論説', 'ろんせつ', None, None], [None, None, '：「', None], ['歴史的', 'れきしてき', None, None], [None, None, 'に', None], ['平仮名', 'ひらがな', None, None], [None, None, 'は', None], ['元', 'もと', None, None], [None, None, 'は', None], [None, None, '『', None], ['女', 'おんな', None, None], [None, None, 'の', None], [None, None, 'もの』', None], [None, None, 'だとされていた', True], [None, None, '。」', None]]
[['論説', 'ろんせつ', None, None], [None, None, '：「', None], ['過度', 'かど', None, None], [None, None, 'の', None], [None, None, 'アルコール', None], ['飲料', 'いんりょう', None, None], [None, None, 'の', None], ['摂取', 'せっしゅ', None, None], [None, None, 'は', None], ['多数', 'たすう', None, None], [None, None, 'の', None], ['病気', 'びょうき', None, None], [None, None, 'の', None], ['原因', 'げんいん', None, None], [None, None, 'にな', None], [None, None, 'る', None], [None, None, 'とされている', True], [None, None, '。」', None]]

 32%|███▏      | 304/938 [03:01<06:03,  1.74it/s]

[['危', 'あぶ', None, None], [None, None, 'な', None], [None, None, 'い', None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'われている', True], [None, None, 'ので', None], [None, None, '、し', None], [None, None, 'ないほうがいい', None], [None, None, 'よ', None], [None, None, '。', None]]
[[None, None, 'ライオン', None], [None, None, 'が', None], [None, None, 'ジャングル', None], [None, None, 'の', None], ['王様', 'おうさま', None, None], [None, None, 'だと', True], ['言', 'い', None, True], [None, None, 'われている', True], [None, None, '。', None]]
[[None, None, 'プロテイン', None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'る', None], [None, None, 'と', None], ['力', 'ちから', None, None], [None, None, 'が', None], [None, None, 'つく', None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'われている', True], [None, None, '。', None]]
[['見', 'み', None, None], [None, None, 'え', None], [None, None, 'ない', None], [None, None, 'こと', None], [None, None, 'は', None], ['信', 'しん', None, None], [None, None, 'じ', None], [None, None, 'られない', None], [None, None, 'こと', None], [None, None, 'だと', True], ['言', 'い', None, True], [None, None, 'われている', True], [None, None, '。', None]]
[[None, None, 'ひど', None], [None, None, 'い', None], [None, None, 'こと', None], [None, None, 'を', None], [None, None, 'した', None], [None, None, 'から', None], [None, None, '、', None], ['犯人', 'はんにん', None, None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'われている', True], [None, None, '。', None]]

 33%|███▎      | 305/938 [03:02<06:00,  1.76it/s]

[['次', 'つぎ', None, None], [None, None, 'の', None], ['電車', 'でんしゃ', None, None], [None, None, 'を', None], ['待', 'ま', None, True], [None, None, 'てば', True], ['良', 'よ', None, True], [None, None, 'かった', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'ゲーム', None], [None, None, 'より', None], ['勉強', 'べんきょう', None, None], [None, None, 'を', None], [None, None, 'すれば', True], ['良', 'よ', None, True], [None, None, 'かった', True], [None, None, 'です', None], [None, None, '。', None]]
[['天気予報', 'てんきよほう', None, None], [None, None, 'を', None], ['見', 'み', None, True], [None, None, 'れば', True], ['良', 'よ', None, True], [None, None, 'かった', True], [None, None, 'です', None], [None, None, '。', None]]
[[None, None, 'スーパー', None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'った', None], ['時', 'とき', None, None], [None, None, '、', None], ['牛乳', 'ぎゅうにゅう', None, None], [None, None, 'を', None], ['買', 'か', None, True], [None, None, 'えば', True], ['良', 'よ', None, True], [None, None, 'かった', True], [None, None, '。', None]]
[['寝', 'ね', None, None], [None, None, 'ないで', None], [None, None, '、', None], ['日本語', 'にほんご', None, None], [None, None, 'を', None], ['勉強', 'べんきょう', None, None], [None, None, 'すれば', True], ['良', 'よ', None, True], [None, None, 'かった', True], [None, None, '。', None]]

 33%|███▎      | 306/938 [03:02<06:01,  1.75it/s]

[['運動', 'うんどう', None, None], [None, None, 'を', None], [None, None, 'すればいい', True], [None, None, 'だろう。', None]]
[[None, None, 'それいつまでに', None], [None, None, 'やればいい', True], [None, None, '？', None]]
[['眠', 'ねむ', None, None], [None, None, 'たいならちょっと', None], ['仮眠', 'かみん', None, None], [None, None, 'を', None], [None, None, 'とればいい', True], [None, None, 'のに。', None]]
[['仕事', 'しごと', None, None], [None, None, 'に', None], ['早', 'はや', None, None], [None, None, 'く', None], [None, None, 'いけばいい', True], [None, None, 'と', None], ['思', 'おも', None, None], [None, None, 'いますよ。', None]]
[['道', 'みち', None, None], [None, None, 'の', None], ['案内', 'あんない', None, None], [None, None, 'を、', None], ['誰', 'だれ', None, None], [None, None, 'に', None], [None, None, 'きけばいい', True], [None, None, 'のか', None], ['分', 'わ', None, None], [None, None, 'からない。', None]]

 33%|███▎      | 307/938 [03:03<05:54,  1.78it/s]

[['毎日', 'まいにち', None, None], [None, None, '、', None], ['好', 'す', None, None], [None, None, 'きな', None], ['番組', 'ばんぐみ', None, None], [None, None, 'が', None], ['見', 'み', None, True], [None, None, 'れたらいい', True], [None, None, '。', None]]
[['自由', 'じゆう', None, None], [None, None, 'に', None], [None, None, 'したらいい', True], [None, None, 'でしょう。', None]]
[['明日', 'あした', None, None], [None, None, 'と', None], ['明後日', 'あさって', None, None], [None, None, 'も', None], ['晴', 'は', None, True], [None, None, 'れるといい', True], [None, None, 'ですね。', None]]
[['文句', 'もんく', None, None], [None, None, 'を', None], ['言', 'い', None, None], [None, None, 'わないで！どう', None], [None, None, 'したらいい', True], [None, None, 'のか', None], ['教', 'おし', None, None], [None, None, 'えてよ。', None]]
[['僕', 'ぼく', None, None], [None, None, 'もイルカみたいに', None], ['上手', 'じょうず', None, None], [None, None, 'に', None], ['泳', 'およ', None, True], [None, None, 'げたらいい', True], [None, None, 'のに。', None]]

 33%|███▎      | 308/938 [03:04<05:49,  1.80it/s]

[['一日', 'いちにち', None, None], ['中', 'じゅう', None, True], [None, None, '、', None], ['勉強', 'べんきょう', None, None], [None, None, 'をした。', None]]
[['授業', 'じゅぎょう', None, None], ['中', 'ちゅう', None, True], [None, None, 'に', True], [None, None, '、トイレに', None], ['行', 'い', None, None], [None, None, 'きたくなった。', None]]
[['食事', 'しょくじ', None, None], ['中', 'ちゅう', None, True], [None, None, 'にスマホをいじるのはやめなさい。', None]]
[[None, None, 'まだ', None], ['考', 'かんが', None, None], [None, None, 'え', None], ['中', 'ちゅう', None, True], [None, None, 'だから、', None], ['決', 'き', None, None], [None, None, 'めていないよ。', None]]
[[None, None, 'テスト', None], ['中', 'ちゅう', None, True], [None, None, 'に', True], ['私', 'わたし', None, None], [None, None, 'の', None], ['携帯', 'けいたい', None, None], [None, None, 'が', None], ['鳴', 'な', None, None], [None, None, 'ってしまった。', None]]

 33%|███▎      | 309/938 [03:04<05:49,  1.80it/s]

[[None, None, 'いつも', None], ['眠', 'ねむ', None, None], [None, None, 'っている', None], ['間', 'あいだ', None, True], [None, None, 'に', True], ['歯軋', 'はぎし', None, None], [None, None, 'りをしてしまう。', None]]
[['私', 'わたし', None, None], [None, None, 'が', None], ['暇', 'ひま', None, None], [None, None, 'な', True], ['間', 'あいだ', None, True], [None, None, 'に', True], [None, None, '、', None], ['電話', 'でんわ', None, None], [None, None, 'をかけてください。', None]]
[['仕事', 'しごと', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'くまで', None], [None, None, 'の', True], ['間', 'あいだ', None, True], [None, None, 'に', True], ['掃除', 'そうじ', None, None], [None, None, 'したかったけど', None], ['無理', 'むり', None, None], [None, None, 'だった。', None]]
[['私', 'わたし', None, None], [None, None, 'が', None], ['家', 'いえ', None, None], [None, None, 'にいる', None], ['間', 'あいだ', None, True], [None, None, 'に', True], [None, None, '、', None], ['電話', 'でんわ', None, None], [None, None, 'をかけてください。', None]]
[['僕', 'ぼく', None, None], [None, None, 'が', None], ['東京', 'とうきょう', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'っていた', None], ['５', 'ご', None, None], ['年', 'ねん', None, None], [None, None, 'の', True], ['間', 'あいだ', None, True], [None, None, 'に', True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'は', None], ['変', 'か', None, None], [None, None, 'わってしまった。', None]]

 33%|███▎      | 310/938 [03:05<05:51,  1.79it/s]

[['近', 'ちか', None, None], [None, None, 'い', None], ['内', 'うち', None, True], [None, None, 'に', True], ['連絡', 'れんらく', None, None], [None, None, 'します。', None]]
[['鉄', 'てつ', None, None], [None, None, 'は', None], ['熱', 'あつ', None, None], [None, None, 'い', None], ['内', 'うち', None, True], [None, None, 'に', True], ['打', 'う', None, None], [None, None, 'て。', None]]
[['授業', 'じゅぎょう', None, None], [None, None, 'を', None], ['受', 'う', None, None], [None, None, 'けている', None], ['内', 'うち', None, True], [None, None, 'に', True], [None, None, '、', None], ['宿題', 'しゅくだい', None, None], [None, None, 'を', None], ['完成', 'かんせい', None, None], [None, None, 'させた。', None]]
[['赤', 'あか', None, None], [None, None, 'ちゃんは', None], ['食', 'た', None, None], [None, None, 'べている', None], ['内', 'うち', None, True], [None, None, 'に', True], ['寝', 'ね', None, None], [None, None, 'てしまった。', None]]
[['日本', 'にほん', None, None], [None, None, 'にいる', None], ['内', 'うち', None, True], [None, None, 'に', True], ['東京', 'とうきょう', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'ってみたい。', None]]

 33%|███▎      | 311/938 [03:05<06:15,  1.67it/s]

[['暗', 'くら', None, True], [None, None, 'くならない', True], ['内', 'うち', None, True], [None, None, 'に', True], ['帰', 'かえ', None, None], [None, None, 'って', None], ['来', 'き', None, None], [None, None, 'なさいよ。', None]]
[['私', 'わたし', None, None], [None, None, 'が', None], ['知', 'し', None, True], [None, None, 'らない', True], ['内', 'うち', None, True], [None, None, 'に', True], [None, None, '、', None], ['友達', 'ともだち', None, None], [None, None, 'が', None], ['離婚', 'りこん', None, None], [None, None, 'していた。', None]]
[['冷', 'さ', None, True], [None, None, 'めない', True], ['内', 'うち', None, True], [None, None, 'に', True], [None, None, 'お', None], ['召', 'め', None, None], [None, None, 'し', None], ['上', 'あ', None, None], [None, None, 'がりください。', None]]
[['眠', 'ねむ', None, True], [None, None, 'くならない', True], ['内', 'うち', None, True], [None, None, 'に', True], ['宿題', 'しゅくだい', None, None], [None, None, 'を', None], ['終', 'お', None, None], [None, None, 'わらせよう。', None]]
[[None, None, 'いくらも', None], ['泳', 'およ', None, True], [None, None, 'がない', True], ['内', 'うち', None, True], [None, None, 'に', True], [None, None, '、', None], ['向', 'む', None, None], [None, None, 'こう', None], ['岸', 'ぎし', None, None], [None, None, 'についてしまった。', None]]

 33%|███▎      | 312/938 [03:06<06:24,  1.63it/s]

[['税金', 'ぜいきん', None, None], [None, None, 'を', None], ['払', 'はら', None, True], [None, None, 'う', True], ['可', 'べ', None, True], [None, None, 'き', True], [None, None, 'です。', None]]
[['考', 'かんが', None, True], [None, None, 'える', True], ['可', 'べ', None, True], [None, None, 'き', True], [None, None, 'ことが', None], ['多', 'おお', None, None], [None, None, 'すぎて、', None], ['頭', 'あたま', None, None], [None, None, 'が', None], ['痛', 'いた', None, None], [None, None, 'い。', None]]
[['言', 'い', None, True], [None, None, 'う', True], ['可', 'べ', None, True], [None, None, 'き', True], [None, None, 'ことを', None], ['言', 'い', None, None], [None, None, 'うのは', None], ['親', 'おや', None, None], [None, None, 'の', None], ['義務', 'ぎむ', None, None], [None, None, 'だ。', None]]
[['誰', 'だれ', None, None], [None, None, 'も', None], ['見', 'み', None, None], [None, None, 'ていなくても、', None], ['法律', 'ほうりつ', None, None], [None, None, 'は', None], ['守', 'まも', None, True], [None, None, 'る', True], ['可', 'べ', None, True], [None, None, 'き', True], [None, None, 'だ。', None]]
[['明日', 'あした', None, None], [None, None, 'の', None], ['会議', 'かいぎ', None, None], [None, None, 'は', None], ['重大', 'じゅうだい', None, None], [None, None, 'な', None], ['話', 'はなし', None, None], [None, None, 'があるので、', None], ['出席', 'しゅっせき', None, None], [None, None, 'を', None], [None, None, 'する', True], ['可', 'べ', None, True], [None, None, 'き', True], [None, None, 'だ。', None]]

 33%|███▎      | 313/938 [03:07<06:18,  1.65it/s]

[[None, None, 'あなた', None], ['一人', 'ひとり', None, None], [None, None, 'だけで', None], ['決', 'き', None, True], [None, None, 'める', True], ['可', 'べ', None, True], [None, None, 'きではない', True], [None, None, '。', None]]
[['腐', 'くさ', None, None], [None, None, 'っている', None], ['食', 'た', None, None], [None, None, 'べ', None], ['物', 'もの', None, None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べる', True], ['可', 'べ', None, True], [None, None, 'きではない', True], [None, None, '。', None]]
[['禁煙', 'きんえん', None, None], ['場所', 'ばしょ', None, None], [None, None, 'では、タバコを', None], ['吸', 'す', None, True], [None, None, 'う', True], ['可', 'べ', None, True], [None, None, 'きではない', True], [None, None, '。', None]]
[['大', 'たい', None, None], [None, None, 'したことないよ。', None], ['心配', 'しんぱい', None, None], [None, None, 'を', None], [None, None, 'する', True], ['可', 'べ', None, True], [None, None, 'きではない', True], [None, None, '。', None]]
[['人', 'ひと', None, None], [None, None, 'が', None], ['嫌', 'いや', None, None], [None, None, 'がることを', None], [None, None, 'する', True], ['可', 'べ', None, True], [None, None, 'きではない', True], [None, None, '。', None]]

 33%|███▎      | 314/938 [03:07<06:46,  1.54it/s]

[[None, None, 'このパスタ', None], [None, None, 'って', True], ['美味', 'おい', None, None], [None, None, 'しいよね。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'って', True], ['誰', 'だれ', None, None], [None, None, '？', None]]
[['先生', 'せんせい', None, None], [None, None, 'って', True], ['優', 'やさ', None, None], [None, None, 'しいね。', None]]
[[None, None, 'ギター', None], [None, None, 'って', True], ['弾', 'ひ', None, None], [None, None, 'けますか？', None]]
[['冬', 'ふゆ', None, None], [None, None, 'って', True], ['寒', 'さむ', None, None], [None, None, 'いけど、', None], ['雪', 'ゆき', None, None], [None, None, 'は', None], ['綺麗', 'きれい', None, None], [None, None, 'だ。', None]]

 34%|███▎      | 315/938 [03:08<07:12,  1.44it/s]

[[None, None, 'このお', None], ['菓子', 'かし', None, None], [None, None, 'は', None], ['中々', 'なかなか', None, True], [None, None, 'おいしい。', None]]
[[None, None, 'ここからの', None], ['景色', 'けしき', None, None], [None, None, 'は', None], ['中々', 'なかなか', None, True], [None, None, 'いいですね。', None]]
[[None, None, 'ここの', None], ['会員', 'かいいん', None, None], [None, None, 'になるのは', None], ['中々', 'なかなか', None, True], ['難', 'むずか', None, None], [None, None, 'しい。', None]]
[['富士', 'ふじ', None, None], ['登山', 'とざん', None, None], [None, None, 'は', None], ['中々', 'なかなか', None, True], ['大変', 'たいへん', None, None], [None, None, 'です。', None]]
[[None, None, 'この', None], ['子', 'こ', None, None], [None, None, 'が', None], ['描', 'か', None, None], [None, None, 'く', None], ['絵', 'え', None, None], [None, None, 'は', None], ['中々', 'なかなか', None, True], [None, None, 'のものです。', None]]

 34%|███▎      | 316/938 [03:09<06:59,  1.48it/s]

[[None, None, 'トムは', None], ['驚', 'おどろ', None, None], [None, None, 'き', None], [None, None, 'の', True], ['余', 'あま', None, True], [None, None, 'り', True], [None, None, '、', None], ['何', 'なに', None, None], [None, None, 'も', None], ['言', 'い', None, None], [None, None, 'えなかった。', None]]
[['美味', 'おい', None, None], [None, None, 'し', None], [None, None, 'さ', None], [None, None, 'の', True], ['余', 'あま', None, True], [None, None, 'り', True], [None, None, '、', None], ['食', 'た', None, None], [None, None, 'べ', None], ['飽', 'あ', None, None], [None, None, 'きることはない。', None]]
[['悲', 'かな', None, None], [None, None, 'し', None], [None, None, 'さ', None], [None, None, 'の', True], ['余', 'あま', None, True], [None, None, 'り', True], [None, None, '、', None], ['言葉', 'ことば', None, None], [None, None, 'を', None], ['失', 'うしな', None, None], [None, None, 'った。', None]]
[['苦', 'くる', None, None], [None, None, 'し', None], [None, None, 'さ', None], [None, None, 'の', True], ['余', 'あま', None, True], [None, None, 'り', True], [None, None, '、', None], ['大', 'おお', None, None], [None, None, 'きな', None], ['声', 'こえ', None, None], [None, None, 'を', None], ['出', 'だ', None, None], [None, None, 'してしまった。', None]]
[['喜', 'よろこ', None, None], [None, None, 'び', None], [None, None, 'の', True], ['余', 'あま', None, True], [None, None, 'り', True], [None, None, '、', None], ['涙', 'なみだ', None, None], [None, None, 'がとまらない。', None]]

 34%|███▍      | 317/938 [03:09<06:39,  1.55it/s]

[[None, None, 'このシステムは', None], ['中々', 'なかなか', None, True], ['改善', 'かいぜん', None, None], [None, None, 'され', None], [None, None, 'ない', None], [None, None, '。', None]]
[['調査', 'ちょうさ', None, None], [None, None, 'が', None], ['中々', 'なかなか', None, True], ['進', 'すす', None, None], [None, None, 'ま', None], [None, None, 'ない', None], [None, None, '。', None]]
[['貯金', 'ちょきん', None, None], [None, None, 'が', None], ['中々', 'なかなか', None, True], [None, None, 'でき', None], [None, None, 'ない', None], [None, None, '。', None]]
[['最近', 'さいきん', None, None], [None, None, '、あたしは', None], ['中々', 'なかなか', None, True], [None, None, 'やる', None], ['気', 'き', None, None], [None, None, 'が', None], ['出', 'で', None, None], [None, None, 'ない', None], [None, None, '。', None]]
[['痛', 'いた', None, None], [None, None, 'みが', None], ['中々', 'なかなか', None, True], ['良', 'よ', None, None], [None, None, 'くなら', None], [None, None, 'ない', None], [None, None, '。', None]]

 34%|███▍      | 318/938 [03:10<06:24,  1.61it/s]

[['天気予報', 'てんきよほう', None, None], [None, None, 'によると', True], [None, None, '、', None], ['明日', 'あした', None, None], [None, None, 'は', None], ['晴', 'は', None, None], [None, None, 'れです。', None]]
[['警察', 'けいさつ', None, None], [None, None, 'によると', True], [None, None, '、', None], ['犯人', 'はんにん', None, None], [None, None, 'が', None], ['逃', 'に', None, None], [None, None, 'げたそうです。', None]]
[['先輩', 'せんぱい', None, None], [None, None, 'の', None], ['話', 'はなし', None, None], [None, None, 'によると', True], [None, None, '、あの', None], ['会社', 'かいしゃ', None, None], [None, None, 'はブラック', None], ['企業', 'きぎょう', None, None], [None, None, 'らしい。', None]]
[['目撃者', 'もくげきしゃ', None, None], [None, None, 'によれば', True], [None, None, '、', None], ['犯人', 'はんにん', None, None], [None, None, 'は', None], ['２０代', 'にじゅうだい', None, None], ['男性', 'だんせい', None, None], [None, None, 'だ。', None]]
[['聞', 'き', None, None], [None, None, 'くところ', None], [None, None, 'によれば', True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'はあの', None], ['子', 'こ', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'きみたいだ。', None]]

 34%|███▍      | 319/938 [03:11<06:19,  1.63it/s]

[[None, None, 'その', None], ['車', 'くるま', None, None], [None, None, 'の', None], ['値段', 'ねだん', None, None], [None, None, 'によって', True], [None, None, '、', None], ['決', 'き', None, None], [None, None, 'めます。', None]]
[['国', 'くに', None, None], [None, None, 'によって', True], [None, None, '、いろいろな', None], ['伝統', 'でんとう', None, None], [None, None, 'があります。', None]]
[['調査', 'ちょうさ', None, None], [None, None, 'によって', True], ['新', 'あら', None, None], [None, None, 'たな', None], ['事実', 'じじつ', None, None], [None, None, 'が', None], ['明', 'あき', None, None], [None, None, 'らかになった。', None]]
[['納豆', 'なっとう', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'きかどうかは', None], ['人', 'ひと', None, None], [None, None, 'による', True], [None, None, '。', None]]
[['話', 'はな', None, None], [None, None, 'し', None], ['合', 'あ', None, None], [None, None, 'い', None], [None, None, 'によって', True], ['決', 'き', None, None], [None, None, 'まったのだから、', None], ['文句', 'もんく', None, None], ['言', 'い', None, None], [None, None, 'わないで。', None]]

 34%|███▍      | 320/938 [03:11<06:07,  1.68it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], ['全', 'まった', None, True], [None, None, 'く', True], ['勉強', 'べんきょう', None, None], [None, None, 'し', None], [None, None, 'ない', None], [None, None, '。', None]]
[['全', 'まった', None, True], [None, None, 'く', True], ['変化', 'へんか', None, None], [None, None, 'が', None], [None, None, 'ない', None], [None, None, '。', None]]
[['全', 'まった', None, True], [None, None, 'く', True], ['負', 'ま', None, None], [None, None, 'けたことが', None], [None, None, 'ない', None], [None, None, '。', None]]
[['全', 'まった', None, True], [None, None, 'く', True], ['学', 'まな', None, None], [None, None, 'ぶつもりが', None], [None, None, 'ない', None], [None, None, '。', None]]
[['実', 'じつ', None, None], [None, None, 'は', None], ['全', 'まった', None, True], [None, None, 'く', True], ['泳', 'およ', None, None], [None, None, 'げ', None], [None, None, 'ない', None], [None, None, 'んです。', None]]

 34%|███▍      | 321/938 [03:12<06:04,  1.69it/s]

[['今回', 'こんかい', None, None], [None, None, 'は、', None], ['相手', 'あいて', None, None], [None, None, 'を', None], ['信', 'しん', None, None], [None, None, 'じてみる', None], ['事', 'こと', None, True], [None, None, 'だ', True], [None, None, '。', None]]
[['生徒', 'せいと', None, None], [None, None, 'は、', None], ['先生', 'せんせい', None, None], [None, None, 'に', None], ['従', 'したが', None, None], [None, None, 'う', None], ['事', 'こと', None, True], [None, None, 'だ', True], [None, None, '。', None]]
[['大事', 'だいじ', None, None], [None, None, 'なのは', None], ['医者', 'いしゃ', None, None], [None, None, 'からもらった', None], ['薬', 'くすり', None, None], [None, None, 'を', None], ['飲', 'の', None, None], [None, None, 'む', None], ['事', 'こと', None, True], [None, None, 'だ', True], [None, None, '。', None]]
[[None, None, 'まずはやってみる', None], ['事', 'こと', None, True], [None, None, 'だ', True], [None, None, '。', None], ['改善点', 'かいぜんてん', None, None], [None, None, 'が', None], ['見', 'み', None, None], [None, None, 'えてくるから。', None]]
[['覚', 'おぼ', None, None], [None, None, 'えたらすぐにしゃべってみる', None], ['事', 'こと', None, True], [None, None, 'だ', True], [None, None, '。', None], ['上達', 'じょうたつ', None, None], [None, None, 'するから。', None]]

 34%|███▍      | 322/938 [03:12<05:59,  1.71it/s]

[['美味', 'おい', None, True], [None, None, 'しいそうだ', True], [None, None, 'から、たくさん', None], ['買', 'か', None, None], [None, None, 'った。', None]]
[[None, None, 'トムの', None], ['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['女優', 'じょゆう', None, None], [None, None, 'だそうだ', True], [None, None, '。', None]]
[[None, None, 'あの', None], ['方', 'かた', None, None], [None, None, 'は', None], ['親切', 'しんせつ', None, None], [None, None, 'だそうです', True], [None, None, '。', None]]
[['今晩', 'こんばん', None, None], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, True], [None, None, 'るそうだ', True], [None, None, '。', None]]
[['来週', 'らいしゅう', None, None], [None, None, 'から', None], ['気温', 'きおん', None, None], [None, None, 'が', None], ['下', 'さ', None, True], [None, None, 'がるそうだ', True], [None, None, '。', None]]

 34%|███▍      | 323/938 [03:13<06:00,  1.71it/s]

[['口笛', 'くちぶえ', None, None], [None, None, 'を', None], ['吹', 'ふ', None, None], [None, None, 'いた。', None], [None, None, 'すると', True], [None, None, '、', None], ['小鳥', 'ことり', None, None], [None, None, 'がやって', None], ['来', 'き', None, None], [None, None, 'た。', None]]
[['目', 'め', None, None], [None, None, 'を', None], ['閉', 'と', None, None], [None, None, 'じた。', None], [None, None, 'すると', True], [None, None, '、', None], ['一瞬', 'いっしゅん', None, None], [None, None, 'で', None], ['眠', 'ねむ', None, None], [None, None, 'ってしまった。', None]]
[['川', 'かわ', None, None], [None, None, 'に', None], ['魚', 'さかな', None, None], [None, None, 'を', None], ['釣', 'つ', None, None], [None, None, 'りに', None], ['行', 'い', None, None], [None, None, 'った。', None], [None, None, 'すると', True], [None, None, '、そこで', None], ['旧友', 'きゅうゆう', None, None], [None, None, 'に', None], ['会', 'あ', None, None], [None, None, 'った。なんという', None], ['偶然', 'ぐうぜん', None, None], [None, None, '？', None]]
[['従兄弟', 'いとこ', None, None], [None, None, 'が', None], ['絵', 'え', None, None], [None, None, 'を', None], ['描', 'か', None, None], [None, None, 'いていた。', None], [None, None, 'すると', True], [None, None, '、', None], ['弟', 'おとうと', None, None], [None, None, 'も', None], ['真似', 'まね', None, None], [None, None, 'をして', None], ['描', 'か', None, None], [None, None, 'き', None], ['始', 'はじ', None, None], [None, None, 'めた。', None]]
[[None, None, 'A：「', None], ['僕', 'ぼく', None, None], [None, None, 'は◯◯', None], ['年', 'ねん', None, None], ['生', 'う', None, None], [None, None, 'まれです。」', None], [None, None, 'B：「', None], [None, None, 'すると', True], [None, None, '、', None], ['車', 'くるま', None, None], [None, None, 'を', None], ['運転', 'うんてん', None, None], [None, None, 'できる', None], ['歳', 'とし', None, None], [None, None, 'ですね。」', None]]

 35%|███▍      | 324/938 [03:13<05:57,  1.72it/s]

[[None, None, 'もう', None], ['少', 'すこ', None, None], [None, None, 'し', None], ['音量', 'おんりょう', None, None], [None, None, 'を', None], ['上', 'あ', None, None], [None, None, 'げて。', None], [None, None, 'そうすると', True], [None, None, 'みんな', None], ['聞', 'き', None, None], [None, None, 'こえるから。', None]]
[[None, None, 'この', None], ['道', 'みち', None, None], [None, None, 'を', None], ['右', 'みぎ', None, None], [None, None, 'に', None], ['曲', 'ま', None, None], [None, None, 'がってください。', None], [None, None, 'そうすると', True], ['案内板', 'あんないばん', None, None], [None, None, 'がありますから。', None]]
[[None, None, 'この', None], ['時刻', 'じこく', None, None], [None, None, 'には', None], ['家', 'いえ', None, None], [None, None, 'を', None], ['出', 'で', None, None], [None, None, 'てください。', None], [None, None, 'そうすると', True], ['間', 'ま', None, None], [None, None, 'に', None], ['合', 'あ', None, None], [None, None, 'いますから。', None]]
[[None, None, 'ちょっと', None], ['右', 'みぎ', None, None], [None, None, 'に', None], ['寄', 'よ', None, None], [None, None, 'ってくれる？', None], [None, None, 'そうすると', True], [None, None, 'みんな', None], ['見', 'み', None, None], [None, None, 'れるから。', None]]
[['新', 'あたら', None, None], [None, None, 'しい', None], ['機械', 'きかい', None, None], [None, None, 'を', None], ['導入', 'どうにゅう', None, None], [None, None, 'するんですね。', None], [None, None, 'そうすると', True], [None, None, '、', None], ['僕', 'ぼく', None, None], [None, None, 'の', None], ['仕事', 'しごと', None, None], [None, None, 'はなくなるということですか？', None]]

 35%|███▍      | 325/938 [03:14<05:51,  1.75it/s]

[['危険', 'きけん', None, None], [None, None, 'なのは', True], [None, None, 'オレ', None], [None, None, 'の', None], ['方', 'ほう', None, None], [None, None, 'だ', None], [None, None, 'よ。', None]]
[['主', 'おも', None, None], [None, None, 'な', None], ['賞', 'しょう', None, None], [None, None, 'を', None], ['受賞', 'じゅしょう', None, None], [None, None, 'する', None], [None, None, 'のは', True], [None, None, 'あちゃん', None], [None, None, 'の', None], ['方', 'ほう', None, None], [None, None, 'だ', None], [None, None, 'といいな。', None]]
[[None, None, 'ドアを', None], ['開', 'あ', None, None], [None, None, 'けっぱなしにした', None], [None, None, 'のは', None], [None, None, 'キちゃん', None], [None, None, 'の', True], ['方', 'ほう', None, True], [None, None, 'だ', True], [None, None, 'と', None], ['思', 'おも', None, None], [None, None, 'う。', None]]
[[None, None, 'あのときサカモトくんを', None], ['誘', 'さそ', None, None], [None, None, 'いたかった', None], [None, None, 'のは', True], [None, None, '、あたし', None], [None, None, 'の', None], ['方', 'ほう', None, None], [None, None, 'だ', None], [None, None, '。', None]]
[[None, None, 'わたしが', None], ['怖', 'こわ', None, None], [None, None, 'い', None], [None, None, 'のは', None], [None, None, '、', None], ['犬', 'いぬ', None, None], [None, None, 'ではなく', None], ['飼', 'か', None, None], [None, None, 'い', None], ['主', 'ぬし', None, None], [None, None, 'の', True], ['方', 'ほう', None, True], [None, None, 'だ', True], [None, None, '。', None]]

 35%|███▍      | 326/938 [03:15<06:07,  1.67it/s]

[['整数', 'せいすう', None, None], [None, None, 'はデータ', None], ['型', 'がた', None, True], [None, None, 'の', None], ['一', 'ひと', None, None], [None, None, 'つである。', None]]
[[None, None, 'きみの', None], ['血液', 'けつえき', None, None], ['型', 'がた', None, True], [None, None, 'は', None], ['何', 'なに', None, None], [None, None, '？', None]]
[[None, None, '「よう」という', None], ['表現', 'ひょうげん', None, None], [None, None, 'はさまざまな', None], ['文', 'ぶん', None, None], ['型', 'けい', None, True], [None, None, 'に', None], ['使', 'つか', None, None], [None, None, 'われている。', None]]
[['君', 'きみ', None, None], [None, None, 'が', None], ['言', 'い', None, None], [None, None, 'った', None], [None, None, 'ように', None], [None, None, '、はるこ', None], [None, None, 'は', None], ['２０００', 'にせん', None, None], ['年', 'ねん', None, None], ['型', 'がた', None, True], [None, None, 'の', None], [None, None, 'モペット', None], [None, None, 'を', None], ['持', 'も', None, None], [None, None, 'っている', None], [None, None, '。', None]]
[['母', 'はは', None, None], [None, None, 'はハート', None], ['型', 'がた', None, True], [None, None, 'の', None], ['枕', 'まくら', None, None], [None, None, 'を', None], ['編', 'あ', None, None], [None, None, 'み', None], ['上', 'あ', None, None], [None, None, 'げた。', None]]

 35%|███▍      | 327/938 [03:15<06:10,  1.65it/s]

[[None, None, 'その', None], ['景色', 'けしき', None, None], [None, None, 'を', None], ['見', 'み', None, True], [None, None, 'てごらん', True], [None, None, '。', None]]
[[None, None, 'ニュースを', None], ['見', 'み', None, True], [None, None, 'てごらん', True], [None, None, '。あなたが', None], ['映', 'うつ', None, None], [None, None, 'っているよ。', None]]
[[None, None, 'あの', None], ['蝶々', 'ちょうちょう', None, None], [None, None, 'を', None], ['捕', 'つか', None, True], [None, None, 'まえてごらんなさい', True], [None, None, '。', None]]
[['手', 'て', None, None], [None, None, 'を', None], ['貸', 'か', None, True], [None, None, 'してごらん', True], [None, None, '。', None], ['手袋', 'てぶくろ', None, None], [None, None, 'をはめてあげるから。', None]]
[[None, None, 'もう', None], ['一度', 'いちど', None, None], [None, None, 'やってごらん', True], [None, None, '。きっとうまくできるよ。', None]]

 35%|███▍      | 328/938 [03:16<06:00,  1.69it/s]

[[None, None, 'あちゃん', None], [None, None, 'との', True], ['握手会', 'あくしゅかい', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'こう！', None]]
[[None, None, 'これ', None], [None, None, 'までの', True], ['話', 'はなし', None, None], [None, None, 'はなかなかおもしろい。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['癌', 'がん', None, None], [None, None, 'との', True], ['戦', 'たたか', None, None], [None, None, 'いに', None], ['勝', 'か', None, None], [None, None, 'ったそうだ。', None]]
[[None, None, 'なぎさんは、はやてさん', None], [None, None, 'への', True], ['手紙', 'てがみ', None, None], [None, None, 'をずっと', None], ['書', 'か', None, None], [None, None, 'いている。', None]]
[[None, None, 'サマーキャンプ', None], [None, None, 'での', True], ['生活', 'せいかつ', None, None], [None, None, 'はとても', None], ['楽', 'たの', None, None], [None, None, 'しいですよ！', None]]

 35%|███▌      | 329/938 [03:17<06:25,  1.58it/s]

[['彼', 'かれ', None, None], [None, None, 'はとてもハンサム', None], [None, None, 'である', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'はパイロット', None], [None, None, 'であった', True], [None, None, '。', None]]
[[None, None, 'とても', None], ['面白', 'おもしろ', None, None], [None, None, 'いドラマ', None], [None, None, 'である', True], [None, None, '。', None]]
[['題名', 'だいめい', None, None], [None, None, '：「', None], ['吾輩', 'わがはい', None, None], [None, None, 'は', None], ['猫', 'ねこ', None, None], [None, None, 'である', True], [None, None, '。」', None]]
[['夢', 'ゆめ', None, None], [None, None, 'は', None], ['海外', 'かいがい', None, None], [None, None, 'で', None], ['成功', 'せいこう', None, None], [None, None, 'すること', None], [None, None, 'である', True], [None, None, '。', None]]

 35%|███▌      | 330/938 [03:17<06:14,  1.62it/s]

[[None, None, 'パンを', None], ['買', 'か', None, None], [None, None, 'いに', None], ['行', 'い', None, None], [None, None, 'きました。', None], [None, None, 'ところが', True], [None, None, '、もう', None], ['売', 'う', None, None], [None, None, 'り', None], ['切', 'き', None, None], [None, None, 'れでした。', None]]
[['日本', 'にほん', None, None], [None, None, 'のチームが', None], ['勝', 'か', None, None], [None, None, 'つと', None], ['思', 'おも', None, None], [None, None, 'っていた。', None], [None, None, 'ところが', True], ['負', 'ま', None, None], [None, None, 'けてしまった。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'は', None], ['非常', 'ひじょう', None, None], [None, None, 'に', None], ['優', 'やさ', None, None], [None, None, 'しそうでした。', None], [None, None, 'ところが', True], [None, None, '、', None], ['裏', 'うら', None, None], [None, None, 'がありました。', None]]
[['友達', 'ともだち', None, None], [None, None, 'によると、テストは', None], ['難', 'むずか', None, None], [None, None, 'しかったそうだ。', None], [None, None, 'ところが', True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'は', None], ['百点', 'ひゃくてん', None, None], [None, None, 'を', None], ['取', 'と', None, None], [None, None, 'った。', None]]
[[None, None, 'テストに', None], ['出', 'で', None, None], [None, None, 'そうなところを', None], ['予想', 'よそう', None, None], [None, None, 'して', None], ['勉強', 'べんきょう', None, None], [None, None, 'した。', None], [None, None, 'ところが', True], [None, None, '、', None], ['全然', 'ぜんぜん', None, None], ['違', 'ちが', None, None], [None, None, 'う', None], ['問題', 'もんだい', None, None], [None, None, 'しか', None], ['出', 'で', None, None], [None, None, 'なかった。', None]]

 35%|███▌      | 331/938 [03:18<06:02,  1.67it/s]

[[None, None, 'ところで', True], [None, None, '、どこに', None], ['行', 'い', None, None], [None, None, 'くつもりですか。', None]]
[[None, None, 'ところで', True], [None, None, '、', None], ['明日', 'あした', None, None], [None, None, 'のパーティーに', None], ['何', 'なに', None, None], [None, None, 'を', None], ['持', 'も', None, None], [None, None, 'って', None], ['来', 'き', None, None], [None, None, 'ますか？', None]]
[[None, None, 'ところで', True], [None, None, '、パソコンの', None], ['使', 'つか', None, None], [None, None, 'い', None], ['方', 'かた', None, None], [None, None, 'をご', None], ['存知', 'ぞんじ', None, None], [None, None, 'ですか。', None]]
[[None, None, 'ところで', True], ['内本', 'うちもと', None, None], [None, None, 'さんはどこ', None], ['出身', 'しゅっしん', None, None], [None, None, '？', None]]
[[None, None, 'ところで', True], [None, None, 'もう', None], ['雨', 'あめ', None, None], [None, None, 'はやみましたか？', None]]

 35%|███▌      | 332/938 [03:18<06:48,  1.48it/s]

[['遅', 'おく', None, None], [None, None, 'れてごめんなさい。あと', None], ['１０分', 'じゅっぷん', None, None], ['程', 'ほど', None, True], [None, None, 'で', None], ['着', 'つ', None, None], [None, None, 'きます。', None]]
[[None, None, 'ピンが', None], ['落', 'お', None, None], [None, None, 'ちた', None], ['音', 'おと', None, None], [None, None, 'が', None], ['聞', 'き', None, None], [None, None, 'こえる', None], ['程', 'ほど', None, True], [None, None, '、', None], ['静', 'しず', None, None], [None, None, 'かだった。', None]]
[[None, None, 'もう', None], ['二度', 'にど', None, None], [None, None, 'と', None], ['食', 'た', None, None], [None, None, 'べたくないと', None], ['思', 'おも', None, None], [None, None, 'う', None], ['程', 'ほど', None, True], [None, None, '、ピザを', None], ['食', 'た', None, None], [None, None, 'べた。', None]]
[['他', 'ほか', None, None], [None, None, 'の', None], ['人', 'ひと', None, None], [None, None, 'がわがままだと', None], ['言', 'い', None, None], [None, None, 'う', None], ['程', 'ほど', None, True], ['甘', 'あま', None, None], [None, None, 'やかしている。', None]]
[['今回', 'こんかい', None, None], [None, None, 'は', None], ['一週間', 'いっしゅうかん', None, None], ['程', 'ほど', None, True], ['旅行', 'りょこう', None, None], [None, None, 'するつもりだ。', None]]

 36%|███▌      | 333/938 [03:19<06:38,  1.52it/s]

[[None, None, 'この', None], ['豆', 'まめ', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べれ', None], [None, None, 'ば', None], ['食', 'た', None, None], [None, None, 'べる', None], [None, None, 'ほど', True], ['痩', 'や', None, None], [None, None, 'せるらしい。', None]]
[['早', 'はや', None, None], [None, None, 'けれ', None], [None, None, 'ば', None], ['早', 'はや', None, None], [None, None, 'い', None], ['程', 'ほど', None, True], [None, None, 'いい。', None]]
[['綺麗', 'きれい', None, True], [None, None, 'ならば', True], ['綺麗', 'きれい', None, None], [None, None, 'な', None], [None, None, 'ほど', None], ['見', 'み', None, None], ['続', 'つづ', None, None], [None, None, 'けたくなる。', None]]
[['勝', 'か', None, True], [None, None, 'てば', True], ['勝', 'か', None, None], [None, None, 'つ', None], [None, None, 'ほど', None], [None, None, '、またやりたくなる。', None]]
[['勉強', 'べんきょう', None, None], [None, None, 'すれ', None], [None, None, 'ば', None], [None, None, 'する', None], ['程', 'ほど', None, True], [None, None, '、', None], ['日本語', 'にほんご', None, None], [None, None, 'が', None], ['上手', 'うま', None, None], [None, None, 'くなる。', None]]

 36%|███▌      | 334/938 [03:20<06:24,  1.57it/s]

[['君', 'きみ', None, None], [None, None, 'の', None], ['母', 'はは', None, None], ['程', 'ほど', None, True], ['優', 'やさ', None, None], [None, None, 'しい', None], ['人', 'ひと', None, None], [None, None, 'はい', None], [None, None, 'ない', None], [None, None, '。', None]]
[['待', 'ま', None, None], [None, None, 'って！あなた', None], [None, None, 'ほど', None], ['速', 'はや', None, None], [None, None, 'く', None], ['走', 'はし', None, True], [None, None, 'れない', True], [None, None, 'んだ！', None]]
[[None, None, 'タイタニック', None], ['程', 'ほど', None, True], ['感動', 'かんどう', None, None], [None, None, 'する', None], ['映画', 'えいが', None, None], [None, None, 'はない', None], [None, None, 'わ。', None]]
[['思', 'おも', None, None], [None, None, 'っていた', None], ['程', 'ほど', None, True], ['大変', 'たいへん', None, None], [None, None, 'な', None], ['仕事', 'しごと', None, None], [None, None, 'では', None], [None, None, 'なかった', None], [None, None, '。', None]]
[['宇宙', 'うちゅう', None, None], [None, None, 'では', None], ['誰', 'だれ', None, None], [None, None, 'もがフリゾ', None], ['程', 'ほど', None, True], ['強', 'つよ', None, None], [None, None, 'く', None], [None, None, 'なかった', None], [None, None, '。', None]]

 36%|███▌      | 335/938 [03:20<06:08,  1.63it/s]

[[None, None, 'じゃあ', True], [None, None, '、ここで', None], ['失礼', 'しつれい', None, None], [None, None, 'します。', None]]
[[None, None, 'では', True], [None, None, '、こうしたらどうでしょう。', None]]
[[None, None, 'では', True], [None, None, '、', None], ['次', 'つぎ', None, None], [None, None, 'の', None], ['問題', 'もんだい', None, None], [None, None, 'です。', None]]
[[None, None, 'じゃあ', True], [None, None, '…', None], ['本', 'ほん', None, None], [None, None, 'を', None], ['取', 'と', None, None], [None, None, 'ってくるから。ちょっと', None], ['待', 'ま', None, None], [None, None, 'ってて。', None]]
[[None, None, 'では', True], [None, None, '、また', None], ['来週', 'らいしゅう', None, None], [None, None, 'の', None], ['火曜日', 'かようび', None, None], [None, None, 'に', None], ['会', 'あ', None, None], [None, None, 'いましょう。', None]]

 36%|███▌      | 336/938 [03:21<05:58,  1.68it/s]

[['本', 'ほん', None, None], [None, None, 'を', None], ['読', 'よ', None, None], [None, None, 'む', None], [None, None, 'のに', True], ['眼鏡', 'めがね', None, None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'った。', None]]
[['背中', 'せなか', None, None], [None, None, 'をかく', None], [None, None, 'のに', True], ['孫', 'まご', None, None], [None, None, 'の', None], ['手', 'て', None, None], [None, None, 'を', None], ['使', 'つか', None, None], [None, None, 'う。', None]]
[['宿題', 'しゅくだい', None, None], [None, None, 'をする', None], [None, None, 'のに', True], [None, None, '、', None], ['３', 'さん', None, None], ['時間', 'じかん', None, None], [None, None, 'かかる。', None]]
[['食', 'た', None, None], [None, None, 'べる', None], [None, None, 'のに', True], ['時間', 'じかん', None, None], [None, None, 'がかかりすぎて、', None], ['昼', 'ひる', None, None], ['休', 'やす', None, None], [None, None, 'みが', None], ['終', 'お', None, None], [None, None, 'わってしまった。', None]]
[[None, None, 'お', None], ['茶', 'ちゃ', None, None], [None, None, 'を', None], ['飲', 'の', None, None], [None, None, 'む', None], [None, None, 'のに', True], ['必要', 'ひつよう', None, None], [None, None, 'なコップがありません。', None]]

 36%|███▌      | 337/938 [03:21<05:56,  1.69it/s]

[['家', 'いえ', None, None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'う', None], ['為', 'ため', None, True], [None, None, 'に', True], [None, None, 'ローンを', None], ['組', 'く', None, None], [None, None, 'んだ。', None]]
[['僕', 'ぼく', None, None], [None, None, 'はただいい', None], ['点', 'てん', None, None], [None, None, 'を', None], ['取', 'と', None, None], [None, None, 'る', None], ['為', 'ため', None, True], [None, None, 'に', True], ['勉強', 'べんきょう', None, None], [None, None, 'していません。', None]]
[['何', 'なん', None, None], [None, None, 'の', True], ['為', 'ため', None, True], [None, None, 'に', True], ['生', 'い', None, None], [None, None, 'きているのか、それが', None], ['知', 'し', None, None], [None, None, 'りたい。', None]]
[[None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'の', True], ['為', 'ため', None, True], [None, None, 'だけに', None], ['仕事', 'しごと', None, None], [None, None, 'をするのは、つらいです。', None]]
[['老後', 'ろうご', None, None], [None, None, 'の', True], ['為', 'ため', None, True], [None, None, 'に', True], [None, None, 'ちゃんと', None], ['貯金', 'ちょきん', None, None], [None, None, 'しておかなければならない。', None]]

 36%|███▌      | 338/938 [03:22<06:27,  1.55it/s]

[['夜更', 'よふ', None, None], [None, None, 'かしした', None], ['為', 'ため', None, True], ['朝', 'あさ', None, None], ['寝坊', 'ねぼう', None, None], [None, None, 'してしまった。', None]]
[['台風', 'たいふう', None, None], [None, None, 'の', True], ['為', 'ため', None, True], [None, None, '、', None], ['試合', 'しあい', None, None], [None, None, 'が', None], ['中止', 'ちゅうし', None, None], [None, None, 'になった。', None]]
[[None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'を', None], ['使', 'つか', None, None], [None, None, 'いすぎた', None], ['為', 'ため', None, True], [None, None, 'に', True], [None, None, '、', None], ['貯金', 'ちょきん', None, None], [None, None, 'がもうほとんどない。', None]]
[['寒', 'さむ', None, None], [None, None, 'い', None], ['為', 'ため', None, True], [None, None, 'に', True], [None, None, '、', None], ['車', 'くるま', None, None], [None, None, 'が', None], ['故障', 'こしょう', None, None], [None, None, 'してしまった。', None]]
[['寒', 'さむ', None, None], [None, None, 'さ', None], [None, None, 'の', True], ['為', 'ため', None, True], [None, None, 'に', True], [None, None, '、', None], ['車', 'くるま', None, None], [None, None, 'が', None], ['故障', 'こしょう', None, None], [None, None, 'してしまった。', None]]

 36%|███▌      | 339/938 [03:23<06:15,  1.60it/s]

[[None, None, 'ポケモン', None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'う', True], [None, None, 'ゲームを', None], ['知', 'し', None, None], [None, None, 'っている？', None]]
[['今', 'いま', None, None], [None, None, 'は', None], ['梅雨', 'つゆ', None, None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'う', True], ['時期', 'じき', None, None], [None, None, 'です。', None]]
[[None, None, 'スマホ', None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'う', True], [None, None, 'ものは', None], ['便利', 'べんり', None, None], [None, None, 'なものだね。', None]]
[['秋', 'あき', None, None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'う', True], ['季節', 'きせつ', None, None], [None, None, 'が', None], ['大好', 'だいす', None, None], [None, None, 'きだ。', None]]
[['佐藤', 'さとう', None, None], ['浩一', 'こういち', None, None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'う', True], ['人', 'ひと', None, None], [None, None, 'を', None], ['知', 'し', None, None], [None, None, 'っていますか？', None]]

 36%|███▌      | 340/938 [03:23<06:04,  1.64it/s]

[['人', 'ひと', None, None], [None, None, 'によって', None], ['考', 'かんが', None, None], [None, None, 'え', None], ['方', 'かた', None, None], [None, None, 'が', None], ['違', 'ちが', None, None], [None, None, 'う', None], [None, None, 'という', True], ['事', 'こと', None, True], [None, None, 'だ', True], [None, None, '。', None]]
[[None, None, 'イルカは', None], ['動物', 'どうぶつ', None, None], [None, None, 'の', None], ['中', 'なか', None, None], [None, None, 'で', None], ['頭', 'あたま', None, None], [None, None, 'が', None], ['一番', 'いちばん', None, None], [None, None, 'いい', None], [None, None, 'という', True], ['事', 'こと', None, True], [None, None, 'だ', True], [None, None, '。', None]]
[[None, None, 'それはただ', None], ['文化', 'ぶんか', None, None], [None, None, 'が', None], ['違', 'ちが', None, None], [None, None, 'う', None], [None, None, 'という', True], ['事', 'こと', None, True], [None, None, 'だ', True], [None, None, '。', None]]
[['田中', 'たなか', None, None], [None, None, 'さんと', None], ['山田', 'やまだ', None, None], [None, None, 'さんは、', None], ['秘密', 'ひみつ', None, None], [None, None, 'で', None], ['付', 'つ', None, None], [None, None, 'き', None], ['合', 'あ', None, None], [None, None, 'っている', None], [None, None, 'という', True], ['事', 'こと', None, True], [None, None, 'だ', True], [None, None, '。', None]]
[['忍耐', 'にんたい', None, None], ['先生', 'せんせい', None, None], [None, None, 'によりますと、ガンの', None], ['治療', 'ちりょう', None, None], ['方法', 'ほうほう', None, None], [None, None, 'がとうとう', None], ['見', 'み', None, None], [None, None, 'つかった', None], [None, None, 'という', True], ['事', 'こと', None, True], [None, None, 'です', True], [None, None, '。', None]]

 36%|███▋      | 341/938 [03:24<06:02,  1.65it/s]

[['雪', 'ゆき', None, None], [None, None, 'というのは', True], [None, None, '、', None], ['自然', 'しぜん', None, None], ['現象', 'げんしょう', None, None], [None, None, 'です。', None]]
[['人生', 'じんせい', None, None], [None, None, 'というのは', True], ['儚', 'はかな', None, None], [None, None, 'いものだな。', None]]
[['働', 'はたら', None, None], [None, None, 'く', None], [None, None, 'というのは', True], ['大変', 'たいへん', None, None], [None, None, 'なことだ。', None]]
[['子供', 'こども', None, None], [None, None, 'というのは', True], [None, None, 'かわいいものだな。', None]]
[['習慣', 'しゅうかん', None, None], [None, None, 'というのは', True], ['恐', 'おそ', None, None], [None, None, 'ろしいものだ。', None]]

 36%|███▋      | 342/938 [03:24<05:53,  1.69it/s]

[['印象', 'いんしょう', None, None], ['的', 'てき', None, True], [None, None, 'な', True], ['絵', 'え', None, None], [None, None, '。', None]]
[['一般', 'いっぱん', None, None], ['的', 'てき', None, True], [None, None, 'な', True], ['考', 'かんが', None, None], [None, None, 'え', None], ['方', 'かた', None, None], [None, None, '。', None]]
[['一時', 'いちじ', None, None], ['的', 'てき', None, True], [None, None, 'な', True], ['大雨', 'おおあめ', None, None], [None, None, '。', None]]
[['悪魔', 'あくま', None, None], ['的', 'てき', None, True], [None, None, 'な', True], ['手口', 'てぐち', None, None], [None, None, '。', None]]
[['時期', 'じき', None, None], ['的', 'てき', None, True], [None, None, 'に', True], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'りやすい。', None]]

 37%|███▋      | 343/938 [03:25<05:47,  1.71it/s]

[[None, None, 'まずい', None], [None, None, 'んだもん', True], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['嘘', 'うそ', None, None], [None, None, 'をついている', None], [None, None, 'もの', True], [None, None, '。', None]]
[['怒', 'おこ', None, None], [None, None, 'らないでね。', None], ['子供', 'こども', None, None], [None, None, 'なんだもん', True], [None, None, '。', None]]
[['寒', 'さむ', None, None], [None, None, 'い', None], [None, None, 'んだ', None], [None, None, 'もん', True], [None, None, '。', None], ['風邪', 'かぜ', None, None], [None, None, 'をひいてしまうよ。', None]]
[[None, None, '「', None], ['食', 'た', None, None], [None, None, 'べすぎ！」って', None], ['言', 'い', None, None], [None, None, 'われても…、', None], ['美味', 'おい', None, None], [None, None, 'しい', None], [None, None, 'んだ', None], [None, None, 'もん', True], [None, None, '！', None]]

 37%|███▋      | 344/938 [03:26<05:47,  1.71it/s]

[[None, None, 'ケーキは', None], ['甘', 'あま', None, None], [None, None, 'い', None], ['物', 'もの', None, True], [None, None, 'だ。', None]]
[['親', 'おや', None, None], [None, None, 'は', None], ['親切', 'しんせつ', None, None], [None, None, 'な', True], ['物', 'もの', None, True], [None, None, 'だ。', None]]
[['食', 'た', None, None], [None, None, 'べ', None], ['物', 'もの', None, None], [None, None, 'はムダにする', None], ['物', 'もの', None, True], [None, None, 'じゃない', True], [None, None, 'よ！', None]]
[['悪', 'わる', None, None], [None, None, 'いことは', None], ['続', 'つづ', None, None], [None, None, 'く', None], ['物', 'もの', None, True], [None, None, 'だ', True], [None, None, '。', None]]
[['子供', 'こども', None, None], [None, None, 'は', None], ['父母', 'ちちはは', None, None], [None, None, 'の', None], ['言', 'い', None, None], [None, None, 'うことを', None], ['聞', 'き', None, None], [None, None, 'く', None], ['物', 'もの', None, True], [None, None, 'だ', True], [None, None, '。', None]]

 37%|███▋      | 345/938 [03:26<05:38,  1.75it/s]

[[None, None, 'それについては', None], ['考', 'かんが', None, None], [None, None, 'え', None], [None, None, 'ている', None], ['最中', 'さいちゅう', None, True], [None, None, 'です。', None]]
[['朝', 'あさ', None, None], [None, None, 'の', None], ['散歩', 'さんぽ', None, None], [None, None, 'の', True], ['最中', 'さいちゅう', None, True], [None, None, 'に', True], [None, None, '、', None], ['犬', 'いぬ', None, None], [None, None, 'に', None], ['噛', 'か', None, None], [None, None, 'まれた。', None]]
[['寝', 'ね', None, None], [None, None, 'ている', None], ['最中', 'さいちゅう', None, True], [None, None, 'に', True], ['声', 'こえ', None, None], [None, None, 'をかけるのはやめてほしい。', None]]
[[None, None, 'テスト', None], [None, None, 'の', True], ['最中', 'さいちゅう', None, True], [None, None, 'に', True], ['眠', 'ねむ', None, None], [None, None, 'ってしまった。', None]]
[['話', 'はな', None, None], [None, None, 'し', None], [None, None, 'ている', None], ['最中', 'さいちゅう', None, True], [None, None, 'に', True], ['邪魔', 'じゃま', None, None], [None, None, 'をするのはやめてほしい。', None]]

 37%|███▋      | 346/938 [03:27<05:33,  1.77it/s]

[['家', 'いえ', None, None], [None, None, 'の', None], ['中', 'なか', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'た', None], ['上', 'うえ', None, True], [None, None, 'で', True], [None, None, '、', None], ['買', 'か', None, None], [None, None, 'おうと', None], ['思', 'おも', None, None], [None, None, 'っている。', None]]
[['説明書', 'せつめいしょ', None, None], [None, None, 'を', None], ['読', 'よ', None, None], [None, None, 'んだ', None], ['上', 'うえ', None, True], [None, None, 'で', True], [None, None, '、ご', None], ['使用', 'しよう', None, None], [None, None, 'ください。', None]]
[['変更', 'へんこう', None, None], [None, None, 'した', None], ['上', 'うえ', None, True], [None, None, 'で', True], [None, None, '、', None], ['間違', 'まちが', None, None], [None, None, 'いがあるかどうか', None], ['確認', 'かくにん', None, None], [None, None, 'するべきだ。', None]]
[[None, None, ' ', None], ['妻', 'つま', None, None], [None, None, 'と', None], ['相談', 'そうだん', None, None], [None, None, 'した', None], ['上', 'うえ', None, True], [None, None, 'で', True], [None, None, '、', None], ['手術', 'しゅじゅつ', None, None], [None, None, 'を', None], ['受', 'う', None, None], [None, None, 'けることを', None], ['決', 'き', None, None], [None, None, 'めたいと', None], ['思', 'おも', None, None], [None, None, 'う。', None]]
[['慎重', 'しんちょう', None, None], [None, None, 'な', None], ['調査', 'ちょうさ', None, None], [None, None, 'の', True], ['上', 'うえ', None, True], [None, None, 'で', True], [None, None, '、', None], ['被告', 'ひこく', None, None], [None, None, 'は', None], ['有罪', 'ゆうざい', None, None], [None, None, 'と', None], ['決定', 'けってい', None, None], [None, None, 'しました。', None]]

 37%|███▋      | 347/938 [03:27<05:31,  1.78it/s]

[['薬', 'くすり', None, None], [None, None, 'のお', True], ['陰', 'かげ', None, True], [None, None, 'で', True], [None, None, 'だいぶよくなりました。', None]]
[[None, None, ' ', None], ['風', 'かぜ', None, None], [None, None, 'が', None], ['強', 'つよ', None, None], [None, None, 'い', None], [None, None, 'お', True], ['陰', 'かげ', None, True], [None, None, 'で', True], [None, None, '、ヨットのスピードが', None], ['上', 'あ', None, None], [None, None, 'がった。', None]]
[[None, None, 'お', True], ['陰', 'かげ', None, True], [None, None, 'で', True], ['助', 'たす', None, None], [None, None, 'かったよ。', None], ['来', 'き', None, None], [None, None, 'てくれてありがとう。', None]]
[[None, None, 'スマホ', None], [None, None, 'のお', True], ['陰', 'かげ', None, True], [None, None, 'で', True], [None, None, '、', None], ['目的地', 'もくてきち', None, None], [None, None, 'にスムーズに', None], ['着', 'つ', None, None], [None, None, 'きました。', None]]
[['君', 'きみ', None, None], [None, None, 'のお', True], ['陰', 'かげ', None, True], [None, None, 'で', True], ['取引', 'とりひき', None, None], [None, None, 'は', None], ['失敗', 'しっぱい', None, None], [None, None, 'だったよ。', None]]

 37%|███▋      | 348/938 [03:28<05:30,  1.79it/s]

[['信用', 'しんよう', None, None], [None, None, 'に', True], ['基', 'もと', None, True], [None, None, 'づいて', True], [None, None, '、お', None], ['金', 'かね', None, None], [None, None, 'を', None], ['貸', 'か', None, None], [None, None, 'す。', None]]
[['法律', 'ほうりつ', None, None], [None, None, 'に', True], ['基', 'もと', None, True], [None, None, 'づいて', True], [None, None, '、', None], ['判断', 'はんだん', None, None], [None, None, 'させていただきます。', None]]
[[None, None, 'ちゃんと', None], ['計画', 'けいかく', None, None], [None, None, 'に', True], ['基', 'もと', None, True], [None, None, 'づいて', True], [None, None, '、', None], ['動', 'うご', None, None], [None, None, 'いてください。', None]]
[[None, None, 'あなたの', None], ['意見', 'いけん', None, None], [None, None, 'に', True], ['基', 'もと', None, True], [None, None, 'づいて', True], [None, None, '、', None], ['変更', 'へんこう', None, None], [None, None, 'を', None], ['加', 'くわ', None, None], [None, None, 'えました。', None]]
[['間違', 'まちが', None, None], [None, None, 'った', None], ['前提', 'ぜんてい', None, None], [None, None, 'に', True], ['基', 'もと', None, True], [None, None, 'づいている', True], [None, None, 'から、', None], ['当然', 'とうぜん', None, None], ['結果', 'けっか', None, None], [None, None, 'も', None], ['間違', 'まちが', None, None], [None, None, 'っている。', None]]

 37%|███▋      | 349/938 [03:28<05:24,  1.81it/s]

[[None, None, 'この', None], ['点', 'てん', None, True], [None, None, 'で', True], [None, None, 'そのスマホの', None], ['方', 'ほう', None, None], [None, None, 'がいいですよ。', None]]
[['英語', 'えいご', None, None], [None, None, 'は', None], [None, None, 'あらゆる', None], ['点', 'てん', None, True], [None, None, 'で', True], ['日本語', 'にほんご', None, None], [None, None, 'と', None], ['違', 'ちが', None, None], [None, None, 'っている。', None]]
[['何', 'なん', None, None], [None, None, 'らかのアクションが', None], ['必要', 'ひつよう', None, None], [None, None, 'である', None], [None, None, 'という', True], ['点', 'てん', None, True], [None, None, 'を', None], ['総', 'そう', None, None], ['株主', 'かぶぬし', None, None], [None, None, 'は', None], ['認', 'みと', None, None], [None, None, 'めた。', None]]
[[None, None, 'いくつか', None], [None, None, 'の', True], ['点', 'てん', None, True], [None, None, 'で', True], ['韓国語', 'かんこくご', None, None], [None, None, 'やトルコ', None], ['語', 'ご', None, None], [None, None, 'は', None], ['日本語', 'にほんご', None, None], [None, None, 'に', None], ['似', 'に', None, None], [None, None, 'ている。', None]]
[['彼', 'かれ', None, None], [None, None, 'はちょっと', None], ['忘', 'わす', None, None], [None, None, 'れっぽい', None], [None, None, 'という', True], ['点', 'てん', None, True], [None, None, 'で', True], ['彼', 'かれ', None, None], [None, None, 'の', None], ['父', 'ちち', None, None], [None, None, 'と', None], ['同', 'おな', None, None], [None, None, 'じだね。', None]]

 37%|███▋      | 350/938 [03:29<05:21,  1.83it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], ['泳', 'およ', None, None], [None, None, 'ぎに', None], ['行', 'い', None, None], [None, None, 'けなかった。', None], [None, None, 'なぜなら', True], [None, None, '、', None], ['寒', 'さむ', None, None], [None, None, 'かった', None], [None, None, 'から', None], [None, None, '。', None]]
[[None, None, 'すみませんが、', None], ['正直', 'しょうじき', None, None], [None, None, 'に', None], ['言', 'い', None, None], [None, None, 'えないんです。', None], [None, None, 'なぜなら', True], [None, None, '、', None], ['秘密', 'ひみつ', None, None], [None, None, 'だ', None], [None, None, 'から', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'らは', None], ['来', 'く', None, None], [None, None, 'るかどうかわからない。', None], [None, None, 'なぜなら', True], [None, None, '、まだ', None], ['連絡', 'れんらく', None, None], [None, None, 'がきていない', None], [None, None, 'から', None], [None, None, 'です。', None]]
[[None, None, 'もうすぐ', None], ['会', 'あ', None, None], [None, None, 'えます。', None], [None, None, 'なぜなら', True], [None, None, '、', None], ['今度', 'こんど', None, None], ['僕', 'ぼく', None, None], [None, None, 'は', None], ['日本', 'にほん', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'から', None], [None, None, '。', None]]
[['今日', 'きょう', None, None], [None, None, 'は', None], ['仕事', 'しごと', None, None], [None, None, 'を', None], ['休', 'やす', None, None], [None, None, 'みました。', None], [None, None, 'なぜなら', True], [None, None, '、インフルエンザにかかってしまった', None], [None, None, 'から', None], [None, None, 'です。', None]]

 37%|███▋      | 351/938 [03:30<05:31,  1.77it/s]

[[None, None, 'あなた', None], [None, None, 'こそ', True], [None, None, 'リーダーにふさわしい！', None]]
[['今度', 'こんど', None, None], [None, None, 'こそ', True], ['達成', 'たっせい', None, None], [None, None, 'してみせる！', None]]
[['誰', 'だれ', None, None], [None, None, 'かが「', None], ['愛', 'あい', None, None], [None, None, 'こそ', True], [None, None, 'すべてだ」って', None], ['言', 'い', None, None], [None, None, 'っていました。', None]]
[['困', 'こま', None, None], [None, None, 'った', None], ['時', 'とき', None, None], [None, None, 'こそ', True], [None, None, 'の', None], ['友達', 'ともだち', None, None], [None, None, 'じゃないか。', None]]
[[None, None, 'そんな', None], ['時', 'とき', None, None], [None, None, 'こそ', True], ['僕', 'ぼく', None, None], [None, None, 'の', None], ['出番', 'でばん', None, None], [None, None, 'だ！', None]]

 38%|███▊      | 352/938 [03:30<05:34,  1.75it/s]

[[None, None, 'あなたがいる', None], [None, None, 'からこそ', True], [None, None, '、', None], ['安心', 'あんしん', None, None], [None, None, 'できるんです。', None]]
[['仲間', 'なかま', None, None], [None, None, 'がいる', None], [None, None, 'からこそ', True], [None, None, '、', None], ['頑張', 'がんば', None, None], [None, None, 'れる。', None]]
[['難', 'むずか', None, None], [None, None, 'しい', None], ['状況', 'じょうきょう', None, None], [None, None, 'だからこそ', True], ['生', 'う', None, None], [None, None, 'まれるアイデアもある。', None]]
[['君', 'きみ', None, None], [None, None, 'が', None], ['励', 'はげ', None, None], [None, None, 'ましてくれた', None], [None, None, 'からこそ', True], [None, None, '、ここまでやってこれたんだ。', None]]
[['毎日', 'まいにち', None, None], ['努力', 'どりょく', None, None], [None, None, 'をした', None], [None, None, 'からこそ', True], [None, None, '、', None], ['一番', 'いちばん', None, None], [None, None, 'になれた。', None]]

 38%|███▊      | 353/938 [03:31<05:30,  1.77it/s]

[['彼', 'かれ', None, None], [None, None, 'はいつも', None], ['嘘', 'うそ', None, None], [None, None, 'ばかり', True], ['言', 'い', None, None], [None, None, 'っている。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['弟', 'おとうと', None, None], [None, None, 'はゲームを', None], [None, None, 'してばかり', True], [None, None, 'ですよ。', None]]
[['知', 'し', None, None], [None, None, 'らない', None], ['顔', 'かお', None, None], [None, None, 'ばかり', True], [None, None, 'だから', None], ['緊張', 'きんちょう', None, None], [None, None, 'する。', None]]
[['甘', 'あま', None, None], [None, None, 'い', None], ['物', 'もの', None, None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べてばかり', True], [None, None, 'いると、', None], ['虫歯', 'むしば', None, None], [None, None, 'が', None], ['増', 'ふ', None, None], [None, None, 'える。', None]]
[[None, None, 'いつも', None], [None, None, 'もらってばかり', True], [None, None, 'ですみません。', None]]

 38%|███▊      | 354/938 [03:31<05:28,  1.78it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], ['傲慢', 'ごうまん', None, None], [None, None, 'になる', None], [None, None, 'ばかりだ', True], [None, None, '。', None]]
[[None, None, 'おじいさんの', None], ['健康', 'けんこう', None, None], [None, None, 'が', None], ['衰', 'おとろ', None, None], [None, None, 'える', None], [None, None, 'ばかりだ', True], [None, None, '。', None]]
[['最近', 'さいきん', None, None], [None, None, '、ビットコインの', None], ['価値', 'かち', None, None], [None, None, 'が', None], ['下', 'さ', None, None], [None, None, 'がる', None], [None, None, 'ばかりだ', True], [None, None, '。', None]]
[['癌', 'がん', None, None], [None, None, 'のため、', None], ['体', 'からだ', None, None], [None, None, 'が', None], ['弱', 'よわ', None, None], [None, None, 'っていく', None], [None, None, 'ばかり', True], [None, None, 'です。', None]]
[['夏休', 'なつやす', None, None], [None, None, 'みになってから、', None], ['日本語', 'にほんご', None, None], [None, None, 'を', None], ['忘', 'わす', None, None], [None, None, 'れていく', None], [None, None, 'ばかり', True], [None, None, 'だ。', None]]

 38%|███▊      | 355/938 [03:32<05:31,  1.76it/s]

[['財布', 'さいふ', None, None], [None, None, 'を', None], ['忘', 'わす', None, None], [None, None, 'れた', None], [None, None, 'ばかりに', True], [None, None, '、お', None], ['弁当', 'べんとう', None, None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'えなかった。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['驚', 'おどろ', None, None], [None, None, 'かされた', None], [None, None, 'ばかりに', True], [None, None, '、', None], ['気', 'き', None, None], [None, None, 'を', None], ['失', 'うしな', None, None], [None, None, 'ってしまった。', None]]
[['恋人', 'こいびと', None, None], [None, None, 'に', None], ['会', 'あ', None, None], [None, None, 'いたい', None], [None, None, 'ばかりに', True], [None, None, '、インドネシアに', None], ['旅行', 'りょこう', None, None], [None, None, 'した。', None]]
[['良', 'い', None, None], [None, None, 'いリーダーがいなかった', None], [None, None, 'ばかりに', True], [None, None, '、チームは', None], ['試合', 'しあい', None, None], [None, None, 'に', None], ['負', 'ま', None, None], [None, None, 'けた。', None]]
[['点検', 'てんけん', None, None], [None, None, 'を', None], ['怠', 'おこた', None, None], [None, None, 'っていた', None], [None, None, 'ばかりに', True], [None, None, '、タコマナローズ', None], ['橋', 'はし', None, None], [None, None, 'は', None], ['崩壊', 'ほうかい', None, None], [None, None, 'した。', None]]

 38%|███▊      | 356/938 [03:32<05:28,  1.77it/s]

[['頑張', 'がんば', None, None], [None, None, 'ってもうまくいかない', None], ['事', 'こと', None, True], [None, None, 'がある', True], [None, None, '。', None]]
[['学校', 'がっこう', None, None], [None, None, 'に', None], ['送', 'おく', None, None], [None, None, 'ってもらう', None], ['事', 'こと', None, True], [None, None, 'がある', True], [None, None, '。', None]]
[['友達', 'ともだち', None, None], [None, None, 'は', None], ['昼', 'ひる', None, None], ['２時', 'にじ', None, None], [None, None, 'まで', None], ['寝', 'ね', None, None], [None, None, 'る', None], ['事', 'こと', None, True], [None, None, 'がある', True], [None, None, '。', None]]
[[None, None, 'あの', None], ['番組', 'ばんぐみ', None, None], [None, None, 'ならたまに', None], ['見', 'み', None, None], [None, None, 'る', None], ['事', 'こと', None, True], [None, None, 'がある', True], [None, None, '。', None]]
[['一日', 'いちにち', None, None], [None, None, 'に', None], ['二', 'に', None, None], [None, None, '、', None], ['三回', 'さんかい', None, None], [None, None, 'ぐらい、ラーメンを', None], ['食', 'た', None, None], [None, None, 'べる', None], ['事', 'こと', None, True], [None, None, 'がある', True], [None, None, '。', None]]

 38%|███▊      | 357/938 [03:33<05:32,  1.75it/s]

[['今日', 'きょう', None, None], [None, None, 'はエイプリルフールだからウソしか', None], ['言', 'い', None, None], [None, None, 'わない', None], ['事', 'こと', None, True], [None, None, 'にする', True], [None, None, '。', None]]
[[None, None, 'あの', None], ['場所', 'ばしょ', None, None], [None, None, 'で、', None], ['記念', 'きねん', None, None], ['写真', 'しゃしん', None, None], [None, None, 'を', None], ['撮', 'と', None, None], [None, None, 'る', None], ['事', 'こと', None, True], [None, None, 'にします', True], [None, None, '。', None]]
[['九', 'く', None, None], ['時', 'じ', None, None], [None, None, 'に', None], ['終', 'お', None, None], [None, None, 'わるか', None], ['分', 'わ', None, None], [None, None, 'からなかったが、', None], ['早', 'はや', None, None], [None, None, 'めに', None], ['帰', 'かえ', None, None], [None, None, 'る', None], ['事', 'こと', None, True], [None, None, 'にしました', True], [None, None, '。', None]]
[[None, None, 'これ', None], ['以上', 'いじょう', None, None], ['言', 'い', None, None], [None, None, 'わない', None], ['事', 'こと', None, True], [None, None, 'にします', True], [None, None, '。もし', None], ['何', 'なに', None, None], [None, None, 'か', None], ['言', 'い', None, None], [None, None, 'ったら', None], ['彼女', 'かのじょ', None, None], [None, None, 'を', None], ['怒', 'おこ', None, None], [None, None, 'らせるでしょう。', None]]
[[None, None, 'この', None], ['商品', 'しょうひん', None, None], [None, None, '、', None], ['無料', 'むりょう', None, None], [None, None, 'で', None], ['配', 'くば', None, None], [None, None, 'る', None], ['事', 'こと', None, True], [None, None, 'にします', True], [None, None, '。', None]]

 38%|███▊      | 358/938 [03:34<05:43,  1.69it/s]

[[None, None, 'ハダウェイ：「', None], ['恋愛', 'れんあい', None, None], [None, None, 'とはどういう', None], ['事', 'こと', None, True], [None, None, 'なの', True], [None, None, 'だろうか。」', None]]
[[None, None, 'つまり、その', None], ['病気', 'びょうき', None, None], [None, None, 'が', None], ['感染症', 'かんせんしょう', None, None], [None, None, 'ではない', None], [None, None, 'という', True], ['事', 'こと', None, True], [None, None, 'なの', True], [None, None, 'である。', None]]
[[None, None, 'チーターのように', None], ['走', 'はし', None, None], [None, None, 'るとは', None], ['足', 'あし', None, None], [None, None, 'が', None], ['速', 'はや', None, None], [None, None, 'い', None], [None, None, 'という', True], ['事', 'こと', None, True], [None, None, 'なの', True], [None, None, 'だ。', None]]
[[None, None, '「ザクシャ・イン・ラブ」とは「', None], ['愛', 'あい', None, None], [None, None, 'を', None], ['永遠', 'えいえん', None, None], [None, None, 'に」', None], [None, None, 'という', True], ['事', 'こと', None, True], [None, None, 'なの', True], [None, None, 'だ。', None]]
[['頭', 'あたま', None, None], [None, None, 'が', None], ['切', 'き', None, None], [None, None, 'れる', None], [None, None, 'という', None], [None, None, 'のは', None], ['頭', 'あたま', None, None], [None, None, 'がいい', None], ['事', 'こと', None, True], [None, None, 'なの', True], [None, None, 'だ。', None]]

 38%|███▊      | 359/938 [03:34<05:48,  1.66it/s]

[[None, None, 'どうしてこんな', None], ['事', 'こと', None, True], [None, None, 'になった', True], [None, None, 'の？', None], ['意味', 'いみ', None, None], [None, None, 'がわからないよ。', None]]
[['大変', 'たいへん', None, None], [None, None, 'な', True], ['事', 'こと', None, True], [None, None, 'になった', True], [None, None, 'ぞ。', None], ['何', 'なに', None, None], [None, None, 'か', None], ['作戦', 'さくせん', None, None], [None, None, 'を', None], ['考', 'かんが', None, None], [None, None, 'えなければ。', None]]
[['私', 'わたし', None, None], [None, None, 'が', None], ['会議', 'かいぎ', None, None], [None, None, 'に', None], ['出', 'で', None, None], [None, None, 'る', None], ['事', 'こと', None, True], [None, None, 'になった', True], [None, None, '。', None]]
[['連絡', 'れんらく', None, None], [None, None, 'がなければ、', None], ['僕', 'ぼく', None, None], [None, None, 'が', None], ['仕事', 'しごと', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'く', None], ['事', 'こと', None, True], [None, None, 'になります', True], [None, None, '。', None]]
[['困', 'こま', None, None], [None, None, 'った', None], ['事', 'こと', None, True], [None, None, 'になった', True], [None, None, 'な。もう', None], ['電池', 'でんち', None, None], [None, None, 'が', None], ['切', 'き', None, None], [None, None, 'れそうだ。', None]]

 38%|███▊      | 360/938 [03:35<05:49,  1.66it/s]

[['札幌', 'さっぽろ', None, None], [None, None, 'は', None], ['雪', 'ゆき', None, None], [None, None, 'まつり', None], [None, None, 'で', True], ['有名', 'ゆうめい', None, True], [None, None, 'です。', None]]
[['大間', 'おおま', None, None], [None, None, 'は', None], [None, None, 'マグロ', None], [None, None, 'で', True], ['有名', 'ゆうめい', None, True], [None, None, 'だ。', None]]
[[None, None, 'あの', None], ['先生', 'せんせい', None, None], [None, None, 'は', None], ['授業', 'じゅぎょう', None, None], [None, None, 'がおもしろい', None], [None, None, 'ことで', True], ['有名', 'ゆうめい', None, True], [None, None, 'です。', None]]
[[None, None, 'このうどん', None], [None, None, 'は', None], [None, None, 'コシが', None], ['強', 'つよ', None, None], [None, None, 'い', None], [None, None, 'ことで', True], ['有名', 'ゆうめい', None, True], [None, None, 'だ。', None]]
[[None, None, 'この', None], ['町', 'まち', None, None], [None, None, 'は', None], ['温泉', 'おんせん', None, None], [None, None, 'で', True], ['有名', 'ゆうめい', None, True], [None, None, 'です。', None]]

 38%|███▊      | 361/938 [03:36<06:23,  1.51it/s]

[[None, None, 'そんな', None], ['急', 'いそ', None, None], [None, None, 'ぐ', None], ['事', 'こと', None, True], [None, None, 'はない', True], [None, None, '。ぼちぼちやればいい。', None]]
[[None, None, 'もうあの', None], ['家', 'いえ', None, None], [None, None, 'に', None], ['帰', 'かえ', None, None], [None, None, 'る', None], ['事', 'こと', None, True], [None, None, 'はない', True], [None, None, 'だろう。', None]]
[[None, None, 'もう', None], ['彼', 'かれ', None, None], [None, None, 'に', None], ['教', 'おし', None, None], [None, None, 'える', None], ['事', 'こと', None, True], [None, None, 'はありません', True], [None, None, '。', None]]
[[None, None, 'これ', None], ['以上', 'いじょう', None, None], ['何', 'なに', None, None], [None, None, 'も', None], ['言', 'い', None, None], [None, None, 'う', None], ['事', 'こと', None, True], [None, None, 'はない', True], [None, None, '。', None]]
[[None, None, 'この', None], ['抽選', 'ちゅうせん', None, None], [None, None, 'で', None], ['車', 'くるま', None, None], [None, None, 'が', None], ['当', 'あ', None, None], [None, None, 'たる', None], ['事', 'こと', None, True], [None, None, 'はない', True], [None, None, 'と', None], ['思', 'おも', None, None], [None, None, 'う。', None]]

 39%|███▊      | 362/938 [03:36<06:02,  1.59it/s]

[[None, None, 'プレゼント', None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'っても', True], [None, None, '、たいしたものはない。', None]]
[[None, None, 'あなたは', None], ['天才', 'てんさい', None, None], [None, None, 'だ', None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'っても', True], ['過言', 'かごん', None, None], [None, None, 'ではない。', None]]
[['先生', 'せんせい', None, None], [None, None, 'って', True], ['言', 'い', None, True], [None, None, 'っても', True], [None, None, '、いろんな', None], ['人', 'ひと', None, None], [None, None, 'がいるよね。', None]]
[['楽', 'たの', None, None], [None, None, 'しい', None], [None, None, 'って', True], ['言', 'い', None, True], [None, None, 'っても', True], [None, None, '、サッカーの', None], ['方', 'ほう', None, None], [None, None, 'が', None], ['楽', 'たの', None, None], [None, None, 'しいと', None], ['思', 'おも', None, None], [None, None, 'う。', None]]
[[None, None, 'ほしい', None], [None, None, 'って', True], ['言', 'い', None, True], [None, None, 'っても', True], [None, None, '、', None], ['高', 'たか', None, None], [None, None, 'くて', None], ['自分', 'じぶん', None, None], [None, None, 'では', None], ['買', 'か', None, None], [None, None, 'えません。', None]]

 39%|███▊      | 363/938 [03:37<05:58,  1.60it/s]

[['Ａ', 'エー', None, None], [None, None, '：「', None], ['夏休', 'なつやす', None, None], [None, None, 'み、', None], ['海', 'うみ', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'きたいわ。」 ', None], [None, None, ' ', None], ['Ｂ', 'ビー', None, None], [None, None, '：「', None], ['夏', 'なつ', None, None], [None, None, 'といえば', True], [None, None, 'かき', None], ['氷', 'ごおり', None, None], [None, None, 'だよね。」', None]]
[['Ａ', 'エー', None, None], [None, None, '：「コーヒーがほしい！」 ', None], ['Ｂ', 'ビー', None, None], [None, None, '：「コーヒー', None], [None, None, 'といえば', True], [None, None, '、', None], ['新', 'あたら', None, None], [None, None, 'しい', None], ['喫茶店', 'きっさてん', None, None], [None, None, 'が', None], ['開店', 'かいてん', None, None], [None, None, 'した。じゃあ、', None], ['一緒', 'いっしょ', None, None], [None, None, 'に', None], ['喫茶店', 'きっさてん', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'こうか？」', None]]
[['Ａ', 'エー', None, None], [None, None, '：「ビットコインの', None], ['評価', 'ひょうか', None, None], [None, None, 'は', None], ['最近', 'さいきん', None, None], ['下', 'さが', None, None], [None, None, 'ったみたい...。」', None], [None, None, ' ', None], ['Ｂ', 'ビー', None, None], [None, None, '：「ビットコイン', None], [None, None, 'といえば', True], [None, None, '、', None], ['今', 'いま', None, None], [None, None, '、', None], ['売', 'う', None, None], [None, None, 'るべきなの？」', None]]
[['Ａ', 'エー', None, None], [None, None, '：「', None], ['最近', 'さいきん', None, None], [None, None, '、アニメは', None], ['国際的', 'こくさいてき', None, None], [None, None, 'に', None], ['人気', 'にんき', None, None], [None, None, 'になっていくよ。」 ', None], ['Ｂ', 'ビー', None, None], [None, None, '：「アニメ', None], [None, None, 'といえば', True], [None, None, 'ドラグーンボールの', None], ['新', 'あたら', None, None], [None, None, 'しいシーズンが', None], ['放送', 'ほうそう', None, None], [None, None, 'されているね。」', None]]
[['Ａ', 'エー', None, None], [None, None, '：「カナダではオーロラや', None], ['野生', 'やせい', None, None], ['動物', 'どうぶつ', None, None], [None, None, 'がよく', None], ['見', 'み', None, None], [None, None, 'られるらしい。」 ', None], ['Ｂ', 'ビー', None, None], [None, None, '：「オーロラの', None], ['美', 'うつく', None, None], [None, None, 'しさ', None], [None, None, 'といったら', True], [None, None, '、', None], ['言葉', 'ことば', None, None], [None, None, 'では', None], ['表現', 'ひょうげん', None, None], [None, None, 'できませんなあ。」', None]]

 39%|███▉      | 364/938 [03:37<05:51,  1.63it/s]

[['高校', 'こうこう', None, None], [None, None, 'の', None], ['頃', 'ころ', None, None], [None, None, '、', None], ['兄', 'あに', None, None], [None, None, 'とドッキリをよく', None], ['仕掛', 'しか', None, True], [None, None, 'け', True], ['合', 'あ', None, True], [None, None, 'った', True], [None, None, '...', None]]
[['協力', 'きょうりょく', None, None], [None, None, 'し', True], ['合', 'あ', None, True], [None, None, 'った', True], [None, None, 'り', None], [None, None, 'しながら', None], ['山', 'やま', None, None], [None, None, 'をゆっくりと', None], ['登', 'のぼ', None, None], [None, None, 'った。', None]]
[['ＥＵ', 'イーユー', None, None], [None, None, 'で', None], ['交流', 'こうりゅう', None, None], [None, None, 'し', True], ['合', 'あ', None, True], [None, None, 'う', True], [None, None, 'ことは', None], ['重要', 'じゅうよう', None, None], [None, None, 'だと', None], ['考', 'かんが', None, None], [None, None, 'えられている。', None]]
[[None, None, '「', None], ['友達', 'ともだち', None, None], [None, None, 'が', None], ['苦', 'くる', None, None], [None, None, 'しんでる', None], ['時', 'とき', None, None], [None, None, 'は、', None], ['助', 'たす', None, True], [None, None, 'け', True], ['合', 'あ', None, True], [None, None, 'う', True], [None, None, 'べきだね。」', None]]
[[None, None, 'かなださき', None], [None, None, '：「', None], ['私達', 'わたしたち', None, None], [None, None, '、', None], ['同時', 'どうじ', None, None], [None, None, 'に', None], ['告白', 'こくはく', None, None], [None, None, 'し', True], ['合', 'あ', None, True], [None, None, 'った', True], [None, None, 'んだよ！」', None]]

 39%|███▉      | 365/938 [03:38<05:39,  1.69it/s]

[['合図', 'あいず', None, None], [None, None, 'に', True], ['合', 'あ', None, True], [None, None, 'わせて', True], [None, None, '、スタートしてください。', None]]
[['服装', 'ふくそう', None, None], [None, None, 'は', None], ['季節', 'きせつ', None, None], [None, None, 'に', True], ['合', 'あ', None, True], [None, None, 'わせて', True], [None, None, '、', None], ['変', 'か', None, None], [None, None, 'えるものだよ！', None]]
[['状況', 'じょうきょう', None, None], [None, None, 'に', True], ['合', 'あ', None, True], [None, None, 'わせて', True], [None, None, '、やり', None], ['方', 'かた', None, None], [None, None, 'を', None], ['変', 'か', None, None], [None, None, 'えてください。', None]]
[['私', 'わたし', None, None], [None, None, 'に', True], ['合', 'あ', None, True], [None, None, 'った', True], ['服', 'ふく', None, None], [None, None, 'を', None], ['選', 'えら', None, None], [None, None, 'んで。', None]]
[[None, None, 'あの', None], ['音楽', 'おんがく', None, None], [None, None, 'に', True], ['合', 'あ', None, True], [None, None, 'わせて', True], [None, None, '、', None], ['踊', 'おど', None, None], [None, None, 'ろうよ。', None]]

 39%|███▉      | 366/938 [03:38<05:35,  1.70it/s]

[[None, None, 'この', None], ['問題', 'もんだい', None, None], [None, None, 'について', True], [None, None, '、', None], ['誰', 'だれ', None, None], [None, None, 'かに', None], ['話', 'はな', None, None], [None, None, 'しましたか。', None]]
[['火災', 'かさい', None, None], [None, None, 'について', True], [None, None, '、', None], ['訓練', 'くんれん', None, None], [None, None, 'をするべきです。', None]]
[['震災', 'しんさい', None, None], [None, None, 'についての', True], ['情報', 'じょうほう', None, None], [None, None, 'を', None], ['教', 'おし', None, None], [None, None, 'えてもらった。', None]]
[['原因', 'げんいん', None, None], [None, None, 'について', True], [None, None, 'はまだ', None], ['調査中', 'ちょうさちゅう', None, None], [None, None, 'です。', None]]
[['明日', 'あした', None, None], [None, None, 'の', None], ['持', 'も', None, None], [None, None, 'ち', None], ['物', 'もの', None, None], [None, None, 'について', True], [None, None, 'お', None], ['伝', 'つた', None, None], [None, None, 'えします。', None]]

 39%|███▉      | 367/938 [03:39<05:29,  1.73it/s]

[[None, None, 'この', None], ['地域', 'ちいき', None, None], [None, None, 'には', None], ['人', 'ひと', None, None], [None, None, 'の', True], ['姿', 'すがた', None, True], [None, None, 'が', None], ['見', 'み', None, None], [None, None, 'えない。', None]]
[[None, None, 'あなたの', None], ['動', 'うご', None, None], [None, None, 'く', None], ['姿', 'すがた', None, True], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'きです。', None]]
[['友達', 'ともだち', None, None], [None, None, 'との', None], ['話', 'はなし', None, None], [None, None, '：「あの', None], ['人', 'ひと', None, None], [None, None, 'は', None], ['顔', 'かお', None, None], [None, None, 'も', None], ['綺麗', 'きれい', None, None], [None, None, 'だし、', None], ['立', 'た', None, None], [None, None, 'ち', None], ['姿', 'すがた', None, True], [None, None, 'も', None], ['美', 'うつく', None, None], [None, None, 'しい。」', None]]
[['衣料品店', 'いりょうひんてん', None, None], [None, None, '、クライアント', None], [None, None, '：「', None], ['自分', 'じぶん', None, None], [None, None, 'の', True], ['姿', 'すがた', None, True], [None, None, 'を', None], ['鏡', 'かがみ', None, None], [None, None, 'で', None], ['見', 'み', None, None], [None, None, 'てみるよ。」', None]]
[['２０１２', 'にせんじゅうに', None, None], ['年', 'ねん', None, None], [None, None, 'に', None], ['最後', 'さいご', None, None], [None, None, 'に', None], ['会', 'あ', None, None], [None, None, 'ってから、あの', None], ['男', 'おとこ', None, None], [None, None, 'の', True], ['姿', 'すがた', None, True], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'ていない。', None]]

 39%|███▉      | 368/938 [03:40<05:28,  1.74it/s]

[['彼', 'かれ', None, None], [None, None, 'らは', None], ['同時', 'どうじ', None, None], [None, None, 'にゴールインした', None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'えるだろう', True], [None, None, '。', None]]
[['船', 'ふね', None, None], [None, None, 'は', None], ['飛行機', 'ひこうき', None, None], [None, None, 'ほど', None], ['速', 'はや', None, None], [None, None, 'くないが、それでも', None], ['船旅', 'ふなたび', None, None], [None, None, 'を', None], ['好', 'この', None, None], [None, None, 'む', None], ['人', 'ひと', None, None], [None, None, 'は', None], ['多', 'おお', None, None], [None, None, 'い', None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'えるだろう', True], [None, None, '。', None]]
[['発明家', 'はつめいか', None, None], [None, None, 'は、「', None], ['変人', 'へんじん', None, None], [None, None, '」という', None], ['評価', 'ひょうか', None, None], [None, None, 'を', None], ['一般', 'いっぱん', None, None], [None, None, 'の', None], ['人', 'ひと', None, None], [None, None, 'から', None], ['下', 'くだ', None, None], [None, None, 'されてきた', None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'えるだろう', True], [None, None, '。', None]]
[['２０', 'にじゅっ', None, None], ['世紀', 'せいき', None, None], [None, None, 'にはコンピュータによって', None], ['生活', 'せいかつ', None, None], [None, None, 'しやすくなってきた', None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'えるだろう', True], [None, None, '。', None]]
[[None, None, 'このマニフェストは', None], ['自然', 'しぜん', None, None], ['環境', 'かんきょう', None, None], [None, None, 'の', None], ['現在', 'げんざい', None, None], [None, None, 'の', None], ['状態', 'じょうたい', None, None], [None, None, 'についてのひとつの', None], ['意見', 'いけん', None, None], [None, None, 'だ', None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'えるだろう', True], [None, None, '。', None]]

 39%|███▉      | 369/938 [03:40<05:27,  1.74it/s]

[['妻', 'つま', None, None], [None, None, '：「ガスを', None], [None, None, 'ちゃんと', True], ['閉', 'し', None, None], [None, None, 'めたか、わからない。」', None], ['夫', 'おっと', None, None], [None, None, '：「', None], ['心配', 'しんぱい', None, None], [None, None, 'しないで、', None], ['僕', 'ぼく', None, None], [None, None, 'が', None], [None, None, 'ちゃんと', True], ['閉', 'し', None, None], [None, None, 'めたよ。」', None]]
[['優', 'やさ', None, None], [None, None, 'しい', None], ['次長', 'じちょう', None, None], [None, None, '：「', None], ['昼休', 'ひるやす', None, None], [None, None, 'みなんだから', None], [None, None, 'ちゃんと', True], ['休', 'やす', None, None], [None, None, 'んでね。」', None], ['部下', 'ぶか', None, None], [None, None, '：「はい! わかりました、', None], ['次長', 'じちょう', None, None], [None, None, '！」', None]]
[['友達', 'ともだち', None, None], [None, None, 'との', None], ['話', 'はなし', None, None], [None, None, '：「', None], ['悪', 'わる', None, None], [None, None, 'いことをしたなら', None], [None, None, 'ちゃんと', True], ['謝', 'あやま', None, None], [None, None, 'るものだ！」', None]]
[['母親', 'ははおや', None, None], [None, None, 'は', None], ['子供', 'こども', None, None], [None, None, 'に', None], ['言', 'い', None, None], [None, None, 'う', None], [None, None, '：「', None], [None, None, 'お', None], ['祖母', 'ばあ', None, None], [None, None, 'さん', None], [None, None, 'が', None], ['来', 'く', None, None], [None, None, 'る', None], ['前', 'まえ', None, None], [None, None, 'に', None], ['部屋', 'へや', None, None], [None, None, 'を', None], [None, None, 'きちんと', True], ['片付', 'かたづ', None, None], [None, None, 'けしなさい！」', None]]
[['大人', 'おとな', None, None], [None, None, 'との', None], ['話', 'はなし', None, None], [None, None, '、', None], ['子供', 'こども', None, None], [None, None, 'を', None], ['褒', 'ほ', None, None], [None, None, 'める', None], [None, None, '：「あの', None], ['子', 'こ', None, None], [None, None, 'は、', None], [None, None, 'ちゃんと', True], [None, None, 'してるわね。」', None]]

 39%|███▉      | 370/938 [03:41<05:24,  1.75it/s]

[['５', 'ご', None, None], ['人', 'にん', None, None], [None, None, 'の', None], ['家族', 'かぞく', None, None], [None, None, 'を', None], ['養', 'やしな', None, None], [None, None, 'う。', None], [None, None, 'その', True], ['為', 'ため', None, True], [None, None, 'に', True], ['僕', 'ぼく', None, None], [None, None, 'は', None], ['働', 'はたら', None, None], [None, None, 'く。', None]]
[['夜', 'よる', None, None], ['遅', 'おそ', None, None], [None, None, 'くまで', None], ['仕事', 'しごと', None, None], [None, None, 'をした。', None], [None, None, 'その', True], ['為', 'ため', None, True], ['寝坊', 'ねぼう', None, None], [None, None, 'してしまった。', None]]
[['会社', 'かいしゃ', None, None], [None, None, 'が', None], ['倒産', 'とうさん', None, None], [None, None, 'した。', None], [None, None, 'その', True], ['為', 'ため', None, True], [None, None, 'に', True], ['失業', 'しつぎょう', None, None], [None, None, 'した。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], ['鉄道', 'てつどう', None, None], [None, None, 'オタクです。いろんな', None], ['電車', 'でんしゃ', None, None], [None, None, 'の', None], ['写真', 'しゃしん', None, None], [None, None, 'を', None], ['撮', 'と', None, None], [None, None, 'るのですが、', None], [None, None, 'その', True], ['為', 'ため', None, True], [None, None, 'に', True], ['徹夜', 'てつや', None, None], [None, None, 'することもあります。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'の', None], ['夢', 'ゆめ', None, None], [None, None, 'を', None], ['実現', 'じつげん', None, None], [None, None, 'させたい。', None], [None, None, 'その', True], ['為', 'ため', None, True], [None, None, 'に', True], [None, None, 'できるだけのことはしたいと', None], ['思', 'おも', None, None], [None, None, 'っている。', None]]

 40%|███▉      | 371/938 [03:41<05:17,  1.78it/s]

[['夜更', 'よふ', None, None], [None, None, 'かしをした。', None], [None, None, 'その', True], ['結果', 'けっか', None, True], [None, None, '、', None], ['遅刻', 'ちこく', None, None], [None, None, 'した。', None]]
[['無理', 'むり', None, None], [None, None, 'をして', None], ['走', 'はし', None, None], [None, None, 'った。', None], [None, None, 'その', True], ['結果', 'けっか', None, True], ['足', 'あし', None, None], [None, None, 'がつった。', None]]
[['値上', 'ねあ', None, None], [None, None, 'げをした。', None], [None, None, 'その', True], ['結果', 'けっか', None, True], [None, None, '、', None], ['売', 'う', None, None], [None, None, 'り', None], ['上', 'あ', None, None], [None, None, 'げが', None], ['下', 'さ', None, None], [None, None, 'がってしまった。', None]]
[['彼', 'かれ', None, None], [None, None, 'の', None], ['分', 'ぶん', None, None], [None, None, 'も', None], ['買', 'か', None, None], [None, None, 'ってきてあげた。', None], [None, None, 'その', True], ['結果', 'けっか', None, True], ['褒', 'ほ', None, None], [None, None, 'められた。', None]]
[['運動', 'うんどう', None, None], [None, None, 'をやめてしまった。', None], [None, None, 'その', True], ['結果', 'けっか', None, True], [None, None, '、', None], ['五', 'ご', None, None], [None, None, 'キロも', None], ['太', 'ふと', None, None], [None, None, 'った。', None]]

 40%|███▉      | 372/938 [03:42<05:21,  1.76it/s]

[['野球', 'やきゅう', None, None], [None, None, 'に', True], ['比', 'くら', None, True], [None, None, 'べたら', True], [None, None, '、サッカーの', None], ['方', 'ほう', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'きだ。', None]]
[['一学期', 'いちがっき', None, None], [None, None, 'に', True], ['比', 'くら', None, True], [None, None, 'べて', True], ['成績', 'せいせき', None, None], [None, None, 'がよくなった。', None]]
[['昨日', 'きのう', None, None], [None, None, 'に', True], ['比', 'くら', None, True], [None, None, 'べたら', True], ['今日', 'きょう', None, None], [None, None, 'は', None], ['暖', 'あたた', None, None], [None, None, 'かい。', None]]
[['去年', 'きょねん', None, None], [None, None, 'に', True], ['比', 'くら', None, True], [None, None, 'べて', True], ['今年', 'ことし', None, None], [None, None, 'は', None], ['雪', 'ゆき', None, None], [None, None, 'が', None], ['多', 'おお', None, None], [None, None, 'い。', None]]
[['昔', 'むかし', None, None], [None, None, 'に', True], ['比', 'くら', None, True], [None, None, 'べると', True], [None, None, '、', None], ['今', 'いま', None, None], [None, None, 'の', None], ['人', 'ひと', None, None], [None, None, 'は', None], ['長生', 'ながい', None, None], [None, None, 'きだ。', None]]

 40%|███▉      | 373/938 [03:42<05:20,  1.77it/s]

[[None, None, 'どんなに', None], ['頑張', 'がんば', None, True], [None, None, 'っても', True], ['無理', 'むり', None, None], [None, None, 'だと', None], ['思', 'おも', None, None], [None, None, 'う。', None]]
[[None, None, 'どんなに', True], ['笑', 'わら', None, None], [None, None, 'われ', None], [None, None, 'ても', None], [None, None, '、', None], ['前', 'まえ', None, None], [None, None, 'に', None], ['進', 'すす', None, None], [None, None, 'もう。', None]]
[[None, None, 'どんなに', True], ['勉強', 'べんきょう', None, None], [None, None, 'し', None], [None, None, 'ても', None], [None, None, '、', None], ['合格', 'ごうかく', None, None], [None, None, 'できないと', None], ['思', 'おも', None, None], [None, None, 'う。', None]]
[[None, None, 'どんなに', True], ['暇', 'ひま', None, None], [None, None, 'でも', None], [None, None, '、', None], ['掃除', 'そうじ', None, None], [None, None, 'するつもりはない。', None]]
[[None, None, 'どんなに', True], ['苦', 'くる', None, None], [None, None, 'しく', None], [None, None, 'ても', None], [None, None, '、', None], ['僕', 'ぼく', None, None], [None, None, 'はぜったいにあきらめない。', None]]

 40%|███▉      | 374/938 [03:43<05:16,  1.78it/s]

[[None, None, 'いくら', True], ['急', 'いそ', None, True], [None, None, 'いでも', True], ['土曜日', 'どようび', None, None], [None, None, 'までには', None], ['終', 'お', None, None], [None, None, 'わらない。', None]]
[[None, None, 'いくら', True], ['泣', 'な', None, True], [None, None, 'いても', True], [None, None, '、', None], ['泣', 'な', None, None], [None, None, 'き', None], ['止', 'や', None, None], [None, None, 'まない。', None]]
[[None, None, 'いくら', None], [None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'が', None], [None, None, 'あっても', True], [None, None, '、', None], ['愛', 'あい', None, None], [None, None, 'は', None], ['買', 'か', None, None], [None, None, 'えない。', None]]
[[None, None, 'いくら', True], ['頑張', 'がんば', None, True], [None, None, 'っても', True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'にはかなわない。', None]]
[[None, None, 'いくら', True], ['稼', 'かせ', None, True], [None, None, 'いでも', True], [None, None, '、', None], ['妻', 'つま', None, None], [None, None, 'がすぐに', None], ['使', 'つか', None, None], [None, None, 'ってしまうから', None], ['困', 'こま', None, None], [None, None, 'っている。', None]]

 40%|███▉      | 375/938 [03:44<05:21,  1.75it/s]

[['音楽', 'おんがく', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'きか', None], ['嫌', 'きら', None, None], [None, None, 'い', None], [None, None, 'かは', None], ['人', 'ひと', None, None], [None, None, 'それぞれ', None], [None, None, 'によって', True], ['違', 'ちが', None, True], [None, None, 'う', True], [None, None, '。', None]]
[['果物', 'くだもの', None, None], [None, None, 'が', None], ['高', 'たか', None, None], [None, None, 'い', None], [None, None, 'かどうかは', None], ['季節', 'きせつ', None, None], [None, None, 'によって', True], ['違', 'ちが', None, True], [None, None, 'う', True], [None, None, '。', None]]
[['何', 'なに', None, None], [None, None, 'が', None], ['良', 'い', None, None], [None, None, 'い', None], [None, None, 'かは', None], ['各人', 'かくじん', None, None], [None, None, 'の', None], ['主観', 'しゅかん', None, None], [None, None, 'によって', True], ['違', 'ちが', None, True], [None, None, 'う', True], [None, None, '。', None]]
[['海', 'うみ', None, None], [None, None, 'が', None], ['深', 'ふか', None, None], [None, None, 'い', None], [None, None, 'かどうかは', None], ['場所', 'ばしょ', None, None], [None, None, 'によって', True], ['違', 'ちが', None, True], [None, None, 'う', True], [None, None, 'でしょうね。', None]]
[['何歳', 'なんさい', None, None], [None, None, 'で', None], ['退職', 'たいしょく', None, None], [None, None, 'できる', None], [None, None, 'かは', None], ['国', 'くに', None, None], [None, None, 'によって', True], ['違', 'ちが', None, True], [None, None, 'う', True], [None, None, '。', None]]

 40%|████      | 376/938 [03:44<05:22,  1.74it/s]

[['友達', 'ともだち', None, None], [None, None, 'との', None], ['話', 'はなし', None, None], [None, None, '、', None], ['地図', 'ちず', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'て', None], [None, None, '：「ここは', None], [None, None, 'かなり', True], ['遠', 'とお', None, None], [None, None, 'くの', None], ['方', 'ほう', None, None], [None, None, 'だね。」', None]]
[['会社', 'かいしゃ', None, None], [None, None, 'の', None], ['社長', 'しゃちょう', None, None], [None, None, '：「', None], ['新', 'あたら', None, None], [None, None, 'しいシステムを', None], ['導入', 'どうにゅう', None, None], [None, None, 'しよう。」', None], ['社員', 'しゃいん', None, None], [None, None, '：「わかりました。でも、', None], [None, None, 'かなり', True], ['費用', 'ひよう', None, None], [None, None, 'がかかりそうですよ。」', None]]
[['配送会社', 'はいそうかいしゃ', None, None], [None, None, '、', None], ['労働者', 'ろうどうしゃ', None, None], ['１', 'いち', None, None], [None, None, '：「じゃあ、はやくこれ、(トラックに）', None], ['積', 'つ', None, None], [None, None, 'んでしまおう。」', None], ['労働者', 'ろうどうしゃ', None, None], ['２', 'に', None, None], [None, None, '：「でもこれ、', None], [None, None, 'かなり', True], ['重', 'おも', None, None], [None, None, 'いんだけど。」', None]]
[['文法', 'ぶんぽう', None, None], [None, None, 'ちゃん', None], [None, None, '：「ユーザーさんの', None], ['日本語', 'にほんご', None, None], [None, None, 'は、', None], [None, None, 'かなり', True], ['上級', 'じょうきゅう', None, None], [None, None, 'レベルだと', None], ['思', 'おも', None, None], [None, None, 'う。」', None]]
[['従業員', 'じゅうぎょういん', None, None], [None, None, 'の', None], ['噂話', 'うわさばなし', None, None], [None, None, '：「', None], ['次長', 'じちょう', None, None], [None, None, 'は、', None], ['家', 'いえ', None, None], [None, None, 'ではお', None], ['孫', 'まご', None, None], [None, None, 'さんに', None], ['優', 'やさ', None, None], [None, None, 'しいおじいちゃんらしいよ。そんな', None], ['風', 'ふう', None, None], [None, None, 'に', None], ['見', 'み', None, None], [None, None, 'えないけどね。', None], ['会社', 'かいしゃ', None, None], [None, None, 'では', None], [None, None, 'かなり', True], ['厳', 'きび', None, None], [None, None, 'しい', None], ['人', 'ひと', None, None], [None, None, 'だから。」', None]]

 40%|████      | 377/938 [03:45<05:26,  1.72it/s]

[['余', 'あま', None, True], [None, None, 'りに', True], ['早', 'はや', None, None], [None, None, 'く', None], ['着', 'つ', None, None], [None, None, 'いてしまった。', None]]
[[None, None, 'そのケーキは', None], ['余', 'あま', None, True], [None, None, 'りに', True], ['大', 'おお', None, None], [None, None, 'きすぎて、', None], ['食', 'た', None, None], [None, None, 'べられない。', None]]
[['余', 'あま', None, True], [None, None, 'りに', True], ['寒', 'さむ', None, None], [None, None, 'すぎて、', None], ['帰', 'かえ', None, None], [None, None, 'ってきてしまった。', None]]
[[None, None, 'その', None], ['計画', 'けいかく', None, None], [None, None, 'は', None], ['余', 'あま', None, True], [None, None, 'りに', True], ['非現実的', 'ひげんじつてき', None, None], [None, None, 'だよ。', None]]
[['余', 'あま', None, True], [None, None, 'りに', True], ['仕事', 'しごと', None, None], [None, None, 'が', None], ['多', 'おお', None, None], [None, None, 'すぎて、', None], ['手', 'て', None, None], [None, None, 'に', None], ['負', 'お', None, None], [None, None, 'えない。', None]]

 40%|████      | 378/938 [03:45<05:27,  1.71it/s]

[['雪', 'ゆき', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'っていた。', None], ['寒', 'さむ', None, None], [None, None, 'い', None], ['訳', 'わけ', None, True], [None, None, 'だ', True], [None, None, '。', None]]
[[None, None, 'また', None], ['忘', 'わす', None, None], [None, None, 'れたの？それで', None], ['先生', 'せんせい', None, None], [None, None, 'に', None], ['叱', 'しか', None, None], [None, None, 'られた', None], ['訳', 'わけ', None, True], [None, None, 'だ', True], [None, None, '。', None]]
[['夜更', 'よふ', None, None], [None, None, 'かししてばかりいるの？それじゃあ', None], ['遅刻', 'ちこく', None, None], [None, None, 'する', None], ['訳', 'わけ', None, True], [None, None, 'だ', True], [None, None, '。', None]]
[[None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'を', None], ['無駄', 'むだ', None, None], [None, None, 'に', None], ['使', 'つか', None, None], [None, None, 'っている。', None], ['貯金', 'ちょきん', None, None], [None, None, 'がない', None], ['訳', 'わけ', None, True], [None, None, 'です', True], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['医者', 'いしゃ', None, None], [None, None, 'になりたいから、', None], ['医学', 'いがく', None, None], [None, None, 'の', None], ['勉強', 'べんきょう', None, None], [None, None, 'をする', None], ['訳', 'わけ', None, True], [None, None, 'だ', True], [None, None, '。', None]]

 40%|████      | 379/938 [03:46<05:20,  1.75it/s]

[['Ａ', 'エー', None, None], [None, None, '：「', None], ['北海道', 'ほっかいどう', None, None], [None, None, 'といえば、', None], ['Ｃ', 'シー', None, None], [None, None, 'さんによれば', None], ['一年中', 'いちねんじゅう', None, None], ['寒', 'さむ', None, None], [None, None, 'いらしい。」', None], [None, None, ' ', None], ['Ｂ', 'ビー', None, None], [None, None, '：「', None], ['夏', 'なつ', None, None], [None, None, 'でも', None], ['寒', 'さむ', None, None], [None, None, 'い', None], [None, None, 'わけではない', True], [None, None, '。」', None]]
[['Ａ', 'エー', None, None], [None, None, '：「', None], ['天気', 'てんき', None, None], ['予報', 'よほう', None, None], [None, None, 'によると', None], ['明日', 'あした', None, None], [None, None, 'は', None], ['晴', 'は', None, None], [None, None, 'れるだろう。」', None], [None, None, ' ', None], ['Ｂ', 'ビー', None, None], [None, None, '：「', None], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'らない', None], [None, None, 'わけではない', True], [None, None, '。」', None]]
[['Ａ', 'エー', None, None], [None, None, '：「また', None], ['試合', 'しあい', None, None], [None, None, 'に', None], ['負', 'ま', None, None], [None, None, 'けたよ。もう', None], ['我慢', 'がまん', None, None], [None, None, 'できない！', None], ['泣', 'な', None, None], [None, None, 'いちゃいたい！」', None], [None, None, ' ', None], ['Ｂ', 'ビー', None, None], [None, None, '：「いつもうまくいく', None], [None, None, 'わけではない', True], [None, None, '。', None], ['失敗', 'しっぱい', None, None], [None, None, 'はつきものだ。」', None]]
[['Ａ', 'エー', None, None], [None, None, '：「あなたはデートを', None], ['忘', 'わす', None, None], [None, None, 'れていたわ！', None], ['私', 'わたし', None, None], [None, None, 'は', None], ['腹', 'はら', None, None], [None, None, 'が', None], ['立', 'た', None, None], [None, None, 'っているから', None], ['話', 'はな', None, None], [None, None, 'しかけないで！」', None], [None, None, ' ', None], ['Ｂ', 'ビー', None, None], [None, None, '：「', None], ['遅', 'おそ', None, None], [None, None, 'くなってしまいましたが、', None], ['忘', 'わす', None, None], [None, None, 'れていた', None], [None, None, 'わけではありません', True], [None, None, 'よ。」', None]]
[['Ａ', 'エー', None, None], [None, None, '：「', None], ['Ｂ', 'ビー', None, None], [None, None, 'さんは、', None], ['来年', 'らいねん', None, None], ['結婚', 'けっこん', None, None], [None, None, 'するつもりということだね。」', None], [None, None, ' ', None], ['Ｂ', 'ビー', None, None], [None, None, '：「まだ', None], ['決', 'き', None, None], [None, None, 'まった', None], [None, None, 'わけではない', True], [None, None, 'から、', None], ['内密', 'ないみつ', None, None], [None, None, 'にお', None], ['願', 'ねが', None, None], [None, None, 'いします。」', None]]

 41%|████      | 380/938 [03:46<05:17,  1.76it/s]

[['財布', 'さいふ', None, None], [None, None, 'と', True], ['同時', 'どうじ', None, True], [None, None, 'に', True], ['免許証', 'めんきょしょう', None, None], [None, None, 'もなくしてしまいました。', None]]
[['毎朝', 'まいあさ', None, None], ['日', 'ひ', None, None], [None, None, 'の', None], ['出', 'で', None, None], [None, None, 'と', True], ['同時', 'どうじ', None, True], [None, None, 'に', True], ['起', 'お', None, None], [None, None, 'きる。', None]]
[['目覚', 'めざ', None, None], [None, None, 'める', None], [None, None, 'と', True], ['同時', 'どうじ', None, True], [None, None, 'に', True], ['着替', 'きが', None, None], [None, None, 'えて', None], ['出', 'で', None, None], [None, None, 'かけた。', None]]
[['録画', 'ろくが', None, None], [None, None, 'する', None], [None, None, 'と', True], ['同時', 'どうじ', None, True], [None, None, 'に', True], [None, None, 'ナレーションも', None], ['入', 'い', None, None], [None, None, 'れてほしい。', None]]
[['決断力', 'けつだんりょく', None, None], [None, None, 'と', True], ['同時', 'どうじ', None, True], [None, None, 'に', True], ['慎重', 'しんちょう', None, None], [None, None, 'さも', None], ['必要', 'ひつよう', None, None], [None, None, 'だ。', None]]

 41%|████      | 381/938 [03:47<05:10,  1.79it/s]

[[None, None, 'もう', None], ['少', 'すこ', None, None], [None, None, 'しで', None], ['船', 'ふね', None, None], [None, None, 'からおちる', None], [None, None, 'ところだった', True], [None, None, '。', None]]
[[None, None, 'ちょうど', None], ['電車', 'でんしゃ', None, None], [None, None, 'が', None], ['発車', 'はっしゃ', None, None], [None, None, 'する', None], [None, None, 'ところだった', True], [None, None, '。', None]]
[['危', 'あや', None, None], [None, None, 'うく', None], ['遅刻', 'ちこく', None, None], [None, None, 'する', None], [None, None, 'ところだった', True], [None, None, '。', None]]
[[None, None, 'もう', None], ['少', 'すこ', None, None], [None, None, 'しで', None], ['事故', 'じこ', None, None], [None, None, 'が', None], ['起', 'お', None, None], [None, None, 'こる', None], [None, None, 'ところだった', True], [None, None, '。', None]]
[['好', 'す', None, None], [None, None, 'きな', None], ['声優', 'せいゆう', None, None], [None, None, 'に', None], ['会', 'あ', None, None], [None, None, 'えない', None], [None, None, 'ところだった', True], [None, None, '。', None]]

 41%|████      | 382/938 [03:48<05:14,  1.77it/s]

[['全員', 'ぜんいん', None, None], ['合格', 'ごうかく', None, None], [None, None, 'だって', True], [None, None, 'よ。', None]]
[[None, None, 'だって', True], [None, None, '、', None], ['全然', 'ぜんぜん', None, None], ['知', 'し', None, None], [None, None, 'らないんだ', None], [None, None, 'もん', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'だって', True], ['落', 'お', None, None], [None, None, 'ち', None], ['込', 'こ', None, None], [None, None, 'むこともあるよ。', None]]
[[None, None, '「たけしさん、', None], ['海外旅行', 'かいがいりょこう', None, None], [None, None, 'だって', True], [None, None, '？」', None]]
[['月', 'つき', None, None], [None, None, 'に', None], [None, None, 'だって', True], ['行', 'い', None, None], [None, None, 'けるかもしれない。', None]]

 41%|████      | 383/938 [03:48<05:12,  1.78it/s]

[[None, None, 'トムは、また', None], ['元', 'もと', None, None], [None, None, 'カノと', None], ['付', 'つ', None, None], [None, None, 'き', None], ['合', 'あ', None, None], [None, None, 'っている', None], [None, None, 'んだって', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['真面目', 'まじめ', None, None], [None, None, 'なんだって', True], [None, None, '。', None]]
[[None, None, 'やっと', None], ['旅行', 'りょこう', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'ける', None], [None, None, 'んだって', True], [None, None, '。お', None], ['金', 'かね', None, None], [None, None, 'が', None], ['貯', 'た', None, None], [None, None, 'まったから。', None]]
[[None, None, 'まだできていない', None], [None, None, 'んだって', True], [None, None, '。あんなに', None], ['時間', 'じかん', None, None], [None, None, 'があったのに…', None]]
[['本当', 'ほんとう', None, None], [None, None, 'は', None], ['嫌', 'いや', None, None], [None, None, 'なんだって', True], [None, None, '。', None], ['口', 'くち', None, None], [None, None, 'では', None], ['言', 'い', None, None], [None, None, 'えないけど。', None]]

 41%|████      | 384/938 [03:49<05:42,  1.62it/s]

[[None, None, 'その', None], ['問題', 'もんだい', None, None], [None, None, 'は', None], ['私', 'わたし', None, None], [None, None, 'には', None], ['関係', 'かんけい', None, True], [None, None, 'はない', True], [None, None, 'よ。', None]]
[[None, None, 'これと', None], ['事故', 'じこ', None, None], [None, None, 'の', None], ['間', 'あいだ', None, None], [None, None, 'になんらかの', None], ['関係', 'かんけい', None, True], [None, None, 'がある', True], [None, None, 'はずだ。', None]]
[['彼', 'かれ', None, None], [None, None, 'らはそれぞれあいざわさんと', None], ['不透明', 'ふとうめい', None, None], [None, None, 'な', None], ['関係', 'かんけい', None, True], [None, None, 'がある', True], [None, None, 'ように', None], ['見', 'み', None, None], [None, None, 'える。', None]]
[['容疑者', 'ようぎしゃ', None, None], [None, None, 'と', None], ['直', 'じか', None, None], [None, None, 'に', None], ['関係', 'かんけい', None, True], [None, None, 'がある', True], ['人物', 'じんぶつ', None, None], [None, None, 'が', None], ['全員', 'ぜんいん', None, None], ['呼', 'よ', None, None], [None, None, 'び', None], ['出', 'だ', None, None], [None, None, 'された。', None]]
[['日本', 'にほん', None, None], ['食', 'しょく', None, None], [None, None, 'に', None], ['関係', 'かんけい', None, True], [None, None, 'がある', True], ['単語', 'たんご', None, None], [None, None, 'で', None], ['空欄', 'くうらん', None, None], [None, None, 'を', None], ['埋', 'う', None, None], [None, None, 'めてください。', None]]

 41%|████      | 385/938 [03:49<05:34,  1.65it/s]

[[None, None, 'ダンス', None], [None, None, 'に', True], ['関', 'かん', None, True], [None, None, 'する', True], ['本', 'ほん', None, None], [None, None, 'が', None], ['机', 'つくえ', None, None], [None, None, 'の', None], ['上', 'うえ', None, None], [None, None, 'にあります。', None]]
[['過去', 'かこ', None, None], [None, None, 'に', True], ['関', 'かん', None, True], [None, None, 'して', True], [None, None, 'は、', None], ['悲', 'かな', None, None], [None, None, 'しまなくてもいい。', None]]
[['環境', 'かんきょう', None, None], [None, None, 'に', True], ['関', 'かん', None, True], [None, None, 'して', True], [None, None, '、', None], ['質問', 'しつもん', None, None], [None, None, 'はありますか。', None]]
[[None, None, 'その', None], ['件', 'けん', None, None], [None, None, 'に', True], ['関', 'かん', None, True], [None, None, 'して', True], [None, None, 'は', None], ['改', 'あらた', None, None], [None, None, 'めてご', None], ['説明', 'せつめい', None, None], [None, None, 'いたします。', None]]
[['経済', 'けいざい', None, None], [None, None, 'に', True], ['関', 'かん', None, True], [None, None, 'して', True], [None, None, 'は', None], ['全然', 'ぜんぜん', None, None], ['詳', 'くわ', None, None], [None, None, 'しくありません。', None]]

 41%|████      | 386/938 [03:50<05:26,  1.69it/s]

[['彼', 'かれ', None, None], [None, None, 'はみんな', None], [None, None, 'に', True], ['対', 'たい', None, True], [None, None, 'して', True], ['優', 'やさ', None, None], [None, None, 'しい', None], ['人', 'ひと', None, None], [None, None, 'なんです。', None]]
[['日本', 'にほん', None, None], [None, None, 'の', None], ['教育', 'きょういく', None, None], ['制度', 'せいど', None, None], [None, None, 'に', True], ['対', 'たい', None, True], [None, None, 'して', True], [None, None, 'どう', None], ['思', 'おも', None, None], [None, None, 'う？', None]]
[['誰', 'だれ', None, None], [None, None, 'に', True], ['対', 'たい', None, True], [None, None, 'して', True], [None, None, 'も', None], ['親切', 'しんせつ', None, None], [None, None, 'な', None], ['人', 'ひと', None, None], [None, None, 'になりたい。', None]]
[['父', 'ちち', None, None], [None, None, 'が', None], ['厳', 'きび', None, None], [None, None, 'しすぎる', None], [None, None, 'のに', True], ['対', 'たい', None, True], [None, None, 'して', True], [None, None, '、', None], ['母', 'はは', None, None], [None, None, 'は', None], ['優', 'やさ', None, None], [None, None, 'しすぎる。', None]]
[[None, None, 'はぐらかさないで', None], ['質問', 'しつもん', None, None], [None, None, 'に', True], ['対', 'たい', None, True], [None, None, 'して', True], ['答', 'こた', None, None], [None, None, 'えてください。', None]]

 41%|████▏     | 387/938 [03:51<05:19,  1.73it/s]

[['寝', 'ね', None, None], [None, None, 'ることしか', None], ['出来', 'でき', None, None], [None, None, 'ない', None], [None, None, 'くらい', True], [None, None, '、', None], ['疲', 'つか', None, None], [None, None, 'れている。', None]]
[[None, None, 'あの', None], ['仕事', 'しごと', None, None], [None, None, 'は、', None], ['泣', 'な', None, None], [None, None, 'きたい', None], [None, None, 'くらい', True], [None, None, 'つらかったよ。', None]]
[[None, None, 'プロ', None], ['選手', 'せんしゅ', None, None], [None, None, 'ぐらい', True], ['上手', 'じょうず', None, None], [None, None, 'になりたい。', None]]
[['残', 'のこ', None, None], [None, None, 'っているのはやきとり', None], [None, None, 'くらい', True], [None, None, 'ですが。', None]]
[[None, None, 'みんなを', None], ['泣', 'な', None, None], [None, None, 'かす', None], [None, None, 'くらい', True], [None, None, 'スパイシーなチリのサラダを', None], ['作', 'つく', None, None], [None, None, 'った。', None]]

 41%|████▏     | 388/938 [03:51<05:21,  1.71it/s]

[['私', 'わたし', None, None], [None, None, 'が', None], ['得意', 'とくい', None, None], [None, None, 'なの', None], [None, None, 'は', None], ['料理', 'りょうり', None, None], [None, None, 'くらい', True], [None, None, 'です。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['仲間', 'なかま', None, None], [None, None, 'は', None], [None, None, '、', None], ['犬', 'いぬ', None, None], [None, None, 'と', None], ['猿', 'さる', None, None], [None, None, 'と', None], ['雉', 'きじ', None, None], [None, None, 'くらい', True], [None, None, 'です。', None]]
[['私', 'わたし', None, None], [None, None, 'が', None], ['苦手', 'にがて', None, None], [None, None, 'なの', None], [None, None, 'は', None], [None, None, '、ネギ', None], [None, None, 'くらい', True], [None, None, 'のもの', None], [None, None, 'です。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['友人', 'ゆうじん', None, None], [None, None, 'は', None], [None, None, '、', None], ['君', 'きみ', None, None], [None, None, 'と', None], ['愛犬', 'あいけん', None, None], [None, None, 'くらい', True], [None, None, 'だ。\n', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['友人', 'ゆうじん', None, None], [None, None, 'は', None], [None, None, '、', None], ['君', 'きみ', None, None], [None, None, 'と', None], ['愛犬', 'あいいぬ', None, None], [None, None, 'ぐらい', True], [None, None, 'だ。', None]]

 41%|████▏     | 389/938 [03:52<05:15,  1.74it/s]

[[None, None, '「', None], [None, None, 'さあ', True], [None, None, '、', None], ['仕事', 'しごと', None, None], [None, None, 'を', None], ['始', 'はじ', None, None], [None, None, 'めよう。」', None]]
[[None, None, '「', None], [None, None, 'さあ', True], [None, None, '、', None], ['行', 'い', None, None], [None, None, 'きましょう。」', None]]
[[None, None, '「あの人、', None], ['誰', 'だれ', None, None], [None, None, '？」', None], [None, None, '「', None], [None, None, 'さあ', True], [None, None, '…」', None]]
[[None, None, '「', None], ['足', 'あし', None, None], [None, None, 'は（どう）？」', None], [None, None, '「', None], ['大丈夫', 'だいじょうぶ', None, None], [None, None, 'よ。', None], [None, None, 'さあ', True], ['早', 'はや', None, None], [None, None, 'く…」', None]]
[[None, None, '「', None], [None, None, 'さ', True], [None, None, '、', None], ['早', 'はや', None, None], [None, None, 'く', None], ['乗', 'の', None, None], [None, None, 'ってください。」', None], [None, None, '「うん。」', None]]

 42%|████▏     | 390/938 [03:52<05:13,  1.75it/s]

[[None, None, '「', None], ['今朝', 'けさ', None, None], [None, None, 'さあ', True], [None, None, '、', None], ['母', 'かあ', None, None], [None, None, 'さんに', None], ['怒', 'おこ', None, None], [None, None, 'られたよ。」', None]]
[['友達', 'ともだち', None, None], [None, None, 'との', None], ['会話', 'かいわ', None, None], [None, None, '：「あの', None], [None, None, 'さ', True], [None, None, '、', None], ['俺', 'おれ', None, None], [None, None, '、', None], ['彼女', 'かのじょ', None, None], [None, None, 'ができたんだ！」', None]]
[[None, None, '「あの', None], [None, None, 'さぁ', True], [None, None, '、', None], ['好', 'す', None, None], [None, None, 'きな', None], ['人', 'ひと', None, None], [None, None, 'とかいるの？」', None]]
[[None, None, '「', None], ['内緒', 'ないしょ', None, None], [None, None, 'だけど', None], [None, None, 'さ', True], [None, None, '、', None], ['彼', 'かれ', None, None], ['宝', 'たから', None, None], [None, None, 'くじに', None], ['当', 'あ', None, None], [None, None, 'たったんだよ。」', None]]
[['Ａ', 'エー', None, None], [None, None, '：「', None], ['私', 'わたし', None, None], [None, None, 'さぁ', True], [None, None, '、', None], ['明日', 'あした', None, None], [None, None, 'から', None], ['５', 'ご', None, None], ['連休', 'れんきゅう', None, None], [None, None, 'なんだ！」', None], ['Ｂ', 'ビー', None, None], [None, None, '：「いいなぁー」', None]]

 42%|████▏     | 391/938 [03:53<05:13,  1.75it/s]

[[None, None, '「', None], ['僕', 'ぼく', None, None], [None, None, 'は', None], ['ＮＢＡ', 'エヌビーエー', None, None], [None, None, 'でやるつもり', None], [None, None, 'さ', True], [None, None, '。」', None]]
[['Ａ', 'エー', None, None], [None, None, '：「', None], ['彼', 'かれ', None, None], [None, None, 'が', None], ['約束', 'やくそく', None, None], [None, None, 'を', None], ['破', 'やぶ', None, None], [None, None, 'ったって', None], [None, None, 'さ', True], [None, None, '。」', None], ['Ｂ', 'ビー', None, None], [None, None, '：「そんな', None], ['人', 'ひと', None, None], [None, None, 'じゃない', None], [None, None, 'さ', True], [None, None, '。」', None]]
[[None, None, '「まぁ、なんとかなる', None], [None, None, 'さ', True], [None, None, '。」', None]]
[['Ａ', 'エー', None, None], [None, None, '：「', None], ['寒', 'さむ', None, None], [None, None, 'い。', None], ['寒', 'さむ', None, None], [None, None, 'すぎるよ。」', None], ['Ｂ', 'ビー', None, None], [None, None, '：「どうってことない', None], [None, None, 'さ', True], [None, None, '。」', None]]
[[None, None, '「テレビで', None], ['台風', 'たいふう', None, None], [None, None, 'がやってくるって', None], [None, None, 'さ', True], [None, None, '。」', None]]

 42%|████▏     | 392/938 [03:53<05:09,  1.76it/s]

[[None, None, 'それぞれ', True], ['行', 'い', None, None], [None, None, 'きたいところに', None], ['行', 'い', None, None], [None, None, 'きましょう。', None]]
[['生', 'い', None, None], [None, None, 'き', None], ['物', 'もの', None, None], [None, None, 'は', None], [None, None, 'それぞれ', True], ['食', 'た', None, None], [None, None, 'べるものが', None], ['違', 'ちが', None, None], [None, None, 'う。', None]]
[[None, None, 'それぞれ', True], ['好', 'す', None, None], [None, None, 'きな', None], ['運動', 'うんどう', None, None], [None, None, 'をした。', None]]
[[None, None, 'これからは', None], [None, None, 'それぞれの', True], ['道', 'みち', None, None], [None, None, 'を', None], ['行', 'い', None, None], [None, None, 'くことに', None], ['決', 'き', None, None], [None, None, 'めた。', None]]
[['人', 'ひと', None, None], [None, None, 'それぞれ', True], ['癖', 'くせ', None, None], [None, None, 'というものがあります。', None]]

 42%|████▏     | 393/938 [03:54<05:16,  1.72it/s]

[[None, None, 'コートを', None], ['着', 'き', None, True], [None, None, 'たまま', True], [None, None, 'だと', None], ['少', 'すこ', None, None], [None, None, 'し', None], ['暑', 'あつ', None, None], [None, None, 'いです。', None]]
[['昨日', 'きのう', None, None], [None, None, 'は', None], ['窓', 'まど', None, None], [None, None, 'を', None], ['開', 'あ', None, True], [None, None, 'けたまま', True], ['寝', 'ね', None, None], [None, None, 'た。', None]]
[['生徒', 'せいと', None, None], [None, None, 'は', None], ['答', 'こた', None, None], [None, None, 'えられなくて、', None], ['黙', 'だま', None, True], [None, None, 'ったまま', True], [None, None, 'でした。', None]]
[[None, None, 'この', None], [None, None, 'まま', True], ['行', 'い', None, None], [None, None, 'くと', None], ['図書館', 'としょかん', None, None], [None, None, 'が', None], ['見', 'み', None, None], [None, None, 'えます。', None]]
[[None, None, 'ありの', None], [None, None, 'まま', True], [None, None, 'の', None], ['君', 'きみ', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'きだ。', None]]

 42%|████▏     | 394/938 [03:55<05:15,  1.72it/s]

[['私', 'わたし', None, None], [None, None, 'は', None], ['彼女', 'かのじょ', None, None], [None, None, 'を', None], ['愛', 'あい', None, None], [None, None, 'している。', None], [None, None, 'そこで', True], [None, None, '、', None], ['結婚', 'けっこん', None, None], [None, None, 'を', None], ['申', 'もう', None, None], [None, None, 'し', None], ['込', 'こ', None, None], [None, None, 'むことに', None], ['決', 'き', None, None], [None, None, 'めた。', None]]
[[None, None, 'この', None], ['方法', 'ほうほう', None, None], [None, None, 'ではもう', None], ['限界', 'げんかい', None, None], [None, None, 'だと', None], ['分', 'わ', None, None], [None, None, 'かった。', None], [None, None, 'そこで', True], [None, None, '、', None], ['新', 'あら', None, None], [None, None, 'たな', None], ['方法', 'ほうほう', None, None], [None, None, 'を', None], ['試', 'ため', None, None], [None, None, 'してみることに', None], ['決', 'き', None, None], [None, None, 'めた。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['暗記', 'あんき', None, None], [None, None, 'が', None], ['苦手', 'にがて', None, None], [None, None, 'だ。', None], [None, None, 'そこで', True], [None, None, '、', None], ['暗記', 'あんき', None, None], [None, None, 'のコツを', None], ['教', 'おし', None, None], [None, None, 'えてあげることに', None], ['決', 'き', None, None], [None, None, 'めた。', None]]
[[None, None, 'この', None], ['荷物', 'にもつ', None, None], [None, None, 'は', None], ['重', 'おも', None, None], [None, None, 'い。', None], [None, None, 'そこで', True], [None, None, '、', None], ['仲間', 'なかま', None, None], [None, None, 'を', None], ['呼', 'よ', None, None], [None, None, 'んで', None], ['手伝', 'てつだ', None, None], [None, None, 'ってもらうことに', None], ['決', 'き', None, None], [None, None, 'めた。', None]]
[[None, None, 'うちには', None], ['工具箱', 'こうぐばこ', None, None], [None, None, 'がありません。', None], [None, None, 'そこで', True], [None, None, 'お', None], ['願', 'ねが', None, None], [None, None, 'いなのですが、ドライバーを', None], ['貸', 'か', None, None], [None, None, 'してもらえませんか？', None]]

 42%|████▏     | 395/938 [03:55<05:10,  1.75it/s]

[['人', 'ひと', None, None], [None, None, 'が', None], ['多', 'おお', None, None], [None, None, 'いから、', None], ['並', 'なら', None, None], [None, None, 'ぶ', None], [None, None, 'しかない', True], [None, None, '。', None]]
[['時', 'とき', None, None], [None, None, 'が', None], ['来', 'く', None, None], [None, None, 'るのを', None], ['待', 'ま', None, None], [None, None, 'つ', None], [None, None, 'しかない', True], [None, None, 'ですよ。', None]]
[[None, None, 'こんなにうまくいかないかなあ… もう', None], ['笑', 'わら', None, None], [None, None, 'う', None], [None, None, 'しかない', True], [None, None, '。', None]]
[['素直', 'すなお', None, None], [None, None, 'に', None], ['謝', 'あやま', None, None], [None, None, 'る', None], [None, None, 'しかない', True], [None, None, 'です。', None]]
[[None, None, 'この', None], ['部屋', 'へや', None, None], [None, None, 'はゴミだらけなので', None], ['掃除', 'そうじ', None, None], [None, None, 'する', None], [None, None, 'しかない', True], [None, None, '。', None]]

 42%|████▏     | 396/938 [03:56<05:08,  1.76it/s]

[['無視', 'むし', None, None], [None, None, 'されても', True], ['構', 'かま', None, True], [None, None, 'わない', True], [None, None, '。', None]]
[[None, None, 'その', None], ['写真', 'しゃしん', None, None], [None, None, 'なら、', None], ['見', 'み', None, True], [None, None, 'ても', True], ['構', 'かま', None, True], [None, None, 'いません', True], [None, None, '。', None]]
[['欲', 'ほ', None, None], [None, None, 'しい', None], ['人', 'ひと', None, None], [None, None, 'がいれば', None], [None, None, 'あげても', True], ['構', 'かま', None, True], [None, None, 'わない', True], [None, None, '。', None]]
[['答', 'こた', None, None], [None, None, 'えたくなければ、', None], ['答', 'こた', None, True], [None, None, 'えなくても', True], ['構', 'かま', None, True], [None, None, 'いません', True], [None, None, '。', None]]
[['暇', 'ひま', None, None], [None, None, 'な', None], ['時', 'とき', None, None], [None, None, 'はゲームを', None], [None, None, 'やっても', True], ['構', 'かま', None, True], [None, None, 'わない', True], [None, None, '。', None]]

 42%|████▏     | 397/938 [03:56<05:11,  1.74it/s]

[['釣', 'つ', None, True], [None, None, 'れても', True], ['釣', 'つ', None, True], [None, None, 'れなくても', True], [None, None, '、', None], ['釣', 'つ', None, None], [None, None, 'りは', None], ['楽', 'たの', None, None], [None, None, 'しいらしい。', None]]
[['言', 'い', None, True], [None, None, 'っても', True], ['言', 'い', None, True], [None, None, 'わなくても', True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'はちゃんと', None], ['仕事', 'しごと', None, None], [None, None, 'ができるよ。', None]]
[[None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'を', None], ['持', 'も', None, True], [None, None, 'っていても', True], ['持', 'も', None, True], [None, None, 'っていなくても', True], [None, None, '、', None], ['幸', 'しあわ', None, None], [None, None, 'せになることは', None], ['可能', 'かのう', None, None], [None, None, 'です。', None]]
[['会', 'あ', None, True], [None, None, 'えても', True], ['会', 'あ', None, True], [None, None, 'えなくても', True], [None, None, '、', None], ['１８', 'じゅうはち', None, None], ['時', 'じ', None, None], [None, None, 'には', None], ['解散', 'かいさん', None, None], [None, None, 'して', None], ['帰', 'かえ', None, None], [None, None, 'りましょう。', None]]
[['助手', 'じょしゅ', None, None], [None, None, 'が', None], [None, None, 'いてもいなくても', True], [None, None, '、やることはたいして', None], ['変', 'か', None, None], [None, None, 'わらない。', None]]

 42%|████▏     | 398/938 [03:57<05:38,  1.60it/s]

[['僕', 'ぼく', None, None], [None, None, 'をバカにする', None], [None, None, 'んじゃない', True], [None, None, '！', None]]
[['先生', 'せんせい', None, None], [None, None, '：「カンニングをする', None], [None, None, 'んじゃない', True], [None, None, '！」', None]]
[['嘘', 'うそ', None, None], [None, None, 'をつく', None], [None, None, 'んじゃない', True], [None, None, '。', None]]
[[None, None, 'あなた、', None], ['仕事', 'しごと', None, None], [None, None, 'をサボる', None], [None, None, 'んじゃありません', True], [None, None, '。', None]]
[[None, None, 'まだ', None], ['子供', 'こども', None, None], [None, None, 'ですよ。', None], ['門限', 'もんげん', None, None], [None, None, 'を', None], ['破', 'やぶ', None, None], [None, None, 'る', None], [None, None, 'んじゃありません', True], [None, None, '。', None]]

 43%|████▎     | 399/938 [03:58<05:36,  1.60it/s]

[['彼', 'かれ', None, None], [None, None, 'が', None], ['嘘', 'うそ', None, None], [None, None, 'をつく', None], [None, None, 'わけがない', True], [None, None, '。', None]]
[[None, None, 'あんな', None], ['大', 'だい', None, None], [None, None, 'ニュース、', None], ['知', 'し', None, None], [None, None, 'らない', None], [None, None, 'わけがない', True], [None, None, '。', None]]
[['日本人', 'にほんじん', None, None], [None, None, 'ならそんなことを', None], ['言', 'い', None, None], [None, None, 'う', None], [None, None, 'わけがない', True], [None, None, '。', None]]
[[None, None, 'あれだけ', None], ['着込', 'きこ', None, None], [None, None, 'んだら', None], ['寒', 'さむ', None, None], [None, None, 'い', None], [None, None, 'わけがない', True], [None, None, '。', None]]
[[None, None, 'そんなやり', None], ['方', 'かた', None, None], [None, None, 'でうまくいく', None], [None, None, 'わけがない', True], [None, None, '。', None]]

 43%|████▎     | 400/938 [03:58<05:29,  1.63it/s]

[['付', 'つ', None, None], [None, None, 'き', None], ['合', 'あ', None, None], [None, None, 'う', None], [None, None, 'としたら', True], [None, None, '、', None], ['田中', 'たなか', None, None], [None, None, 'さんと', None], ['山田', 'やまだ', None, None], [None, None, 'さんどっちがいい？', None]]
[['無料', 'むりょう', None, None], [None, None, 'だとすれば', True], [None, None, '、', None], ['人', 'ひと', None, None], [None, None, 'が', None], ['大勢', 'おおぜい', None, None], ['来', 'く', None, None], [None, None, 'る。', None]]
[['留学', 'りゅうがく', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'とすると', True], [None, None, '、', None], ['論文', 'ろんぶん', None, None], [None, None, 'が', None], ['必要', 'ひつよう', None, None], [None, None, '。', None]]
[['買', 'か', None, None], [None, None, 'い', None], ['物', 'もの', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'かない', None], [None, None, 'としたら', True], [None, None, '、', None], ['晩御飯', 'ばんごはん', None, None], [None, None, 'はどうする？', None]]
[[None, None, 'もし', None], ['会', 'あ', None, None], [None, None, 'える', None], [None, None, 'としたら', True], [None, None, '、', None], ['明日', 'あした', None, None], [None, None, 'か', None], ['明後日', 'あさって', None, None], [None, None, 'だね。', None]]

 43%|████▎     | 401/938 [03:59<05:19,  1.68it/s]

[['私', 'わたし', None, None], [None, None, 'たちは', None], ['先生', 'せんせい', None, None], [None, None, 'として', True], [None, None, 'の', None], ['彼', 'かれ', None, None], [None, None, 'を', None], ['尊敬', 'そんけい', None, None], [None, None, 'します。', None]]
[['妻', 'つま', None, None], [None, None, 'として', True], [None, None, 'の', None], ['役割', 'やくわり', None, None], [None, None, 'をよく', None], ['果', 'は', None, None], [None, None, 'たしてくれている。', None]]
[['挨拶', 'あいさつ', None, None], [None, None, 'は', None], ['礼儀', 'れいぎ', None, None], [None, None, 'として', True], ['必要', 'ひつよう', None, None], [None, None, 'です。', None]]
[[None, None, 'ジョチはチンギス・カンの', None], ['長男', 'ちょうなん', None, None], [None, None, 'として', True], ['生', 'う', None, None], [None, None, 'まれた。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['嫁', 'よめ', None, None], [None, None, 'さんは', None], ['母', 'はは', None, None], [None, None, 'として', True], [None, None, '、そして', None], ['妻', 'つま', None, None], [None, None, 'として', True], [None, None, '、', None], ['本当', 'ほんとう', None, None], [None, None, 'にいい', None], ['人', 'ひと', None, None], [None, None, 'だ。', None]]

 43%|████▎     | 402/938 [03:59<05:17,  1.69it/s]

[['子供', 'こども', None, None], [None, None, 'にしては', True], ['静', 'しず', None, None], [None, None, 'かな', None], ['方', 'ほう', None, None], [None, None, 'だ。', None]]
[['力士', 'りきし', None, None], [None, None, 'にしては', True], ['結構', 'けっこう', None, None], ['細', 'ほそ', None, None], [None, None, 'いですね。', None]]
[['猫', 'ねこ', None, None], [None, None, 'にしては', True], ['大', 'おお', None, None], [None, None, 'きすぎませんか？', None]]
[[None, None, 'うどん', None], [None, None, 'にしては', True], ['随分', 'ずいぶん', None, None], ['細', 'ほそ', None, None], [None, None, 'い', None], ['麺', 'めん', None, None], [None, None, 'だな。', None]]
[['昔話', 'むかしばなし', None, None], [None, None, 'にしては', True], [None, None, '、', None], ['随分', 'ずいぶん', None, None], ['現実', 'げんじつ', None, None], ['的', 'てき', None, None], [None, None, 'な', None], ['話', 'はなし', None, None], [None, None, 'ですね。', None]]

 43%|████▎     | 403/938 [04:00<05:22,  1.66it/s]

[[None, None, 'テスラモデル', None], ['Ｓ', 'エス', None, None], [None, None, 'にしても', True], [None, None, '、この', None], ['値段', 'ねだん', None, None], [None, None, 'は', None], ['高', 'たか', None, None], [None, None, 'すぎる。', None]]
[[None, None, 'ジュースがいっぱいの', None], ['樽', 'たる', None, None], [None, None, 'を', None], ['頼', 'たの', None, None], [None, None, 'む', None], [None, None, 'にしても', True], [None, None, '、まだ', None], ['足', 'た', None, None], [None, None, 'りないと', None], ['思', 'おも', None, None], [None, None, 'います。', None]]
[['風邪', 'かぜ', None, None], [None, None, 'にしても', True], [None, None, '、', None], ['楽', 'たの', None, None], [None, None, 'しい', None], ['英語', 'えいご', None, None], [None, None, 'の', None], ['勉強', 'べんきょう', None, None], [None, None, 'はできるはずだ。', None]]
[['言', 'い', None, None], [None, None, 'う', None], [None, None, 'にしても', True], ['言', 'い', None, None], [None, None, 'い', None], ['方', 'かた', None, None], [None, None, 'というものがあるでしょ。', None]]
[['分', 'わ', None, None], [None, None, 'からない', None], [None, None, 'にしても', True], [None, None, '、', None], ['少', 'すこ', None, None], [None, None, 'しくらいは', None], ['調', 'しら', None, None], [None, None, 'べてくれてもいいじゃないか。', None]]

 43%|████▎     | 404/938 [04:01<05:17,  1.68it/s]

[['彼', 'かれ', None, None], [None, None, 'が', None], ['俳優', 'はいゆう', None, None], [None, None, 'だ', None], [None, None, 'というのは', True], ['事実', 'じじつ', None, True], [None, None, 'だ。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'が', None], ['二十歳', 'はたち', None, None], [None, None, 'だ', None], [None, None, 'というのは', True], ['事実', 'じじつ', None, True], [None, None, 'だ。', None]]
[['地球', 'ちきゅう', None, None], [None, None, 'が', None], ['丸', 'まる', None, None], [None, None, 'い', None], [None, None, 'というのは', True], ['事実', 'じじつ', None, True], [None, None, 'だ。', None]]
[['彼', 'かれ', None, None], [None, None, 'に', None], ['前科', 'ぜんか', None, None], [None, None, 'がある', None], [None, None, 'というのは', True], ['事実', 'じじつ', None, True], [None, None, 'だ。', None]]
[['父', 'ちち', None, None], [None, None, 'が', None], ['病気', 'びょうき', None, None], [None, None, 'だ', None], [None, None, 'というのは', True], ['事実', 'じじつ', None, True], [None, None, 'です。', None]]

 43%|████▎     | 405/938 [04:01<05:10,  1.72it/s]

[['法律', 'ほうりつ', None, None], [None, None, 'から', True], ['言', 'い', None, True], [None, None, 'うと', True], [None, None, '、それは', None], ['違反', 'いはん', None, None], [None, None, 'です。', None]]
[['結論', 'けつろん', None, None], [None, None, 'から', True], ['言', 'い', None, True], [None, None, 'うと', True], [None, None, '、', None], ['失敗', 'しっぱい', None, None], [None, None, 'です。', None]]
[['値段', 'ねだん', None, None], [None, None, 'から', True], ['言', 'い', None, True], [None, None, 'うと', True], [None, None, '、このコーヒーは', None], ['高', 'たか', None, None], [None, None, 'すぎるよ。', None]]
[['物価', 'ぶっか', None, None], [None, None, 'から', True], ['言', 'い', None, True], [None, None, 'うと', True], [None, None, '、この', None], ['地域', 'ちいき', None, None], [None, None, 'は', None], ['住', 'す', None, None], [None, None, 'みやすいですね。', None]]
[['景色', 'けしき', None, None], [None, None, 'から', True], ['言', 'い', None, True], [None, None, 'うと', True], [None, None, '、あの', None], ['山', 'やま', None, None], [None, None, 'は', None], ['最高', 'さいこう', None, None], [None, None, 'だよ。', None]]

 43%|████▎     | 406/938 [04:02<05:13,  1.70it/s]

[[None, None, 'それは', None], ['会社', 'かいしゃ', None, None], [None, None, 'に', True], ['取', 'と', None, True], [None, None, 'って', True], [None, None, 'もいいアイデアですね。', None]]
[['君', 'きみ', None, None], [None, None, 'に', True], ['取', 'と', None, True], [None, None, 'って', True], ['友達', 'ともだち', None, None], [None, None, 'を', None], ['作', 'つく', None, None], [None, None, 'ることは', None], ['簡単', 'かんたん', None, None], [None, None, 'だ。', None]]
[['誰', 'だれ', None, None], [None, None, 'に', True], ['取', 'と', None, True], [None, None, 'って', True], [None, None, 'も', None], ['親', 'おや', None, None], [None, None, 'は', None], ['大切', 'たいせつ', None, None], [None, None, 'です。', None]]
[['君', 'きみ', None, None], [None, None, 'に', True], ['取', 'と', None, True], [None, None, 'って', True], [None, None, 'は', None], ['簡単', 'かんたん', None, None], [None, None, 'でも、', None], ['僕', 'ぼく', None, None], [None, None, 'には', None], ['難', 'むずか', None, None], [None, None, 'しいよ。', None]]
[[None, None, 'お', None], ['父', 'とう', None, None], [None, None, 'さん', None], [None, None, 'に', True], ['取', 'と', None, True], [None, None, 'って', True], [None, None, '、', None], ['仕事', 'しごと', None, None], [None, None, 'は', None], ['大切', 'たいせつ', None, None], [None, None, 'だ。', None]]

 43%|████▎     | 407/938 [04:02<05:08,  1.72it/s]

[['以上', 'いじょう', None, None], [None, None, 'の', True], ['事', 'こと', None, True], [None, None, 'から', True], [None, None, '、この', None], ['結論', 'けつろん', None, None], [None, None, 'に', None], ['至', 'いた', None, None], [None, None, 'りました。', None]]
[[None, None, '「お', None], ['父', 'とお', None, None], [None, None, 'さん」と', None], ['呼', 'よ', None, None], [None, None, 'ばれている', None], ['事', 'こと', None, True], [None, None, 'から', True], [None, None, '、', None], ['子供', 'こども', None, None], [None, None, 'がいるのだと', None], ['分', 'わ', None, None], [None, None, 'かった。', None]]
[['指輪', 'ゆびわ', None, None], [None, None, 'をしている', None], ['事', 'こと', None, True], [None, None, 'から', True], [None, None, '、', None], ['既婚者', 'きこんしゃ', None, None], [None, None, 'だと', None], ['分', 'わ', None, None], [None, None, 'かった。', None]]
[['野球', 'やきゅう', None, None], [None, None, 'がとても', None], ['上手', 'じょうず', None, None], [None, None, 'な', True], ['事', 'こと', None, True], [None, None, 'から', True], [None, None, '、', None], ['将来', 'しょうらい', None, None], [None, None, 'は', None], ['有名', 'ゆうめい', None, None], [None, None, 'になりそうだ。', None]]
[['田代島', 'たしろじま', None, None], [None, None, 'は', None], ['猫', 'ねこ', None, None], [None, None, 'が', None], ['多', 'おお', None, None], [None, None, 'い', None], ['事', 'こと', None, True], [None, None, 'から', True], [None, None, '、', None], ['猫', 'ねこ', None, None], [None, None, 'の', None], ['島', 'しま', None, None], [None, None, 'と', None], ['呼', 'よ', None, None], [None, None, 'ばれるようになった。', None]]

 43%|████▎     | 408/938 [04:03<05:33,  1.59it/s]

[['今日', 'きょう', None, None], [None, None, 'は', None], ['暖', 'あたた', None, None], [None, None, 'かい', None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'うより', True], ['暑', 'あつ', None, None], [None, None, 'い。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'はかわいい', None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'うより', True], ['綺麗', 'きれい', None, None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['聡明', 'そうめい', None, None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'うより', True], [None, None, 'ずる', None], ['賢', 'がしこ', None, None], [None, None, 'い', None], ['人', 'ひと', None, None], [None, None, 'です。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['技術者', 'ぎじゅつしゃ', None, None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'うより', True], ['芸術家', 'げいじゅつか', None, None], [None, None, 'だ。', None]]
[[None, None, 'これは', None], ['悲', 'かな', None, None], [None, None, 'しさ', None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'うより', True], ['後悔', 'こうかい', None, None], [None, None, 'に', None], ['近', 'ちか', None, None], [None, None, 'い。', None]]

 44%|████▎     | 409/938 [04:04<05:21,  1.65it/s]

[['平日', 'へいじつ', None, None], [None, None, 'はもちろん', True], [None, None, '、', None], ['土日', 'どにち', None, None], [None, None, 'も', None], ['働', 'はたら', None, None], [None, None, 'いている。', None]]
[[None, None, 'ここのそば', None], ['屋', 'や', None, None], [None, None, 'はそば', None], [None, None, 'はもちろん', True], [None, None, '、カレーも', None], ['美味', 'おい', None, None], [None, None, 'しい。', None]]
[['彼', 'かれ', None, None], [None, None, 'は、', None], ['英語', 'えいご', None, None], [None, None, 'はもちろん', True], [None, None, '、', None], ['日本語', 'にほんご', None, None], [None, None, 'も', None], ['話', 'はな', None, None], [None, None, 'せる。', None]]
[['父', 'ちち', None, None], [None, None, 'は、スマホ', None], [None, None, 'はもちろん', True], [None, None, '、ガラケーも', None], ['持', 'も', None, None], [None, None, 'っていません。', None]]
[['勉強', 'べんきょう', None, None], [None, None, 'はもちろん', True], [None, None, '、', None], ['運動', 'うんどう', None, None], [None, None, 'もできるのだからすごい', None], ['人', 'ひと', None, None], [None, None, 'だ。', None]]

 44%|████▎     | 410/938 [04:04<05:14,  1.68it/s]

[[None, None, 'スーツ', None], [None, None, 'を', True], ['始', 'はじ', None, True], [None, None, 'め', True], [None, None, '、シャツや', None], ['靴', 'くつ', None, None], [None, None, 'も', None], ['新', 'あたら', None, None], [None, None, 'しくした。', None]]
[['小説', 'しょうせつ', None, None], [None, None, 'を', True], ['始', 'はじ', None, True], [None, None, 'め', True], [None, None, '、', None], ['本', 'ほん', None, None], [None, None, 'なら', None], ['何', 'なん', None, None], [None, None, 'でも', None], ['読', 'よ', None, None], [None, None, 'みます。', None]]
[['犬', 'いぬ', None, None], [None, None, 'を', True], ['始', 'はじ', None, True], [None, None, 'め', True], [None, None, '、', None], ['様々', 'さまざま', None, None], [None, None, 'な', None], ['動物', 'どうぶつ', None, None], [None, None, 'を', None], ['飼', 'か', None, None], [None, None, 'うようになった。', None]]
[['東京', 'とうきょう', None, None], [None, None, 'を', True], ['始', 'はじ', None, True], [None, None, 'め', True], [None, None, '、', None], ['国内', 'こくない', None, None], ['観光', 'かんこう', None, None], [None, None, 'ツアーに', None], ['行', 'い', None, None], [None, None, 'きます。', None]]
[[None, None, 'ヨーロッパ', None], [None, None, 'を', True], ['始', 'はじ', None, True], [None, None, 'め', True], [None, None, '、', None], ['世界', 'せかい', None, None], ['中', 'じゅう', None, None], [None, None, 'を', None], ['旅行', 'りょこう', None, None], [None, None, 'してみたいです。', None]]

 44%|████▍     | 411/938 [04:05<05:13,  1.68it/s]

[['失', 'うしな', None, True], [None, None, 'って', True], ['初', 'はじ', None, True], [None, None, 'めて', True], [None, None, '、その', None], ['価値', 'かち', None, None], [None, None, 'が', None], ['分', 'わ', None, None], [None, None, 'かりました。', None]]
[[None, None, 'やってみて', True], ['初', 'はじ', None, True], [None, None, 'めて', True], [None, None, '、', None], ['難', 'むずか', None, None], [None, None, 'しさを', None], ['痛感', 'つうかん', None, None], [None, None, 'しました。', None]]
[['話', 'はなし', None, None], [None, None, 'を', None], ['聞', 'き', None, True], [None, None, 'いてみて', True], ['初', 'はじ', None, True], [None, None, 'めて', True], [None, None, '、', None], ['君', 'きみ', None, None], [None, None, 'の', None], ['苦労', 'くろう', None, None], [None, None, 'を', None], ['知', 'し', None, None], [None, None, 'った。', None]]
[[None, None, 'テレビを', None], ['見', 'み', None, True], [None, None, 'て', True], ['初', 'はじ', None, True], [None, None, 'めて', True], [None, None, '、', None], ['地震', 'じしん', None, None], [None, None, 'があったことを', None], ['知', 'し', None, None], [None, None, 'った。', None]]
[['指摘', 'してき', None, None], [None, None, 'されて', True], ['初', 'はじ', None, True], [None, None, 'めて', True], [None, None, '、', None], ['寝癖', 'ねぐせ', None, None], [None, None, 'がついていることに', None], ['気', 'き', None, None], [None, None, 'づいた。', None]]

 44%|████▍     | 412/938 [04:05<05:05,  1.72it/s]

[['富士山', 'ふじさん', None, None], [None, None, 'の', None], ['頂上', 'ちょうじょう', None, None], [None, None, 'は', None], ['夏', 'なつ', None, None], [None, None, 'でさえ', True], ['寒', 'さむ', None, None], [None, None, 'い。', None]]
[[None, None, 'そんな', None], ['初歩的', 'しょほてき', None, None], [None, None, 'なことは、', None], ['子供', 'こども', None, None], [None, None, 'でさえ', True], ['知', 'し', None, None], [None, None, 'っている。', None]]
[['小', 'ちい', None, None], [None, None, 'さい', None], ['戦', 'たたか', None, None], [None, None, 'い', None], [None, None, 'さえ', True], [None, None, '、', None], ['私', 'わたし', None, None], [None, None, 'はしたことがない。', None]]
[[None, None, 'あのこと', None], [None, None, 'について', None], [None, None, 'さえ', True], ['知', 'し', None, None], [None, None, 'っているんです。', None]]
[['家族', 'かぞく', None, None], [None, None, 'さえも', True], ['応援', 'おうえん', None, None], [None, None, 'してくれないんです。', None]]

 44%|████▍     | 413/938 [04:06<04:59,  1.75it/s]

[['妹', 'いもうと', None, None], [None, None, 'は', None], ['暇', 'ひま', None, None], [None, None, 'さえあれば', True], [None, None, '、', None], ['運動', 'うんどう', None, None], [None, None, 'する。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['自分', 'じぶん', None, None], [None, None, 'さえ', True], ['良', 'よ', None, True], [None, None, 'ければ', True], [None, None, '、いいと', None], ['思', 'おも', None, None], [None, None, 'っている。', None]]
[['天気', 'てんき', None, None], [None, None, 'さえ', True], ['良', 'よ', None, True], [None, None, 'ければ', True], [None, None, 'テニスできるのに…', None]]
[['機会', 'きかい', None, None], [None, None, 'さえあれば', True], [None, None, '、', None], ['会', 'あ', None, None], [None, None, 'えるのに…', None]]
[['君', 'きみ', None, None], [None, None, 'さえいれば', True], [None, None, '、', None], ['他', 'ほか', None, None], [None, None, 'には', None], ['何', 'なに', None, None], [None, None, 'もいらない。', None]]

 44%|████▍     | 414/938 [04:06<05:03,  1.73it/s]

[['若', 'わか', None, None], [None, None, 'い', None], ['頃', 'ころ', None, None], [None, None, 'は、いろんな', None], ['苦労', 'くろう', None, None], [None, None, 'を', None], [None, None, 'したものだ', True], [None, None, '。', None]]
[['子供', 'こども', None, None], [None, None, 'の', None], ['頃', 'ころ', None, None], [None, None, 'はよく', None], ['海', 'うみ', None, None], [None, None, 'に', None], ['泳', 'およ', None, None], [None, None, 'ぎに', None], ['行', 'い', None, True], [None, None, 'ったものだ', True], [None, None, '。', None]]
[['昔', 'むかし', None, None], [None, None, 'はよく、', None], ['車', 'くるま', None, None], [None, None, 'を', None], ['運転', 'うんてん', None, None], [None, None, 'して', None], ['遠', 'とお', None, None], [None, None, 'くに', None], ['出', 'で', None, True], [None, None, 'かけたものだ', True], [None, None, '。', None]]
[['子供', 'こども', None, None], [None, None, 'の', None], ['頃', 'ころ', None, None], [None, None, 'は', None], ['授業', 'じゅぎょう', None, None], ['中', 'ちゅう', None, None], [None, None, '、よく', None], ['居', 'い', None, None], ['眠', 'ねむ', None, None], [None, None, 'りを', None], [None, None, 'したものだ', True], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'が', None], ['子', 'こ', None, None], [None, None, 'どもの', None], ['頃', 'ころ', None, None], [None, None, '、よく', None], ['父', 'ちち', None, None], [None, None, 'に', None], ['映画', 'えいが', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'に', None], ['連', 'つ', None, None], [None, None, 'れていって', None], [None, None, 'もらったものだ', True], [None, None, '。', None]]

 44%|████▍     | 415/938 [04:07<05:05,  1.71it/s]

[[None, None, 'さて', True], [None, None, '、', None], ['順番', 'じゅんばん', None, None], [None, None, 'に', None], ['並', 'なら', None, None], [None, None, 'べましたか。', None]]
[[None, None, 'さて', True], [None, None, '、', None], ['出発', 'しゅっぱつ', None, None], [None, None, 'してもいいでしょうか。', None]]
[[None, None, 'さて', True], [None, None, '、', None], ['行', 'い', None, None], [None, None, 'きましょうか。', None]]
[[None, None, 'さて', True], [None, None, '、', None], ['準備', 'じゅんび', None, None], [None, None, 'はできましたか。', None]]
[[None, None, 'さて', True], [None, None, '、', None], ['次', 'つぎ', None, None], [None, None, 'のテーマは', None], ['何', 'なに', None, None], [None, None, 'にしますか？', None]]

 44%|████▍     | 416/938 [04:08<05:08,  1.69it/s]

[['彼', 'かれ', None, None], [None, None, 'よりも', None], ['寧', 'むし', None, True], [None, None, 'ろ', True], [None, None, 'あなたに', None], ['来', 'き', None, None], [None, None, 'てほしい。', None]]
[['僕', 'ぼく', None, None], [None, None, 'はコーヒーより', None], ['寧', 'むし', None, True], [None, None, 'ろ', True], ['紅茶', 'こうちゃ', None, None], [None, None, 'が', None], ['飲', 'の', None, None], [None, None, 'みたい。', None]]
[['明日', 'あした', None, None], [None, None, 'より', None], ['寧', 'むし', None, True], [None, None, 'ろ', True], ['今日', 'きょう', None, None], ['行', 'い', None, None], [None, None, 'きたいんですが、', None], ['駄目', 'だめ', None, None], [None, None, 'ですか？', None]]
[['韓国', 'かんこく', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'くより', None], ['寧', 'むし', None, True], [None, None, 'ろ', True], ['日本', 'にほん', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'きたい。', None]]
[['事態', 'じたい', None, None], [None, None, 'は', None], ['寧', 'むし', None, True], [None, None, 'ろ', True], ['好転', 'こうてん', None, None], [None, None, 'してきたように', None], ['思', 'おも', None, None], [None, None, 'える。', None]]

 44%|████▍     | 417/938 [04:08<05:01,  1.73it/s]

[['明日', 'あした', None, None], ['何時', 'なんじ', None, None], [None, None, 'でも', None], ['良', 'い', None, None], [None, None, 'いんだって。', None], ['詰', 'つ', None, True], [None, None, 'まり', True], [None, None, '、', None], ['夜遅', 'よるおそ', None, None], [None, None, 'くなっても', None], ['良', 'い', None, None], [None, None, 'いらしい。', None]]
[['彼', 'かれ', None, None], [None, None, 'はいつも', None], ['約束', 'やくそく', None, None], [None, None, 'を', None], ['破', 'やぶ', None, None], [None, None, 'る。', None], ['詰', 'つ', None, True], [None, None, 'まり', True], [None, None, '、', None], ['私', 'わたし', None, None], [None, None, 'のこと', None], ['好', 'す', None, None], [None, None, 'きじゃないよね。', None]]
[[None, None, 'この', None], ['車', 'くるま', None, None], [None, None, 'は', None], ['電気', 'でんき', None, None], ['自動車', 'じどうしゃ', None, None], [None, None, 'です。', None], ['詰', 'つ', None, True], [None, None, 'まり', True], [None, None, '、ガソリンが', None], ['要', 'い', None, None], [None, None, 'らないです。', None]]
[['詰', 'つ', None, True], [None, None, 'まり', True], [None, None, 'それはどういうことですか？もっと', None], ['簡単', 'かんたん', None, None], [None, None, 'に', None], ['説明', 'せつめい', None, None], [None, None, 'してください。', None]]
[['今', 'いま', None, None], [None, None, 'は', None], ['失業', 'しつぎょう', None, None], [None, None, 'しています。', None], ['詰', 'つ', None, True], [None, None, 'まり', True], [None, None, '、あまりお', None], ['金', 'かね', None, None], [None, None, 'がないということです。', None]]

 45%|████▍     | 418/938 [04:09<05:04,  1.71it/s]

[['僕', 'ぼく', None, None], [None, None, 'は', None], ['肉', 'にく', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べない。', None], ['即', 'すなわ', None, True], [None, None, 'ち', True], ['菜食', 'さいしょく', None, None], ['主義者', 'しゅぎしゃ', None, None], [None, None, 'だ。', None]]
[['和食', 'わしょく', None, None], [None, None, '、', None], ['即', 'すなわ', None, True], [None, None, 'ち', True], ['焼', 'や', None, None], [None, None, 'き', None], ['魚', 'ざかな', None, None], [None, None, 'やお', None], ['味噌汁', 'みそしる', None, None], [None, None, 'のようなものが', None], ['食', 'た', None, None], [None, None, 'べられるお', None], ['店', 'みせ', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'きたいんです。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['学校', 'がっこう', None, None], [None, None, 'の', None], ['先生', 'せんせい', None, None], [None, None, '、', None], ['即', 'すなわ', None, True], [None, None, 'ち', True], ['教育者', 'きょういくしゃ', None, None], [None, None, 'だ。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['私', 'わたし', None, None], [None, None, 'の', None], ['母', 'はは', None, None], [None, None, 'の', None], ['弟', 'おとうと', None, None], [None, None, 'の', None], ['息子', 'むすこ', None, None], [None, None, '、', None], ['即', 'すなわ', None, True], [None, None, 'ち', True], ['従兄弟', 'いとこ', None, None], [None, None, 'です。', None]]
[['５', 'ご', None, None], ['割引', 'わりび', None, None], [None, None, 'きの', None], ['商品', 'しょうひん', None, None], [None, None, 'とは、', None], ['即', 'すなわ', None, True], [None, None, 'ち', True], ['元', 'もと', None, None], [None, None, 'の', None], ['値段', 'ねだん', None, None], [None, None, 'の', None], ['半額', 'はんがく', None, None], [None, None, 'ということだ。', None]]

 45%|████▍     | 419/938 [04:09<05:06,  1.69it/s]

[['欲張', 'よくば', None, None], [None, None, 'ると', None], ['却', 'かえ', None, True], [None, None, 'って', True], ['損', 'そん', None, None], [None, None, 'をしますよ。', None]]
[[None, None, '「やれ」と', None], ['言', 'い', None, None], [None, None, 'われると、', None], ['却', 'かえ', None, True], [None, None, 'って', True], [None, None, 'やる', None], ['気', 'き', None, None], [None, None, 'がなくなる。', None]]
[['情', 'なさ', None, None], [None, None, 'けが', None], ['却', 'かえ', None, True], [None, None, 'って', True], ['仇', 'あだ', None, None], [None, None, 'となることもある。', None]]
[['僕', 'ぼく', None, None], [None, None, 'がいると', None], ['却', 'かえ', None, True], [None, None, 'って', True], ['邪魔', 'じゃま', None, None], [None, None, 'になると', None], ['思', 'おも', None, None], [None, None, 'うんです。', None]]
[[None, None, 'お', None], ['手伝', 'てつだ', None, None], [None, None, 'いのつもりでしょうが、', None], ['却', 'かえ', None, True], [None, None, 'って', True], ['迷惑', 'めいわく', None, None], [None, None, 'です。', None]]

 45%|████▍     | 420/938 [04:10<05:00,  1.73it/s]

[[None, None, 'あなたの', None], ['顔', 'かお', None, None], [None, None, 'は', None], [None, None, 'まるで', True], ['幽霊', 'ゆうれい', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'た', None], [None, None, 'ようだ', None], [None, None, '。', None]]
[['全部', 'ぜんぶ', None, None], [None, None, 'の', None], ['家事', 'かじ', None, None], [None, None, 'をしてくれたの？', None], [None, None, 'まるで', None], ['天使', 'てんし', None, None], [None, None, 'のよう', True], [None, None, 'だ！', None]]
[[None, None, 'あの', None], ['二人', 'ふたり', None, None], [None, None, 'は', None], ['仲', 'なか', None, None], [None, None, 'がいい。', None], [None, None, 'まるで', True], ['兄弟', 'きょうだい', None, None], [None, None, 'のようだ', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は、', None], [None, None, 'まるで', True], ['山', 'やま', None, None], [None, None, 'のように', None], ['積', 'つ', None, None], [None, None, 'まれた', None], ['本', 'ほん', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'て', None], ['驚', 'おどろ', None, None], [None, None, 'いた。', None]]
[[None, None, 'こんな', None], ['日', 'ひ', None, None], [None, None, 'がくるなんて、', None], [None, None, 'まるで', True], ['夢', 'ゆめ', None, None], [None, None, 'のようだ', None], [None, None, '。', None]]

 45%|████▍     | 421/938 [04:11<04:56,  1.74it/s]

[['分', 'わ', None, None], [None, None, 'かる', None], [None, None, 'ような', True], ['気', 'き', None, True], [None, None, 'がする', True], [None, None, '。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'に', None], ['騙', 'だま', None, None], [None, None, 'された', None], [None, None, 'ような', True], ['気', 'き', None, True], [None, None, 'がする', True], [None, None, '。', None]]
[['今回', 'こんかい', None, None], [None, None, 'は', None], ['合格', 'ごうかく', None, None], [None, None, 'する', None], [None, None, 'ような', True], ['気', 'き', None, True], [None, None, 'がしています', True], [None, None, '。', None]]
[['道', 'みち', None, None], [None, None, 'を', None], ['間違', 'まちが', None, None], [None, None, 'えた', None], [None, None, 'ような', True], ['気', 'き', None, True], [None, None, 'がします', True], [None, None, '。', None]]
[[None, None, 'この', None], ['問題', 'もんだい', None, None], [None, None, '、', None], ['分', 'わ', None, None], [None, None, 'かった', None], [None, None, 'ような', True], ['気', 'き', None, True], [None, None, 'がする', True], [None, None, 'ぞ。', None]]

 45%|████▍     | 422/938 [04:11<04:54,  1.75it/s]

[[None, None, 'とても', True], ['考', 'かんが', None, None], [None, None, 'えられ', None], [None, None, 'ない', None], [None, None, '。', None]]
[[None, None, 'とても', True], ['観光', 'かんこう', None, None], [None, None, 'でき', None], [None, None, 'ない', None], [None, None, '。', None]]
[[None, None, 'とても', True], ['観察', 'かんさつ', None, None], [None, None, 'でき', None], [None, None, 'ない', None], [None, None, '。', None]]
[[None, None, 'とても', True], ['完成', 'かんせい', None, None], [None, None, 'させられ', None], [None, None, 'ない', None], [None, None, '。', None]]
[[None, None, 'とても', True], ['記憶', 'きおく', None, None], [None, None, 'でき', None], [None, None, 'ない', None], [None, None, '。', None]]

 45%|████▌     | 423/938 [04:12<04:48,  1.78it/s]

[[None, None, 'トムが', None], ['悪', 'わる', None, None], [None, None, 'いとは', None], ['別', 'べつ', None, True], [None, None, 'にいっていない', True], [None, None, 'よ。', None]]
[[None, None, 'それは', None], ['別', 'べつ', None, True], [None, None, 'に', True], ['悪', 'わる', None, None], [None, None, 'いことでは', None], [None, None, 'ない', None], [None, None, 'よ。', None]]
[['別', 'べつ', None, True], [None, None, 'に', True], ['夢', 'ゆめ', None, None], [None, None, 'がないわけでは', None], [None, None, 'ないよ', None], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'はそんなに', None], ['音楽', 'おんがく', None, None], [None, None, 'がうるさくても、', None], ['別', 'べつ', None, True], [None, None, 'に', True], ['気', 'き', None, True], [None, None, 'にしない', True], [None, None, '。', None]]
[['別', 'べつ', None, True], [None, None, 'に', True], ['楽', 'たの', None, True], [None, None, 'しくない', True], [None, None, 'わけではない。', None], ['少', 'すこ', None, None], [None, None, 'し', None], ['疲', 'つか', None, None], [None, None, 'れているだけだ。', None]]

 45%|████▌     | 424/938 [04:12<04:43,  1.81it/s]

[['田中', 'たなか', None, None], [None, None, 'さんはサッカー', None], [None, None, 'ばかりでなく', True], ['水泳', 'すいえい', None, None], [None, None, 'も', None], ['上手', 'じょうず', None, None], [None, None, 'です。', None]]
[['日本語', 'にほんご', None, None], [None, None, 'は', None], ['漢字', 'かんじ', None, None], [None, None, 'ばかりでなく', True], [None, None, '、ひらがなとカタカナもある。', None]]
[['悪', 'わる', None, None], [None, None, 'いこと', None], [None, None, 'ばかりではなく', True], [None, None, '、', None], ['楽', 'たの', None, None], [None, None, 'しいことを', None], ['考', 'かんが', None, None], [None, None, 'えてみよう。', None]]
[['自分', 'じぶん', None, None], [None, None, 'ばかりでなく', True], [None, None, '、', None], ['家族', 'かぞく', None, None], [None, None, 'にも', None], ['迷惑', 'めいわく', None, None], [None, None, 'をかけてしまった。', None]]
[['勉強', 'べんきょう', None, None], [None, None, 'ばかりでなく', True], [None, None, '、', None], ['運動', 'うんどう', None, None], [None, None, 'もした', None], ['方', 'ほう', None, None], [None, None, 'がいいと', None], ['思', 'おも', None, None], [None, None, 'います。', None]]

 45%|████▌     | 425/938 [04:13<04:44,  1.80it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], ['兄弟', 'きょうだい', None, None], [None, None, 'ではなくて', True], ['従兄弟', 'いとこ', None, None], [None, None, 'です。', None]]
[['魚', 'さかな', None, None], [None, None, 'じゃなくて', True], ['肉', 'にく', None, None], [None, None, 'が', None], ['食', 'た', None, None], [None, None, 'べたい。', None]]
[['科学', 'かがく', None, None], [None, None, 'ではなくて', True], ['化学', 'かがく', None, None], [None, None, 'です。', None]]
[['火曜日', 'かようび', None, None], [None, None, 'ではなくて', True], ['水曜日', 'すいようび', None, None], [None, None, 'です。', None]]
[[None, None, 'あの', None], ['選手', 'せんしゅ', None, None], [None, None, 'は', None], ['天才', 'てんさい', None, None], [None, None, 'ではなくて', True], [None, None, '、', None], ['努力家', 'どりょくか', None, None], [None, None, 'だ。', None]]

 45%|████▌     | 426/938 [04:13<04:46,  1.79it/s]

[[None, None, 'アイスクリーム', None], [None, None, 'だけじゃなくて', True], [None, None, '、プリン', None], [None, None, 'も', None], ['買', 'か', None, None], [None, None, 'いました。', None]]
[['机', 'つくえ', None, None], [None, None, 'だけじゃなくて', True], [None, None, '、', None], ['椅子', 'いす', None, None], [None, None, 'も', None], [None, None, 'ほしい。', None]]
[['市場', 'いちば', None, None], [None, None, 'だけでなく', True], [None, None, '、スーパーに', None], [None, None, 'も', None], [None, None, 'いきませんか。', None]]
[['君', 'きみ', None, None], [None, None, 'だけじゃなく', True], [None, None, '、', None], ['僕', 'ぼく', None, None], [None, None, 'も', None], ['悪', 'わる', None, None], [None, None, 'かったと', None], ['思', 'おも', None, None], [None, None, 'っている。', None]]
[['体', 'からだ', None, None], [None, None, 'だけじゃなく', True], [None, None, '、', None], ['心', 'こころ', None, None], [None, None, 'も', None], ['疲', 'つか', None, None], [None, None, 'れてしまった。', None]]

 46%|████▌     | 427/938 [04:14<04:46,  1.78it/s]

[[None, None, 'この', None], ['時間', 'じかん', None, None], [None, None, '、', None], ['医師', 'いし', None, None], [None, None, 'は', None], ['一人', 'ひとり', None, None], [None, None, 'だけしか', True], [None, None, 'いません', None], [None, None, '。', None]]
[['椅子', 'いす', None, None], [None, None, 'はここにあるもの', None], [None, None, 'だけしか', True], [None, None, 'ありません', None], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'には', None], ['従兄弟', 'いとこ', None, None], [None, None, 'が', None], ['一人', 'ひとり', None, None], [None, None, 'だけしか', True], [None, None, 'いません', None], [None, None, '。', None]]
[['僕', 'ぼく', None, None], [None, None, 'は', None], ['日本語', 'にほんご', None, None], [None, None, 'だけしか', True], [None, None, 'できません', None], [None, None, '。', None]]
[['現金', 'げんきん', None, None], [None, None, 'は', None], ['今', 'いま', None, None], ['１０００', 'せん', None, None], ['円', 'えん', None, None], [None, None, 'だけしか', True], [None, None, 'ありません', None], [None, None, '。', None]]

 46%|████▌     | 428/938 [04:14<04:52,  1.74it/s]

[['困', 'こま', None, None], [None, None, 'っている', None], ['人', 'ひと', None, None], [None, None, 'を', None], ['助', 'たす', None, None], [None, None, 'けるべき', None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'うのは', True], ['言', 'い', None, True], [None, None, 'うまでもない', True], [None, None, '。', None]]
[[None, None, 'エネルギーの', None], ['無駄', 'むだ', None, None], ['使', 'づか', None, None], [None, None, 'いをやめれば、', None], ['電気代', 'でんきだい', None, None], [None, None, 'が', None], ['下', 'さ', None, None], [None, None, 'がる', None], [None, None, 'ことは', True], ['言', 'い', None, True], [None, None, 'うまでもない', True], [None, None, '。', None]]
[[None, None, 'ともちゃんの', None], ['大阪', 'おおさか', None, None], [None, None, 'での', None], ['知名度', 'ちめいど', None, None], [None, None, 'が', None], ['高', 'たか', None, None], [None, None, 'い', None], [None, None, 'ことは', True], ['言', 'い', None, True], [None, None, 'うまでもない', True], [None, None, '。', None]]
[[None, None, '「にせあい」がこの', None], ['世代', 'せだい', None, None], [None, None, 'の', None], ['最良', 'さいりょう', None, None], [None, None, 'の', None], ['漫画', 'まんが', None, None], [None, None, 'の', None], ['一', 'ひと', None, None], [None, None, 'つである', None], [None, None, 'ことは', True], ['言', 'い', None, True], [None, None, 'うまでもない', True], [None, None, 'だろう。', None]]
[['生', 'い', None, None], [None, None, 'きるのに', None], ['酸素', 'さんそ', None, None], [None, None, 'が', None], ['必要', 'ひつよう', None, None], [None, None, 'なことは', True], ['言', 'い', None, True], [None, None, 'うまでもない', True], [None, None, '。', None]]

 46%|████▌     | 429/938 [04:15<04:50,  1.75it/s]

[['嘘', 'うそ', None, None], [None, None, 'をついたら', None], ['決', 'けっ', None, True], [None, None, 'してゆるさない', True], [None, None, '。', None]]
[['何', 'なに', None, None], [None, None, 'があっても、', None], ['決', 'けっ', None, True], [None, None, 'して', True], ['諦', 'あきら', None, True], [None, None, 'めない', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['決', 'けっ', None, True], [None, None, 'して', True], ['妥協', 'だきょう', None, None], [None, None, 'し', None], [None, None, 'ない', None], ['人', 'ひと', None, None], [None, None, 'だ。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'は', None], ['決', 'けっ', None, True], [None, None, 'して', True], ['嘘', 'うそ', None, None], [None, None, 'をつか', None], [None, None, 'ない', None], [None, None, '。', None]]
[[None, None, 'あなたのことは', None], ['決', 'けっ', None, True], [None, None, 'して', True], ['忘', 'わす', None, True], [None, None, 'れません', True], [None, None, '。', None]]

 46%|████▌     | 430/938 [04:16<04:55,  1.72it/s]

[['僕', 'ぼく', None, None], [None, None, 'はその', None], ['問題', 'もんだい', None, None], [None, None, 'を', None], ['黙', 'だま', None, None], [None, None, 'って', None], ['見', 'み', None, None], ['過', 'す', None, None], [None, None, 'ごす', None], ['訳', 'わけ', None, True], [None, None, 'には', True], ['行', 'い', None, True], [None, None, 'かない', True], [None, None, '。', None]]
[[None, None, 'まだやるべきことがあるから、', None], ['死', 'し', None, None], [None, None, 'ぬ', None], ['訳', 'わけ', None, True], [None, None, 'には', True], ['行', 'い', None, True], [None, None, 'かない', True], [None, None, 'んだ！', None]]
[['大統領', 'だいとうりょう', None, None], [None, None, 'に', None], ['頼', 'たの', None, None], [None, None, 'まれたので', None], ['断', 'ことわ', None, None], [None, None, 'る', None], ['訳', 'わけ', None, True], [None, None, 'には', True], ['行', 'い', None, True], [None, None, 'かない', True], [None, None, '。', None]]
[[None, None, 'それは', None], ['捨', 'す', None, None], [None, None, 'てる', None], ['訳', 'わけ', None, True], [None, None, 'には', True], ['行', 'い', None, True], [None, None, 'きません', True], [None, None, '。', None], ['大切', 'たいせつ', None, None], [None, None, 'な', None], ['人', 'ひと', None, None], [None, None, 'からもらったんです。', None]]
[[None, None, 'まだ', None], ['許', 'ゆる', None, None], [None, None, 'す', None], ['訳', 'わけ', None, True], [None, None, 'には', True], ['行', 'い', None, True], [None, None, 'きません', True], [None, None, '。ちゃんと', None], ['反省', 'はんせい', None, None], [None, None, 'してないでしょ。', None]]

 46%|████▌     | 431/938 [04:16<04:51,  1.74it/s]

[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['好', 'す', None, None], [None, None, 'きな', None], ['男', 'おとこ', None, None], [None, None, 'を', None], ['諦', 'あきら', None, True], [None, None, 'めようとしない', True], [None, None, '。', None]]
[['皆', 'みんな', None, None], [None, None, 'に', None], ['嫌', 'きら', None, None], [None, None, 'われているのに、', None], ['性格', 'せいかく', None, None], [None, None, 'を', None], ['変', 'か', None, True], [None, None, 'えようとしない', True], [None, None, 'の？', None]]
[[None, None, 'こんなに', None], ['天気', 'てんき', None, None], [None, None, 'がいいのに、うちの', None], ['息子', 'むすこ', None, None], [None, None, 'は', None], ['外', 'そと', None, None], [None, None, 'に', None], ['出', 'で', None, True], [None, None, 'ようとしない', True], [None, None, '。', None]]
[[None, None, 'これだけ', None], ['説明', 'せつめい', None, None], [None, None, 'しても', None], ['信', 'しん', None, True], [None, None, 'じようとしない', True], [None, None, 'ならもういいよ。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['現実', 'げんじつ', None, None], [None, None, 'を', None], ['見', 'み', None, True], [None, None, 'ようとしない', True], [None, None, '。', None], ['逃', 'に', None, None], [None, None, 'げてばかりだ。', None]]

 46%|████▌     | 432/938 [04:17<05:35,  1.51it/s]

[[None, None, 'もしかしたら', True], [None, None, '…', None], ['病気', 'びょうき', None, None], [None, None, 'かもしれない', None], [None, None, 'んだ…', None]]
[[None, None, 'もしかしたら', True], ['採用', 'さいよう', None, None], [None, None, 'される', None], [None, None, 'かもしれません', None], [None, None, '。', None]]
[[None, None, 'もしかしたら', True], ['今晩', 'こんばん', None, None], ['雪', 'ゆき', None, None], [None, None, 'になる', None], [None, None, 'かもしれない', None], [None, None, '。', None]]
[[None, None, 'もしかしたら', True], ['気', 'き', None, None], [None, None, 'が', None], ['変', 'か', None, None], [None, None, 'わって、', None], ['来', 'き', None, None], [None, None, 'てくれる', None], [None, None, 'かもしれない', None], [None, None, '。', None]]
[[None, None, '「', None], [None, None, 'もしかしたら', True], ['嫌', 'きら', None, None], [None, None, 'われてるのかな？」なんて', None], ['思', 'おも', None, None], [None, None, 'ってしまうことがある。', None]]

 46%|████▌     | 433/938 [04:18<05:19,  1.58it/s]

[['仮令', 'たとえ', None, True], ['雪', 'ゆき', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'らなく', None], [None, None, 'ても', None], [None, None, '、スノーボードをしに', None], ['行', 'い', None, None], [None, None, 'く。', None]]
[['仮令', 'たとえ', None, True], ['笑', 'わら', None, None], [None, None, 'われ', None], [None, None, 'ても', None], [None, None, '、', None], ['正', 'ただ', None, None], [None, None, 'しいことをしたいんだ。', None]]
[['仮令', 'たとえ', None, True], ['叱', 'しか', None, None], [None, None, 'られ', None], [None, None, 'ても', None], [None, None, '、', None], ['譲', 'ゆず', None, None], [None, None, 'れないことがある。', None]]
[['仮令', 'たとえ', None, True], [None, None, 'あなたが', None], ['行', 'い', None, None], [None, None, 'かなく', None], [None, None, 'ても', None], [None, None, '、', None], ['僕', 'ぼく', None, None], [None, None, 'は', None], ['行', 'い', None, None], [None, None, 'きます。', None]]
[['仮令', 'たとえ', None, True], ['嬉', 'うれ', None, None], [None, None, 'し', None], [None, None, 'く', None], [None, None, 'ても', None], [None, None, '、', None], ['笑', 'わら', None, None], [None, None, 'ってはいけない', None], ['時', 'とき', None, None], [None, None, 'もある。', None]]

 46%|████▋     | 434/938 [04:18<05:10,  1.63it/s]

[['幸', 'しあわ', None, None], [None, None, 'せ', None], [None, None, 'な', True], ['事', 'こと', None, True], [None, None, 'に', True], [None, None, '、', None], ['来年', 'らいねん', None, None], ['結婚', 'けっこん', None, None], [None, None, 'します。', None]]
[['不思議', 'ふしぎ', None, None], [None, None, 'な', True], ['事', 'こと', None, True], [None, None, 'に', True], [None, None, '、', None], ['最近', 'さいきん', None, None], ['物事', 'ものごと', None, None], [None, None, 'がすべてうまくいく。', None]]
[['嬉', 'うれ', None, None], [None, None, 'しい', None], ['事', 'こと', None, True], [None, None, 'に', True], [None, None, '、みんなが', None], ['協力', 'きょうりょく', None, None], [None, None, 'してくれるようになりました。', None]]
[['嬉', 'うれ', None, None], [None, None, 'しい', None], ['事', 'こと', None, True], [None, None, 'に', True], ['日本語', 'にほんご', None, None], ['能力', 'のうりょく', None, None], ['試験', 'しけん', None, None], [None, None, 'に', None], ['合格', 'ごうかく', None, None], [None, None, 'しました。', None]]
[['驚', 'おどろ', None, None], [None, None, 'いた', None], ['事', 'こと', None, True], [None, None, 'に', True], [None, None, '、', None], ['六', 'ろっ', None, None], ['ヶ月', 'かげつ', None, None], [None, None, 'で', None], ['赤', 'あか', None, None], [None, None, 'ちゃんが', None], ['初', 'はじ', None, None], [None, None, 'めて', None], ['歩', 'ある', None, None], [None, None, 'いた。', None]]

 46%|████▋     | 435/938 [04:19<05:03,  1.66it/s]

[[None, None, 'これを', None], [None, None, 'どれだけ', None], ['待', 'ま', None, None], [None, None, 'っていた', None], ['事', 'こと', None, True], [None, None, 'か', True], [None, None, '。', None]]
[['文', 'ぶん', None, None], [None, None, 'プロがあって', None], [None, None, 'どんなに', None], ['便利', 'べんり', None, None], [None, None, 'な', True], ['事', 'こと', None, True], [None, None, 'か', True], [None, None, '！', None]]
[['君', 'きみ', None, None], [None, None, 'に', None], ['会', 'あ', None, None], [None, None, 'えて', None], [None, None, 'どんなに', None], ['嬉', 'うれ', None, None], [None, None, 'しかった', None], ['事', 'こと', None, True], [None, None, 'か', True], [None, None, '。', None]]
[['君', 'きみ', None, None], [None, None, 'に', None], ['会', 'あ', None, None], [None, None, 'える', None], ['日', 'ひ', None, None], [None, None, 'を、', None], [None, None, 'どんなに', None], ['夢', 'ゆめ', None, None], ['見', 'み', None, None], [None, None, 'た', None], ['事', 'こと', None, True], [None, None, 'か', True], [None, None, '。', None]]
[[None, None, 'このプロテインの', None], [None, None, 'なんと', None], ['美味', 'おい', None, None], [None, None, 'しい', None], ['事', 'こと', None, True], [None, None, 'か', True], [None, None, '！すごく', None], ['飲', 'の', None, None], [None, None, 'みやすい。', None]]

 46%|████▋     | 436/938 [04:20<05:26,  1.54it/s]

[[None, None, 'なぜ', None], ['彼', 'かれ', None, None], [None, None, 'はそれをしたの', None], [None, None, 'かというと', True], [None, None, 'いまだに', None], ['私', 'わたし', None, None], ['自身', 'じしん', None, None], [None, None, 'もわからない。', None]]
[[None, None, 'どうして', None], [None, None, 'そのブランドのスマホは', None], ['買', 'か', None, None], [None, None, 'いたくない', None], [None, None, 'かっていうと', True], [None, None, '、', None], ['前', 'まえ', None, None], [None, None, 'に', None], ['一回', 'いっかい', None, None], ['買', 'か', None, None], [None, None, 'ったけど', None], ['二週間', 'にしゅうかん', None, None], [None, None, 'で', None], ['壊', 'こわ', None, None], [None, None, 'れた', None], [None, None, 'んだ', None], [None, None, 'よね.', None]]
[[None, None, 'キリンには', None], ['長', 'なが', None, None], [None, None, 'い', None], ['首', 'くび', None, None], [None, None, 'がある。', None], [None, None, 'なぜかというと', True], [None, None, '、その', None], ['長', 'なが', None, None], [None, None, 'い', None], ['首', 'くび', None, None], [None, None, 'を', None], ['使', 'つか', None, None], [None, None, 'って', None], ['高', 'たか', None, None], [None, None, 'い', None], ['木', 'き', None, None], [None, None, 'の', None], ['上', 'うえ', None, None], [None, None, 'にある', None], ['葉', 'は', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べる', None], [None, None, 'ためだ', None], [None, None, '。', None]]
[[None, None, 'どうして', None], [None, None, 'バスを', None], ['使', 'つか', None, None], [None, None, 'うよりは', None], ['自転車', 'じてんしゃ', None, None], [None, None, 'を', None], ['使', 'つか', None, None], [None, None, 'うようにしている', None], [None, None, 'かというと', True], [None, None, '、', None], ['自転車', 'じてんしゃ', None, None], [None, None, 'はより', None], ['安', 'やす', None, None], [None, None, 'いばかりではなくて', None], ['交通', 'こうつう', None, None], ['渋滞', 'じゅうたい', None, None], [None, None, 'の', None], ['中', 'なか', None, None], [None, None, 'でもより', None], ['速', 'はや', None, None], [None, None, 'い', None], [None, None, 'からです', None], [None, None, '。', None]]
[['法律', 'ほうりつ', None, None], [None, None, 'によって', None], ['犬', 'いぬ', None, None], [None, None, 'や', None], ['猫', 'ねこ', None, None], [None, None, 'にチップをつけることが', None], ['要求', 'ようきゅう', None, None], [None, None, 'されています。', None], [None, None, 'なぜかというと', True], [None, None, 'ペットが', None], ['捨', 'す', None, None], [None, None, 'てられた', None], ['場合', 'ばあい', None, None], [None, None, 'にすぐにオーナーがわかるようにする', None], [None, None, 'ためです', None], [None, None, '。', None]]

 47%|████▋     | 437/938 [04:20<05:37,  1.48it/s]

[['一方', 'いっぽう', None, None], [None, None, '、', None], ['自分', 'じぶん', None, None], [None, None, 'にとってどちら', None], [None, None, 'かというと', True], ['丈夫', 'じょうぶ', None, None], [None, None, 'な', None], ['車', 'くるま', None, None], [None, None, 'のほうが', None], ['優', 'すぐ', None, None], [None, None, 'れていると', None], ['思', 'おも', None, None], [None, None, 'う。', None]]
[[None, None, 'イオさん', None], [None, None, '：「どっちのほうがいいの？」', None], [None, None, 'ツミキさん', None], [None, None, '：「どどどっち', None], [None, None, 'かっていうと', True], [None, None, '、こっちのほう...」', None]]
[[None, None, 'イチカさん', None], [None, None, '：「ミクちゃんは', None], ['好', 'す', None, None], [None, None, 'きな', None], ['人', 'ひと', None, None], [None, None, 'がいるみたいに', None], ['見', 'み', None, None], [None, None, 'えるよ。」', None], [None, None, 'イツキさん', None], [None, None, '：「', None], ['誰', 'だれ', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'かっていうと', True], [None, None, 'きっとフウタロウくんでしょう。」', None]]
[[None, None, 'ヨツバさん', None], [None, None, '：「その', None], ['犬', 'いぬ', None, None], [None, None, 'はどのくらい', None], ['大', 'おお', None, None], [None, None, 'きいの？」', None], [None, None, 'フウカさん', None], [None, None, '：「どのくらい', None], ['大', 'おお', None, None], [None, None, 'きい', None], [None, None, 'かというと', True], [None, None, '....えーと....こんなに', None], ['大', 'おお', None, None], [None, None, 'きいくらいでしょう。」', None]]
[['何', 'なん', None, None], [None, None, 'でこんなことになった', None], [None, None, 'かというと', True], [None, None, '、すべてが', None], ['始', 'はじ', None, None], [None, None, 'まったのは', None], ['一', 'いっ', None, None], ['週間', 'しゅうかん', None, None], [None, None, 'ほど', None], ['前', 'まえ', None, None], [None, None, 'に', None], ['学校', 'がっこう', None, None], [None, None, 'から', None], ['帰', 'かえ', None, None], [None, None, 'っていた', None], ['時', 'とき', None, None], [None, None, '...', None]]

 47%|████▋     | 438/938 [04:21<05:43,  1.46it/s]

[['統計', 'とうけい', None, None], [None, None, 'で', True], ['言', 'い', None, True], [None, None, 'うと', True], [None, None, '、', None], ['客', 'きゃく', None, None], [None, None, 'の', None], ['７０', 'ななじゅっ', None, None], ['％', 'パーセント', None, None], [None, None, 'が', None], ['観光客', 'かんこうきゃく', None, None], [None, None, 'だ。', None]]
[[None, None, 'この', None], ['年', 'とし', None, None], [None, None, 'をとっていそうな', None], ['猫', 'ねこ', None, None], [None, None, 'は', None], ['人間', 'にんげん', None, None], [None, None, 'の', None], ['年齢', 'ねんれい', None, None], [None, None, 'で', True], ['言', 'い', None, True], [None, None, 'うと', True], ['８４', 'はちじゅうよん', None, None], ['歳', 'さい', None, None], [None, None, 'ぐらいです。', None]]
[[None, None, 'つまり、「hmmm」は', None], ['日本語', 'にほんご', None, None], [None, None, 'で', True], ['言', 'い', None, True], [None, None, 'うと', True], [None, None, '「うーん」に', None], ['当', 'あ', None, None], [None, None, 'たります。', None]]
[[None, None, 'わかりやすい', None], ['言葉', 'ことば', None, None], [None, None, 'で', True], ['言', 'い', None, True], [None, None, 'うと', True], ['俺', 'おれ', None, None], [None, None, 'は', None], ['上司', 'じょうし', None, None], [None, None, 'だが、', None], ['君', 'きみ', None, None], [None, None, 'は', None], ['部下', 'ぶか', None, None], [None, None, 'だ。', None]]
[[None, None, '「I am batman」って', None], ['日本語', 'にほんご', None, None], [None, None, 'で', True], ['言', 'い', None, True], [None, None, 'うと', True], [None, None, 'どうなる？', None]]

 47%|████▋     | 439/938 [04:22<05:20,  1.56it/s]

[[None, None, 'それぞれのテストを', None], ['２', 'に', None, None], ['回', 'かい', None, None], ['宛', 'ずつ', None, True], [None, None, 'チェックした。', None]]
[['静', 'しず', None, None], [None, None, 'かにして', None], ['下', 'くだ', None, None], [None, None, 'さい！', None], ['一人', 'ひとり', None, None], ['宛', 'ずつ', None, True], [None, None, 'お', None], ['願', 'ねが', None, None], [None, None, 'いします！', None]]
[['１０', 'じゅう', None, None], ['宛', 'ずつ', None, True], [None, None, 'に', None], ['分', 'わ', None, None], [None, None, 'けて', None], ['数', 'かぞ', None, None], [None, None, 'えてください。', None]]
[['一人', 'ひとり', None, None], ['宛', 'ずつ', None, True], ['入場', 'にゅうじょう', None, None], [None, None, 'できる。', None]]
[['生徒', 'せいと', None, None], [None, None, 'は', None], ['１０', 'じゅう', None, None], ['人', 'にん', None, None], ['宛', 'ずつ', None, True], [None, None, 'のグループに', None], ['分', 'わ', None, None], [None, None, 'かれてバスに', None], ['乗', 'の', None, None], [None, None, 'った。', None]]

 47%|████▋     | 440/938 [04:22<05:46,  1.44it/s]

[[None, None, 'この', None], ['車', 'くるま', None, None], [None, None, 'は', None], ['私', 'わたし', None, None], [None, None, 'のより', None], [None, None, 'ずっと', True], [None, None, 'よく', None], ['見', 'み', None, None], [None, None, 'える。', None]]
[[None, None, '「でも', None], ['勇者', 'ゆうしゃ', None, None], [None, None, 'さまは', None], [None, None, 'ずっと', True], ['強', 'つよ', None, None], [None, None, 'いし...」', None]]
[['僕', 'ぼく', None, None], [None, None, 'よりも', None], [None, None, 'ずっと', True], ['年上', 'としうえ', None, None], [None, None, 'だということ、', None], ['信', 'しん', None, None], [None, None, 'じられないよ。', None]]
[['太陽', 'たいよう', None, None], [None, None, 'のほうが', None], ['地球', 'ちきゅう', None, None], [None, None, 'より', None], [None, None, 'ずっと', True], ['大', 'おお', None, None], [None, None, 'きいです。', None]]
[[None, None, 'コンピュータは', None], ['以前', 'いぜん', None, None], [None, None, 'に', None], ['比', 'くら', None, None], [None, None, 'べて', None], [None, None, 'ずっと', True], ['使', 'つか', None, None], [None, None, 'いやすくなった。', None]]

 47%|████▋     | 441/938 [04:23<05:58,  1.39it/s]

[['床', 'ゆか', None, None], [None, None, 'が', None], ['泥', 'どろ', None, None], [None, None, 'だらけ', True], [None, None, 'になった。', None]]
[['汗', 'あせ', None, None], [None, None, 'だらけ', True], [None, None, 'でもかまわない。', None]]
[[None, None, 'あの', None], ['壁', 'かべ', None, None], [None, None, 'はいつも', None], ['落書', 'らくが', None, None], [None, None, 'き', None], [None, None, 'だらけ', True], [None, None, 'だ。', None]]
[['欠点', 'けってん', None, None], [None, None, 'だらけ', True], [None, None, 'の', None], ['人', 'ひと', None, None], [None, None, 'はいない。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'の', None], ['話', 'はなし', None, None], [None, None, 'は', None], ['矛盾', 'むじゅん', None, None], [None, None, 'だらけ', True], [None, None, 'だ。', None]]

 47%|████▋     | 442/938 [04:24<05:51,  1.41it/s]

[['日本語', 'にほんご', None, None], [None, None, 'を', None], ['話', 'はな', None, None], [None, None, 'せます。', None], ['尤', 'もっと', None, True], [None, None, 'も', True], [None, None, '、', None], ['少', 'すこ', None, None], [None, None, 'しだけです', None], [None, None, 'が', None], [None, None, '。', None]]
[[None, None, 'みんなラーメンが', None], ['好', 'す', None, None], [None, None, 'きだ。', None], ['尤', 'もっと', None, True], [None, None, 'も', True], [None, None, '、', None], ['例外', 'れいがい', None, None], [None, None, 'もありますよ。', None]]
[[None, None, 'それはいい', None], ['質問', 'しつもん', None, None], [None, None, 'です。', None], ['尤', 'もっと', None, True], [None, None, 'も', True], [None, None, '、', None], ['十分', 'じゅうぶん', None, None], [None, None, 'に', None], ['説明', 'せつめい', None, None], [None, None, 'できません', None], [None, None, 'が', None], [None, None, '。', None]]
[['君', 'きみ', None, None], [None, None, 'は', None], ['正', 'ただ', None, None], [None, None, 'しい。オレの', None], ['一番', 'いちばん', None, None], ['好', 'す', None, None], [None, None, 'きなものは、ラーメンだ。', None], ['尤', 'もっと', None, True], [None, None, 'も', True], [None, None, 'いつも', None], ['食', 'た', None, None], [None, None, 'べられるわけではない。', None]]
[[None, None, 'とうとう', None], ['仕事', 'しごと', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'つけた。', None], ['尤', 'もっと', None, True], [None, None, 'も', True], ['今', 'いま', None, None], [None, None, 'では', None], ['自分', 'じぶん', None, None], [None, None, 'の', None], ['時間', 'じかん', None, None], [None, None, 'がなくなった', None], [None, None, 'けど', None], [None, None, '。', None]]

 47%|████▋     | 443/938 [04:25<05:55,  1.39it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], ['再', 'ふたた', None, True], [None, None, 'び', True], ['紙', 'かみ', None, None], ['飛行機', 'ひこうき', None, None], [None, None, 'を', None], ['飛', 'と', None, None], [None, None, 'ばした。', None]]
[['免許', 'めんきょ', None, None], [None, None, 'をなくして、', None], ['再', 'ふたた', None, True], [None, None, 'び', True], ['発行', 'はっこう', None, None], [None, None, 'してもらった。', None]]
[['来年', 'らいねん', None, None], [None, None, 'も', None], ['再', 'ふたた', None, True], [None, None, 'び', True], [None, None, 'ここに', None], ['来', 'き', None, None], [None, None, 'たいです。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['再', 'ふたた', None, True], [None, None, 'び', True], ['夜空', 'よぞら', None, None], [None, None, 'を', None], ['眺', 'なが', None, None], [None, None, 'めた。', None]]
[['今', 'いま', None, None], ['家', 'いえ', None, None], [None, None, 'に', None], ['帰', 'かえ', None, None], [None, None, 'ったばかりなのに、', None], ['再', 'ふたた', None, True], [None, None, 'び', True], ['呼', 'よ', None, None], [None, None, 'び', None], ['出', 'だ', None, None], [None, None, 'された。', None]]

 47%|████▋     | 444/938 [04:25<05:32,  1.48it/s]

[[None, None, 'このスープは', None], ['魚', 'さかな', None, None], [None, None, 'の', None], [None, None, 'うま', True], ['味', 'み', None, True], [None, None, 'が', None], ['感', 'かん', None, None], [None, None, 'じられるね。', None]]
[['人', 'ひと', None, None], [None, None, 'の', None], ['痛', 'いた', None, True], [None, None, 'み', True], [None, None, 'がわかる', None], ['人間', 'にんげん', None, None], [None, None, 'になろう。', None]]
[['弱', 'よわ', None, True], [None, None, 'み', True], [None, None, 'を', None], ['人', 'ひと', None, None], [None, None, 'に', None], ['見', 'み', None, None], [None, None, 'せたくない。', None]]
[[None, None, 'この', None], ['文章', 'ぶんしょう', None, None], [None, None, 'は', None], ['全然', 'ぜんぜん', None, None], ['面白', 'おもしろ', None, True], ['味', 'み', None, True], [None, None, 'がないな。', None]]
[['渋', 'しぶ', None, True], ['味', 'み', None, True], [None, None, 'がある', None], ['食', 'た', None, None], [None, None, 'べ', None], ['物', 'もの', None, None], [None, None, 'は', None], ['苦手', 'にがて', None, None], [None, None, 'だ。', None]]

 47%|████▋     | 445/938 [04:26<05:15,  1.56it/s]

[[None, None, 'うちのぽちはこの', None], ['箱', 'はこ', None, None], [None, None, 'と', True], ['同', 'おな', None, True], [None, None, 'じくらいの', True], ['大', 'おお', None, None], [None, None, 'きさだ。', None]]
[[None, None, 'いつか、トモキ', None], [None, None, 'と', True], ['同', 'おな', None, True], [None, None, 'じくらいの', True], ['身長', 'しんちょう', None, None], [None, None, 'になりたいな。', None]]
[[None, None, 'うちの', None], ['娘', 'むすめ', None, None], [None, None, 'はきみの', None], ['息子', 'むすこ', None, None], [None, None, 'と', True], ['同', 'おな', None, True], [None, None, 'じくらいの', True], ['年齢', 'ねんれい', None, None], [None, None, 'だね？', None]]
[[None, None, 'ぼくにとってきみは', None], ['金', 'きん', None, None], [None, None, 'と', True], ['同', 'おな', None, True], [None, None, 'じくらい', True], ['貴重', 'きちょう', None, None], [None, None, 'だよ。', None]]
[[None, None, 'このトランペットはピラミッド', None], [None, None, 'と', True], ['同', 'おな', None, True], [None, None, 'じくらい', True], ['古', 'ふる', None, None], [None, None, 'いです。', None]]

 48%|████▊     | 446/938 [04:26<05:22,  1.53it/s]

[['君', 'きみ', None, None], [None, None, 'と', True], ['同', 'おな', None, True], [None, None, 'じで', True], [None, None, 'その', None], ['意見', 'いけん', None, None], [None, None, 'に', None], ['賛成', 'さんせい', None, None], [None, None, 'だ。', None]]
[[None, None, 'フィンランド', None], [None, None, 'と', True], ['違', 'ちが', None, True], [None, None, 'って', True], [None, None, '、ハワイは', None], ['一年中', 'いちねんじゅう', None, None], ['暖', 'あたた', None, None], [None, None, 'かい。', None]]
[['天気', 'てんき', None, None], ['予報', 'よほう', None, None], [None, None, 'と', True], ['違', 'ちが', None, True], [None, None, 'って', True], ['今日', 'きょう', None, None], [None, None, 'はとても', None], ['暖', 'あたた', None, None], [None, None, 'かい。', None]]
[['大統領', 'だいとうりょう', None, None], [None, None, 'と', True], ['違', 'ちが', None, True], [None, None, 'って', True], [None, None, '、', None], ['副大統領', 'ふくだいとうりょう', None, None], [None, None, 'は', None], ['優', 'やさ', None, None], [None, None, 'しい。', None]]
[['先生', 'せんせい', None, None], [None, None, 'と', True], ['同', 'おな', None, True], [None, None, 'じで', True], [None, None, '、', None], ['僕', 'ぼく', None, None], [None, None, 'も', None], ['日本語', 'にほんご', None, None], [None, None, 'が', None], ['大好', 'だいす', None, None], [None, None, 'きです。', None]]

 48%|████▊     | 447/938 [04:27<05:30,  1.49it/s]

[[None, None, 'ラーメンもまた、', None], ['寿司', 'すし', None, None], [None, None, 'と', True], ['並', 'なら', None, True], [None, None, 'んで', True], ['人気', 'にんき', None, None], [None, None, 'の', None], ['日本食', 'にほんしょく', None, None], [None, None, 'だ。', None]]
[[None, None, 'この', None], ['芸術作品', 'げいじゅつさくひん', None, None], [None, None, 'はモナ・リザ', None], [None, None, 'と', True], ['並', 'なら', None, True], [None, None, 'んで', True], ['高', 'たか', None, None], [None, None, 'く', None], ['評価', 'ひょうか', None, None], [None, None, 'されている。', None]]
[['喫煙', 'きつえん', None, None], [None, None, 'は', None], ['揚', 'あ', None, None], [None, None, 'げ', None], ['物', 'もの', None, None], [None, None, 'と', True], ['並', 'なら', None, True], [None, None, 'んで', True], ['癌', 'がん', None, None], [None, None, 'を', None], ['引', 'ひ', None, None], [None, None, 'き', None], ['起', 'お', None, None], [None, None, 'こす', None], ['確率', 'かくりつ', None, None], [None, None, 'が', None], ['高', 'たか', None, None], [None, None, 'い。', None]]
[['東京', 'とうきょう', None, None], ['大学', 'だいがく', None, None], [None, None, 'は', None], ['慶應義塾', 'けいおうぎじゅく', None, None], ['大学', 'だいがく', None, None], [None, None, 'や', None], ['早稲田', 'わせだ', None, None], ['大学', 'だいがく', None, None], [None, None, 'と', True], ['並', 'なら', None, True], [None, None, 'んで', True], ['日本', 'にほん', None, None], ['屈指', 'くっし', None, None], [None, None, 'の', None], ['大学', 'だいがく', None, None], [None, None, 'として', None], ['考', 'かんが', None, None], [None, None, 'えられている。', None]]
[['宮崎', 'みやざき', None, None], ['駿', 'はやお', None, None], [None, None, 'は', None], ['小津', 'おず', None, None], ['安二郎', 'やすじろう', None, None], [None, None, 'や', None], ['黒澤', 'くろさわ', None, None], ['明', 'あきら', None, None], [None, None, 'と', True], ['並', 'なら', None, True], [None, None, 'んで', True], ['日本', 'にほん', None, None], ['三大', 'さんだい', None, None], ['監督', 'かんとく', None, None], [None, None, 'の', None], ['一人', 'ひとり', None, None], [None, None, 'と', None], ['言', 'い', None, None], [None, None, 'われている。', None]]

 48%|████▊     | 448/938 [04:28<05:09,  1.58it/s]

[[None, None, 'あの', None], ['顔', 'かお', None, None], [None, None, 'は', None], ['日本人', 'にほんじん', None, None], [None, None, 'に', True], ['違', 'ちが', None, True], [None, None, 'いない', True], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['病気', 'びょうき', None, None], [None, None, 'に', True], ['違', 'ちが', None, True], [None, None, 'いない', True], [None, None, '。', None]]
[[None, None, 'こんなに', None], ['遅', 'おそ', None, None], [None, None, 'いなんて…、', None], ['何', 'なに', None, None], [None, None, 'かあった', None], [None, None, 'に', True], ['違', 'ちが', None, True], [None, None, 'いない', True], [None, None, '。', None]]
[[None, None, 'あの', None], ['言', 'い', None, None], [None, None, 'い', None], ['方', 'かた', None, None], [None, None, 'だと、', None], ['何', 'なに', None, None], [None, None, 'か', None], ['隠', 'かく', None, None], [None, None, 'している', None], [None, None, 'に', True], ['違', 'ちが', None, True], [None, None, 'いない', True], [None, None, '。', None]]
[['大雪', 'おおゆき', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'って', None], ['大変', 'たいへん', None, None], [None, None, 'だった', None], [None, None, 'に', True], ['違', 'ちが', None, True], [None, None, 'いない', True], [None, None, '。', None]]

 48%|████▊     | 449/938 [04:28<05:26,  1.50it/s]

[[None, None, 'これは', None], ['１個', 'いっこ', None, None], ['当', 'あ', None, True], [None, None, 'たり', True], ['５０', 'ごじゅっ', None, None], [None, None, 'キロカロリーあります。', None]]
[[None, None, 'このコーヒーは', None], ['一缶', 'ひとかん', None, None], ['当', 'あ', None, True], [None, None, 'たり', True], [None, None, '￥', None], ['１３０', 'ひゃくさんじゅう', None, None], [None, None, '（', None], ['税込', 'ぜいこみ', None, None], [None, None, '）。', None]]
[['一個', 'いっこ', None, None], ['当', 'あ', None, True], [None, None, 'たり', True], [None, None, 'の', None], ['代金', 'だいきん', None, None], [None, None, 'は', None], ['千', 'せん', None, None], ['円', 'えん', None, None], [None, None, 'です。', None]]
[['一人', 'ひとり', None, None], ['当', 'あ', None, True], [None, None, 'たり', True], ['三', 'さん', None, None], ['個', 'こ', None, None], [None, None, 'ずつパンを', None], ['配', 'くば', None, None], [None, None, 'ります。', None]]
[['１日', 'いちにち', None, None], ['当', 'あ', None, True], [None, None, 'たり', True], ['１０００', 'せん', None, None], ['円', 'えん', None, None], [None, None, 'の', None], ['手当', 'てあ', None, None], [None, None, 'てが', None], ['出', 'で', None, None], [None, None, 'ます。', None]]

 48%|████▊     | 450/938 [04:29<05:34,  1.46it/s]

[[None, None, 'おじと', None], ['呼', 'よ', None, None], [None, None, 'んでいるけど、', None], ['実', 'じつ', None, None], [None, None, 'はいとこ', None], [None, None, 'に', True], ['当', 'あ', None, True], [None, None, 'たる', True], [None, None, 'んだ。', None]]
[['江戸', 'えど', None, None], [None, None, 'という', None], ['都市', 'とし', None, None], [None, None, 'は', None], ['現在', 'げんざい', None, None], [None, None, 'の', None], ['東京', 'とうきょう', None, None], [None, None, 'に', True], ['当', 'あ', None, True], [None, None, 'たる', True], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'の', None], ['長男', 'ちょうなん', None, None], [None, None, 'のリンゴパンはパムの', None], ['父', 'ちち', None, None], [None, None, 'に', True], ['当', 'あ', None, True], [None, None, 'たる', True], [None, None, '。', None]]
[[None, None, '「', None], ['地下鉄', 'ちかてつ', None, None], [None, None, '」', None], [None, None, 'に', True], ['当', 'あ', None, True], [None, None, 'たる', True], ['言葉', 'ことば', None, None], [None, None, 'は、イギリスでは「underground」で、アメリカでは「subway」です。', None]]
[[None, None, 'ドイツでは', None], ['日本', 'にほん', None, None], [None, None, 'の', None], ['首相', 'しゅしょう', None, None], [None, None, 'に', True], ['当', 'あ', None, True], [None, None, 'たる', True], ['役職', 'やくしょく', None, None], [None, None, 'を「Bundeskanzler 」と', None], ['呼', 'よ', None, None], [None, None, 'んでいる。', None]]

 48%|████▊     | 451/938 [04:30<05:37,  1.44it/s]

[['疲', 'つか', None, None], [None, None, 'れた', None], ['時', 'とき', None, None], [None, None, 'は', None], ['寝', 'ね', None, None], [None, None, 'る', None], [None, None, 'に', True], ['限', 'かぎ', None, True], [None, None, 'る', True], [None, None, '。', None]]
[['寒', 'さむ', None, None], [None, None, 'い', None], ['夜', 'よる', None, None], [None, None, 'は', None], ['鍋', 'なべ', None, None], [None, None, 'に', True], ['限', 'かぎ', None, True], [None, None, 'る', True], [None, None, '。', None]]
[[None, None, 'やっぱり', None], ['秋刀魚', 'さんま', None, None], [None, None, 'は', None], ['目黒', 'めぐろ', None, None], [None, None, 'に', True], ['限', 'かぎ', None, True], [None, None, 'る', True], [None, None, '。', None]]
[['仕事', 'しごと', None, None], [None, None, 'の', None], ['後', 'あと', None, None], [None, None, 'はジュース', None], [None, None, 'に', True], ['限', 'かぎ', None, True], [None, None, 'る', True], [None, None, '。', None]]
[['登山', 'とざん', None, None], [None, None, 'をするなら、', None], ['富士山', 'ふじさん', None, None], [None, None, 'に', True], ['限', 'かぎ', None, True], [None, None, 'る', True], [None, None, '。', None]]

 48%|████▊     | 452/938 [04:31<05:45,  1.41it/s]

[[None, None, 'にわとりは', None], ['鳥', 'とり', None, None], [None, None, 'ですが、', None], ['飛', 'と', None, None], [None, None, 'べる', None], [None, None, 'とは', True], ['限', 'かぎ', None, True], [None, None, 'りません', True], [None, None, '。', None]]
[['誰', 'だれ', None, None], [None, None, 'もがお', None], ['寿司', 'すし', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き', None], [None, None, 'だとは', True], ['限', 'かぎ', None, True], [None, None, 'らない', True], [None, None, '。', None]]
[[None, None, 'たとえどんなに', None], ['緻密', 'ちみつ', None, None], [None, None, 'な', None], ['計画', 'けいかく', None, None], [None, None, 'を', None], ['立', 'た', None, None], [None, None, 'てても、うまくいく', None], [None, None, 'とは', True], ['限', 'かぎ', None, True], [None, None, 'らない', True], [None, None, '。', None]]
[['君', 'きみ', None, None], [None, None, 'の', None], ['言', 'い', None, None], [None, None, 'うことがいつも', None], ['正', 'ただ', None, None], [None, None, 'しい', None], [None, None, 'とは', True], ['限', 'かぎ', None, True], [None, None, 'らない', True], [None, None, 'でしょ。', None]]
[['勉強', 'べんきょう', None, None], [None, None, 'ができても、', None], ['頭', 'あたま', None, None], [None, None, 'がいい', None], [None, None, 'とは', True], ['限', 'かぎ', None, True], [None, None, 'らない', True], [None, None, '。', None]]

 48%|████▊     | 453/938 [04:31<05:47,  1.40it/s]

[['父', 'ちち', None, None], [None, None, 'は', None], ['滅多', 'めった', None, True], [None, None, 'に', True], [None, None, 'テレビを', None], ['見', 'み', None, None], [None, None, 'ない', None], [None, None, '。', None]]
[[None, None, 'こんなにいい', None], ['話', 'はな', None, None], [None, None, 'しは', None], ['滅多', 'めった', None, True], [None, None, 'にない', True], [None, None, '。', None]]
[['滅多', 'めった', None, True], [None, None, 'に', True], ['泣', 'な', None, None], [None, None, 'か', None], [None, None, 'ない', None], ['彼', 'かれ', None, None], [None, None, 'が', None], ['泣', 'な', None, None], [None, None, 'いていた。', None]]
[['僕', 'ぼく', None, None], [None, None, 'のおじいちゃんは', None], ['滅多', 'めった', None, True], [None, None, 'に', True], ['笑', 'わら', None, None], [None, None, 'わ', None], [None, None, 'ない', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['滅多', 'めった', None, True], [None, None, 'に', True], ['忘', 'わす', None, None], [None, None, 'れ', None], [None, None, 'ない', None], [None, None, 'のに、', None], ['今日', 'きょう', None, None], [None, None, 'はどうしたんだろう？', None]]

 48%|████▊     | 454/938 [04:32<05:20,  1.51it/s]

[['今日', 'きょう', None, None], [None, None, 'は', None], ['冬', 'ふゆ', None, None], [None, None, 'の', True], ['割', 'わり', None, True], [None, None, 'に', True], ['暖', 'あたた', None, None], [None, None, 'かい。', None]]
[['高', 'たか', None, None], [None, None, 'い', None], ['食', 'た', None, None], [None, None, 'べ', None], ['物', 'もの', None, None], [None, None, 'の', True], ['割', 'わり', None, True], [None, None, 'に', True], [None, None, '、', None], ['美味', 'おい', None, None], [None, None, 'しくなさそう。', None]]
[['私', 'わたし', None, None], [None, None, 'はたくさん', None], ['勉強', 'べんきょう', None, None], [None, None, 'した', None], ['割', 'わり', None, True], [None, None, 'に', True], [None, None, '、テストの', None], ['点数', 'てんすう', None, None], [None, None, 'が', None], ['悪', 'わる', None, None], [None, None, 'かった。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'は', None], ['頭', 'あたま', None, None], [None, None, 'が', None], ['良', 'い', None, None], [None, None, 'い', None], ['割', 'わり', None, True], [None, None, 'に', True], [None, None, '、コミュニケーションが', None], ['苦手', 'にがて', None, None], [None, None, 'です。', None]]
[['疲', 'つか', None, None], [None, None, 'れている', None], ['割', 'わり', None, True], [None, None, 'に', True], [None, None, 'は、かなり', None], ['動', 'うご', None, None], [None, None, 'けた', None], ['方', 'ほう', None, None], [None, None, 'だと', None], ['思', 'おも', None, None], [None, None, 'います。', None]]

 49%|████▊     | 455/938 [04:32<05:06,  1.58it/s]

[['一度', 'いちど', None, None], [None, None, 'に', None], ['二', 'ふた', None, None], [None, None, 'つのことを', None], [None, None, 'しようとする', True], [None, None, 'な', None], [None, None, '。', None]]
[[None, None, 'ひよこは', None], ['親', 'おや', None, None], [None, None, 'のように', None], ['飛', 'と', None, True], [None, None, 'ぼうとしても', True], [None, None, '、できなかった。', None]]
[['答', 'こた', None, True], [None, None, 'えようとした', True], [None, None, 'のに、', None], ['隣', 'となり', None, None], [None, None, 'の', None], ['人', 'ひと', None, None], [None, None, 'に', None], ['遮', 'さえぎ', None, None], [None, None, 'られた。', None]]
[['見', 'み', None, True], [None, None, 'ようとした', True], [None, None, 'わけではないのに、', None], ['見', 'み', None, None], [None, None, 'えてしまいました。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], ['止', 'と', None, True], [None, None, 'めようとした', True], [None, None, 'のに、', None], ['言', 'い', None, None], [None, None, 'うことを', None], ['聞', 'き', None, None], [None, None, 'いてくれないんです。', None]]

 49%|████▊     | 456/938 [04:33<05:42,  1.41it/s]

[['兎', 'うさぎ', None, None], [None, None, 'の', None], ['世話', 'せわ', None, None], [None, None, 'を', None], [None, None, 'しようとしたが', True], ['逃', 'に', None, None], [None, None, 'げられた。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['徹夜', 'てつや', None, None], [None, None, 'しようとしたけれど', True], ['寝', 'ね', None, None], [None, None, 'てしまった。', None]]
[['説得', 'せっとく', None, None], [None, None, 'しようとしたが', True], [None, None, '、', None], ['失敗', 'しっぱい', None, None], [None, None, 'した。', None]]
[[None, None, 'お', None], ['弁当', 'べんとう', None, None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べようとしたが', True], [None, None, '、', None], ['箸', 'はし', None, None], [None, None, 'が', None], ['入', 'はい', None, None], [None, None, 'っていなかった。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], ['彼女', 'かのじょ', None, None], [None, None, 'の', None], ['手伝', 'てつだ', None, None], [None, None, 'いを', None], [None, None, 'しようとしたが', True], [None, None, '、', None], ['断', 'ことわ', None, None], [None, None, 'られた。', None]]

 49%|████▊     | 457/938 [04:34<05:38,  1.42it/s]

[['言', 'い', None, True], [None, None, 'うまでもない', True], [None, None, 'けど', None], [None, None, '、それが', None], ['恋', 'こい', None, None], [None, None, 'だった。', None]]
[['言', 'い', None, True], [None, None, 'うまでもなく', True], [None, None, 'もうこんなこと', None], ['知', 'し', None, None], [None, None, 'ってるよね。', None]]
[[None, None, 'しかし、', None], ['言', 'い', None, True], [None, None, 'うまでもなく', True], [None, None, '、', None], ['私', 'わたし', None, None], [None, None, 'たちはいつものように', None], ['負', 'ま', None, None], [None, None, 'けた。', None]]
[['言', 'い', None, True], [None, None, 'うまでもない', True], [None, None, 'ことだが', None], [None, None, '、', None], ['文章', 'ぶんしょう', None, None], [None, None, 'を', None], ['読', 'よ', None, None], [None, None, 'みやすくするために、', None], ['括弧', 'かっこ', None, None], [None, None, 'は', None], ['使', 'つか', None, None], [None, None, 'われている。', None]]
[[None, None, 'さだおさんの', None], ['妻', 'つま', None, None], [None, None, 'のえみさんは', None], ['英語', 'えいご', None, None], [None, None, 'は', None], ['言', 'い', None, True], [None, None, 'うまでもなく', True], [None, None, '、', None], ['韓国語', 'かんこくご', None, None], [None, None, 'も', None], ['話', 'はな', None, None], [None, None, 'せます。', None]]

 49%|████▉     | 458/938 [04:35<05:45,  1.39it/s]

[['今回', 'こんかい', None, None], [None, None, 'のテストは', None], ['受', 'う', None, True], [None, None, 'かりそうもない', True], [None, None, '。', None]]
[[None, None, 'このテーブルは', None], ['重', 'おも', None, None], [None, None, 'たいから、', None], ['一人', 'ひとり', None, None], [None, None, 'で', None], ['運', 'はこ', None, True], [None, None, 'べそうもない', True], [None, None, '。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, '、', None], ['僕', 'ぼく', None, None], [None, None, 'の', None], ['意見', 'いけん', None, None], [None, None, 'を', None], ['聞', 'き', None, True], [None, None, 'いてくれそうもない', True], [None, None, '。', None]]
[[None, None, 'そんなすごい', None], ['技', 'わざ', None, None], [None, None, '、', None], ['僕', 'ぼく', None, None], [None, None, 'には', None], [None, None, 'できそうもない', True], [None, None, '。', None]]
[['予報', 'よほう', None, None], [None, None, 'は', None], ['雨', 'あめ', None, None], [None, None, 'だけど、', None], ['全然', 'ぜんぜん', None, None], ['降', 'ふ', None, True], [None, None, 'りそうもない', True], [None, None, '。', None]]

 49%|████▉     | 459/938 [04:35<05:27,  1.46it/s]

[['Ａ', 'エー', None, None], [None, None, '：「', None], ['浅', 'あさ', None, None], [None, None, 'いからここで', None], ['泳', 'およ', None, None], [None, None, 'ごう！」', None], [None, None, ' ', None], ['Ｂ', 'ビー', None, None], [None, None, '：「', None], ['浅', 'あさ', None, None], [None, None, 'いけど、', None], ['危', 'あぶ', None, True], [None, None, 'なくない', True], ['事', 'こと', None, True], [None, None, 'はない', True], [None, None, '。」', None]]
[['清水', 'しみず', None, None], [None, None, '：「', None], ['昨年', 'さくねん', None, None], ['買', 'か', None, None], [None, None, 'ったドレスを', None], ['着', 'き', None, None], [None, None, 'たら、どう？」', None], ['木村', 'きむら', None, None], [None, None, '：「', None], ['着', 'き', None, True], [None, None, 'れない', True], ['事', 'こと', None, True], [None, None, 'はない', True], [None, None, 'が、', None], ['少', 'すこ', None, None], [None, None, 'しサイズが', None], ['小', 'ちい', None, None], [None, None, 'さいな。」', None]]
[['林', 'はやし', None, None], [None, None, '：「', None], ['怪我', 'けが', None, None], [None, None, 'はないか？', None], ['歩', 'ある', None, None], [None, None, 'ける？」', None], ['森', 'もり', None, None], [None, None, '：「', None], ['歩', 'ある', None, None], [None, None, 'いて', None], ['行', 'い', None, True], [None, None, 'けない', True], ['事', 'こと', None, True], [None, None, 'はない', True], [None, None, 'んですが、かなりゆっくりですね。」', None]]
[['小川', 'おがわ', None, None], [None, None, '：「ビットコインのことを', None], ['何', 'なに', None, None], [None, None, 'か', None], ['知', 'し', None, None], [None, None, 'ってるの？」', None], ['村上', 'むらかみ', None, None], [None, None, '：「', None], ['何', 'なに', None, None], [None, None, 'も', None], ['知', 'し', None, True], [None, None, 'らない', True], ['事', 'こと', None, True], [None, None, 'はない', True], [None, None, 'が、', None], ['詳', 'くわ', None, None], [None, None, 'しくもない。」', None]]
[['Ａ', 'エー', None, None], [None, None, '：「お', None], ['金', 'かね', None, None], [None, None, 'がないから', None], ['君', 'きみ', None, None], [None, None, 'と', None], ['一緒', 'いっしょ', None, None], [None, None, 'に', None], ['旅行', 'りょこう', None, None], [None, None, 'にいけないんだ。」', None], [None, None, ' ', None], ['Ｂ', 'ビー', None, None], [None, None, '：「お', None], ['金', 'かね', None, None], [None, None, 'がなくても', None], ['旅行', 'りょこう', None, None], [None, None, 'に', None], ['行', 'い', None, True], [None, None, 'けない', True], ['事', 'こと', None, True], [None, None, 'はない', True], [None, None, 'よ。」', None]]

 49%|████▉     | 460/938 [04:36<05:24,  1.47it/s]

[['人生', 'じんせい', None, None], [None, None, 'なんて', True], [None, None, 'そんなもんさ。', None]]
[[None, None, 'お', None], ['世辞', 'せじ', None, None], [None, None, 'なんて', True], ['大嫌', 'だいきら', None, None], [None, None, 'いだ！', None]]
[['嘘', 'うそ', None, None], [None, None, 'なんか', True], [None, None, 'つかないよ。', None], ['信', 'しん', None, None], [None, None, 'じてよ。', None]]
[['私', 'わたし', None, None], [None, None, 'が', None], ['太', 'ふと', None, None], [None, None, 'っている', None], [None, None, 'なんて', True], ['言', 'い', None, None], [None, None, 'わないで。', None]]
[['僕', 'ぼく', None, None], [None, None, 'には', None], ['道案内', 'みちあんない', None, None], [None, None, 'なんて', True], [None, None, 'できませんよ。', None]]

 49%|████▉     | 461/938 [04:37<05:26,  1.46it/s]

[['犬', 'いぬ', None, None], [None, None, 'はイヌ', None], ['科', 'か', None, None], [None, None, 'である。', None], ['又', 'また', None, True], [None, None, '、', None], ['狐', 'きつね', None, None], [None, None, 'も', None], [None, None, 'イヌ', None], ['科', 'か', None, None], [None, None, 'である。', None]]
[[None, None, 'その', None], ['詩', 'し', None, None], [None, None, 'は', None], ['悲', 'かな', None, None], [None, None, 'しく、', None], ['又', 'また', None, True], [None, None, '、', None], ['感動', 'かんどう', None, None], [None, None, 'させる', None], ['文学', 'ぶんがく', None, None], [None, None, 'で', None], [None, None, 'も', None], [None, None, 'ある。', None]]
[[None, None, 'このアプリは', None], ['ＪＰＧ', 'ジェイペグ', None, None], [None, None, 'ファイルを', None], ['読', 'よ', None, None], [None, None, 'み、', None], ['又', 'また', None, True], [None, None, '、', None], ['ＰＮＧ', 'ピーエヌジー', None, None], [None, None, 'ファイル', None], [None, None, 'も', None], ['読', 'よ', None, None], [None, None, 'む。', None]]
[['燕尾服', 'えんびふく', None, None], [None, None, 'を', None], ['着', 'き', None, None], [None, None, 'てもよいです。', None], ['又', 'また', None, True], [None, None, '、スーツを', None], ['着', 'き', None, None], [None, None, 'て', None], [None, None, 'も', None], [None, None, 'よいです。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['有名', 'ゆうめい', None, None], [None, None, 'な', None], ['歌手', 'かしゅ', None, None], [None, None, 'であり', None], [None, None, '、', None], ['又', 'また', None, True], [None, None, '、', None], ['腕', 'うで', None, None], [None, None, 'のいい', None], ['外科医', 'げかい', None, None], [None, None, 'で', None], [None, None, 'も', None], [None, None, 'ある。', None]]

 49%|████▉     | 462/938 [04:37<05:31,  1.44it/s]

[['序', 'つい', None, True], [None, None, 'でに', True], ['君', 'きみ', None, None], [None, None, 'の', None], ['分', 'ぶん', None, None], [None, None, 'も', None], ['払', 'はら', None, None], [None, None, 'ってあげるよ。', None]]
[['序', 'つい', None, True], [None, None, 'でに', True], ['君', 'きみ', None, None], [None, None, 'の', None], ['車', 'くるま', None, None], [None, None, 'も', None], ['洗', 'あら', None, None], [None, None, 'ってあげようか？', None]]
[[None, None, 'ここまで', None], ['来', 'き', None, None], [None, None, 'たなら', None], ['序', 'つい', None, True], [None, None, 'でに', True], [None, None, 'うちにも', None], ['寄', 'よ', None, None], [None, None, 'ってよ。', None]]
[['話', 'はなし', None, None], [None, None, 'の', None], ['序', 'つい', None, True], [None, None, 'でに', True], ['言', 'い', None, None], [None, None, 'っておきたいことがあります。', None]]
[['給油', 'きゅうゆ', None, None], [None, None, 'の', None], ['序', 'つい', None, True], [None, None, 'でに', True], ['車', 'くるま', None, None], [None, None, 'を', None], ['点検', 'てんけん', None, None], [None, None, 'してもらいました。', None]]

 49%|████▉     | 463/938 [04:38<05:38,  1.40it/s]

[['風', 'かぜ', None, None], [None, None, 'と', True], ['共', 'とも', None, True], [None, None, 'に', True], ['去', 'さ', None, None], [None, None, 'りぬ。', None]]
[['心身', 'しんしん', None, None], [None, None, 'と', True], ['共', 'とも', None, True], [None, None, 'に', True], ['健康', 'けんこう', None, None], [None, None, 'だ。', None]]
[['夜明', 'よあ', None, None], [None, None, 'け', None], [None, None, 'と', True], ['共', 'とも', None, True], [None, None, 'に', True], ['旅立', 'たびだ', None, None], [None, None, 'った。', None]]
[['驚', 'おどろ', None, None], [None, None, 'き', None], [None, None, 'と', True], ['共', 'とも', None, True], [None, None, 'に', True], ['喜', 'よろこ', None, None], [None, None, 'びが', None], ['溢', 'あふ', None, None], [None, None, 'れ', None], ['出', 'だ', None, None], [None, None, 'してきた。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], ['今', 'いま', None, None], [None, None, 'でも', None], ['父', 'ちち', None, None], [None, None, 'と', True], ['共', 'とも', None, True], [None, None, 'に', True], ['仕事', 'しごと', None, None], [None, None, 'をしています。', None]]

 49%|████▉     | 464/938 [04:39<05:11,  1.52it/s]

[['日', 'ひ', None, None], [None, None, 'がたつ', None], [None, None, 'に', True], ['連', 'つ', None, True], [None, None, 'れて', True], [None, None, '、', None], ['怪我', 'けが', None, None], [None, None, 'が', None], ['悪化', 'あっか', None, None], [None, None, 'してきた。', None]]
[[None, None, 'こちらの', None], ['木', 'き', None, None], [None, None, 'が', None], ['大', 'おお', None, None], [None, None, 'きくなる', None], [None, None, 'に', True], ['連', 'つ', None, True], [None, None, 'れて', True], [None, None, '、', None], ['影', 'かげ', None, None], [None, None, 'が', None], ['広', 'ひろ', None, None], [None, None, 'がります。', None]]
[['子供', 'こども', None, None], [None, None, 'は、', None], ['成長', 'せいちょう', None, None], [None, None, 'する', None], [None, None, 'に', True], ['連', 'つ', None, True], [None, None, 'れて', True], [None, None, '、', None], ['性格', 'せいかく', None, None], [None, None, 'が', None], ['変', 'か', None, None], [None, None, 'わる。', None]]
[['進', 'すす', None, None], [None, None, 'む', None], [None, None, 'に', True], ['連', 'つ', None, True], [None, None, 'れて', True], ['道', 'みち', None, None], [None, None, 'がどんどん', None], ['狭', 'せま', None, None], [None, None, 'くなるから', None], ['心配', 'しんぱい', None, None], [None, None, 'になってきた。', None]]
[['経済', 'けいざい', None, None], [None, None, 'の', None], ['発展', 'はってん', None, None], [None, None, 'に', True], ['連', 'つ', None, True], [None, None, 'れて', True], ['一般', 'いっぱん', None, None], ['市民', 'しみん', None, None], [None, None, 'の', None], ['日常', 'にちじょう', None, None], ['生活', 'せいかつ', None, None], [None, None, 'は', None], ['良', 'よ', None, None], [None, None, 'くなっていく。', None]]

 50%|████▉     | 465/938 [04:39<05:13,  1.51it/s]

[['効果', 'こうか', None, None], [None, None, 'は', None], ['直', 'ただ', None, True], [None, None, 'ちに', True], ['現', 'あらわ', None, None], [None, None, 'れるわけではありません。', None]]
[['直', 'ただ', None, True], [None, None, 'ちに', True], ['安定', 'あんてい', None, None], [None, None, 'した', None], ['仕事', 'しごと', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'つけなければ。', None]]
[[None, None, 'この', None], ['案件', 'あんけん', None, None], [None, None, 'は', None], ['直', 'ただ', None, True], [None, None, 'ちに', True], ['対応', 'たいおう', None, None], [None, None, 'する', None], ['必要', 'ひつよう', None, None], [None, None, 'がある。', None]]
[['結果', 'けっか', None, None], [None, None, 'が', None], ['出', 'で', None, None], [None, None, 'たら', None], ['直', 'ただ', None, True], [None, None, 'ちに', True], [None, None, 'お', None], ['伝', 'つた', None, None], [None, None, 'えします。', None]]
[['急', 'いそ', None, None], [None, None, 'ごう。', None], ['直', 'ただ', None, True], [None, None, 'ちに', True], ['出発', 'しゅっぱつ', None, None], [None, None, 'した', None], ['方', 'ほう', None, None], [None, None, 'がいい。', None]]

 50%|████▉     | 466/938 [04:40<04:56,  1.59it/s]

[['出', 'で', None, True], [None, None, 'た', True], ['途端', 'とたん', None, True], [None, None, 'に', True], [None, None, '、', None], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'り', None], ['始', 'はじ', None, None], [None, None, 'めた。', None]]
[['帰', 'かえ', None, None], [None, None, 'ろうと', None], [None, None, 'した', True], ['途端', 'とたん', None, True], [None, None, '、', None], ['仕事', 'しごと', None, None], [None, None, 'を', None], ['頼', 'たの', None, None], [None, None, 'まれた。', None]]
[['青', 'あお', None, None], [None, None, 'に', None], [None, None, 'なった', True], ['途端', 'とたん', None, True], [None, None, 'に', True], ['飛', 'と', None, None], [None, None, 'び', None], ['出', 'だ', None, None], [None, None, 'すのは', None], ['危', 'あぶ', None, None], [None, None, 'ないよ。', None]]
[['家', 'いえ', None, None], [None, None, 'に', None], ['入', 'はい', None, True], [None, None, 'った', True], ['途端', 'とたん', None, True], ['呼', 'よ', None, None], [None, None, 'び', None], ['鈴', 'りん', None, None], [None, None, 'が', None], ['鳴', 'な', None, None], [None, None, 'った。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'を', None], ['見', 'み', None, True], [None, None, 'た', True], ['途端', 'とたん', None, True], [None, None, 'に', True], ['恋', 'こい', None, None], [None, None, 'をしてしまった。', None]]

 50%|████▉     | 467/938 [04:41<05:13,  1.50it/s]

[['３０分', 'さんじゅっぷん', None, None], ['置', 'お', None, True], [None, None, 'きに', True], ['休憩', 'きゅうけい', None, None], [None, None, 'しよう。', None]]
[['約', 'やく', None, None], ['３分', 'さんぷん', None, None], ['置', 'お', None, True], [None, None, 'きに', True], ['電車', 'でんしゃ', None, None], [None, None, 'が', None], ['来', 'き', None, None], [None, None, 'ます。', None]]
[['１時間', 'いちじかん', None, None], ['置', 'お', None, True], [None, None, 'きに', True], ['温度', 'おんど', None, None], [None, None, 'を', None], ['測', 'はか', None, None], [None, None, 'ってください。', None]]
[['５０', 'ごじゅう', None, None], [None, None, 'メートル', None], ['置', 'お', None, True], [None, None, 'きに', True], ['自動', 'じどう', None, None], ['販売', 'はんばい', None, None], ['機', 'き', None, None], [None, None, 'がある。', None]]
[['階段', 'かいだん', None, None], [None, None, 'を', None], ['一段', 'いちだん', None, None], ['置', 'お', None, True], [None, None, 'きに', True], ['飛', 'と', None, None], [None, None, 'ばして', None], ['上', 'あ', None, None], [None, None, 'がる。', None]]

 50%|████▉     | 468/938 [04:41<05:20,  1.47it/s]

[['君', 'きみ', None, None], [None, None, 'は', None], ['会', 'あ', None, None], [None, None, 'う', None], ['度', 'たび', None, True], [None, None, 'に', True], ['大人', 'おとな', None, None], [None, None, 'になってゆく。', None]]
[[None, None, 'この', None], ['映画', 'えいが', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'る', None], ['度', 'たび', None, True], [None, None, 'に', True], [None, None, '、', None], ['泣', 'な', None, None], [None, None, 'いてしまう。', None]]
[['旅行', 'りょこう', None, None], [None, None, 'の', True], ['度', 'たび', None, True], [None, None, 'に', True], [None, None, '、いい', None], ['思', 'おも', None, None], [None, None, 'い', None], ['出', 'で', None, None], [None, None, 'を', None], ['作', 'つく', None, None], [None, None, 'ろう。', None]]
[['冬', 'ふゆ', None, None], [None, None, 'の', None], ['間', 'あいだ', None, None], [None, None, 'は、', None], ['休', 'やす', None, None], [None, None, 'み', None], [None, None, 'の', True], ['度', 'たび', None, True], [None, None, 'に', True], [None, None, 'スキーに', None], ['行', 'い', None, None], [None, None, 'っています。', None]]
[['買', 'か', None, None], [None, None, 'い', None], ['物', 'もの', None, None], [None, None, 'へ', None], ['行', 'い', None, None], [None, None, 'く', None], ['度', 'たび', None, True], [None, None, 'に', True], [None, None, '、いらないものを', None], ['買', 'か', None, None], [None, None, 'っちゃう。', None]]

 50%|█████     | 469/938 [04:42<05:28,  1.43it/s]

[['鍋', 'なべ', None, None], ['或', 'ある', None, True], [None, None, 'いは', True], ['深', 'ふか', None, None], [None, None, 'めのフライパンを', None], ['使', 'つか', None, None], [None, None, 'いましょう。', None]]
[['動画', 'どうが', None, None], ['或', 'ある', None, True], [None, None, 'いは', True], ['写真', 'しゃしん', None, None], [None, None, 'でもいいので', None], ['送', 'おく', None, None], [None, None, 'ってください。', None]]
[['月曜日', 'げつようび', None, None], ['或', 'ある', None, True], [None, None, 'いは', True], ['火曜日', 'かようび', None, None], [None, None, 'であれば、', None], ['参加', 'さんか', None, None], [None, None, 'できます。', None]]
[['植物', 'しょくぶつ', None, None], ['或', 'ある', None, True], [None, None, 'いは', True], ['昆虫', 'こんちゅう', None, None], [None, None, 'を', None], ['観察', 'かんさつ', None, None], [None, None, 'しましょう。', None]]
[['晴', 'は', None, None], [None, None, 'れ', None], ['或', 'ある', None, True], [None, None, 'いは', True], ['曇', 'くも', None, None], [None, None, 'りであれば、お', None], ['祭', 'まつ', None, None], [None, None, 'りに', None], ['行', 'い', None, None], [None, None, 'きましょう。', None]]

 50%|█████     | 470/938 [04:43<05:29,  1.42it/s]

[[None, None, 'すこし', None], ['狭', 'せま', None, None], [None, None, 'い', None], ['乍', 'なが', None, True], [None, None, 'らも', True], ['楽', 'たの', None, None], [None, None, 'しい', None], ['我', 'わ', None, None], [None, None, 'が', None], ['家', 'いえ', None, None], [None, None, '。', None]]
[[None, None, '「やらなきゃいけない」と', None], ['思', 'おも', None, True], [None, None, 'い', True], ['乍', 'なが', None, True], [None, None, 'らも', True], [None, None, 'ダラダラしてしまう。', None]]
[['不本意', 'ふほんい', None, None], ['乍', 'なが', None, True], [None, None, 'らも', True], [None, None, '、', None], ['従', 'したが', None, None], [None, None, 'うしかない。', None]]
[['足', 'あし', None, None], [None, None, 'を', None], ['引', 'ひ', None, True], [None, None, 'きずり', True], ['乍', 'なが', None, True], [None, None, 'らも', True], [None, None, '、マラソンを', None], ['完走', 'かんそう', None, None], [None, None, 'しました。', None]]
[['良', 'よ', None, None], [None, None, 'くないと', None], ['知', 'し', None, True], [None, None, 'ってい', True], ['乍', 'なが', None, True], [None, None, 'らも', True], [None, None, '、', None], ['注意', 'ちゅうい', None, None], [None, None, 'することができませんでした。', None]]

 50%|█████     | 471/938 [04:44<05:32,  1.40it/s]

[['数', 'かず', None, None], [None, None, 'に', True], ['於', 'お', None, True], [None, None, 'いて', True], [None, None, 'は', None], ['劣', 'おと', None, None], [None, None, 'っているが、', None], ['力', 'ちから', None, None], [None, None, 'に', True], ['於', 'お', None, True], [None, None, 'いて', True], [None, None, 'は', None], ['負', 'ま', None, None], [None, None, 'けていない。', None]]
[['大都市', 'だいとし', None, None], [None, None, 'に', True], ['於', 'お', None, True], [None, None, 'ける', True], ['渋滞', 'じゅうたい', None, None], [None, None, 'の', None], ['問題', 'もんだい', None, None], [None, None, 'は', None], ['深刻', 'しんこく', None, None], [None, None, 'だ。', None]]
[[None, None, 'この', None], ['文脈', 'ぶんみゃく', None, None], [None, None, 'に', True], ['於', 'お', None, True], [None, None, 'いて', True], [None, None, 'の「空」は、「そら」ではなく「から」だと', None], ['思', 'おも', None, None], [None, None, 'う。', None]]
[['現代', 'げんだい', None, None], [None, None, 'に', True], ['於', 'お', None, True], [None, None, 'いて', True], [None, None, '、', None], ['電気', 'でんき', None, None], [None, None, 'のない', None], ['生活', 'せいかつ', None, None], [None, None, 'は', None], ['考', 'かんが', None, None], [None, None, 'えられない。', None]]
[['東京', 'とうきょう', None, None], [None, None, 'に', True], ['於', 'お', None, True], [None, None, 'ける', True], ['環境', 'かんきょう', None, None], [None, None, 'についての', None], ['会議', 'かいぎ', None, None], [None, None, 'を', None], ['行', 'おこな', None, None], [None, None, 'います。', None]]

 50%|█████     | 472/938 [04:44<05:29,  1.41it/s]

[['安全', 'あんぜん', None, None], [None, None, 'は', None], ['第一', 'だいいち', None, True], [None, None, 'だ。', None]]
[['第一', 'だいいっ', None, True], ['節', 'せつ', None, None], ['第一', 'だいいっ', None, True], ['款', 'かん', None, None], ['検察官', 'けんさつかん', None, None], [None, None, 'の', None], ['義務', 'ぎむ', None, None], ['等', 'など', None, None], [None, None, '。', None]]
[[None, None, 'ハグ・クラブルールの', None], ['第一', 'だいいち', None, True], [None, None, '、ハグ・クラブのことを', None], ['明', 'あ', None, None], [None, None, 'かすな。', None]]
[[None, None, 'オリンピック', None], ['選手', 'せんしゅ', None, None], [None, None, 'になるには、', None], ['優', 'すぐ', None, None], [None, None, 'れた', None], ['身体能力', 'しんたいのうりょく', None, None], [None, None, 'が', None], ['第一', 'だいいち', None, True], ['条件', 'じょうけん', None, None], [None, None, 'だ。', None]]
[['第一', 'だいいっ', None, True], ['章', 'しょう', None, None], [None, None, '：「', None], ['自動販売機', 'じどうはんばいき', None, None], [None, None, 'として', None], ['生', 'う', None, None], [None, None, 'まれ', None], ['変', 'か', None, None], [None, None, 'わった', None], ['日', 'ひ', None, None], [None, None, '。」', None]]

 50%|█████     | 473/938 [04:45<05:25,  1.43it/s]

[['益々', 'ますます', None, True], ['寒', 'さむ', None, None], [None, None, 'さが', None], ['厳', 'きび', None, None], [None, None, 'しくなってまいりました。', None]]
[['景気', 'けいき', None, None], [None, None, 'は', None], ['益々', 'ますます', None, True], ['悪', 'わる', None, None], [None, None, 'くなるばかりだ。', None]]
[['商売', 'しょうばい', None, None], [None, None, 'は', None], ['益々', 'ますます', None, True], ['繁盛', 'はんじょう', None, None], [None, None, 'している。', None]]
[['益々', 'ますます', None, True], ['責任', 'せきにん', None, None], [None, None, 'が', None], ['重', 'おも', None, None], [None, None, 'くなってきた。', None]]
[['水', 'みず', None, None], ['不足', 'ぶそく', None, None], [None, None, 'が', None], ['益々', 'ますます', None, True], ['深刻', 'しんこく', None, None], [None, None, 'になってきている。', None]]

 51%|█████     | 474/938 [04:46<05:32,  1.40it/s]

[['災害', 'さいがい', None, None], [None, None, 'は', None], ['増', 'ふ', None, None], [None, None, 'える', None], ['一方', 'いっぽう', None, True], [None, None, 'です', True], [None, None, '。', None]]
[['会社', 'かいしゃ', None, None], [None, None, 'の', None], ['財政', 'ざいせい', None, None], [None, None, 'は', None], ['厳', 'きび', None, None], [None, None, 'しくなる', None], ['一方', 'いっぽう', None, True], [None, None, 'だ', True], [None, None, '。', None]]
[[None, None, 'うちの', None], ['町', 'まち', None, None], [None, None, 'の', None], ['人口', 'じんこう', None, None], [None, None, 'は', None], ['減', 'へ', None, None], [None, None, 'る', None], ['一方', 'いっぽう', None, True], [None, None, 'だ', True], [None, None, '。', None]]
[[None, None, 'このままだと', None], ['借金', 'しゃっきん', None, None], [None, None, 'が', None], ['増', 'ふ', None, None], [None, None, 'える', None], ['一方', 'いっぽう', None, True], [None, None, 'だ', True], [None, None, '。', None]]
[['残念', 'ざんねん', None, None], [None, None, 'ながらこんな', None], ['事件', 'じけん', None, None], [None, None, 'が', None], ['増', 'ふ', None, None], [None, None, 'える', None], ['一方', 'いっぽう', None, True], [None, None, 'だ。', None]]

 51%|█████     | 475/938 [04:46<05:31,  1.39it/s]

[[None, None, 'この', None], ['靴', 'くつ', None, None], [None, None, 'は、', None], ['温', 'あたた', None, None], [None, None, 'かい', None], ['一方', 'いっぽう', None, True], [None, None, 'で', True], [None, None, '、', None], ['重', 'おも', None, None], [None, None, 'いです。', None]]
[[None, None, 'あの', None], ['食', 'た', None, None], [None, None, 'べ', None], ['物', 'もの', None, None], [None, None, 'は', None], ['体', 'からだ', None, None], [None, None, 'に', None], ['良', 'い', None, None], [None, None, 'い', None], ['一方', 'いっぽう', None, True], [None, None, 'で', True], [None, None, '、', None], ['食', 'た', None, None], [None, None, 'べ', None], ['過', 'す', None, None], [None, None, 'ぎたら、', None], ['体', 'からだ', None, None], [None, None, 'に', None], ['悪', 'わる', None, None], [None, None, 'い。', None]]
[['彼', 'かれ', None, None], [None, None, 'の', None], ['会社', 'かいしゃ', None, None], [None, None, 'が', None], ['儲', 'もう', None, None], [None, None, 'かる', None], ['一方', 'いっぽう', None, True], [None, None, 'で', True], [None, None, '、うちの', None], ['会社', 'かいしゃ', None, None], [None, None, 'は', None], ['経営', 'けいえい', None, None], ['状態', 'じょうたい', None, None], [None, None, 'が', None], ['悪化', 'あっか', None, None], [None, None, 'している。', None]]
[['友人', 'ゆうじん', None, None], [None, None, 'たちがスキーを', None], ['楽', 'たの', None, None], [None, None, 'しむ', None], ['一方', 'いっぽう', None, True], [None, None, 'で', True], [None, None, '、', None], ['私', 'わたし', None, None], [None, None, 'は', None], ['働', 'はたら', None, None], [None, None, 'かなくてはいけない。', None]]
[['会社', 'かいしゃ', None, None], [None, None, 'ではいい', None], ['上司', 'じょうし', None, None], [None, None, 'だが、その', None], ['一方', 'いっぽう', None, True], [None, None, 'で', True], [None, None, '、', None], ['家', 'いえ', None, None], [None, None, 'では', None], ['酒乱', 'しゅらん', None, None], [None, None, 'だ。', None]]

 51%|█████     | 476/938 [04:47<05:32,  1.39it/s]

[['遂', 'つい', None, True], [None, None, 'に', True], ['論文', 'ろんぶん', None, None], [None, None, 'を', None], ['書', 'か', None, None], [None, None, 'き', None], ['上', 'あ', None, None], [None, None, 'げた。', None]]
[['遂', 'つい', None, True], [None, None, 'に', True], ['犯人', 'はんにん', None, None], [None, None, 'を', None], ['捕', 'つか', None, None], [None, None, 'まえることができた。', None]]
[['遂', 'つい', None, True], [None, None, 'に', True], ['借金', 'しゃっきん', None, None], [None, None, 'を', None], ['払', 'はら', None, None], [None, None, 'い', None], ['終', 'お', None, None], [None, None, 'えた。', None]]
[['遂', 'つい', None, True], [None, None, 'に', True], ['孫', 'まご', None, None], [None, None, 'に', None], ['身長', 'しんちょう', None, None], [None, None, 'で', None], ['負', 'ま', None, None], [None, None, 'けてしまった。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'にプロポーズをする', None], ['日', 'ひ', None, None], [None, None, 'が', None], ['遂', 'つい', None, True], [None, None, 'に', True], ['来', 'き', None, None], [None, None, 'た。', None]]

 51%|█████     | 477/938 [04:48<05:36,  1.37it/s]

[['時', 'とき', None, None], ['既', 'すで', None, True], [None, None, 'に', True], ['遅', 'おそ', None, None], [None, None, 'し。', None]]
[['電話', 'でんわ', None, None], ['料金', 'りょうきん', None, None], [None, None, 'は', None], ['既', 'すで', None, True], [None, None, 'に', True], ['払', 'はら', None, None], [None, None, 'い', None], ['終', 'お', None, None], [None, None, 'えました。', None]]
[[None, None, 'あなたの', None], ['席', 'せき', None, None], [None, None, 'は', None], ['既', 'すで', None, True], [None, None, 'に', True], [None, None, 'ここと', None], ['決', 'き', None, None], [None, None, 'まっています。', None]]
[['僕', 'ぼく', None, None], [None, None, 'が', None], ['来', 'き', None, None], [None, None, 'た', None], ['時', 'とき', None, None], [None, None, 'には、', None], ['電気', 'でんき', None, None], [None, None, 'は', None], ['既', 'すで', None, True], [None, None, 'に', True], [None, None, 'つけてあった。', None]]
[['旅行', 'りょこう', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'くための', None], ['休', 'やす', None, None], [None, None, 'みは', None], ['既', 'すで', None, True], [None, None, 'に', True], ['取', 'と', None, None], [None, None, 'りました。', None]]

 51%|█████     | 478/938 [04:49<05:32,  1.38it/s]

[['忘', 'わす', None, True], [None, None, 'れずに', True], ['届', 'とど', None, None], [None, None, 'けてくれてありがとうございます。', None]]
[['何', 'なに', None, None], [None, None, 'も', None], ['知', 'し', None, True], [None, None, 'らずに', True], [None, None, 'あんなこと', None], ['言', 'い', None, None], [None, None, 'ってごめんなさい。', None]]
[['悩', 'なや', None, True], [None, None, 'まずに', True], ['生', 'い', None, None], [None, None, 'きるなんて', None], ['不可能', 'ふかのう', None, None], [None, None, 'なのかもしれない。', None]]
[['値段', 'ねだん', None, None], [None, None, 'を', None], ['見', 'み', None, True], [None, None, 'ずに', True], ['買', 'か', None, None], [None, None, 'ったら', None], ['大変', 'たいへん', None, None], [None, None, 'なことになった。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['朝', 'あさ', None, None], [None, None, 'ごはんを', None], ['食', 'た', None, True], [None, None, 'べずに', True], ['仕事', 'しごと', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'きました。', None]]

 51%|█████     | 479/938 [04:50<05:57,  1.28it/s]

[['子供', 'こども', None, None], [None, None, 'が', None], ['生', 'う', None, None], [None, None, 'まれて', None], ['泣', 'な', None, True], [None, None, 'かずには', True], ['居', 'い', None, True], [None, None, 'られない', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'はよく', None], ['嘘', 'うそ', None, None], [None, None, 'をつくから、', None], ['疑', 'うたが', None, True], [None, None, 'わずには', True], ['居', 'い', None, True], [None, None, 'られない', True], [None, None, '。', None]]
[['事故', 'じこ', None, None], [None, None, 'を', None], ['目撃', 'もくげき', None, None], [None, None, 'したら、', None], ['助', 'たす', None, True], [None, None, 'けずには', True], ['居', 'い', None, True], [None, None, 'られない', True], [None, None, '。', None]]
[[None, None, 'それ', None], [None, None, 'を', None], ['思', 'おも', None, None], [None, None, 'い', None], ['出', 'だ', None, None], [None, None, 'す', None], [None, None, 'たびに', None], ['恥', 'は', None, True], [None, None, 'ずかしくならずには', True], ['居', 'い', None, True], [None, None, 'られない', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'の', None], ['変顔', 'へんがお', None, None], [None, None, 'は', None], ['面白', 'おもしろ', None, None], [None, None, 'すぎて、', None], ['笑', 'わら', None, True], [None, None, 'わずには', True], ['居', 'い', None, True], [None, None, 'られません', True], [None, None, '。', None]]

 51%|█████     | 480/938 [04:50<05:24,  1.41it/s]

[[None, None, 'ことわざ', None], [None, None, '：「', None], ['死人', 'しにん', None, None], [None, None, 'に', None], ['口', 'くち', None, None], ['無', 'な', None, True], [None, None, 'しだ', True], [None, None, '。」', None]]
[['告白', 'こくはく', None, None], [None, None, '：「あなた', None], ['無', 'な', None, True], [None, None, 'しで', True], ['生', 'い', None, None], [None, None, 'きていけない。」', None]]
[['商品', 'しょうひん', None, None], [None, None, 'ラベル', None], [None, None, '：「', None], ['砂糖', 'さとう', None, None], ['無', 'な', None, True], [None, None, 'しの', True], [None, None, 'ダイエットドリンク」', None]]
[[None, None, 'エッセイ', None], [None, None, '：「', None], ['今', 'いま', None, None], [None, None, 'では', None], ['現生', 'げんせい', None, None], ['人類', 'じんるい', None, None], [None, None, 'はスマホ', None], ['無', 'な', None, True], [None, None, 'しでは', True], ['生活', 'せいかつ', None, None], [None, None, 'できないだろう。」', None]]
[[None, None, 'テスト', None], ['飛行', 'ひこう', None, None], [None, None, 'は', None], ['文句', 'もんく', None, None], ['無', 'な', None, True], [None, None, 'しの', True], ['成功', 'せいこう', None, None], [None, None, 'でした。', None]]

 51%|█████▏    | 481/938 [04:51<05:19,  1.43it/s]

[['遊', 'あそ', None, None], [None, None, 'びに', None], ['行', 'い', None, None], [None, None, 'くなら、', None], ['遊園地', 'ゆうえんち', None, None], [None, None, 'も', None], [None, None, 'あり', True], [None, None, 'だ。', None]]
[['何', 'なに', None, None], [None, None, 'か', None], ['動物', 'どうぶつ', None, None], [None, None, 'を', None], ['飼', 'か', None, None], [None, None, 'いたい。ネコも', None], [None, None, 'あり', True], [None, None, 'だ。', None]]
[['明日', 'あした', None, None], [None, None, 'のデート、', None], ['水族館', 'すいぞくかん', None, None], [None, None, 'も', None], [None, None, 'あり', True], [None, None, 'じゃない？', None]]
[[None, None, 'キッズメニュー', None], [None, None, 'あり', True], [None, None, 'のレストランに', None], ['行', 'い', None, None], [None, None, 'こう。', None]]
[[None, None, 'この', None], ['香', 'かお', None, None], [None, None, 'りも', None], [None, None, 'あり', True], [None, None, 'だけど、あの', None], ['香', 'かお', None, None], [None, None, 'りの', None], ['方', 'ほう', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き！', None]]

 51%|█████▏    | 482/938 [04:51<05:23,  1.41it/s]

[[None, None, '「ほかの', None], ['方法', 'ほうほう', None, None], [None, None, 'は', None], ['考', 'かんが', None, True], [None, None, 'えられない', True], [None, None, '。」', None]]
[['論文', 'ろんぶん', None, None], [None, None, '：「チタン', None], [None, None, 'は', None], ['考', 'かんが', None, True], [None, None, 'えられない', True], [None, None, 'ほど', None], ['硬', 'かた', None, None], [None, None, 'いので、', None], ['飛行機', 'ひこうき', None, None], [None, None, 'によく', None], ['使用', 'しよう', None, None], [None, None, 'される。」', None]]
[[None, None, 'ブログの', None], ['投稿', 'とうこう', None, None], [None, None, '：「', None], ['君', 'きみ', None, None], [None, None, 'の', None], ['事', 'こと', None, None], ['以外', 'いがい', None, None], [None, None, 'は', None], ['何', 'なに', None, None], [None, None, 'も', None], ['考', 'かんが', None, True], [None, None, 'えられない', True], [None, None, '。」', None]]
[['友達', 'ともだち', None, None], [None, None, 'との', None], ['話', 'はなし', None, None], [None, None, '：「', None], ['子供', 'こども', None, None], [None, None, 'がそんな', None], ['難', 'むずか', None, None], [None, None, 'しい', None], ['数学', 'すうがく', None, None], [None, None, 'の', None], ['問題', 'もんだい', None, None], [None, None, 'を', None], ['解', 'と', None, None], [None, None, 'く', None], [None, None, 'ということは', None], ['考', 'かんが', None, True], [None, None, 'えられない', True], [None, None, '。」', None]]
[[None, None, 'ブログの', None], ['投稿', 'とうこう', None, None], [None, None, '：「', None], ['電気', 'でんき', None, None], [None, None, 'なしの', None], ['生活', 'せいかつ', None, None], [None, None, 'は', None], ['私', 'わたし', None, None], [None, None, 'に', None], [None, None, 'は', None], ['考', 'かんが', None, True], [None, None, 'えられない', True], [None, None, '。」', None]]

 51%|█████▏    | 483/938 [04:52<05:00,  1.51it/s]

[['失敗', 'しっぱい', None, None], [None, None, 'は', None], ['必', 'かなら', None, True], [None, None, 'ずしも', True], ['悪', 'わる', None, None], [None, None, 'い', None], [None, None, 'わけではない', None], [None, None, '。', None]]
[['必', 'かなら', None, True], [None, None, 'ずしも', True], ['上達', 'じょうたつ', None, None], [None, None, 'する', None], [None, None, 'わけではない', None], [None, None, '。', None]]
[['思', 'おも', None, None], [None, None, 'い', None], ['出', 'で', None, None], [None, None, 'が', None], ['必', 'かなら', None, True], [None, None, 'ずしも', True], ['美', 'うつく', None, None], [None, None, 'しい', None], [None, None, 'とは', None], ['限', 'かぎ', None, None], [None, None, 'らない', None], [None, None, '。', None]]
[['天気', 'てんき', None, None], ['予報', 'よほう', None, None], [None, None, 'は', None], ['必', 'かなら', None, True], [None, None, 'ずしも', True], ['当', 'あ', None, None], [None, None, 'たる', None], [None, None, 'わけではない', None], [None, None, '。', None]]
[['必', 'かなら', None, True], [None, None, 'ずしも', True], [None, None, 'この', None], ['情報', 'じょうほう', None, None], [None, None, 'が', None], ['正', 'ただ', None, None], [None, None, 'しい', None], [None, None, 'とは', None], ['限', 'かぎ', None, None], [None, None, 'らない', None], [None, None, '。', None]]

 52%|█████▏    | 484/938 [04:53<05:19,  1.42it/s]

[['風', 'かぜ', None, None], [None, None, 'が', None], ['吹', 'ふ', None, True], [None, None, 'き', True], [None, None, '、', None], ['悪魔', 'あくま', None, None], [None, None, 'が', None], ['現', 'あらわ', None, None], [None, None, 'れた。', None]]
[['空', 'そら', None, None], [None, None, 'は', None], ['青', 'あお', None, True], [None, None, 'く', True], [None, None, '、', None], ['海', 'うみ', None, None], [None, None, 'より', None], ['広', 'ひろ', None, None], [None, None, 'い。', None]]
[[None, None, 'スピードを', None], ['出', 'だ', None, None], [None, None, 'し', None], [None, None, 'すぎ', True], [None, None, '、', None], ['警察', 'けいさつ', None, None], [None, None, 'に', None], ['捕', 'つか', None, None], [None, None, 'まった。', None]]
[['公園', 'こうえん', None, None], [None, None, 'に', None], ['行', 'い', None, True], [None, None, 'き', True], [None, None, '、', None], ['子供', 'こども', None, None], [None, None, 'と', None], ['遊', 'あそ', None, None], [None, None, 'んだ。', None]]
[['夢', 'ゆめ', None, None], [None, None, 'は', None], ['大', 'おお', None, True], [None, None, 'きく', True], [None, None, '、', None], ['志', 'こころざし', None, None], [None, None, 'は', None], ['高', 'たか', None, None], [None, None, 'く！', None]]

 52%|█████▏    | 485/938 [04:54<05:23,  1.40it/s]

[[None, None, 'この', None], ['部屋', 'へや', None, None], [None, None, 'は', None], ['南', 'みなみ', None, None], ['向', 'む', None, True], [None, None, 'き', True], [None, None, 'ですか。', None]]
[[None, None, 'それだと', None], ['向', 'む', None, True], [None, None, 'き', True], [None, None, 'が', None], ['逆', 'ぎゃく', None, None], [None, None, 'ですよ。', None]]
[['経済', 'けいざい', None, None], [None, None, 'は', None], ['上', 'うわ', None, None], ['向', 'む', None, True], [None, None, 'き', True], [None, None, 'のようですね。', None]]
[[None, None, 'あなたはいつも', None], ['前', 'まえ', None, None], ['向', 'む', None, True], [None, None, 'き', True], [None, None, 'な', None], ['人', 'ひと', None, None], [None, None, 'だ。', None]]
[[None, None, 'これは', None], ['若', 'わか', None, None], [None, None, 'い', None], ['者', 'もの', None, None], ['向', 'む', None, True], [None, None, 'き', True], [None, None, 'の', None], ['本', 'ほん', None, None], [None, None, 'だな。', None]]

 52%|█████▏    | 486/938 [04:54<05:28,  1.38it/s]

[[None, None, 'この', None], ['番組', 'ばんぐみ', None, None], [None, None, 'は', None], ['大人', 'おとな', None, None], ['向', 'む', None, True], [None, None, 'け', True], [None, None, 'だ。', None]]
[[None, None, 'これは', None], ['女性', 'じょせい', None, None], ['向', 'む', None, True], [None, None, 'け', True], [None, None, 'の', None], ['服', 'ふく', None, None], [None, None, 'だから、', None], ['僕', 'ぼく', None, None], [None, None, 'には', None], ['着', 'き', None, None], [None, None, 'れない。', None]]
[['Ｘ', 'エックス', None, None], [None, None, 'というライトノベルは', None], ['子供', 'こども', None, None], ['向', 'む', None, True], [None, None, 'け', True], [None, None, 'に', None], ['書', 'か', None, None], [None, None, 'かれたんだ。', None]]
[[None, None, 'このアプリは', None], ['学生', 'がくせい', None, None], ['向', 'む', None, True], [None, None, 'け', True], [None, None, 'だが、', None], ['誰', 'だれ', None, None], [None, None, 'でも', None], ['使用', 'しよう', None, None], [None, None, 'できる。', None]]
[[None, None, 'これは', None], ['海外', 'かいがい', None, None], ['向', 'む', None, True], [None, None, 'け', True], [None, None, 'の', None], ['番組', 'ばんぐみ', None, None], [None, None, 'だから、', None], ['何', 'なに', None, None], [None, None, 'を', None], ['言', 'い', None, None], [None, None, 'っているのか', None], ['全然', 'ぜんぜん', None, None], ['分', 'わ', None, None], [None, None, 'からない。', None]]

 52%|█████▏    | 487/938 [04:55<05:35,  1.34it/s]

[[None, None, 'ところで、やっと', None], ['絵', 'え', None, None], [None, None, 'が', None], ['描', 'えが', None, True], [None, None, 'き', True], ['上', 'あ', None, True], [None, None, 'がった', True], [None, None, 'よ。', None]]
[['作品', 'さくひん', None, None], [None, None, 'が', None], [None, None, 'し', True], ['上', 'あ', None, True], [None, None, 'がる', True], [None, None, '。', None]]
[[None, None, 'なんとかドレス', None], [None, None, 'を', None], ['縫', 'ぬ', None, True], [None, None, 'い', True], ['上', 'あ', None, True], [None, None, 'げました', True], [None, None, '。', None]]
[[None, None, 'ご', None], ['飯', 'はん', None, None], [None, None, 'が', None], ['炊', 'た', None, True], [None, None, 'きあがる', True], [None, None, '。', None]]
[['空', 'そら', None, None], [None, None, 'は', None], ['雨', 'あめ', None, None], [None, None, 'の', None], ['後', 'あと', None, None], [None, None, 'で', None], ['晴', 'は', None, True], [None, None, 'れ', True], ['上', 'あ', None, True], [None, None, 'がった', True], [None, None, '。', None]]

 52%|█████▏    | 488/938 [04:56<05:34,  1.35it/s]

[['使', 'つか', None, True], [None, None, 'い', True], ['切', 'き', None, True], [None, None, 'って', True], [None, None, 'から', None], ['次', 'つぎ', None, None], [None, None, 'のジャムを', None], ['買', 'か', None, None], [None, None, 'ってよ。', None]]
[['今日', 'きょう', None, None], [None, None, 'の', None], ['寒', 'さむ', None, None], [None, None, 'さで', None], ['冷', 'ひ', None, True], [None, None, 'え', True], ['切', 'き', None, True], [None, None, 'って', True], [None, None, 'しまいました。', None]]
[['給料', 'きゅうりょう', None, None], [None, None, 'をもらった', None], ['日', 'ひ', None, None], [None, None, 'に', None], ['使', 'つか', None, True], [None, None, 'い', True], ['切', 'き', None, True], [None, None, 'って', True], [None, None, 'しまった。', None]]
[[None, None, 'たとえどんなことがあっても', None], ['勇者', 'ゆうしゃ', None, None], [None, None, 'さまを', None], ['信', 'しん', None, True], [None, None, 'じ', True], ['切', 'き', None, True], [None, None, 'ります', True], [None, None, '。', None]]
[['先週末', 'せんしゅうまつ', None, None], [None, None, '、', None], ['三冊', 'さんさつ', None, None], [None, None, 'のマンガを', None], ['読', 'よ', None, True], [None, None, 'み', True], ['切', 'き', None, True], [None, None, 'った', True], [None, None, '。', None]]

 52%|█████▏    | 489/938 [04:57<05:26,  1.38it/s]

[['空', 'そら', None, None], [None, None, 'の', None], ['星', 'ほし', None, None], [None, None, 'の', None], ['数', 'かず', None, None], [None, None, 'が', None], ['数', 'かぞ', None, True], [None, None, 'え', True], ['切', 'き', None, True], [None, None, 'れない', True], [None, None, '。', None]]
[[None, None, 'お', None], ['皿', 'さら', None, None], [None, None, 'が', None], ['多', 'おお', None, None], [None, None, 'すぎて、', None], ['洗', 'あら', None, True], [None, None, 'い', True], ['切', 'き', None, True], [None, None, 'れない', True], [None, None, '。', None]]
[['新曲', 'しんきょく', None, None], [None, None, 'の', None], ['発売日', 'はつばいび', None, None], [None, None, 'が', None], ['待', 'ま', None, True], [None, None, 'ち', True], ['切', 'き', None, True], [None, None, 'れない', True], [None, None, '。', None]]
[['辛', 'から', None, None], [None, None, 'かったから、', None], ['食', 'た', None, True], [None, None, 'べ', True], ['切', 'き', None, True], [None, None, 'れなかった', True], [None, None, '。', None]]
[[None, None, 'この', None], ['溢', 'あふ', None, None], [None, None, 'れる', None], ['思', 'おも', None, None], [None, None, 'いを', None], ['抑', 'おさ', None, True], [None, None, 'え', True], ['切', 'き', None, True], [None, None, 'れない', True], [None, None, '。', None]]

 52%|█████▏    | 490/938 [04:57<05:17,  1.41it/s]

[[None, None, 'やっと', None], ['二人', 'ふたり', None, None], [None, None, 'っきり', True], [None, None, 'になれたね。', None]]
[['寂', 'さび', None, None], [None, None, 'しい', None], ['時', 'とき', None, None], [None, None, '、', None], ['一人', 'ひとり', None, None], [None, None, 'っきり', True], [None, None, 'で', None], ['泣', 'な', None, None], [None, None, 'く。', None]]
[['父', 'ちち', None, None], [None, None, 'がついに', None], ['寝', 'ね', None, None], [None, None, 'た', None], [None, None, 'きり', True], [None, None, 'になってしまった。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'とは', None], ['喧嘩', 'けんか', None, None], [None, None, 'した', None], [None, None, 'っきり', True], ['会', 'あ', None, None], [None, None, 'っていません。', None]]
[[None, None, 'チャンスは', None], ['一度', 'いちど', None, None], [None, None, 'きり', True], [None, None, 'しかない', None], [None, None, 'から', None], ['緊張', 'きんちょう', None, None], [None, None, 'する。', None]]

 52%|█████▏    | 491/938 [04:58<05:25,  1.37it/s]

[['食', 'た', None, True], [None, None, 'べ', True], ['掛', 'か', None, True], [None, None, 'けの', True], [None, None, 'ケーキでも', None], ['良', 'よ', None, None], [None, None, 'ければありますよ。', None]]
[['描', 'か', None, True], [None, None, 'き', True], ['掛', 'か', None, True], [None, None, 'けの', True], ['絵', 'え', None, None], [None, None, 'を', None], ['早', 'はや', None, None], [None, None, 'く', None], ['完成', 'かんせい', None, None], [None, None, 'させたい。', None]]
[[None, None, 'この', None], ['時計', 'とけい', None, None], ['壊', 'こわ', None, True], [None, None, 'れ', True], ['掛', 'か', None, True], [None, None, 'け', True], [None, None, 'だけど、ないよりはいいか。', None]]
[['忘', 'わす', None, True], [None, None, 'れ', True], ['掛', 'か', None, True], [None, None, 'けていた', True], ['思', 'おも', None, None], [None, None, 'い', None], ['出', 'で', None, None], [None, None, 'が', None], ['急', 'きゅう', None, None], [None, None, 'に', None], ['蘇', 'よみがえ', None, None], [None, None, 'った。', None]]
[['交通', 'こうつう', None, None], ['事故', 'じこ', None, None], [None, None, 'で', None], ['危', 'あや', None, None], [None, None, 'うく', None], ['死', 'し', None, True], [None, None, 'に', True], ['掛', 'か', None, True], [None, None, 'けた', True], [None, None, '。', None]]

 52%|█████▏    | 492/938 [04:59<05:25,  1.37it/s]

[['今週末', 'こんしゅうまつ', None, None], [None, None, 'に', True], ['掛', 'か', None, True], [None, None, 'けて', True], [None, None, '、', None], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'るでしょう。', None]]
[[None, None, 'この', None], ['一年', 'いちねん', None, None], [None, None, 'に', True], ['掛', 'か', None, True], [None, None, 'けて', True], [None, None, '、いろいろなことを', None], ['経験', 'けいけん', None, None], [None, None, 'したい。', None]]
[['先週', 'せんしゅう', None, None], [None, None, 'に', True], ['掛', 'か', None, True], [None, None, 'けて', True], ['降', 'ふ', None, None], [None, None, 'った', None], ['大雪', 'おおゆき', None, None], [None, None, 'が、まだ', None], ['全然', 'ぜんぜん', None, None], ['溶', 'と', None, None], [None, None, 'けない。', None]]
[['来年', 'らいねん', None, None], [None, None, 'に', True], ['掛', 'か', None, True], [None, None, 'けて', True], [None, None, 'の', None], ['目標', 'もくひょう', None, None], [None, None, 'を', None], ['立', 'た', None, None], [None, None, 'ててください。', None]]
[['関東', 'かんとう', None, None], [None, None, 'から', None], ['東北', 'とうほく', None, None], [None, None, 'に', True], ['掛', 'か', None, True], [None, None, 'けて', True], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'り', None], ['続', 'つづ', None, None], [None, None, 'いている。', None]]

 53%|█████▎    | 493/938 [04:59<05:00,  1.48it/s]

[['釣', 'つ', None, True], [None, None, 'り', True], ['立', 'た', None, True], [None, None, 'ての', True], ['魚', 'さかな', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べるのは', None], ['最高', 'さいこう', None, None], [None, None, '！', None]]
[[None, None, 'この', None], ['魚', 'さかな', None, None], [None, None, 'は', None], ['焼', 'や', None, True], [None, None, 'き', True], ['立', 'た', None, True], [None, None, 'て', True], [None, None, 'です。', None]]
[['出来', 'でき', None, True], ['立', 'た', None, True], [None, None, 'て', True], [None, None, 'の', None], [None, None, 'お', None], ['菓子', 'かし', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べたのは', None], ['初', 'はじ', None, None], [None, None, 'めてだ。', None]]
[[None, None, 'このお', None], ['店', 'みせ', None, None], [None, None, 'では', None], [None, None, 'とり', True], ['立', 'た', None, True], [None, None, 'ての', True], ['野菜', 'やさい', None, None], [None, None, 'が', None], ['買', 'か', None, None], [None, None, 'えます。', None]]
[['淹', 'い', None, True], [None, None, 'れ', True], ['立', 'た', None, True], [None, None, 'ての', True], [None, None, 'コーヒーの', None], ['香', 'かお', None, None], [None, None, 'りが', None], ['好', 'す', None, None], [None, None, 'きだ。', None]]

 53%|█████▎    | 494/938 [05:00<04:43,  1.57it/s]

[['教師', 'きょうし', None, None], [None, None, '：「', None], ['教科書', 'きょうかしょ', None, None], [None, None, 'に', None], ['答', 'こた', None, None], [None, None, 'えを', None], ['書', 'か', None, True], [None, None, 'き', True], ['込', 'こ', None, True], [None, None, 'んで', True], [None, None, 'ください。」', None]]
[[None, None, 'トムはジェロニモと', None], ['叫', 'さけ', None, None], [None, None, 'びながら、プールに', None], ['飛', 'と', None, True], [None, None, 'び', True], ['込', 'こ', None, True], [None, None, 'んだ', True], [None, None, '。', None]]
[['Ａ', 'エー', None, None], [None, None, '：「どうして', None], ['窓', 'まど', None, None], [None, None, 'が', None], ['閉', 'し', None, None], [None, None, 'めてあるの？」', None], ['Ｂ', 'ビー', None, None], [None, None, '：「', None], ['冷', 'つめ', None, None], [None, None, 'たい', None], ['風', 'かぜ', None, None], [None, None, 'が', None], ['入', 'はい', None, True], [None, None, 'りこまない', True], [None, None, 'ように。」', None]]
[[None, None, 'バッキンガム', None], ['宮殿', 'きゅうでん', None, None], [None, None, 'の', None], ['警護官', 'けいごかん', None, None], [None, None, 'について', None], [None, None, '：「', None], ['笑', 'わら', None, None], [None, None, 'いを', None], ['飲', 'の', None, True], [None, None, 'み', True], ['込', 'こ', None, True], [None, None, 'み', True], [None, None, 'ながら', None], [None, None, '、', None], ['移動', 'いどう', None, None], [None, None, 'せずに', None], ['立', 'た', None, None], [None, None, 'った', None], [None, None, 'まま', None], [None, None, 'だった', None], [None, None, '。」', None]]
[['友達', 'ともだち', None, None], [None, None, 'との', None], ['話', 'はなし', None, None], [None, None, '：「', None], ['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['泥棒', 'どろぼう', None, None], [None, None, 'の', None], ['顎', 'あご', None, None], [None, None, 'に', None], ['見事', 'みごと', None, None], [None, None, 'に', None], ['拳', 'こぶし', None, None], [None, None, 'を', None], ['打', 'う', None, True], [None, None, 'ち', True], ['込', 'こ', None, True], [None, None, 'んだ', True], [None, None, 'そうだ。」', None]]

 53%|█████▎    | 495/938 [05:01<04:56,  1.49it/s]

[[None, None, 'みんないっせいに', None], ['黙', 'だま', None, True], [None, None, 'り', True], ['込', 'こ', None, True], [None, None, 'んでいた', True], [None, None, '。', None]]
[[None, None, 'ノベル', None], [None, None, '：「れつこは', None], ['気分', 'きぶん', None, None], [None, None, 'が', None], ['悪', 'わる', None, None], [None, None, 'くなり、', None], ['座', 'すわ', None, True], [None, None, 'り', True], ['込', 'こ', None, True], [None, None, 'んだ', True], [None, None, '。」', None]]
[['疲', 'つか', None, None], [None, None, 'れていたので、シャワーを', None], ['浴', 'あ', None, None], [None, None, 'びずに', None], ['眠', 'ねむ', None, True], [None, None, 'り', True], ['込', 'こ', None, True], [None, None, 'んだ', True], [None, None, '。', None]]
[['友達', 'ともだち', None, None], [None, None, 'との', None], ['話', 'はなし', None, None], [None, None, '：「', None], ['何', 'なに', None, None], [None, None, 'を', None], ['長々', 'ながなが', None, None], ['話', 'はな', None, True], [None, None, 'し', True], ['込', 'こ', None, True], [None, None, 'んでた', True], [None, None, 'の？」', None]]
[[None, None, 'エッセイ', None], [None, None, '：「', None], ['熱心', 'ねっしん', None, None], [None, None, 'にひとつの', None], ['事', 'こと', None, None], [None, None, 'に', None], ['打', 'う', None, True], [None, None, 'ち', True], ['込', 'こ', None, True], [None, None, 'む', True], [None, None, 'ことが', None], ['必要', 'ひつよう', None, None], [None, None, 'だと', None], ['思', 'おも', None, None], [None, None, 'っている。」', None]]

 53%|█████▎    | 496/938 [05:01<05:10,  1.42it/s]

[['泣', 'な', None, True], [None, None, 'いた', True], ['振', 'ふ', None, True], [None, None, 'りをした', True], [None, None, 'って', None], ['無駄', 'むだ', None, None], [None, None, 'ですよ。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['犬', 'いぬ', None, None], [None, None, 'は', None], ['寝', 'ね', None, True], [None, None, 'た', True], ['振', 'ふ', None, True], [None, None, 'りをする', True], [None, None, 'ことがある。', None]]
[['子供', 'こども', None, None], [None, None, 'は、', None], ['注意', 'ちゅうい', None, None], [None, None, 'された', None], ['時', 'とき', None, None], [None, None, 'に、', None], ['聞', 'き', None, True], [None, None, 'こえない', True], ['振', 'ふ', None, True], [None, None, 'りをした', True], [None, None, '。', None]]
[['病気', 'びょうき', None, None], [None, None, 'の', True], ['振', 'ふ', None, True], [None, None, 'りをして', True], ['会社', 'かいしゃ', None, None], [None, None, 'を', None], ['休', 'やす', None, None], [None, None, 'んだ。', None]]
[['見', 'み', None, None], [None, None, 'て', None], ['見', 'み', None, None], [None, None, 'ない', None], ['振', 'ふ', None, True], [None, None, 'りをする', True], [None, None, 'のは', None], ['良', 'よ', None, None], [None, None, 'くない。', None]]

 53%|█████▎    | 497/938 [05:02<05:05,  1.44it/s]

[[None, None, 'できたら', True], ['運転', 'うんてん', None, None], [None, None, 'して', None], ['欲', 'ほ', None, None], [None, None, 'しいです。', None]]
[[None, None, 'できれば', True], [None, None, 'お', None], ['弁当', 'べんとう', None, None], [None, None, 'を', None], ['作', 'つく', None, None], [None, None, 'ってほしいな。', None]]
[[None, None, 'できれば', True], ['本人', 'ほんにん', None, None], [None, None, 'と', None], ['会', 'あ', None, None], [None, None, 'って', None], ['話', 'はなし', None, None], [None, None, 'がしたい。', None]]
[[None, None, 'それが', None], [None, None, 'できたら', True], ['嬉', 'うれ', None, None], [None, None, 'しいんですけど。', None]]
[[None, None, 'できれば', True], [None, None, 'あの', None], ['会社', 'かいしゃ', None, None], [None, None, 'で', None], ['働', 'はたら', None, None], [None, None, 'きたい。', None]]

 53%|█████▎    | 498/938 [05:03<05:00,  1.47it/s]

[[None, None, 'この', None], ['籠', 'かご', None, None], [None, None, 'で', True], ['良', 'よ', None, True], [None, None, 'ければ', True], ['作', 'つく', None, None], [None, None, 'れますよ。', None]]
[[None, None, 'この', None], ['傘', 'かさ', None, None], [None, None, 'で', True], ['良', 'よ', None, True], [None, None, 'ければ', True], [None, None, 'お', None], ['貸', 'か', None, None], [None, None, 'しできます。', None]]
[['日中', 'にっちゅう', None, None], [None, None, 'で', True], ['良', 'よ', None, True], [None, None, 'ければ', True], ['空', 'あ', None, None], [None, None, 'いてます。', None]]
[[None, None, 'この', None], ['値段', 'ねだん', None, None], [None, None, 'で', True], ['良', 'よ', None, True], [None, None, 'ければ', True], ['売', 'う', None, None], [None, None, 'ります。', None]]
[[None, None, 'これくらいの', None], ['出来', 'でき', None, None], [None, None, 'で', True], ['良', 'よ', None, True], [None, None, 'ければ', True], [None, None, '、すぐに', None], ['作', 'つく', None, None], [None, None, 'れます。', None]]

 53%|█████▎    | 499/938 [05:03<05:09,  1.42it/s]

[['準備', 'じゅんび', None, None], [None, None, 'が', None], ['出来', 'でき', None, True], ['次第', 'しだい', None, True], ['出発', 'しゅっぱつ', None, None], [None, None, 'しますよ。', None]]
[['彼', 'かれ', None, None], [None, None, 'が', None], ['来', 'き', None, True], ['次第', 'しだい', None, True], [None, None, '、', None], ['知', 'し', None, None], [None, None, 'らせてください。', None]]
[[None, None, 'プロジェクトが', None], ['済', 'す', None, True], [None, None, 'み', True], ['次第', 'しだい', None, True], [None, None, '、ご', None], ['連絡', 'れんらく', None, None], [None, None, 'ください。', None]]
[[None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'を', None], ['受', 'う', None, True], [None, None, 'け', True], ['取', 'と', None, True], [None, None, 'り', True], ['次第', 'しだい', None, True], [None, None, '、', None], ['郵送', 'ゆうそう', None, None], [None, None, 'します。', None]]
[['学校', 'がっこう', None, None], [None, None, 'を', None], ['卒業', 'そつぎょう', None, None], [None, None, 'し', True], ['次第', 'しだい', None, True], [None, None, '、', None], ['仕事', 'しごと', None, None], [None, None, 'を', None], ['探', 'さが', None, None], [None, None, 'すつもりだ。', None]]

 53%|█████▎    | 500/938 [05:04<05:05,  1.43it/s]

[['思', 'おも', None, None], [None, None, 'った', None], ['通', 'とお', None, True], [None, None, 'り', True], [None, None, 'でした。', None]]
[[None, None, 'あなたのおっしゃる', None], ['通', 'とお', None, True], [None, None, 'り', True], [None, None, 'です。', None]]
[['合格者', 'ごうかくしゃ', None, None], [None, None, 'は', None], ['次', 'つぎ', None, None], [None, None, 'の', True], ['通', 'とお', None, True], [None, None, 'り', True], [None, None, 'です。', None]]
[[None, None, 'お', None], ['察', 'さっ', None, None], [None, None, 'し', None], [None, None, 'の', True], ['通', 'とお', None, True], [None, None, 'り', True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'は', None], ['病気', 'びょうき', None, None], [None, None, 'です。', None]]
[['物事', 'ものごと', None, None], [None, None, 'はいつも', None], ['計画', 'けいかく', None, None], ['通', 'どお', None, True], [None, None, 'り', True], [None, None, 'にはいかないものだなぁ。', None]]

 53%|█████▎    | 501/938 [05:05<05:04,  1.43it/s]

[[None, None, 'この', None], ['車', 'くるま', None, None], [None, None, 'は', None], ['少', 'すこ', None, None], [None, None, 'し', None], ['狭', 'せま', None, None], [None, None, 'いけれども、', None], ['快適', 'かいてき', None, None], [None, None, 'でもある', True], [None, None, '。', None]]
[[None, None, 'オーストラリアは', None], ['国', 'くに', None, None], [None, None, 'であり、', None], ['大陸', 'たいりく', None, None], [None, None, 'でもある', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['優', 'すぐ', None, None], [None, None, 'れたプログラマーだ。そして', None], ['多言語', 'たげんご', None, None], ['話者', 'わしゃ', None, None], [None, None, 'でもある', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['良', 'い', None, None], [None, None, 'い', None], ['社長', 'しゃちょう', None, None], [None, None, 'であったし、', None], ['良', 'い', None, None], [None, None, 'い', None], ['父親', 'ちちおや', None, None], [None, None, 'でもあった', True], [None, None, '。', None]]
[[None, None, 'ひとみさんは', None], ['中学生', 'ちゅうがくせい', None, None], [None, None, 'であるとともに', None], ['社長', 'しゃちょう', None, None], [None, None, 'でもある', True], [None, None, '。', None]]

 54%|█████▎    | 502/938 [05:05<05:02,  1.44it/s]

[[None, None, 'どうしても', True], [None, None, 'お', None], ['土産', 'みやげ', None, None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'いたい。', None]]
[['食', 'た', None, None], [None, None, 'べる', None], [None, None, 'とどうしても', True], ['眠', 'ねむ', None, None], [None, None, 'たくなる。', None]]
[[None, None, 'どうしても', True], [None, None, 'アイスクリームが', None], ['食', 'た', None, None], [None, None, 'べたい。', None]]
[['君', 'きみ', None, None], [None, None, 'に', None], [None, None, 'どうしても', True], ['伝', 'つた', None, None], [None, None, 'えたいことがある。', None]]
[[None, None, 'この', None], ['癖', 'くせ', None, None], [None, None, 'は', None], [None, None, 'どうしても', True], ['治', 'なお', None, None], [None, None, 'らない。', None]]

 54%|█████▎    | 503/938 [05:06<05:17,  1.37it/s]

[[None, None, 'もしも', True], [None, None, 'ドラえもんがいた', None], [None, None, 'なら', None], [None, None, '、', None], ['助', 'たす', None, None], [None, None, 'けてもらえるのに。', None]]
[[None, None, 'もしも', True], ['僕', 'ぼく', None, None], [None, None, 'がドラえもん', None], [None, None, 'でも', None], ['助', 'たす', None, None], [None, None, 'けられない。', None]]
[[None, None, 'もしも', True], ['戦', 'たたか', None, None], [None, None, 'う', None], [None, None, 'なら', None], ['囲碁', 'いご', None, None], [None, None, 'がいい。', None]]
[[None, None, 'もしも', True], ['可能', 'かのう', None, None], [None, None, 'なら', None], [None, None, '、', None], ['僕', 'ぼく', None, None], [None, None, 'も', None], ['仲間', 'なかま', None, None], [None, None, 'に', None], ['入', 'はい', None, None], [None, None, 'りたい。', None]]
[[None, None, 'もしも', True], [None, None, 'これが', None], ['現実', 'げんじつ', None, None], [None, None, 'でも', None], [None, None, '、', None], ['受', 'う', None, None], [None, None, 'け', None], ['入', 'い', None, None], [None, None, 'れられると', None], ['思', 'おも', None, None], [None, None, 'います。', None]]

 54%|█████▎    | 504/938 [05:07<05:29,  1.32it/s]

[[None, None, 'このように', None], ['紐', 'ひも', None, None], [None, None, 'でページ', None], ['同士', 'どうし', None, True], [None, None, 'を', None], ['結', 'むす', None, None], [None, None, 'びつけることができます。', None]]
[['負', 'ま', None, None], [None, None, 'けた', None], ['者', 'もの', None, None], ['同士', 'どうし', None, True], [None, None, 'で', None], ['飲', 'の', None, None], [None, None, 'みに', None], ['行', 'い', None, None], [None, None, 'こうよ！', None]]
[['中学生', 'ちゅうがくせい', None, None], ['同士', 'どうし', None, True], [None, None, 'は', None], ['結婚', 'けっこん', None, None], [None, None, 'するには', None], ['若', 'わか', None, None], [None, None, 'すぎる。', None]]
[['同級生', 'どうきゅうせい', None, None], ['同士', 'どうし', None, True], [None, None, 'だから、', None], ['助', 'たす', None, None], [None, None, 'け', None], ['合', 'あ', None, None], [None, None, 'わなきゃね。', None]]
[['友達', 'ともだち', None, None], ['同士', 'どうし', None, True], [None, None, 'の', True], ['約束', 'やくそく', None, None], [None, None, 'だったのに', None], ['彼', 'かれ', None, None], [None, None, 'は', None], ['破', 'やぶ', None, None], [None, None, 'った。', None]]

 54%|█████▍    | 505/938 [05:08<05:20,  1.35it/s]

[[None, None, 'あの', None], ['罪', 'つみ', None, None], [None, None, 'は', None], ['許', 'ゆる', None, True], [None, None, 'しがたい', True], [None, None, '。', None]]
[[None, None, 'もう', None], ['一', 'ひと', None, None], [None, None, 'つのアイデアも', None], ['捨', 'す', None, True], [None, None, 'てがたい', True], [None, None, '。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'の', None], ['言', 'い', None, None], [None, None, 'っていることは', None], ['信', 'しん', None, True], [None, None, 'じがたい', True], [None, None, 'ですね。', None]]
[['忘', 'わす', None, True], [None, None, 'れがたい', True], ['出来事', 'できごと', None, None], [None, None, 'に', None], ['遭遇', 'そうぐう', None, None], [None, None, 'した。', None]]
[['皆', 'みんな', None, None], [None, None, 'から', None], ['近寄', 'ちかよ', None, True], [None, None, 'りがたい', True], [None, None, 'ってよく', None], ['言', 'い', None, None], [None, None, 'われます。', None]]

 54%|█████▍    | 506/938 [05:08<05:11,  1.39it/s]

[[None, None, 'まさか', True], [None, None, 'こんなところで', None], ['君', 'きみ', None, None], [None, None, 'に', None], ['出会', 'であ', None, None], [None, None, 'えるなんて⁉︎', None]]
[[None, None, 'まさか', True], [None, None, 'こんな', None], ['大雪', 'おおゆき', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'るなんて', None], ['思', 'おも', None, None], [None, None, 'わなかった。', None]]
[[None, None, 'まさか', True], [None, None, '…あのこと', None], ['本当', 'ほんとう', None, None], [None, None, 'に', None], ['彼', 'かれ', None, None], [None, None, 'に', None], ['話', 'はな', None, None], [None, None, 'したの？', None]]
[[None, None, 'まさか', True], [None, None, '…また', None], ['財布', 'さいふ', None, None], ['忘', 'わす', None, None], [None, None, 'れたわけじゃないよね。', None]]
[[None, None, 'まさか', True], ['彼', 'かれ', None, None], [None, None, 'が', None], ['犯人', 'はんにん', None, None], [None, None, 'だなんて… ショックだ。', None]]

 54%|█████▍    | 507/938 [05:09<05:07,  1.40it/s]

[[None, None, 'ダンゴムシとワラジムシ、', None], ['前者', 'ぜんしゃ', None, True], [None, None, 'は', True], ['触', 'さわ', None, None], [None, None, 'ると', None], ['丸', 'まる', None, None], [None, None, 'まり、', None], ['後者', 'こうしゃ', None, None], [None, None, 'は', None], ['触', 'さわ', None, None], [None, None, 'っても', None], ['丸', 'まる', None, None], [None, None, 'まらないという', None], ['違', 'ちが', None, None], [None, None, 'いがあります。', None]]
[[None, None, 'そうめんと', None], ['冷麦', 'ひやむぎ', None, None], [None, None, '、', None], ['前者', 'ぜんしゃ', None, None], [None, None, 'は', None], ['細', 'ほそ', None, None], [None, None, 'く、', None], ['後者', 'こうしゃ', None, True], [None, None, 'は', True], ['少', 'すこ', None, None], [None, None, 'し', None], ['太', 'ふと', None, None], [None, None, 'い。', None]]
[['宿泊', 'しゅくはく', None, None], ['場所', 'ばしょ', None, None], [None, None, 'の', None], ['候補', 'こうほ', None, None], [None, None, 'が', None], ['二', 'ふた', None, None], [None, None, 'つあります。', None], ['前者', 'ぜんしゃ', None, None], [None, None, 'は', None], ['温泉', 'おんせん', None, None], [None, None, 'があり、', None], ['後者', 'こうしゃ', None, True], [None, None, 'は', True], [None, None, 'ご', None], ['飯', 'はん', None, None], [None, None, 'がおいしいです。', None]]
[['交通', 'こうつう', None, None], [None, None, 'の', None], ['札', 'ふだ', None, None], [None, None, 'には', None], ['切符', 'きっぷ', None, None], [None, None, 'と', None], ['整理券', 'せいりけん', None, None], [None, None, 'の', None], ['二', 'ふた', None, None], [None, None, 'つがあります。', None], ['前者', 'ぜんしゃ', None, True], [None, None, 'は', True], ['電車', 'でんしゃ', None, None], [None, None, 'に', None], ['乗', 'の', None, None], [None, None, 'るために', None], ['必要', 'ひつよう', None, None], [None, None, 'なもので、', None], ['後者', 'こうしゃ', None, None], [None, None, 'は', None], [None, None, 'バスに', None], ['乗', 'の', None, None], [None, None, 'るときに', None], ['取', 'と', None, None], [None, None, 'るものです。', None]]
[[None, None, 'どちらのパソコンがいいですか？', None], ['前者', 'ぜんしゃ', None, True], [None, None, 'は', True], ['安', 'やす', None, None], [None, None, 'いが', None], ['性能', 'せいのう', None, None], [None, None, 'は', None], ['一般', 'いっぱん', None, None], ['向', 'む', None, None], [None, None, 'け、', None], ['後者', 'こうしゃ', None, None], [None, None, 'は', None], ['高', 'たか', None, None], [None, None, 'いが', None], ['高性能', 'こうせいのう', None, None], [None, None, '。', None]]

 54%|█████▍    | 508/938 [05:10<04:42,  1.52it/s]

[[None, None, 'つい', True], ['楽', 'らく', None, None], [None, None, 'な', None], ['方', 'ほう', None, None], [None, None, 'に', None], ['流', 'なが', None, None], [None, None, 'されてしまう。', None]]
[['運転', 'うんてん', None, None], ['中', 'ちゅう', None, None], [None, None, '、', None], [None, None, 'つい', True], [None, None, 'よそ', None], ['見', 'み', None, None], [None, None, 'をしてしまう。', None]]
[['運動', 'うんどう', None, None], [None, None, 'を', None], ['始', 'はじ', None, None], [None, None, 'めると、', None], [None, None, 'つい', True], [None, None, 'やり', None], ['過', 'す', None, None], [None, None, 'ぎてしまう。', None]]
[['笑', 'わら', None, None], [None, None, 'ってはいけないのに、', None], [None, None, 'つい', True], ['笑', 'わら', None, None], [None, None, 'ってしまう。', None]]
[[None, None, '「', None], [None, None, 'つい', True], ['食', 'た', None, None], [None, None, 'べ', None], ['過', 'す', None, None], [None, None, 'ぎてしまう」なんて', None], ['言', 'い', None, None], [None, None, 'い', None], ['訳', 'わけ', None, None], [None, None, 'だ。', None]]

 54%|█████▍    | 509/938 [05:10<04:48,  1.49it/s]

[[None, None, 'トムは', None], ['暑', 'あつ', None, None], [None, None, 'さ', None], [None, None, 'のせいで', True], ['気', 'き', None, None], [None, None, 'を', None], ['失', 'うしな', None, None], [None, None, 'った。', None]]
[['誰', 'だれ', None, None], [None, None, 'のせい', True], [None, None, 'でもないと', None], ['思', 'おも', None, None], [None, None, 'います。', None]]
[['湿気', 'しっけ', None, None], [None, None, 'のせいで', True], [None, None, 'カビがひどい。', None]]
[[None, None, 'ストレス', None], [None, None, 'のせいで', True], ['病気', 'びょうき', None, None], [None, None, 'になってしまった。', None]]
[['物忘', 'ものわす', None, None], [None, None, 'れがひどいのは、たぶん', None], ['年', 'とし', None, None], [None, None, 'のせい', True], [None, None, 'です。', None]]

 54%|█████▍    | 510/938 [05:11<04:33,  1.57it/s]

[['食', 'た', None, None], [None, None, 'べきれない', None], ['癖', 'くせ', None, True], [None, None, 'に', True], [None, None, 'たくさん', None], ['注文', 'ちゅうもん', None, None], [None, None, 'するのはやめてほしい。', None]]
[['昨日', 'きのう', None, None], ['休', 'やす', None, None], [None, None, 'んだ', None], ['癖', 'くせ', None, True], [None, None, 'に', True], [None, None, '、なんで', None], ['知', 'し', None, None], [None, None, 'ったかぶりするの？', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'は', None], ['先輩', 'せんぱい', None, None], [None, None, 'の', True], ['癖', 'くせ', None, True], [None, None, 'に', True], [None, None, '、いつも', None], ['僕', 'ぼく', None, None], [None, None, 'におごらせようとする。', None]]
[['寒', 'さむ', None, None], [None, None, 'い', None], ['癖', 'くせ', None, True], [None, None, 'に', True], [None, None, '「', None], ['寒', 'さむ', None, None], [None, None, 'くない」とやせ', None], ['我慢', 'がまん', None, None], [None, None, 'するのはやめてください。', None]]
[['給料', 'きゅうりょう', None, None], [None, None, 'を', None], ['沢山', 'たくさん', None, None], [None, None, 'もらっている', None], ['癖', 'くせ', None, True], [None, None, 'に', True], [None, None, '、', None], ['貯金', 'ちょきん', None, None], [None, None, 'がないらしい。', None]]

 54%|█████▍    | 511/938 [05:12<04:38,  1.53it/s]

[[None, None, 'それは', None], ['初心者', 'しょしんしゃ', None, None], [None, None, 'に', None], [None, None, 'ありがち', True], [None, None, 'のミスですね。', None]]
[['彼', 'かれ', None, None], [None, None, 'はいつも', None], ['遠慮', 'えんりょ', None, None], [None, None, 'がち', True], [None, None, 'だ。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['息子', 'むすこ', None, None], [None, None, 'は', None], ['病気', 'びょうき', None, None], [None, None, 'がち', True], [None, None, 'だ。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'はすぐ、', None], ['痩', 'や', None, None], [None, None, 'せることを', None], ['諦', 'あきら', None, True], [None, None, 'めがち', True], [None, None, 'だ。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], ['昔', 'むかし', None, None], [None, None, 'から', None], ['遅刻', 'ちこく', None, None], [None, None, 'しがち', True], [None, None, 'だ。', None]]

 55%|█████▍    | 512/938 [05:12<04:33,  1.56it/s]

[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['風邪', 'かぜ', None, None], ['気味', 'ぎみ', None, True], [None, None, 'だと', None], ['言', 'い', None, None], [None, None, 'った。', None]]
[['最近', 'さいきん', None, None], [None, None, '、', None], ['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['太', 'ふと', None, True], [None, None, 'り', True], ['気味', 'ぎみ', None, True], [None, None, 'らしい。', None]]
[['貧血', 'ひんけつ', None, None], ['気味', 'ぎみ', None, True], [None, None, 'なので、', None], ['採血', 'さいけつ', None, None], [None, None, 'はやめておきましょう。', None]]
[['暗', 'くら', None, None], [None, None, 'いニュースばかりで', None], ['食傷', 'しょくしょう', None, None], ['気味', 'ぎみ', None, True], [None, None, 'だ。', None]]
[['台風', 'たいふう', None, None], [None, None, 'のせいで', None], ['天気', 'てんき', None, None], [None, None, 'が', None], ['荒', 'あ', None, True], [None, None, 'れ', True], ['気味', 'ぎみ', None, True], [None, None, 'だ。', None]]

 55%|█████▍    | 513/938 [05:13<04:50,  1.46it/s]

[['寅', 'とら', None, None], [None, None, 'さんは', None], ['惚', 'ほ', None, True], [None, None, 'れっぽく', True], [None, None, '、', None], ['飽', 'あ', None, None], [None, None, 'きっぽい。', None]]
[[None, None, 'なんかこの', None], ['牛乳', 'ぎゅうにゅう', None, None], [None, None, 'は', None], ['水', 'みず', None, True], [None, None, 'っぽい', True], [None, None, 'な。', None]]
[['怒', 'おこ', None, True], [None, None, 'りっぽい', True], ['人', 'ひと', None, None], [None, None, 'はあまり', None], ['好', 'す', None, None], [None, None, 'かれない。', None]]
[[None, None, 'トムは', None], ['記憶力', 'きおくりょく', None, None], [None, None, 'がいいどころか、', None], ['忘', 'わす', None, True], [None, None, 'れっぽい', True], [None, None, 'よ。', None]]
[[None, None, 'こういう', None], ['時', 'とき', None, None], [None, None, 'は', None], ['黒', 'くろ', None, True], [None, None, 'っぽい', True], [None, None, 'スーツを', None], ['着', 'き', None, None], [None, None, 'るべきか？', None]]

 55%|█████▍    | 514/938 [05:14<04:57,  1.43it/s]

[['誰', 'だれ', None, None], [None, None, 'かがそのドアを', None], ['開', 'あ', None, True], [None, None, 'けっ', True], ['放', 'ぱな', None, True], [None, None, 'し', True], [None, None, 'にした。', None]]
[[None, None, 'ライトを', None], [None, None, 'つけっ', True], ['放', 'ぱな', None, True], [None, None, 'し', True], [None, None, 'にしないで。', None]]
[['電話', 'でんわ', None, None], [None, None, 'が', None], ['鳴', 'な', None, True], [None, None, 'りっ', True], ['放', 'ぱな', None, True], [None, None, 'し', True], [None, None, 'だけど…', None], ['大丈夫', 'だいじょうぶ', None, None], [None, None, '？', None]]
[[None, None, 'いつも', None], ['開', 'あ', None, True], [None, None, 'けっ', True], ['放', 'ぱな', None, True], [None, None, 'し', True], [None, None, 'で、ちゃんと', None], ['閉', 'し', None, None], [None, None, 'めてよね。', None]]
[['水', 'みず', None, None], [None, None, 'を', None], ['出', 'だ', None, True], [None, None, 'しっ', True], ['放', 'ぱな', None, True], [None, None, 'し', True], [None, None, 'にするのはやめてください。', None]]

 55%|█████▍    | 515/938 [05:14<04:55,  1.43it/s]

[[None, None, 'わざわざ', True], [None, None, 'ここまで', None], ['働', 'はたら', None, None], [None, None, 'きに', None], ['来', 'き', None, None], [None, None, 'ているんですね。', None]]
[[None, None, 'わざわざ', True], ['批判', 'ひはん', None, None], [None, None, 'しなくてもいいのに。', None]]
[[None, None, 'わざわざ', True], ['独', 'ひと', None, None], [None, None, 'りで', None], ['行', 'い', None, None], [None, None, 'くんですか？', None]]
[[None, None, 'わざわざ', True], ['傘', 'かさ', None, None], [None, None, 'を', None], ['返', 'かえ', None, None], [None, None, 'しに', None], ['来', 'き', None, None], [None, None, 'てくれたの？', None]]
[[None, None, 'わざわざ', True], ['自慢', 'じまん', None, None], [None, None, 'しなくてもいいじゃないか。', None]]

 55%|█████▌    | 516/938 [05:15<04:54,  1.43it/s]

[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'は', None], ['一体', 'いったい', None, True], ['誰', 'だれ', None, None], [None, None, 'なのだろう…', None]]
[['一体', 'いったい', None, True], [None, None, 'いつ', None], [None, None, '、', None], ['掃除', 'そうじ', None, None], [None, None, 'をする', None], ['暇', 'ひま', None, None], [None, None, 'があるというんだ。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['一体', 'いったい', None, True], [None, None, 'どう', None], [None, None, 'いうつもりなんだ。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'は', None], ['一体', 'いったい', None, True], ['何', 'なん', None, None], ['歳', 'さい', None, None], [None, None, 'なんだろう。', None]]
[['僕', 'ぼく', None, None], [None, None, 'たちの', None], ['未来', 'みらい', None, None], [None, None, 'は', None], ['一体', 'いったい', None, True], [None, None, 'どうなる', None], [None, None, 'んだろう…', None]]

 55%|█████▌    | 517/938 [05:16<04:40,  1.50it/s]

[['折角', 'せっかく', None, True], [None, None, 'この', None], ['旅行', 'りょこう', None, None], [None, None, 'の', None], ['準備', 'じゅんび', None, None], [None, None, 'してきたのに....', None]]
[['折角', 'せっかく', None, True], [None, None, 'の', True], ['友達', 'ともだち', None, None], [None, None, 'との', None], ['遠足', 'えんそく', None, None], [None, None, 'だから、たくさん', None], ['遊', 'あそ', None, None], [None, None, 'びたい。', None]]
[['折角', 'せっかく', None, True], [None, None, 'の', True], [None, None, 'デートが', None], ['風邪', 'かぜ', None, None], [None, None, 'でつぶれた。ちょっと', None], ['残念', 'ざんねん', None, None], [None, None, 'だよ。', None]]
[['折角', 'せっかく', None, True], ['大学', 'だいがく', None, None], [None, None, 'を', None], ['卒業', 'そつぎょう', None, None], [None, None, 'したんだから、いい', None], ['会社', 'かいしゃ', None, None], [None, None, 'で', None], ['働', 'はたら', None, None], [None, None, 'くつもりだ。', None]]
[['折角', 'せっかく', None, True], ['高性能', 'こうせいのう', None, None], [None, None, 'のコンピューターを', None], ['買', 'か', None, None], [None, None, 'ったんだから、', None], ['新', 'あたら', None, None], [None, None, 'しいゲームをしようと', None], ['思', 'おも', None, None], [None, None, 'う。', None]]

 55%|█████▌    | 518/938 [05:16<04:44,  1.48it/s]

[[None, None, 'そんなもの', None], ['家', 'いえ', None, None], [None, None, 'にあった', None], [None, None, 'っけ', True], [None, None, '？', None]]
[['明日', 'あした', None, None], [None, None, 'って', None], ['晴', 'は', None, None], [None, None, 'れるんだ', None], [None, None, 'っけ', True], [None, None, '？', None]]
[[None, None, 'もうすぐ', None], ['梅雨', 'つゆ', None, None], [None, None, 'も', None], ['終', 'お', None, None], [None, None, 'わりだ', None], [None, None, 'っけ', True], [None, None, '？', None]]
[[None, None, 'この', None], ['資料', 'しりょう', None, None], ['渡', 'わた', None, None], [None, None, 'した', None], [None, None, 'っけ', True], [None, None, '？', None]]
[['一昨日', 'おととい', None, None], [None, None, 'もラーメン', None], ['食', 'た', None, None], [None, None, 'べた', None], [None, None, 'っけ', True], [None, None, '？', None]]

 55%|█████▌    | 519/938 [05:17<04:26,  1.57it/s]

[[None, None, 'バター', None], [None, None, 'の', True], ['代', 'か', None, True], [None, None, 'わりに', True], [None, None, 'マーガリンを', None], ['使', 'つか', None, None], [None, None, 'っています。', None]]
[[None, None, 'コーヒー', None], [None, None, 'の', True], ['代', 'か', None, True], [None, None, 'わりに', True], ['紅茶', 'こうちゃ', None, None], [None, None, 'では', None], ['駄目', 'だめ', None, None], [None, None, 'ですか？', None]]
[['玉', 'たま', None, None], [None, None, 'ねぎ', None], [None, None, 'の', True], ['代', 'か', None, True], [None, None, 'わりに', True], ['長', 'なが', None, None], [None, None, 'ねぎを', None], ['使', 'つか', None, None], [None, None, 'おう。', None]]
[['電話', 'でんわ', None, None], [None, None, 'の', True], ['代', 'か', None, True], [None, None, 'わりに', True], [None, None, '、メールを', None], ['送', 'おく', None, None], [None, None, 'った。', None]]
[['私', 'わたし', None, None], [None, None, 'の', True], ['代', 'か', None, True], [None, None, 'わりに', True], [None, None, 'この', None], ['問題', 'もんだい', None, None], [None, None, 'を', None], ['解', 'と', None, None], [None, None, 'いてください。', None]]

 55%|█████▌    | 520/938 [05:18<04:38,  1.50it/s]

[['月', 'つき', None, None], [None, None, 'に', True], ['代', 'か', None, True], [None, None, 'わって', True], [None, None, 'お', None], ['仕置', 'しお', None, None], [None, None, 'きよ。', None]]
[['私', 'わたし', None, None], [None, None, 'に', True], ['代', 'か', None, True], [None, None, 'わって', True], ['説明', 'せつめい', None, None], [None, None, 'をしてくれてありがとう。', None]]
[['私', 'わたし', None, None], [None, None, 'に', True], ['代', 'か', None, True], [None, None, 'わって', True], [None, None, '、あなたが', None], ['発表', 'はっぴょう', None, None], [None, None, 'をすることになった。', None]]
[['機長', 'きちょう', None, None], [None, None, 'に', True], ['代', 'か', None, True], [None, None, 'わって', True], ['副操縦士', 'ふくそうじゅうし', None, None], [None, None, 'が', None], ['操縦', 'そうじゅう', None, None], [None, None, 'した。', None]]
[['社長', 'しゃちょう', None, None], [None, None, 'に', True], ['代', 'か', None, True], [None, None, 'わって', True], [None, None, '、', None], ['山田', 'やまだ', None, None], [None, None, 'さんが', None], ['乾杯', 'かんぱい', None, None], [None, None, 'の', None], ['挨拶', 'あいさつ', None, None], [None, None, 'をします。', None]]

 56%|█████▌    | 521/938 [05:18<04:37,  1.50it/s]

[[None, None, 'そのケーキは', None], ['甘', 'あま', None, None], [None, None, 'い', None], [None, None, 'どころか', True], [None, None, '、', None], ['酸', 'す', None, None], [None, None, 'っぱかった。', None]]
[['吹雪', 'ふぶき', None, None], [None, None, 'はやむ', None], [None, None, 'どころか', True], [None, None, '、かえってひどくなっている。', None]]
[['謙虚', 'けんきょ', None, None], [None, None, 'になる', None], [None, None, 'どころか', True], [None, None, 'かえって', None], ['傲慢', 'ごうまん', None, None], [None, None, 'になっている。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['休', 'やす', None, None], [None, None, 'む', None], [None, None, 'どころか', True], [None, None, '、', None], ['全力', 'ぜんりょく', None, None], [None, None, 'を', None], ['出', 'だ', None, None], [None, None, 'し', None], ['切', 'き', None, None], [None, None, 'った。', None]]
[['親切', 'しんせつ', None, None], [None, None, 'にしようとしたけど、', None], ['感謝', 'かんしゃ', None, None], [None, None, 'される', None], [None, None, 'どころか', True], [None, None, '、', None], ['叱', 'しか', None, None], [None, None, 'られた。', None]]

 56%|█████▌    | 522/938 [05:19<04:53,  1.42it/s]

[[None, None, 'ストアのルールを', None], ['破', 'やぶ', None, None], [None, None, 'った', None], [None, None, 'という', True], ['理由', 'りゆう', None, True], [None, None, 'で', True], ['五', 'いつ', None, None], [None, None, 'つのアプリが', None], ['削除', 'さくじょ', None, None], [None, None, 'されました。', None]]
[['仕事', 'しごと', None, None], [None, None, 'がとても', None], ['大変', 'たいへん', None, None], [None, None, 'だった。', None], [None, None, 'そういう', True], ['理由', 'りゆう', None, True], [None, None, 'で', True], [None, None, '、', None], ['今日', 'きょう', None, None], [None, None, 'はゆっくりしたい。', None]]
[[None, None, 'ゴルゴさんはプロフェッショナルです。', None], [None, None, 'そういう', True], ['理由', 'りゆう', None, True], [None, None, 'で', True], ['彼', 'かれ', None, None], [None, None, 'を', None], ['雇', 'やと', None, None], [None, None, 'う', None], ['予定', 'よてい', None, None], [None, None, 'です。', None]]
[[None, None, '「', None], ['高', 'たか', None, None], [None, None, 'すぎるなぁ」', None], [None, None, 'という', True], ['理由', 'りゆう', None, True], [None, None, 'で', True], ['課長', 'かちょう', None, None], [None, None, 'は', None], ['提案', 'ていあん', None, None], [None, None, 'に', None], ['反対', 'はんたい', None, None], [None, None, 'した。', None]]
[[None, None, 'やまださんは', None], ['年寄', 'としよ', None, None], [None, None, 'りだ', None], [None, None, 'という', True], ['理由', 'りゆう', None, True], [None, None, 'で', True], [None, None, '、', None], ['詐欺師', 'さぎし', None, None], [None, None, 'によってターゲットによくされている。', None]]

 56%|█████▌    | 523/938 [05:20<04:49,  1.43it/s]

[['納期限', 'のうきげん', None, None], [None, None, 'は', None], ['４', 'し', None, None], ['月', 'がつ', None, None], ['３０', 'さんじゅう', None, None], ['日', 'にち', None, None], [None, None, 'まで', None], [None, None, 'となっています', True], [None, None, '。', None]]
[[None, None, 'アメリカをはじめとして、', None], ['電気', 'でんき', None, None], [None, None, 'は', None], ['主要', 'しゅよう', None, None], [None, None, 'な', None], ['光源', 'こうげん', None, None], [None, None, 'となっている', True], [None, None, '。', None]]
[['中国', 'ちゅうごく', None, None], [None, None, 'では', None], ['男性', 'だんせい', None, None], [None, None, 'の', None], ['女性', 'じょせい', None, None], [None, None, 'に', None], ['対', 'たい', None, None], [None, None, 'する', None], ['割合', 'わりあい', None, None], [None, None, 'は', None], ['１１８', 'ひゃくじゅうはち', None, None], ['対', 'たい', None, None], ['１００', 'ひゃく', None, None], [None, None, 'となっている', True], [None, None, '。', None]]
[[None, None, 'フランツ・フェルディナント', None], ['大公', 'たいこう', None, None], [None, None, 'の', None], ['暗殺', 'あんさつ', None, None], [None, None, 'が', None], ['開戦', 'かいせん', None, None], [None, None, 'の', None], ['原因', 'げんいん', None, None], [None, None, 'の', None], ['一', 'ひと', None, None], [None, None, 'つ', None], [None, None, 'となっている', True], [None, None, '。', None]]
[[None, None, 'それ', None], [None, None, 'が', None], ['標準', 'ひょうじゅん', None, None], [None, None, 'となっていて', True], ['他', 'ほか', None, None], [None, None, 'の', None], ['方法', 'ほうほう', None, None], [None, None, 'はほとんど', None], ['使用', 'しよう', None, None], [None, None, 'されない。', None]]

 56%|█████▌    | 524/938 [05:21<04:49,  1.43it/s]

[['流行', 'りゅうこう', None, None], [None, None, 'についてのサイト、', None], ['記事', 'きじ', None, None], [None, None, 'のタイトル', None], [None, None, '：「', None], ['靴磨', 'くつみが', None, None], [None, None, 'きが', None], ['靴', 'くつ', None, None], [None, None, 'の', None], ['寿命', 'じゅみょう', None, None], [None, None, 'と', None], ['美', 'うつく', None, None], [None, None, 'しさを', None], ['左右', 'さゆう', None, True], [None, None, 'する', True], [None, None, '」', None]]
[['歴史書', 'れきししょ', None, None], [None, None, '：「', None], ['古代', 'こだい', None, None], [None, None, 'ギリシャ', None], ['人', 'じん', None, None], [None, None, 'は', None], ['自分', 'じぶん', None, None], [None, None, 'たちの', None], ['生活', 'せいかつ', None, None], [None, None, 'が', None], ['神々', 'かみがみ', None, None], [None, None, 'に', None], ['左右', 'さゆう', None, True], [None, None, 'される', True], [None, None, 'と', None], ['信', 'しん', None, None], [None, None, 'じていた。」', None]]
[[None, None, 'ビジネス', None], ['記事', 'きじ', None, None], [None, None, '：「', None], ['新', 'あたら', None, None], [None, None, 'しい', None], ['法律', 'ほうりつ', None, None], [None, None, 'が', None], ['電気', 'でんき', None, None], ['自動車', 'じどうしゃ', None, None], [None, None, 'の', None], ['需要', 'じゅよう', None, None], [None, None, 'を', None], ['左右', 'さゆう', None, True], [None, None, 'する', True], [None, None, 'かもしれない。」', None]]
[['教科書', 'きょうかしょ', None, None], [None, None, '：「', None], ['裁判官', 'さいばんかん', None, None], [None, None, 'は', None], ['賄賂', 'わいろ', None, None], [None, None, 'などによって', None], ['左右', 'さゆう', None, True], [None, None, 'されない', True], [None, None, 'よう、', None], ['良', 'い', None, None], [None, None, 'い', None], ['給与', 'きゅうよ', None, None], [None, None, 'が', None], ['保証', 'ほしょう', None, None], [None, None, 'されている。」', None]]
[['記事', 'きじ', None, None], [None, None, '：「', None], ['平均余命', 'へいきんよめい', None, None], [None, None, 'を', None], ['大', 'おお', None, None], [None, None, 'きく', None], ['左右', 'さゆう', None, True], [None, None, 'する', True], [None, None, 'のは', None], ['食生活', 'しょくせいかつ', None, None], [None, None, 'や', None], ['睡眠時間', 'すいみんじかん', None, None], [None, None, 'だと', None], ['考', 'かんが', None, None], [None, None, 'えられている。」', None]]

 56%|█████▌    | 525/938 [05:21<04:54,  1.40it/s]

[[None, None, 'それは', None], [None, None, 'あり', True], ['得', 'え', None, True], [None, None, 'る', True], [None, None, '。', None]]
[[None, None, 'その', None], ['対策', 'たいさく', None, None], [None, None, 'は', None], ['考', 'かんが', None, True], [None, None, 'え', True], ['得', 'う', None, True], [None, None, 'る', True], [None, None, '。', None]]
[['災害', 'さいがい', None, None], [None, None, 'はいつだって', None], ['起', 'お', None, True], [None, None, 'こり', True], ['得', 'え', None, True], [None, None, 'る', True], [None, None, '。', None]]
[['対応', 'たいおう', None, None], ['次第', 'しだい', None, None], [None, None, 'でストライキは', None], ['回避', 'かいひ', None, True], [None, None, 'し', True], ['得', 'え', None, True], [None, None, 'る', True], [None, None, '。', None]]
[['耕', 'たがや', None, True], [None, None, 'し', True], ['得', 'う', None, True], [None, None, 'る', True], ['土地', 'とち', None, None], [None, None, 'を', None], ['持', 'も', None, None], [None, None, 'っている', None], ['方', 'かた', None, None], [None, None, 'は', None], ['田植', 'たう', None, None], [None, None, 'えができます。', None]]

 56%|█████▌    | 526/938 [05:22<04:52,  1.41it/s]

[[None, None, 'そこまで', None], ['大', 'おお', None, None], [None, None, 'きな', None], ['地震', 'じしん', None, None], [None, None, 'は', None], ['起', 'お', None, True], [None, None, 'こり', True], ['得', 'え', None, True], [None, None, 'ない', True], [None, None, '。', None]]
[['本来', 'ほんらい', None, None], [None, None, '、', None], ['水', 'みず', None, None], [None, None, 'と', None], ['油', 'あぶら', None, None], [None, None, 'は', None], ['混', 'ま', None, True], [None, None, 'ざり', True], ['得', 'え', None, True], [None, None, 'ない', True], [None, None, '。', None]]
[[None, None, 'そんなことはほとんど', None], ['起', 'お', None, True], [None, None, 'こり', True], ['得', 'え', None, True], [None, None, 'ない', True], [None, None, 'と', None], ['思', 'おも', None, None], [None, None, 'います。', None]]
[['私', 'わたし', None, None], [None, None, 'がその', None], ['夢', 'ゆめ', None, None], [None, None, 'を', None], ['叶', 'かな', None, None], [None, None, 'えることは', None], [None, None, 'あり', True], ['得', 'え', None, True], [None, None, 'ない', True], [None, None, '。', None]]
[['君', 'きみ', None, None], [None, None, 'の', None], ['話術', 'わじゅつ', None, None], [None, None, 'を', None], ['持', 'も', None, None], [None, None, 'ってしても、', None], ['説得', 'せっとく', None, None], [None, None, 'し', True], ['得', 'え', None, True], [None, None, 'ない', True], [None, None, 'だろう。', None]]

 56%|█████▌    | 527/938 [05:23<04:31,  1.51it/s]

[[None, None, 'サプライズのプレゼントに、', None], ['驚', 'おどろ', None, True], [None, None, 'かざるを', True], ['得', 'え', None, True], [None, None, 'なかった', True], [None, None, '。', None]]
[['思', 'おも', None, None], [None, None, 'い', None], ['掛', 'が', None, None], [None, None, 'けない', None], ['出会', 'であ', None, None], [None, None, 'いに、', None], ['感動', 'かんどう', None, None], [None, None, 'せざるを', True], ['得', 'え', None, True], [None, None, 'なかった', True], [None, None, '。', None]]
[['田中', 'たなか', None, None], [None, None, 'さんはとても', None], ['忙', 'いそが', None, None], [None, None, 'しかったのでゴルフの', None], ['誘', 'さそ', None, None], [None, None, 'いを', None], ['断', 'ことわ', None, True], [None, None, 'らざるを', True], ['得', 'え', None, True], [None, None, 'なかった', True], [None, None, '。', None]]
[['古', 'ふる', None, None], [None, None, 'い', None], ['家屋', 'かおく', None, None], [None, None, 'は', None], ['倒壊', 'とうかい', None, None], [None, None, 'する', None], ['恐', 'おそ', None, None], [None, None, 'れがあるから、', None], ['壊', 'こわ', None, True], [None, None, 'さざるを', True], ['得', 'え', None, True], [None, None, 'ません', True], [None, None, '。', None]]
[['今', 'いま', None, None], [None, None, 'まで', None], ['使', 'つか', None, None], [None, None, 'った', None], ['顕微鏡', 'けんびきょう', None, None], [None, None, 'が', None], ['壊', 'こわ', None, None], [None, None, 'れたから、', None], ['新', 'あたら', None, None], [None, None, 'しいのを', None], ['買', 'か', None, True], [None, None, 'わざるを', True], ['得', 'え', None, True], [None, None, 'ない', True], [None, None, '。', None]]

 56%|█████▋    | 528/938 [05:23<05:01,  1.36it/s]

[[None, None, 'たゆま', None], [None, None, 'ざる', True], ['努力', 'どりょく', None, None], [None, None, 'のおかげで', None], ['成功者', 'せいこうしゃ', None, None], [None, None, 'になった。', None]]
[[None, None, 'たゆま', None], [None, None, 'ざる', True], ['努力', 'どりょく', None, None], [None, None, 'をすることが、', None], ['成功', 'せいこう', None, None], [None, None, 'への', None], ['鍵', 'かぎ', None, None], [None, None, 'だ。', None]]
[[None, None, 'あの', None], ['作家', 'さっか', None, None], [None, None, 'の', None], ['知', 'し', None, None], [None, None, 'られ', None], [None, None, 'ざる', True], ['名画', 'めいが', None, None], [None, None, 'を', None], ['僕', 'ぼく', None, None], [None, None, 'は', None], ['知', 'し', None, None], [None, None, 'っています。', None]]
[['消', 'き', None, None], [None, None, 'え', None], [None, None, 'ざる', True], ['傷', 'きず', None, None], [None, None, 'を', None], ['負', 'お', None, None], [None, None, 'ってしまい、', None], ['落', 'お', None, None], [None, None, 'ち', None], ['込', 'こ', None, None], [None, None, 'んでいる。', None]]
[['嘘', 'うそ', None, None], [None, None, 'をつか', None], [None, None, 'ざる', True], ['人', 'ひと', None, None], [None, None, 'しか', None], ['信頼', 'しんらい', None, None], [None, None, 'することができない。', None]]

 56%|█████▋    | 529/938 [05:25<05:47,  1.18it/s]

[[None, None, 'ご', None], ['馳走', 'ちそう', None, None], [None, None, 'する', None], [None, None, 'つもりで', True], ['行', 'い', None, None], [None, None, 'ったのに、おごってもらうことになった。', None]]
[['本', 'ほん', None, None], [None, None, 'にする', None], [None, None, 'つもりで', True], ['執筆', 'しっぴつ', None, None], [None, None, 'していたが、これはボツだな。', None]]
[[None, None, 'お', None], ['土産', 'みやげ', None, None], [None, None, 'のつもりで', True], ['買', 'か', None, None], [None, None, 'ったが、', None], ['食', 'た', None, None], [None, None, 'べてしまった。', None]]
[['車掌', 'しゃしょう', None, None], [None, None, 'になっ', None], [None, None, 'た', None], [None, None, 'つもりで', True], [None, None, '、', None], ['毎日', 'まいにち', None, None], ['電車', 'でんしゃ', None, None], [None, None, 'に', None], ['乗', 'の', None, None], [None, None, 'っている。', None]]
[['日本', 'にほん', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'っ', None], [None, None, 'た', None], [None, None, 'つもりで', True], [None, None, '、', None], ['日本語', 'にほんご', None, None], [None, None, 'を', None], ['勉強', 'べんきょう', None, None], [None, None, 'しています。', None]]

 57%|█████▋    | 530/938 [05:25<05:34,  1.22it/s]

[[None, None, 'どうせ', True], [None, None, 'ダイアモンドなんて', None], ['買', 'か', None, None], [None, None, 'ってもらえない。', None]]
[[None, None, 'どうせ', True], [None, None, '「ウドの', None], ['大木', 'たいぼく', None, None], [None, None, 'だ」と', None], ['悪口', 'わるぐち', None, None], [None, None, 'を', None], ['言', 'い', None, None], [None, None, 'われるのがオチだ。', None]]
[[None, None, 'どうせ', True], ['通訳', 'つうやく', None, None], [None, None, 'はつけてもらえない。', None], ['自力', 'じりき', None, None], [None, None, 'で', None], ['頑張', 'がんば', None, None], [None, None, 'るしかない。', None]]
[['私', 'わたし', None, None], [None, None, 'がどう', None], ['謝', 'あやま', None, None], [None, None, 'っても、', None], [None, None, 'どうせ', True], ['彼', 'かれ', None, None], [None, None, 'は', None], ['許', 'ゆる', None, None], [None, None, 'すつもりはないだろう。', None]]
[[None, None, 'どうせ', True], [None, None, 'ご', None], ['飯', 'はん', None, None], [None, None, 'を', None], ['炊', 'た', None, None], [None, None, 'かないといけないのだから、あなたの', None], ['分', 'ぶん', None, None], [None, None, 'も', None], ['炊', 'た', None, None], [None, None, 'きますよ。', None]]

 57%|█████▋    | 531/938 [05:26<05:25,  1.25it/s]

[[None, None, 'せめて', True], [None, None, 'ドアくらい', None], ['閉', 'し', None, None], [None, None, 'めて', None], ['欲', 'ほ', None, None], [None, None, 'しかった...。', None]]
[['親', 'おや', None, None], [None, None, '：「', None], [None, None, 'せめて', True], [None, None, 'おかずだけでも', None], ['食', 'た', None, None], [None, None, 'べて。」', None]]
[[None, None, 'せめて', True], ['着替', 'きが', None, None], [None, None, 'えさせてもらえませんか？びしょ', None], ['濡', 'ぬ', None, None], [None, None, 'れなんです。', None]]
[[None, None, 'いい', None], ['案', 'あん', None, None], [None, None, 'ではなくてもいいので、', None], [None, None, 'せめて', True], [None, None, 'アイデアだけでも', None], ['出', 'だ', None, None], [None, None, 'してください。', None]]
[['楽器', 'がっき', None, None], [None, None, 'を', None], ['寄贈', 'きぞう', None, None], [None, None, 'させてください。', None], [None, None, 'せめて', True], [None, None, 'もの', None], ['恩返', 'おんがえ', None, None], [None, None, 'しです。', None]]

 57%|█████▋    | 532/938 [05:27<05:13,  1.29it/s]

[[None, None, 'あの', None], ['二人', 'ふたり', None, None], [None, None, '、', None], [None, None, 'どうやら', True], ['結婚', 'けっこん', None, None], [None, None, 'してる', None], ['感', 'かん', None, None], [None, None, 'じだよ。', None]]
[[None, None, 'あの', None], ['動画', 'どうが', None, None], [None, None, '、', None], [None, None, 'どうやら', True], ['削除', 'さくじょ', None, None], [None, None, 'されたみたいだ。', None]]
[[None, None, 'どうやら', True], ['今年', 'ことし', None, None], [None, None, 'の', None], ['紅葉', 'こうよう', None, None], [None, None, 'は', None], ['遅', 'おく', None, None], [None, None, 'れているらしい。', None]]
[[None, None, 'どうやら', True], [None, None, '「', None], ['心当', 'こころあ', None, None], [None, None, 'たりがない」というのは', None], ['本当', 'ほんとう', None, None], [None, None, 'らしい。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], [None, None, 'どうやら', True], [None, None, 'お', None], ['小遣', 'こづか', None, None], [None, None, 'いをもらったことがないようです。', None]]

 57%|█████▋    | 533/938 [05:28<05:08,  1.31it/s]

[['何', 'なに', None, True], [None, None, 'やら', True], [None, None, 'いいにおいがします。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, '、', None], ['何', 'なに', None, True], [None, None, 'やら', True], ['困', 'こま', None, None], [None, None, 'っているようです。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'のまなざしには、', None], ['何', 'なに', None, True], [None, None, 'やら', True], ['言葉', 'ことば', None, None], [None, None, 'にならない', None], ['想', 'おも', None, None], [None, None, 'いが', None], ['隠', 'かく', None, None], [None, None, 'されていた。', None]]
[['何', 'なに', None, True], [None, None, 'やら', True], ['母', 'はは', None, None], [None, None, 'は、', None], ['宝', 'たから', None, None], [None, None, 'くじの', None], ['一等', 'いっとう', None, None], [None, None, 'を', None], ['当', 'あ', None, None], [None, None, 'てたことを、', None], ['家族', 'かぞく', None, None], ['全員', 'ぜんいん', None, None], [None, None, 'に', None], ['黙', 'だま', None, None], [None, None, 'っていたらしい。', None]]
[['何', 'なに', None, True], [None, None, 'やら', True], ['社長', 'しゃちょう', None, None], [None, None, 'に', None], ['隠', 'かく', None, None], [None, None, 'し', None], ['子', 'ご', None, None], [None, None, 'がいたらしく、その', None], ['噂', 'うわさ', None, None], [None, None, 'がオフィスの', None], ['他社', 'たしゃ', None, None], [None, None, 'にも', None], ['広', 'ひろ', None, None], [None, None, 'まっているよ。', None]]

 57%|█████▋    | 534/938 [05:28<05:05,  1.32it/s]

[[None, None, 'このコースレイアウトだと、', None], ['刻', 'きざ', None, None], [None, None, 'む', None], [None, None, 'よりほかない', True], [None, None, '。', None]]
[['給与', 'きゅうよ', None, None], [None, None, 'が', None], ['悪', 'わる', None, None], [None, None, 'すぎる。', None], ['仕事', 'しごと', None, None], [None, None, 'を', None], ['代', 'か', None, None], [None, None, 'える', None], [None, None, 'よりほかない', True], [None, None, '。', None]]
[['教養', 'きょうよう', None, None], [None, None, 'がなさすぎる。', None], ['勉強', 'べんきょう', None, None], [None, None, 'する', None], [None, None, 'よりほかありません', True], [None, None, '。', None]]
[['車', 'くるま', None, None], [None, None, 'を', None], ['出', 'だ', None, None], [None, None, 'せなかったので、', None], ['自転車', 'じてんしゃ', None, None], [None, None, 'で', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'よりほかはなかった', True], [None, None, '。', None]]
[['材料', 'ざいりょう', None, None], [None, None, 'が', None], ['入手', 'にゅうしゅ', None, None], [None, None, 'できない。', None], ['休業', 'きゅうぎょう', None, None], [None, None, 'する', None], [None, None, 'よりほかない', True], [None, None, '。', None]]

 57%|█████▋    | 535/938 [05:29<05:01,  1.34it/s]

[['確', 'たし', None, True], [None, None, 'かに', True], ['彼', 'かれ', None, None], [None, None, 'は', None], ['信頼', 'しんらい', None, None], [None, None, 'できます。', None]]
[['確', 'たし', None, True], [None, None, 'かに', True], [None, None, 'その', None], ['服', 'ふく', None, None], [None, None, 'はあなたに', None], ['似合', 'にあ', None, None], [None, None, 'う。', None]]
[[None, None, 'みんな', None], ['焦', 'あせ', None, None], [None, None, 'っているようだ。', None], ['確', 'たし', None, True], [None, None, 'かに', True], ['期限', 'きげん', None, None], [None, None, 'が', None], ['迫', 'せま', None, None], [None, None, 'っている。', None]]
[['学校', 'がっこう', None, None], [None, None, 'の', None], ['規則', 'きそく', None, None], ['上', 'じょう', None, None], [None, None, '、', None], ['確', 'たし', None, True], [None, None, 'かに', True], ['生徒', 'せいと', None, None], [None, None, 'は', None], ['先生', 'せんせい', None, None], [None, None, 'に', None], ['従', 'したが', None, None], [None, None, 'うべきだ。', None]]
[['彼', 'かれ', None, None], [None, None, 'のうちは', None], ['音楽', 'おんがく', None, None], ['一家', 'いっか', None, None], [None, None, 'らしいが、', None], ['確', 'たし', None, True], [None, None, 'かに', True], ['楽器', 'がっき', None, None], [None, None, 'がうまい。', None]]

 57%|█████▋    | 536/938 [05:30<05:06,  1.31it/s]

[[None, None, '「', None], ['一応', 'いちおう', None, True], ['夜道', 'よみち', None, None], [None, None, 'だから、', None], ['気', 'き', None, None], [None, None, 'をつけてね。それじゃまた', None], ['明日', 'あした', None, None], [None, None, '。」', None]]
[[None, None, 'ルームメイトの', None], ['間', 'あいだ', None, None], [None, None, 'での', None], ['話', 'はなし', None, None], [None, None, '：「', None], ['Ｆａｃｅｂｏｏｋ', 'フェイスブック', None, None], [None, None, 'アカウントは', None], ['一応', 'いちおう', None, True], ['持', 'も', None, None], [None, None, 'ってるけど、あまり', None], ['使', 'つか', None, None], [None, None, 'ってない。」', None]]
[['教師', 'きょうし', None, None], [None, None, 'が', None], ['生徒', 'せいと', None, None], [None, None, 'に', None], [None, None, '：「ハサミが', None], ['必要', 'ひつよう', None, None], [None, None, 'になるかは', None], ['分', 'わ', None, None], [None, None, 'かりませんが、', None], ['一応', 'いちおう', None, True], ['持', 'も', None, None], [None, None, 'ってきてください。」', None]]
[['友達', 'ともだち', None, None], [None, None, 'は', None], ['助言', 'じょげん', None, None], [None, None, 'する', None], [None, None, '：「', None], ['引越', 'ひっこ', None, None], [None, None, 'ししたら、', None], ['一応', 'いちおう', None, True], [None, None, '、', None], ['隣近所', 'となりきんじょ', None, None], [None, None, 'に', None], ['挨拶', 'あいさつ', None, None], [None, None, 'しないとね。」', None]]
[['友達', 'ともだち', None, None], [None, None, 'の', None], ['間', 'あいだ', None, None], [None, None, 'での', None], ['話', 'はなし', None, None], [None, None, '：「このスマホは', None], ['充電', 'じゅうでん', None, None], [None, None, 'してあるけど、', None], ['一応', 'いちおう', None, True], [None, None, 'モバイルバッテリーも', None], ['持', 'も', None, None], [None, None, 'ってきた。」', None]]

 57%|█████▋    | 537/938 [05:31<05:03,  1.32it/s]

[[None, None, '「もうコンピュータを', None], ['直', 'なお', None, None], [None, None, 'したの？」', None], [None, None, '「', None], ['一応', 'いちおう', None, True], [None, None, 'ね。', None], ['時間', 'じかん', None, None], [None, None, 'がかかったけど。」', None]]
[['医者', 'いしゃ', None, None], [None, None, '、', None], ['患者', 'かんじゃ', None, None], [None, None, 'について', None], [None, None, '：「ふう…', None], ['一応', 'いちおう', None, True], [None, None, '、', None], ['容態', 'ようだい', None, None], [None, None, 'は', None], ['安定化', 'あんていか', None, None], [None, None, 'できました。」', None]]
[['若', 'わか', None, None], [None, None, 'く', None], ['見', 'み', None, None], [None, None, 'えるメリオダズさん', None], [None, None, '：「これでも', None], ['一応', 'いちおう', None, True], [None, None, '、', None], ['僕', 'ぼく', None, None], [None, None, 'は', None], ['大人', 'おとな', None, None], [None, None, 'なんです。」', None]]
[['部長', 'ぶちょう', None, None], [None, None, '：「', None], ['残念', 'ざんねん', None, None], [None, None, 'ながらもう', None], ['時間', 'じかん', None, None], [None, None, 'がありませんので、これで', None], ['一応', 'いちおう', None, True], ['会議', 'かいぎ', None, None], [None, None, 'は', None], ['終', 'お', None, None], [None, None, 'わりです。」', None]]
[['転', 'ころ', None, None], [None, None, 'んだ', None], ['友達', 'ともだち', None, None], ['１', 'いち', None, None], [None, None, 'に', None], ['話', 'はな', None, None], [None, None, 'しかける', None], ['友達', 'ともだち', None, None], ['２', 'に', None, None], [None, None, '：「', None], ['大丈夫', 'だいじょうぶ', None, None], [None, None, '？」', None], ['友達', 'ともだち', None, None], ['１', 'いち', None, None], [None, None, '：「', None], ['一応', 'いちおう', None, True], [None, None, '。」', None]]

 57%|█████▋    | 538/938 [05:31<05:02,  1.32it/s]

[[None, None, 'この', None], ['下駄', 'げた', None, None], [None, None, 'は', None], ['彼', 'かれ', None, None], [None, None, 'の', None], ['物', 'もの', None, None], [None, None, 'に', True], ['相違', 'そうい', None, True], [None, None, 'ない', True], [None, None, '。', None]]
[[None, None, 'これは', None], ['県庁', 'けんちょう', None, None], [None, None, 'からの', None], ['指示', 'しじ', None, None], [None, None, 'ということ', None], [None, None, 'に', True], ['相違', 'そうい', None, True], [None, None, 'ない', True], [None, None, 'か？', None]]
[[None, None, 'これは', None], ['我', 'わ', None, None], [None, None, 'が', None], ['社', 'しゃ', None, None], [None, None, 'の', None], ['公式', 'こうしき', None, None], [None, None, 'の', None], ['見解', 'けんかい', None, None], [None, None, 'ということ', None], [None, None, 'に', True], ['相違', 'そうい', None, True], [None, None, 'ない', True], [None, None, '。', None]]
[[None, None, 'わたしの', None], ['意見', 'いけん', None, None], [None, None, 'は', None], ['妻', 'つま', None, None], [None, None, 'の', None], ['意見', 'いけん', None, None], [None, None, 'ということ', None], [None, None, 'に', True], ['相違', 'そうい', None, True], [None, None, 'ない', True], [None, None, '。', None]]
[[None, None, 'これはゴッホの', None], ['絵', 'え', None, None], [None, None, 'のコレクション', None], [None, None, 'に', True], ['相違', 'そうい', None, True], [None, None, 'ない', True], [None, None, '。', None]]

 57%|█████▋    | 539/938 [05:32<04:54,  1.36it/s]

[['万', 'まん', None, True], [None, None, 'が', True], ['一', 'いち', None, True], [None, None, 'のために、', None], ['消火器', 'しょうかき', None, None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'うことにした。', None]]
[['万', 'まん', None, True], [None, None, 'が', True], ['一', 'いち', None, True], ['思', 'おも', None, None], [None, None, 'いついたら、アイデアを', None], ['教', 'おし', None, None], [None, None, 'えてください。', None]]
[['万', 'まん', None, True], [None, None, 'が', True], ['一', 'いち', None, True], ['嫌', 'いや', None, None], [None, None, 'がられても、', None], ['次', 'つぎ', None, None], [None, None, 'の', None], ['手', 'て', None, None], [None, None, 'は', None], ['打', 'う', None, None], [None, None, 'ってある。', None]]
[['万', 'まん', None, True], [None, None, 'が', True], ['一', 'いち', None, True], ['裁判', 'さいばん', None, None], [None, None, 'で', None], ['争', 'あらそ', None, None], [None, None, 'うことになっても、', None], ['受', 'う', None, None], [None, None, 'けて', None], ['立', 'た', None, None], [None, None, 'ちますよ。', None]]
[['万', 'まん', None, True], [None, None, 'が', True], ['一', 'いち', None, True], ['入', 'い', None, None], [None, None, 'れ', None], ['物', 'もの', None, None], [None, None, 'がないと', None], ['困', 'こま', None, None], [None, None, 'るから、', None], ['袋', 'ふくろ', None, None], [None, None, 'を', None], ['持', 'も', None, None], [None, None, 'って', None], ['行', 'い', None, None], [None, None, 'こう。', None]]

 58%|█████▊    | 540/938 [05:33<04:47,  1.38it/s]

[['何', 'なん', None, None], [None, None, 'とも', None], ['言', 'い', None, True], [None, None, 'いようがない', True], ['味', 'あじ', None, None], [None, None, 'だ。', None]]
[['弁解', 'べんかい', None, None], [None, None, 'のしようがない', True], [None, None, '。', None]]
[[None, None, 'これはどうにも', None], [None, None, 'しようがない', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['速', 'はや', None, None], [None, None, 'すぎて', None], ['追', 'お', None, True], [None, None, 'い', True], ['越', 'こ', None, True], [None, None, 'しようがない', True], [None, None, '。', None]]
[[None, None, 'そんなバレバレのサプライズ、', None], ['驚', 'おどろ', None, True], [None, None, 'きようがない', True], [None, None, '。', None]]

 58%|█████▊    | 541/938 [05:33<04:50,  1.37it/s]

[['第', 'だい', None, None], ['一', 'いち', None, None], [None, None, 'にすべきは', None], ['人命', 'じんめい', None, None], [None, None, 'にほかなりません', True], [None, None, '。', None]]
[['三', 'さん', None, None], ['位', 'い', None, None], [None, None, 'という', None], ['結果', 'けっか', None, None], [None, None, 'は', None], ['彼', 'かれ', None, None], [None, None, 'の', None], ['実力', 'じつりょく', None, None], [None, None, 'にほかならない', True], [None, None, '。', None]]
[['結局', 'けっきょく', None, None], [None, None, '「', None], ['笑', 'わら', None, None], [None, None, 'い」というのは', None], ['好', 'す', None, None], [None, None, 'き', None], ['嫌', 'きら', None, None], [None, None, 'い', None], [None, None, 'にほかならない', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'があの', None], ['番組', 'ばんぐみ', None, None], [None, None, 'に', None], ['出', 'で', None, None], [None, None, 'たのは、', None], ['宣伝', 'せんでん', None, None], [None, None, 'にほかならない', True], [None, None, '。', None]]
[['通常', 'つうじょう', None, None], [None, None, 'の', None], ['事故', 'じこ', None, None], [None, None, 'の', None], ['原因', 'げんいん', None, None], [None, None, 'はスピード', None], ['違反', 'いはん', None, None], [None, None, 'にほかならない', True], [None, None, '。', None]]

 58%|█████▊    | 542/938 [05:34<04:45,  1.39it/s]

[[None, None, '「', None], ['今', 'いま', None, None], ['持', 'も', None, None], [None, None, 'っているスキルでリングは', None], ['何', 'なに', None, None], [None, None, 'も', None], ['滅', 'ほろ', None, True], [None, None, 'ぼせっこありません', True], [None, None, '。」', None]]
[['練習', 'れんしゅう', None, None], [None, None, 'をたくさんしなくては、', None], ['楽器', 'がっき', None, None], [None, None, 'の', None], ['演奏', 'えんそう', None, None], [None, None, 'なんか', None], [None, None, 'できっこない', True], [None, None, '。', None]]
[['日本語', 'にほんご', None, None], [None, None, 'で', None], ['書', 'か', None, None], [None, None, 'く', None], ['練習', 'れんしゅう', None, None], [None, None, 'をしないと、', None], ['日本語', 'にほんご', None, None], [None, None, 'で', None], ['書', 'か', None, None], [None, None, 'けるようには', None], [None, None, 'なりっこない', True], [None, None, '。', None]]
[['怒', 'おこ', None, None], [None, None, 'ったお', None], ['母', 'かあ', None, None], [None, None, 'さん', None], [None, None, '：「ひきこもりのように、', None], ['一日', 'いちにち', None, None], ['中', 'じゅう', None, None], ['家', 'いえ', None, None], [None, None, 'でゲームしてばかりでは、', None], ['何', 'なに', None, None], [None, None, 'も', None], ['成', 'な', None, True], [None, None, 'し', True], ['遂', 'と', None, True], [None, None, 'げっこない', True], [None, None, '。」', None]]
[[None, None, 'どんなに', None], ['勉強', 'べんきょう', None, None], [None, None, 'したって「は」と「が」の', None], ['違', 'ちが', None, None], [None, None, 'いなんて', None], ['分', 'わ', None, True], [None, None, 'かりっこない', True], [None, None, '。', None]]

 58%|█████▊    | 543/938 [05:35<05:05,  1.29it/s]

[['遠藤', 'えんどう', None, None], [None, None, 'さん', None], [None, None, '：「アプリをもっと', None], ['使', 'つか', None, None], [None, None, 'いやすくしました。」', None], ['土井', 'どい', None, None], [None, None, 'さん', None], [None, None, '：「', None], [None, None, 'それなら', True], ['普及', 'ふきゅう', None, None], [None, None, 'すると', None], ['思', 'おも', None, None], [None, None, 'います。」', None]]
[['岩村', 'いわむら', None, None], [None, None, 'さん', None], [None, None, '：「もう', None], ['誰', 'だれ', None, None], [None, None, 'も', None], ['食', 'た', None, None], [None, None, 'べないんだね。」', None], ['山崎', 'やまさき', None, None], [None, None, 'さん', None], [None, None, '：「', None], [None, None, 'それなら', True], ['蓋', 'ふた', None, None], [None, None, 'をした', None], ['方', 'ほう', None, None], [None, None, 'がいい。」', None]]
[['藤本', 'ふじもと', None, None], [None, None, 'さん', None], [None, None, '：「この', None], ['戸', 'と', None, None], [None, None, 'は', None], ['鍵', 'かぎ', None, None], [None, None, 'が', None], ['壊', 'こわ', None, None], [None, None, 'れてかからない。」', None], ['横山', 'よこやま', None, None], [None, None, 'さん', None], [None, None, '：「', None], [None, None, 'それなら', True], [None, None, 'あまりにも', None], ['物騒', 'ぶっそう', None, None], [None, None, 'だ。」', None]]
[['松本', 'まつもと', None, None], [None, None, 'さん', None], [None, None, '：「あそこは', None], ['開', 'あ', None, None], [None, None, 'かずの', None], ['踏切', 'ふみきり', None, None], [None, None, 'だ。」', None], ['山端', 'やまはた', None, None], [None, None, 'さん', None], [None, None, '：「', None], [None, None, 'それなら', True], ['陸橋', 'りっきょう', None, None], [None, None, 'を', None], ['渡', 'わた', None, None], [None, None, 'った', None], ['方', 'ほう', None, None], [None, None, 'がいい。」', None]]
[['森口', 'もりぐち', None, None], [None, None, 'さん', None], [None, None, '：「', None], ['今', 'いま', None, None], ['鍋', 'なべ', None, None], [None, None, 'が', None], ['使', 'つか', None, None], [None, None, 'えない。」', None], ['上田', 'うえだ', None, None], [None, None, 'さん', None], [None, None, '：「', None], [None, None, 'それなら', True], ['代', 'か', None, None], [None, None, 'わりにフライパンを', None], ['使', 'つか', None, None], [None, None, 'えばいい。」', None]]

 58%|█████▊    | 544/938 [05:36<04:53,  1.34it/s]

[['私', 'わたし', None, None], [None, None, 'よりもっと', None], ['上手', 'うま', None, None], [None, None, 'くやれる', None], [None, None, 'ものなら', True], [None, None, 'やってみろ！', None]]
[[None, None, 'もしできる', None], [None, None, 'ものなら', True], [None, None, '、', None], ['二', 'に', None, None], ['年', 'ねん', None, None], ['前', 'まえ', None, None], [None, None, 'にビットコインを', None], ['買', 'か', None, None], [None, None, 'ったんだが。', None]]
[['行', 'い', None, None], [None, None, 'ける', None], [None, None, 'ものなら', True], ['僕', 'ぼく', None, None], [None, None, 'だって', None], ['大学院', 'だいがくいん', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'きたいです。', None]]
[[None, None, 'なれる', None], [None, None, 'ものなら', True], ['体操', 'たいそう', None, None], ['選手', 'せんしゅ', None, None], [None, None, 'になりたい。', None]]
[['直', 'なお', None, None], [None, None, 'せる', None], [None, None, 'ものなら', True], ['短所', 'たんしょ', None, None], [None, None, 'を', None], ['直', 'なお', None, None], [None, None, 'したいが、', None], ['簡単', 'かんたん', None, None], [None, None, 'ではない。', None]]

 58%|█████▊    | 545/938 [05:36<04:51,  1.35it/s]

[[None, None, 'アンテナの', None], ['修理', 'しゅうり', None, None], [None, None, 'を', None], ['息子', 'むすこ', None, None], [None, None, 'に', True], ['任', 'まか', None, True], [None, None, 'せた', True], [None, None, '。', None]]
[['研修生', 'けんしゅうせい', None, None], [None, None, 'に', None], ['掃除', 'そうじ', None, None], [None, None, 'を', True], ['任', 'まか', None, True], [None, None, 'せます', True], [None, None, '。', None]]
[['奇跡', 'きせき', None, None], [None, None, 'が', None], ['起', 'お', None, None], [None, None, 'こるかどうか', None], [None, None, 'を', None], ['神様', 'かみさま', None, None], [None, None, 'に', True], ['任', 'まか', None, True], [None, None, 'せる', True], [None, None, '。', None]]
[['育児', 'いくじ', None, None], [None, None, 'を', None], ['親', 'おや', None, None], [None, None, 'に', True], ['任', 'まか', None, True], [None, None, 'せ', True], [None, None, 'っきりというのはよくない。', None]]
[['井戸', 'いど', None, None], [None, None, 'の', None], ['調査', 'ちょうさ', None, None], [None, None, 'を', None], ['専門家', 'せんもんか', None, None], [None, None, 'に', True], ['任', 'まか', None, True], [None, None, 'せよう', True], [None, None, '。', None]]

 58%|█████▊    | 546/938 [05:37<04:58,  1.31it/s]

[['友達', 'ともだち', None, None], [None, None, 'との', None], ['話', 'はなし', None, None], [None, None, '：「ぼくはこのチャンスを', None], ['活', 'い', None, True], [None, None, 'かしたい', True], [None, None, '。」', None]]
[['新聞記事', 'しんぶんきじ', None, None], [None, None, '：「ルイスさんは', None], ['技師', 'ぎし', None, None], [None, None, 'としての', None], ['経験', 'けいけん', None, None], [None, None, 'を', None], ['活', 'い', None, True], [None, None, 'かして', True], ['修理業', 'しゅうりぎょう', None, None], [None, None, 'を', None], ['始', 'はじ', None, None], [None, None, 'めました。」', None]]
[[None, None, 'ノートパソコンの', None], ['生産者', 'せいさんしゃ', None, None], [None, None, 'のサイト', None], [None, None, '：「アルミニウムの', None], ['美', 'うつく', None, None], [None, None, 'しさを', None], ['最大限', 'さいだいげん', None, None], [None, None, 'に', None], ['活', 'い', None, True], [None, None, 'かした', True], [None, None, 'ノートパソコン」', None]]
[['教師', 'きょうし', None, None], [None, None, '、', None], ['生徒', 'せいと', None, None], [None, None, 'に', None], [None, None, '：「マックス、すばらしい', None], ['写真', 'しゃしん', None, None], [None, None, 'をとる', None], ['才能', 'さいのう', None, None], [None, None, 'があるのだから、それを', None], ['最大限', 'さいだいげん', None, None], [None, None, 'に', None], ['活', 'い', None, True], [None, None, 'かす', True], [None, None, 'べきだよ。」', None]]
[[None, None, 'ジョブ', None], ['広告', 'こうこく', None, None], [None, None, '：「', None], ['資格', 'しかく', None, None], [None, None, 'を', None], ['活', 'い', None, True], [None, None, 'かした', True], ['仕事', 'しごと', None, None], [None, None, 'です。', None], ['一緒', 'いっしょ', None, None], [None, None, 'に', None], ['頑張', 'がんば', None, None], [None, None, 'ってくれる', None], ['仲間', 'なかま', None, None], [None, None, 'を', None], ['募集中', 'ぼしゅうちゅう', None, None], [None, None, '。」', None]]

 58%|█████▊    | 547/938 [05:38<04:49,  1.35it/s]

[[None, None, 'まずは', None], ['計画', 'けいかく', None, None], [None, None, 'の', None], [None, None, 'おおよそ', True], [None, None, 'を', None], ['説明', 'せつめい', None, None], [None, None, 'しよう。', None]]
[['地震', 'じしん', None, None], [None, None, 'による', None], ['犠牲者', 'ぎせいしゃ', None, None], [None, None, 'は', None], [None, None, 'おおよそ', True], ['１２０', 'ひゃくにじゅう', None, None], ['人', 'にん', None, None], [None, None, 'です。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['家', 'いえ', None, None], [None, None, 'から', None], ['実家', 'じっか', None, None], [None, None, 'まで', None], [None, None, 'およそ', True], ['１０', 'じっ', None, None], [None, None, 'キロ', None], ['離', 'はな', None, None], [None, None, 'れている。', None]]
[[None, None, 'およそ', True], [None, None, 'の', None], ['見積', 'みつ', None, None], [None, None, 'もりを', None], ['立', 'た', None, None], [None, None, 'ててから', None], ['詳細', 'しょうさい', None, None], [None, None, 'をつめる。', None]]
[[None, None, 'パーティーにくる', None], [None, None, 'おおよそ', True], [None, None, 'の', None], ['人数', 'にんずう', None, None], [None, None, 'を', None], ['把握', 'はあく', None, None], [None, None, 'する。', None]]

 58%|█████▊    | 548/938 [05:39<04:43,  1.38it/s]

[[None, None, 'あの', None], ['店', 'みせ', None, None], [None, None, 'は', None], ['行列', 'ぎょうれつ', None, None], [None, None, 'がすごすぎる。もう', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'まい', True], [None, None, '。', None]]
[['税金', 'ぜいきん', None, None], [None, None, 'が', None], ['高', 'たか', None, None], [None, None, 'いから、この', None], ['町', 'まち', None, None], [None, None, 'には', None], ['住', 'す', None, None], [None, None, 'む', None], [None, None, 'まい', True], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'のせいでものすごい', None], ['苦情', 'くじょう', None, None], [None, None, 'だ。もう', None], ['失敗', 'しっぱい', None, None], [None, None, 'する', None], [None, None, 'まい', True], [None, None, '。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'の', None], ['話', 'はなし', None, None], [None, None, 'は', None], ['下品', 'げひん', None, None], [None, None, 'だ。', None], ['二度', 'にど', None, None], [None, None, 'と', None], ['聞', 'き', None, None], [None, None, 'く', None], [None, None, 'まい', True], [None, None, '。', None]]
[['昨日', 'きのう', None, None], ['飲', 'の', None, None], [None, None, 'みすぎてしまったので、', None], ['二度', 'にど', None, None], [None, None, 'と', None], ['酒', 'さけ', None, None], [None, None, 'は', None], ['飲', 'の', None, None], [None, None, 'む', None], [None, None, 'まい', True], [None, None, '。', None]]

 59%|█████▊    | 549/938 [05:39<04:21,  1.49it/s]

[['予算', 'よさん', None, None], ['上', 'じょう', None, True], [None, None, '、その', None], ['依頼', 'いらい', None, None], [None, None, 'は', None], ['断', 'ことわ', None, None], [None, None, 'るしかない。', None]]
[[None, None, 'あのビルは', None], ['構造', 'こうぞう', None, None], ['上', 'じょう', None, True], ['地震', 'じしん', None, None], [None, None, 'に', None], ['弱', 'よわ', None, None], [None, None, 'い。', None]]
[['規則', 'きそく', None, None], ['上', 'じょう', None, True], [None, None, '、このアパートでペットを', None], ['飼', 'か', None, None], [None, None, 'うのは', None], ['禁止', 'きんし', None, None], [None, None, 'です。', None]]
[[None, None, 'それは', None], ['飽', 'あ', None, None], [None, None, 'くまで', None], ['計算', 'けいさん', None, None], ['上', 'じょう', None, True], [None, None, 'の', None], ['話', 'はなし', None, None], [None, None, 'で、', None], ['実際', 'じっさい', None, None], [None, None, 'にはそう', None], ['簡単', 'かんたん', None, None], [None, None, 'にはいきません。', None]]
[['立場', 'たちば', None, None], ['上', 'じょう', None, True], [None, None, 'ああいう', None], ['発言', 'はつげん', None, None], [None, None, 'をしたが、', None], ['個人的', 'こじんてき', None, None], [None, None, 'には', None], ['争', 'あらそ', None, None], [None, None, 'う', None], ['気持', 'きも', None, None], [None, None, 'ちは', None], ['全', 'まった', None, None], [None, None, 'くない。', None]]

 59%|█████▊    | 550/938 [05:40<04:24,  1.47it/s]

[[None, None, 'そのジムは', None], ['安', 'やす', None, None], [None, None, 'い', None], ['上', 'うえ', None, True], [None, None, 'に', True], [None, None, '、', None], ['私', 'わたし', None, None], [None, None, 'の', None], ['家', 'いえ', None, None], [None, None, 'から', None], ['近', 'ちか', None, None], [None, None, 'い。', None]]
[[None, None, 'あの', None], ['店', 'みせ', None, None], [None, None, 'はリフォームした', None], ['上', 'うえ', None, True], [None, None, 'に', True], [None, None, '、メニューも', None], ['変', 'か', None, None], [None, None, 'わったらしい。', None]]
[['彼', 'かれ', None, None], [None, None, 'はお', None], ['洒落', 'しゃれ', None, None], [None, None, 'な', True], ['上', 'うえ', None, True], [None, None, 'に', True], [None, None, 'イケメンだから、モテモテだ。', None]]
[['今日', 'きょう', None, None], [None, None, 'の', None], ['宿題', 'しゅくだい', None, None], [None, None, 'は', None], ['簡単', 'かんたん', None, None], [None, None, 'な', True], ['上', 'うえ', None, True], [None, None, 'に', True], [None, None, '、', None], ['少', 'すく', None, None], [None, None, 'ない。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'の', None], ['説明', 'せつめい', None, None], [None, None, 'は、', None], ['曖昧', 'あいまい', None, None], [None, None, 'な', True], ['上', 'うえ', None, True], [None, None, 'に', True], ['不', 'ふ', None, None], ['正確', 'せいかく', None, None], [None, None, 'だ。', None]]

 59%|█████▊    | 551/938 [05:41<04:28,  1.44it/s]

[['試験', 'しけん', None, None], [None, None, 'を', None], ['受', 'う', None, None], [None, None, 'ける', None], ['以上', 'いじょう', None, True], [None, None, '、', None], ['休', 'やす', None, None], [None, None, 'むことはできない。', None]]
[['親', 'おや', None, None], [None, None, 'である', True], ['以上', 'いじょう', None, True], [None, None, 'は', None], ['子', 'こ', None, None], ['育', 'そだ', None, None], [None, None, 'てを', None], ['頑張', 'がんば', None, None], [None, None, 'る', None], [None, None, 'べき', None], [None, None, 'だ。', None]]
[['日本', 'にほん', None, None], [None, None, 'に', None], ['来', 'き', None, None], [None, None, 'た', None], ['以上', 'いじょう', None, True], [None, None, '、', None], ['真剣', 'しんけん', None, None], [None, None, 'に', None], ['日本語', 'にほんご', None, None], [None, None, 'の', None], ['勉強', 'べんきょう', None, None], [None, None, 'をし', None], [None, None, 'たい', None], [None, None, 'と', None], ['思', 'おも', None, None], [None, None, 'います。', None]]
[['都心', 'としん', None, None], [None, None, 'に', None], ['住', 'す', None, None], [None, None, 'んでいる', None], ['以上', 'いじょう', None, True], [None, None, '、', None], ['渋滞', 'じゅうたい', None, None], [None, None, 'は', None], ['避', 'さ', None, None], [None, None, 'けられない。', None]]
[[None, None, 'この', None], ['条件', 'じょうけん', None, None], [None, None, 'で', None], ['引', 'ひ', None, None], [None, None, 'き', None], ['受', 'う', None, None], [None, None, 'けた', None], ['以上', 'いじょう', None, True], [None, None, '、', None], ['文句', 'もんく', None, None], [None, None, 'は', None], ['言', 'い', None, None], [None, None, 'えない。', None]]

 59%|█████▉    | 552/938 [05:41<04:32,  1.42it/s]

[['天気', 'てんき', None, None], [None, None, 'は', None], ['予想', 'よそう', None, None], ['以上', 'いじょう', None, True], [None, None, 'に', True], ['悪', 'わる', None, None], [None, None, 'かった', None], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'には', None], ['思', 'おも', None, None], [None, None, 'った', None], ['以上', 'いじょう', None, True], [None, None, 'の', True], ['人生', 'じんせい', None, None], [None, None, 'がある。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は、', None], ['競馬', 'けいば', None, None], ['以上', 'いじょう', None, True], [None, None, 'に', True], ['競輪', 'けいりん', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'き。', None]]
[[None, None, 'お', None], ['父', 'とう', None, None], [None, None, 'さんのギャグは、', None], ['僕', 'ぼく', None, None], [None, None, 'のギャグ', None], ['以上', 'いじょう', None, True], [None, None, 'に', True], [None, None, 'くだらない。', None]]
[['彼', 'かれ', None, None], [None, None, 'は、カーブ', None], ['以上', 'いじょう', None, True], [None, None, 'に', True], [None, None, 'シュートを', None], [None, None, 'よく', None], ['投', 'な', None, None], [None, None, 'げる', None], ['投手', 'とうしゅ', None, None], [None, None, 'です。', None]]

 59%|█████▉    | 553/938 [05:42<04:59,  1.29it/s]

[[None, None, 'シャッターが', None], ['途中', 'とちゅう', None, True], [None, None, 'で', True], ['閉', 'し', None, None], [None, None, 'まらなくなってしまった。', None]]
[['集金', 'しゅうきん', None, None], [None, None, 'の', None], ['途中', 'とちゅう', None, True], [None, None, 'で', True], [None, None, 'お', None], ['釣', 'つ', None, None], [None, None, 'りがなくなってしまった。', None]]
[['面接', 'めんせつ', None, None], [None, None, 'の', None], ['途中', 'とちゅう', None, True], [None, None, 'で', True], [None, None, 'リクルーターはいきなり', None], ['笑', 'わら', None, None], [None, None, 'い', None], ['始', 'はじ', None, None], [None, None, 'めた。', None]]
[['朝', 'あさ', None, None], [None, None, 'ご', None], ['飯', 'はん', None, None], [None, None, 'を', None], ['作', 'つく', None, None], [None, None, 'っている', None], ['途中', 'とちゅう', None, True], [None, None, 'で', True], ['電話', 'でんわ', None, None], [None, None, 'が', None], ['鳴', 'な', None, None], [None, None, 'った。', None]]
[[None, None, 'シーズン', None], [None, None, 'の', None], ['途中', 'とちゅう', None, True], [None, None, 'で', True], ['引退', 'いんたい', None, None], ['会見', 'かいけん', None, None], [None, None, 'をするのは', None], ['微妙', 'びみょう', None, None], [None, None, 'だ。', None]]

 59%|█████▉    | 554/938 [05:43<05:34,  1.15it/s]

[[None, None, 'トンネルの', None], ['中', 'なか', None, True], [None, None, 'を', True], ['覗', 'のぞ', None, None], [None, None, 'く。', None]]
[['鍋', 'なべ', None, None], [None, None, 'の', None], ['中', 'なか', None, True], [None, None, 'を', True], ['洗', 'あら', None, None], [None, None, 'う。', None]]
[['家', 'いえ', None, None], [None, None, 'の', None], ['中', 'なか', None, True], [None, None, 'を', True], ['猫', 'ねこ', None, None], [None, None, 'が', None], ['駆', 'か', None, None], [None, None, 'け', None], ['回', 'まわ', None, None], [None, None, 'っている。', None]]
[[None, None, 'ペットボトルの', None], ['中', 'なか', None, True], [None, None, 'を', True], [None, None, 'ちゃんと', None], ['洗', 'あら', None, None], [None, None, 'ってください。', None]]
[['人混', 'ひとご', None, None], [None, None, 'みの', None], ['中', 'なか', None, True], [None, None, 'を', True], ['歩', 'ある', None, None], [None, None, 'くのは', None], ['大変', 'たいへん', None, None], [None, None, 'です。', None]]

 59%|█████▉    | 555/938 [05:44<05:01,  1.27it/s]

[[None, None, 'てるはしさん', None], [None, None, 'を', True], ['中心', 'ちゅうしん', None, True], [None, None, 'に', True], ['世界', 'せかい', None, None], [None, None, 'が', None], ['回', 'まわ', None, None], [None, None, 'っている。', None]]
[[None, None, 'マコさんはコンピューター', None], [None, None, 'を', True], ['中心', 'ちゅうしん', None, True], [None, None, 'として', None], ['生活', 'せいかつ', None, None], [None, None, 'をしている。', None]]
[['妻', 'つま', None, None], [None, None, 'は', None], ['働', 'はたら', None, None], [None, None, 'き、', None], ['私', 'わたし', None, None], [None, None, 'は', None], ['育児', 'いくじ', None, None], [None, None, 'を', True], ['中心', 'ちゅうしん', None, True], [None, None, 'に', True], ['生活', 'せいかつ', None, None], [None, None, 'しています。', None]]
[[None, None, 'あのアンテナ', None], [None, None, 'を', True], ['中心', 'ちゅうしん', None, True], [None, None, 'に', True], ['家', 'いえ', None, None], [None, None, 'を', None], ['何', 'なん', None, None], ['軒', 'けん', None, None], [None, None, 'か', None], ['建', 'た', None, None], [None, None, 'てましょう。', None]]
[['息子', 'むすこ', None, None], [None, None, 'はあいかわらずお', None], ['金', 'かね', None, None], [None, None, 'を', True], ['中心', 'ちゅうしん', None, True], [None, None, 'に', True], ['物', 'もの', None, None], [None, None, 'を', None], ['考', 'かんが', None, None], [None, None, 'えているようだ。', None]]

 59%|█████▉    | 556/938 [05:45<05:02,  1.26it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], ['勇', 'いさ', None, None], [None, None, 'ましい。', None], [None, None, 'その', True], ['上', 'うえ', None, True], ['優', 'やさ', None, None], [None, None, 'しいのだから、', None], ['言', 'い', None, None], [None, None, 'うことない。', None]]
[['彼', 'かれ', None, None], [None, None, 'の', None], ['家', 'いえ', None, None], [None, None, 'は', None], ['薄暗', 'うすぐら', None, None], [None, None, 'い。', None], [None, None, 'その', True], ['上', 'うえ', None, True], ['寒', 'さむ', None, None], [None, None, 'いから、', None], ['冬場', 'ふゆば', None, None], [None, None, 'は', None], ['悲惨', 'ひさん', None, None], [None, None, 'だ。', None]]
[['顔', 'かお', None, None], [None, None, 'が', None], ['青白', 'あおじろ', None, None], [None, None, 'い。', None], [None, None, 'その', True], ['上', 'うえ', None, True], [None, None, '、', None], ['唇', 'くちびる', None, None], [None, None, 'は', None], ['紫', 'むらさき', None, None], [None, None, 'だ。', None], ['大丈夫', 'だいじょうぶ', None, None], [None, None, 'だろうか？', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['思', 'おも', None, None], [None, None, 'い', None], ['込', 'こ', None, None], [None, None, 'みが', None], ['激', 'はげ', None, None], [None, None, 'しい。', None], [None, None, 'その', True], ['上', 'うえ', None, True], ['頑固', 'がんこ', None, None], [None, None, 'だから、', None], ['手', 'て', None, None], [None, None, 'に', None], ['負', 'お', None, None], [None, None, 'えない。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['植木', 'うえき', None, None], ['職人', 'しょくにん', None, None], [None, None, 'だ。', None], [None, None, 'その', True], ['上', 'うえ', None, True], [None, None, 'パソコンのプログラムもできるなんて、すごい', None], ['人', 'ひと', None, None], [None, None, 'だ。', None]]

 59%|█████▉    | 557/938 [05:46<04:56,  1.28it/s]

[[None, None, 'かくなる', None], ['上', 'うえ', None, True], [None, None, 'は', True], [None, None, 'きさまを', None], ['殺', 'ころ', None, None], [None, None, 'すしかない。', None], ['今', 'いま', None, None], [None, None, 'すぐ。', None]]
[['何', 'なに', None, None], [None, None, 'かをし', None], ['始', 'はじ', None, None], [None, None, 'める', None], ['上', 'うえ', None, True], [None, None, 'は', True], ['正', 'ただ', None, None], [None, None, 'しくやらなければならない。', None]]
[['日本', 'にほん', None, None], [None, None, 'に', None], ['来', 'き', None, None], [None, None, 'た', None], ['上', 'うえ', None, True], [None, None, 'は', True], ['勉強', 'べんきょう', None, None], [None, None, 'するつもりです。', None]]
[['卒業', 'そつぎょう', None, None], [None, None, 'した', None], ['上', 'うえ', None, True], [None, None, 'は', True], [None, None, 'より', None], ['大人', 'おとな', None, None], [None, None, 'らしくなるべきだ。', None]]
[['市長', 'しちょう', None, None], [None, None, 'になった', None], ['上', 'うえ', None, True], [None, None, 'は', True], ['住民', 'じゅうみん', None, None], [None, None, 'のために', None], ['何', 'なに', None, None], [None, None, 'かをしてあげたいです。', None]]

 59%|█████▉    | 558/938 [05:46<05:07,  1.24it/s]

[[None, None, 'ベジカと', None], ['戦', 'たたか', None, None], [None, None, 'うためにそんゴツウはカエ', None], ['王様', 'おうさま', None, None], [None, None, 'の', True], ['下', 'もと', None, True], [None, None, 'で', True], ['修行', 'しゅぎょう', None, None], [None, None, 'した。', None]]
[['叔父', 'おじ', None, None], [None, None, 'さん', None], [None, None, 'の', True], ['下', 'もと', None, True], [None, None, 'で', True], ['働', 'はたら', None, None], [None, None, 'いた', None], ['３', 'さん', None, None], ['年間', 'ねんかん', None, None], [None, None, 'は、', None], ['僕', 'ぼく', None, None], [None, None, 'にとって', None], ['宝物', 'たからもの', None, None], [None, None, 'です。', None]]
[['盤石', 'ばんじゃく', None, None], [None, None, 'な', None], ['地盤', 'じばん', None, None], [None, None, 'の', True], ['下', 'もと', None, True], [None, None, 'で', True], [None, None, 'の', None], ['選挙', 'せんきょ', None, None], [None, None, 'だが、', None], ['余裕', 'よゆう', None, None], [None, None, 'というわけではない。', None]]
[['優秀', 'ゆうしゅう', None, None], [None, None, 'な', None], ['講師', 'こうし', None, None], [None, None, 'の', True], ['下', 'もと', None, True], [None, None, 'で', True], ['実験', 'じっけん', None, None], [None, None, 'をしていたから、いろいろなスキルが', None], ['身', 'み', None, None], [None, None, 'につきました。', None]]
[['高', 'たか', None, None], [None, None, 'い', None], ['基準', 'きじゅん', None, None], [None, None, 'の', True], ['下', 'もと', None, True], [None, None, 'で', True], ['訓練', 'くんれん', None, None], [None, None, 'を', None], ['受', 'う', None, None], [None, None, 'けたから、その', None], ['後', 'ご', None, None], [None, None, 'の', None], ['仕事', 'しごと', None, None], [None, None, 'が', None], ['楽', 'らく', None, None], [None, None, 'にこなせる。', None]]

 60%|█████▉    | 559/938 [05:47<04:56,  1.28it/s]

[[None, None, '「', None], ['次', 'つぎ', None, None], [None, None, 'の', None], ['電車', 'でんしゃ', None, None], [None, None, 'はいつくるの？」', None], [None, None, '「', None], ['後', 'あと', None, True], ['八分', 'はっぷん', None, None], [None, None, 'で', None], ['来', 'く', None, None], [None, None, 'るよ。」', None]]
[[None, None, 'いすずちゃん', None], [None, None, '：「この', None], ['問題', 'もんだい', None, None], [None, None, 'は', None], ['私', 'わたし', None, None], [None, None, 'がやるわ。」', None], [None, None, 'かにえくん', None], [None, None, '：「じゃあ、', None], ['後', 'あと', None, True], [None, None, 'はこっちに', None], ['任', 'まか', None, None], [None, None, 'せてくれ。」', None]]
[[None, None, 'チトゲさん', None], [None, None, '：「ラクさんが', None], ['来', 'く', None, None], [None, None, 'るまで、', None], ['後', 'あと', None, True], ['何分', 'なんぷん', None, None], [None, None, '？」', None], [None, None, 'オノデラさん', None], [None, None, '：「まだ', None], ['後', 'あと', None, True], ['五', 'ご', None, None], ['分', 'ふん', None, None], [None, None, '！」', None]]
[['彼女', 'かのじょ', None, None], [None, None, '：「たまごと', None], ['牛乳', 'ぎゅうにゅう', None, None], [None, None, 'はあるの。」', None], ['彼氏', 'かれし', None, None], [None, None, '：「', None], ['後', 'あと', None, True], [None, None, 'は', None], ['何', 'なに', None, None], [None, None, 'が', None], ['必要', 'ひつよう', None, None], [None, None, 'なの？」', None]]
[[None, None, 'ヨツバちゃん', None], [None, None, '：「ミクとイツキは', None], ['先', 'さき', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'ったわ。」', None], [None, None, 'フウタロウくん', None], [None, None, '：「', None], ['後', 'あと', None, True], [None, None, 'の', True], ['連中', 'れんちゅう', None, None], [None, None, 'は？」', None], [None, None, 'ヨツバちゃん', None], [None, None, '：「', None], ['全然', 'ぜんぜん', None, None], [None, None, 'わからないわ。」', None]]

 60%|█████▉    | 560/938 [05:48<04:40,  1.35it/s]

[[None, None, 'あなた', None], [None, None, 'の', True], ['手前', 'てまえ', None, True], [None, None, 'にあるものを', None], ['見', 'み', None, None], [None, None, 'てください。', None]]
[[None, None, 'オルガンをもっと', None], ['手前', 'てまえ', None, True], [None, None, 'に', None], ['配置', 'はいち', None, None], [None, None, 'してください。', None]]
[['死', 'し', None, None], [None, None, 'んでしまう', None], ['一歩', 'いっぽ', None, None], ['手前', 'てまえ', None, True], [None, None, 'で', None], ['助', 'たす', None, None], [None, None, 'かった。', None]]
[['私', 'わたし', None, None], [None, None, 'の', True], ['手前', 'てまえ', None, True], [None, None, 'の', None], ['人', 'ひと', None, None], [None, None, 'が、', None], ['私', 'わたし', None, None], [None, None, 'の', None], ['友達', 'ともだち', None, None], [None, None, 'です。', None]]
[['火山', 'かざん', None, None], [None, None, 'の', None], ['被害', 'ひがい', None, None], [None, None, 'がうち', None], [None, None, 'の', True], ['手前', 'てまえ', None, True], [None, None, 'まで', None], ['及', 'およ', None, None], [None, None, 'んだ。', None]]

 60%|█████▉    | 561/938 [05:48<04:33,  1.38it/s]

[['日本', 'にっぽん', None, None], [None, None, 'には', None], ['金魚', 'きんぎょ', None, None], [None, None, 'を', True], ['巡', 'めぐ', None, True], [None, None, 'る', True], ['戦', 'たたか', None, None], [None, None, 'いがある。', None]]
[[None, None, 'あの', None], ['組合', 'くみあわ', None, None], [None, None, 'せ', None], [None, None, 'を', True], ['巡', 'めぐ', None, True], [None, None, 'って', True], [None, None, 'は、やらせの', None], ['疑', 'うたが', None, None], [None, None, 'いがある。', None]]
[[None, None, 'ファイルの', None], ['形式', 'けいしき', None, None], [None, None, 'を', True], ['巡', 'めぐ', None, True], [None, None, 'る', True], ['話', 'はな', None, None], [None, None, 'し', None], ['合', 'あ', None, None], [None, None, 'いが', None], ['今', 'いま', None, None], [None, None, 'も', None], ['続', 'つづ', None, None], [None, None, 'いています。', None]]
[['伝説', 'でんせつ', None, None], [None, None, 'の', None], ['釜', 'かま', None, None], [None, None, 'を', True], ['巡', 'めぐ', None, True], [None, None, 'って', True], [None, None, '、', None], ['専門', 'せんもん', None, None], ['家', 'か', None, None], [None, None, 'たちが', None], ['言', 'い', None, None], [None, None, 'い', None], ['合', 'あ', None, None], [None, None, 'いをしています。', None]]
[['塩分', 'えんぶん', None, None], [None, None, 'の', None], ['過剰', 'かじょう', None, None], ['摂取', 'せっしゅ', None, None], [None, None, 'を', True], ['巡', 'めぐ', None, True], [None, None, 'って', True], [None, None, '、', None], ['意見', 'いけん', None, None], [None, None, 'が', None], ['分', 'わ', None, None], [None, None, 'かれている。', None]]

 60%|█████▉    | 562/938 [05:49<04:16,  1.47it/s]

[[None, None, 'この', None], ['車', 'くるま', None, None], [None, None, 'の', None], ['細部', 'さいぶ', None, None], [None, None, 'に', True], ['渡', 'わた', None, True], [None, None, 'る', True], [None, None, 'こだわりはさすがですね。', None]]
[['三日', 'みっか', None, None], [None, None, 'に', True], ['渡', 'わた', None, True], [None, None, 'って', True], ['降', 'ふ', None, None], [None, None, 'り', None], ['続', 'つづ', None, None], [None, None, 'いた', None], ['雨', 'あめ', None, None], [None, None, 'がようやくやんだ。', None]]
[['４０', 'よんじゅっ', None, None], ['分', 'ぷん', None, None], [None, None, 'に', True], ['渡', 'わた', None, True], [None, None, 'る', True], ['校長', 'こうちょう', None, None], ['先生', 'せんせい', None, None], [None, None, 'の', None], ['話', 'はなし', None, None], [None, None, 'が', None], ['退屈', 'たいくつ', None, None], [None, None, 'だった。', None]]
[['長期', 'ちょうき', None, None], [None, None, 'に', True], ['渡', 'わた', None, True], [None, None, 'って', True], ['利用', 'りよう', None, None], [None, None, 'してきたサービスが', None], ['終了', 'しゅうりょう', None, None], [None, None, 'してしまう。', None]]
[['今日', 'きょう', None, None], [None, None, 'から', None], ['７', 'なな', None, None], ['回', 'かい', None, None], [None, None, 'に', True], ['渡', 'わた', None, True], [None, None, 'って', True], [None, None, '、このテーマで', None], ['授業', 'じゅぎょう', None, None], [None, None, 'を', None], ['進', 'すす', None, None], [None, None, 'めていきます。', None]]

 60%|██████    | 563/938 [05:50<04:25,  1.41it/s]

[[None, None, 'スケジュール', None], [None, None, 'に', True], ['沿', 'そ', None, True], [None, None, 'って', True], ['作業', 'さぎょう', None, None], [None, None, 'を', None], ['進', 'すす', None, None], [None, None, 'めていきます。', None]]
[[None, None, 'この', None], ['台本', 'だいほん', None, None], [None, None, 'に', True], ['沿', 'そ', None, True], [None, None, 'って', True], ['司会', 'しかい', None, None], [None, None, 'してください。', None]]
[[None, None, 'じゅうたん', None], [None, None, 'に', True], ['沿', 'そ', None, True], [None, None, 'って', True], [None, None, 'しるしを', None], ['付', 'つ', None, None], [None, None, 'けるのはやめてほしい。', None]]
[['提示', 'ていじ', None, None], [None, None, 'した', None], ['資料', 'しりょう', None, None], [None, None, 'に', True], ['沿', 'そ', None, True], [None, None, 'って', True], [None, None, 'チェックを', None], ['進', 'すす', None, None], [None, None, 'めてください。', None]]
[[None, None, '「', None], ['道', 'みち', None, None], [None, None, 'に', True], ['沿', 'そ', None, True], [None, None, 'って', True], [None, None, 'いったら、そのうちスーパーが', None], ['見', 'み', None, None], [None, None, 'えてきますよ」', None]]

 60%|██████    | 564/938 [05:51<04:33,  1.37it/s]

[['温泉', 'おんせん', None, None], [None, None, 'を', None], [None, None, 'ほりあてた', True], ['末', 'すえ', None, True], [None, None, 'に', True], [None, None, '、', None], ['旅館', 'りょかん', None, None], [None, None, 'を', None], ['建', 'た', None, None], [None, None, 'てることにした。', None]]
[[None, None, 'これは、', None], ['蚊', 'か', None, None], [None, None, 'に', None], [None, None, 'さされた', True], ['末', 'すえ', None, True], [None, None, 'の', None], ['感染', 'かんせん', None, None], ['症', 'しょう', None, None], [None, None, 'です。', None]]
[[None, None, 'いろいろ', None], ['面接', 'めんせつ', None, None], [None, None, 'した', True], ['末', 'すえ', None, True], [None, None, 'に', True], [None, None, '、', None], ['大', 'だい', None, None], ['企業', 'きぎょう', None, None], [None, None, 'に', None], ['雇', 'やと', None, None], [None, None, 'われたんだ。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'は、', None], ['散々', 'さんざん', None, None], [None, None, 'おそわった', True], ['末', 'すえ', None, True], [None, None, 'に', True], ['仕事', 'しごと', None, None], [None, None, 'をやめてしまった。', None]]
[['無理', 'むり', None, None], [None, None, 'をして', None], ['試合', 'しあい', None, None], [None, None, 'に', None], [None, None, 'でた', True], ['末', 'すえ', None, True], [None, None, 'に', True], [None, None, '、', None], ['大', 'おお', None, None], ['怪我', 'けが', None, None], [None, None, 'をしてしまった。', None]]

 60%|██████    | 565/938 [05:51<04:19,  1.44it/s]

[[None, None, 'この', None], ['原稿', 'げんこう', None, None], [None, None, 'に', True], ['従', 'したが', None, True], [None, None, 'って', True], [None, None, 'インタビューに', None], ['答', 'こた', None, None], [None, None, 'えてください。', None]]
[['憲法', 'けんぽう', None, None], [None, None, 'に', True], ['従', 'したが', None, True], [None, None, 'って', True], [None, None, '、', None], ['新', 'あら', None, None], [None, None, 'たな', None], ['法律', 'ほうりつ', None, None], [None, None, 'が', None], ['成立', 'せいりつ', None, None], [None, None, 'する。', None]]
[[None, None, 'クラスメイトの', None], ['言', 'い', None, None], [None, None, 'うこと', None], [None, None, 'に', True], ['従', 'したが', None, True], [None, None, 'って', True], ['意地悪', 'いじわる', None, None], [None, None, 'をしてはいけません。', None]]
[[None, None, 'この', None], ['足跡', 'あしあと', None, None], [None, None, 'に', True], ['従', 'したが', None, True], [None, None, 'って', True], ['進', 'すす', None, None], [None, None, 'めば、きっとみんなに', None], ['会', 'あ', None, None], [None, None, 'えるはずです。', None]]
[['会社', 'かいしゃ', None, None], [None, None, 'の', None], ['指示', 'しじ', None, None], [None, None, 'に', True], ['従', 'したが', None, True], [None, None, 'って', True], [None, None, 'オートメーション', None], ['化', 'か', None, None], [None, None, 'を', None], ['進', 'すす', None, None], [None, None, 'めています。', None]]

 60%|██████    | 566/938 [05:52<04:04,  1.52it/s]

[['春', 'はる', None, None], [None, None, 'が', None], ['始', 'はじ', None, None], [None, None, 'まる', None], [None, None, 'に', True], ['伴', 'ともな', None, True], [None, None, 'って', True], [None, None, '、', None], ['植生', 'しょくせい', None, None], [None, None, 'は', None], ['復活', 'ふっかつ', None, None], [None, None, 'する。', None]]
[['医学', 'いがく', None, None], [None, None, 'の', None], ['進歩', 'しんぽ', None, None], [None, None, 'に', True], ['伴', 'ともな', None, True], [None, None, 'って', True], ['平均', 'へいきん', None, None], ['寿命', 'じゅみょう', None, None], [None, None, 'が', None], ['伸', 'の', None, None], [None, None, 'びています。', None]]
[['円', 'えん', None, None], ['高', 'だか', None, None], [None, None, 'に', True], ['伴', 'ともな', None, True], [None, None, 'い', True], ['輸出', 'ゆしゅつ', None, None], [None, None, 'の', None], ['量', 'りょう', None, None], [None, None, 'は', None], ['減', 'へ', None, None], [None, None, 'る。', None]]
[['火傷', 'やけど', None, None], [None, None, 'に', True], ['伴', 'ともな', None, True], [None, None, 'う', True], ['痛', 'いた', None, None], [None, None, 'みは', None], ['神経', 'しんけい', None, None], [None, None, 'への', None], ['刺激', 'しげき', None, None], [None, None, 'が', None], ['原因', 'げんいん', None, None], [None, None, 'だとされている。', None]]
[['城', 'しろ', None, None], [None, None, 'の', None], ['改修', 'かいしゅう', None, None], ['中', 'ちゅう', None, None], [None, None, '、', None], ['床', 'ゆか', None, None], [None, None, 'の', None], ['修理', 'しゅうり', None, None], [None, None, 'に', True], ['伴', 'ともな', None, True], [None, None, 'って', True], [None, None, '、', None], ['壁', 'かべ', None, None], [None, None, 'も', None], ['塗', 'ぬ', None, None], [None, None, 'りなおされた。', None]]

 60%|██████    | 567/938 [05:52<03:51,  1.60it/s]

[['工事', 'こうじ', None, None], ['中', 'ちゅう', None, None], [None, None, 'に', True], ['就', 'つ', None, True], [None, None, 'き', True], [None, None, '、', None], ['迂回', 'うかい', None, None], [None, None, 'してください。', None]]
[['開店', 'かいてん', None, None], [None, None, 'に', True], ['就', 'つ', None, True], [None, None, 'き', True], [None, None, '、', None], ['事務', 'じむ', None, None], ['員', 'いん', None, None], [None, None, 'を', None], ['募集', 'ぼしゅう', None, None], [None, None, 'する。', None]]
[['今', 'いま', None, None], [None, None, 'なら', None], ['１００', 'ひゃく', None, None], ['円', 'えん', None, None], [None, None, 'に', True], ['就', 'つ', None, True], [None, None, 'き', True], ['５', 'ご', None, None], [None, None, 'ポイントもらえる。', None]]
[['明日', 'あした', None, None], [None, None, 'は', None], ['祭日', 'さいじつ', None, None], [None, None, 'に', True], ['就', 'つ', None, True], [None, None, 'き', True], [None, None, '、', None], ['会社', 'かいしゃ', None, None], [None, None, 'は', None], ['休', 'やす', None, None], [None, None, 'みです。', None]]
[[None, None, 'ここは', None], ['私有地', 'しゆうち', None, None], [None, None, 'に', True], ['就', 'つ', None, True], [None, None, 'き', True], [None, None, '、', None], ['通', 'とお', None, None], [None, None, 'り', None], ['抜', 'ぬ', None, None], [None, None, 'け', None], ['禁止', 'きんし', None, None], [None, None, 'です。', None]]

 61%|██████    | 568/938 [05:53<03:57,  1.56it/s]

[['話', 'はな', None, None], [None, None, 'し', None], ['合', 'あ', None, None], [None, None, 'いをする', None], [None, None, 'に', True], ['付', 'つ', None, True], [None, None, 'け', True], [None, None, '、', None], ['喧嘩', 'けんか', None, None], [None, None, 'ばかりしてしまう。', None]]
[[None, None, 'この', None], ['絵', 'え', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'る', None], [None, None, 'に', True], ['付', 'つ', None, True], [None, None, 'け', True], [None, None, '、', None], ['子供', 'こども', None, None], [None, None, 'の', None], ['頃', 'ころ', None, None], [None, None, 'のことを', None], ['思', 'おも', None, None], [None, None, 'い', None], ['出', 'だ', None, None], [None, None, 'す。', None]]
[['悪', 'わる', None, None], [None, None, 'い', None], ['噂', 'うわさ', None, None], [None, None, 'を', None], ['聞', 'き', None, None], [None, None, 'く', None], [None, None, 'に', True], ['付', 'つ', None, True], [None, None, 'けて', True], [None, None, '、だんだん', None], ['不安', 'ふあん', None, None], [None, None, 'になってきた。', None]]
[['雨', 'あめ', None, None], [None, None, 'に', True], ['付', 'つ', None, True], [None, None, 'け', True], ['雪', 'ゆき', None, None], [None, None, 'に', True], ['付', 'つ', None, True], [None, None, 'け', True], [None, None, '、どうせ', None], ['仕事', 'しごと', None, None], [None, None, 'には', None], ['行', 'い', None, None], [None, None, 'かなければならない。', None]]
[['隣', 'となり', None, None], [None, None, 'の', None], ['叔父', 'おじ', None, None], [None, None, 'さんは', None], ['何', 'なに', None, None], [None, None, 'か', None], [None, None, 'に', True], ['付', 'つ', None, True], [None, None, 'けて', True], ['文句', 'もんく', None, None], [None, None, 'を', None], ['言', 'い', None, None], [None, None, 'う', None], ['人', 'ひと', None, None], [None, None, 'だ。', None]]

 61%|██████    | 569/938 [05:54<03:49,  1.61it/s]

[['医師', 'いし', None, None], [None, None, 'は', None], ['命', 'いのち', None, None], [None, None, 'に', True], ['関', 'かか', None, True], [None, None, 'わる', True], ['仕事', 'しごと', None, None], [None, None, 'です。', None]]
[['判事', 'はんじ', None, None], [None, None, 'の', None], ['行動', 'こうどう', None, None], [None, None, 'は', None], ['司法', 'しほう', None, None], [None, None, 'の', None], ['信用', 'しんよう', None, None], [None, None, 'に', True], ['関', 'かか', None, True], [None, None, 'わる', True], [None, None, '。', None]]
[['会社', 'かいしゃ', None, None], [None, None, 'の', None], ['存亡', 'そんぼう', None, None], [None, None, 'に', True], ['関', 'かか', None, True], [None, None, 'わる', True], ['危機', 'きき', None, None], [None, None, 'に', None], ['直面', 'ちょくめん', None, None], [None, None, 'している。', None]]
[[None, None, 'わたしの', None], ['将来', 'しょうらい', None, None], [None, None, 'に', True], ['関', 'かか', None, True], [None, None, 'わる', True], ['面接', 'めんせつ', None, None], [None, None, 'だから、', None], ['重要', 'じゅうよう', None, None], [None, None, 'なんです。', None]]
[['人間', 'にんげん', None, None], ['関係', 'かんけい', None, None], [None, None, 'に', True], ['関', 'かか', None, True], [None, None, 'わる', True], ['問題', 'もんだい', None, None], [None, None, 'はなかなか', None], ['難', 'むずか', None, None], [None, None, 'しい。', None]]

 61%|██████    | 570/938 [05:54<04:05,  1.50it/s]

[[None, None, 'カメラ', None], [None, None, 'に', True], ['向', 'む', None, True], [None, None, 'かって', True], [None, None, '、', None], ['笑顔', 'えがお', None, None], [None, None, 'をお', None], ['願', 'ねが', None, None], [None, None, 'いします。', None]]
[['受験生', 'じゅけんせい', None, None], [None, None, 'に', True], ['向', 'む', None, True], [None, None, 'けて', True], [None, None, 'アドバイスをお', None], ['願', 'ねが', None, None], [None, None, 'いします。', None]]
[['日本', 'にほん', None, None], [None, None, 'をはじめ、', None], ['外国', 'がいこく', None, None], [None, None, 'に', True], ['向', 'む', None, True], [None, None, 'けて', True], [None, None, 'ブランドを', None], ['広', 'ひろ', None, None], [None, None, 'げたい。', None]]
[['通貨', 'つうか', None, None], ['統一', 'とういつ', None, None], [None, None, 'に', True], ['向', 'む', None, True], [None, None, 'けて', True], [None, None, 'の', None], ['動', 'うご', None, None], [None, None, 'きが', None], ['加速', 'かそく', None, None], [None, None, 'している。', None]]
[['深夜', 'しんや', None, None], [None, None, 'のアルバイト', None], [None, None, 'に', True], ['向', 'む', None, True], [None, None, 'けて', True], ['昼寝', 'ひるね', None, None], [None, None, 'をしておこう。', None]]

 61%|██████    | 571/938 [05:55<04:08,  1.48it/s]

[[None, None, 'あの', None], ['工場', 'こうじょう', None, None], ['見学', 'けんがく', None, None], [None, None, 'が', True], ['気', 'き', None, True], [None, None, 'になる', True], [None, None, '。', None]]
[['最近', 'さいきん', None, None], [None, None, '、', None], ['芸能界', 'げいのうかい', None, None], [None, None, 'が', True], ['気', 'き', None, True], [None, None, 'になる', True], [None, None, '。', None]]
[[None, None, 'あの', None], ['映画', 'えいが', None, None], [None, None, 'が', True], ['気', 'き', None, True], [None, None, 'になっている', True], [None, None, '。あらすじだけは', None], ['知', 'し', None, None], [None, None, 'っているけど。', None]]
[[None, None, 'この', None], ['香水', 'こうすい', None, None], [None, None, 'を', None], ['付', 'つ', None, None], [None, None, 'けている', None], ['人', 'ひと', None, None], [None, None, 'が', True], ['気', 'き', None, True], [None, None, 'になる', True], [None, None, '。', None]]
[[None, None, 'クッキーよりもその', None], ['入', 'い', None, None], [None, None, 'れ', None], ['物', 'もの', None, None], [None, None, 'が', True], ['気', 'き', None, True], [None, None, 'になっている', True], [None, None, '。すごくかわいいから。', None]]

 61%|██████    | 572/938 [05:56<04:14,  1.44it/s]

[['頭', 'あたま', None, None], [None, None, 'をぶつけないようにシャッター', None], [None, None, 'に', True], ['気', 'き', None, True], [None, None, 'をつけよう', True], [None, None, '。', None]]
[['電柱', 'でんちゅう', None, None], [None, None, 'に', True], ['気', 'き', None, True], [None, None, 'をつけて', True], ['車庫', 'しゃこ', None, None], ['入', 'い', None, None], [None, None, 'れをしてください。', None]]
[['氷', 'こおり', None, None], [None, None, 'は', None], ['滑', 'すべ', None, None], [None, None, 'りやすいから、', None], ['足', 'あし', None, None], [None, None, 'もと', None], [None, None, 'に', True], ['気', 'き', None, True], [None, None, 'をつけて', True], [None, None, '。', None]]
[['妊娠', 'にんしん', None, None], ['中', 'ちゅう', None, None], [None, None, 'の', None], ['女性', 'じょせい', None, None], [None, None, 'は、', None], ['健康', 'けんこう', None, None], [None, None, 'に', True], ['気', 'き', None, True], [None, None, 'をつける', True], [None, None, 'べきだ。', None]]
[['階段', 'かいだん', None, None], [None, None, 'は', None], ['急', 'きゅう', None, None], [None, None, 'だから、', None], ['落', 'お', None, None], [None, None, 'ち', None], [None, None, 'ないよう', None], [None, None, 'に', True], ['気', 'き', None, True], [None, None, 'をつけなさい', True], [None, None, '。', None]]

 61%|██████    | 573/938 [05:57<04:21,  1.40it/s]

[['御馳走', 'ごちそう', None, None], [None, None, 'もかまわず', True], [None, None, '、', None], ['仕事', 'しごと', None, None], [None, None, 'に', None], ['没頭', 'ぼっとう', None, None], [None, None, 'している。', None]]
[[None, None, 'さんざん', None], ['失敗', 'しっぱい', None, None], [None, None, 'した', None], [None, None, 'にも', True], ['構', 'かま', None, True], [None, None, 'わず', True], [None, None, '、まだ', None], ['研究', 'けんきゅう', None, None], [None, None, 'に', None], ['打', 'う', None, None], [None, None, 'ち', None], ['込', 'こ', None, None], [None, None, 'んでいる。', None]]
[[None, None, 'サイレン', None], [None, None, 'にもかまわず', True], [None, None, '、', None], ['避難', 'ひなん', None, None], [None, None, 'しようとしない', None], ['人', 'ひと', None, None], [None, None, 'もいる。', None]]
[['錆', 'さび', None, None], [None, None, 'もかまわず', True], ['放置', 'ほうち', None, None], [None, None, 'していたせいで、', None], ['使', 'つか', None, None], [None, None, 'えなくなってしまった。', None]]
[['塩辛', 'しおから', None, None], [None, None, 'いと', None], ['感', 'かん', None, None], [None, None, 'じていた', None], [None, None, 'にもかまわず', True], ['食', 'た', None, None], [None, None, 'べ', None], ['続', 'つづ', None, None], [None, None, 'けて、', None], ['病気', 'びょうき', None, None], [None, None, 'になってしまった。', None]]

 61%|██████    | 574/938 [05:57<04:03,  1.49it/s]

[[None, None, '「', None], ['役者', 'やくしゃ', None, None], [None, None, 'になりたい」だなんて、', None], ['賛成', 'さんせい', None, None], [None, None, 'しかねる', True], [None, None, '。', None]]
[['専門', 'せんもん', None, None], ['的', 'てき', None, None], [None, None, 'なプログラムには', None], ['対応', 'たいおう', None, None], [None, None, 'し', True], ['兼', 'か', None, True], [None, None, 'ねる', True], [None, None, '。', None]]
[[None, None, 'そんな', None], ['乱暴', 'らんぼう', None, None], [None, None, 'なやり', None], ['方', 'かた', None, None], [None, None, 'は', None], ['承服', 'しょうふく', None, None], [None, None, 'し', True], ['兼', 'か', None, True], [None, None, 'ねる', True], [None, None, '。', None]]
[[None, None, 'そんな', None], ['無茶', 'むちゃ', None, None], [None, None, 'な', None], ['要望', 'ようぼう', None, None], [None, None, 'はお', None], ['引受', 'ひきう', None, None], [None, None, 'け', None], [None, None, 'し', True], ['兼', 'か', None, True], [None, None, 'ねます', True], [None, None, '。', None]]
[[None, None, 'そういう', None], ['方針', 'ほうしん', None, None], [None, None, 'ということでしたら、', None], ['応援', 'おうえん', None, None], [None, None, 'し', True], ['兼', 'か', None, True], [None, None, 'ねます', True], [None, None, '。', None]]

 61%|██████▏   | 575/938 [05:58<04:05,  1.48it/s]

[[None, None, 'この', None], ['事', 'こと', None, None], [None, None, 'をそのままにしていたら、', None], ['摩擦', 'まさつ', None, None], [None, None, 'を', None], [None, None, 'うみ', True], ['兼', 'か', None, True], [None, None, 'ねない', True], [None, None, '。', None]]
[['危険', 'きけん', None, None], [None, None, 'な', None], ['運転', 'うんてん', None, None], [None, None, 'をすれば、', None], ['事故', 'じこ', None, None], [None, None, 'が', None], ['起', 'お', None, True], [None, None, 'こり', True], ['兼', 'か', None, True], [None, None, 'ねない', True], [None, None, '。', None]]
[[None, None, 'この', None], ['犬', 'いぬ', None, None], [None, None, 'に', None], ['噛', 'か', None, None], [None, None, 'まれたら、', None], ['大', 'おお', None, None], ['怪我', 'けが', None, None], [None, None, 'を', None], [None, None, 'しかねない', True], [None, None, '。', None]]
[[None, None, 'この', None], ['程度', 'ていど', None, None], [None, None, 'の', None], ['怪我', 'けが', None, None], [None, None, 'でも、ウイルスに', None], ['感染', 'かんせん', None, None], [None, None, 'し', True], ['兼', 'か', None, True], [None, None, 'ねない', True], [None, None, '。', None]]
[['灯油', 'とうゆ', None, None], [None, None, 'の', None], ['保管', 'ほかん', None, None], [None, None, 'をちゃんとしないと、', None], ['火事', 'かじ', None, None], [None, None, 'に', None], [None, None, 'なり', True], ['兼', 'か', None, True], [None, None, 'ねない', True], [None, None, '。', None]]

 61%|██████▏   | 576/938 [05:59<04:09,  1.45it/s]

[['病院', 'びょういん', None, None], [None, None, 'スタッフ', None], [None, None, 'を', True], ['除', 'のぞ', None, True], [None, None, 'いて', True], [None, None, '、', None], ['入', 'はい', None, None], [None, None, 'ってはならない。', None]]
[[None, None, 'エウロパ', None], [None, None, 'を', True], ['除', 'のぞ', None, True], [None, None, 'いて', True], [None, None, '、これらすべての', None], ['世界', 'せかい', None, None], [None, None, 'が', None], ['人間', 'にんげん', None, None], [None, None, 'に', None], ['属', 'ぞく', None, None], [None, None, 'しています。', None]]
[['一部', 'いちぶ', None, None], [None, None, 'の', None], ['作業', 'さぎょう', None, None], [None, None, 'を', True], ['除', 'のぞ', None, True], [None, None, 'いて', True], [None, None, '、ほとんどがオートメーション', None], ['化', 'か', None, None], [None, None, 'されている。', None]]
[[None, None, 'あなた', None], [None, None, 'を', True], ['除', 'のぞ', None, True], [None, None, 'いて', True], [None, None, '、', None], ['他', 'ほか', None, None], [None, None, 'の', None], ['社員', 'しゃいん', None, None], [None, None, 'は', None], ['皆', 'みな', None, None], [None, None, 'お', None], ['帰', 'かえ', None, None], [None, None, 'りください。', None]]
[[None, None, 'あの', None], ['楽器', 'がっき', None, None], [None, None, 'を', True], ['除', 'のぞ', None, True], [None, None, 'く', True], [None, None, 'すべての', None], ['楽器', 'がっき', None, None], [None, None, 'はわたしの', None], ['私物', 'しぶつ', None, None], [None, None, 'です。', None]]

 62%|██████▏   | 577/938 [06:00<04:41,  1.28it/s]

[['点', 'てん', None, None], ['数', 'すう', None, None], [None, None, 'に', True], ['関', 'かか', None, True], [None, None, 'わらず', True], [None, None, '、', None], ['参加', 'さんか', None, None], [None, None, 'しただけで', None], ['合格', 'ごうかく', None, None], [None, None, 'できる', None], ['試験', 'しけん', None, None], [None, None, 'もある。', None]]
[['好', 'す', None, None], [None, None, 'き', None], ['嫌', 'きら', None, None], [None, None, 'い', None], [None, None, 'に', True], ['関', 'かか', None, True], [None, None, 'わらず', True], [None, None, '、この', None], ['課題', 'かだい', None, None], [None, None, 'はやってもらわないと', None], ['困', 'こま', None, None], [None, None, 'ります。', None]]
[['流行', 'りゅうこう', None, None], [None, None, 'に', True], ['関', 'かか', None, True], [None, None, 'わらず', True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'は', None], ['昔', 'むかし', None, None], [None, None, 'からああいう', None], ['格好', 'かっこう', None, None], [None, None, 'をしています。', None]]
[['実力', 'じつりょく', None, None], [None, None, 'に', True], ['関', 'かか', None, True], [None, None, 'わらず', True], ['仕事', 'しごと', None, None], [None, None, 'を', None], ['与', 'あた', None, None], [None, None, 'えるから、かなり', None], ['効率', 'こうりつ', None, None], [None, None, 'が', None], ['悪', 'わる', None, None], [None, None, 'い。', None]]
[[None, None, 'この', None], ['棚', 'たな', None, None], [None, None, 'の', None], ['商品', 'しょうひん', None, None], [None, None, 'に', None], ['限', 'かぎ', None, None], [None, None, 'り、', None], ['大', 'おお', None, None], [None, None, 'きい', None], ['小', 'ちい', None, None], [None, None, 'さい', None], [None, None, 'に', True], ['関', 'かか', None, True], [None, None, 'わらず', True], [None, None, '、', None], ['全品', 'ぜんぴん', None, None], [None, None, '100', None], ['円', 'えん', None, None], [None, None, '。', None]]

 62%|██████▏   | 578/938 [06:00<04:22,  1.37it/s]

[['勘違', 'かんちが', None, None], [None, None, 'いした', None], [None, None, 'にもかかわらず', True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'は', None], ['一切', 'いっさい', None, None], ['謝', 'あやま', None, None], [None, None, 'らない。', None]]
[[None, None, 'あんなにかわいがった', None], [None, None, 'にもかかわらず', True], [None, None, '、', None], ['裏切', 'うらぎ', None, None], [None, None, 'られるなんて…', None]]
[['間隔', 'かんかく', None, None], [None, None, 'があいた', None], [None, None, 'にもかかわらず', True], [None, None, '、', None], ['相変', 'あいか', None, None], [None, None, 'わらずいいプレーをしますね。', None]]
[['乾燥', 'かんそう', None, None], [None, None, 'している', None], [None, None, 'にもかかわらず', True], ['加湿', 'かしつ', None, None], [None, None, 'しないから、', None], ['喉', 'のど', None, None], [None, None, 'をやられた。', None]]
[['喉', 'のど', None, None], [None, None, 'が', None], ['渇', 'かわ', None, None], [None, None, 'いている', None], [None, None, 'にもかかわらず', True], [None, None, '、', None], ['飲', 'の', None, None], [None, None, 'み', None], ['物', 'もの', None, None], [None, None, 'を', None], ['与', 'あた', None, None], [None, None, 'えないのは', None], ['虐待', 'ぎゃくたい', None, None], [None, None, 'だ。', None]]

 62%|██████▏   | 579/938 [06:01<04:18,  1.39it/s]

[['昼寝', 'ひるね', None, None], [None, None, 'をしている', None], ['時', 'とき', None, None], [None, None, 'に', True], ['限', 'かぎ', None, True], [None, None, 'って', True], ['電話', 'でんわ', None, None], [None, None, 'が', None], ['鳴', 'な', None, None], [None, None, 'る。', None]]
[['僕', 'ぼく', None, None], [None, None, 'がカメラを', None], ['忘', 'わす', None, None], [None, None, 'れた', None], ['日', 'ひ', None, None], [None, None, 'に', True], ['限', 'かぎ', None, True], [None, None, 'って', True], ['虹', 'にじ', None, None], [None, None, 'が', None], ['出', 'で', None, None], [None, None, 'る。', None]]
[['新曲', 'しんきょく', None, None], ['発売', 'はつばい', None, None], ['日', 'び', None, None], [None, None, 'に', True], ['限', 'かぎ', None, True], [None, None, 'って', True], ['大雨', 'おおあめ', None, None], [None, None, 'だ。', None]]
[['早口', 'はやくち', None, None], [None, None, 'の', None], ['人', 'ひと', None, None], [None, None, 'に', True], ['限', 'かぎ', None, True], [None, None, 'って', True], [None, None, 'たくさんしゃべるから、', None], ['聞', 'き', None, None], [None, None, 'き', None], ['取', 'と', None, None], [None, None, 'れない。', None]]
[['外', 'そと', None, None], [None, None, 'に', None], ['調査', 'ちょうさ', None, None], [None, None, 'へ', None], ['出', 'で', None, None], [None, None, 'かける', None], ['時', 'とき', None, None], [None, None, 'に', True], ['限', 'かぎ', None, True], [None, None, 'って', True], [None, None, '、', None], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'る。', None]]

 62%|██████▏   | 580/938 [06:01<04:00,  1.49it/s]

[[None, None, 'ラッシュアワー', None], [None, None, 'に', True], ['限', 'かぎ', None, True], [None, None, 'らず', True], [None, None, '、', None], ['電車', 'でんしゃ', None, None], [None, None, 'にはあまり', None], ['乗', 'の', None, None], [None, None, 'りたくない。', None]]
[[None, None, 'マンション', None], [None, None, 'に', True], ['限', 'かぎ', None, True], [None, None, 'らず', True], [None, None, '、', None], ['綺麗', 'きれい', None, None], [None, None, 'な', None], ['部屋', 'へや', None, None], [None, None, 'なら', None], ['住', 'す', None, None], [None, None, 'んでみたい。', None]]
[[None, None, 'オルガン', None], [None, None, 'に', True], ['限', 'かぎ', None, True], [None, None, 'らず', True], [None, None, '、', None], ['鍵盤', 'けんばん', None, None], ['楽器', 'がっき', None, None], [None, None, 'はだいたい', None], ['弾', 'ひ', None, None], [None, None, 'けます。', None]]
[['生', 'い', None, None], [None, None, 'け', None], ['花', 'ばな', None, None], [None, None, 'に', True], ['限', 'かぎ', None, True], [None, None, 'らず', True], [None, None, '、', None], ['正座', 'せいざ', None, None], [None, None, 'をするのが', None], ['苦手', 'にがて', None, None], [None, None, 'です。', None]]
[['英文', 'えいぶん', None, None], [None, None, 'に', True], ['限', 'かぎ', None, True], [None, None, 'らず', True], [None, None, '、アルファベットを', None], ['使', 'つか', None, None], [None, None, 'った', None], ['文章', 'ぶんしょう', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'きです。', None]]

 62%|██████▏   | 581/938 [06:02<04:10,  1.43it/s]

[[None, None, 'アメリア・イアハートの', None], ['消失', 'しょうしつ', None, None], [None, None, 'は', None], ['今', 'いま', None, None], [None, None, 'も', None], ['尚', 'なお', None, True], ['謎', 'なぞ', None, None], [None, None, 'である', None], [None, None, '。', None]]
[['大学院生', 'だいがくいんせい', None, None], [None, None, 'になっても', None], ['尚', 'なお', None, True], [None, None, '、', None], ['夜遊', 'よあそ', None, None], [None, None, 'びをやめない', None], ['人', 'ひと', None, None], [None, None, 'も', None], [None, None, 'いる', None], [None, None, '。', None]]
[['大工', 'だいく', None, None], [None, None, 'になっても', None], ['尚', 'なお', None, True], [None, None, '、', None], ['高', 'たか', None, None], [None, None, 'いところが', None], ['苦手', 'にがて', None, None], [None, None, 'な', None], ['人', 'ひと', None, None], [None, None, 'も', None], [None, None, 'いる', None], [None, None, 'らしい。', None]]
[['短所', 'たんしょ', None, None], [None, None, 'に', None], ['気', 'き', None, None], [None, None, 'づいても', None], ['尚', 'なお', None, True], ['認', 'みと', None, None], [None, None, 'めようとしない', None], ['人', 'ひと', None, None], [None, None, 'に', None], ['未来', 'みらい', None, None], [None, None, 'はありませんよ。', None]]
[['蒸気機関車', 'じょうききかんしゃ', None, None], [None, None, 'は', None], ['今', 'いま', None, None], [None, None, 'も', None], ['尚', 'なお', None, True], [None, None, '、', None], ['電気', 'でんき', None, None], [None, None, 'がない', None], ['地域', 'ちいき', None, None], [None, None, 'において', None], ['使用', 'しよう', None, None], [None, None, 'され', None], [None, None, 'ている', None], [None, None, '。', None]]

 62%|██████▏   | 582/938 [06:03<04:17,  1.38it/s]

[['明日', 'あした', None, None], [None, None, 'は', None], ['臨時', 'りんじ', None, None], ['休業', 'きゅうぎょう', None, None], [None, None, 'です。', None], ['尚', 'なお', None, True], [None, None, '、', None], ['定休', 'ていきゅう', None, None], ['日', 'び', None, None], [None, None, 'は', None], ['水曜日', 'すいようび', None, None], [None, None, 'です。', None]]
[['作品', 'さくひん', None, None], [None, None, 'の', None], ['提出', 'ていしゅつ', None, None], [None, None, 'は', None], ['今月', 'こんげつ', None, None], [None, None, 'いっぱいまで。', None], ['尚', 'なお', None, True], [None, None, '、テーマは', None], ['各自', 'かくじ', None, None], [None, None, 'で', None], ['考', 'かんが', None, None], [None, None, 'えること。', None]]
[['只今', 'ただいま', None, None], [None, None, 'パンを', None], ['焼', 'や', None, None], [None, None, 'いております。', None], ['尚', 'なお', None, True], [None, None, '、', None], ['出来上', 'できあ', None, None], [None, None, 'がりは', None], ['１１', 'じゅういち', None, None], ['時', 'じ', None, None], [None, None, 'を', None], ['予定', 'よてい', None, None], [None, None, 'しております。', None]]
[['説明', 'せつめい', None, None], [None, None, 'は', None], ['以上', 'いじょう', None, None], [None, None, 'です。', None], ['尚', 'なお', None, True], [None, None, '、', None], ['手続', 'てつづ', None, None], [None, None, 'きは', None], ['明後日', 'みょうごにち', None, None], [None, None, 'までにお', None], ['願', 'ねが', None, None], [None, None, 'いします。', None]]
[[None, None, 'では、これで', None], ['試験', 'しけん', None, None], [None, None, 'を', None], ['終', 'お', None, None], [None, None, 'わります。', None], ['尚', 'なお', None, True], [None, None, '、', None], ['点数', 'てんすう', None, None], [None, None, 'は', None], ['追', 'お', None, None], [None, None, 'って', None], ['発表', 'はっぴょう', None, None], [None, None, 'いたします。', None]]

 62%|██████▏   | 583/938 [06:04<04:17,  1.38it/s]

[['行列', 'ぎょうれつ', None, None], [None, None, 'に', None], ['並', 'なら', None, None], [None, None, 'ばない', None], ['限', 'かぎ', None, True], [None, None, 'り', True], [None, None, '、あのパンは', None], ['買', 'か', None, None], [None, None, 'えない。', None]]
[['意識', 'いしき', None, None], [None, None, 'して', None], ['気', 'き', None, None], [None, None, 'を', None], ['付', 'つ', None, None], [None, None, 'けない', None], ['限', 'かぎ', None, True], [None, None, 'り', True], [None, None, '、あの', None], ['癖', 'くせ', None, None], [None, None, 'は', None], ['直', 'なお', None, None], [None, None, 'らない。', None]]
[['離島', 'りとう', None, None], [None, None, 'に', None], ['漂流', 'ひょうりゅう', None, None], ['者', 'しゃ', None, None], [None, None, '：「', None], ['見', 'み', None, None], [None, None, 'る', None], ['限', 'かぎ', None, True], [None, None, 'り', True], [None, None, '、', None], ['水', 'みず', None, None], [None, None, 'しかない...」', None]]
[['休息', 'きゅうそく', None, None], [None, None, 'をとらない', None], ['限', 'かぎ', None, True], [None, None, 'り', True], [None, None, '、', None], ['体調', 'たいちょう', None, None], [None, None, 'は', None], ['回復', 'かいふく', None, None], [None, None, 'しませんよ。', None]]
[[None, None, 'あの', None], ['教', 'おし', None, None], [None, None, 'えを', None], ['心', 'こころ', None, None], [None, None, 'に', None], ['刻', 'きざ', None, None], [None, None, 'んでいる', None], ['限', 'かぎ', None, True], [None, None, 'り', True], [None, None, '、', None], ['人', 'ひと', None, None], [None, None, 'の', None], ['道', 'みち', None, None], [None, None, 'を', None], ['踏', 'ふ', None, None], [None, None, 'み', None], ['外', 'はず', None, None], [None, None, 'したりはしないはずだ。', None]]

 62%|██████▏   | 584/938 [06:04<04:21,  1.35it/s]

[[None, None, 'ワインの', None], ['渋味', 'しぶみ', None, None], [None, None, 'は', None], ['濃度', 'のうど', None, None], ['次第', 'しだい', None, True], [None, None, 'だ', None], [None, None, '。', None]]
[['成功', 'せいこう', None, None], [None, None, 'は', None], ['大抵', 'たいてい', None, None], ['努力', 'どりょく', None, None], ['次第', 'しだい', None, True], [None, None, 'だ', None], [None, None, '。', None]]
[['天気', 'てんき', None, None], ['次第', 'しだい', None, True], [None, None, 'で', True], [None, None, '、', None], ['日', 'ひ', None, None], ['帰', 'がえ', None, None], [None, None, 'りか', None], ['一泊', 'いっぱく', None, None], ['二日', 'ふつか', None, None], [None, None, 'かを', None], ['決', 'き', None, None], [None, None, 'めます。', None]]
[[None, None, 'アイデア', None], ['次第', 'しだい', None, True], [None, None, 'で', True], [None, None, '、', None], ['売上', 'うりあげ', None, None], [None, None, 'にかなりの', None], ['違', 'ちが', None, None], [None, None, 'いが', None], ['出', 'で', None, None], [None, None, 'てきます。', None]]
[['応援', 'おうえん', None, None], ['次第', 'しだい', None, True], [None, None, 'で', True], [None, None, '、', None], ['試合', 'しあい', None, None], [None, None, 'の', None], ['結果', 'けっか', None, None], [None, None, 'が', None], ['変', 'か', None, None], [None, None, 'わることもあり', None], ['得', 'え', None, None], [None, None, 'ます。', None]]

 62%|██████▏   | 585/938 [06:05<04:12,  1.40it/s]

[['膝', 'ひざ', None, None], [None, None, 'の', None], ['痛', 'いた', None, None], [None, None, 'みは', None], ['次第', 'しだい', None, True], [None, None, 'に', True], ['和', 'やわ', None, None], [None, None, 'らいでいった。', None]]
[['朝晩', 'あさばん', None, None], [None, None, 'の', None], ['冷', 'ひ', None, None], [None, None, 'え', None], ['込', 'こ', None, None], [None, None, 'みが', None], ['次第', 'しだい', None, True], [None, None, 'に', True], ['激', 'はげ', None, None], [None, None, 'しくなり、', None], ['冬', 'ふゆ', None, None], [None, None, 'の', None], ['訪', 'おとず', None, None], [None, None, 'れを', None], ['感', 'かん', None, None], [None, None, 'じた。', None]]
[['時', 'とき', None, None], [None, None, 'が', None], ['経', 'た', None, None], [None, None, 'つにつれ、', None], ['次第', 'しだい', None, True], [None, None, 'に', True], ['彼', 'かれ', None, None], [None, None, 'への', None], ['愛情', 'あいじょう', None, None], [None, None, 'は', None], ['無', 'な', None, None], [None, None, 'くなっていった。', None]]
[['薬', 'くすり', None, None], [None, None, 'を', None], ['飲', 'の', None, None], [None, None, 'んだら、', None], ['次第', 'しだい', None, True], [None, None, 'に', True], ['痛', 'いた', None, None], [None, None, 'みが', None], ['引', 'ひ', None, None], [None, None, 'いてきたよ。', None]]
[['次第', 'しだい', None, True], [None, None, 'に', True], ['雲行', 'くもゆ', None, None], [None, None, 'きが', None], ['怪', 'あや', None, None], [None, None, 'しくなり、イベントの', None], ['中止', 'ちゅうし', None, None], [None, None, 'をせざるを', None], ['得', 'え', None, None], [None, None, 'なくなった。', None]]

 62%|██████▏   | 586/938 [06:06<04:12,  1.40it/s]

[['助', 'たす', None, True], [None, None, 'け', True], ['合', 'あ', None, True], [None, None, 'ってこそ', True], [None, None, 'の', None], ['親友', 'しんゆう', None, None], [None, None, 'じゃないか。', None]]
[['全部', 'ぜんぶ', None, None], ['揃', 'そろ', None, True], [None, None, 'えてこそ', True], [None, None, 'のコレクションだ。', None]]
[['優勝', 'ゆうしょう', None, None], [None, None, 'してこそ', True], [None, None, '、', None], ['自信', 'じしん', None, None], [None, None, 'に', None], ['繋', 'つな', None, None], [None, None, 'がる。', None]]
[[None, None, 'くだらないプライドを', None], ['捨', 'す', None, True], [None, None, 'ててこそ', True], [None, None, '、', None], ['男', 'おとこ', None, None], [None, None, 'らしくなれる。', None]]
[['全員', 'ぜんいん', None, None], ['参加', 'さんか', None, None], [None, None, 'してこそ', True], [None, None, 'の', None], ['遠足', 'えんそく', None, None], [None, None, 'だ。', None]]

 63%|██████▎   | 587/938 [06:06<03:58,  1.47it/s]

[[None, None, 'どんな', None], ['役', 'やく', None, None], [None, None, 'かは', None], ['問', 'と', None, True], [None, None, 'わず', True], [None, None, '、', None], ['主役', 'しゅやく', None, None], [None, None, 'であればね。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], ['彼女', 'かのじょ', None, None], [None, None, 'と', None], ['結婚', 'けっこん', None, None], [None, None, 'したい。', None], ['手段', 'しゅだん', None, None], [None, None, 'を', True], ['問', 'と', None, True], [None, None, 'わない', True], [None, None, '。', None]]
[['買', 'か', None, None], [None, None, 'う', None], ['買', 'か', None, None], [None, None, 'わない', None], [None, None, 'を', True], ['問', 'と', None, True], [None, None, 'わず', True], [None, None, '、', None], ['商品', 'しょうひん', None, None], [None, None, 'を', None], ['試', 'ため', None, None], [None, None, 'しに', None], ['来', 'き', None, None], [None, None, 'てください。', None]]
[['好', 'す', None, None], [None, None, 'き', None], ['嫌', 'きら', None, None], [None, None, 'い', None], [None, None, 'を', True], ['問', 'と', None, True], [None, None, 'わず', True], ['探', 'さが', None, None], [None, None, 'せば、', None], ['仕事', 'しごと', None, None], [None, None, 'は', None], ['見', 'み', None, None], [None, None, 'つかります。', None]]
[['上手', 'うま', None, None], [None, None, 'い', None], ['下手', 'へた', None, None], [None, None, 'を', True], ['問', 'と', None, True], [None, None, 'わず', True], [None, None, '、', None], ['習字', 'しゅうじ', None, None], [None, None, 'の', None], ['練習', 'れんしゅう', None, None], [None, None, 'は', None], ['続', 'つづ', None, None], [None, None, 'けてください。', None]]

 63%|██████▎   | 588/938 [06:07<04:03,  1.44it/s]

[['税金', 'ぜいきん', None, None], [None, None, 'は、', None], ['高', 'たか', None, None], [None, None, 'くとも', None], ['納', 'おさ', None, None], [None, None, 'める', None], [None, None, 'より', True], ['仕方', 'しかた', None, True], [None, None, 'がない', True], [None, None, '。', None]]
[['税金', 'ぜいきん', None, None], [None, None, 'は、', None], ['納', 'おさ', None, None], [None, None, 'める', None], [None, None, 'より', True], ['仕方', 'しかた', None, True], [None, None, 'のない', True], [None, None, 'ものだ。', None]]
[[None, None, 'ミシンが', None], ['故障', 'こしょう', None, None], [None, None, 'しているから、', None], ['手', 'て', None, None], [None, None, 'で', None], ['縫', 'ぬ', None, None], [None, None, 'う', None], [None, None, 'より', True], ['仕方', 'しかた', None, True], [None, None, 'がない', True], [None, None, '。', None]]
[['見本', 'みほん', None, None], [None, None, 'がないから、', None], ['頭', 'あたま', None, None], [None, None, 'の', None], ['中', 'なか', None, None], [None, None, 'でイメージして', None], ['作', 'つく', None, None], [None, None, 'る', None], [None, None, 'より', True], ['仕方', 'しかた', None, True], [None, None, 'がない', True], [None, None, '。', None]]
[[None, None, 'マラソン', None], ['大会', 'たいかい', None, None], [None, None, 'に', None], ['出', 'で', None, None], [None, None, 'たいなら、', None], ['地道', 'じみち', None, None], [None, None, 'にトレーニングを', None], ['積', 'つ', None, None], [None, None, 'む', None], [None, None, 'より', True], ['仕方', 'しかた', None, True], [None, None, 'がない', True], [None, None, '。', None]]

 63%|██████▎   | 589/938 [06:08<04:03,  1.43it/s]

[['休息', 'きゅうそく', None, None], [None, None, 'できる', None], [None, None, 'に', True], ['越', 'こ', None, True], [None, None, 'したことはない', True], [None, None, 'が、あまりにもひまだ。', None]]
[['応援', 'おうえん', None, None], [None, None, 'してもらうこと', None], [None, None, 'に', True], ['越', 'こ', None, True], [None, None, 'したことはない', True], [None, None, 'が、ちょっとやり', None], ['過', 'す', None, None], [None, None, 'ぎです。', None]]
[['受験', 'じゅけん', None, None], [None, None, 'は', None], ['受', 'う', None, None], [None, None, 'かる', None], ['確率', 'かくりつ', None, None], [None, None, 'が', None], ['高', 'たか', None, None], [None, None, 'い', None], [None, None, 'に', True], ['越', 'こ', None, True], [None, None, 'したことはない', True], [None, None, '。', None]]
[[None, None, 'オーケストラの', None], ['楽器', 'がっき', None, None], [None, None, 'は', None], ['多', 'おお', None, None], [None, None, 'い', None], [None, None, 'に', True], ['越', 'こ', None, True], [None, None, 'したことはない', True], [None, None, 'が、', None], ['限度', 'げんど', None, None], [None, None, 'がある。', None]]
[['基礎', 'きそ', None, None], [None, None, 'がしっかりしている', None], [None, None, 'に', True], ['越', 'こ', None, True], [None, None, 'したことはない', True], [None, None, 'が、', None], ['基礎', 'きそ', None, None], [None, None, 'にばかり', None], ['時間', 'じかん', None, None], [None, None, 'をかけられない。', None]]

 63%|██████▎   | 590/938 [06:09<04:05,  1.42it/s]

[['要', 'よう', None, True], [None, None, 'するに', True], ['何', 'なん', None, None], [None, None, 'でもいいよね？', None]]
[['要', 'よう', None, True], [None, None, 'するに', True], [None, None, '、あなたは', None], ['反省', 'はんせい', None, None], [None, None, 'していないということですよ。', None]]
[['要', 'よう', None, True], [None, None, 'するに', True], [None, None, '、', None], ['発想', 'はっそう', None, None], [None, None, 'が', None], ['貧弱', 'ひんじゃく', None, None], [None, None, 'だということでしょう。', None]]
[['要', 'よう', None, True], [None, None, 'するに', True], [None, None, '、', None], ['期限', 'きげん', None, None], [None, None, 'を', None], ['延', 'の', None, None], [None, None, 'ばすことは', None], ['許', 'ゆる', None, None], [None, None, 'されないということです。', None]]
[['要', 'よう', None, True], [None, None, 'するに', True], [None, None, '、', None], ['乗換', 'のりかえ', None, None], [None, None, 'を', None], ['間違', 'まちが', None, None], [None, None, 'えて', None], ['遅刻', 'ちこく', None, None], [None, None, 'したということですね？', None]]

 63%|██████▎   | 591/938 [06:09<04:07,  1.40it/s]

[[None, None, 'サンプルを', None], ['見', 'み', None, True], [None, None, 'てからでないと', True], [None, None, '、', None], ['買', 'か', None, None], [None, None, 'うかどうかは', None], ['決', 'き', None, None], [None, None, 'められ', None], [None, None, 'ません', None], [None, None, '。', None]]
[['猫舌', 'ねこじた', None, None], [None, None, 'なので、', None], ['冷', 'さ', None, True], [None, None, 'めてからでないと', True], ['飲', 'の', None, None], [None, None, 'め', None], [None, None, 'ない', None], [None, None, '。', None]]
[['電源', 'でんげん', None, None], [None, None, 'を', None], ['切', 'き', None, True], [None, None, 'ってからでないと', True], [None, None, '、コンセントを', None], ['抜', 'ぬ', None, None], [None, None, 'いてはいけ', None], [None, None, 'ません', None], [None, None, '。', None]]
[[None, None, 'サークルに', None], ['入', 'はい', None, True], [None, None, 'ってからでないと', True], [None, None, '、', None], ['活動', 'かつどう', None, None], [None, None, 'に', None], ['参加', 'さんか', None, None], [None, None, 'でき', None], [None, None, 'ない', None], [None, None, '。', None]]
[['撮影', 'さつえい', None, None], [None, None, 'してからでないと', True], [None, None, '、ギャラは', None], ['入', 'はい', None, None], [None, None, 'り', None], [None, None, 'ません', None], [None, None, '。', None]]

 63%|██████▎   | 592/938 [06:10<03:52,  1.49it/s]

[['貯金', 'ちょきん', None, None], [None, None, 'すれば', None], ['買', 'か', None, True], [None, None, 'えなくはない', True], [None, None, '。', None]]
[[None, None, 'かなり', None], ['固', 'かた', None, None], [None, None, 'い', None], ['木', 'き', None, None], [None, None, 'だが、このカンナで', None], ['削', 'けず', None, True], [None, None, 'れなくはない', True], [None, None, '。', None]]
[['難', 'むずか', None, None], [None, None, 'しそうだが、', None], ['自分', 'じぶん', None, None], [None, None, 'で', None], ['組', 'く', None, True], [None, None, 'み', True], ['立', 'た', None, True], [None, None, 'てられなくはない', True], [None, None, '。', None]]
[[None, None, 'その', None], ['意見', 'いけん', None, None], [None, None, 'を', None], ['考', 'かんが', None, None], [None, None, 'えた', None], ['上', 'うえ', None, None], [None, None, 'で、', None], ['賛成', 'さんせい', None, None], [None, None, 'できなくはない', True], [None, None, '。', None]]
[['原理', 'げんり', None, None], [None, None, 'は', None], ['分', 'わ', None, True], [None, None, 'からなくはない', True], [None, None, 'が、すべてを', None], ['理解', 'りかい', None, None], [None, None, 'するのは', None], ['難', 'むずか', None, None], [None, None, 'しい。', None]]

 63%|██████▎   | 593/938 [06:11<03:57,  1.45it/s]

[[None, None, 'やってみないことには', True], [None, None, '、', None], ['出来', 'でき', None, None], [None, None, 'るかどうか', None], ['分', 'わ', None, None], [None, None, 'から', None], [None, None, 'ない', None], [None, None, '。', None]]
[['髭', 'ひげ', None, None], [None, None, 'を', None], ['剃', 'そ', None, True], [None, None, 'らないことには', True], [None, None, '、', None], ['仕事', 'しごと', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'け', None], [None, None, 'ない', None], [None, None, '。', None]]
[['夫婦', 'ふうふ', None, None], [None, None, 'では', None], ['仲良', 'なかよ', None, None], [None, None, 'く', None], [None, None, 'しないことには', True], [None, None, '、うまくいか', None], [None, None, 'ない', None], [None, None, '。', None]]
[['田植', 'たう', None, None], [None, None, 'えを', None], [None, None, 'しないことには', True], [None, None, '、', None], ['米', 'こめ', None, None], [None, None, 'を', None], ['収穫', 'しゅうかく', None, None], [None, None, 'でき', None], [None, None, 'ません', None], [None, None, '。', None]]
[['退院', 'たいいん', None, None], [None, None, 'しないことには', True], [None, None, '、', None], ['仕事', 'しごと', None, None], ['復帰', 'ふっき', None, None], [None, None, 'でき', None], [None, None, 'ない', None], [None, None, '。', None]]

 63%|██████▎   | 594/938 [06:11<03:43,  1.54it/s]

[['悔', 'くや', None, None], [None, None, 'しすぎて、', None], ['飲', 'の', None, True], [None, None, 'まないではいられない', True], [None, None, '。', None]]
[[None, None, 'いい', None], ['金魚', 'きんぎょ', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'つけてしまった。', None], ['買', 'か', None, True], [None, None, 'わないではいられない', True], [None, None, '。', None]]
[['架空', 'かくう', None, None], ['請求', 'せいきゅう', None, None], [None, None, 'され、', None], ['怒', 'おこ', None, True], [None, None, 'らないではいられない', True], [None, None, '。', None]]
[['困', 'こま', None, None], [None, None, 'ったことがあって、', None], ['神様', 'かみさま', None, None], [None, None, 'に', None], ['頼', 'たよ', None, True], [None, None, 'らないではいられない', True], [None, None, '。', None]]
[['引退', 'いんたい', None, None], ['試合', 'じあい', None, None], [None, None, 'に', None], ['負', 'ま', None, None], [None, None, 'けて、', None], ['泣', 'な', None, True], [None, None, 'かないではいられません', True], [None, None, '。', None]]

 63%|██████▎   | 595/938 [06:12<03:48,  1.50it/s]

[['家賃', 'やちん', None, None], [None, None, 'を', None], ['月末', 'げつまつ', None, None], [None, None, 'までに', None], ['払', 'はら', None, True], [None, None, 'わねばならない', True], [None, None, '。', None]]
[['後輩', 'こうはい', None, None], [None, None, 'の', None], ['意見', 'いけん', None, None], [None, None, 'もちゃんと', None], ['聞', 'き', None, True], [None, None, 'かねばならない', True], [None, None, '。', None]]
[['根本', 'こんぽん', None, None], ['的', 'てき', None, None], [None, None, 'な', None], ['構造', 'こうぞう', None, None], [None, None, 'から', None], ['見直', 'みなお', None, True], [None, None, 'さねばならない', True], [None, None, '。', None]]
[['見学', 'けんがく', None, None], [None, None, 'した', None], ['感想', 'かんそう', None, None], [None, None, 'を', None], ['書', 'か', None, None], [None, None, 'いて', None], ['提出', 'ていしゅつ', None, None], [None, None, 'せねばならない', True], [None, None, '。', None]]
[['公衆', 'こうしゅう', None, None], [None, None, 'の', None], ['面前', 'めんぜん', None, None], [None, None, 'ではちゃんと', None], ['秩序', 'ちつじょ', None, None], [None, None, 'を', None], ['保', 'たも', None, True], [None, None, 'たねばならない', True], [None, None, '。', None]]

 64%|██████▎   | 596/938 [06:13<03:50,  1.49it/s]

[['勉強', 'べんきょう', None, None], [None, None, 'をや', None], [None, None, 'り', None], [None, None, 'たまえ', True], [None, None, '。', None]]
[['上司', 'じょうし', None, None], [None, None, '：「これを、', None], ['明日', 'あした', None, None], [None, None, 'までに', None], ['終', 'お', None, None], [None, None, 'え', None], [None, None, 'たまえ', True], [None, None, '。」', None]]
[[None, None, '「', None], ['神様', 'かみさま', None, None], [None, None, '、', None], ['豊穣', 'ほうじょう', None, None], [None, None, 'の', None], ['願', 'ねが', None, None], [None, None, 'いをかな', None], [None, None, 'え', None], [None, None, 'たまえ', True], [None, None, '。」', None]]
[[None, None, 'オフィスの', None], ['中', 'なか', None, None], [None, None, 'で', None], [None, None, '：「', None], ['次', 'つぎ', None, None], [None, None, 'の', None], ['人', 'ひと', None, None], [None, None, '、', None], ['入', 'はい', None, None], [None, None, 'り', None], [None, None, 'たまえ', True], [None, None, '。」', None]]
[['Ａ', 'エー', None, None], [None, None, '：「', None], ['何', 'なん', None, None], [None, None, 'て、', None], ['言', 'い', None, None], [None, None, 'ったの。」', None], ['Ｂ', 'ビー', None, None], [None, None, '：「お', None], ['前', 'まえ', None, None], [None, None, 'にうんざりだ！うちの', None], ['会社', 'かいしゃ', None, None], [None, None, 'をとっとと', None], ['辞', 'や', None, None], [None, None, 'め', None], [None, None, 'たまえ', True], [None, None, '！って', None], ['言', 'い', None, None], [None, None, 'ったんだよ。」', None]]

 64%|██████▎   | 597/938 [06:13<03:59,  1.42it/s]

[[None, None, 'ひなさん', None], [None, None, '：「すべての', None], ['食', 'た', None, None], [None, None, 'べ', None], ['物', 'もの', None, None], [None, None, 'のうちで', True], [None, None, 'イクラが', None], ['一番', 'いちばん', None, None], ['好', 'す', None, None], [None, None, 'きです。」', None]]
[['記事', 'きじ', None, None], [None, None, '：「', None], ['１９５', 'ひゃくきゅうじゅうご', None, None], ['国', 'こく', None, None], [None, None, 'のうちで', True], ['一番', 'いちばん', None, None], ['狭', 'せま', None, None], [None, None, 'いのはバチカンだ。」', None]]
[[None, None, '「', None], ['一万人', 'いちまんにん', None, None], [None, None, 'のうち', True], ['一人', 'ひとり', None, None], [None, None, 'ぐらいが', None], ['成功', 'せいこう', None, None], [None, None, 'できるそうだ。」', None]]
[['記事', 'きじ', None, None], [None, None, '：「', None], ['金属', 'きんぞく', None, None], [None, None, 'のうちで', True], ['最', 'もっと', None, None], [None, None, 'も', None], ['一般的', 'いっぱんてき', None, None], [None, None, 'なものはアルミニウムだ。」', None]]
[[None, None, '「', None], ['山', 'やま', None, None], [None, None, 'のように', None], ['積', 'つ', None, None], [None, None, 'み', None], ['重', 'かさ', None, None], [None, None, 'ねた', None], ['ＣＤ', 'シーディー', None, None], [None, None, 'のうち', True], ['１枚', 'いちまい', None, None], [None, None, 'ぐらいは', None], ['聞', 'き', None, None], [None, None, 'く', None], ['価値', 'かち', None, None], [None, None, 'があるかもしれない。」', None]]

 64%|██████▍   | 598/938 [06:14<03:43,  1.52it/s]

[[None, None, 'ツバメは', None], ['飛行', 'ひこう', None, None], [None, None, 'しつつ', True], [None, None, '、', None], ['寝', 'ね', None, None], [None, None, 'ることができる。', None]]
[['布団', 'ふとん', None, None], [None, None, 'を', None], [None, None, 'しきつつ', True], [None, None, 'テレビに', None], ['見入', 'みい', None, None], [None, None, 'ってしまった。', None]]
[['集金', 'しゅうきん', None, None], [None, None, 'しつつ', True], [None, None, '、', None], ['空', 'あ', None, None], [None, None, 'き', None], ['家', 'や', None, None], [None, None, 'の', None], ['調査', 'ちょうさ', None, None], [None, None, 'もしています。', None]]
[['育児', 'いくじ', None, None], [None, None, 'を', None], [None, None, 'しつつ', True], [None, None, '、フルタイムで', None], ['働', 'はたら', None, None], [None, None, 'くのは', None], ['大変', 'たいへん', None, None], [None, None, 'なことです。', None]]
[['父', 'ちち', None, None], [None, None, 'の', None], ['足跡', 'あしあと', None, None], [None, None, 'を', None], [None, None, 'たどりつつ', True], [None, None, '、', None], ['自分', 'じぶん', None, None], [None, None, 'の', None], ['生', 'い', None, None], [None, None, 'き', None], ['方', 'かた', None, None], [None, None, 'を', None], ['探', 'さが', None, None], [None, None, 'している。', None]]

 64%|██████▍   | 599/938 [06:14<03:35,  1.57it/s]

[['斜', 'なな', None, None], [None, None, 'めに', None], [None, None, 'なりつつも', True], [None, None, 'なんとか', None], ['持', 'も', None, None], [None, None, 'ちこたえたジェンガ。', None]]
[['上', 'うえ', None, None], [None, None, 'を', None], ['狙', 'ねら', None, True], [None, None, 'いつつも', True], [None, None, '、まるで', None], ['狙', 'ねら', None, None], [None, None, 'っていないかのような', None], ['素振', 'すぶ', None, None], [None, None, 'りをしています。', None]]
[['南極点', 'なんきょくてん', None, None], ['遠征', 'えんせい', None, None], [None, None, 'はよく', None], ['備', 'そな', None, True], [None, None, 'えつつも', True], [None, None, '、', None], ['失敗', 'しっぱい', None, None], [None, None, 'した。', None]]
[['車庫', 'しゃこ', None, None], [None, None, 'のシャッターを', None], ['開', 'あ', None, True], [None, None, 'けつつも', True], [None, None, '、まだ', None], ['行', 'い', None, None], [None, None, 'こうか', None], ['行', 'い', None, None], [None, None, 'くまいか', None], ['迷', 'まよ', None, None], [None, None, 'っていた。', None]]
[['船', 'ふね', None, None], [None, None, 'は、', None], ['沈', 'しず', None, None], [None, None, 'みそうに', None], [None, None, 'なりつつも', True], [None, None, '、なんとか', None], ['港', 'みなと', None, None], [None, None, 'まで', None], ['帰', 'かえ', None, None], [None, None, 'って', None], ['来', 'き', None, None], [None, None, 'た。', None]]

 64%|██████▍   | 600/938 [06:15<03:50,  1.47it/s]

[['応援', 'おうえん', None, None], [None, None, 'に', True], ['際', 'さい', None, True], [None, None, 'して', True], ['守', 'まも', None, None], [None, None, 'ってほしいルールがあります。', None]]
[['移転', 'いてん', None, None], [None, None, 'に', True], ['際', 'さい', None, True], [None, None, 'して', True], ['必要', 'ひつよう', None, None], [None, None, 'なものがあれば', None], ['言', 'い', None, None], [None, None, 'ってね。', None]]
[[None, None, '「', None], ['受験', 'じゅけん', None, None], [None, None, 'に', True], ['際', 'さい', None, True], [None, None, 'して', True], [None, None, 'の', None], ['注意', 'ちゅうい', None, None], ['事項', 'じこう', None, None], [None, None, '」をよくお', None], ['読', 'よ', None, None], [None, None, 'みください。', None]]
[['車', 'くるま', None, None], [None, None, 'を', None], ['追', 'お', None, None], [None, None, 'い', None], ['越', 'こ', None, None], [None, None, 'す', None], [None, None, 'に', True], ['際', 'さい', None, True], [None, None, 'して', True], ['気', 'き', None, None], [None, None, 'をつけるべきことがある。', None]]
[['独立', 'どくりつ', None, None], [None, None, 'する', None], [None, None, 'に', True], ['際', 'さい', None, True], [None, None, 'して', True], [None, None, '、', None], ['先輩', 'せんぱい', None, None], [None, None, 'のご', None], ['意見', 'いけん', None, None], [None, None, 'をいただけませんか？', None]]

 64%|██████▍   | 601/938 [06:16<04:16,  1.31it/s]

[['炎天下', 'えんてんか', None, None], [None, None, 'で', None], ['働', 'はたら', None, None], [None, None, 'く', None], ['際', 'さい', None, True], [None, None, 'に', True], [None, None, 'は', None], ['帽子', 'ぼうし', None, None], [None, None, 'などを', None], ['持', 'も', None, None], [None, None, 'ってきてください。', None]]
[['休講', 'きゅうこう', None, None], [None, None, 'の', None], ['際', 'さい', None, True], [None, None, 'に', True], [None, None, 'は', None], ['連絡', 'れんらく', None, None], [None, None, 'しますから、ちゃんと', None], ['授業', 'じゅぎょう', None, None], [None, None, 'に', None], ['出', 'で', None, None], [None, None, 'てください。', None]]
[['稽古', 'けいこ', None, None], [None, None, 'の', None], ['際', 'さい', None, True], [None, None, 'に', True], ['教', 'おそ', None, None], [None, None, 'わったことを', None], ['本番', 'ほんばん', None, None], [None, None, 'でどこまで', None], ['発揮', 'はっき', None, None], [None, None, 'できるかが', None], ['問題', 'もんだい', None, None], [None, None, 'だ。', None]]
[['警備', 'けいび', None, None], [None, None, 'の', None], ['際', 'さい', None, True], [None, None, 'に', True], ['注意', 'ちゅうい', None, None], [None, None, 'してほしいことを', None], ['書', 'か', None, None], [None, None, 'き', None], ['出', 'だ', None, None], [None, None, 'しておきましたので、', None], ['確認', 'かくにん', None, None], [None, None, 'してください。', None]]
[['血圧', 'けつあつ', None, None], [None, None, 'を', None], ['測', 'はか', None, None], [None, None, 'る', None], ['際', 'さい', None, True], [None, None, 'に', True], [None, None, 'は、できるだけ', None], ['平常', 'へいじょう', None, None], ['心', 'しん', None, None], [None, None, 'でいたほうがいい。', None]]

 64%|██████▍   | 602/938 [06:17<04:18,  1.30it/s]

[[None, None, 'レーザーの', None], ['試験', 'しけん', None, None], [None, None, 'に', True], ['当', 'あ', None, True], [None, None, 'たり', True], [None, None, '、', None], ['必', 'かなら', None, None], [None, None, 'ず', None], ['保護', 'ほご', None, None], [None, None, 'メガネを', None], ['着用', 'ちゃくよう', None, None], [None, None, 'してください。', None]]
[['綱渡', 'つなわた', None, None], [None, None, 'りをする', None], [None, None, 'に', True], ['当', 'あ', None, True], [None, None, 'たり', True], [None, None, '、', None], ['命綱', 'いのちづな', None, None], [None, None, 'をつけてもらった。', None]]
[['彫刻', 'ちょうこく', None, None], [None, None, 'を', None], ['彫', 'ほ', None, None], [None, None, 'る', None], [None, None, 'に', True], ['当', 'あ', None, True], [None, None, 'たり', True], [None, None, '、', None], ['彫刻', 'ちょうこく', None, None], ['刀', 'とう', None, None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'い', None], ['換', 'か', None, None], [None, None, 'えた。', None]]
[['課長', 'かちょう', None, None], [None, None, 'の', None], ['退職', 'たいしょく', None, None], [None, None, 'に', True], ['当', 'あ', None, True], [None, None, 'たって', True], [None, None, '、お', None], ['別', 'わか', None, None], [None, None, 'れの', None], ['一言', 'ひとこと', None, None], [None, None, 'を', None], ['述', 'の', None, None], [None, None, 'べさせていただきます。', None]]
[[None, None, 'パスポートの', None], ['申請', 'しんせい', None, None], [None, None, 'に', True], ['当', 'あ', None, True], [None, None, 'たり', True], [None, None, '、', None], ['顔', 'かお', None, None], ['写真', 'じゃしん', None, None], [None, None, 'を', None], ['必', 'かなら', None, None], [None, None, 'ず', None], ['持', 'も', None, None], [None, None, 'ってきてください。', None]]

 64%|██████▍   | 603/938 [06:18<04:18,  1.29it/s]

[['子供', 'こども', None, None], [None, None, 'の', None], ['独立', 'どくりつ', None, None], [None, None, 'を', True], ['契機', 'けいき', None, True], [None, None, 'に', True], ['家', 'いえ', None, None], [None, None, 'を', None], ['改造', 'かいぞう', None, None], [None, None, 'することにした。', None]]
[[None, None, 'テレビ', None], ['取材', 'しゅざい', None, None], [None, None, 'を', True], ['契機', 'けいき', None, True], [None, None, 'に', True], [None, None, '、（レストランの）', None], ['人気', 'にんき', None, None], [None, None, 'が', None], ['加速', 'かそく', None, None], [None, None, 'していった。', None]]
[['転職', 'てんしょく', None, None], [None, None, 'を', True], ['契機', 'けいき', None, True], [None, None, 'に', True], ['落', 'お', None, None], [None, None, 'ち', None], ['着', 'つ', None, None], [None, None, 'きを', None], ['取', 'と', None, None], [None, None, 'り', None], ['戻', 'もど', None, None], [None, None, 'した。', None]]
[[None, None, 'あんなに', None], ['大人', 'おとな', None, None], [None, None, 'しかった', None], ['彼', 'かれ', None, None], [None, None, 'が、', None], ['引越', 'ひっこ', None, None], [None, None, 'し', None], [None, None, 'を', True], ['契機', 'けいき', None, True], [None, None, 'に', True], [None, None, 'よく', None], ['話', 'はな', None, None], [None, None, 'すようになった。', None]]
[['温泉', 'おんせん', None, None], [None, None, 'を', None], ['掘', 'ほ', None, None], [None, None, 'り', None], ['当', 'あ', None, None], [None, None, 'てた', None], [None, None, 'こと', None], [None, None, 'を', True], ['契機', 'けいき', None, True], [None, None, 'に', True], ['大金持', 'おおがねも', None, None], [None, None, 'ちになりました。', None]]

 64%|██████▍   | 604/938 [06:19<04:13,  1.32it/s]

[[None, None, 'おかげさまで、', None], ['病気', 'びょうき', None, None], [None, None, 'は', None], ['治', 'なお', None, True], [None, None, 'りつつあります', True], [None, None, '。', None]]
[['契約', 'けいやく', None, None], [None, None, 'しつつあった', True], [None, None, 'のに', None], ['決裂', 'けつれつ', None, None], [None, None, 'した。', None], ['惜', 'お', None, None], [None, None, 'しいことをした。', None]]
[['大', 'だい', None, None], ['流行', 'りゅうこう', None, None], [None, None, 'したインフルエンザの', None], ['猛威', 'もうい', None, None], [None, None, 'も、', None], ['今', 'いま', None, None], [None, None, 'は', None], ['落', 'お', None, True], [None, None, 'ち', True], ['着', 'つ', None, True], [None, None, 'きつつある', True], [None, None, '。', None]]
[[None, None, 'アフリカの', None], ['野生', 'やせい', None, None], ['動物', 'どうぶつ', None, None], [None, None, 'の', None], ['数', 'かず', None, None], [None, None, 'が', None], ['減', 'へ', None, True], [None, None, 'りつつある', True], [None, None, 'のは', None], ['残念', 'ざんねん', None, None], [None, None, 'だ。', None]]
[['在庫', 'ざいこ', None, None], ['過剰', 'かじょう', None, None], [None, None, 'に', None], [None, None, 'なりつつある', True], [None, None, 'から、', None], ['値下', 'ねさ', None, None], [None, None, 'げしてでも', None], ['売', 'う', None, None], [None, None, 'ってください。', None]]

 64%|██████▍   | 605/938 [06:19<04:08,  1.34it/s]

[['犬', 'いぬ', None, None], [None, None, 'を', None], ['散歩', 'さんぽ', None, None], [None, None, 'させている', None], [None, None, 'ところに', True], [None, None, 'Tさんに', None], ['出', 'で', None, None], [None, None, 'くわした。', None]]
[[None, None, 'ちょうどジャガイモの', None], ['皮', 'かわ', None, None], [None, None, 'をむこうとしている', None], [None, None, 'ところに', True], ['電話', 'でんわ', None, None], [None, None, 'が', None], ['鳴', 'な', None, None], [None, None, 'った。', None]]
[[None, None, 'セメントを', None], ['入', 'い', None, None], [None, None, 'れている', None], [None, None, 'ところへ', True], ['猫', 'ねこ', None, None], [None, None, 'がやって', None], ['来', 'き', None, None], [None, None, 'て', None], ['足跡', 'あしあと', None, None], [None, None, 'を', None], ['付', 'つ', None, None], [None, None, 'けた。', None]]
[['店', 'みせ', None, None], [None, None, 'を', None], ['閉', 'し', None, None], [None, None, 'めている', None], [None, None, 'ところへ', True], [None, None, 'お', None], ['客', 'きゃく', None, None], [None, None, 'さんが', None], ['来', 'き', None, None], [None, None, 'ちゃった。', None]]
[['車', 'くるま', None, None], [None, None, 'を', None], ['洗', 'あら', None, None], [None, None, 'っていた', None], [None, None, 'ところに', True], [None, None, 'ウチの', None], ['犬', 'いぬ', None, None], [None, None, 'がやってきて、', None], ['車', 'くるま', None, None], [None, None, 'にオシッコをした。', None]]

 65%|██████▍   | 606/938 [06:20<03:48,  1.45it/s]

[['焦', 'こ', None, None], [None, None, 'がす', None], [None, None, 'か', None], ['焦', 'こ', None, None], [None, None, 'がさ', None], [None, None, 'ない', None], [None, None, 'かの', True], ['内', 'うち', None, True], [None, None, 'に', True], [None, None, '、', None], ['肉', 'にく', None, None], [None, None, 'を', None], ['取', 'と', None, None], [None, None, 'るのが', None], ['僕', 'ぼく', None, None], [None, None, 'の', None], ['流儀', 'りゅうぎ', None, None], [None, None, '。', None]]
[['御馳走', 'ごちそう', None, None], [None, None, 'をいただく', None], [None, None, 'か', None], [None, None, 'いただか', None], [None, None, 'ない', None], [None, None, 'かの', True], ['内', 'うち', None, True], [None, None, 'に', True], [None, None, '、', None], ['帰', 'かえ', None, None], [None, None, 'る', None], ['時間', 'じかん', None, None], [None, None, 'になってしまった。', None]]
[['削除', 'さくじょ', None, None], [None, None, 'される', None], [None, None, 'か', None], [None, None, 'され', None], [None, None, 'ない', None], [None, None, 'かの', True], ['内', 'うち', None, True], [None, None, 'に', True], [None, None, '、', None], ['自', 'みずか', None, None], [None, None, 'ら', None], ['手', 'て', None, None], [None, None, 'を', None], ['引', 'ひ', None, None], [None, None, 'いた', None], ['方', 'ほう', None, None], [None, None, 'がいい。', None]]
[['清書', 'せいしょ', None, None], [None, None, 'する', None], [None, None, 'か', None], [None, None, 'し', None], [None, None, 'ない', None], [None, None, 'かの', True], ['内', 'うち', None, True], [None, None, 'に', True], [None, None, '、', None], ['下書', 'したが', None, None], [None, None, 'きを', None], ['紛失', 'ふんしつ', None, None], [None, None, 'してしまいました。', None]]
[[None, None, ' ', None], ['言葉', 'ことば', None, None], [None, None, 'が', None], ['終', 'お', None, None], [None, None, 'わる', None], [None, None, 'か', None], ['終', 'お', None, None], [None, None, 'わら', None], [None, None, 'ない', None], [None, None, 'かの', True], ['内', 'うち', None, True], [None, None, 'に', True], [None, None, '、', None], ['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['意識', 'いしき', None, None], [None, None, 'を', None], ['失', 'うしな', None, None], [None, None, 'った。', None]]

 65%|██████▍   | 607/938 [06:21<03:58,  1.39it/s]

[['女', 'おんな', None, None], [None, None, 'の', None], ['子', 'こ', None, None], [None, None, 'の', None], ['噂話', 'うわさばなし', None, None], [None, None, '：「さっきあいつ、', None], ['来', 'き', None, True], ['掛', 'が', None, True], [None, None, 'けに', True], ['妙', 'みょう', None, None], [None, None, 'なことを', None], ['言', 'い', None, None], [None, None, 'ってたね。」', None]]
[['友達', 'ともだち', None, None], [None, None, 'との', None], ['話', 'はなし', None, None], [None, None, '：「', None], ['帰', 'かえ', None, True], [None, None, 'り', True], ['掛', 'が', None, True], [None, None, 'けに', True], [None, None, 'タイコさんを', None], ['誘', 'さそ', None, None], [None, None, 'って', None], ['一緒', 'いっしょ', None, None], [None, None, 'に', None], ['戻', 'もど', None, None], [None, None, 'ろうか。」', None]]
[['先生', 'せんせい', None, None], [None, None, 'は', None], ['生徒', 'せいと', None, None], [None, None, 'と', None], ['話', 'はな', None, None], [None, None, 'している', None], [None, None, '：「タカスさん、このプリントを', None], ['帰', 'かえ', None, True], [None, None, 'り', True], ['掛', 'が', None, True], [None, None, 'けに', True], [None, None, 'アイサカさんに', None], ['持', 'も', None, None], [None, None, 'って', None], ['行', 'い', None, None], [None, None, 'ってください。」', None]]
[[None, None, 'ライトノベル', None], [None, None, '：「', None], ['彼', 'かれ', None, None], [None, None, 'はスーパーへの', None], ['行', 'い', None, True], [None, None, 'き', True], ['掛', 'が', None, True], [None, None, 'けに', True], ['何', 'なに', None, None], [None, None, 'かを', None], ['思', 'おも', None, None], [None, None, 'い', None], ['出', 'だ', None, None], [None, None, 'したように', None], ['突然', 'とつぜん', None, None], ['止', 'と', None, None], [None, None, 'まり', None], ['速', 'はや', None, None], [None, None, 'く', None], ['家', 'いえ', None, None], [None, None, 'に', None], ['帰', 'かえ', None, None], [None, None, 'った。」', None]]
[['病気', 'びょうき', None, None], [None, None, 'の', None], ['友達', 'ともだち', None, None], [None, None, 'の', None], ['見舞', 'みま', None, None], [None, None, 'いに', None], ['行', 'い', None, None], [None, None, 'く', None], ['時', 'とき', None, None], [None, None, '、', None], ['友達', 'ともだち', None, None], [None, None, 'との', None], ['話', 'はなし', None, None], [None, None, '：「', None], ['病院', 'びょういん', None, None], [None, None, 'への', None], ['行', 'い', None, True], [None, None, 'き', True], ['掛', 'が', None, True], [None, None, 'けに', True], ['花屋', 'はなや', None, None], [None, None, 'に', None], ['寄', 'よ', None, None], [None, None, 'って', None], ['花束', 'はなたば', None, None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'おう。」', None]]

 65%|██████▍   | 608/938 [06:21<04:13,  1.30it/s]

[['黙', 'だま', None, True], [None, None, 'っていては', True], [None, None, '、', None], ['相手', 'あいて', None, None], [None, None, 'に', None], ['気持', 'きも', None, None], [None, None, 'ちが', None], ['伝', 'つた', None, None], [None, None, 'わらないんじゃない？', None]]
[['来', 'く', None, None], [None, None, 'るのが', None], ['遅', 'おそ', None, None], [None, None, 'すぎます。', None], ['先', 'さき', None, None], [None, None, 'に', None], ['始', 'はじ', None, True], [None, None, 'めていては', True], [None, None, 'いけませんか？', None]]
[['力', 'ちから', None, None], [None, None, 'を', None], ['抜', 'ぬ', None, True], [None, None, 'いていては', True], ['持', 'も', None, None], [None, None, 'てない。もっと', None], ['力', 'ちから', None, None], [None, None, 'を', None], ['入', 'い', None, None], [None, None, 'れて！', None]]
[['暖房', 'だんぼう', None, None], [None, None, 'を', None], [None, None, 'つけていては', True], ['暑', 'あつ', None, None], [None, None, 'すぎる。もう', None], ['春', 'はる', None, None], [None, None, 'なんだから。', None]]
[[None, None, 'そんな', None], ['歩', 'ある', None, None], [None, None, 'き', None], ['方', 'かた', None, None], [None, None, 'を', None], [None, None, 'していては', True], [None, None, '、ペンギンかと', None], ['思', 'おも', None, None], [None, None, 'われますよ。', None]]

 65%|██████▍   | 609/938 [06:22<03:57,  1.39it/s]

[['絵', 'え', None, None], [None, None, 'の', None], ['具', 'ぐ', None, None], [None, None, 'をつけてしまう', None], [None, None, 'ところだった', True], [None, None, '。', None]]
[['危', 'あや', None, None], [None, None, 'うく', None], ['期限', 'きげん', None, None], [None, None, 'が', None], ['切', 'き', None, None], [None, None, 'れてしまう', None], [None, None, 'ところだった', True], [None, None, '。', None]]
[['今', 'いま', None, None], [None, None, 'から', None], ['関西弁', 'かんさいべん', None, None], [None, None, 'を', None], ['教', 'おそ', None, None], [None, None, 'わる', None], [None, None, 'ところだった', True], [None, None, 'のに。', None]]
[['出掛', 'でか', None, None], [None, None, 'ける', None], [None, None, 'ところだった', True], [None, None, 'が、', None], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'ってきたのでやめました。', None]]
[['捕', 'つか', None, None], [None, None, 'まえた', None], ['犯人', 'はんにん', None, None], [None, None, 'を', None], ['危', 'あや', None, None], [None, None, 'うく', None], ['逃', 'のが', None, None], [None, None, 'す', None], [None, None, 'ところだった', True], [None, None, '。', None]]

 65%|██████▌   | 610/938 [06:23<03:55,  1.39it/s]

[['休', 'やす', None, None], [None, None, 'みの', None], ['日', 'ひ', None, None], [None, None, 'はたくさん', None], ['寝', 'ね', None, None], [None, None, 'たい。レジャー', None], [None, None, 'どころではない', True], [None, None, '。', None]]
[['腰', 'こし', None, None], [None, None, 'を', None], ['痛', 'いた', None, None], [None, None, 'めてしまったから、マラソン', None], [None, None, 'どころではありません', True], [None, None, '。', None]]
[['熱', 'ねつ', None, None], [None, None, 'があるというのに、', None], ['遊園', 'ゆうえん', None, None], ['地', 'ち', None, None], [None, None, 'どころではない', True], [None, None, 'よ。', None]]
[[None, None, 'なんとか', None], ['通', 'つう', None, None], [None, None, 'じればいい。アクセント', None], [None, None, 'どころではありません', True], [None, None, '。', None]]
[['急用', 'きゅうよう', None, None], [None, None, 'が', None], ['入', 'はい', None, None], [None, None, 'ったので、お', None], ['出掛', 'でか', None, None], [None, None, 'け', None], [None, None, 'どころではなくなった', True], [None, None, '。', None]]

 65%|██████▌   | 611/938 [06:24<03:56,  1.38it/s]

[['歯医者', 'はいしゃ', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'くのは', None], ['二年', 'にねん', None, None], ['振', 'ぶ', None, True], [None, None, 'り', True], [None, None, 'だ。', None]]
[['十年', 'じゅうねん', None, None], ['振', 'ぶ', None, True], [None, None, 'りに', True], [None, None, '、', None], ['高校', 'こうこう', None, None], [None, None, 'の', None], ['友達', 'ともだち', None, None], [None, None, 'に', None], ['会', 'あ', None, None], [None, None, 'った。', None]]
[['２', 'に', None, None], ['週間', 'しゅうかん', None, None], ['振', 'ぶ', None, True], [None, None, 'りの', True], ['寿司', 'すし', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べた。', None]]
[['三', 'さん', None, None], ['年', 'ねん', None, None], ['振', 'ぶ', None, True], [None, None, 'りに', True], ['日本食', 'にほんしょく', None, None], [None, None, 'を', None], ['味', 'あじ', None, None], [None, None, 'わえて', None], ['幸', 'しあわ', None, None], [None, None, 'せです。', None]]
[['十日', 'とおか', None, None], ['振', 'ぶ', None, True], [None, None, 'りの', True], ['快晴', 'かいせい', None, None], [None, None, 'で、とてもさわやかだ。', None]]

 65%|██████▌   | 612/938 [06:24<03:58,  1.36it/s]

[['無理', 'むり', None, None], [None, None, 'に', None], ['引', 'ひ', None, None], [None, None, 'っぱっ', None], [None, None, 'ては', True], ['壊', 'こわ', None, None], [None, None, 'れてしまいますよ！', None]]
[['寝', 'ね', None, None], [None, None, 'る', None], ['前', 'まえ', None, None], [None, None, 'にそんなコーヒーを', None], ['飲', 'の', None, True], [None, None, 'んでは', True], ['寝', 'ね', None, None], [None, None, 'られない。', None]]
[[None, None, 'こんなに', None], ['塩辛', 'しおから', None, None], [None, None, 'く', None], [None, None, 'ては', True], ['売', 'う', None, None], [None, None, 'り', None], ['物', 'もの', None, None], [None, None, 'にならないよ。', None]]
[[None, None, 'そんな', None], ['服装', 'ふくそう', None, None], [None, None, 'では', True], [None, None, 'あの', None], ['店', 'みせ', None, None], [None, None, 'には', None], ['入', 'い', None, None], [None, None, 'れてもらえないよ。', None]]
[[None, None, 'そのような', None], ['給与', 'きゅうよ', None, None], [None, None, 'では', True], [None, None, '、あの', None], ['工場', 'こうじょう', None, None], [None, None, 'で', None], ['働', 'はたら', None, None], [None, None, 'くには', None], ['無理', 'むり', None, None], [None, None, 'がある。', None]]

 65%|██████▌   | 613/938 [06:25<03:59,  1.36it/s]

[['田舎者', 'いなかもの', None, None], [None, None, '：「', None], ['働', 'はたら', None, None], [None, None, 'い', None], [None, None, 'ては', True], ['寝', 'ね', None, None], [None, None, 'て、', None], ['働', 'はたら', None, None], [None, None, 'い', None], [None, None, 'ては', True], ['寝', 'ね', None, None], [None, None, 'てばかりだ。このような', None], ['人生', 'じんせい', None, None], [None, None, 'はダメだ。」', None]]
[[None, None, 'あくびをし', None], [None, None, 'ては', True], [None, None, 'フリスクを', None], ['食', 'た', None, None], [None, None, 'べ、あくびをし', None], [None, None, 'ては', True], [None, None, 'フリスクを', None], ['食', 'た', None, None], [None, None, 'べ、', None], ['何', 'なん', None, None], [None, None, 'とか', None], ['起', 'お', None, None], [None, None, 'きていられた。', None]]
[['曖昧', 'あいまい', None, None], [None, None, 'なことを', None], ['言', 'い', None, None], [None, None, 'っ', None], [None, None, 'ては', True], [None, None, 'はぐらかし、', None], ['嘘', 'うそ', None, None], [None, None, 'をつい', None], [None, None, 'ては', True], ['逃', 'に', None, None], [None, None, 'げようとし、あの', None], ['人', 'ひと', None, None], [None, None, 'はどうしようもない。', None]]
[['酒', 'さけ', None, None], [None, None, 'を', None], ['飲', 'の', None, None], [None, None, 'ん', None], [None, None, 'では', None], ['暴', 'あば', None, None], [None, None, 'れ、', None], ['暴', 'あば', None, None], [None, None, 'れ', None], [None, None, 'ては', True], ['物', 'もの', None, None], [None, None, 'を', None], ['壊', 'こわ', None, None], [None, None, 'す。', None], ['彼', 'かれ', None, None], [None, None, 'は', None], ['酒', 'さけ', None, None], ['癖', 'ぐせ', None, None], [None, None, 'が', None], ['悪', 'わる', None, None], [None, None, 'い。', None]]
[['受', 'う', None, None], [None, None, 'け', None], ['取', 'と', None, None], [None, None, 'っ', None], [None, None, 'ては', True], ['誰', 'だれ', None, None], [None, None, 'かに', None], ['渡', 'わた', None, None], [None, None, 'し、', None], ['渡', 'わた', None, None], [None, None, 'され', None], [None, None, 'ては', True], ['受', 'う', None, None], [None, None, 'け', None], ['取', 'と', None, None], [None, None, 'るというだけの', None], ['仕事', 'しごと', None, None], [None, None, 'です。', None]]

 65%|██████▌   | 614/938 [06:26<03:55,  1.37it/s]

[[None, None, 'チームのキャプテン', None], [None, None, '：「', None], ['今日', 'きょう', None, None], [None, None, 'も', True], ['又', 'また', None, True], ['頑張', 'がんば', None, None], [None, None, 'ろう！」', None]]
[['社長', 'しゃちょう', None, None], [None, None, '：「', None], ['今年', 'ことし', None, None], [None, None, 'も', True], ['又', 'また', None, True], ['利益', 'りえき', None, None], ['増大', 'ぞうだい', None, None], [None, None, 'に', None], ['取', 'と', None, None], [None, None, 'り', None], ['組', 'く', None, None], [None, None, 'みます。」', None]]
[['論文', 'ろんぶん', None, None], [None, None, '：「', None], ['盆栽', 'ぼんさい', None, None], [None, None, 'をいじるという', None], ['趣味', 'しゅみ', None, None], [None, None, 'も', True], ['又', 'また', None, True], ['中国', 'ちゅうごく', None, None], [None, None, 'がルーツである。」', None]]
[['論文', 'ろんぶん', None, None], [None, None, '：「お', None], ['金', 'かね', None, None], [None, None, 'は、', None], ['使', 'つか', None, None], [None, None, 'うことだけでなく', None], ['稼', 'かせ', None, None], [None, None, 'ぐこと', None], [None, None, 'も', True], ['又', 'また', None, True], ['楽', 'たの', None, None], [None, None, 'しいです。」', None]]
[['子育', 'こそだ', None, None], [None, None, 'てについての', None], ['論文', 'ろんぶん', None, None], [None, None, '：「', None], ['可愛', 'かわい', None, None], [None, None, 'い', None], ['子', 'こ', None, None], [None, None, 'に', None], ['旅', 'たび', None, None], [None, None, 'をさせてみること、それ', None], [None, None, 'も', True], ['又', 'また', None, True], ['大切', 'たいせつ', None, None], [None, None, 'なことです。」', None]]

 66%|██████▌   | 615/938 [06:26<03:52,  1.39it/s]

[['叫', 'さけ', None, None], [None, None, 'んで', None], ['暴', 'あば', None, None], [None, None, 'れた', None], ['結果', 'けっか', None, True], [None, None, '、', None], ['逮捕', 'たいほ', None, None], [None, None, 'された。', None]]
[['占', 'うらな', None, None], [None, None, 'い', None], [None, None, 'の', True], ['結果', 'けっか', None, True], [None, None, 'など', None], ['信', 'しん', None, None], [None, None, 'じたりはしない。', None]]
[['運動', 'うんどう', None, None], [None, None, 'を', None], ['怠', 'おこた', None, None], [None, None, 'った', None], ['結果', 'けっか', None, True], [None, None, '、', None], ['太', 'ふと', None, None], [None, None, 'ってしまった。', None]]
[['研究', 'けんきゅう', None, None], [None, None, 'の', True], ['結果', 'けっか', None, True], [None, None, '、', None], ['新', 'あたら', None, None], [None, None, 'しい', None], ['粒子', 'りゅうし', None, None], [None, None, 'が', None], ['見', 'み', None, None], [None, None, 'つかった。', None]]
[['裁判', 'さいばん', None, None], [None, None, 'で', None], ['争', 'あらそ', None, None], [None, None, 'った', None], ['結果', 'けっか', None, True], ['負', 'ま', None, None], [None, None, 'けてしまうなんて…', None]]

 66%|██████▌   | 616/938 [06:27<03:33,  1.51it/s]

[[None, None, 'あの', None], ['原稿', 'げんこう', None, None], [None, None, 'を', None], ['読', 'よ', None, True], [None, None, 'んで', True], ['以来', 'いらい', None, True], [None, None, '、すっかり', None], ['彼', 'かれ', None, None], [None, None, 'のファンになった。', None]]
[['紅葉', 'こうよう', None, None], [None, None, 'が', None], ['始', 'はじ', None, True], [None, None, 'まって', True], ['以来', 'いらい', None, True], [None, None, '、', None], ['店', 'みせ', None, None], [None, None, 'は', None], ['超', 'ちょう', None, None], ['満員', 'まんいん', None, None], [None, None, 'だ。', None]]
[['卒業', 'そつぎょう', None, None], [None, None, 'して', True], ['以来', 'いらい', None, True], [None, None, 'だな。この', None], ['校舎', 'こうしゃ', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'に', None], ['来', 'き', None, None], [None, None, 'たのは。', None]]
[[None, None, 'シフトを', None], ['交替', 'こうたい', None, None], [None, None, 'して', True], ['以来', 'いらい', None, True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'とは', None], ['全然', 'ぜんぜん', None, None], ['会', 'あ', None, None], [None, None, 'わなくなった。', None]]
[['休業', 'きゅうぎょう', None, None], [None, None, 'して', True], ['以来', 'いらい', None, True], [None, None, '、', None], ['再開', 'さいかい', None, None], [None, None, 'の', None], ['目処', 'めど', None, None], [None, None, 'が', None], ['立', 'た', None, None], [None, None, 'っていない。', None]]

 66%|██████▌   | 617/938 [06:28<03:40,  1.45it/s]

[[None, None, 'このアプリの', None], ['使用', 'しよう', None, None], [None, None, 'に', True], ['先立', 'さきだ', None, True], [None, None, 'ち', True], [None, None, '、ライセンス', None], ['契約', 'けいやく', None, None], [None, None, 'を', None], ['読', 'よ', None, None], [None, None, 'んでおいてください。', None]]
[[None, None, 'クリストファー・コロンブス', None], [None, None, 'に', True], ['先立', 'さきだ', None, True], [None, None, 'って', True], [None, None, 'ヴァイキングはアメリカを', None], ['発見', 'はっけん', None, None], [None, None, 'したと', None], ['考', 'かんが', None, None], [None, None, 'えられている。', None]]
[[None, None, 'レーザーの', None], ['電源', 'でんげん', None, None], [None, None, 'を', None], ['入', 'い', None, None], [None, None, 'れる', None], [None, None, 'に', True], ['先立', 'さきだ', None, True], [None, None, 'って', True], [None, None, '、', None], ['保護', 'ほご', None, None], [None, None, 'メガネをかけておいてください。', None]]
[[None, None, 'あるゲームの', None], ['通知', 'つうち', None, None], [None, None, '：「', None], ['冒険', 'ぼうけん', None, None], [None, None, 'に', None], ['挑', 'いど', None, None], [None, None, 'む', None], [None, None, 'に', True], ['先立', 'さきだ', None, True], [None, None, 'って', True], ['仲間', 'なかま', None, None], [None, None, 'を', None], ['集', 'あつ', None, None], [None, None, 'めよ。」', None]]
[['ＰＣ', 'ピーシー', None, None], [None, None, 'ケースを', None], ['開', 'あ', None, None], [None, None, 'ける', None], [None, None, 'に', True], ['先立', 'さきだ', None, True], [None, None, 'ち', True], [None, None, '、', None], ['万', 'まん', None, None], [None, None, 'が', None], ['一', 'いち', None, None], [None, None, 'のためにまず', None], ['電源', 'でんげん', None, None], [None, None, 'を', None], ['切', 'き', None, None], [None, None, 'っておかなければならない。', None]]

 66%|██████▌   | 618/938 [06:28<03:47,  1.41it/s]

[['迷子', 'まいご', None, None], [None, None, '：「', None], ['果', 'は', None, True], [None, None, 'たして', True], [None, None, 'どうやって', None], ['帰', 'かえ', None, None], [None, None, 'るの？」', None]]
[['Ａ', 'エー', None, None], [None, None, '：「バンジージャンプしてみたいなぁ〜。」 ', None], ['Ｂ', 'ビー', None, None], [None, None, '：「', None], ['果', 'は', None, True], [None, None, 'たして', True], [None, None, 'できるかしら？」', None]]
[[None, None, 'あんな', None], ['厚', 'あつ', None, None], [None, None, 'かましいお', None], ['願', 'ねが', None, None], [None, None, 'いをして、', None], ['果', 'は', None, True], [None, None, 'たして', True], [None, None, 'うまくいくのだろうか。', None]]
[['大学', 'だいがく', None, None], [None, None, 'を', None], ['中退', 'ちゅうたい', None, None], [None, None, 'するのは', None], ['果', 'は', None, True], [None, None, 'たして', True], ['賢明', 'けんめい', None, None], [None, None, 'な', None], ['行動', 'こうどう', None, None], [None, None, 'でしょうか。', None]]
[['首相', 'しゅしょう', None, None], [None, None, 'は', None], ['減税', 'げんぜい', None, None], [None, None, 'を', None], ['約束', 'やくそく', None, None], [None, None, 'した。', None], ['果', 'は', None, True], [None, None, 'たして', True], ['首相', 'しゅしょう', None, None], [None, None, 'は', None], ['公約', 'こうやく', None, None], [None, None, 'を', None], ['守', 'まも', None, None], [None, None, 'らなかった。', None]]

 66%|██████▌   | 619/938 [06:29<03:32,  1.50it/s]

[[None, None, '「', None], ['彼', 'かれ', None, None], [None, None, 'は', None], ['勉強', 'べんきょう', None, None], [None, None, 'しないので', None], ['教', 'おし', None, True], [None, None, 'え', True], ['甲斐', 'がい', None, True], [None, None, 'がない', True], [None, None, '。」', None]]
[['移転', 'いてん', None, None], [None, None, 'した', None], ['甲斐', 'かい', None, True], [None, None, 'があり', True], [None, None, '、', None], ['今', 'いま', None, None], [None, None, 'やうちは', None], ['人気', 'にんき', None, None], ['店', 'てん', None, None], [None, None, 'だ。', None]]
[[None, None, 'あの', None], ['選手', 'せんしゅ', None, None], [None, None, 'の', None], ['本音', 'ほんね', None, None], [None, None, 'を', None], ['聞', 'き', None, None], [None, None, 'けて、インタビューした', None], ['甲斐', 'かい', None, True], [None, None, 'がありました', True], [None, None, '。', None]]
[[None, None, 'あんだけ', None], ['喜', 'よろこ', None, None], [None, None, 'んでもらえれば、', None], ['頑張', 'がんば', None, None], [None, None, 'って', None], ['手', 'て', None, None], [None, None, 'で', None], ['編', 'あ', None, None], [None, None, 'んだ', None], ['甲斐', 'かい', None, True], [None, None, 'がある', True], [None, None, '。', None]]
[[None, None, 'やっぱり、', None], ['消火', 'しょうか', None, None], ['器', 'き', None, None], [None, None, 'を', None], ['取', 'と', None, None], [None, None, 'り', None], ['付', 'つ', None, None], [None, None, 'けておいた', None], ['甲斐', 'かい', None, True], [None, None, 'があって', True], [None, None, '、', None], ['今回', 'こんかい', None, None], ['役', 'やく', None, None], [None, None, 'に', None], ['立', 'た', None, None], [None, None, 'った。', None]]

 66%|██████▌   | 620/938 [06:30<03:36,  1.47it/s]

[['軈', 'やが', None, True], [None, None, 'て', True], [None, None, 'きみは', None], ['失恋', 'しつれん', None, None], [None, None, 'したことも', None], ['忘', 'わす', None, None], [None, None, 'れるかもしれない。', None]]
[['軈', 'やが', None, True], [None, None, 'て', True], ['３０', 'さんじゅっ', None, None], ['歳', 'さい', None, None], [None, None, 'になるけど、お', None], ['金', 'かね', None, None], [None, None, 'も', None], ['名声', 'めいせい', None, None], [None, None, 'も', None], ['持', 'も', None, None], [None, None, 'ってない。', None]]
[[None, None, 'それがきっかけで、', None], ['軈', 'やが', None, True], [None, None, 'て', True], ['新', 'あら', None, None], [None, None, 'たな', None], ['戦争', 'せんそう', None, None], [None, None, 'が', None], ['起', 'お', None, None], [None, None, 'こる', None], ['可能性', 'かのうせい', None, None], [None, None, 'がある。', None]]
[[None, None, 'オデュッセウス', None], [None, None, '：「', None], ['時間', 'じかん', None, None], [None, None, 'と', None], ['手間', 'てま', None, None], [None, None, 'をかけても、', None], ['軈', 'やが', None, True], [None, None, 'て', True], ['家', 'いえ', None, None], [None, None, 'に', None], ['帰', 'かえ', None, None], [None, None, 'れる！」', None]]
[[None, None, 'どんな', None], ['本', 'ほん', None, None], [None, None, 'も', None], ['軈', 'やが', None, True], [None, None, 'て', True], ['読', 'よ', None, None], [None, None, 'み', None], ['終', 'お', None, None], [None, None, 'わります。けれど、', None], ['果', 'は', None, None], [None, None, 'たしてそれは', None], ['本当', 'ほんとう', None, None], [None, None, 'でしょうか？', None]]

 66%|██████▌   | 621/938 [06:30<03:39,  1.44it/s]

[[None, None, 'あの', None], ['会社', 'かいしゃ', None, None], [None, None, 'は', None], ['業界', 'ぎょうかい', None, None], ['大手', 'おおて', None, None], [None, None, 'だ。', None], ['従', 'したが', None, True], [None, None, 'って', True], [None, None, '、', None], ['強気', 'つよき', None, None], [None, None, 'に', None], ['出', 'で', None, None], [None, None, 'てくるはずです。', None]]
[['値下', 'ねさ', None, None], [None, None, 'げしないよう', None], ['連絡', 'れんらく', None, None], [None, None, 'がありました。', None], ['従', 'したが', None, True], [None, None, 'って', True], [None, None, '、', None], ['定価', 'ていか', None, None], [None, None, 'で', None], ['売', 'う', None, None], [None, None, 'るしかありません。', None]]
[['意見', 'いけん', None, None], [None, None, 'の', None], ['相違', 'そうい', None, None], [None, None, 'がありすぎる。', None], ['従', 'したが', None, True], [None, None, 'って', True], [None, None, '、', None], ['契約', 'けいやく', None, None], [None, None, 'は', None], ['破棄', 'はき', None, None], [None, None, 'させていただきます。', None]]
[['公害', 'こうがい', None, None], [None, None, 'が', None], ['増大', 'ぞうだい', None, None], [None, None, 'している。', None], ['従', 'したが', None, True], [None, None, 'って', True], [None, None, '、', None], ['工場', 'こうじょう', None, None], [None, None, 'は', None], ['閉鎖', 'へいさ', None, None], [None, None, 'する', None], ['方向', 'ほうこう', None, None], [None, None, 'になります。', None]]
[['電車', 'でんしゃ', None, None], [None, None, 'が', None], ['脱線', 'だっせん', None, None], [None, None, 'してしまった。', None], ['従', 'したが', None, True], [None, None, 'って', True], [None, None, '、', None], ['今日', 'きょう', None, None], ['中', 'じゅう', None, None], [None, None, 'の', None], ['到着', 'とうちゃく', None, None], [None, None, 'は', None], ['無理', 'むり', None, None], [None, None, 'だと', None], ['思', 'おも', None, None], [None, None, 'われます。', None]]

 66%|██████▋   | 622/938 [06:31<03:27,  1.52it/s]

[['走', 'はし', None, None], [None, None, 'って', None], ['転', 'ころ', None, None], [None, None, 'んだ', None], ['挙', 'あ', None, True], [None, None, 'げ', True], ['句', 'く', None, True], [None, None, 'に、', None], ['壁', 'かべ', None, None], [None, None, 'に', None], ['衝突', 'しょうとつ', None, None], [None, None, 'した。', None]]
[[None, None, 'さんざん', None], ['泣', 'な', None, None], [None, None, 'いた', None], ['挙', 'あ', None, True], [None, None, 'げ', True], ['句', 'く', None, True], [None, None, '、', None], ['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['眠', 'ねむ', None, None], [None, None, 'ってしまった。', None]]
[['数', 'すう', None, None], ['回', 'かい', None, None], ['追', 'お', None, None], [None, None, 'い', None], ['越', 'こ', None, None], [None, None, 'した', None], ['挙', 'あ', None, True], [None, None, 'げ', True], ['句', 'く', None, True], [None, None, 'に、ドライバーはガードレールにぶつかってしまった。', None]]
[[None, None, 'お', None], ['酒', 'さけ', None, None], [None, None, 'を', None], ['飲', 'の', None, None], [None, None, 'んで', None], ['泥酔', 'でいすい', None, None], [None, None, 'した', None], ['挙', 'あ', None, True], [None, None, 'げ', True], ['句', 'く', None, True], [None, None, 'に、', None], ['財布', 'さいふ', None, None], [None, None, 'を', None], ['盗', 'と', None, None], [None, None, 'られた。', None]]
[[None, None, 'さんざん', None], ['考', 'かんが', None, None], [None, None, 'えた', None], ['挙', 'あ', None, True], [None, None, 'げ', True], ['句', 'く', None, True], [None, None, 'に', None], ['親', 'おや', None, None], [None, None, 'の', None], ['意', 'い', None, None], [None, None, 'に', None], ['反', 'はん', None, None], [None, None, 'して', None], ['大学', 'だいがく', None, None], [None, None, 'を', None], ['辞', 'や', None, None], [None, None, 'めた。', None]]

 66%|██████▋   | 623/938 [06:32<03:32,  1.48it/s]

[['相手', 'あいて', None, None], [None, None, 'チームのエラー', None], [None, None, 'を', True], ['切', 'き', None, True], [None, None, 'っ', True], ['掛', 'か', None, True], [None, None, 'け', True], [None, None, 'に、', None], ['逆転', 'ぎゃくてん', None, None], [None, None, 'して', None], ['勝', 'か', None, None], [None, None, 'った。', None]]
[[None, None, 'クモに', None], ['刺', 'さ', None, None], [None, None, 'されたの', None], [None, None, 'を', True], ['切', 'き', None, True], [None, None, 'っ', True], ['掛', 'か', None, True], [None, None, 'け', True], [None, None, 'として、', None], ['彼', 'かれ', None, None], [None, None, 'はスーパーヒーローになった。', None]]
[[None, None, 'オランダで', None], ['自転車', 'じてんしゃ', None, None], [None, None, 'が', None], ['普及', 'ふきゅう', None, None], [None, None, 'するようになったのは、オイルショック', None], [None, None, 'が', True], ['切', 'き', None, True], [None, None, 'っ', True], ['掛', 'か', None, True], [None, None, 'け', True], [None, None, 'である。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['母', 'はは', None, None], [None, None, 'はスモーカーだったけど、', None], ['電子', 'でんし', None, None], [None, None, 'たばこを', None], ['贈', 'おく', None, None], [None, None, 'ってあげたの', None], [None, None, 'を', True], ['切', 'き', None, True], [None, None, 'っ', True], ['掛', 'か', None, True], [None, None, 'け', True], [None, None, 'に、', None], ['止', 'や', None, None], [None, None, 'めてくれた。', None]]
[[None, None, 'サラエボ', None], ['事件', 'じけん', None, None], [None, None, 'を', True], ['切', 'き', None, True], [None, None, 'っ', True], ['掛', 'か', None, True], [None, None, 'け', True], [None, None, 'にして、', None], ['１９１４', 'せんきゅうひゃくじゅうよ', None, None], ['年', 'ねん', None, None], [None, None, 'から', None], ['１９１８', 'せんきゅうひゃくじゅうはち', None, None], ['年', 'ねん', None, None], [None, None, 'にかけて、', None], ['後', 'のち', None, None], [None, None, 'に', None], ['世界', 'せかい', None, None], ['大戦', 'たいせん', None, None], [None, None, 'と', None], ['呼', 'よ', None, None], [None, None, 'ばれるようになった', None], ['戦争', 'せんそう', None, None], [None, None, 'が', None], ['起', 'お', None, None], [None, None, 'きた。', None]]

 67%|██████▋   | 624/938 [06:32<03:33,  1.47it/s]

[['ＲＰＧ', 'アールピージー', None, None], [None, None, 'ゲームをすること', None], [None, None, 'にかけては', True], ['誰', 'だれ', None, None], [None, None, 'にも', None], ['負', 'ま', None, None], [None, None, 'けない。', None]]
[['格闘', 'かくとう', None, None], [None, None, 'にかけては', True], [None, None, 'リュ◯の', None], ['右', 'みぎ', None, None], [None, None, 'に', None], ['出', 'で', None, None], [None, None, 'る', None], ['者', 'もの', None, None], [None, None, 'はいない。', None]]
[['算数', 'さんすう', None, None], [None, None, 'にかけては', True], [None, None, 'あの', None], ['子', 'こ', None, None], [None, None, 'がうちのクラスでトップだと', None], ['思', 'おも', None, None], [None, None, 'う。', None]]
[['香水', 'こうすい', None, None], [None, None, 'にかけては', True], ['彼女', 'かのじょ', None, None], [None, None, 'が', None], ['一番', 'いちばん', None, None], ['詳', 'くわ', None, None], [None, None, 'しいと', None], ['思', 'おも', None, None], [None, None, 'う。', None]]
[[None, None, 'クーラーの', None], ['掃除', 'そうじ', None, None], [None, None, 'にかけては', True], [None, None, 'あの', None], ['会社', 'かいしゃ', None, None], [None, None, 'が', None], ['一番', 'いちばん', None, None], [None, None, 'だと', None], ['思', 'おも', None, None], [None, None, 'います。', None]]

 67%|██████▋   | 625/938 [06:33<03:31,  1.48it/s]

[[None, None, '「バス？', None], ['疾', 'と', None, True], [None, None, 'っくに', True], ['行', 'い', None, None], [None, None, 'っちゃったよ。」', None]]
[[None, None, '「お', None], ['前', 'まえ', None, None], [None, None, 'は', None], ['疾', 'と', None, True], [None, None, 'っくに', True], ['死', 'し', None, None], [None, None, 'んでいる。」', None]]
[[None, None, '「うちの', None], ['子', 'こ', None, None], [None, None, 'は', None], ['疾', 'と', None, True], [None, None, 'っくに', True], ['歩', 'ある', None, None], [None, None, 'けるようになった。」', None]]
[[None, None, '「', None], ['魔王', 'まおう', None, None], [None, None, 'と', None], ['勇者', 'ゆうしゃ', None, None], [None, None, 'の', None], ['栄光', 'えいこう', None, None], ['時代', 'じだい', None, None], [None, None, 'は', None], ['疾', 'と', None, True], [None, None, 'っくに', True], ['過', 'す', None, None], [None, None, 'ぎた。」', None]]
[[None, None, '「よく', None], ['寝', 'ね', None, None], [None, None, 'るために、', None], ['暗号', 'あんごう', None, None], ['通貨', 'つうか', None, None], [None, None, 'から', None], ['疾', 'と', None, True], [None, None, 'っくに', True], ['撤退', 'てったい', None, None], [None, None, 'した。」', None]]

 67%|██████▋   | 626/938 [06:34<03:57,  1.31it/s]

[['小説', 'しょうせつ', None, None], [None, None, '、', None], ['語', 'かた', None, None], [None, None, 'り', None], ['手', 'て', None, None], [None, None, '：「そのようなことが', None], ['起', 'お', None, None], [None, None, 'こったとは、', None], ['未', 'いま', None, True], [None, None, 'だに', True], ['信', 'しん', None, None], [None, None, 'じられない。」', None]]
[['歴史書', 'れきししょ', None, None], [None, None, '：「', None], ['未', 'いま', None, True], [None, None, 'だに', True], [None, None, 'クロサキマサキ', None], ['氏', 'し', None, None], [None, None, 'の', None], ['死', 'し', None, None], [None, None, 'に', None], ['関', 'かん', None, None], [None, None, 'して', None], ['不明', 'ふめい', None, None], [None, None, 'な', None], ['点', 'てん', None, None], [None, None, 'が', None], ['多', 'おお', None, None], [None, None, 'い。」', None]]
[['小説', 'しょうせつ', None, None], [None, None, '、', None], ['語', 'かた', None, None], [None, None, 'り', None], ['手', 'て', None, None], [None, None, '：「', None], ['未', 'いま', None, True], [None, None, 'だに', True], ['俺', 'おれ', None, None], [None, None, 'は、なぜ', None], ['彼女', 'かのじょ', None, None], [None, None, 'があんなにも', None], ['怒', 'おこ', None, None], [None, None, 'っていたのか、よくわからない。」', None]]
[['苦情', 'くじょう', None, None], [None, None, 'の', None], ['内容', 'ないよう', None, None], [None, None, '：「', None], ['購入', 'こうにゅう', None, None], [None, None, 'してから', None], ['三', 'さん', None, None], ['週間', 'しゅうかん', None, None], ['経', 'た', None, None], [None, None, 'ったものの', None], ['未', 'いま', None, True], [None, None, 'だに', True], ['商品', 'しょうひん', None, None], [None, None, 'が', None], ['届', 'とど', None, None], [None, None, 'いていません。」', None]]
[['記事', 'きじ', None, None], [None, None, '：「', None], ['専門家', 'せんもんか', None, None], [None, None, 'は', None], ['未', 'いま', None, True], [None, None, 'だに', True], ['伝説上', 'でんせつじょう', None, None], [None, None, 'の', None], ['街', 'まち', None, None], [None, None, 'の', None], ['位置', 'いち', None, None], [None, None, 'を', None], ['巡', 'めぐ', None, None], [None, None, 'り', None], ['論争', 'ろんそう', None, None], [None, None, 'している。」', None]]

 67%|██████▋   | 627/938 [06:35<03:54,  1.32it/s]

[[None, None, 'これはクックパッド', None], [None, None, 'を', True], ['元', 'もと', None, True], [None, None, 'に', True], ['作', 'つく', None, None], [None, None, 'ったうどんです。', None]]
[[None, None, 'このインタビュー', None], [None, None, 'を', True], ['元', 'もと', None, True], [None, None, 'に', True], ['記事', 'きじ', None, None], [None, None, 'を', None], ['書', 'か', None, None], [None, None, 'いてください。', None]]
[['息子', 'むすこ', None, None], [None, None, 'の', None], ['足跡', 'あしあと', None, None], [None, None, 'を', True], ['元', 'もと', None, True], [None, None, 'に', True], ['後', 'あと', None, None], [None, None, 'を', None], ['追', 'お', None, None], [None, None, 'った。', None]]
[['電話', 'でんわ', None, None], ['帳', 'ちょう', None, None], [None, None, 'を', True], ['元', 'もと', None, True], [None, None, 'に', True], ['宛名', 'あてな', None, None], [None, None, 'を', None], ['書', 'か', None, None], [None, None, 'いてください。', None]]
[[None, None, 'そんな', None], ['主観', 'しゅかん', None, None], [None, None, 'を', True], ['元', 'もと', None, True], [None, None, 'に', True], ['恨', 'うら', None, None], [None, None, 'まれても', None], ['困', 'こま', None, None], [None, None, 'るよ。', None]]

 67%|██████▋   | 628/938 [06:36<03:56,  1.31it/s]

[['二十歳', 'はたち', None, None], [None, None, 'になる', None], [None, None, 'からには', True], [None, None, '、ドライブしに', None], ['行', 'い', None, None], [None, None, 'こう！', None]]
[[None, None, 'インタビューをする', None], [None, None, 'からには', True], [None, None, '、', None], ['本音', 'ほんね', None, None], [None, None, 'を', None], ['聞', 'き', None, None], [None, None, 'き', None], ['出', 'だ', None, None], [None, None, 'し', None], [None, None, 'たい。', None]]
[['休業', 'きゅうぎょう', None, None], [None, None, 'する', None], [None, None, 'からには', True], [None, None, '、', None], ['事前', 'じぜん', None, None], [None, None, 'の', None], ['説明', 'せつめい', None, None], [None, None, 'をきちんとし', None], [None, None, 'てください', None], [None, None, '。', None]]
[['行事', 'ぎょうじ', None, None], [None, None, 'を', None], ['任', 'まか', None, None], [None, None, 'された', None], [None, None, 'からには', True], [None, None, '、', None], ['絶対', 'ぜったい', None, None], [None, None, 'に', None], ['成功', 'せいこう', None, None], [None, None, 'させます。', None]]
[['演劇', 'えんげき', None, None], [None, None, 'をやる', None], [None, None, 'からには', True], [None, None, '、まずは', None], ['発声', 'はっせい', None, None], ['練習', 'れんしゅう', None, None], [None, None, 'が', None], ['大切', 'たいせつ', None, None], [None, None, 'です。', None]]

 67%|██████▋   | 629/938 [06:36<03:37,  1.42it/s]

[[None, None, 'オレはみんなから', None], [None, None, 'いつの', True], ['間', 'ま', None, True], [None, None, 'にか', True], [None, None, 'ポチと', None], ['呼', 'よ', None, None], [None, None, 'ばれるようになった。', None]]
[[None, None, 'いつの', True], ['間', 'ま', None, True], [None, None, 'にか', True], [None, None, 'もう', None], ['１', 'いち', None, None], ['年', 'ねん', None, None], [None, None, 'が', None], ['経', 'た', None, None], [None, None, 'ってしまった。', None]]
[[None, None, '「', None], [None, None, 'いつの', True], ['間', 'ま', None, True], [None, None, 'にか', True], ['彼女', 'かのじょ', None, None], [None, None, 'はネイティブみたいに', None], ['話', 'はな', None, None], [None, None, 'せるようになった。」', None]]
[['帽子', 'ぼうし', None, None], [None, None, 'を', None], ['被', 'かぶ', None, None], [None, None, 'ってないと', None], [None, None, 'いつの', True], ['間', 'ま', None, True], [None, None, 'にか', True], ['風邪', 'かぜ', None, None], [None, None, 'を', None], ['引', 'ひ', None, None], [None, None, 'く。だからきちんと', None], ['帽子', 'ぼうし', None, None], [None, None, 'を', None], ['被', 'かぶ', None, None], [None, None, 'って。', None]]
[[None, None, 'あなたの', None], ['子供', 'こども', None, None], [None, None, 'から', None], ['目', 'め', None, None], [None, None, 'を', None], ['離', 'はな', None, None], [None, None, 'せば', None], [None, None, 'いつの', True], ['間', 'ま', None, True], [None, None, 'にか', True], ['迷子', 'まいご', None, None], [None, None, 'になるかもしれない。ご', None], ['注意', 'ちゅうい', None, None], [None, None, 'ください。', None]]

 67%|██████▋   | 630/938 [06:37<03:36,  1.42it/s]

[['一旦', 'いったん', None, True], [None, None, 'これをしたら', None], ['残', 'のこ', None, None], [None, None, 'りを', None], ['Ａ', 'エー', None, None], [None, None, 'さんに', None], ['任', 'まか', None, None], [None, None, 'せてください。', None]]
[['一旦', 'いったん', None, True], ['勉強', 'べんきょう', None, None], [None, None, 'し', None], ['始', 'はじ', None, None], [None, None, 'めたら、すべて', None], ['知', 'し', None, None], [None, None, 'りたいです。', None]]
[['一旦', 'いったん', None, True], ['機械', 'きかい', None, None], [None, None, 'の', None], ['電源', 'でんげん', None, None], [None, None, 'がはいるとなかなかとまらない。', None]]
[['一旦', 'いったん', None, True], ['一戸建', 'いっこだ', None, None], [None, None, 'てに', None], ['住', 'す', None, None], [None, None, 'めばアパートに', None], ['戻', 'もど', None, None], [None, None, 'れない。', None]]
[['一旦', 'いったん', None, True], ['何', 'なに', None, None], [None, None, 'かを', None], ['学', 'まな', None, None], [None, None, 'ぶのを', None], ['止', 'や', None, None], [None, None, 'めると', None], ['再開', 'さいかい', None, None], [None, None, 'しにくくなる。', None]]

 67%|██████▋   | 631/938 [06:38<03:35,  1.43it/s]

[['速', 'はや', None, None], [None, None, 'く', None], ['走', 'はし', None, None], [None, None, 'るの', None], [None, None, 'は', True], ['元', 'もと', None, True], [None, None, 'より', True], ['経済', 'けいざい', None, None], ['的', 'てき', None, None], [None, None, 'でもある', None], ['車', 'くるま', None, None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'いたい。', None]]
[['最近', 'さいきん', None, None], [None, None, 'ではコンピューターやスマホ', None], [None, None, 'は', True], ['元', 'もと', None, True], [None, None, 'より', True], [None, None, '、', None], ['歯', 'は', None, None], [None, None, 'ブラシさえ', None], ['ＷＩＦＩ', 'ワイファイ', None, None], [None, None, 'を', None], ['備', 'そな', None, None], [None, None, 'えている。', None]]
[['英語', 'えいご', None, None], [None, None, 'はイギリスやアメリカの', None], ['母国', 'ぼこく', None, None], ['語', 'ご', None, None], [None, None, 'として', None], [None, None, 'は', True], ['元', 'もと', None, True], [None, None, 'より', True], ['台湾', 'たいわん', None, None], [None, None, 'でも', None], ['使', 'つか', None, None], [None, None, 'われている。', None]]
[['我', 'わ', None, None], [None, None, 'が', None], ['社', 'しゃ', None, None], [None, None, 'が', None], ['製造', 'せいぞう', None, None], [None, None, 'する', None], ['棒', 'ぼう', None, None], ['茶', 'ちゃ', None, None], [None, None, 'は', None], ['日本', 'にっぽん', None, None], ['全国', 'ぜんこく', None, None], [None, None, 'は', True], ['元', 'もと', None, True], [None, None, 'より', True], [None, None, '、', None], ['海外', 'かいがい', None, None], [None, None, 'でもよく', None], ['売', 'う', None, None], [None, None, 'られている。', None]]
[[None, None, 'アニメや', None], ['漫画', 'まんが', None, None], [None, None, 'は', None], ['子供', 'こども', None, None], [None, None, 'は', True], ['元', 'もと', None, True], [None, None, 'より', True], ['大人', 'おとな', None, None], [None, None, 'や', None], ['老人', 'ろうじん', None, None], [None, None, 'の', None], ['関心', 'かんしん', None, None], [None, None, 'も', None], ['集', 'あつ', None, None], [None, None, 'める。', None]]

 67%|██████▋   | 632/938 [06:38<03:35,  1.42it/s]

[['明日', 'あした', None, None], ['雪', 'ゆき', None, None], [None, None, 'は', None], ['降', 'ふ', None, True], [None, None, 'りそうにない', True], [None, None, '。', None]]
[[None, None, 'このストーブでは、いつまでたっても', None], ['暖', 'あたた', None, True], [None, None, 'まりそうにない', True], [None, None, '。', None]]
[['今日', 'きょう', None, None], [None, None, 'は', None], ['荷物', 'にもつ', None, None], [None, None, 'を', None], ['受', 'う', None, True], [None, None, 'け', True], ['取', 'と', None, True], [None, None, 'れそうにない', True], [None, None, '。', None]]
[['２', 'に', None, None], ['回', 'かい', None, None], ['連続', 'れんぞく', None, None], [None, None, 'で', None], ['宝', 'たから', None, None], [None, None, 'くじには', None], ['当', 'あ', None, True], [None, None, 'たりそうにない', True], [None, None, '。', None]]
[['偉大', 'いだい', None, None], [None, None, 'すぎて、', None], ['父', 'ちち', None, None], [None, None, 'を', None], ['追', 'お', None, True], [None, None, 'い', True], ['越', 'こ', None, True], [None, None, 'せそうにない', True], [None, None, '。', None]]

 67%|██████▋   | 633/938 [06:39<03:22,  1.51it/s]

[['神様', 'かみさま', None, None], [None, None, 'の', None], ['教', 'おし', None, None], [None, None, 'え', None], [None, None, 'に', True], ['反', 'はん', None, True], [None, None, 'する', True], [None, None, 'ようなことをしてはいけません。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['法律', 'ほうりつ', None, None], [None, None, 'に', True], ['反', 'はん', None, True], [None, None, 'して', True], [None, None, '、', None], ['大学', 'だいがく', None, None], [None, None, 'に', None], ['裏口', 'うらぐち', None, None], ['入学', 'にゅうがく', None, None], [None, None, 'した。', None]]
[[None, None, 'うちのチームは', None], ['予想', 'よそう', None, None], [None, None, 'に', True], ['反', 'はん', None, True], [None, None, 'して', True], [None, None, '、 ', None], ['昨年', 'さくねん', None, None], ['優勝', 'ゆうしょう', None, None], [None, None, 'したチームに', None], ['勝', 'か', None, None], [None, None, 'ったよ！\u3000', None]]
[[None, None, 'モラル', None], [None, None, 'に', True], ['反', 'はん', None, True], [None, None, 'して', True], [None, None, 'まで', None], ['成', 'な', None, None], [None, None, 'り', None], ['上', 'あ', None, None], [None, None, 'がった', None], ['彼', 'かれ', None, None], [None, None, 'を、', None], ['羨', 'うらや', None, None], [None, None, 'ましいとは', None], ['思', 'おも', None, None], [None, None, 'いません。', None]]
[['予想', 'よそう', None, None], [None, None, 'に', True], ['反', 'はん', None, True], [None, None, 'して', True], [None, None, 'ものすごい', None], ['売行', 'うれゆ', None, None], [None, None, 'きで、', None], ['社員', 'しゃいん', None, None], ['一同', 'いちどう', None, None], ['驚', 'おどろ', None, None], [None, None, 'いている。', None]]

 68%|██████▊   | 634/938 [06:40<03:23,  1.49it/s]

[[None, None, 'あの', None], ['話', 'はなし', None, None], [None, None, 'は', None], ['事実', 'じじつ', None, None], [None, None, 'らしいが、', None], ['逆', 'ぎゃく', None, True], [None, None, 'に', True], ['信', 'しん', None, None], [None, None, 'じにくい。', None]]
[['親切', 'しんせつ', None, None], [None, None, 'で', None], ['声', 'こえ', None, None], [None, None, 'をかけたのに、', None], ['逆', 'ぎゃく', None, True], [None, None, 'に', True], ['苦情', 'くじょう', None, None], [None, None, 'を', None], ['言', 'い', None, None], [None, None, 'われた。', None]]
[['遅刻', 'ちこく', None, None], [None, None, 'になると', None], ['思', 'おも', None, None], [None, None, 'って、', None], ['急', 'いそ', None, None], [None, None, 'いだが', None], ['逆', 'ぎゃく', None, True], [None, None, 'に', True], ['余裕', 'よゆう', None, None], [None, None, 'でした。', None]]
[[None, None, 'クレーム', None], ['対応', 'たいおう', None, None], [None, None, 'をしっかりしたら、', None], ['逆', 'ぎゃく', None, True], [None, None, 'に', True], ['売上', 'うりあ', None, None], [None, None, 'げが', None], ['伸', 'の', None, None], [None, None, 'びました。', None]]
[['寒', 'さむ', None, None], [None, None, 'いと', None], ['思', 'おも', None, None], [None, None, 'って', None], ['厚着', 'あつぎ', None, None], [None, None, 'をして', None], ['行', 'い', None, None], [None, None, 'ったら、', None], ['逆', 'ぎゃく', None, True], [None, None, 'に', True], ['暑', 'あつ', None, None], [None, None, 'かった。', None]]

 68%|██████▊   | 635/938 [06:40<03:12,  1.58it/s]

[['商品', 'しょうひん', None, None], [None, None, 'が', None], ['豪華', 'ごうか', None, None], [None, None, 'である', None], ['反面', 'はんめん', None, True], [None, None, '、', None], ['参加', 'さんか', None, None], ['費', 'ひ', None, None], [None, None, 'が', None], ['高額', 'こうがく', None, None], [None, None, 'だ。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['慎重', 'しんちょう', None, None], [None, None, 'な', None], ['反面', 'はんめん', None, True], [None, None, '、', None], ['消極', 'しょうきょく', None, None], ['的', 'てき', None, None], [None, None, 'なところがあります。', None]]
[['一人暮', 'ひとりぐ', None, None], [None, None, 'らしは', None], ['楽', 'たの', None, None], [None, None, 'しい', None], ['反面', 'はんめん', None, True], [None, None, '、', None], ['自分', 'じぶん', None, None], [None, None, 'で', None], ['料理', 'りょうり', None, None], [None, None, 'したり', None], ['掃除', 'そうじ', None, None], [None, None, 'したりする', None], ['必要', 'ひつよう', None, None], [None, None, 'もある。', None]]
[['厳', 'きび', None, None], [None, None, 'しいトレーニングを', None], ['積', 'つ', None, None], [None, None, 'むと', None], ['筋力', 'きんりょく', None, None], [None, None, 'はつく', None], ['反面', 'はんめん', None, True], [None, None, '、', None], ['風邪', 'かぜ', None, None], [None, None, 'をひきやすくなるらしい。', None]]
[['消防署', 'しょうぼうしょ', None, None], [None, None, 'が', None], ['近', 'ちか', None, None], [None, None, 'くにあると', None], ['安心', 'あんしん', None, None], [None, None, 'できる', None], ['反面', 'はんめん', None, True], [None, None, '、', None], ['夜中', 'やちゅう', None, None], [None, None, 'にサイレンがなるから', None], ['大変', 'たいへん', None, None], [None, None, 'だ。', None]]

 68%|██████▊   | 636/938 [06:41<03:21,  1.50it/s]

[[None, None, 'ウォルターさんは', None], ['化学', 'かがく', None, None], [None, None, 'のことなら', None], ['知', 'し', None, True], [None, None, 'り', True], ['抜', 'ぬ', None, True], [None, None, 'いている', True], [None, None, '。', None]]
[['木材', 'もくざい', None, None], [None, None, 'に', None], ['刺', 'さ', None, None], [None, None, 'さった', None], ['釘', 'くぎ', None, None], [None, None, 'を', None], ['引', 'ひ', None, True], [None, None, 'き', True], ['抜', 'ぬ', None, True], [None, None, 'く', True], [None, None, '。', None]]
[['徹夜', 'てつや', None, None], [None, None, 'してでも、このプロジェクトを', None], [None, None, 'やり', True], ['抜', 'ぬ', None, True], [None, None, 'きたい', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['漁師', 'りょうし', None, None], [None, None, 'として', None], ['人生', 'じんせい', None, None], [None, None, 'を', None], ['生', 'い', None, True], [None, None, 'き', True], ['抜', 'ぬ', None, True], [None, None, 'いた', True], [None, None, '。', None]]
[['真', 'しん', None, None], [None, None, 'の', None], ['友', 'とも', None, None], [None, None, 'というのなら、', None], ['信', 'しん', None, True], [None, None, 'じ', True], ['抜', 'ぬ', None, True], [None, None, 'く', True], ['心', 'こころ', None, None], [None, None, 'が', None], ['必要', 'ひつよう', None, None], [None, None, 'だ。', None]]

 68%|██████▊   | 637/938 [06:42<03:24,  1.47it/s]

[[None, None, 'リスク', None], ['抜', 'ぬ', None, True], [None, None, 'きに', True], [None, None, 'は', None], ['決', 'けっ', None, None], [None, None, 'してフグを', None], ['食', 'た', None, None], [None, None, 'べられない。', None]]
[[None, None, '「クソ、', None], ['渋滞', 'じゅうたい', None, None], [None, None, 'だ。あいつら、パーティーをオレ', None], ['抜', 'ぬ', None, True], [None, None, 'きで', True], ['始', 'はじ', None, None], [None, None, 'めそうだ。」', None]]
[[None, None, '「', None], ['食', 'た', None, None], [None, None, 'べれる」のような「ら」', None], ['抜', 'ぬ', None, True], [None, None, 'きの', True], ['言葉', 'ことば', None, None], [None, None, 'は', None], ['人気', 'にんき', None, None], [None, None, 'になっている。', None]]
[['Ｃ', 'シー', None, None], [None, None, '：「', None], ['Ａ', 'エー', None, None], [None, None, 'と', None], ['Ｂ', 'ビー', None, None], [None, None, 'は', None], ['付', 'つ', None, None], [None, None, 'き', None], ['合', 'あ', None, None], [None, None, 'ってんのよ」', None], ['Ｄ', 'ディー', None, None], [None, None, '：「マジ！？', None], ['冗談', 'じょうだん', None, None], ['抜', 'ぬ', None, True], [None, None, 'きで', True], [None, None, '？」', None]]
[['夫婦', 'ふうふ', None, None], [None, None, 'の', None], ['会話', 'かいわ', None, None], [None, None, '：「', None], ['子供', 'こども', None, None], ['抜', 'ぬ', None, True], [None, None, 'きで', True], [None, None, 'どこか', None], ['面白', 'おもしろ', None, None], [None, None, 'いところに', None], ['行', 'い', None, None], [None, None, 'こう！」', None]]

 68%|██████▊   | 638/938 [06:42<03:12,  1.56it/s]

[['愈々', 'いよいよ', None, True], ['春', 'はる', None, None], [None, None, 'がやって', None], ['来', 'き', None, None], [None, None, 'た。', None]]
[[None, None, 'じゃ、', None], ['愈々', 'いよいよ', None, True], ['俺', 'おれ', None, None], [None, None, 'の', None], ['番', 'ばん', None, None], [None, None, 'だ！', None]]
[['愈々', 'いよいよ', None, True], ['夏休', 'なつやす', None, None], [None, None, 'みが', None], ['始', 'はじ', None, None], [None, None, 'まった！', None]]
[['愈々', 'いよいよ', None, True], ['大学', 'だいがく', None, None], [None, None, 'を', None], ['卒業', 'そつぎょう', None, None], [None, None, 'する！', None]]
[['愈々', 'いよいよ', None, True], [None, None, 'ステージが', None], ['始', 'はじ', None, None], [None, None, 'まる。わくわくしてきた。', None]]

 68%|██████▊   | 639/938 [06:43<03:01,  1.65it/s]

[['洗', 'あら', None, None], [None, None, 'い', None], ['物', 'もの', None, None], [None, None, 'を', None], [None, None, 'せずに', True], ['済', 'す', None, True], [None, None, 'む', True], [None, None, '。', None]]
[['事故', 'じこ', None, None], [None, None, 'が', None], ['起', 'お', None, None], [None, None, 'こったけど、', None], ['怪我', 'けが', None, None], [None, None, 'を', None], [None, None, 'せずに', True], ['済', 'す', None, True], [None, None, 'んだ', True], [None, None, '。', None]]
[['犯人', 'はんにん', None, None], [None, None, 'は', None], ['警察', 'けいさつ', None, None], [None, None, 'から、', None], ['捕', 'つか', None, True], [None, None, 'まらずに', True], ['済', 'す', None, True], [None, None, 'んだ', True], [None, None, '。', None]]
[['基礎', 'きそ', None, None], [None, None, 'からトレーニングを', None], ['積', 'つ', None, None], [None, None, 'んでいたから、', None], ['潰', 'つぶ', None, True], [None, None, 'れずに', True], ['済', 'す', None, True], [None, None, 'んだ', True], [None, None, '。', None]]
[[None, None, 'ちゃんとペース', None], ['配分', 'はいぶん', None, None], [None, None, 'したから、', None], ['体力', 'たいりょく', None, None], [None, None, 'を', None], ['消耗', 'しょうもう', None, None], [None, None, 'せずに', True], ['済', 'す', None, True], [None, None, 'んだ', True], [None, None, '。', None]]

 68%|██████▊   | 640/938 [06:43<02:55,  1.70it/s]

[[None, None, 'ジムでは', None], ['実力', 'じつりょく', None, None], [None, None, 'に', True], ['応', 'おう', None, True], [None, None, 'じて', True], [None, None, '、', None], ['練習', 'れんしゅう', None, None], [None, None, 'を', None], ['選', 'えら', None, None], [None, None, 'べるべきだ。', None]]
[['赤', 'あか', None, None], [None, None, 'ん', None], ['坊', 'ぼう', None, None], [None, None, 'のために', None], ['年齢', 'ねんれい', None, None], [None, None, 'に', True], ['応', 'おう', None, True], [None, None, 'じた', True], [None, None, 'ダイエットが', None], ['必要', 'ひつよう', None, None], [None, None, 'です。', None]]
[['私', 'わたし', None, None], ['共', 'ども', None, None], [None, None, 'のホテルでは', None], ['ＶＩＰ', 'ブイアイピー', None, None], [None, None, 'レベルのニーズ', None], [None, None, 'に', True], ['応', 'おう', None, True], [None, None, 'じた', True], [None, None, 'サービスをご', None], ['提供', 'ていきょう', None, None], [None, None, 'いたします。', None]]
[['日本', 'にほん', None, None], ['人', 'じん', None, None], [None, None, 'は', None], ['相手', 'あいて', None, None], [None, None, 'への', None], ['尊敬', 'そんけい', None, None], ['度', 'ど', None, None], [None, None, 'に', True], ['応', 'おう', None, True], [None, None, 'じて', True], [None, None, '、お', None], ['辞儀', 'じぎ', None, None], [None, None, 'の', None], ['角度', 'かくど', None, None], [None, None, 'を', None], ['変', 'か', None, None], [None, None, 'える。', None]]
[['警察官', 'けいさつかん', None, None], [None, None, 'は', None], ['状態', 'じょうたい', None, None], [None, None, 'や', None], ['必要', 'ひつよう', None, None], [None, None, 'に', True], ['応', 'おう', None, True], [None, None, 'じて', True], ['暴力', 'ぼうりょく', None, None], [None, None, 'を', None], ['行使', 'こうし', None, None], [None, None, 'できる', None], ['場合', 'ばあい', None, None], [None, None, 'もあります。', None]]

 68%|██████▊   | 641/938 [06:44<02:49,  1.75it/s]

[[None, None, 'このプロジェクト', None], [None, None, 'を', True], ['通', 'つう', None, True], [None, None, 'じて', True], ['多', 'おお', None, None], [None, None, 'くのことを', None], ['学', 'まな', None, None], [None, None, 'んだ。', None]]
[['看病', 'かんびょう', None, None], [None, None, 'を', True], ['通', 'とお', None, True], [None, None, 'して', True], ['人', 'ひと', None, None], [None, None, 'の', None], ['愛', 'あい', None, None], [None, None, 'を', None], ['知', 'し', None, None], [None, None, 'りました。', None]]
[['叔父', 'おじ', None, None], [None, None, 'さん', None], [None, None, 'を', True], ['通', 'とお', None, True], [None, None, 'して', True], ['仕事', 'しごと', None, None], [None, None, 'の', None], ['依頼', 'いらい', None, None], [None, None, 'がきた。', None]]
[['打合', 'うちあわ', None, None], [None, None, 'せ', None], [None, None, 'を', True], ['通', 'とお', None, True], [None, None, 'して', True], ['新', 'あら', None, None], [None, None, 'たな', None], ['発見', 'はっけん', None, None], [None, None, 'をすることもよくある。', None]]
[['植木', 'うえき', None, None], [None, None, 'を', True], ['通', 'とお', None, True], [None, None, 'して', True], ['自然', 'しぜん', None, None], [None, None, 'の', None], ['尊', 'とうと', None, None], [None, None, 'さを', None], ['学', 'まな', None, None], [None, None, 'びました。', None]]

 68%|██████▊   | 642/938 [06:44<02:46,  1.78it/s]

[['応援', 'おうえん', None, None], [None, None, 'の', None], ['声', 'こえ', None, None], [None, None, 'に', True], ['応', 'こた', None, True], [None, None, 'えて', True], [None, None, '、', None], ['勝利', 'しょうり', None, None], [None, None, 'したチームが', None], ['礼', 'れい', None, None], [None, None, 'をした。', None]]
[['選手', 'せんしゅ', None, None], [None, None, 'の', None], ['活躍', 'かつやく', None, None], [None, None, 'に', True], ['応', 'こた', None, True], [None, None, 'えて', True], [None, None, '、トレー二ングルームを', None], ['新', 'あたら', None, None], [None, None, 'しくした。', None]]
[[None, None, 'アイドル', None], ['歌手', 'かしゅ', None, None], [None, None, 'の', None], ['喝采', 'かっさい', None, None], [None, None, 'に', True], ['応', 'こた', None, True], [None, None, 'えた', True], ['笑顔', 'えがお', None, None], [None, None, 'が', None], ['素晴', 'すば', None, None], [None, None, 'らしかった。', None]]
[['我', 'わ', None, None], [None, None, 'が', None], ['社', 'しゃ', None, None], [None, None, 'はクライアントのニーズ', None], [None, None, 'に', True], ['応', 'こた', None, True], [None, None, 'えた', True], ['商品', 'しょうひん', None, None], [None, None, 'を', None], ['開発', 'かいはつ', None, None], [None, None, 'するべきだ。', None]]
[['演劇', 'えんげき', None, None], ['人気', 'にんき', None, None], [None, None, 'に', True], ['応', 'こた', None, True], [None, None, 'えて', True], ['建', 'た', None, None], [None, None, 'てた', None], ['劇場', 'げきじょう', None, None], [None, None, 'の', None], ['維持', 'いじ', None, None], ['費', 'ひ', None, None], [None, None, 'が', None], ['大変', 'たいへん', None, None], [None, None, 'だ。', None]]

 69%|██████▊   | 643/938 [06:45<02:45,  1.78it/s]

[[None, None, 'クレジットカードで', None], ['払', 'はら', None, None], [None, None, 'う？', None], [None, None, 'それとも', True], ['現金', 'げんきん', None, None], [None, None, 'で？', None]]
[['苦情', 'くじょう', None, None], [None, None, 'を', None], ['言', 'い', None, None], [None, None, 'うべきか、', None], [None, None, 'それとも', True], ['我慢', 'がまん', None, None], [None, None, 'すべきか。', None]]
[['今夜', 'こんや', None, None], [None, None, 'はカラオケに', None], ['行', 'い', None, None], [None, None, 'く？', None], [None, None, 'それとも', True], ['映画館', 'えいがかん', None, None], [None, None, '？', None]]
[[None, None, 'あなたの', None], ['大学', 'だいがく', None, None], [None, None, 'は', None], ['国立', 'こくりつ', None, None], [None, None, '？', None], [None, None, 'それとも', True], ['私立', 'しりつ', None, None], [None, None, '？', None]]
[['生', 'い', None, None], [None, None, 'きるべきか、', None], [None, None, 'それとも', True], ['死', 'し', None, None], [None, None, 'ぬべきか。それが', None], ['問題', 'もんだい', None, None], [None, None, 'だ。', None]]

 69%|██████▊   | 644/938 [06:45<02:45,  1.77it/s]

[['妻', 'つま', None, None], [None, None, 'にしたら', True], [None, None, '、', None], ['私', 'わたし', None, None], [None, None, 'はもっと', None], ['家事', 'かじ', None, None], [None, None, 'をしなくてはいけない。', None]]
[['赤', 'あか', None, None], [None, None, 'ちゃんは', None], ['可愛', 'かわい', None, None], [None, None, 'いが、', None], ['親', 'おや', None, None], [None, None, 'にしたら', True], ['苦労', 'くろう', None, None], [None, None, 'もあるだろう。', None]]
[['大人', 'おとな', None, None], [None, None, 'にしたら', True], [None, None, '、', None], ['童話', 'どうわ', None, None], [None, None, 'は', None], ['少', 'すこ', None, None], [None, None, 'し', None], ['物足', 'ものた', None, None], [None, None, 'りない。', None]]
[['床屋', 'とこや', None, None], [None, None, 'さん', None], [None, None, 'にしたら', True], [None, None, '、', None], ['散髪', 'さんぱつ', None, None], [None, None, 'はアートのようなものなのかもしれない。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'にしたら', True], [None, None, '、', None], ['僕', 'ぼく', None, None], [None, None, 'の', None], ['成功', 'せいこう', None, None], [None, None, 'が', None], ['憎', 'にく', None, None], [None, None, 'らしくてたまらないのだろう。', None]]

 69%|██████▉   | 645/938 [06:46<03:01,  1.61it/s]

[['貸', 'か', None, None], [None, None, 'す', None], [None, None, 'にしても', True], ['売', 'う', None, None], [None, None, 'る', None], [None, None, 'にしても', True], [None, None, '、とにかく', None], ['元', 'もと', None, None], [None, None, 'を', None], ['取', 'と', None, None], [None, None, 'れればそれでいい。', None]]
[['食', 'た', None, None], [None, None, 'べる', None], [None, None, 'にしても', True], [None, None, '、', None], ['食', 'た', None, None], [None, None, 'べない', None], [None, None, 'にしても', True], [None, None, '、', None], ['料理代', 'りょうりだい', None, None], [None, None, 'を', None], ['払', 'はら', None, None], [None, None, 'わないといけない。', None]]
[['貸家', 'かしや', None, None], [None, None, 'にしても', True], [None, None, '、', None], ['自宅', 'じたく', None, None], [None, None, 'にしても', True], [None, None, '、', None], ['家族', 'かぞく', None, None], [None, None, 'がいるだけで', None], ['十分', 'じゅうぶん', None, None], [None, None, '。', None]]
[['簡単', 'かんたん', None, None], [None, None, 'にしても', True], [None, None, '、', None], ['難', 'むずか', None, None], [None, None, 'しい', None], [None, None, 'にしても', True], [None, None, '、', None], ['宿題', 'しゅくだい', None, None], [None, None, 'を', None], ['終', 'お', None, None], [None, None, 'わらせるべきだ。', None]]
[['煮', 'に', None, None], [None, None, 'る', None], [None, None, 'にしても', True], ['焼', 'や', None, None], [None, None, 'く', None], [None, None, 'にしても', True], [None, None, '、', None], ['素材', 'そざい', None, None], [None, None, 'の', None], ['良', 'よ', None, None], [None, None, 'さを', None], ['活', 'い', None, None], [None, None, 'かした', None], ['料理', 'りょうり', None, None], [None, None, 'にしてください。', None]]

 69%|██████▉   | 646/938 [06:47<03:10,  1.53it/s]

[['概論', 'がいろん', None, None], [None, None, 'としては', True], [None, None, '、まだ', None], ['不十分', 'ふじゅうぶん', None, None], [None, None, 'です。', None]]
[['晴', 'は', None, None], [None, None, 'れ', None], ['着', 'ぎ', None, None], [None, None, 'としては', True], [None, None, '、ぼろすぎないか？', None]]
[[None, None, 'アイデア', None], [None, None, 'としては', True], [None, None, 'いいが、', None], ['実現', 'じつげん', None, None], [None, None, 'するのは', None], ['難', 'むずか', None, None], [None, None, 'しい。', None]]
[[None, None, 'イメージ', None], [None, None, 'としては', True], ['分', 'わ', None, None], [None, None, 'かりますが、', None], ['説明', 'せつめい', None, None], [None, None, 'が', None], ['曖昧', 'あいまい', None, None], [None, None, 'すぎます。', None]]
[['趣味', 'しゅみ', None, None], [None, None, 'としては', True], [None, None, 'いいが、', None], ['編物', 'あみもの', None, None], [None, None, 'だけで', None], ['食', 'た', None, None], [None, None, 'べていくのは', None], ['難', 'むずか', None, None], [None, None, 'しい。', None]]

 69%|██████▉   | 647/938 [06:48<03:17,  1.47it/s]

[[None, None, 'たとえできる', None], [None, None, 'としても', True], [None, None, '、やらないだろう。', None]]
[['例', 'たと', None, None], [None, None, 'え', None], ['話', 'ばなし', None, None], [None, None, 'だとしても', True], ['許', 'ゆる', None, None], [None, None, 'されない。', None]]
[['大人', 'おとな', None, None], ['向', 'む', None, None], [None, None, 'きの', None], ['本', 'ほん', None, None], [None, None, 'だとしても', True], ['売', 'う', None, None], [None, None, 'れます。', None]]
[['彼', 'かれ', None, None], [None, None, 'はピアノ', None], ['奏者', 'そうしゃ', None, None], [None, None, 'だが、オルガン', None], ['奏者', 'そうしゃ', None, None], [None, None, 'としても', True], ['有名', 'ゆうめい', None, None], [None, None, 'です。', None]]
[[None, None, 'それが', None], ['正式', 'せいしき', None, None], [None, None, 'な', None], ['回答', 'かいとう', None, None], [None, None, 'だとしても', True], [None, None, '、', None], ['僕', 'ぼく', None, None], [None, None, 'はまだ', None], ['諦', 'あきら', None, None], [None, None, 'めきれません。', None]]

 69%|██████▉   | 648/938 [06:48<03:19,  1.45it/s]

[[None, None, 'ラッピングをお', None], ['願', 'ねが', None, None], [None, None, 'いしたが、', None], [None, None, 'それにしても', True], [None, None, '、かなりの', None], ['過剰', 'かじょう', None, None], ['包装', 'ほうそう', None, None], [None, None, 'だ。', None]]
[['彼', 'かれ', None, None], [None, None, 'らが', None], ['問題', 'もんだい', None, None], [None, None, 'の', None], ['解決', 'かいけつ', None, None], [None, None, 'に', None], ['手', 'て', None, None], [None, None, 'を', None], ['貸', 'か', None, None], [None, None, 'していますが、', None], [None, None, 'それにしても', True], [None, None, 'それは', None], ['難問', 'なんもん', None, None], [None, None, 'です。', None]]
[['古', 'ふる', None, None], [None, None, 'い', None], ['車', 'くるま', None, None], [None, None, 'だから', None], ['仕方', 'しかた', None, None], [None, None, 'がないが、', None], [None, None, 'それにしても', True], ['加速', 'かそく', None, None], [None, None, 'が', None], ['悪', 'わる', None, None], [None, None, 'すぎる。', None]]
[['上司', 'じょうし', None, None], [None, None, 'から', None], ['許可', 'きょか', None, None], [None, None, 'を', None], ['得', 'え', None, None], [None, None, 'ました。', None], [None, None, 'それにしても', True], [None, None, '、', None], ['本部', 'ほんぶ', None, None], [None, None, 'に', None], ['連絡', 'れんらく', None, None], [None, None, 'しないといけません。', None]]
[['災害', 'さいがい', None, None], [None, None, 'を', None], ['防止', 'ぼうし', None, None], [None, None, 'するには、', None], ['避難', 'ひなん', None, None], ['訓練', 'くんれん', None, None], [None, None, 'が', None], ['必要', 'ひつよう', None, None], [None, None, 'だ。', None], [None, None, 'それにしても', True], [None, None, '、', None], ['完全', 'かんぜん', None, None], [None, None, 'な', None], ['予防', 'よぼう', None, None], [None, None, 'は', None], ['無理', 'むり', None, None], [None, None, 'だろう。', None]]

 69%|██████▉   | 649/938 [06:49<03:17,  1.46it/s]

[[None, None, '「', None], ['愚', 'おろ', None, None], [None, None, 'か', None], ['者', 'もの', None, None], [None, None, '、', None], ['男', 'おとこ', None, None], [None, None, 'には', None], ['殺', 'ころ', None, True], [None, None, 'せぬ', True], [None, None, 'のだ。」', None]]
[[None, None, 'こちらでは', None], ['性', 'せい', None, None], [None, None, 'による', None], ['差別', 'さべつ', None, None], [None, None, 'は', None], ['許可', 'きょか', None, None], [None, None, 'されておらぬ', True], [None, None, '。', None]]
[[None, None, 'ペーネロペー', None], [None, None, '：「オデュッセウスはまだ', None], ['戻', 'もど', None, True], [None, None, 'ってこぬ', True], [None, None, 'のか？」', None]]
[[None, None, '「', None], ['隅', 'すみ', None, None], [None, None, 'に', None], ['置', 'お', None, True], [None, None, 'けぬ', True], ['人', 'ひと', None, None], [None, None, '」というのは「', None], ['侮', 'あなど', None, None], [None, None, 'れない', None], ['人', 'ひと', None, None], [None, None, '」ということなのだ。', None]]
[['上司', 'じょうし', None, None], [None, None, 'は', None], ['部下', 'ぶか', None, None], [None, None, 'が', None], ['向上', 'こうじょう', None, None], [None, None, 'できるように、', None], ['至', 'いた', None, True], [None, None, 'らぬ', True], ['点', 'てん', None, None], [None, None, 'を', None], ['教', 'おし', None, None], [None, None, 'えてあげるべきだ。', None]]

 69%|██████▉   | 650/938 [06:50<03:29,  1.38it/s]

[['何', 'なに', None, None], [None, None, 'ごとも', None], ['理解', 'りかい', None, None], [None, None, 'される', None], [None, None, 'ことなく', True], ['終', 'お', None, None], [None, None, 'わる。', None]]
[['真実', 'しんじつ', None, None], [None, None, 'を', None], ['知', 'し', None, None], [None, None, 'る', None], [None, None, 'ことなく', True], ['終', 'お', None, None], [None, None, 'わる。', None]]
[['遅', 'おく', None, None], [None, None, 'れる', None], [None, None, 'ことなく', True], ['到着', 'とうちゃく', None, None], [None, None, 'した。', None]]
[['耕', 'たがや', None, None], [None, None, 'す', None], [None, None, 'ことなく', True], ['種', 'たね', None, None], [None, None, 'を', None], ['植', 'う', None, None], [None, None, 'えても、うまくいくはずがない。', None]]
[[None, None, 'うちの', None], ['子', 'こ', None, None], [None, None, 'には、', None], ['散', 'ち', None, None], [None, None, 'らかす', None], [None, None, 'ことなく', True], ['遊', 'あそ', None, None], [None, None, 'ぶという', None], ['特技', 'とくぎ', None, None], [None, None, 'があります。', None]]

 69%|██████▉   | 651/938 [06:50<03:16,  1.46it/s]

[[None, None, 'これ', None], [None, None, 'にて', True], ['一件', 'いっけん', None, None], ['落着', 'らくちゃく', None, None], [None, None, '。', None]]
[['応接室', 'おうせつしつ', None, None], [None, None, 'にて', True], [None, None, 'お', None], ['待', 'ま', None, None], [None, None, 'ちしております。', None]]
[['面接', 'めんせつ', None, None], [None, None, 'は', None], ['本社', 'ほんしゃ', None, None], [None, None, 'にて', True], ['行', 'おこな', None, None], [None, None, 'います。', None]]
[[None, None, 'メール', None], [None, None, 'にて', True], [None, None, 'ご', None], ['連絡', 'れんらく', None, None], [None, None, 'いただけると', None], ['助', 'たす', None, None], [None, None, 'かります。', None]]
[['午後', 'ごご', None, None], ['五時', 'ごじ', None, None], [None, None, 'にて', True], ['閉店', 'へいてん', None, None], [None, None, 'いたします。', None]]

 70%|██████▉   | 652/938 [06:51<03:38,  1.31it/s]

[[None, None, '「', None], ['移動', 'いどう', None, None], [None, None, 'には', True], [None, None, 'スクーターを', None], ['使', 'つか', None, None], [None, None, 'ったらどう？」', None]]
[['夢', 'ゆめ', None, None], [None, None, 'を', None], ['実現', 'じつげん', None, None], [None, None, 'する', None], [None, None, 'には', True], ['時間', 'じかん', None, None], [None, None, 'がかかる。', None]]
[['出産', 'しゅっさん', None, None], [None, None, 'には', True], [None, None, '、', None], ['我慢', 'がまん', None, None], ['強', 'づよ', None, None], [None, None, 'さが', None], ['必要', 'ひつよう', None, None], [None, None, 'です。', None]]
[['一戸建', 'いっこだ', None, None], [None, None, 'てを', None], ['買', 'か', None, None], [None, None, 'う', None], [None, None, 'には', True], ['多', 'おお', None, None], [None, None, 'くの', None], ['金', 'かね', None, None], [None, None, 'がかかる。', None]]
[['間違', 'まちが', None, None], [None, None, 'いを', None], ['認', 'みと', None, None], [None, None, 'めてやり', None], ['直', 'なお', None, None], [None, None, 'す', None], [None, None, 'には', True], ['勇気', 'ゆうき', None, None], [None, None, 'が', None], ['要', 'い', None, None], [None, None, 'ります。', None]]

 70%|██████▉   | 653/938 [06:52<03:20,  1.42it/s]

[[None, None, 'この', None], ['車', 'くるま', None, None], [None, None, 'は', None], ['思', 'おも', None, True], [None, None, 'うように', True], ['加速', 'かそく', None, None], [None, None, 'しないからイライラする。', None]]
[[None, None, 'オーケストラのメンバー', None], ['集', 'あつ', None, None], [None, None, 'めが', None], ['思', 'おも', None, True], [None, None, 'うように', True], [None, None, 'いきません。', None]]
[[None, None, 'プリンを', None], ['作', 'つく', None, None], [None, None, 'ったら、', None], ['思', 'おも', None, True], [None, None, 'うように', True], ['固', 'かた', None, None], [None, None, 'まらなくて', None], ['困', 'こま', None, None], [None, None, 'った。', None]]
[[None, None, 'ケーキ', None], ['屋', 'や', None, None], [None, None, 'みたいなお', None], ['菓子', 'かし', None, None], [None, None, 'が', None], ['思', 'おも', None, True], [None, None, 'うように', True], ['作', 'つく', None, None], [None, None, 'れなかった。', None]]
[['育児', 'いくじ', None, None], [None, None, 'というのは、', None], ['親', 'おや', None, None], [None, None, 'の', None], ['思', 'おも', None, True], [None, None, 'うように', True], [None, None, 'はいかないものです。', None]]

 70%|██████▉   | 654/938 [06:53<03:29,  1.36it/s]

[[None, None, 'ミスが', None], ['続', 'つづ', None, None], [None, None, 'いたのであきれられた', None], [None, None, 'かと', True], ['思', 'おも', None, True], [None, None, 'ったら', True], [None, None, '、そうでもなかった。', None]]
[['嫌', 'いや', None, None], [None, None, 'がられる', None], [None, None, 'かと', True], ['思', 'おも', None, True], [None, None, 'ったら', True], [None, None, '、あっさり', None], ['ＯＫ', 'オーケー', None, None], [None, None, 'してくれた。', None]]
[['暴', 'あば', None, None], [None, None, 'れていた', None], [None, None, 'かと', True], ['思', 'おも', None, True], [None, None, 'ったら', True], [None, None, '、やけに', None], ['大人', 'おとな', None, None], [None, None, 'しくなることもある。', None]]
[['彼', 'かれ', None, None], [None, None, 'はあれだけ', None], ['怒', 'おこ', None, None], [None, None, 'られて', None], ['悲', 'かな', None, None], [None, None, 'しんでいる', None], [None, None, 'かと', True], ['思', 'おも', None, True], [None, None, 'ったら', True], [None, None, '、すぐに', None], ['笑', 'わら', None, None], [None, None, 'いだした。', None]]
[['何', 'なに', None, None], [None, None, 'を', None], ['言', 'い', None, None], [None, None, 'い', None], ['出', 'だ', None, None], [None, None, 'す', None], [None, None, 'かと', True], ['思', 'おも', None, True], [None, None, 'ったら', True], [None, None, '、コンビ', None], ['解散', 'かいさん', None, None], [None, None, 'の', None], ['話', 'はなし', None, None], [None, None, 'だった。', None]]

 70%|██████▉   | 655/938 [06:53<03:15,  1.45it/s]

[['愛', 'あい', None, None], [None, None, 'があれば', None], ['結婚', 'けっこん', None, None], [None, None, 'できる', None], [None, None, 'というものでもない', True], [None, None, '。', None]]
[[None, None, 'スマートに', None], ['見', 'み', None, None], [None, None, 'える', None], ['人', 'ひと', None, None], [None, None, 'が', None], ['皆', 'みな', None, None], ['痩', 'や', None, None], [None, None, 'せている', None], [None, None, 'というものでもない', True], [None, None, '。', None]]
[['車', 'くるま', None, None], [None, None, 'は', None], ['高', 'たか', None, None], [None, None, 'ければ', None], ['高', 'たか', None, None], [None, None, 'いほどいい', None], [None, None, 'というものでもない', True], [None, None, '。', None]]
[['漫才', 'まんざい', None, None], [None, None, 'は、', None], ['素人', 'しろうと', None, None], [None, None, 'だからといってできない', None], [None, None, 'というものでもない', True], [None, None, '。', None]]
[['図鑑', 'ずかん', None, None], [None, None, 'にはすべての', None], ['生', 'い', None, None], [None, None, 'き', None], ['物', 'もの', None, None], [None, None, 'が', None], ['載', 'の', None, None], [None, None, 'っている', None], [None, None, 'というものでもない', True], [None, None, '。', None]]

 70%|██████▉   | 656/938 [06:54<03:22,  1.40it/s]

[['衆議院', 'しゅうぎいん', None, None], [None, None, '、いよいよ', None], ['解散', 'かいさん', None, None], [None, None, 'する', None], [None, None, 'と', True], ['考', 'かんが', None, True], [None, None, 'えられる', True], [None, None, '。', None]]
[[None, None, 'あの', None], ['子', 'こ', None, None], [None, None, 'の', None], ['親', 'おや', None, None], [None, None, 'は', None], ['育児', 'いくじ', None, None], ['放棄', 'ほうき', None, None], [None, None, 'している', None], [None, None, 'と', True], ['考', 'かんが', None, True], [None, None, 'えられる', True], [None, None, '。', None]]
[[None, None, 'あの', None], ['政策', 'せいさく', None, None], [None, None, 'なら、', None], ['一定', 'いってい', None, None], [None, None, 'の', None], ['支持', 'しじ', None, None], [None, None, 'が', None], ['得', 'え', None, None], [None, None, 'られる', None], [None, None, 'と', True], ['考', 'かんが', None, True], [None, None, 'えられる', True], [None, None, '。', None]]
[['安易', 'あんい', None, None], [None, None, 'に', None], ['決定', 'けってい', None, None], [None, None, 'した', None], [None, None, 'と', True], ['考', 'かんが', None, True], [None, None, 'えられる', True], [None, None, 'が、もしかしたら', None], ['作戦', 'さくせん', None, None], [None, None, 'かもしれません。', None]]
[[None, None, 'そのプロジェクト、', None], ['一旦', 'いったん', None, None], ['白紙', 'はくし', None, None], [None, None, 'に', None], ['戻', 'もど', None, None], [None, None, 'すということも', None], ['考', 'かんが', None, True], [None, None, 'えられません', True], [None, None, 'か？', None]]

 70%|███████   | 657/938 [06:55<03:20,  1.40it/s]

[[None, None, 'もし、うまくいくとしても', None], ['製造', 'せいぞう', None, None], [None, None, 'のコスト', None], [None, None, 'の', True], ['点', 'てん', None, True], [None, None, 'から', True], ['考', 'かんが', None, True], [None, None, 'えると', True], [None, None, 'まだ', None], ['非効率', 'ひこうりつ', None, None], [None, None, 'である。', None]]
[[None, None, 'エンドユーザーの', None], ['便利', 'べんり', None, None], [None, None, 'さ', None], [None, None, 'という', True], ['点', 'てん', None, True], [None, None, 'から', True], ['考', 'かんが', None, True], [None, None, 'えると', True], [None, None, 'それはむしろ', None], ['不便', 'ふべん', None, None], [None, None, 'である。', None]]
[['仕事', 'しごと', None, None], [None, None, 'の', None], ['効率', 'こうりつ', None, None], [None, None, 'の', True], ['点', 'てん', None, True], [None, None, 'から', True], ['考', 'かんが', None, True], [None, None, 'えると', True], ['１', 'いち', None, None], ['時間', 'じかん', None, None], [None, None, 'に', None], ['５', 'ご', None, None], ['分', 'ふん', None, None], [None, None, 'の', None], ['休憩', 'きゅうけい', None, None], [None, None, 'を', None], ['取', 'と', None, None], [None, None, 'る', None], ['方', 'ほう', None, None], [None, None, 'がいい。', None]]
[[None, None, 'ビジネス', None], [None, None, 'という', True], ['点', 'てん', None, True], [None, None, 'から', True], ['考', 'かんが', None, True], [None, None, 'えると', True], ['需要', 'じゅよう', None, None], [None, None, 'が', None], ['高', 'たか', None, None], [None, None, 'いということは', None], ['高', 'たか', None, None], [None, None, 'い', None], ['利益', 'りえき', None, None], [None, None, 'の', None], ['可能性', 'かのうせい', None, None], [None, None, 'があるということだ。', None]]
[['健康', 'けんこう', None, None], [None, None, 'の', True], ['点', 'てん', None, True], [None, None, 'から', True], ['考', 'かんが', None, True], [None, None, 'えると', True], ['砂糖', 'さとう', None, None], [None, None, 'の', None], ['多', 'おお', None, None], [None, None, 'い', None], ['食', 'た', None, None], [None, None, 'べ', None], ['物', 'もの', None, None], [None, None, 'を', None], ['食', 'しょく', None, None], [None, None, 'すればするほど', None], ['肥満', 'ひまん', None, None], [None, None, 'の', None], ['可能性', 'かのうせい', None, None], [None, None, 'が', None], ['高', 'たか', None, None], [None, None, 'くなる。', None]]

 70%|███████   | 658/938 [06:55<03:06,  1.50it/s]

[['末', 'すえ', None, None], [None, None, 'っ', None], ['子', 'こ', None, None], [None, None, 'ということは', True], [None, None, '、', None], ['本当', 'ほんとう', None, None], [None, None, 'は', None], ['甘', 'あま', None, None], [None, None, 'えん', None], ['坊', 'ぼう', None, None], [None, None, 'なんじゃない？', None]]
[[None, None, 'ステージに', None], ['立', 'た', None, None], [None, None, 'つ', None], [None, None, 'ということは', True], [None, None, '、', None], ['誰', 'だれ', None, None], [None, None, 'にでもできることではないと', None], ['思', 'おも', None, None], [None, None, 'います。', None]]
[['素直', 'すなお', None, None], [None, None, 'である', None], [None, None, 'ということは', True], [None, None, '、', None], ['君', 'きみ', None, None], [None, None, 'の', None], ['表情', 'ひょうじょう', None, None], [None, None, 'からも', None], ['分', 'わ', None, None], [None, None, 'かります。', None]]
[[None, None, 'ここに', None], ['隙間', 'すきま', None, None], [None, None, 'がある', None], [None, None, 'ということは', True], [None, None, '、', None], ['欠陥', 'けっかん', None, None], ['住宅', 'じゅうたく', None, None], [None, None, 'の', None], ['疑', 'うたが', None, None], [None, None, 'いがある。', None]]
[['彼', 'かれ', None, None], [None, None, 'が', None], ['一人', 'ひとり', None, None], [None, None, 'で', None], ['旅', 'たび', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'ということは', True], [None, None, '、', None], ['大人', 'おとな', None, None], [None, None, 'になったということだ。', None]]

 70%|███████   | 659/938 [06:56<03:31,  1.32it/s]

[[None, None, 'いつか', None], ['自分', 'じぶん', None, None], [None, None, 'も', None], [None, None, 'こんなふうに', True], [None, None, 'なりたい。', None]]
[[None, None, 'どんなふうに', True], [None, None, 'やればいいのか', None], ['分', 'わ', None, None], [None, None, 'からない。', None]]
[[None, None, 'どうすれば', None], [None, None, 'あんなふうに', True], [None, None, 'なれるのだろうか。', None]]
[['兄', 'あに', None, None], [None, None, 'はすぐに', None], ['嘘', 'うそ', None, None], [None, None, 'をつく。', None], ['僕', 'ぼく', None, None], [None, None, 'は', None], [None, None, 'そんなふうに', True], [None, None, 'はなりたくない。', None]]
[['聞', 'き', None, None], [None, None, 'いていない', None], [None, None, 'ふうに', True], ['振舞', 'ふるま', None, None], [None, None, 'っているが、', None], ['本当', 'ほんとう', None, None], [None, None, 'は', None], ['聞', 'き', None, None], [None, None, 'いている。', None]]

 70%|███████   | 660/938 [06:57<03:24,  1.36it/s]

[['父', 'ちち', None, None], [None, None, '：「', None], ['母', 'はは', None, None], [None, None, 'に、', None], ['遅', 'おく', None, None], [None, None, 'れるだろう', None], [None, None, 'という', True], ['風', 'ふう', None, True], [None, None, 'に', True], ['言', 'い', None, None], [None, None, 'って。」', None]]
[['秘書', 'ひしょ', None, None], [None, None, 'が', None], ['仕事', 'しごと', None, None], [None, None, 'を', None], ['辞', 'や', None, None], [None, None, 'める', None], [None, None, 'という', True], ['風', 'ふう', None, True], [None, None, 'に', True], ['聞', 'き', None, None], [None, None, 'いていた。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['命', 'いのち', None, None], [None, None, 'がかかってる', None], [None, None, 'という', True], ['風', 'ふう', None, True], [None, None, 'に', True], ['走', 'はし', None, None], [None, None, 'っていた。', None]]
[['入団', 'にゅうだん', None, None], [None, None, 'してすぐに', None], ['活躍', 'かつやく', None, None], [None, None, 'という', True], ['風', 'ふう', None, True], [None, None, 'に', True], [None, None, 'なかなかいかない。', None]]
[['合格', 'ごうかく', None, None], [None, None, 'は', None], ['堅', 'かた', None, None], [None, None, 'い', None], [None, None, 'という', True], ['風', 'ふう', None, True], [None, None, 'に', True], ['言', 'い', None, None], [None, None, 'われても、やっぱり', None], ['不安', 'ふあん', None, None], [None, None, 'です。', None]]

 70%|███████   | 661/938 [06:58<03:07,  1.47it/s]

[['Ａ', 'エー', None, None], [None, None, 'と', None], ['Ｂ', 'ビー', None, None], [None, None, 'を', None], ['組', 'く', None, None], [None, None, 'み', None], ['合', 'あ', None, None], [None, None, 'わせてみた', None], [None, None, 'ものの', True], [None, None, '、ほとんど', None], ['味', 'あじ', None, None], [None, None, 'が', None], ['変', 'か', None, None], [None, None, 'わらないな。', None]]
[['工夫', 'くふう', None, None], [None, None, 'してみた', None], [None, None, 'ものの', True], [None, None, '、', None], ['結果', 'けっか', None, None], [None, None, 'は', None], ['大', 'たい', None, None], [None, None, 'して', None], ['変', 'か', None, None], [None, None, 'わらない。', None]]
[['自分', 'じぶん', None, None], [None, None, 'で', None], ['組', 'く', None, None], [None, None, 'み', None], ['立', 'た', None, None], [None, None, 'ててみた', None], [None, None, 'ものの', True], [None, None, '、', None], ['見栄', 'みば', None, None], [None, None, 'えが', None], ['悪', 'わる', None, None], [None, None, 'すぎる。', None]]
[[None, None, 'クーラーを', None], ['最大', 'さいだい', None, None], [None, None, 'にしてみた', None], [None, None, 'ものの', True], [None, None, '、', None], ['全然', 'ぜんぜん', None, None], ['涼', 'すず', None, None], [None, None, 'しくならない。', None]]
[['口紅', 'くちべに', None, None], [None, None, 'をつけてみた', None], [None, None, 'ものの', True], [None, None, '、', None], ['全然', 'ぜんぜん', None, None], ['女性', 'じょせい', None, None], [None, None, 'らしく', None], ['見', 'み', None, None], [None, None, 'えないのはなぜ？', None]]

 71%|███████   | 662/938 [06:58<02:56,  1.56it/s]

[[None, None, 'その', None], ['言', 'い', None, None], [None, None, 'い', None], ['分', 'ぶん', None, None], [None, None, 'はわがまま', None], [None, None, 'というものだ', True], [None, None, '。', None]]
[[None, None, 'あなたの', None], ['好', 'す', None, None], [None, None, 'き', None], ['嫌', 'きら', None, None], [None, None, 'いは', None], ['食', 'く', None, None], [None, None, 'わず', None], ['嫌', 'ぎら', None, None], [None, None, 'い', None], [None, None, 'というものだ', True], [None, None, '。', None]]
[['嘘', 'うそ', None, None], [None, None, 'はつかない。それがジャーナリスト', None], [None, None, 'というものだ', True], [None, None, '。', None]]
[['楽', 'たの', None, None], [None, None, 'しくないと', None], ['意味', 'いみ', None, None], [None, None, 'がない。それがサークル', None], [None, None, 'というものだ', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'はいつも', None], ['結果', 'けっか', None, None], [None, None, 'を', None], ['出', 'だ', None, None], [None, None, 'す。あれが', None], ['実力', 'じつりょく', None, None], [None, None, 'というものだ', True], [None, None, '。', None]]

 71%|███████   | 663/938 [06:59<03:01,  1.51it/s]

[['外', 'そと', None, None], [None, None, 'から', True], ['見', 'み', None, True], [None, None, 'ると', True], [None, None, '、やりやすそうです。', None]]
[['老人', 'ろうじん', None, None], ['夫婦', 'ふうふ', None, None], [None, None, 'から', True], ['見', 'み', None, True], [None, None, 'ると', True], [None, None, '、', None], ['若者', 'わかもの', None, None], [None, None, 'の', None], ['恋愛', 'れんあい', None, None], [None, None, 'は', None], ['懐', 'なつ', None, None], [None, None, 'かしい。', None]]
[['普段', 'ふだん', None, None], [None, None, 'から', True], ['見', 'み', None, True], [None, None, 'て', True], [None, None, '、', None], ['今年', 'ことし', None, None], [None, None, 'は', None], ['稀', 'まれ', None, None], [None, None, 'な', None], ['気象', 'きしょう', None, None], [None, None, 'が', None], ['多', 'おお', None, None], [None, None, 'かった。', None]]
[['脇役', 'わきやく', None, None], [None, None, 'から', True], ['見', 'み', None, True], [None, None, 'ると', True], ['主役', 'しゅやく', None, None], [None, None, 'は', None], ['羨', 'うらや', None, None], [None, None, 'ましいが、', None], ['主役', 'しゅやく', None, None], [None, None, 'は', None], ['主役', 'しゅやく', None, None], [None, None, 'で', None], ['大変', 'たいへん', None, None], [None, None, 'らしい。', None]]
[['小学生', 'しょうがくせい', None, None], [None, None, 'から', True], ['見', 'み', None, True], [None, None, 'ると', True], ['中高生', 'ちゅうこうせい', None, None], [None, None, 'は', None], ['大人', 'おとな', None, None], [None, None, 'に', None], ['見', 'み', None, None], [None, None, 'えるが、', None], ['実際', 'じっさい', None, None], [None, None, 'はそうでもない。', None]]

 71%|███████   | 664/938 [07:00<03:06,  1.47it/s]

[['香水', 'こうすい', None, None], [None, None, 'をつけている', None], [None, None, 'ところを', True], ['見', 'み', None, True], [None, None, 'ると', True], [None, None, '、お', None], ['出掛', 'でか', None, None], [None, None, 'けですね？', None]]
[['心当', 'こころあ', None, None], [None, None, 'たりがない', None], [None, None, 'ところを', True], ['見', 'み', None, True], [None, None, 'ると', True], [None, None, '、', None], ['誤解', 'ごかい', None, None], [None, None, 'かもしれない。', None]]
[[None, None, 'このタイミングで', None], ['交替', 'こうたい', None, None], [None, None, 'した', None], [None, None, 'ところを', True], ['見', 'み', None, True], [None, None, 'ると', True], [None, None, '、あのピッチャーは', None], ['怪我', 'けが', None, None], [None, None, 'をしたのかもしれない。', None]]
[['彼', 'かれ', None, None], [None, None, 'が', None], ['落', 'お', None, None], [None, None, 'ち', None], ['込', 'こ', None, None], [None, None, 'んでいる', None], [None, None, 'ところを', True], ['見', 'み', None, True], [None, None, 'ると', True], [None, None, '、', None], ['恋人', 'こいびと', None, None], [None, None, 'に', None], ['振', 'ふ', None, None], [None, None, 'られたのかもしれない。', None]]
[['焦', 'こ', None, None], [None, None, 'がした', None], [None, None, 'ところを', True], ['見', 'み', None, True], [None, None, 'ると', True], [None, None, '、', None], ['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['料理', 'りょうり', None, None], [None, None, 'が', None], ['苦手', 'にがて', None, None], [None, None, 'なのでしょう。', None]]

 71%|███████   | 665/938 [07:00<02:59,  1.52it/s]

[[None, None, 'あの', None], ['煙突', 'えんとつ', None, None], [None, None, 'からすると', True], [None, None, '、たぶん', None], ['薪', 'まき', None, None], [None, None, 'ストーブですね。', None]]
[['歴史', 'れきし', None, None], [None, None, 'からすると', True], [None, None, '、', None], ['京都', 'きょうと', None, None], [None, None, 'はかつて', None], ['首都', 'しゅと', None, None], [None, None, 'でした。', None]]
[[None, None, 'あなたが', None], ['言', 'い', None, None], [None, None, 'っていること', None], [None, None, 'からすると', True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'はそこにいなかったようですね。', None]]
[['足', 'あし', None, None], [None, None, 'の', None], ['速', 'はや', None, None], [None, None, 'さ', None], [None, None, 'からすると', True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'はプロの', None], ['選手', 'せんしゅ', None, None], [None, None, 'になれるだろう。', None]]
[[None, None, 'あのアクセント', None], [None, None, 'からすると', True], ['彼', 'かれ', None, None], [None, None, 'は', None], ['日本人', 'にほんじん', None, None], [None, None, 'ではないようです。', None]]

 71%|███████   | 666/938 [07:01<02:53,  1.57it/s]

[[None, None, 'このスープは', None], ['匂', 'にお', None, None], [None, None, 'い', None], [None, None, 'からして', True], ['美味', 'おい', None, None], [None, None, 'しそうだ。', None]]
[[None, None, 'あの', None], ['演奏', 'えんそう', None, None], [None, None, 'からして', True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'は', None], ['楽器', 'がっき', None, None], [None, None, 'のプロだ。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['感覚', 'かんかく', None, None], [None, None, 'からして', True], [None, None, '、このスイカは', None], ['甘', 'あま', None, None], [None, None, 'いと', None], ['思', 'おも', None, None], [None, None, 'う。', None]]
[[None, None, 'あの', None], ['看板', 'かんばん', None, None], [None, None, 'からして', True], [None, None, '、', None], ['店', 'みせ', None, None], [None, None, 'の', None], ['中', 'なか', None, None], [None, None, 'もきっとオシャレなのだろう。', None]]
[['稽古', 'けいこ', None, None], [None, None, 'の', None], ['内容', 'ないよう', None, None], [None, None, 'からして', True], [None, None, '、あの', None], ['先生', 'せんせい', None, None], [None, None, 'は', None], ['厳', 'きび', None, None], [None, None, 'しそうだ。', None]]

 71%|███████   | 667/938 [07:01<02:46,  1.63it/s]

[[None, None, 'ご', None], ['機嫌', 'きげん', None, None], ['斜', 'なな', None, None], [None, None, 'め', None], [None, None, 'だからといって', True], [None, None, '、', None], ['八', 'や', None, None], [None, None, 'つ', None], ['当', 'あ', None, None], [None, None, 'たりしないで。', None]]
[['丼物', 'どんぶりもの', None, None], [None, None, 'だからといって', True], [None, None, '、', None], ['安', 'やす', None, None], [None, None, 'いとは', None], ['限', 'かぎ', None, None], [None, None, 'りません。', None]]
[['慰', 'なぐさ', None, None], [None, None, 'められた', None], [None, None, 'からといって', True], [None, None, '、すぐに', None], ['気持', 'きも', None, None], [None, None, 'ちは', None], ['晴', 'は', None, None], [None, None, 'れない。', None]]
[['懐', 'なつ', None, None], [None, None, 'かしい', None], [None, None, 'からといって', True], [None, None, '、なんでもすぐに', None], ['買', 'か', None, None], [None, None, 'うのはやめてください。', None]]
[['憎', 'にく', None, None], [None, None, 'い', None], [None, None, 'からといって', True], [None, None, '、', None], ['人', 'ひと', None, None], [None, None, 'を', None], ['殺', 'ころ', None, None], [None, None, 'していいわけないでしょ。', None]]

 71%|███████   | 668/938 [07:02<02:42,  1.67it/s]

[[None, None, 'そういえば', True], [None, None, '、', None], ['今日', 'きょう', None, None], [None, None, 'は', None], ['母', 'はは', None, None], [None, None, 'の', None], ['日', 'ひ', None, None], [None, None, 'だ。', None]]
[[None, None, 'そういえば', True], [None, None, '、', None], ['昨夜', 'さくや', None, None], [None, None, 'は', None], ['何時', 'なんじ', None, None], [None, None, 'に', None], ['家', 'いえ', None, None], [None, None, 'に', None], ['帰', 'かえ', None, None], [None, None, 'ったの？', None]]
[[None, None, 'そういえば', True], [None, None, '、', None], ['着替', 'きが', None, None], [None, None, 'え', None], ['持', 'も', None, None], [None, None, 'ってきてくれた？', None]]
[[None, None, 'そういえば', True], [None, None, '、', None], ['昨日', 'きのう', None, None], [None, None, 'の', None], ['卒業式', 'そつぎょうしき', None, None], [None, None, 'はどうだった？', None]]
[[None, None, 'そういえば', True], [None, None, '、', None], ['客席', 'きゃくせき', None, None], [None, None, 'に', None], ['君', 'きみ', None, None], [None, None, 'のお', None], ['父', 'とう', None, None], [None, None, 'さんとお', None], ['母', 'かあ', None, None], [None, None, 'さんがいたよ。', None]]

 71%|███████▏  | 669/938 [07:03<02:51,  1.57it/s]

[['書類', 'しょるい', None, None], [None, None, 'のこの', None], ['下', 'した', None, None], [None, None, 'にサイン', None], ['願', 'ねが', None, True], [None, None, 'います', True], [None, None, '。', None]]
[['問題', 'もんだい', None, None], [None, None, 'が', None], ['起', 'お', None, None], [None, None, 'こった', None], ['場合', 'ばあい', None, None], [None, None, 'は', None], [None, None, 'ご', True], ['連絡', 'れんらく', None, True], ['願', 'ねが', None, True], [None, None, 'います', True], [None, None, '。', None]]
[[None, None, 'ここは', None], ['図書館', 'としょかん', None, None], [None, None, 'です。', None], [None, None, 'お', True], ['静', 'しず', None, True], [None, None, 'かに', True], ['願', 'ねが', None, True], [None, None, 'います', True], [None, None, '。', None]]
[['一週間', 'いっしゅうかん', None, None], ['以内', 'いない', None, None], [None, None, 'に', None], [None, None, 'お', True], ['返事', 'へんじ', None, True], ['願', 'ねが', None, True], [None, None, 'います', True], [None, None, '。', None]]
[[None, None, 'この', None], ['文章', 'ぶんしょう', None, None], [None, None, 'で', None], ['間違', 'まちが', None, None], [None, None, 'いないか、', None], [None, None, 'ご', True], ['確認', 'かくにん', None, True], ['願', 'ねが', None, True], [None, None, 'います', True], [None, None, '。', None]]

 71%|███████▏  | 670/938 [07:03<03:00,  1.49it/s]

[[None, None, 'お', None], ['母', 'かあ', None, None], [None, None, 'さん、そこのリモコンを、', None], ['取', 'と', None, True], [None, None, 'ってちょうだい', True], [None, None, '。', None]]
[['今', 'いま', None, None], ['忙', 'いそが', None, None], [None, None, 'しいんだから、', None], ['私', 'わたし', None, None], [None, None, 'に', None], ['構', 'かま', None, True], [None, None, 'わないでちょうだい', True], [None, None, '！', None]]
[['会議室', 'かいぎしつ', None, None], [None, None, 'の', None], ['予約', 'よやく', None, None], [None, None, 'を', None], [None, None, 'してちょうだい', True], [None, None, '。', None]]
[[None, None, '「', None], ['私', 'わたし', None, None], [None, None, 'のために…', None], ['世界', 'せかい', None, None], [None, None, 'を', None], ['救', 'すく', None, True], [None, None, 'ってちょうだい', True], [None, None, '♡」と', None], ['姫', 'ひめ', None, None], [None, None, 'が', None], ['仰', 'おお', None, None], [None, None, 'せです。', None]]
[[None, None, 'おばあちゃんに、', None], ['白菜', 'はくさい', None, None], [None, None, 'を', None], ['届', 'とど', None, None], [None, None, 'けに', None], ['行', 'い', None, True], [None, None, 'って', True], ['来', 'き', None, True], [None, None, 'てちょうだい', True], [None, None, '！', None]]

 72%|███████▏  | 671/938 [07:04<02:44,  1.62it/s]

[['納豆', 'なっとう', None, None], [None, None, 'は', None], ['体', 'からだ', None, None], [None, None, 'にいいんだ', None], [None, None, 'とか', True], [None, None, '。', None]]
[[None, None, 'このワンピースは', None], ['体型', 'たいけい', None, None], [None, None, 'をカバーする', None], [None, None, 'とか', True], [None, None, '。', None]]
[['ＡＫＢ', 'えーけーびー', None, None], ['４８', 'ふぉーてぃーえいと', None, None], [None, None, 'という', None], ['音楽', 'おんがく', None, None], [None, None, 'グループは', None], ['解散', 'かいさん', None, None], [None, None, 'する', None], [None, None, 'とか', True], [None, None, '。', None]]
[['最近', 'さいきん', None, None], [None, None, 'はカラーサングラスが', None], ['流行', 'はや', None, None], [None, None, 'っている', None], [None, None, 'とか', True], [None, None, '。', None]]
[[None, None, 'お', None], ['母', 'かあ', None, None], [None, None, 'さんが', None], ['朝', 'あさ', None, None], [None, None, 'ごはんを', None], ['食', 'た', None, None], [None, None, 'べるのは', None], ['大事', 'だいじ', None, None], [None, None, 'だ', None], [None, None, 'とか', True], ['言', 'い', None, None], [None, None, 'っていた。', None]]

 72%|███████▏  | 672/938 [07:04<02:45,  1.60it/s]

[['彼', 'かれ', None, None], [None, None, 'の', None], ['成功', 'せいこう', None, None], [None, None, 'を', None], ['信', 'しん', None, True], [None, None, 'じようではないか', True], [None, None, '。', None]]
[['共', 'とも', None, None], [None, None, 'に', None], ['素晴', 'すば', None, None], [None, None, 'らしい', None], ['世界', 'せかい', None, None], [None, None, 'を', None], ['創', 'つく', None, True], [None, None, 'っていこうではないか', True], [None, None, '。', None]]
[['日本語', 'にほんご', None, None], [None, None, 'を', None], ['身', 'み', None, None], [None, None, 'につけるために', None], ['頑張', 'がんば', None, True], [None, None, 'ろうではないか', True], [None, None, '。', None]]
[[None, None, 'この', None], ['瀬戸物', 'せともの', None, None], [None, None, 'をちゃんと', None], ['鑑定', 'かんてい', None, None], [None, None, 'してもらおうではないか', True], [None, None, '。', None]]
[['意見', 'いけん', None, None], [None, None, 'の', None], ['相違', 'そうい', None, None], [None, None, 'があっても、', None], ['話', 'はな', None, True], [None, None, 'し', True], ['合', 'あ', None, True], [None, None, 'おうではないか', True], [None, None, '。', None]]

 72%|███████▏  | 673/938 [07:05<02:41,  1.64it/s]

[[None, None, 'その', None], ['作品', 'さくひん', None, None], [None, None, 'は、あの', None], ['有名', 'ゆうめい', None, None], [None, None, 'な', None], ['作品', 'さくひん', None, None], [None, None, 'を', None], ['真似', 'まね', None, None], [None, None, 'た', None], [None, None, 'かのようです', True], [None, None, 'ね。', None]]
[['彼', 'かれ', None, None], [None, None, 'はまるでお', None], ['腹', 'なか', None, None], [None, None, 'に', None], ['風船', 'ふうせん', None, None], [None, None, 'を', None], ['入', 'い', None, None], [None, None, 'れている', None], [None, None, 'かのようだ', True], [None, None, '。', None]]
[[None, None, 'あの', None], ['会社', 'かいしゃ', None, None], [None, None, 'は', None], ['営業', 'えいぎょう', None, None], ['中', 'ちゅう', None, None], [None, None, 'も', None], ['休業', 'きゅうぎょう', None, None], [None, None, 'している', None], [None, None, 'かのようだ', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['相当', 'そうとう', None, None], ['目', 'め', None, None], [None, None, 'がいい。', None], ['望遠鏡', 'ぼうえんきょう', None, None], [None, None, 'を', None], ['使', 'つか', None, None], [None, None, 'っている', None], [None, None, 'かのようだ', True], [None, None, '。', None]]
[[None, None, 'あのシャツの', None], ['色', 'いろ', None, None], [None, None, 'と', None], ['柄', 'がら', None, None], [None, None, 'じゃあ、', None], ['包帯', 'ほうたい', None, None], [None, None, 'をしている', None], [None, None, 'かのようです', True], [None, None, 'ね。', None]]

 72%|███████▏  | 674/938 [07:06<02:34,  1.71it/s]

[['彼', 'かれ', None, None], [None, None, 'はもしかして、あきれている', None], [None, None, 'の', None], [None, None, 'ではないだろうか', True], [None, None, '。', None]]
[[None, None, 'あそこに', None], ['見', 'み', None, None], [None, None, 'えるのは、', None], ['虹', 'にじ', None, None], [None, None, 'ではないだろうか', True], [None, None, '。', None]]
[[None, None, 'この', None], ['症状', 'しょうじょう', None, None], [None, None, '、', None], ['伝染病', 'でんせんびょう', None, None], [None, None, 'ではないだろうか', True], [None, None, '。', None]]
[[None, None, 'この', None], ['調子', 'ちょうし', None, None], [None, None, 'だと、', None], ['停電', 'ていでん', None, None], [None, None, 'が', None], ['長引', 'ながび', None, None], [None, None, 'く', None], [None, None, 'のではないだろうか', True], [None, None, '。', None]]
[[None, None, 'こんなお', None], ['願', 'ねが', None, None], [None, None, 'いをしてしまって、', None], ['厚', 'あつ', None, None], [None, None, 'かましかった', None], [None, None, 'のではないだろうか', True], [None, None, '。', None]]

 72%|███████▏  | 675/938 [07:06<02:37,  1.67it/s]

[[None, None, 'そんなに', None], ['食', 'た', None, None], [None, None, 'べたら、', None], ['太', 'ふと', None, True], [None, None, 'って', True], ['当然', 'とうぜん', None, True], [None, None, 'だ。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['厚', 'あつ', None, None], [None, None, 'かましいから、', None], ['避', 'さ', None, True], [None, None, 'けられて', True], ['当然', 'とうぜん', None, True], [None, None, 'だ。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['優', 'やさ', None, None], [None, None, 'しいから、', None], ['好', 'す', None, True], [None, None, 'かれて', True], ['当然', 'とうぜん', None, True], [None, None, 'だ。', None]]
[[None, None, 'アイデアがいいから、', None], ['人気', 'にんき', None, None], [None, None, 'が', None], [None, None, 'あって', True], ['当然', 'とうぜん', None, True], [None, None, 'だ。', None]]
[['脂', 'あぶら', None, None], [None, None, 'を', None], ['取', 'と', None, None], [None, None, 'り', None], ['過', 'す', None, None], [None, None, 'ぎたら、', None], ['気持', 'きも', None, None], [None, None, 'ち', None], ['悪', 'わる', None, True], [None, None, 'くなって', True], ['当然', 'とうぜん', None, True], [None, None, 'だ。', None]]

 72%|███████▏  | 676/938 [07:07<02:28,  1.77it/s]

[['税金', 'ぜいきん', None, None], [None, None, 'を', None], ['納', 'おさ', None, None], [None, None, 'めていないんだから、', None], ['逮捕', 'たいほ', None, None], [None, None, 'される', None], [None, None, 'のも', True], ['当然', 'とうぜん', None, True], [None, None, 'です。', None]]
[['練習', 'れんしゅう', None, None], [None, None, 'を', None], ['怠', 'おこた', None, None], [None, None, 'ったんだから、ああいう', None], ['結果', 'けっか', None, None], [None, None, 'になる', None], [None, None, 'のも', True], ['当然', 'とうぜん', None, True], [None, None, 'だ。', None]]
[[None, None, 'そんなマッチョな', None], ['体型', 'たいけい', None, None], [None, None, 'では、エプロンが', None], ['似合', 'にあ', None, None], [None, None, 'わない', None], [None, None, 'のも', True], ['当然', 'とうぜん', None, True], [None, None, 'だ。', None]]
[['彼', 'かれ', None, None], [None, None, 'があんな', None], ['風', 'ふう', None, None], [None, None, 'に', None], ['振舞', 'ふるま', None, None], [None, None, 'っていたなら、ほかの', None], ['人', 'ひと', None, None], [None, None, 'からの', None], ['受', 'う', None, None], [None, None, 'けが', None], ['悪', 'わる', None, None], [None, None, 'い', None], [None, None, 'のも', True], ['当然', 'とうぜん', None, True], [None, None, 'だ。', None]]
[['久', 'ひさ', None, None], [None, None, 'しぶりに', None], ['彼', 'かれ', None, None], [None, None, 'に', None], ['会', 'あ', None, None], [None, None, 'ったのだから、', None], ['彼女', 'かのじょ', None, None], [None, None, 'が', None], ['嬉', 'うれ', None, None], [None, None, 'しそうな', None], [None, None, 'のは', True], ['当然', 'とうぜん', None, True], [None, None, 'だ。', None]]

 72%|███████▏  | 677/938 [07:07<02:22,  1.83it/s]

[[None, None, '「', None], ['彼', 'かれ', None, None], [None, None, 'は', None], [None, None, 'たった', True], ['一人', 'ひとり', None, None], [None, None, 'の', None], ['兄弟', 'きょうだい', None, None], [None, None, 'です。」', None]]
[['友達', 'ともだち', None, None], ['１', 'いち', None, None], [None, None, '：「', None], ['１０００', 'せん', None, None], ['円', 'えん', None, None], ['貸', 'か', None, None], [None, None, 'してくれる？」', None], ['友達', 'ともだち', None, None], ['２', 'に', None, None], [None, None, '：「', None], [None, None, 'たった', True], ['５００', 'ごひゃく', None, None], ['円', 'えん', None, None], [None, None, 'しかないよ。」', None]]
[[None, None, 'そうまさん', None], [None, None, '：「ケーキ、', None], ['出来', 'でき', None, None], [None, None, 'ました。」', None], [None, None, 'えりなさん', None], [None, None, '：「え、', None], [None, None, 'たった', True], ['５', 'ご', None, None], ['分', 'ふん', None, None], [None, None, 'で', None], ['出来', 'でき', None, None], [None, None, 'たの？！」', None]]
[['自分', 'じぶん', None, None], [None, None, 'の', None], ['子供', 'こども', None, None], [None, None, 'について、', None], ['母親', 'ははおや', None, None], [None, None, '：「ケビンはずっと、', None], [None, None, 'たった', True], [None, None, 'ひとりで', None], ['家', 'いえ', None, None], [None, None, 'にいた！！」', None]]
[['市場', 'いちば', None, None], [None, None, 'の', None], ['商人', 'しょうにん', None, None], [None, None, '：「', None], ['安', 'やす', None, None], [None, None, 'いよ、', None], ['安', 'やす', None, None], [None, None, 'いよ、りっぱな', None], ['高級', 'こうきゅう', None, None], ['時計', 'どけい', None, None], [None, None, 'が', None], [None, None, 'たった', True], ['千', 'せん', None, None], ['円', 'えん', None, None], [None, None, '。」', None]]

 72%|███████▏  | 678/938 [07:08<02:19,  1.86it/s]

[[None, None, 'お', None], ['辞儀', 'じぎ', None, None], [None, None, 'をしすぎると', None], ['腰', 'こし', None, None], [None, None, 'を', None], ['痛', 'いた', None, None], [None, None, 'める', None], ['恐', 'おそ', None, True], [None, None, 'れがある', True], [None, None, '。', None]]
[['教', 'おそ', None, None], [None, None, 'わっても', None], ['忘', 'わす', None, None], [None, None, 'れる', None], ['恐', 'おそ', None, True], [None, None, 'れがある', True], [None, None, 'から、メモしておこう。', None]]
[[None, None, 'このオイルだとエンジンに', None], ['負担', 'ふたん', None, None], [None, None, 'をかける', None], ['恐', 'おそ', None, True], [None, None, 'れがある', True], [None, None, 'からやめたほうがいい。', None]]
[[None, None, 'あの', None], ['勢', 'いきお', None, None], [None, None, 'いでお', None], ['代', 'か', None, None], [None, None, 'わりされると、ご', None], ['飯', 'はん', None, None], [None, None, 'が', None], ['足', 'た', None, None], [None, None, 'りなくなる', None], ['恐', 'おそ', None, True], [None, None, 'れがある', True], [None, None, '。', None]]
[[None, None, 'この', None], ['絵', 'え', None, None], [None, None, 'の', None], ['具', 'ぐ', None, None], [None, None, 'は', None], ['中身', 'なかみ', None, None], [None, None, 'が', None], ['漏', 'も', None, None], [None, None, 'れる', None], ['恐', 'おそ', None, True], [None, None, 'れがある', True], [None, None, 'から', None], ['袋', 'ふくろ', None, None], [None, None, 'に', None], ['入', 'い', None, None], [None, None, 'れてください。', None]]

 72%|███████▏  | 679/938 [07:08<02:34,  1.68it/s]

[['恐', 'おそ', None, True], [None, None, 'らく', True], ['彼', 'かれ', None, None], [None, None, 'はここにいないだろう。', None]]
[['恐', 'おそ', None, True], [None, None, 'らく', True], ['明日', 'あした', None, None], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'る。', None]]
[['彼', 'かれ', None, None], [None, None, 'だったら、', None], ['恐', 'おそ', None, True], [None, None, 'らく', True], [None, None, 'こんなことできっこないでしょう。', None]]
[[None, None, '「くそ、', None], ['恐', 'おそ', None, True], [None, None, 'らく', True], [None, None, 'あなたの', None], ['結婚式', 'けっこんしき', None, None], [None, None, 'には', None], ['行', 'い', None, None], [None, None, 'けないじゃないか。」', None]]
[['道路', 'どうろ', None, None], [None, None, 'に', None], ['沿', 'そ', None, None], [None, None, 'って', None], ['行', 'い', None, None], [None, None, 'けば', None], ['恐', 'おそ', None, True], [None, None, 'らく', True], [None, None, 'ガソリンスタンドが', None], ['見', 'み', None, None], [None, None, 'つかるでしょう。', None]]

 72%|███████▏  | 680/938 [07:09<02:25,  1.77it/s]

[[None, None, 'あんなひどいこと', None], ['言', 'い', None, None], [None, None, 'われたんだ。', None], ['平気', 'へいき', None, None], [None, None, 'なものか', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'が', None], ['皮肉', 'ひにく', None, None], [None, None, 'なんて', None], ['言', 'い', None, None], [None, None, 'う', None], [None, None, 'ものか', True], [None, None, '。そういう', None], ['奴', 'やつ', None, None], [None, None, 'じゃない。', None]]
[[None, None, 'そんな', None], ['安', 'やす', None, None], [None, None, 'っぽい', None], ['言葉', 'ことば', None, None], [None, None, 'が', None], ['心', 'こころ', None, None], [None, None, 'に', None], ['響', 'ひび', None, None], [None, None, 'く', None], [None, None, 'ものか', True], [None, None, '。', None]]
[[None, None, 'それくらいの', None], ['研究', 'けんきゅう', None, None], [None, None, 'で', None], ['理解', 'りかい', None, None], [None, None, 'など', None], ['深', 'ふか', None, None], [None, None, 'まる', None], [None, None, 'ものか', True], [None, None, '。', None]]
[[None, None, 'あの', None], ['山', 'やま', None, None], [None, None, 'が', None], ['噴火', 'ふんか', None, None], [None, None, 'する', None], [None, None, 'ものか', True], [None, None, '。あれは', None], ['火山', 'かざん', None, None], [None, None, 'じゃない。', None]]

 73%|███████▎  | 681/938 [07:09<02:21,  1.82it/s]

[['家', 'いえ', None, None], [None, None, 'を', None], ['掃除', 'そうじ', None, None], [None, None, 'した。', None], ['御負', 'おま', None, True], [None, None, 'けに', True], [None, None, 'ランチを', None], ['作', 'つく', None, None], [None, None, 'っといた。', None]]
[['宝石', 'ほうせき', None, None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'ったら、', None], ['御負', 'おま', None, True], [None, None, 'けに', True], ['香水', 'こうすい', None, None], [None, None, 'をサービスしてくれた。', None]]
[['自転車', 'じてんしゃ', None, None], [None, None, 'が', None], ['盗', 'ぬす', None, None], [None, None, 'まれただけではなく、', None], ['御負', 'おま', None, True], [None, None, 'けに', True], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'お', None, None], [None, None, 'りそうだ。', None]]
[['競馬', 'けいば', None, None], [None, None, 'で', None], ['負', 'ま', None, None], [None, None, 'け、', None], ['御負', 'おま', None, True], [None, None, 'けに', True], ['帰', 'かえ', None, None], [None, None, 'りに', None], ['財布', 'さいふ', None, None], [None, None, 'を', None], ['落', 'お', None, None], [None, None, 'とし、', None], ['最悪', 'さいあく', None, None], [None, None, 'だ。', None]]
[['体重', 'たいじゅう', None, None], [None, None, 'が', None], ['激増', 'げきぞう', None, None], [None, None, 'し、', None], ['御負', 'おま', None, True], [None, None, 'けに', True], ['髪', 'かみ', None, None], [None, None, 'まで', None], ['薄', 'うす', None, None], [None, None, 'くなった。ストレスですね。', None]]

 73%|███████▎  | 682/938 [07:10<02:17,  1.87it/s]

[[None, None, 'あの', None], ['店', 'みせ', None, None], [None, None, 'のトロはどれも', None], ['脂', 'あぶら', None, None], [None, None, 'がのっている', None], [None, None, 'に', True], ['決', 'き', None, True], [None, None, 'まっている', True], [None, None, '。', None]]
[[None, None, 'このセーター、ウール１００', None], ['％', 'ひゃくパーセント', None, None], [None, None, 'でしょ？', None], ['高', 'たか', None, None], [None, None, 'い', None], [None, None, 'に', True], ['決', 'き', None, True], [None, None, 'まっています', True], [None, None, '。', None]]
[['毎日', 'まいにち', None, None], [None, None, 'お', None], ['菓子', 'かし', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べることはダメ', None], [None, None, 'に', True], ['決', 'き', None, True], [None, None, 'まっている', True], [None, None, '！', None]]
[['彼', 'かれ', None, None], [None, None, 'のことだから、あいかわらずいい', None], ['人', 'ひと', None, None], [None, None, 'に', True], ['決', 'き', None, True], [None, None, 'まっている', True], [None, None, '。', None]]
[[None, None, 'かなりひどいことを', None], ['言', 'い', None, None], [None, None, 'ってしまったから、', None], ['恨', 'うら', None, None], [None, None, 'んでいる', None], [None, None, 'に', True], ['決', 'き', None, True], [None, None, 'まっている', True], [None, None, '。', None]]

 73%|███████▎  | 683/938 [07:10<02:16,  1.87it/s]

[[None, None, 'この', None], ['寮', 'りょう', None, None], [None, None, 'では、', None], ['起床', 'きしょう', None, None], ['時間', 'じかん', None, None], [None, None, 'は', None], ['６', 'ろく', None, None], ['時', 'じ', None, None], [None, None, 'という', None], [None, None, 'ことになっている', True], [None, None, '。', None]]
[['来年', 'らいねん', None, None], [None, None, 'も', None], ['契約', 'けいやく', None, None], [None, None, 'を', None], ['更新', 'こうしん', None, None], [None, None, 'する', None], [None, None, 'ことになっています', True], [None, None, '。', None]]
[['来週', 'らいしゅう', None, None], [None, None, 'あの', None], ['工場', 'こうじょう', None, None], [None, None, 'を', None], ['見学', 'けんがく', None, None], [None, None, 'する', None], [None, None, 'ことになっています', True], [None, None, '。', None]]
[['原稿', 'げんこう', None, None], [None, None, 'は、', None], ['郵送', 'ゆうそう', None, None], [None, None, 'ではなく、メールで', None], ['送', 'おく', None, None], [None, None, 'る', None], [None, None, 'ことになっている', True], [None, None, '。', None]]
[['会議', 'かいぎ', None, None], [None, None, 'は', None], ['東京', 'とうきょう', None, None], [None, None, 'にある', None], ['官庁', 'かんちょう', None, None], [None, None, 'で', None], ['行', 'おこな', None, None], [None, None, 'う', None], [None, None, 'ことになっている', True], [None, None, '。', None]]

 73%|███████▎  | 684/938 [07:11<02:14,  1.88it/s]

[['誰', 'だれ', None, None], [None, None, 'かに', None], ['見', 'み', None, True], [None, None, 'られている', True], ['気', 'き', None, True], [None, None, 'がする。', None]]
[['何', 'なに', None, None], [None, None, 'も', None], [None, None, 'やる', True], ['気', 'き', None, True], [None, None, 'が', None], ['起', 'お', None, None], [None, None, 'きない。', None]]
[['応援', 'おうえん', None, None], [None, None, 'されて、', None], [None, None, 'やる', True], ['気', 'き', None, True], [None, None, 'が', None], ['出', 'で', None, None], [None, None, 'た。', None]]
[['娘', 'むすめ', None, None], [None, None, 'は', None], ['好', 'す', None, None], [None, None, 'き', None], ['嫌', 'きら', None, None], [None, None, 'いが', None], ['多', 'おお', None, True], [None, None, 'すぎる', True], ['気', 'き', None, True], [None, None, 'がする。', None]]
[['彼', 'かれ', None, None], [None, None, 'の', None], ['送別', 'そうべつ', None, None], ['会', 'かい', None, None], [None, None, 'には', None], ['行', 'い', None, True], [None, None, 'く', True], ['気', 'き', None, True], [None, None, 'がしない。', None]]

 73%|███████▎  | 685/938 [07:11<02:11,  1.92it/s]

[['教養', 'きょうよう', None, None], [None, None, 'がありすぎて', None], ['可愛', 'かわい', None, True], ['気', 'げ', None, True], [None, None, 'がないのもどうかと', None], ['思', 'おも', None, None], [None, None, 'う。', None]]
[['彼', 'かれ', None, None], [None, None, 'が', None], ['恥', 'は', None, True], [None, None, 'ずかし', True], ['気', 'げ', None, True], [None, None, 'に', True], ['自分', 'じぶん', None, None], [None, None, 'の', None], ['弱点', 'じゃくてん', None, None], [None, None, 'を', None], ['教', 'おし', None, None], [None, None, 'えてくれた。', None]]
[['涼', 'すず', None, True], [None, None, 'し', True], ['気', 'げ', None, True], [None, None, 'な', True], ['顔', 'かお', None, None], [None, None, 'でマラソンを', None], ['走', 'はし', None, None], [None, None, 'りきるんだから', None], ['大', 'たい', None, None], [None, None, 'したもんだよ。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'はとても', None], ['素直', 'すなお', None, None], [None, None, 'だが、どことなく', None], ['儚', 'はかな', None, True], ['気', 'げ', None, True], [None, None, 'な', True], [None, None, 'のが', None], ['気', 'き', None, None], [None, None, 'になります。', None]]
[['子供', 'こども', None, None], [None, None, 'たちが', None], ['羨', 'うらや', None, True], [None, None, 'まし', True], ['気', 'げ', None, True], [None, None, 'に', True], ['見', 'み', None, None], [None, None, 'ているから、お', None], ['菓子', 'かし', None, None], [None, None, 'を', None], ['分', 'わ', None, None], [None, None, 'けてあげた。', None]]

 73%|███████▎  | 686/938 [07:12<02:12,  1.90it/s]

[['神様', 'かみさま', None, None], [None, None, 'のことだから', True], [None, None, '、', None], ['必', 'かなら', None, None], [None, None, 'ず', None], ['助', 'たす', None, None], [None, None, 'けてくれます。', None]]
[[None, None, 'あなた', None], [None, None, 'のことだから', True], ['間違', 'まちが', None, None], [None, None, 'いなくうまくいくと', None], ['思', 'おも', None, None], [None, None, 'うよ。', None]]
[[None, None, 'あれは', None], ['基礎', 'きそ', None, None], ['問題', 'もんだい', None, None], [None, None, 'という', None], [None, None, 'ことだから', True], [None, None, '、', None], ['簡単', 'かんたん', None, None], [None, None, 'だったでしょ？', None]]
[['彼', 'かれ', None, None], [None, None, 'の', None], ['勘違', 'かんちが', None, None], [None, None, 'いという', None], [None, None, 'ことだから', True], [None, None, '、', None], ['許', 'ゆる', None, None], [None, None, 'してやってほしい。', None]]
[[None, None, 'いつもウソをついている', None], ['彼', 'かれ', None, None], [None, None, 'のことだから', True], [None, None, '、', None], ['今回', 'こんかい', None, None], [None, None, 'も', None], ['信', 'しん', None, None], [None, None, 'じがたい。', None]]

 73%|███████▎  | 687/938 [07:13<02:10,  1.93it/s]

[['郊外', 'こうがい', None, None], [None, None, 'に', None], ['家', 'いえ', None, None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'った', None], [None, None, 'ものだから', True], [None, None, '、', None], ['通勤', 'つうきん', None, None], [None, None, 'に', None], ['２', 'に', None, None], ['時間', 'じかん', None, None], [None, None, 'もかかる。', None]]
[['税関', 'ぜいかん', None, None], [None, None, 'に', None], ['引', 'ひ', None, None], [None, None, 'っかかった', None], [None, None, 'ものだから', True], [None, None, '、', None], ['遅', 'おそ', None, None], [None, None, 'くなってしまいました。', None]]
[['素人', 'しろうと', None, None], [None, None, 'が', None], ['制作', 'せいさく', None, None], [None, None, 'した', None], [None, None, 'ものだから', True], [None, None, '、やっぱりすぐに', None], ['壊', 'こわ', None, None], [None, None, 'れてしまった。', None]]
[['英語', 'えいご', None, None], [None, None, 'が', None], ['苦手', 'にがて', None, None], [None, None, 'なものだから', True], [None, None, '、', None], ['海外', 'かいがい', None, None], ['旅行', 'りょこう', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'くのは', None], ['楽', 'たの', None, None], [None, None, 'しくない。', None]]
[['墨', 'すみ', None, None], [None, None, 'で', None], ['黒', 'くろ', None, None], [None, None, 'く', None], ['塗', 'ぬ', None, None], [None, None, 'ってしまった', None], [None, None, 'ものだから', True], [None, None, '、', None], ['何', 'なん', None, None], [None, None, 'て', None], ['書', 'か', None, None], [None, None, 'いてあったか', None], ['分', 'わ', None, None], [None, None, 'からない。', None]]

 73%|███████▎  | 688/938 [07:13<02:12,  1.89it/s]

[['売上', 'うりあげ', None, None], [None, None, 'が', None], ['良', 'よ', None, None], [None, None, 'かった', None], [None, None, 'ものですから', True], [None, None, '、', None], ['発注', 'はっちゅう', None, None], [None, None, 'しすぎてしまいました。', None]]
[['育児', 'いくじ', None, None], [None, None, 'は', None], ['初', 'はじ', None, None], [None, None, 'めて', None], [None, None, 'なものですから', True], [None, None, '、いろいろと', None], ['教', 'おし', None, None], [None, None, 'えてください。', None]]
[['熊', 'くま', None, None], [None, None, 'の', None], ['足跡', 'あしあと', None, None], [None, None, 'があった', None], [None, None, 'ものですから', True], [None, None, '、', None], ['山', 'やま', None, None], [None, None, 'に', None], ['入', 'はい', None, None], [None, None, 'るのはやめました。', None]]
[[None, None, 'アクセントが', None], ['違', 'ちが', None, None], [None, None, 'った', None], [None, None, 'ものですから', True], [None, None, '、', None], ['地元', 'じもと', None, None], [None, None, 'の', None], ['方', 'かた', None, None], [None, None, 'ではないのかと', None], ['思', 'おも', None, None], [None, None, 'いました。', None]]
[['明', 'あ', None, None], [None, None, 'け', None], ['方', 'がた', None, None], [None, None, 'まで', None], ['仕事', 'しごと', None, None], [None, None, 'をしていた', None], [None, None, 'ものですから', True], [None, None, '、もう', None], ['眠', 'ねむ', None, None], [None, None, 'いです。', None]]

 73%|███████▎  | 689/938 [07:14<02:19,  1.78it/s]

[[None, None, 'モナリザには、', None], ['神秘的', 'しんぴてき', None, None], [None, None, 'なものがある', True], [None, None, 'よ。', None]]
[['文房具', 'ぶんぼうぐ', None, None], [None, None, 'には', None], ['魅力', 'みりょく', None, None], ['的', 'てき', None, None], [None, None, 'なものがある', True], [None, None, '。', None]]
[[None, None, 'この', None], ['絵', 'え', None, None], [None, None, 'って、うまく', None], ['説明', 'せつめい', None, None], [None, None, 'できないけどすばらしい', None], [None, None, 'ものがある', True], [None, None, 'よ。', None]]
[['彼', 'かれ', None, None], [None, None, 'の', None], ['遺', 'のこ', None, None], [None, None, 'した', None], ['言葉', 'ことば', None, None], [None, None, 'には', None], ['考', 'かんが', None, None], [None, None, 'えさせられる', None], [None, None, 'ものがあった', True], [None, None, '。', None]]
[['売店', 'ばいてん', None, None], [None, None, 'には', None], ['全然', 'ぜんぜん', None, None], ['売', 'う', None, None], [None, None, 'れない', None], [None, None, 'ものがある', True], [None, None, '。', None]]

 74%|███████▎  | 690/938 [07:14<02:15,  1.82it/s]

[[None, None, 'だが、', None], ['調', 'しら', None, None], [None, None, 'べたデータによると、そのような', None], ['傾向', 'けいこう', None, True], [None, None, 'も', None], ['見', 'み', None, None], [None, None, 'られる', None], [None, None, '。', None]]
[['年月', 'としつき', None, None], [None, None, 'が', None], ['経', 'た', None, None], [None, None, 'つとともにこの', None], ['傾向', 'けいこう', None, True], [None, None, 'が', None], ['見', 'み', None, None], [None, None, 'られる', None], [None, None, 'ようになった。', None]]
[[None, None, 'ハイエンドスマホの', None], ['需要', 'じゅよう', None, None], [None, None, 'は', None], ['最近', 'さいきん', None, None], [None, None, 'ますます', None], ['低下', 'ていか', None, None], [None, None, 'の', None], ['傾向', 'けいこう', None, True], [None, None, 'にある', None], [None, None, '。', None]]
[['健康', 'けんこう', None, None], ['問題', 'もんだい', None, None], [None, None, 'の', None], ['数量', 'すうりょう', None, None], [None, None, 'は', None], ['老化', 'ろうか', None, None], [None, None, 'とともに', None], ['増加', 'ぞうか', None, None], [None, None, 'する', None], ['傾向', 'けいこう', None, True], [None, None, 'がある', None], [None, None, '。', None]]
[['次', 'つぎ', None, None], [None, None, 'に、インフレが', None], ['加速', 'かそく', None, None], [None, None, 'すると', None], ['同時', 'どうじ', None, None], [None, None, 'に', None], ['物価', 'ぶっか', None, None], [None, None, 'も', None], ['増加', 'ぞうか', None, None], [None, None, 'する', None], ['傾向', 'けいこう', None, True], [None, None, 'がある', None], [None, None, '。', None]]

 74%|███████▎  | 691/938 [07:15<02:11,  1.87it/s]

[['彼', 'かれ', None, None], [None, None, 'のこれまでの', None], ['努力', 'どりょく', None, None], [None, None, 'は、', None], ['間違', 'まちが', None, None], [None, None, 'いなく', None], ['高', 'たか', None, None], [None, None, 'い', None], ['評価', 'ひょうか', None, None], [None, None, 'に', True], ['値', 'あたい', None, True], [None, None, 'する', True], [None, None, 'ものであり、', None], ['私', 'わたし', None, None], [None, None, 'たちはその', None], ['功績', 'こうせき', None, None], [None, None, 'を', None], ['正当', 'せいとう', None, None], [None, None, 'に', None], ['認', 'みと', None, None], [None, None, 'めるべきだと', None], ['思', 'おも', None, None], [None, None, 'います。', None]]
[['今年', 'ことし', None, None], ['１', 'いち', None, None], ['年', 'ねん', None, None], [None, None, 'の', None], ['成績', 'せいせき', None, None], [None, None, 'に', None], ['基', 'もと', None, None], [None, None, 'づいて、あなたがプロレベル', None], [None, None, 'に', True], ['値', 'あたい', None, True], [None, None, 'する', True], [None, None, 'かどうかを', None], ['検討', 'けんとう', None, None], [None, None, 'します。', None]]
[['彼', 'かれ', None, None], [None, None, 'の', None], ['行動', 'こうどう', None, None], [None, None, 'は、', None], ['尊敬', 'そんけい', None, None], [None, None, 'に', True], ['値', 'あたい', None, True], [None, None, 'する', True], [None, None, '。', None]]
[[None, None, 'あなたは、', None], ['総理', 'そうり', None, None], [None, None, 'に', True], ['値', 'あたい', None, True], [None, None, 'する', True], ['人間', 'にんげん', None, None], [None, None, 'です。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'の', None], ['論文', 'ろんぶん', None, None], [None, None, 'は、', None], ['十分', 'じゅうぶん', None, None], [None, None, 'に', None], ['出版', 'しゅっぱん', None, None], [None, None, 'に', True], ['値', 'あたい', None, True], [None, None, 'する', True], ['内容', 'ないよう', None, None], [None, None, 'だ。', None]]

 74%|███████▍  | 692/938 [07:15<02:08,  1.92it/s]

[[None, None, 'いつも', None], ['同', 'おな', None, None], [None, None, 'じものを', None], ['忘', 'わす', None, True], [None, None, 'れてしょうがない', True], [None, None, '。', None]]
[[None, None, 'ゲームが', None], [None, None, 'したくてしょうがない', True], [None, None, '。', None]]
[['楽', 'たの', None, True], [None, None, 'しくてしょうがない', True], [None, None, '。', None]]
[[None, None, 'あの', None], ['望遠鏡', 'ぼうえんきょう', None, None], [None, None, 'が', None], ['欲', 'ほ', None, True], [None, None, 'しくてしょうがない', True], [None, None, '。', None]]
[['包帯', 'ほうたい', None, None], [None, None, 'をしているから、', None], ['痒', 'かゆ', None, True], [None, None, 'くてしょうがない', True], [None, None, '。', None]]

 74%|███████▍  | 693/938 [07:16<02:04,  1.97it/s]

[[None, None, 'ご', None], ['馳走', 'ちそう', None, None], [None, None, 'とは', None], ['言', 'い', None, None], [None, None, 'えないが、', None], ['食', 'た', None, None], [None, None, 'べるものがある', None], [None, None, 'だけましだ', True], [None, None, '。', None]]
[['古', 'ふる', None, None], [None, None, 'い', None], ['校舎', 'こうしゃ', None, None], [None, None, 'だが、', None], ['冷房', 'れいぼう', None, None], [None, None, 'がある', None], [None, None, 'だけましだ', True], [None, None, '。', None]]
[[None, None, 'あんな', None], ['大事故', 'だいじこ', None, None], [None, None, 'が', None], ['起', 'お', None, None], [None, None, 'きたのだから、', None], ['命', 'いのち', None, None], [None, None, 'がある', None], [None, None, 'だけましだ', True], [None, None, '。', None]]
[['泥棒', 'どろぼう', None, None], [None, None, 'に', None], ['入', 'はい', None, None], [None, None, 'られたが、', None], ['金庫', 'きんこ', None, None], [None, None, 'が', None], ['無事', 'ぶじ', None, None], [None, None, 'なだけましだ', True], [None, None, '。', None]]
[['上手', 'じょうず', None, None], [None, None, 'な', None], ['部員', 'ぶいん', None, None], [None, None, 'はいなくても、', None], ['部', 'ぶ', None, None], [None, None, 'に', None], ['後輩', 'こうはい', None, None], [None, None, 'がいる', None], [None, None, 'だけましです', True], [None, None, '。', None]]

 74%|███████▍  | 694/938 [07:16<02:06,  1.93it/s]

[['幸', 'さいわ', None, True], [None, None, 'いなことに', True], ['遊', 'あそ', None, None], [None, None, 'ぶ', None], ['時間', 'じかん', None, None], [None, None, 'が', None], ['結構', 'けっこう', None, None], [None, None, 'ある。', None]]
[['幸', 'さいわ', None, True], [None, None, 'いなことに', True], [None, None, '、', None], ['船上', 'せんじょう', None, None], [None, None, 'に', None], ['医者', 'いしゃ', None, None], [None, None, 'がいた。', None]]
[['幸', 'さいわ', None, True], [None, None, 'いなことに', True], ['人', 'ひと', None, None], [None, None, 'を', None], ['集', 'あつ', None, None], [None, None, 'めることができました。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['幸', 'さいわ', None, True], [None, None, 'い', True], [None, None, '、エアバッグのおかげで', None], ['怪我', 'けが', None, None], [None, None, 'をせずに', None], ['済', 'す', None, None], [None, None, 'んだ。', None]]
[['幸', 'さいわ', None, True], [None, None, 'いなことに', True], ['元気', 'げんき', None, None], [None, None, 'な', None], ['赤', 'あか', None, None], [None, None, 'ちゃんが', None], ['生', 'う', None, None], [None, None, 'まれました。', None]]

 74%|███████▍  | 695/938 [07:17<02:05,  1.94it/s]

[[None, None, 'そこまで', None], ['甘', 'あま', None, None], [None, None, 'やかす', None], [None, None, 'ようでは', True], [None, None, '、ろくな', None], ['大人', 'おとな', None, None], [None, None, 'にならないですよ。', None]]
[[None, None, 'こんなに', None], ['日時', 'にちじ', None, None], [None, None, 'を', None], ['間違', 'まちが', None, None], [None, None, 'える', None], [None, None, 'ようでは', True], [None, None, '、', None], ['仕事', 'しごと', None, None], [None, None, 'なんてできないよ。', None]]
[[None, None, 'こんな', None], ['問題', 'もんだい', None, None], [None, None, 'も', None], ['解', 'と', None, None], [None, None, 'けない', None], [None, None, 'ようでは', True], [None, None, '、', None], ['次', 'つぎ', None, None], [None, None, 'のテストが', None], ['思', 'おも', None, None], [None, None, 'いやられる。', None]]
[['人', 'ひと', None, None], [None, None, 'の', None], ['成功', 'せいこう', None, None], [None, None, 'を', None], ['羨', 'うらや', None, None], [None, None, 'んでいる', None], [None, None, 'ようでは', True], [None, None, '、', None], ['自分', 'じぶん', None, None], [None, None, 'の', None], ['成功', 'せいこう', None, None], [None, None, 'にはつながらない。', None]]
[['勉強', 'べんきょう', None, None], [None, None, 'の', None], ['日課', 'にっか', None, None], [None, None, 'を', None], ['守', 'まも', None, None], [None, None, 'れない', None], [None, None, 'ようでは', True], [None, None, '、', None], ['試験', 'しけん', None, None], [None, None, 'に', None], ['受', 'う', None, None], [None, None, 'からないと', None], ['思', 'おも', None, None], [None, None, 'います。', None]]

 74%|███████▍  | 696/938 [07:17<02:02,  1.98it/s]

[[None, None, 'いいカーブだ。', None], ['流石', 'さすが', None, True], [None, None, 'ダルビッシュ。', None]]
[['流石', 'さすが', None, True], [None, None, 'に', True], ['食', 'く', None, None], [None, None, 'いすぎたな。', None], ['椅子', 'いす', None, None], [None, None, 'から', None], ['立', 'た', None, None], [None, None, 'てない。', None]]
[[None, None, 'こんなおめでたい', None], ['席', 'せき', None, None], [None, None, 'に、', None], ['流石', 'さすが', None, True], [None, None, 'に', True], [None, None, 'あの', None], ['格好', 'かっこう', None, None], [None, None, 'はない。', None]]
[['一流', 'いちりゅう', None, None], [None, None, 'のオーケストラの', None], ['演奏', 'えんそう', None, None], [None, None, 'は', None], ['流石', 'さすが', None, True], [None, None, 'ですね。', None]]
[['流石', 'さすが', None, True], [None, None, 'に', True], ['落', 'おと', None, None], [None, None, 'し', None], ['物', 'もの', None, None], [None, None, 'が', None], ['多', 'おお', None, None], [None, None, 'すぎる。', None], ['注意', 'ちゅうい', None, None], [None, None, 'しないと。', None]]

 74%|███████▍  | 697/938 [07:18<02:19,  1.73it/s]

[[None, None, 'パターンが', None], [None, None, 'ある', None], [None, None, 'ことは', True], [None, None, 'ある', None], [None, None, 'が', None], [None, None, '、なかなか', None], ['解読', 'かいどく', None, None], [None, None, 'できません。', None]]
[['雨', 'あめ', None, None], [None, None, 'に', None], ['濡', 'ぬ', None, None], [None, None, 'れた', None], [None, None, 'ことは', True], ['濡', 'ぬ', None, None], [None, None, 'れた', None], [None, None, 'が', None], [None, None, '、', None], ['大', 'たい', None, None], [None, None, 'したことはなかった。', None]]
[['熱', 'ねつ', None, None], [None, None, 'が', None], ['出', 'で', None, None], [None, None, 'た', None], [None, None, 'ことは', True], ['出', 'で', None, None], [None, None, 'た', None], [None, None, 'が', None], [None, None, '、インフルエンザではありませんでした。', None]]
[['締切', 'しめきり', None, None], [None, None, 'を', None], ['延', 'の', None, None], [None, None, 'ばせた', None], [None, None, 'ことは', True], ['延', 'の', None, None], [None, None, 'ばせた', None], [None, None, 'が', None], [None, None, '、', None], ['余裕', 'よゆう', None, None], [None, None, 'ないですよ。', None]]
[[None, None, 'ボルトは', None], ['外', 'はず', None, None], [None, None, 'れる', None], [None, None, 'ことは', True], ['外', 'はず', None, None], [None, None, 'れた', None], [None, None, 'が', None], [None, None, '、これ', None], ['以上', 'いじょう', None, None], ['分解', 'ぶんかい', None, None], [None, None, 'できない。', None]]

 74%|███████▍  | 698/938 [07:18<02:15,  1.77it/s]

[['税金', 'ぜいきん', None, None], [None, None, 'が', None], [None, None, 'さらに', True], ['高', 'たか', None, None], [None, None, 'くなった。', None]]
[[None, None, 'さらに', True], ['気', 'き', None, None], [None, None, 'を', None], ['付', 'つ', None, None], [None, None, 'けてもらわないと', None], ['困', 'こま', None, None], [None, None, 'ります。', None]]
[[None, None, 'さらに', True], ['給与', 'きゅうよ', None, None], [None, None, 'が', None], ['上', 'あ', None, None], [None, None, 'がり、とても', None], ['助', 'たす', None, None], [None, None, 'かります。', None]]
[[None, None, 'さらに', True], ['乾燥', 'かんそう', None, None], [None, None, 'がひどくなり、', None], ['保湿', 'ほしつ', None, None], [None, None, 'するのが', None], ['大変', 'たいへん', None, None], [None, None, 'だ。', None]]
[['国家', 'こっか', None, None], [None, None, 'からの', None], ['融資', 'ゆうし', None, None], [None, None, 'で', None], [None, None, 'さらに', True], [None, None, 'グラフェンの', None], ['研究', 'けんきゅう', None, None], [None, None, 'を', None], ['進', 'すす', None, None], [None, None, 'める。', None]]

 75%|███████▍  | 699/938 [07:19<02:18,  1.72it/s]

[[None, None, '「', None], ['３８', 'さんじゅうはっ', None, None], ['歳', 'さい', None, None], [None, None, 'だって？', None], ['精々', 'せいぜい', None, True], ['３０', 'さんじゅう', None, None], [None, None, 'くらいなものだと', None], ['思', 'おも', None, None], [None, None, 'っていたよ。」', None]]
[[None, None, '「', None], ['電車', 'でんしゃ', None, None], [None, None, 'が', None], ['来', 'こ', None, None], [None, None, 'ないうちに', None], ['観光', 'かんこう', None, None], ['出来', 'でき', None, None], [None, None, 'るのは', None], ['精々', 'せいぜい', None, True], ['４', 'よ', None, None], ['時間', 'じかん', None, None], [None, None, 'ぐらい。」', None]]
[['証人', 'しょうにん', None, None], [None, None, '：「', None], ['加害', 'かがい', None, None], ['者', 'しゃ', None, None], [None, None, 'はたぶん', None], ['精々', 'せいぜい', None, True], ['３０', 'さんじゅっ', None, None], ['歳', 'さい', None, None], [None, None, 'ぐらいでしょ。」', None]]
[['凄', 'すご', None, None], [None, None, 'く', None], ['怒', 'おこ', None, None], [None, None, 'ったファン', None], [None, None, '：「ダーデンは', None], ['精々', 'せいぜい', None, True], ['二流', 'にりゅう', None, None], [None, None, 'のコーチだぞ！', None], ['子供', 'こども', None, None], [None, None, 'でさえもっと', None], ['上手', 'うま', None, None], [None, None, 'くコーチングできるぞ!」', None]]
[[None, None, '「この', None], ['車', 'くるま', None, None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'うのに', None], ['彼', 'かれ', None, None], [None, None, 'が', None], ['支払', 'しはら', None, None], [None, None, 'ったのは', None], ['精々', 'せいぜい', None, True], ['３万', 'さんまん', None, None], [None, None, 'ドルだと', None], ['思', 'おも', None, None], [None, None, 'う。」', None]]

 75%|███████▍  | 700/938 [07:20<02:21,  1.68it/s]

[['彼女', 'かのじょ', None, None], [None, None, 'とは', None], ['僅', 'わず', None, True], [None, None, 'かに', True], ['意見', 'いけん', None, None], [None, None, 'が', None], ['違', 'ちが', None, None], [None, None, 'う。', None]]
[['ＬＩＮＵＸ', 'リナックス', None, None], [None, None, 'のインタフェイスは', None], ['ＷＩＮＤＯＷＳ', 'ウィンドウズ', None, None], [None, None, 'のと', None], ['僅', 'わず', None, True], [None, None, 'かに', True], ['異', 'こと', None, None], [None, None, 'なる。', None]]
[['似', 'に', None, None], [None, None, 'ているけど、', None], ['僅', 'わず', None, True], [None, None, 'かに', True], ['形', 'かたち', None, None], [None, None, 'が', None], ['違', 'ちが', None, None], [None, None, 'うような', None], ['気', 'き', None, None], [None, None, 'がした。', None]]
[['僅', 'わず', None, True], [None, None, 'かに', True], ['毛', 'け', None, None], [None, None, 'が', None], ['生', 'は', None, None], [None, None, 'えてきた。', None], ['育毛', 'いくもう', None, None], [None, None, 'に', None], ['成功', 'せいこう', None, None], [None, None, 'したのかもしれない。', None]]
[['校長', 'こうちょう', None, None], ['先生', 'せんせい', None, None], [None, None, 'の', None], ['怒鳴', 'どな', None, None], [None, None, 'り', None], ['声', 'ごえ', None, None], [None, None, 'が', None], ['僅', 'わず', None, True], [None, None, 'かに', True], ['聞', 'き', None, None], [None, None, 'こえる。', None]]

 75%|███████▍  | 701/938 [07:20<02:14,  1.76it/s]

[['布団', 'ふとん', None, None], ['及', 'およ', None, True], [None, None, 'び', True], ['枕', 'まくら', None, None], ['等', 'など', None, None], [None, None, 'はございます。', None]]
[['指輪', 'ゆびわ', None, None], ['及', 'およ', None, True], [None, None, 'び', True], [None, None, 'ネックレス', None], ['等', 'など', None, None], [None, None, 'は', None], ['外', 'はず', None, None], [None, None, 'してください。', None]]
[['受付', 'うけつけ', None, None], ['及', 'およ', None, True], [None, None, 'び', True], ['入館', 'にゅうかん', None, None], [None, None, 'は', None], ['８', 'はち', None, None], ['時', 'じ', None, None], [None, None, 'からです。', None]]
[['手帳', 'てちょう', None, None], ['及', 'およ', None, True], [None, None, 'び', True], ['日記', 'にっき', None, None], ['等', 'など', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'せてください。', None]]
[['旅館', 'りょかん', None, None], ['及', 'およ', None, True], [None, None, 'び', True], [None, None, 'ホテルへの', None], ['連絡', 'れんらく', None, None], [None, None, 'はご', None], ['遠慮', 'えんりょ', None, None], [None, None, 'ください。', None]]

 75%|███████▍  | 702/938 [07:21<02:26,  1.61it/s]

[['少', 'すこ', None, None], [None, None, 'し', None], ['油断', 'ゆだん', None, None], [None, None, 'したら、ライバルに', None], ['忽', 'たちま', None, True], [None, None, 'ち', True], ['追', 'お', None, None], [None, None, 'い', None], ['越', 'こ', None, None], [None, None, 'された。', None]]
[['小', 'ちい', None, None], [None, None, 'さな', None], ['村', 'むら', None, None], [None, None, 'で', None], ['噂', 'うわさ', None, None], [None, None, 'が', None], ['忽', 'たちま', None, True], [None, None, 'ち', True], ['広', 'ひろ', None, None], [None, None, 'がるのは', None], ['当然', 'とうぜん', None, None], [None, None, 'だよ！', None]]
[[None, None, 'うちの', None], ['庭', 'にわ', None, None], [None, None, 'を', None], ['掘', 'ほ', None, None], [None, None, 'ったら、', None], ['忽', 'たちま', None, True], [None, None, 'ち', True], ['温泉', 'おんせん', None, None], [None, None, 'が', None], ['出', 'で', None, None], [None, None, 'てきて', None], ['驚', 'おどろ', None, None], [None, None, 'いた。', None]]
[[None, None, 'うちの', None], ['犬', 'いぬ', None, None], [None, None, 'は', None], ['郵便', 'ゆうびん', None, None], ['配達員', 'はいたついん', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'ると', None], ['忽', 'たちま', None, True], [None, None, 'ち', True], [None, None, 'フェンスにそって', None], ['走', 'はし', None, None], [None, None, 'り', None], ['始', 'はじ', None, None], [None, None, 'めるのだ。', None]]
[[None, None, 'あんなに', None], ['仲', 'なか', None, None], [None, None, 'が', None], ['良', 'よ', None, None], [None, None, 'かったのに、あの', None], ['事件', 'じけん', None, None], [None, None, 'のせいで', None], ['忽', 'たちま', None, True], [None, None, 'ち', True], ['解散', 'かいさん', None, None], [None, None, 'だ。', None]]

 75%|███████▍  | 703/938 [07:22<02:28,  1.59it/s]

[['行', 'い', None, True], [None, None, 'き', True], ['成', 'な', None, True], [None, None, 'り', True], [None, None, 'の', None], ['展開', 'てんかい', None, None], [None, None, 'に', None], ['驚', 'おどろ', None, None], [None, None, 'きを', None], ['隠', 'かく', None, None], [None, None, 'せない。', None]]
[['行', 'い', None, True], [None, None, 'き', True], ['成', 'な', None, True], [None, None, 'り', True], ['電波', 'でんぱ', None, None], [None, None, 'が', None], ['切', 'き', None, None], [None, None, 'れてしまうのは', None], ['困', 'こま', None, None], [None, None, 'る。', None]]
[[None, None, 'そんな', None], ['行', 'い', None, True], [None, None, 'き', True], ['成', 'な', None, True], [None, None, 'り', True], ['停車', 'ていしゃ', None, None], [None, None, 'したら', None], ['危', 'あぶ', None, None], [None, None, 'ないですよ。', None]]
[['行', 'い', None, True], [None, None, 'き', True], ['成', 'な', None, True], [None, None, 'り', True], ['難問', 'なんもん', None, None], [None, None, 'に', None], ['突', 'つ', None, None], [None, None, 'き', None], ['当', 'あ', None, None], [None, None, 'たってしまった。', None]]
[['弟', 'おとうと', None, None], [None, None, 'は、', None], ['行', 'い', None, True], [None, None, 'き', True], ['成', 'な', None, True], [None, None, 'り', True], ['手', 'て', None, None], [None, None, 'づかみでご', None], ['飯', 'はん', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べ', None], ['始', 'はじ', None, None], [None, None, 'めた。', None]]

 75%|███████▌  | 704/938 [07:22<02:15,  1.72it/s]

[['勝敗', 'しょうはい', None, None], [None, None, 'といった', True], [None, None, 'ものにこだわるのはやめよう。', None]]
[['蕎麦', 'そば', None, None], [None, None, 'といった', True], ['麺類', 'めんるい', None, None], [None, None, 'があまり', None], ['好', 'す', None, None], [None, None, 'きではありません。', None]]
[['相撲', 'すもう', None, None], [None, None, 'といった', True], ['日本', 'にっぽん', None, None], [None, None, 'の', None], ['文化', 'ぶんか', None, None], [None, None, 'に', None], ['興味', 'きょうみ', None, None], [None, None, 'がある。', None]]
[['宣伝', 'せんでん', None, None], [None, None, 'といった', True], [None, None, 'ものに', None], ['振', 'ふ', None, None], [None, None, 'り', None], ['回', 'まわ', None, None], [None, None, 'されてはいけません。', None]]
[[None, None, 'これ', None], [None, None, 'といった', True], ['理由', 'りゆう', None, None], [None, None, 'もないのに', None], ['約束', 'やくそく', None, None], [None, None, 'を', None], ['破', 'やぶ', None, None], [None, None, 'ってはいけない。', None]]

 75%|███████▌  | 705/938 [07:23<02:22,  1.64it/s]

[['感謝', 'かんしゃ', None, None], [None, None, 'の', None], ['気持', 'きも', None, None], [None, None, 'ち', None], [None, None, 'を', True], ['込', 'こ', None, True], [None, None, 'めて', True], [None, None, '、プレゼントを', None], ['贈', 'おく', None, None], [None, None, 'った。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'が', None], ['愛', 'あい', None, None], [None, None, 'を', True], ['込', 'こ', None, True], [None, None, 'めて', True], ['作', 'つく', None, None], [None, None, 'った', None], ['弁当', 'べんとう', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べたい！', None]]
[['憧', 'あこが', None, None], [None, None, 'れ', None], [None, None, 'を', True], ['込', 'こ', None, True], [None, None, 'めて', True], ['伯父', 'おじ', None, None], [None, None, 'さんの', None], ['背中', 'せなか', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'ていた。', None]]
[['祈', 'いの', None, None], [None, None, 'り', None], [None, None, 'を', True], ['込', 'こ', None, True], [None, None, 'めて', True], ['書', 'か', None, None], [None, None, 'いた', None], ['詩', 'し', None, None], [None, None, 'に', None], ['涙', 'なみだ', None, None], [None, None, 'した。', None]]
[['願', 'ねが', None, None], [None, None, 'い', None], [None, None, 'を', True], ['込', 'こ', None, True], [None, None, 'めて', True], [None, None, 'ステージで', None], ['歌', 'うた', None, None], [None, None, 'う', None], ['姿', 'すがた', None, None], [None, None, 'にジーンときた。', None]]

 75%|███████▌  | 706/938 [07:23<02:13,  1.74it/s]

[['白髪', 'はくはつ', None, None], [None, None, 'に', True], ['加', 'くわ', None, True], [None, None, 'えて', True], [None, None, 'シワまで', None], ['増', 'ふ', None, None], [None, None, 'えてきた。もう', None], ['年', 'とし', None, None], [None, None, 'だな。', None]]
[['性能', 'せいのう', None, None], [None, None, 'に', True], ['加', 'くわ', None, True], [None, None, 'えて', True], ['価格', 'かかく', None, None], [None, None, 'まで', None], ['負', 'ま', None, None], [None, None, 'けているようではどうにもならない。', None]]
[['彼', 'かれ', None, None], [None, None, 'の', None], ['別荘', 'べっそう', None, None], [None, None, 'にはテニスコート', None], [None, None, 'に', True], ['加', 'くわ', None, True], [None, None, 'えて', True], [None, None, 'サッカーコートまであるんですよ。', None]]
[['内科', 'ないか', None, None], [None, None, 'に', True], ['加', 'くわ', None, True], [None, None, 'えて', True], ['外科', 'げか', None, None], [None, None, 'にもかかることになるなんて', None], ['思', 'おも', None, None], [None, None, 'いもしなかった。', None]]
[['中指', 'なかゆび', None, None], [None, None, 'に', True], ['加', 'くわ', None, True], [None, None, 'えて', True], ['薬指', 'くすりゆび', None, None], [None, None, 'まで', None], ['骨折', 'こっせつ', None, None], [None, None, 'していました。', None]]

 75%|███████▌  | 707/938 [07:24<02:09,  1.78it/s]

[[None, None, '「', None], ['本当', 'ほんとう', None, None], [None, None, 'に', None], ['何', 'なに', None, True], [None, None, 'から', True], ['何', 'なに', None, True], [None, None, 'まで', True], [None, None, 'すみません。」', None]]
[[None, None, 'サポートスタッフ', None], [None, None, '：「このマニュアルには、', None], ['何', 'なに', None, True], [None, None, 'から', True], ['何', 'なに', None, True], [None, None, 'まで', True], ['書', 'か', None, None], [None, None, 'いてあります。」', None]]
[['刑事', 'けいじ', None, None], [None, None, '、', None], ['容疑者', 'ようぎしゃ', None, None], [None, None, 'について', None], [None, None, '：「', None], ['彼', 'かれ', None, None], [None, None, 'の', None], ['話', 'はなし', None, None], [None, None, 'は', None], ['何', 'なに', None, True], [None, None, 'から', True], ['何', 'なに', None, True], [None, None, 'まで', True], [None, None, 'うそだった！」', None]]
[[None, None, 'ライトノベル', None], [None, None, '：「しかし、そのルールは', None], ['何', 'なに', None, True], [None, None, 'から', True], ['何', 'なに', None, True], [None, None, 'まで', True], ['当', 'あ', None, None], [None, None, 'てはまるわけではない。', None], ['例外', 'れいがい', None, None], [None, None, 'もある。」', None]]
[['子供', 'こども', None, None], [None, None, 'について、ご', None], ['近所', 'きんじょ', None, None], [None, None, 'さんの', None], ['話', 'はなし', None, None], [None, None, '：「エレンは', None], ['何', 'なに', None, True], [None, None, 'から', True], ['何', 'なに', None, True], [None, None, 'まで', True], ['母親', 'ははおや', None, None], [None, None, 'そっくりだ。」', None]]

 75%|███████▌  | 708/938 [07:24<02:04,  1.85it/s]

[['手伝', 'てつだ', None, None], [None, None, 'うべきかどうか', None], [None, None, 'は', True], ['別', 'べつ', None, True], [None, None, 'として', True], [None, None, 'そもそも', None], ['現場', 'げんば', None, None], [None, None, 'にはいなかった。', None]]
[[None, None, 'それ', None], [None, None, 'は', True], ['別', 'べつ', None, True], [None, None, 'として', True], [None, None, 'もたぶん', None], ['遅', 'おそ', None, None], [None, None, 'かれ', None], ['早', 'はや', None, None], [None, None, 'かれそのトピックに', None], ['戻', 'もど', None, None], [None, None, 'ってくるだろう。', None]]
[[None, None, 'この', None], ['子犬', 'こいぬ', None, None], [None, None, 'はかわいい、かわいくない', None], [None, None, 'は', True], ['別', 'べつ', None, True], [None, None, 'として', True], ['確', 'たし', None, None], [None, None, 'かに', None], ['動物', 'どうぶつ', None, None], [None, None, 'としては', None], ['随分', 'ずいぶん', None, None], ['賢', 'かしこ', None, None], [None, None, 'い。', None]]
[[None, None, 'そのジョークを', None], ['言', 'い', None, None], [None, None, 'うのはいいか', None], ['悪', 'わる', None, None], [None, None, 'いか', None], [None, None, 'は', True], ['別', 'べつ', None, True], [None, None, 'として', True], [None, None, '、', None], ['自分', 'じぶん', None, None], [None, None, 'ではとてもおもしろいと', None], ['思', 'おも', None, None], [None, None, 'った！', None]]
[['喰', 'く', None, None], [None, None, 'われている', None], ['餌食', 'えじき', None, None], ['自身', 'じしん', None, None], [None, None, 'は', True], ['別', 'べつ', None, True], [None, None, 'として', True], ['喰', 'く', None, None], [None, None, 'っている', None], ['捕食', 'ほしょく', None, None], ['動物', 'どうぶつ', None, None], [None, None, 'は', None], ['本当', 'ほんとう', None, None], [None, None, 'に', None], ['幸', 'しあわ', None, None], [None, None, 'せだ。', None]]

 76%|███████▌  | 709/938 [07:25<02:04,  1.84it/s]

[[None, None, 'この', None], ['車', 'くるま', None, None], [None, None, 'は', None], ['最新', 'さいしん', None, None], [None, None, 'だけに', True], [None, None, '、', None], ['椅子', 'いす', None, None], [None, None, 'のヒーターもあります。', None]]
[['年', 'とし', None, None], [None, None, 'を', None], ['取', 'と', None, None], [None, None, 'ってきた', None], [None, None, 'だけに', True], [None, None, '、', None], ['出来', 'でき', None, None], [None, None, 'なくなったことが', None], ['多', 'おお', None, None], [None, None, 'い。', None]]
[['大工', 'だいく', None, None], [None, None, 'だけに', True], [None, None, '、', None], ['椅子', 'いす', None, None], [None, None, 'くらいならすぐに', None], ['作', 'つく', None, None], [None, None, 'ってくれる。', None]]
[['寿司', 'すし', None, None], ['職人', 'しょくにん', None, None], [None, None, 'だけに', True], [None, None, '、', None], ['醤油', 'しょうゆ', None, None], [None, None, 'へのこだわりがすごい。', None]]
[[None, None, 'スチュワーデス', None], [None, None, 'だけに', True], [None, None, '、', None], ['身長', 'しんちょう', None, None], [None, None, 'が', None], ['高', 'たか', None, None], [None, None, 'く', None], ['姿勢', 'しせい', None, None], [None, None, 'もいいですね。', None]]

 76%|███████▌  | 710/938 [07:26<02:14,  1.69it/s]

[['食', 'た', None, None], [None, None, 'べられる', None], [None, None, 'だけは', True], ['食', 'た', None, None], [None, None, 'べた', None], [None, None, '。', None], ['食', 'た', None, None], [None, None, 'べ', None], ['放題', 'ほうだい', None, None], [None, None, 'だからさ。', None]]
[[None, None, 'このナッツを', None], ['砕', 'くだ', None, None], [None, None, 'く', None], [None, None, 'だけは', True], ['砕', 'くだ', None, None], [None, None, 'いた', None], [None, None, '。', None]]
[['儀式', 'ぎしき', None, None], [None, None, 'だから', None], [None, None, 'やる', None], [None, None, 'だけは', True], [None, None, 'やっている', None], [None, None, 'が、さっぱり', None], ['意味', 'いみ', None, None], [None, None, 'が', None], ['分', 'わ', None, None], [None, None, 'からない。', None]]
[['感想', 'かんそう', None, None], [None, None, 'を', None], ['書', 'か', None, None], [None, None, 'く', None], [None, None, 'だけは', True], ['書', 'か', None, None], [None, None, 'いて', None], [None, None, 'みたが、まだメールで', None], ['送', 'おく', None, None], [None, None, 'っていません。', None]]
[['今日', 'きょう', None, None], ['着', 'き', None, None], [None, None, 'たい', None], ['服', 'ふく', None, None], [None, None, 'を', None], ['乾', 'かわ', None, None], [None, None, 'かす', None], [None, None, 'だけは', True], ['乾', 'かわ', None, None], [None, None, 'かして', None], ['家', 'いえ', None, None], [None, None, 'を', None], ['出', 'で', None, None], [None, None, 'た。', None]]

 76%|███████▌  | 711/938 [07:26<02:13,  1.70it/s]

[['茶道', 'さどう', None, None], [None, None, 'を', None], ['習', 'なら', None, None], [None, None, 'っている', None], [None, None, 'だけあって', True], [None, None, '、', None], ['礼儀', 'れいぎ', None, None], [None, None, 'が', None], ['正', 'ただ', None, None], [None, None, 'しい。', None]]
[['昼寝', 'ひるね', None, None], [None, None, 'した', None], [None, None, 'だけあって', True], [None, None, '、', None], ['午後', 'ごご', None, None], [None, None, 'から', None], ['眠', 'ねむ', None, None], [None, None, 'くなることはなかった。', None]]
[[None, None, 'あの', None], ['二人', 'ふたり', None, None], [None, None, 'は', None], ['仲良', 'なかよ', None, None], [None, None, 'し', None], [None, None, 'なだけあって', True], [None, None, '、いつも', None], ['一緒', 'いっしょ', None, None], [None, None, 'にいるよね。', None]]
[['揚', 'あ', None, None], [None, None, 'げ', None], ['物', 'もの', None, None], [None, None, 'を', None], ['控', 'ひか', None, None], [None, None, 'えた', None], [None, None, 'だけあって', True], [None, None, '、', None], ['私', 'わたし', None, None], [None, None, 'は', None], ['３', 'さん', None, None], [None, None, 'キロも', None], ['痩', 'や', None, None], [None, None, 'せた。', None]]
[[None, None, 'アナウンサー', None], [None, None, 'だけあって', True], [None, None, '、', None], ['早口', 'はやくち', None, None], ['言葉', 'ことば', None, None], [None, None, 'が', None], ['得意', 'とくい', None, None], [None, None, 'だ。', None]]

 76%|███████▌  | 712/938 [07:27<02:19,  1.62it/s]

[[None, None, '「ありがとうございます。」', None], [None, None, '「お', None], ['役', 'やく', None, None], [None, None, 'に', None], ['立', 'た', None, None], [None, None, 'てれば、', None], ['何', 'なに', None, True], [None, None, 'よりの', True], ['幸', 'しあわ', None, None], [None, None, 'せです。」', None]]
[['友達', 'ともだち', None, None], [None, None, '：「', None], ['互', 'たが', None, None], [None, None, 'いに', None], ['助', 'たす', None, None], [None, None, 'け', None], ['合', 'あ', None, None], [None, None, 'うことが', None], ['何', 'なに', None, True], [None, None, 'より', True], ['大事', 'だいじ', None, None], [None, None, 'なのよ。」', None]]
[['久', 'ひさ', None, None], [None, None, 'しぶりに', None], ['挨拶', 'あいさつ', None, None], [None, None, 'する', None], ['時', 'とき', None, None], [None, None, '：「', None], [None, None, 'お', None], ['元気', 'げんき', None, None], [None, None, 'そうで', None], ['何', 'なに', None, True], [None, None, 'より', True], [None, None, 'です。」', None]]
[['記事', 'きじ', None, None], [None, None, '：「', None], ['両親', 'りょうしん', None, None], [None, None, 'にとって', None], ['自分', 'じぶん', None, None], [None, None, 'の', None], ['子供', 'こども', None, None], [None, None, 'の', None], ['健康', 'けんこう', None, None], [None, None, 'が', None], ['何', 'なに', None, True], [None, None, 'より', True], ['大切', 'たいせつ', None, None], [None, None, 'です。」', None]]
[[None, None, 'らくさん', None], [None, None, '：「あなたにもらった', None], ['本', 'ほん', None, None], [None, None, '、わたしの', None], ['息子', 'むすこ', None, None], [None, None, 'がとても', None], ['気', 'き', None, None], [None, None, 'に', None], ['入', 'い', None, None], [None, None, 'っています。」', None], [None, None, 'おのでらさん', None], [None, None, '：「', None], [None, None, 'それは', None], ['何', 'なに', None, True], [None, None, 'より', True], [None, None, 'です。」', None]]

 76%|███████▌  | 713/938 [07:28<02:25,  1.55it/s]

[['彼', 'かれ', None, None], [None, None, 'の', None], ['長所', 'ちょうしょ', None, None], [None, None, 'は、', None], ['何', 'なん', None, True], [None, None, 'といっても', True], ['朗', 'ほが', None, None], [None, None, 'らかなところだ。', None]]
[[None, None, 'この', None], ['地域', 'ちいき', None, None], [None, None, 'の', None], ['見所', 'みどころ', None, None], [None, None, 'は、', None], ['何', 'なん', None, True], [None, None, 'といっても', True], ['紅葉', 'こうよう', None, None], [None, None, 'だ。', None]]
[[None, None, 'このマンションのセールスポイントは、', None], ['何', 'なん', None, True], [None, None, 'といっても', True], ['駅', 'えき', None, None], [None, None, 'から', None], ['近', 'ちか', None, None], [None, None, 'いことです。', None]]
[[None, None, 'あの', None], ['牧場', 'ぼくじょう', None, None], [None, None, 'のおすすめは、', None], ['何', 'なん', None, True], [None, None, 'といっても', True], ['自家製', 'じかせい', None, None], [None, None, 'のアイスクリームだ。', None]]
[[None, None, 'うちの', None], ['会社', 'かいしゃ', None, None], [None, None, 'のいいところは、', None], ['何', 'なん', None, True], [None, None, 'といっても', True], [None, None, 'ボーナスがたくさんもらえることです。', None]]

 76%|███████▌  | 714/938 [07:29<02:50,  1.31it/s]

[['学校', 'がっこう', None, None], [None, None, 'か', True], ['何', 'なに', None, True], [None, None, 'か', True], [None, None, 'に', None], ['通', 'かよ', None, None], [None, None, 'ってるみたいだけど。', None]]
[[None, None, '「', None], ['仕事', 'しごと', None, None], [None, None, 'でいやなことがあった', None], [None, None, 'か', True], ['何', 'なに', None, True], [None, None, 'か', True], [None, None, '？', None], ['機嫌', 'きげん', None, None], [None, None, 'が', None], ['悪', 'わる', None, None], [None, None, 'そうね。」', None]]
[[None, None, 'バーテンダーのひとみさん', None], [None, None, '：「お', None], ['飲', 'の', None, None], [None, None, 'み', None], ['物', 'もの', None, None], [None, None, 'はいかが？」', None], ['顧客', 'こきゃく', None, None], [None, None, 'のにったさん', None], [None, None, '：「ビール', None], [None, None, 'か', True], ['何', 'なに', None, True], [None, None, 'か', True], [None, None, 'がほしいな。」', None]]
[['奥', 'おく', None, None], [None, None, 'さん', None], [None, None, '：「コーヒー', None], [None, None, 'か', True], ['何', 'なに', None, True], [None, None, 'か', True], ['飲', 'の', None, None], [None, None, 'みませんか？」', None], [None, None, 'お', None], ['客', 'きゃく', None, None], [None, None, 'さん', None], [None, None, '：「', None], ['結構', 'けっこう', None, None], [None, None, 'です。」', None]]
[['警察官', 'けいさつかん', None, None], [None, None, '：「', None], ['泥棒', 'どろぼう', None, None], [None, None, 'はバール', None], [None, None, 'か', True], ['何', 'なに', None, True], [None, None, 'か', True], [None, None, 'を', None], ['使', 'つか', None, None], [None, None, 'って、', None], ['窓', 'まど', None, None], [None, None, 'を', None], ['開', 'あ', None, None], [None, None, 'けたと', None], ['思', 'おも', None, None], [None, None, 'います。」', None]]

 76%|███████▌  | 715/938 [07:29<02:42,  1.38it/s]

[['詐欺', 'さぎ', None, None], [None, None, 'にあった', None], ['気', 'き', None, True], [None, None, 'がしてならない', True], [None, None, '。', None]]
[[None, None, 'あんなコレクションは', None], ['無駄', 'むだ', None, None], [None, None, 'に', None], ['思', 'おも', None, True], [None, None, 'えてならない', True], [None, None, '。', None]]
[['去年', 'きょねん', None, None], [None, None, 'あなたと', None], ['見', 'み', None, None], [None, None, 'た', None], ['紅葉', 'こうよう', None, None], [None, None, 'が', None], ['思', 'おも', None, True], [None, None, 'い', True], ['出', 'だ', None, True], [None, None, 'されてならない', True], [None, None, '。', None]]
[[None, None, 'この', None], ['毛皮', 'けがわ', None, None], [None, None, 'は', None], ['暑', 'あつ', None, True], [None, None, 'くてならない', True], [None, None, '。', None]]
[['明日', 'あした', None, None], [None, None, 'の', None], ['見学', 'けんがく', None, None], [None, None, 'が', None], ['楽', 'たの', None, None], [None, None, 'しみ', None], [None, None, 'でならない', True], [None, None, '。', None]]

 76%|███████▋  | 716/938 [07:30<02:41,  1.37it/s]

[['炭素', 'たんそ', None, None], ['繊維', 'せんい', None, None], [None, None, 'は', None], ['極', 'きわ', None, None], [None, None, 'めて', None], ['丈夫', 'じょうぶ', None, None], [None, None, 'である', None], [None, None, 'のみならず', True], ['非常', 'ひじょう', None, None], [None, None, 'に', None], ['軽', 'かる', None, None], [None, None, 'いらしい。', None]]
[[None, None, 'この', None], ['大統領', 'だいとうりょう', None, None], ['候補', 'こうほ', None, None], [None, None, 'は、', None], ['豊富', 'ほうふ', None, None], [None, None, 'な', None], ['知識', 'ちしき', None, None], [None, None, 'がある', None], [None, None, 'のみならず', True], ['経験', 'けいけん', None, None], [None, None, 'の', None], ['深', 'ふか', None, None], [None, None, 'い', None], ['人', 'ひと', None, None], [None, None, 'でもある。', None]]
[['現代', 'げんだい', None, None], ['人', 'じん', None, None], [None, None, 'は', None], ['健康', 'けんこう', None, None], [None, None, 'のために', None], ['健康', 'けんこう', None, None], ['食品', 'しょくひん', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べる', None], [None, None, 'のみならず', True], [None, None, '、', None], ['運動', 'うんどう', None, None], [None, None, 'もするべきである。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['年', 'とし', None, None], [None, None, 'が', None], ['経', 'た', None, None], [None, None, 'つに', None], ['伴', 'ともな', None, None], [None, None, 'って', None], ['英語', 'えいご', None, None], [None, None, 'のみならず', True], ['中国語', 'ちゅうごくご', None, None], [None, None, 'も', None], ['流麗', 'りゅうれい', None, None], [None, None, 'に', None], ['話', 'はな', None, None], [None, None, 'せるようになった。', None]]
[['発光', 'はっこう', None, None], [None, None, 'ダイオードは', None], ['蛍光', 'けいこう', None, None], ['灯', 'とう', None, None], [None, None, 'よりずっと', None], ['安', 'やす', None, None], [None, None, 'い', None], [None, None, 'のみならず', True], ['環境', 'かんきょう', None, None], [None, None, 'への', None], ['影響', 'えいきょう', None, None], [None, None, 'も', None], ['細小', 'さいしょう', None, None], [None, None, 'である。', None]]

 76%|███████▋  | 717/938 [07:30<02:27,  1.50it/s]

[['新品', 'しんぴん', None, None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'った。', None], [None, None, 'それなのに', True], [None, None, 'もう', None], ['壊', 'こわ', None, None], [None, None, 'れた。', None]]
[['早起', 'はやお', None, None], [None, None, 'きするために', None], ['早', 'はや', None, None], [None, None, 'く', None], ['寝', 'ね', None, None], [None, None, 'た。', None], [None, None, 'それなのに', True], ['寝坊', 'ねぼう', None, None], [None, None, 'した。', None]]
[[None, None, 'アンテナを', None], ['新', 'あたら', None, None], [None, None, 'しくした。', None], [None, None, 'それなのに', True], [None, None, 'テレビの', None], ['映', 'うつ', None, None], [None, None, 'りが', None], ['悪', 'わる', None, None], [None, None, 'い。', None]]
[['明日', 'あした', None, None], [None, None, 'は', None], ['遠足', 'えんそく', None, None], [None, None, 'だ。', None], [None, None, 'それなのに', True], ['夜更', 'よふ', None, None], [None, None, 'かししている。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], ['努力', 'どりょく', None, None], [None, None, 'していると', None], ['思', 'おも', None, None], [None, None, 'う。', None], [None, None, 'それなのに', True], [None, None, 'うまくいかないのか。', None]]

 77%|███████▋  | 718/938 [07:31<02:25,  1.51it/s]

[[None, None, 'それは', None], ['所謂', 'いわゆる', None, True], ['神話', 'しんわ', None, None], [None, None, 'というやつです。', None], ['信用', 'しんよう', None, None], [None, None, 'してはいけません。', None]]
[[None, None, 'これは', None], ['所謂', 'いわゆる', None, True], ['宣伝', 'せんでん', None, None], [None, None, 'ですので、ご', None], ['理解', 'りかい', None, None], [None, None, 'ください。', None]]
[[None, None, 'これは', None], ['所謂', 'いわゆる', None, True], ['葬式', 'そうしき', None, None], [None, None, 'ではありませんので、', None], ['悲', 'かな', None, None], [None, None, 'しまないでください。', None]]
[[None, None, 'これは', None], ['所謂', 'いわゆる', None, True], ['総理', 'そうり', None, None], ['案件', 'あんけん', None, None], [None, None, 'というやつでは？', None]]
[['所謂', 'いわゆる', None, True], ['送料', 'そうりょう', None, None], [None, None, 'ですが、', None], ['無料', 'むりょう', None, None], [None, None, 'でやらせてもらっています。', None]]

 77%|███████▋  | 719/938 [07:32<02:13,  1.64it/s]

[['君', 'きみ', None, None], [None, None, 'は', None], ['学生', 'がくせい', None, None], [None, None, 'にすぎない', True], [None, None, '。', None]]
[['行動', 'こうどう', None, None], [None, None, 'しなかったら、', None], ['口', 'くち', None, None], [None, None, 'だけ', None], [None, None, 'にすぎない', True], [None, None, '。', None]]
[['運', 'うん', None, None], [None, None, 'が', None], ['悪', 'わる', None, None], [None, None, 'い', None], [None, None, 'だけ', None], [None, None, 'にすぎない', True], [None, None, '。', None]]
[['利害', 'りがい', None, None], ['関係', 'かんけい', None, None], [None, None, 'があるから、', None], ['親切', 'しんせつ', None, None], [None, None, 'にしている', None], [None, None, 'にすぎない', True], [None, None, '。', None]]
[[None, None, '「いつか', None], ['飲', 'の', None, None], [None, None, 'みましょう」って', None], ['言', 'い', None, None], [None, None, 'ったけど、あれは', None], ['社交', 'しゃこう', None, None], ['辞令', 'じれい', None, None], [None, None, 'にすぎない', True], [None, None, '。', None]]

 77%|███████▋  | 720/938 [07:32<02:13,  1.63it/s]

[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['地位', 'ちい', None, None], [None, None, 'も', True], [None, None, 'なけれ', None], [None, None, 'ば', None], [None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'も', True], [None, None, 'ない。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'は、', None], ['実力', 'じつりょく', None, None], [None, None, 'もあれば', True], [None, None, '、', None], ['努力', 'どりょく', None, None], [None, None, 'も', None], [None, None, 'する。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['撮影', 'さつえい', None, None], [None, None, 'もできれば', True], [None, None, '、ナレーション', None], [None, None, 'も', None], [None, None, 'できる。', None]]
[[None, None, '「うまくいっている」という', None], ['実感', 'じっかん', None, None], [None, None, 'もなければ', True], [None, None, '、', None], ['兆候', 'ちょうこう', None, None], [None, None, 'も', None], [None, None, 'ない。', None]]
[['総理大臣', 'そうりだいじん', None, None], [None, None, 'は、', None], ['経済', 'けいざい', None, None], [None, None, 'も', True], ['見直', 'みなお', None, None], [None, None, 'せれ', None], [None, None, 'ば', None], [None, None, '、', None], ['人権', 'じんけん', None, None], ['問題', 'もんだい', None, None], [None, None, 'も', True], ['解決', 'かいけつ', None, None], [None, None, 'できます。', None]]

 77%|███████▋  | 721/938 [07:33<02:04,  1.74it/s]

[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'は', None], ['見栄', 'みえ', None, None], [None, None, 'の', None], ['塊', 'かたまり', None, None], [None, None, 'でしかない', True], [None, None, '。', None]]
[['聞', 'き', None, None], [None, None, 'こえはいいが、', None], ['安易', 'あんい', None, None], [None, None, 'な', None], ['言', 'い', None, None], [None, None, 'い', None], ['訳', 'わけ', None, None], [None, None, 'でしかない', True], [None, None, '。', None]]
[[None, None, '「', None], ['訓練', 'くんれん', None, None], [None, None, 'だ」と', None], ['言', 'い', None, None], [None, None, 'っているが、あんなの', None], ['意地悪', 'いじわる', None, None], [None, None, 'でしかない', True], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'から', None], ['秘密', 'ひみつ', None, None], [None, None, 'を', None], ['教', 'おし', None, None], [None, None, 'えてもらったが、ウソ', None], [None, None, 'でしかなかった', True], [None, None, '。', None]]
[[None, None, 'アイデアは', None], ['悪', 'わる', None, None], [None, None, 'くないが、', None], ['机上', 'きじょう', None, None], [None, None, 'の', None], ['空論', 'くうろん', None, None], [None, None, 'でしかない', True], [None, None, '。', None]]

 77%|███████▋  | 722/938 [07:33<01:59,  1.80it/s]

[[None, None, 'サイレンの', None], ['音', 'おと', None, None], [None, None, 'が', None], [None, None, 'うるさくてたまらない', True], [None, None, '。', None]]
[['蚊', 'か', None, None], [None, None, 'に', None], ['刺', 'さ', None, None], [None, None, 'されて', None], [None, None, 'かゆくてたまらない', True], [None, None, '。', None]]
[['自分', 'じぶん', None, None], [None, None, 'の', None], ['子供', 'こども', None, None], [None, None, 'のことが', None], ['心配', 'しんぱい', None, True], [None, None, 'でたまらない', True], [None, None, '。', None]]
[['暑', 'あつ', None, True], [None, None, 'くてたまらない', True], [None, None, '。だからクーラーをつけた。', None]]
[[None, None, 'あのコーラスグループのコンサートが', None], ['見', 'み', None, True], [None, None, 'たくてたまらない', True], [None, None, '。', None]]

 77%|███████▋  | 723/938 [07:34<01:57,  1.83it/s]

[['違', 'ちが', None, None], [None, None, 'いがある', None], [None, None, 'にせよ', True], [None, None, '、わずかな', None], ['差', 'さ', None, None], [None, None, 'だ。', None]]
[[None, None, 'それは', None], ['難', 'むずか', None, None], [None, None, 'しい', None], [None, None, 'にしろ', True], [None, None, '、するしかない。', None]]
[['飲', 'の', None, None], [None, None, 'まない', None], [None, None, 'にしろ', True], [None, None, '、', None], ['居酒屋', 'いざかや', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'こう。', None]]
[[None, None, 'いずれ', None], [None, None, 'にせよ', True], [None, None, '、この', None], ['決定', 'けってい', None, None], [None, None, 'は', None], ['変', 'か', None, None], [None, None, 'わりません。', None]]
[[None, None, 'それが', None], ['上司', 'じょうし', None, None], [None, None, 'の', None], ['命令', 'めいれい', None, None], [None, None, 'にせよ', True], [None, None, '、わたしは', None], ['従', 'したが', None, None], [None, None, 'えません。', None]]

 77%|███████▋  | 724/938 [07:34<01:55,  1.86it/s]

[['何', 'なに', None, True], [None, None, 'しろ', True], ['暑', 'あつ', None, None], [None, None, 'い', None], [None, None, 'から', None], [None, None, 'ね。', None], ['食欲', 'しょくよく', None, None], [None, None, 'も', None], ['出', 'で', None, None], [None, None, 'ないよ。', None]]
[['何', 'なに', None, True], [None, None, 'しろ', True], ['期限', 'きげん', None, None], [None, None, 'が', None], ['迫', 'せま', None, None], [None, None, 'っている。', None], ['急', 'いそ', None, None], [None, None, 'いでくれないか。', None]]
[['何', 'なに', None, True], [None, None, 'しろ', True], ['基礎', 'きそ', None, None], [None, None, 'ができていない', None], [None, None, 'から', None], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'に', None], ['数学', 'すうがく', None, None], [None, None, 'を', None], ['教', 'おし', None, None], [None, None, 'えるのは', None], ['大変', 'たいへん', None, None], [None, None, 'だ。', None]]
[[None, None, 'あそこの', None], ['会社', 'かいしゃ', None, None], [None, None, 'は', None], ['何', 'なに', None, True], [None, None, 'しろ', True], ['規律', 'きりつ', None, None], [None, None, 'が', None], ['厳', 'きび', None, None], [None, None, 'しい。あれじゃあまるで', None], ['軍隊', 'ぐんたい', None, None], [None, None, 'だ。', None]]
[[None, None, 'あの', None], ['社長', 'しゃちょう', None, None], [None, None, 'は', None], ['何', 'なに', None, True], [None, None, 'しろ', True], ['強引', 'ごういん', None, None], [None, None, 'だ', None], [None, None, 'から', None], [None, None, '、それで', None], ['会社', 'かいしゃ', None, None], [None, None, 'を', None], ['辞', 'や', None, None], [None, None, 'めた', None], ['人', 'ひと', None, None], [None, None, 'もたくさんいます。', None]]

 77%|███████▋  | 725/938 [07:35<02:03,  1.73it/s]

[['好', 'す', None, None], [None, None, 'き', None], [None, None, 'にしろ', True], ['嫌', 'きら', None, None], [None, None, 'い', None], [None, None, 'にしろ', True], [None, None, '、このワクチンは', None], ['義務', 'ぎむ', None, None], [None, None, 'づけられている。', None]]
[['公務', 'こうむ', None, None], [None, None, 'にしろ', True], [None, None, 'プライベート', None], [None, None, 'にしろ', True], [None, None, '、ルールはちゃんと', None], ['守', 'まも', None, None], [None, None, 'ってください。', None]]
[['古典', 'こてん', None, None], [None, None, 'にしろ', True], ['新作', 'しんさく', None, None], [None, None, 'にしろ', True], [None, None, '、とにかく', None], ['彼', 'かれ', None, None], [None, None, 'の', None], ['落語', 'らくご', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'きだ。', None]]
[['言葉', 'ことば', None, None], ['遣', 'づか', None, None], [None, None, 'い', None], [None, None, 'にしろ', True], ['態度', 'たいど', None, None], [None, None, 'にしろ', True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'の', None], ['印象', 'いんしょう', None, None], [None, None, 'はとにかく', None], ['悪', 'わる', None, None], [None, None, 'い。', None]]
[['寿司', 'すし', None, None], [None, None, 'にしろ', True], ['刺身', 'さしみ', None, None], [None, None, 'にしろ', True], [None, None, '、とにかく', None], ['生', 'なま', None, None], [None, None, 'の', None], ['魚', 'さかな', None, None], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'きなんです。', None]]

 77%|███████▋  | 726/938 [07:35<01:58,  1.79it/s]

[['冗談', 'じょうだん', None, None], [None, None, 'は', True], ['兎', 'と', None, True], [None, None, 'も', True], ['角', 'かく', None, True], [None, None, '、そろそろビジネスの', None], ['話', 'はなし', None, None], [None, None, 'だ。', None]]
[['家屋', 'かおく', None, None], [None, None, 'は', True], ['兎', 'と', None, True], [None, None, 'も', True], ['角', 'かく', None, True], [None, None, 'としてもだ', True], [None, None, '、せめてアルバムだけでも', None], ['持', 'も', None, None], [None, None, 'って', None], ['逃', 'に', None, None], [None, None, 'げたい。', None]]
[[None, None, 'カタカナ', None], [None, None, 'は', True], ['兎', 'と', None, True], [None, None, 'も', True], ['角', 'かく', None, True], [None, None, '、', None], ['平仮名', 'ひらがな', None, None], [None, None, 'は', None], ['読', 'よ', None, None], [None, None, 'めないと', None], ['困', 'こま', None, None], [None, None, 'ります。', None]]
[['楽器', 'がっき', None, None], [None, None, 'は', True], ['兎', 'と', None, True], [None, None, 'も', True], ['角', 'かく', None, True], [None, None, '、せめて', None], ['歌', 'うた', None, None], [None, None, 'だけでも', None], ['歌', 'うた', None, None], [None, None, 'いましょうよ。', None]]
[['関東', 'かんとう', None, None], [None, None, 'は', True], ['兎', 'と', None, True], [None, None, 'も', True], ['角', 'かく', None, True], [None, None, '、', None], ['関西', 'かんさい', None, None], [None, None, 'でだけでもいいから', None], ['売', 'う', None, None], [None, None, 'れたい。', None]]

 78%|███████▊  | 727/938 [07:36<02:02,  1.73it/s]

[['生魚', 'なまざかな', None, None], [None, None, 'ならともかく', True], [None, None, '、', None], ['納豆', 'なっとう', None, None], [None, None, 'は', None], ['食', 'た', None, None], [None, None, 'べられません。', None]]
[['夜', 'よる', None, None], [None, None, 'ならともかく', True], [None, None, '、', None], ['夏', 'なつ', None, None], [None, None, 'は', None], ['日中', 'にっちゅう', None, None], [None, None, 'は', None], ['外', 'そと', None, None], [None, None, 'に', None], ['出', 'で', None, None], [None, None, 'られない。', None]]
[['赤', 'あか', None, None], [None, None, 'ん', None], ['坊', 'ぼう', None, None], [None, None, 'ならともかく', True], [None, None, '、', None], ['子供', 'こども', None, None], [None, None, 'には', None], ['叱', 'しか', None, None], [None, None, 'る', None], ['事', 'こと', None, None], [None, None, 'も', None], ['必要', 'ひつよう', None, None], [None, None, 'だ。', None]]
[['社長', 'しゃちょう', None, None], [None, None, 'ならともかく', True], [None, None, '、', None], ['平社員', 'ひらしゃいん', None, None], [None, None, 'に', None], ['決定権', 'けっていけん', None, None], [None, None, 'はありません。', None]]
[[None, None, 'イケメン', None], [None, None, 'ならともかく', True], [None, None, '、そうでない', None], ['人', 'ひと', None, None], [None, None, 'はナンパで', None], ['成功', 'せいこう', None, None], [None, None, 'しないだろう。', None]]

 78%|███████▊  | 728/938 [07:37<01:57,  1.79it/s]

[['嬉', 'うれ', None, None], [None, None, 'しい', None], [None, None, 'やら', True], ['恥', 'は', None, None], [None, None, 'ずかしい', None], [None, None, 'やら', True], [None, None, 'で、どんな', None], ['顔', 'かお', None, None], [None, None, 'をしていればいいのか、わからなかった。', None]]
[['彼', 'かれ', None, None], [None, None, 'に', None], ['褒', 'ほ', None, None], [None, None, 'めてもらうとうれしい', None], [None, None, 'やら', True], ['恥', 'は', None, None], [None, None, 'ずかしい', None], [None, None, 'やら', True], [None, None, '、とにかく', None], ['気持', 'きも', None, None], [None, None, 'ちがよかったわ。', None]]
[['髭', 'ひげ', None, None], [None, None, 'やら', True], ['頭髪', 'とうはつ', None, None], [None, None, 'やら', True], [None, None, 'の', None], ['身', 'み', None, None], [None, None, 'だしなみのチェックが', None], ['厳', 'きび', None, None], [None, None, 'しくて', None], ['困', 'こま', None, None], [None, None, 'る。', None]]
[['悪口', 'わるぐち', None, None], [None, None, 'やら', True], ['皮肉', 'ひにく', None, None], [None, None, 'やら', True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'はとにかく', None], ['口', 'くち', None, None], [None, None, 'が', None], ['悪', 'わる', None, None], [None, None, 'いから、あまり', None], ['付', 'つ', None, None], [None, None, 'き', None], ['合', 'あ', None, None], [None, None, 'いたくない。', None]]
[['小数', 'しょうすう', None, None], [None, None, 'やら', True], ['分数', 'ぶんすう', None, None], [None, None, 'やら', True], [None, None, 'の', None], ['問題', 'もんだい', None, None], [None, None, 'を', None], ['教', 'おし', None, None], [None, None, 'えて', None], ['欲', 'ほ', None, None], [None, None, 'しいと', None], ['言', 'い', None, None], [None, None, 'われても、', None], ['算数', 'さんすう', None, None], [None, None, 'が', None], ['苦手', 'にがて', None, None], [None, None, 'なもので...', None]]

 78%|███████▊  | 729/938 [07:37<02:01,  1.72it/s]

[['記事', 'きじ', None, None], [None, None, '：「', None], ['多', 'おお', None, None], [None, None, 'くの', None], ['喫煙者', 'きつえんしゃ', None, None], [None, None, 'は', None], ['喫煙', 'きつえん', None, None], [None, None, 'が', None], ['癌', 'がん', None, None], [None, None, 'の', None], ['原因', 'げんいん', None, None], [None, None, 'の', None], ['一', 'ひと', None, None], [None, None, 'つであることを', None], ['知', 'し', None, None], [None, None, 'っている。', None], [None, None, 'しかしながら', True], [None, None, '、', None], ['気', 'き', None, None], [None, None, 'にせずに', None], ['未', 'ま', None, None], [None, None, 'だタバコを', None], ['吸', 'す', None, None], [None, None, 'い', None], ['続', 'つづ', None, None], [None, None, 'けている。」', None]]
[[None, None, 'ある', None], ['電気自動車', 'でんきじどうしゃ', None, None], [None, None, 'は', None], ['自動的', 'じどうてき', None, None], [None, None, 'に', None], ['運転', 'うんてん', None, None], [None, None, 'することができる。', None], [None, None, 'しかしながら', True], ['運転者', 'うんてんしゃ', None, None], [None, None, 'はまだハンドルの', None], ['上', 'うえ', None, None], [None, None, 'に', None], ['手', 'て', None, None], [None, None, 'を', None], ['置', 'お', None, None], [None, None, 'く', None], ['必要', 'ひつよう', None, None], [None, None, 'がある。', None]]
[[None, None, 'オンラインの', None], ['安全性', 'あんぜんせい', None, None], [None, None, 'の', None], ['記事', 'きじ', None, None], [None, None, '：「オンラインショッピングは', None], ['安全', 'あんぜん', None, None], [None, None, 'だと', None], ['考', 'かんが', None, None], [None, None, 'えられている。', None], [None, None, 'しかしながら', True], ['詐欺', 'さぎ', None, None], [None, None, 'に', None], ['遭', 'あ', None, None], [None, None, 'う', None], ['可能性', 'かのうせい', None, None], [None, None, 'が', None], ['０', 'ぜろ', None, None], [None, None, 'であるわけではない。」', None]]
[['記事', 'きじ', None, None], [None, None, '：「オゾンホールの', None], ['問題', 'もんだい', None, None], [None, None, 'は', None], ['９０', 'きゅうじゅう', None, None], ['年代', 'ねんだい', None, None], [None, None, 'には', None], ['解決', 'かいけつ', None, None], [None, None, 'できるとは', None], ['思', 'おも', None, None], [None, None, 'われていなかった。', None], [None, None, 'しかしながら', True], [None, None, '、', None], ['国際協力', 'こくさいきょうりょく', None, None], [None, None, 'により、オゾン', None], ['層', 'そう', None, None], [None, None, 'は', None], ['２００５', 'にせんご', None, None], ['年', 'ねん', None, None], [None, None, 'ごろから', None], ['回復', 'かいふく', None, None], [None, None, 'が', None], ['進', 'すす', None, None], [None, None, 'んでいる。」', None]]
[[None, None, 'アニメーション', None], ['評価', 'ひょうか', None, None], [None, None, '：「『ジェイクとビーモ』というアニメーションは', None], ['子供', 'こども', None, None], ['向', 'む', None, None], [None, None, 'けである。', None], [None, None, 'しかしながら', True], [None, None, '、', None], ['子供', 'こども', None, None], [None, None, 'たちだけでなく', None], ['大人', 'おとな', None, None], ['向', 'む', None, None], [None, None, 'きでもある。」', None]]

 78%|███████▊  | 730/938 [07:38<02:07,  1.63it/s]

[['錆', 'さ', None, None], [None, None, 'びている', None], [None, None, 'からといって', None], [None, None, '、ガラクタだという', None], [None, None, 'ことにはならない', True], [None, None, '。', None]]
[[None, None, 'サンプルだ', None], [None, None, 'からといって', None], [None, None, '、', None], ['乱暴', 'らんぼう', None, None], [None, None, 'に', None], ['扱', 'あつか', None, None], [None, None, 'ってもいいという', None], [None, None, 'ことにはならない', True], [None, None, '。', None]]
[['祝日', 'しゅくじつ', None, None], [None, None, 'だ', None], [None, None, 'からといって', None], [None, None, '、いつまで', None], ['寝', 'ね', None, None], [None, None, 'ていてもいいという', None], [None, None, 'ことにはならない', True], [None, None, '。', None]]
[['実力', 'じつりょく', None, None], [None, None, 'がある', None], [None, None, 'からといって', None], [None, None, '、', None], ['威張', 'いば', None, None], [None, None, 'ってもいいという', None], [None, None, 'ことにはならない', True], [None, None, '。', None]]
[[None, None, 'ジャーナリストだ', None], [None, None, 'からといって', None], [None, None, '、', None], ['事実', 'じじつ', None, None], [None, None, 'を', None], ['何', 'なん', None, None], [None, None, 'でも', None], ['公表', 'こうひょう', None, None], [None, None, 'してもいいという', None], [None, None, 'ことにはならない', True], [None, None, '。', None]]

 78%|███████▊  | 731/938 [07:39<02:23,  1.45it/s]

[[None, None, 'かなりの', None], ['実力', 'じつりょく', None, None], [None, None, 'だ。', None], ['誘', 'さそ', None, None], [None, None, 'いを', None], ['蹴', 'け', None, None], [None, None, 'った', None], [None, None, 'だけのことはある', True], [None, None, '。', None]]
[[None, None, 'すごいことを', None], ['思', 'おも', None, None], [None, None, 'いついた。', None], ['苦心', 'くしん', None, None], [None, None, 'した', None], [None, None, 'だけのことはある', True], [None, None, '。', None]]
[['仕上', 'しあ', None, None], [None, None, 'がりが', None], ['完璧', 'かんぺき', None, None], [None, None, 'だ。', None], ['彼', 'かれ', None, None], [None, None, 'にお', None], ['願', 'ねが', None, None], [None, None, 'いした', None], [None, None, 'だけのことはある', True], [None, None, '。', None]]
[['利益', 'りえき', None, None], [None, None, 'が', None], ['上', 'あ', None, None], [None, None, 'がってきた。', None], ['経費', 'けいひ', None, None], [None, None, 'を', None], ['削', 'けず', None, None], [None, None, 'った', None], [None, None, 'だけのことはある', True], [None, None, '。', None]]
[[None, None, 'いい', None], ['芝居', 'しばい', None, None], [None, None, 'だった。', None], ['一生懸命', 'いっしょうけんめい', None, None], ['稽古', 'けいこ', None, None], [None, None, 'した', None], [None, None, 'だけのことはある', True], [None, None, '。', None]]

 78%|███████▊  | 732/938 [07:39<02:11,  1.56it/s]

[[None, None, 'くれぐれもこの', None], ['戸', 'と', None, None], [None, None, 'を', None], ['開', 'あ', None, True], [None, None, 'けてはならない', True], [None, None, '。', None]]
[['十代', 'じゅうだい', None, None], [None, None, 'はお', None], ['酒', 'さけ', None, None], [None, None, 'を', None], ['飲', 'の', None, True], [None, None, 'んではならない', True], [None, None, '。', None]]
[['市民', 'しみん', None, None], ['病院', 'びょういん', None, None], [None, None, 'ではタバコを', None], ['吸', 'す', None, True], [None, None, 'ってはならない', True], [None, None, '。', None]]
[['安易', 'あんい', None, None], [None, None, 'に', None], ['規律', 'きりつ', None, None], [None, None, 'を', None], ['破', 'やぶ', None, True], [None, None, 'ってはならない', True], [None, None, '。', None]]
[['何事', 'なにごと', None, None], [None, None, 'も', None], ['限度', 'げんど', None, None], [None, None, 'を', None], ['超', 'こ', None, True], [None, None, 'えてはならない', True], [None, None, '。', None]]

 78%|███████▊  | 733/938 [07:40<02:11,  1.56it/s]

[['時間', 'じかん', None, None], [None, None, 'がない。', None], ['下書', 'したが', None, None], [None, None, 'き', None], [None, None, 'しては', True], ['居', 'い', None, True], [None, None, 'られない', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['実績', 'じっせき', None, None], [None, None, 'を', None], ['上', 'あ', None, None], [None, None, 'げています。', None], ['負', 'ま', None, True], [None, None, 'けては', True], ['居', 'い', None, True], [None, None, 'られません', True], [None, None, '。', None]]
[['寒', 'さむ', None, None], [None, None, 'すぎて', None], ['写生', 'しゃせい', None, None], [None, None, 'してはいられません', True], [None, None, '。', None]]
[[None, None, 'もう', None], ['働', 'はたら', None, None], [None, None, 'くしかない。', None], ['受験', 'じゅけん', None, None], [None, None, 'しては', True], ['居', 'い', None, True], [None, None, 'られない', True], [None, None, '。', None]]
[[None, None, 'こんなひどい', None], ['商品', 'しょうひん', None, None], [None, None, '、', None], ['宣伝', 'せんでん', None, None], [None, None, 'しては', True], ['居', 'い', None, True], [None, None, 'られません', True], [None, None, '。', None]]

 78%|███████▊  | 734/938 [07:41<02:08,  1.59it/s]

[['陸', 'ろく', None, True], [None, None, 'に', True], ['準備', 'じゅんび', None, None], [None, None, 'もしてい', None], [None, None, 'ない', None], [None, None, 'のに、ショップをオープンさせた。', None]]
[['彼', 'かれ', None, None], [None, None, 'はケーキを', None], ['焼', 'や', None, None], [None, None, 'くどころか、シンプルな', None], ['料理', 'りょうり', None, None], [None, None, 'さえ', None], ['陸', 'ろく', None, True], [None, None, 'にできない', True], [None, None, '。', None]]
[['毎日', 'まいにち', None, None], [None, None, '、うちの', None], ['猫', 'ねこ', None, None], [None, None, 'に', None], ['起', 'お', None, None], [None, None, 'こされるせいで', None], ['陸', 'ろく', None, True], [None, None, 'に', True], ['寝', 'ね', None, True], [None, None, 'られない', True], [None, None, '。', None]]
[['陸', 'ろく', None, True], [None, None, 'に', True], ['演技', 'えんぎ', None, None], [None, None, 'もでき', None], [None, None, 'ない', None], [None, None, 'のに、テレビドラマのオファーがきた。', None]]
[['陸', 'ろく', None, True], [None, None, 'に', True], ['掃除', 'そうじ', None, None], [None, None, 'もし', None], [None, None, 'ない', None], [None, None, 'のに、なぜか', None], ['洗剤', 'せんざい', None, None], [None, None, 'をたくさん', None], ['持', 'も', None, None], [None, None, 'っている。', None]]

 78%|███████▊  | 735/938 [07:41<02:00,  1.68it/s]

[['私', 'わたし', None, None], [None, None, 'の', None], ['鼻', 'はな', None, None], [None, None, 'はとても', None], ['大', 'おお', None, None], [None, None, 'きく、', None], [None, None, 'しかも', True], ['曲', 'ま', None, None], [None, None, 'がっている。', None]]
[[None, None, 'あのスーパーの', None], ['肉', 'にく', None, None], [None, None, 'は', None], ['安', 'やす', None, None], [None, None, 'い。', None], [None, None, 'しかも', True], [None, None, '、', None], ['脂', 'あぶら', None, None], [None, None, 'がのっている。', None]]
[[None, None, 'プレーは', None], ['一流', 'いちりゅう', None, None], [None, None, '。', None], [None, None, 'しかも', True], [None, None, '、ファンに', None], ['優', 'やさ', None, None], [None, None, 'しい。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'は', None], ['常識', 'じょうしき', None, None], [None, None, 'を', None], ['知', 'し', None, None], [None, None, 'らない。', None], [None, None, 'しかも', True], [None, None, '、', None], ['厚', 'あつ', None, None], [None, None, 'かましい。', None]]
[[None, None, 'しかも', True], [None, None, '、', None], ['舞台', 'ぶたい', None, None], [None, None, 'の', None], ['途中', 'とちゅう', None, None], [None, None, 'に', None], ['足', 'あし', None, None], [None, None, 'が', None], ['絡', 'から', None, None], [None, None, 'んで、', None], ['転', 'こ', None, None], [None, None, 'けた。', None]]

 78%|███████▊  | 736/938 [07:42<01:55,  1.75it/s]

[[None, None, 'どんな', None], ['事', 'こと', None, None], [None, None, 'を', None], [None, None, 'してでも', True], [None, None, '、', None], ['海賊', 'かいぞく', None, None], ['王', 'おう', None, None], [None, None, 'になりたいぞ！', None]]
[[None, None, 'グループを', None], ['解散', 'かいさん', None, None], [None, None, 'してでも', True], ['守', 'まも', None, None], [None, None, 'りたい', None], ['秘密', 'ひみつ', None, None], [None, None, 'がある。', None]]
[['争', 'あらそ', None, True], [None, None, 'ってでも', True], [None, None, 'いいから、あの', None], ['契約', 'けいやく', None, None], [None, None, 'を', None], ['取', 'と', None, None], [None, None, 'ってこい！', None]]
[[None, None, 'それはまた', None], ['改', 'あらた', None, True], [None, None, 'めてでも', True], [None, None, 'いいので、', None], ['必', 'かなら', None, None], [None, None, 'ず', None], ['持', 'も', None, None], [None, None, 'ってきてください。', None]]
[['意地悪', 'いじわる', None, None], [None, None, 'と', None], ['思', 'おも', None, True], [None, None, 'われてでも', True], [None, None, '、', None], ['説得', 'せっとく', None, None], [None, None, 'するしかない。', None]]

 79%|███████▊  | 737/938 [07:42<01:50,  1.81it/s]

[[None, None, 'どんなことに', None], [None, None, 'なろうとも', True], [None, None, '、', None], ['国家', 'こっか', None, None], [None, None, 'が', None], ['破産', 'はさん', None, None], [None, None, 'するのはまずありえない。', None]]
[['頂点', 'ちょうてん', None, None], [None, None, 'には', None], ['届', 'とど', None, True], [None, None, 'かなくとも', True], [None, None, '、', None], ['行', 'い', None, None], [None, None, 'けるところまで', None], ['行', 'い', None, None], [None, None, 'ってみよう。', None]]
[[None, None, 'どんなに', None], ['生意気', 'なまいき', None, None], [None, None, 'に', None], [None, None, 'なろうとも', True], [None, None, '、わたしの', None], ['息子', 'むすこ', None, None], [None, None, 'であることに', None], ['変', 'か', None, None], [None, None, 'わりはない。', None]]
[['誰', 'だれ', None, None], [None, None, 'に', None], ['憎', 'にく', None, True], [None, None, 'まれようとも', True], [None, None, '、', None], ['使命', 'しめい', None, None], [None, None, 'を', None], ['果', 'は', None, None], [None, None, 'たさないわけにはいきません。', None]]
[[None, None, 'ため', None], ['息', 'いき', None, None], [None, None, 'が', None], ['出', 'で', None, True], [None, None, 'ようとも', True], [None, None, '、', None], ['仕事', 'しごと', None, None], [None, None, 'はやり', None], ['遂', 'と', None, None], [None, None, 'げなければなりません。', None]]

 79%|███████▊  | 738/938 [07:43<01:55,  1.74it/s]

[['訳', 'わけ', None, None], [None, None, 'あって、', None], ['白髪', 'しらが', None, None], [None, None, 'を', None], ['染', 'そ', None, True], [None, None, 'めないわけにはいかない', True], [None, None, 'んです。', None]]
[[None, None, 'ベテランの', None], ['職人', 'しょくにん', None, None], [None, None, 'でも、トレーニングを', None], [None, None, 'しないわけにはいかない', True], [None, None, '。', None]]
[['面倒', 'めんどう', None, None], [None, None, 'だからといって、', None], ['打', 'う', None, None], [None, None, 'ち', None], ['合', 'あ', None, None], [None, None, 'わせを', None], [None, None, 'しないわけにはいかない', True], [None, None, '。', None]]
[['締切', 'しめきり', None, None], ['前', 'まえ', None, None], [None, None, 'だからといって、まったく', None], ['寝', 'ね', None, True], [None, None, 'ないわけにはいかない', True], [None, None, '。', None]]
[['慣', 'な', None, None], [None, None, 'れたメニューだとはいえ、', None], ['味見', 'あじみ', None, None], [None, None, 'しないわけにはいかない', True], [None, None, '。', None]]

 79%|███████▉  | 739/938 [07:43<02:03,  1.62it/s]

[['苦情', 'くじょう', None, None], [None, None, 'という', True], ['訳', 'わけ', None, True], [None, None, 'ではなく', True], [None, None, '、', None], ['提案', 'ていあん', None, None], [None, None, 'です。', None]]
[['全', 'すべ', None, None], [None, None, 'てのキノコが', None], ['毒', 'どく', None, None], [None, None, 'を', None], ['持', 'も', None, None], [None, None, 'っている', None], [None, None, 'という', True], ['訳', 'わけ', None, True], [None, None, 'ではない', True], [None, None, '。', None]]
[['儀式', 'ぎしき', None, None], [None, None, 'という', True], ['訳', 'わけ', None, True], [None, None, 'ではない', True], [None, None, 'けど、あれはもはや', None], ['儀式', 'ぎしき', None, None], [None, None, 'に', None], ['近', 'ちか', None, None], [None, None, 'い。', None]]
[['正式', 'せいしき', None, None], [None, None, 'な', None], ['基準', 'きじゅん', None, None], [None, None, 'という', True], ['訳', 'わけ', None, True], [None, None, 'ではない', True], [None, None, 'ですが、', None], ['参考', 'さんこう', None, None], [None, None, 'にしてください。', None]]
[['警備', 'けいび', None, None], [None, None, 'という', True], ['訳', 'わけ', None, True], [None, None, 'ではない', True], [None, None, 'が、', None], ['近', 'ちか', None, None], [None, None, 'くにいてもらえるとありがたいです。', None]]

 79%|███████▉  | 740/938 [07:44<01:53,  1.74it/s]

[['状況', 'じょうきょう', None, None], [None, None, 'からして、', None], ['彼', 'かれ', None, None], [None, None, 'らがそう', None], ['考', 'かんが', None, None], [None, None, 'えた', None], [None, None, 'のも', True], ['尤', 'もっと', None, True], [None, None, 'も', True], [None, None, 'だ。', None]]
[[None, None, 'あの', None], ['本', 'ほん', None, None], [None, None, 'がいつも', None], ['貸', 'か', None, None], [None, None, 'し', None], ['出', 'だ', None, None], [None, None, 'し', None], ['中', 'ちゅう', None, None], [None, None, 'な', None], [None, None, 'のも', True], ['尤', 'もっと', None, True], [None, None, 'も', True], [None, None, 'だ。', None], ['大', 'だい', None, None], [None, None, 'ベストセラーだから。', None]]
[['ＳＮＳ', 'エスエヌエス', None, None], [None, None, 'の', None], ['投稿', 'とうこう', None, None], ['回数', 'かいすう', None, None], [None, None, 'を', None], ['減', 'へ', None, None], [None, None, 'らした', None], [None, None, 'のも', True], ['尤', 'もっと', None, True], [None, None, 'も', True], [None, None, 'だ。', None], ['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['忙', 'いそが', None, None], [None, None, 'しすぎる。', None]]
[['会社', 'かいしゃ', None, None], [None, None, 'の', None], ['規約', 'きやく', None, None], [None, None, 'を', None], ['改正', 'かいせい', None, None], [None, None, 'する', None], [None, None, 'のも', True], ['尤', 'もっと', None, True], [None, None, 'も', True], [None, None, 'だ。あの', None], ['規約', 'きやく', None, None], [None, None, 'は', None], ['古', 'ふる', None, None], [None, None, 'すぎる。', None]]
[['解説', 'かいせつ', None, None], ['者', 'しゃ', None, None], [None, None, 'が', None], ['言', 'い', None, None], [None, None, 'っている', None], [None, None, 'のも', True], ['尤', 'もっと', None, True], [None, None, 'も', True], [None, None, 'だ。かなり', None], ['的確', 'てきかく', None, None], [None, None, 'な', None], ['意見', 'いけん', None, None], [None, None, 'だと', None], ['思', 'おも', None, None], [None, None, 'います。', None]]

 79%|███████▉  | 741/938 [07:44<01:50,  1.79it/s]

[[None, None, 'パーティーにはピザじゃ', None], [None, None, 'なくたって', True], [None, None, 'かまわないよね。', None]]
[[None, None, 'ブロッコリーが', None], ['健康', 'けんこう', None, None], [None, None, 'に', None], ['良', 'よ', None, True], [None, None, 'くたって', True], [None, None, '、もう', None], ['食', 'た', None, None], [None, None, 'べたくない！', None]]
[[None, None, 'どんなに', None], ['押', 'お', None, True], [None, None, 'したくたって', True], [None, None, '、この', None], ['赤', 'あか', None, None], [None, None, 'いボタンを', None], ['押', 'お', None, None], [None, None, 'してはダメ。', None]]
[['海水浴', 'かいすいよく', None, None], [None, None, 'に', None], ['行', 'い', None, True], [None, None, 'ったって', True], ['僕', 'ぼく', None, None], [None, None, 'は', None], ['泳', 'およ', None, None], [None, None, 'げないからつまらない。', None]]
[[None, None, 'たとえ', None], ['彼', 'かれ', None, None], [None, None, 'がどこにいるか', None], ['知', 'し', None, None], [None, None, 'っていると', None], [None, None, 'したって', True], [None, None, '、それでもお', None], ['前', 'まえ', None, None], [None, None, 'には', None], ['教', 'おし', None, None], [None, None, 'えない。', None]]

 79%|███████▉  | 742/938 [07:45<01:44,  1.87it/s]

[[None, None, 'にしまさんはバーテンダー', None], [None, None, 'から', None], ['大企業', 'だいきぎょう', None, None], [None, None, 'の', None], ['社長', 'しゃちょう', None, None], [None, None, 'に', True], ['至', 'いた', None, True], [None, None, 'るまで', True], [None, None, 'いろいろな', None], ['仕事', 'しごと', None, None], [None, None, 'を', None], ['歴任', 'れきにん', None, None], [None, None, 'した。', None]]
[['今日', 'こんにち', None, None], [None, None, 'では、', None], ['ＣＰＵ', 'シーピーユー', None, None], [None, None, 'はパソコン', None], [None, None, 'から', None], ['歯', 'は', None, None], [None, None, 'ブラシ', None], [None, None, 'に', True], ['至', 'いた', None, True], [None, None, 'るまで', True], [None, None, '、さまざまな', None], ['装置', 'そうち', None, None], [None, None, 'に', None], ['見', 'み', None, None], [None, None, 'られる。', None]]
[['総理大臣', 'そうりだいじん', None, None], [None, None, 'から', None], ['一般人', 'いっぱんじん', None, None], [None, None, 'に', True], ['至', 'いた', None, True], [None, None, 'るまで', True], [None, None, 'あらゆる', None], ['市民', 'しみん', None, None], [None, None, 'は', None], ['法', 'ほう', None, None], [None, None, 'のもとで', None], ['平等', 'びょうどう', None, None], [None, None, 'である。', None]]
[['航海', 'こうかい', None, None], [None, None, 'の', None], ['初', 'はじ', None, None], [None, None, 'め', None], [None, None, 'から', None], ['事故', 'じこ', None, None], [None, None, 'そのもの', None], [None, None, 'に', True], ['至', 'いた', None, True], [None, None, 'るまで', True], [None, None, 'の', None], ['難破船', 'なんぱせん', None, None], [None, None, 'の', None], ['航海日誌', 'こうかいにっし', None, None], [None, None, 'が', None], ['見', 'み', None, None], [None, None, 'つかった。', None]]
[[None, None, 'アジアでは、', None], ['箸', 'はし', None, None], [None, None, 'は', None], ['昔', 'むかし', None, None], [None, None, 'より', None], ['現在', 'げんざい', None, None], [None, None, 'に', True], ['至', 'いた', None, True], [None, None, 'るまで', True], ['長', 'なが', None, None], [None, None, 'きに', None], ['渡', 'わた', None, None], [None, None, 'って、', None], ['食', 'た', None, None], [None, None, 'べるために', None], ['使', 'つか', None, None], [None, None, 'われている。', None]]

 79%|███████▉  | 743/938 [07:46<01:52,  1.74it/s]

[['徹夜', 'てつや', None, None], [None, None, 'で', None], ['勉強', 'べんきょう', None, None], [None, None, 'したところで', True], [None, None, '、', None], ['合格', 'ごうかく', None, None], [None, None, 'し', None], [None, None, 'ない', None], [None, None, '。', None]]
[[None, None, '「いまごろ', None], ['車', 'くるま', None, None], [None, None, 'に', None], ['乗', 'の', None, True], [None, None, 'って', True], ['行', 'い', None, True], [None, None, 'ったところで', True], ['間', 'ま', None, None], [None, None, 'に', None], ['合', 'あ', None, None], [None, None, 'いようが', None], [None, None, 'ない', None], [None, None, '。」', None]]
[[None, None, '「', None], ['謝', 'あやま', None, True], [None, None, 'ってみたところで', True], [None, None, '、', None], ['彼女', 'かのじょ', None, None], [None, None, 'が', None], ['許', 'ゆる', None, None], [None, None, 'してくれるわけ', None], [None, None, 'じゃない', None], [None, None, 'けど。」', None]]
[[None, None, '「たとえ', None], ['失敗', 'しっぱい', None, None], [None, None, 'してしまったところで', True], [None, None, '、 ', None], ['問題', 'もんだい', None, None], [None, None, 'は', None], [None, None, 'ありません', None], [None, None, '。」', None]]
[['私', 'わたし', None, None], [None, None, 'が', None], ['告白', 'こくはく', None, None], [None, None, 'したところで', True], [None, None, '、', None], ['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['応', 'おう', None, None], [None, None, 'じ', None], [None, None, 'ない', None], [None, None, 'だろう。', None]]

 79%|███████▉  | 744/938 [07:46<01:56,  1.67it/s]

[['彼女', 'かのじょ', None, None], [None, None, 'の', None], ['動', 'うご', None, None], [None, None, 'きはバレリーナ', None], [None, None, 'の', True], ['如', 'ごと', None, True], [None, None, 'し', True], [None, None, '。', None]]
[[None, None, 'ガンダルフ', None], [None, None, 'の', True], ['如', 'ごと', None, True], [None, None, 'き', True], ['英雄', 'えいゆう', None, None], [None, None, 'はたんと', None], ['無', 'な', None, None], [None, None, 'い。', None]]
[[None, None, 'ウサイン・ボルト', None], [None, None, 'の', True], ['如', 'ごと', None, True], [None, None, 'く', True], ['走', 'はし', None, None], [None, None, 'る。', None]]
[[None, None, 'サービス', None], ['業', 'ぎょう', None, None], [None, None, 'のマネージャーを', None], ['任', 'まか', None, None], [None, None, 'されている', None], ['私', 'わたし', None, None], [None, None, 'にとって、', None], ['休日', 'きゅうじつ', None, None], [None, None, 'などはあってなき', None], [None, None, 'が', None], ['如', 'ごと', None, True], [None, None, 'し', True], [None, None, '。', None]]
[['忍者', 'にんじゃ', None, None], [None, None, 'についての', None], ['小説', 'しょうせつ', None, None], [None, None, '：「カツラが', None], ['疾風', 'はやて', None, None], [None, None, 'の', True], ['如', 'ごと', None, True], [None, None, 'く', True], ['庭', 'にわ', None, None], [None, None, 'を', None], ['駆', 'か', None, None], [None, None, 'け', None], ['巡', 'めぐ', None, None], [None, None, 'り、', None], ['塀', 'へい', None, None], [None, None, 'を', None], ['飛', 'と', None, None], [None, None, 'び', None], ['越', 'こ', None, None], [None, None, 'えていった。」', None]]

 79%|███████▉  | 745/938 [07:47<01:51,  1.73it/s]

[[None, None, '「これは', None], ['多', 'おお', None, None], [None, None, 'くの', None], ['人', 'ひと', None, None], [None, None, 'の', None], ['興味', 'きょうみ', None, None], [None, None, 'を', None], ['引', 'ひ', None, None], [None, None, 'く', None], [None, None, 'に', True], ['足', 'た', None, True], [None, None, 'る', True], [None, None, 'ものではない。」', None]]
[['信頼', 'しんらい', None, None], [None, None, 'に', True], ['足', 'た', None, True], [None, None, 'る', True], ['友達', 'ともだち', None, None], [None, None, 'に、', None], ['腕', 'うで', None, None], [None, None, 'のいい', None], ['歯医者', 'はいしゃ', None, None], [None, None, 'を', None], ['紹介', 'しょうかい', None, None], [None, None, 'してもらった。', None]]
[['功績', 'こうせき', None, None], [None, None, 'から', None], ['考', 'かんが', None, None], [None, None, 'えると、その', None], ['専門分野', 'せんもんぶんや', None, None], [None, None, 'では', None], ['尊敬', 'そんけい', None, None], [None, None, 'に', True], ['足', 'た', None, True], [None, None, 'る', True], ['研究者', 'けんきゅうしゃ', None, None], [None, None, 'だ。', None]]
[[None, None, 'テスラ・モデル', None], ['Ｓ', 'エス', None, None], [None, None, 'は', None], ['語', 'かた', None, None], [None, None, 'る', None], [None, None, 'に', True], ['足', 'た', None, True], [None, None, 'る', True], ['電気', 'でんき', None, None], ['自動車', 'じどうしゃ', None, None], [None, None, 'であり、その', None], ['技術', 'ぎじゅつ', None, None], [None, None, 'は', None], ['世界', 'せかい', None, None], [None, None, 'に', None], ['認', 'みと', None, None], [None, None, 'められる。', None]]
[['地検', 'ちけん', None, None], [None, None, '：「', None], ['捜査', 'そうさ', None, None], [None, None, 'を', None], ['尽', 'つ', None, None], [None, None, 'くしましたが、', None], ['起訴', 'きそ', None, None], [None, None, 'する', None], [None, None, 'に', True], ['足', 'た', None, True], [None, None, 'る', True], ['証拠', 'しょうこ', None, None], [None, None, 'を', None], ['掴', 'つか', None, None], [None, None, 'むことができませんでした。」', None]]

 80%|███████▉  | 746/938 [07:47<01:54,  1.68it/s]

[['犯罪', 'はんざい', None, None], [None, None, 'を', None], ['犯', 'おか', None, None], [None, None, 'すのは', None], ['愚劣', 'ぐれつ', None, None], ['極', 'きわ', None, True], [None, None, 'まりない', True], [None, None, 'ことだ。', None]]
[['当初', 'とうしょ', None, None], [None, None, '、ベジータは', None], ['残忍', 'ざんにん', None, None], ['極', 'きわ', None, True], [None, None, 'まる', True], ['人', 'ひと', None, None], [None, None, 'だった。', None]]
[['警察官', 'けいさつかん', None, None], [None, None, 'は', None], ['危険', 'きけん', None, None], ['極', 'きわ', None, True], [None, None, 'まりない', True], ['仕事', 'しごと', None, None], [None, None, 'です。', None]]
[[None, None, 'ひらさわ・すすむさん', None], [None, None, '：「さすがにグレープフルーツはサワー', None], ['極', 'きわ', None, True], [None, None, 'まる', True], ['味', 'あじ', None, None], [None, None, 'があるわよ。」', None]]
[[None, None, 'ブログの', None], ['投稿', 'とうこう', None, None], [None, None, '：「', None], ['食', 'た', None, None], [None, None, 'べながら', None], ['話', 'はな', None, None], [None, None, 'すことは、', None], ['失礼', 'しつれい', None, None], ['極', 'きわ', None, True], [None, None, 'まりない', True], ['行為', 'こうい', None, None], [None, None, 'だと', None], ['考', 'かんが', None, None], [None, None, 'えられている。」', None]]

 80%|███████▉  | 747/938 [07:48<01:47,  1.77it/s]

[[None, None, 'ヒジカタが', None], ['恐', 'おそ', None, None], [None, None, 'るべし', None], [None, None, 'と', True], ['雖', 'いえど', None, True], [None, None, 'も', True], [None, None, '、スギモトの', None], ['敵', 'てき', None, None], [None, None, 'ではない。', None]]
[['手術', 'しゅじゅつ', None, None], ['中', 'ちゅう', None, None], [None, None, 'は', None], ['一瞬', 'いっしゅん', None, None], [None, None, 'と', True], ['雖', 'いえど', None, True], ['気', 'き', None, None], [None, None, 'が', None], ['抜', 'ぬ', None, None], [None, None, 'けない。', None]]
[[None, None, 'たとえ', None], ['囚人', 'しゅうじん', None, None], [None, None, 'と', True], ['雖', 'いえど', None, True], [None, None, 'も', True], [None, None, 'ときどき', None], ['刑務所', 'けいむしょ', None, None], [None, None, 'を', None], ['出', 'で', None, None], [None, None, 'ることができる。', None]]
[['雨天', 'うてん', None, None], [None, None, 'と', True], ['雖', 'いえど', None, True], [None, None, 'も', True], [None, None, '、ゴミ', None], ['拾', 'ひろ', None, None], [None, None, 'いのボランティアをしないわけにはいかない。', None]]
[['王様', 'おうさま', None, None], [None, None, 'と', True], ['雖', 'いえど', None, True], [None, None, 'も', True], [None, None, '、', None], ['法律', 'ほうりつ', None, None], [None, None, 'を', None], ['犯', 'おか', None, None], [None, None, 'すことは', None], ['出来', 'でき', None, None], [None, None, 'ません。', None]]

 80%|███████▉  | 748/938 [07:49<01:52,  1.70it/s]

[['以上', 'いじょう', None, None], [None, None, '、', None], ['本状', 'ほんじょう', None, None], [None, None, 'を', True], ['以', 'も', None, True], [None, None, 'って', True], ['辞表', 'じひょう', None, None], [None, None, 'と', None], ['致', 'いた', None, None], [None, None, 'します。', None]]
[['当選', 'とうせん', None, None], [None, None, 'は', None], ['賞品', 'しょうひん', None, None], [None, None, 'の', None], ['発送', 'はっそう', None, None], [None, None, 'を', True], ['以', 'もっ', None, True], [None, None, 'て', True], ['発表', 'はっぴょう', None, None], [None, None, 'に', None], ['代', 'か', None, None], [None, None, 'えさせていただきます。', None]]
[[None, None, 'ライトノベル', None], [None, None, '：「どうしてヒメジの', None], ['料理', 'りょうり', None, None], [None, None, 'がみんなに', None], ['避', 'さ', None, None], [None, None, 'けられるか、', None], ['身', 'み', None, None], [None, None, 'を', True], ['以', 'もっ', None, True], [None, None, 'て', True], ['知', 'し', None, None], [None, None, 'ったばかりだ。」', None]]
[['田中', 'たなか', None, None], [None, None, 'さんは', None], ['多数決', 'たすうけつ', None, None], [None, None, 'を', True], ['以', 'もっ', None, True], [None, None, 'て', True], ['労働', 'ろうどう', None, None], ['組合', 'くみあい', None, None], [None, None, 'の', None], ['代表', 'だいひょう', None, None], [None, None, 'として', None], ['選出', 'せんしゅつ', None, None], [None, None, 'されました。', None]]
[['採用', 'さいよう', None, None], ['担当者', 'たんとうしゃ', None, None], [None, None, '：「', None], ['面接', 'めんせつ', None, None], [None, None, 'の', None], ['結果', 'けっか', None, None], [None, None, 'は', None], ['電話', 'でんわ', None, None], [None, None, 'を', True], ['以', 'もっ', None, True], [None, None, 'て', True], [None, None, 'ご', None], ['連絡', 'れんらく', None, None], [None, None, 'いたします。」', None]]

 80%|███████▉  | 749/938 [07:49<01:50,  1.71it/s]

[['近頃', 'ちかごろ', None, None], [None, None, 'の', None], ['親', 'おや', None, None], [None, None, 'は', None], ['過保護', 'かほご', None, None], [None, None, 'のきらいがある', True], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['彼', 'かれ', None, None], [None, None, 'の', None], ['気持', 'きも', None, None], [None, None, 'ちを', None], ['尊重', 'そんちょう', None, None], [None, None, 'しない', None], [None, None, 'きらいがある', True], [None, None, '。', None]]
[[None, None, 'ある', None], ['人', 'ひと', None, None], [None, None, 'は、', None], ['民族', 'みんぞく', None, None], [None, None, 'だけで', None], ['人', 'ひと', None, None], [None, None, 'の', None], ['性格', 'せいかく', None, None], [None, None, 'を', None], ['判断', 'はんだん', None, None], [None, None, 'してしまう', None], [None, None, 'きらいがある', True], [None, None, '。', None]]
[[None, None, 'お', None], ['父', 'とう', None, None], [None, None, 'さんは、', None], ['困', 'こま', None, None], [None, None, 'っている', None], ['人', 'ひと', None, None], [None, None, 'のためには', None], ['人助', 'ひとだす', None, None], [None, None, 'けをする。しかし', None], ['助', 'たす', None, None], [None, None, 'けてもらった', None], ['人', 'ひと', None, None], [None, None, 'は、されたことを', None], ['忘', 'わす', None, None], [None, None, 'れる', None], [None, None, 'きらいがある', True], [None, None, '。', None]]
[['記事', 'きじ', None, None], [None, None, '：「', None], ['高血圧', 'こうけつあつ', None, None], [None, None, 'のきらいがある', True], [None, None, 'ことを', None], ['除', 'のぞ', None, None], [None, None, 'けばほとんど', None], ['健康', 'けんこう', None, None], [None, None, 'だった', None], ['３４', 'さんじゅうよん', None, None], ['歳', 'さい', None, None], [None, None, 'の', None], ['男性', 'だんせい', None, None], [None, None, 'はバクテリアの', None], ['感染', 'かんせん', None, None], [None, None, 'により', None], ['重体', 'じゅうたい', None, None], [None, None, 'に', None], ['陥', 'おちい', None, None], [None, None, 'った。」', None]]

 80%|███████▉  | 750/938 [07:50<01:52,  1.67it/s]

[[None, None, 'すみませんが、', None], ['付', 'つ', None, None], [None, None, 'き', None], ['合', 'あ', None, None], [None, None, 'う', None], [None, None, 'ぐらい', None], [None, None, 'ならまだしも', True], [None, None, '、', None], ['結婚', 'けっこん', None, None], [None, None, 'は', None], ['無理', 'むり', None, None], [None, None, 'な', None], ['注文', 'ちゅうもん', None, None], [None, None, 'です。', None]]
[[None, None, 'すごく', None], ['恥', 'は', None, None], [None, None, 'ずかしい！お', None], ['父', 'とう', None, None], [None, None, 'さん、ビーチで', None], [None, None, 'ならまだしも', True], [None, None, '、', None], ['半裸', 'はんら', None, None], [None, None, 'で', None], ['外', 'そと', None, None], [None, None, 'に', None], ['出', 'で', None, None], [None, None, 'るのはやめてほしい！', None]]
[[None, None, '「ねぇ、', None], ['歩', 'ある', None, None], [None, None, 'いて', None], ['行', 'い', None, None], [None, None, 'こうよ。」', None], [None, None, '「', None], ['自転車', 'じてんしゃ', None, None], [None, None, 'ならまだしも', True], [None, None, '、そんな', None], ['遠', 'とお', None, None], [None, None, 'くまで', None], ['歩', 'ある', None, None], [None, None, 'いて', None], ['行', 'い', None, None], [None, None, 'くのは', None], ['無理', 'むり', None, None], [None, None, 'だよ。」', None]]
[['隣人', 'りんじん', None, None], [None, None, 'がうちの', None], ['駐車', 'ちゅうしゃ', None, None], ['区域', 'くいき', None, None], [None, None, 'にたまに', None], ['車', 'くるま', None, None], [None, None, 'を', None], ['止', 'と', None, None], [None, None, 'める', None], [None, None, 'ならまだしも', True], [None, None, '、いつも', None], ['止', 'と', None, None], [None, None, 'めているから、いい', None], ['加減', 'かげん', None, None], ['腹', 'はら', None, None], [None, None, 'が', None], ['立', 'た', None, None], [None, None, 'つよ。', None]]
[[None, None, 'ツイート', None], [None, None, '：「', None], ['自分', 'じぶん', None, None], [None, None, 'が', None], ['感染', 'かんせん', None, None], [None, None, 'する', None], [None, None, 'だけ', None], [None, None, 'ならまだしも', True], ['祖父母', 'そふぼ', None, None], [None, None, 'や', None], ['親', 'おや', None, None], [None, None, 'などが', None], ['病気', 'びょうき', None, None], [None, None, 'になってしまうのがとても', None], ['恐', 'おそ', None, None], [None, None, 'ろしいです。」', None]]

 80%|████████  | 751/938 [07:50<01:46,  1.75it/s]

[[None, None, '「', None], ['今', 'いま', None, None], [None, None, 'さら', None], ['訂正', 'ていせい', None, None], [None, None, 'する', None], [None, None, 'までもなく', True], [None, None, '、', None], ['明', 'あき', None, None], [None, None, 'らかに', None], ['間違', 'まちが', None, None], [None, None, 'っている。」', None]]
[['先生', 'せんせい', None, None], [None, None, 'は、すでに', None], ['全', 'すべ', None, None], [None, None, 'て', None], ['解説', 'かいせつ', None, None], [None, None, 'したので', None], ['聞', 'き', None, None], [None, None, 'く', None], [None, None, 'までもない', True], [None, None, '。', None]]
[[None, None, 'これはただの', None], ['打撲', 'だぼく', None, None], [None, None, 'で', None], ['骨', 'ほね', None, None], [None, None, 'にヒビが', None], ['入', 'はい', None, None], [None, None, 'っているわけではないので', None], ['病院', 'びょういん', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'までもない', True], [None, None, '。', None]]
[[None, None, 'あのね......そんごくうはクリリンなんかとは', None], ['比', 'くら', None, None], [None, None, 'べる', None], [None, None, 'までもなく', True], [None, None, '、それどころかベジータよりもずっと', None], ['強', 'つよ', None, None], [None, None, 'いんだから。', None]]
[[None, None, 'この', None], ['試験', 'しけん', None, None], [None, None, 'の', None], ['難', 'むずか', None, None], [None, None, 'しさから', None], ['考', 'かんが', None, None], [None, None, 'えると、', None], ['試験', 'しけん', None, None], [None, None, 'の', None], ['結果', 'けっか', None, None], ['発表', 'はっぴょう', None, None], [None, None, 'は', None], ['見', 'み', None, None], [None, None, 'る', None], [None, None, 'までもなく', True], ['明', 'あき', None, None], [None, None, 'らかだ。', None]]

 80%|████████  | 752/938 [07:51<01:41,  1.83it/s]

[['大人', 'おとな', None, None], [None, None, 'ともなると', True], [None, None, '、', None], ['幼馴染', 'おさななじみ', None, None], [None, None, 'との', None], ['友情', 'ゆうじょう', None, None], [None, None, 'は', None], ['弱', 'よわ', None, None], [None, None, 'くなりつつあるだろう。', None]]
[[None, None, 'チームリーダーに', None], ['就任', 'しゅうにん', None, None], [None, None, 'する', None], [None, None, 'ともなると', True], [None, None, '、', None], ['自分', 'じぶん', None, None], [None, None, 'の', None], ['仕事', 'しごと', None, None], [None, None, 'に', None], ['限', 'かぎ', None, None], [None, None, 'らずチームメンバーの', None], ['仕事', 'しごと', None, None], [None, None, 'に', None], ['責任', 'せきにん', None, None], [None, None, 'があるだろう。', None]]
[['普段', 'ふだん', None, None], [None, None, 'は', None], ['貪欲', 'どんよく', None, None], [None, None, 'ではない', None], ['人', 'ひと', None, None], [None, None, 'でも、', None], ['莫大', 'ばくだい', None, None], [None, None, 'な', None], ['金額', 'きんがく', None, None], [None, None, 'ともなると', True], ['貪欲', 'どんよく', None, None], [None, None, 'になるかもしれない。', None]]
[[None, None, 'この', None], ['辺', 'あた', None, None], [None, None, 'りでは', None], ['１１', 'じゅういち', None, None], ['月', 'がつ', None, None], [None, None, 'ともなると', True], ['中々', 'なかなか', None, None], ['寒', 'さむ', None, None], [None, None, 'さも', None], ['厳', 'きび', None, None], [None, None, 'しくなってくるため、これからの', None], ['時期', 'じき', None, None], [None, None, 'はヒートテックが', None], ['必須', 'ひっす', None, None], [None, None, 'だろう。', None]]
[[None, None, 'ここは', None], ['普通', 'ふつう', None, None], [None, None, 'の', None], ['漁村', 'ぎょそん', None, None], [None, None, 'だが、', None], ['夏休', 'なつやす', None, None], [None, None, 'み', None], [None, None, 'ともなると', True], ['大勢', 'おおぜい', None, None], [None, None, 'の', None], ['客', 'きゃく', None, None], [None, None, 'が', None], ['来', 'き', None, None], [None, None, 'て、', None], ['賑', 'にぎ', None, None], [None, None, 'やかになります。', None]]

 80%|████████  | 753/938 [07:51<01:39,  1.86it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], ['私', 'わたし', None, None], [None, None, 'が', None], ['稼', 'かせ', None, None], [None, None, 'いでいる', None], [None, None, 'のを', True], ['良', 'い', None, True], [None, None, 'い', True], ['事', 'こと', None, True], [None, None, 'に', True], [None, None, '、', None], ['遊', 'あそ', None, None], [None, None, 'んでばかりいます。', None]]
[['先生', 'せんせい', None, None], [None, None, 'の', None], ['目', 'め', None, None], [None, None, 'が', None], ['悪', 'わる', None, None], [None, None, 'い', None], [None, None, 'のを', True], ['良', 'い', None, True], [None, None, 'い', True], ['事', 'こと', None, True], [None, None, 'に', True], ['試験', 'しけん', None, None], ['中', 'ちゅう', None, None], [None, None, 'にカンニングしていた。', None]]
[['私', 'わたし', None, None], [None, None, 'はお', None], ['母', 'かあ', None, None], [None, None, 'さんが', None], ['忘', 'わす', None, None], [None, None, 'れっぽい', None], [None, None, 'のを', True], ['良', 'い', None, True], [None, None, 'い', True], ['事', 'こと', None, True], [None, None, 'に', True], [None, None, '、', None], ['責任', 'せきにん', None, None], [None, None, 'から', None], ['逃', 'のが', None, None], [None, None, 'れようとした。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['新入社員', 'しんにゅうしゃいん', None, None], [None, None, 'なのを', True], ['良', 'い', None, True], [None, None, 'い', True], ['事', 'こと', None, True], [None, None, 'に', True], [None, None, '、', None], ['仕事', 'しごと', None, None], [None, None, 'が', None], ['出来', 'でき', None, None], [None, None, 'ないふりをしている。', None]]
[['敵', 'てき', None, None], [None, None, 'が', None], ['罠', 'わな', None, None], [None, None, 'にはまった', None], [None, None, 'のを', True], ['良', 'い', None, True], [None, None, 'い', True], ['事', 'こと', None, True], [None, None, 'に', True], [None, None, '、', None], ['全力', 'ぜんりょく', None, None], [None, None, 'で', None], ['総攻撃', 'そうこうげき', None, None], [None, None, 'をしかけた。', None]]

 80%|████████  | 754/938 [07:52<01:42,  1.79it/s]

[['入学', 'にゅうがく', None, None], ['試験', 'しけん', None, None], [None, None, 'の', None], ['成績', 'せいせき', None, None], ['如何', 'いかん', None, True], [None, None, 'で', None], [None, None, '、', None], ['私', 'わたし', None, None], [None, None, 'の', None], ['将来', 'しょうらい', None, None], [None, None, 'が', None], ['決', 'き', None, None], [None, None, 'まる。', None]]
[['中東', 'ちゅうとう', None, None], ['情勢', 'じょうせい', None, None], ['如何', 'いかん', None, True], [None, None, 'で', True], [None, None, 'は', None], ['石油', 'せきゆ', None, None], ['価格', 'かかく', None, None], [None, None, 'が', None], ['急上昇', 'きゅうじょうしょう', None, None], [None, None, 'しかねない。', None]]
[['衝突', 'しょうとつ', None, None], ['事故', 'じこ', None, None], [None, None, 'ならば', None], ['傷', 'きず', None, None], [None, None, 'の', None], ['状態', 'じょうたい', None, None], ['如何', 'いかん', None, True], [None, None, 'によって', None], [None, None, 'は', None], ['入院', 'にゅういん', None, None], [None, None, 'する', None], ['場合', 'ばあい', None, None], [None, None, 'もありうる。', None]]
[[None, None, '「', None], ['応募者', 'おうぼしゃ', None, None], [None, None, 'の', None], ['採用', 'さいよう', None, None], [None, None, '・', None], ['不採用', 'ふさいよう', None, None], [None, None, 'は', None], ['書類選考', 'しょるいせんこう', None, None], [None, None, 'の', None], ['結果', 'けっか', None, None], ['如何', 'いかん', None, True], [None, None, 'です。」', None]]
[['相手', 'あいて', None, None], [None, None, 'の', None], ['対応', 'たいおう', None, None], ['如何', 'いかん', None, True], [None, None, 'で', True], [None, None, 'は、', None], ['今回', 'こんかい', None, None], [None, None, 'の', None], ['件', 'けん', None, None], [None, None, 'を', None], ['裁判', 'さいばん', None, None], ['沙汰', 'ざた', None, None], [None, None, 'にしようと', None], ['思', 'おも', None, None], [None, None, 'っている。', None]]

 80%|████████  | 755/938 [07:52<01:38,  1.86it/s]

[[None, None, '「', None], ['問題', 'もんだい', None, None], [None, None, 'が', None], ['起', 'お', None, None], [None, None, 'きても、', None], ['解決', 'かいけつ', None, True], [None, None, 'するまでだ', True], [None, None, 'よ', None], [None, None, '。」', None]]
[[None, None, 'もし', None], ['ＪＬＰＴ', 'ジェーエルピーティー', None, None], [None, None, 'に', None], ['落', 'お', None, None], [None, None, 'ちたら、もう', None], ['一度', 'いちど', None, None], ['試', 'ため', None, True], [None, None, 'してみるまでのことだ', True], [None, None, '。', None]]
[['電車', 'でんしゃ', None, None], [None, None, 'に', None], ['乗', 'の', None, None], [None, None, 'り', None], ['遅', 'おく', None, None], [None, None, 'れたら、', None], ['次', 'つぎ', None, None], [None, None, 'のを', None], ['待', 'ま', None, True], [None, None, 'つまでのことだ', True], [None, None, '。', None]]
[['夫婦', 'ふうふ', None, None], [None, None, 'の', None], ['話', 'はなし', None, None], [None, None, '：「やめなくちゃならないというなら、', None], [None, None, 'やめるまでのことだ', True], [None, None, '。」', None]]
[['祖国', 'そこく', None, None], [None, None, 'で', None], ['就職', 'しゅうしょく', None, None], [None, None, 'できなかったら、', None], ['外国', 'がいこく', None, None], [None, None, 'へ', None], ['移住', 'いじゅう', None, None], [None, None, 'することに', None], [None, None, 'なるまでだ', True], [None, None, '。', None]]

 81%|████████  | 756/938 [07:53<01:35,  1.90it/s]

[['好況', 'こうきょう', None, None], [None, None, 'にあっても', True], ['破産', 'はさん', None, None], [None, None, 'を', None], ['申請', 'しんせい', None, None], [None, None, 'している', None], ['企業', 'きぎょう', None, None], [None, None, 'がある。', None]]
[['危険', 'きけん', None, None], [None, None, 'な', None], ['非常時', 'ひじょうじ', None, None], [None, None, 'にあって', True], [None, None, 'は、', None], ['安全', 'あんぜん', None, None], ['確保', 'かくほ', None, None], [None, None, 'が', None], ['第一', 'だいいち', None, None], [None, None, 'だ。', None]]
[[None, None, 'このような', None], ['状況', 'じょうきょう', None, None], ['下', 'か', None, None], [None, None, 'にあって', True], [None, None, '、', None], ['医療機関', 'いりょうきかん', None, None], [None, None, 'へのアクセスは', None], ['限定', 'げんてい', None, None], [None, None, 'されているかもしれない。', None]]
[['ＣＥＯ', 'シーイーオー', None, None], [None, None, 'のスピーチ', None], [None, None, '：「', None], ['混乱期', 'こんらんき', None, None], [None, None, 'にあっても', True], ['心配', 'しんぱい', None, None], [None, None, 'せずに', None], ['将来', 'しょうらい', None, None], [None, None, 'を', None], ['見据', 'みす', None, None], [None, None, 'えます。」', None]]
[['歴史', 'れきし', None, None], [None, None, 'の', None], ['教科書', 'きょうかしょ', None, None], [None, None, '：「', None], ['総理大臣', 'そうりだいじん', None, None], [None, None, 'という', None], ['立場', 'たちば', None, None], [None, None, 'にあって', True], [None, None, '、', None], ['言論', 'げんろん', None, None], [None, None, 'の', None], ['自由', 'じゆう', None, None], [None, None, 'のみならず', None], ['動物', 'どうぶつ', None, None], [None, None, 'の', None], ['権利', 'けんり', None, None], [None, None, 'も', None], ['提唱', 'ていしょう', None, None], [None, None, 'した。」', None]]

 81%|████████  | 757/938 [07:54<01:54,  1.58it/s]

[['景気', 'けいき', None, None], ['悪化', 'あっか', None, None], [None, None, 'のため、', None], ['会社', 'かいしゃ', None, None], [None, None, 'は', None], ['閉鎖', 'へいさ', None, None], [None, None, 'を', True], ['余儀', 'よぎ', None, True], [None, None, 'なくされた', True], [None, None, '。', None]]
[['津波', 'つなみ', None, None], [None, None, 'が', None], ['接近', 'せっきん', None, None], [None, None, 'したため、', None], ['野外', 'やがい', None, None], [None, None, 'コンサートは', None], ['中止', 'ちゅうし', None, None], [None, None, 'を', True], ['余儀', 'よぎ', None, True], [None, None, 'なくされた', True], [None, None, '。', None]]
[['少子', 'しょうし', None, None], ['化', 'か', None, None], [None, None, 'により', None], ['学生', 'がくせい', None, None], [None, None, 'が', None], ['減', 'へ', None, None], [None, None, 'れば、', None], ['多', 'おお', None, None], [None, None, 'くの', None], ['学校', 'がっこう', None, None], [None, None, 'は', None], ['閉校', 'へいこう', None, None], [None, None, 'を', True], ['余儀', 'よぎ', None, True], [None, None, 'なくされる', True], [None, None, 'だろう。', None]]
[['国民', 'こくみん', None, None], [None, None, 'による', None], ['反発', 'はんぱつ', None, None], [None, None, 'が', None], ['強', 'つよ', None, None], [None, None, 'まったために、', None], ['政府', 'せいふ', None, None], [None, None, 'は', None], ['補助', 'ほじょ', None, None], ['金', 'きん', None, None], [None, None, 'の', None], ['配布', 'はいふ', None, None], [None, None, 'を', True], ['余儀', 'よぎ', None, True], [None, None, 'なくされました', True], [None, None, '。', None]]
[['津波', 'つなみ', None, None], [None, None, 'によって', None], ['家', 'いえ', None, None], [None, None, 'を', None], ['流', 'なが', None, None], [None, None, 'されてしまった', None], ['被災', 'ひさい', None, None], ['者', 'しゃ', None, None], ['達', 'たち', None, None], [None, None, 'は、', None], ['避難', 'ひなん', None, None], ['所', 'じょ', None, None], [None, None, 'での', None], ['生活', 'せいかつ', None, None], [None, None, 'を', True], ['余儀', 'よぎ', None, True], [None, None, 'なくされた', True], [None, None, '。', None]]

 81%|████████  | 758/938 [07:54<01:47,  1.67it/s]

[[None, None, 'こんなところでキアヌ・リーブスに', None], ['出会', 'であ', None, None], [None, None, 'った', None], [None, None, 'とは', True], [None, None, 'ねぇ！', None]]
[[None, None, '「', None], ['一戸建', 'いっこだ', None, None], [None, None, 'てに', None], ['住', 'す', None, None], [None, None, 'むってこれほどまでに', None], ['大変', 'たいへん', None, None], [None, None, 'だった', None], [None, None, 'とは', True], ['驚', 'おどろ', None, None], [None, None, 'きだ', None], [None, None, 'よ。」', None]]
[[None, None, 'まさか', None], ['二', 'に', None, None], ['ヶ月', 'かげつ', None, None], [None, None, 'で', None], ['１０', 'じゅっ', None, None], [None, None, 'キロも', None], ['痩', 'や', None, None], [None, None, 'せる', None], [None, None, 'とは', True], [None, None, '！このダイエットは', None], ['効果', 'こうか', None, None], ['的', 'てき', None, None], [None, None, 'だ！', None]]
[[None, None, 'メアリーさんとたけしさんが', None], ['去年', 'きょねん', None, None], [None, None, 'もう', None], ['一度', 'いちど', None, None], ['新婚旅行', 'しんこんりょこう', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'った', None], [None, None, 'とは', True], ['驚', 'おどろ', None, None], [None, None, 'いた', None], [None, None, '。', None]]
[['病弱', 'びょうじゃく', None, None], [None, None, 'で', None], ['内気', 'うちき', None, None], [None, None, 'だった', None], ['田中', 'たなか', None, None], [None, None, 'さんがボクシングチャンピオンになる', None], [None, None, 'とは', True], ['夢', 'ゆめ', None, None], [None, None, 'にも', None], ['思', 'おも', None, None], [None, None, 'わなかった', None], [None, None, 'よ！', None]]

 81%|████████  | 759/938 [07:55<01:50,  1.62it/s]

[['減', 'へ', None, None], [None, None, 'るもん', None], [None, None, 'じゃあるまいし', True], ['車', 'くるま', None, None], [None, None, 'を', None], ['貸', 'か', None, None], [None, None, 'してくれ。', None]]
[['子供', 'こども', None, None], [None, None, 'じゃあるまいし', True], [None, None, 'お', None], ['菓子', 'かし', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'つけた', None], ['途端', 'とたん', None, None], [None, None, 'に', None], ['全部', 'ぜんぶ', None, None], ['食', 'た', None, None], [None, None, 'べるな！', None]]
[[None, None, 'アニメ', None], [None, None, 'じゃあるまいし', True], [None, None, '、かわいい', None], ['女', 'おんな', None, None], [None, None, 'の', None], ['子', 'こ', None, None], [None, None, 'は', None], ['急', 'きゅう', None, None], [None, None, 'に', None], ['空', 'そら', None, None], [None, None, 'から', None], ['落', 'お', None, None], [None, None, 'ちてこない。', None]]
[['田中', 'たなか', None, None], [None, None, 'さん！', None], ['新入', 'しんにゅう', None, None], ['社員', 'しゃいん', None, None], [None, None, 'でもあるまいし', True], [None, None, '！そんな', None], ['簡単', 'かんたん', None, None], [None, None, 'なミスはすべきじゃないよ。', None]]
[[None, None, 'お', None], ['父', 'とう', None, None], [None, None, 'さん、', None], ['結婚', 'けっこん', None, None], [None, None, 'する', None], [None, None, 'わけ', None], [None, None, 'じゃあるまいし', True], [None, None, '、ただの', None], ['学校', 'がっこう', None, None], [None, None, 'のパーティーだよ。', None], ['泣', 'な', None, None], [None, None, 'かないで。', None]]

 81%|████████  | 760/938 [07:55<01:42,  1.74it/s]

[['赤', 'あか', None, None], [None, None, 'ちゃんが', None], ['生', 'う', None, None], [None, None, 'まれて', None], [None, None, 'からというもの', True], [None, None, '、もっと', None], ['本気', 'ほんき', None, None], [None, None, 'で', None], ['働', 'はたら', None, None], [None, None, 'くようになった。', None]]
[[None, None, 'あやうく', None], ['溺', 'おぼ', None, None], [None, None, 'れかけて', None], [None, None, 'からというもの', True], [None, None, '、', None], ['泳', 'およ', None, None], [None, None, 'ぎ', None], ['方', 'かた', None, None], [None, None, 'を', None], ['習', 'なら', None, None], [None, None, 'い', None], ['始', 'はじ', None, None], [None, None, 'めました。', None]]
[[None, None, 'ツイート', None], [None, None, '：「', None], ['娘', 'むすめ', None, None], [None, None, 'が', None], ['生', 'う', None, None], [None, None, 'まれて', None], [None, None, 'からというもの', True], [None, None, '、', None], ['一日', 'いちにち', None, None], [None, None, 'たりともろくに', None], ['眠', 'ねむ', None, None], [None, None, 'れていない。」', None]]
[[None, None, 'スペース', None], ['Ｘ', 'エックス', None, None], [None, None, 'のファルコンヘビーの', None], ['離陸', 'りりく', None, None], [None, None, 'を', None], ['観', 'み', None, None], [None, None, 'て', None], [None, None, 'からというもの', True], [None, None, '、', None], ['宇宙', 'うちゅう', None, None], [None, None, 'が', None], ['頭', 'あたま', None, None], [None, None, 'から', None], ['離', 'はな', None, None], [None, None, 'れない。', None]]
[['親友', 'しんゆう', None, None], [None, None, 'が', None], ['鬱', 'うつ', None, None], [None, None, 'で', None], ['自殺', 'じさつ', None, None], [None, None, 'して', None], [None, None, 'からというもの', True], [None, None, '、', None], ['心理', 'しんり', None, None], ['学', 'がく', None, None], [None, None, 'を', None], ['勉強', 'べんきょう', None, None], [None, None, 'してカウンセラーになりたいとずっと', None], ['夢', 'ゆめ', None, None], ['見', 'み', None, None], [None, None, 'ている。', None]]

 81%|████████  | 761/938 [07:56<01:36,  1.83it/s]

[['本業', 'ほんぎょう', None, None], [None, None, 'の', True], ['傍', 'かたわ', None, True], [None, None, 'ら', True], [None, None, 'バイトなどの', None], ['副業', 'ふくぎょう', None, None], [None, None, 'をしている', None], ['多数', 'たすう', None, None], [None, None, 'の', None], ['人々', 'ひとびと', None, None], [None, None, 'がいる。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['大学', 'だいがく', None, None], [None, None, 'で', None], ['教', 'おし', None, None], [None, None, 'える', None], ['傍', 'かたわ', None, True], [None, None, 'ら', True], [None, None, '、', None], ['家', 'いえ', None, None], [None, None, 'でも', None], ['個人', 'こじん', None, None], ['指導', 'しどう', None, None], [None, None, 'をしている。', None]]
[[None, None, 'さらに', None], ['大学', 'だいがく', None, None], [None, None, 'での', None], ['国語', 'こくご', None, None], [None, None, 'の', None], ['教授', 'きょうじゅ', None, None], [None, None, 'をしている', None], ['傍', 'かたわ', None, True], [None, None, 'ら', True], [None, None, '、', None], ['漫画家', 'まんがか', None, None], [None, None, 'として', None], ['活躍', 'かつやく', None, None], [None, None, 'している。', None]]
[[None, None, 'ブルースは、', None], ['昼', 'ひる', None, None], [None, None, 'は', None], ['財閥', 'ざいばつ', None, None], [None, None, 'を', None], ['経営', 'けいえい', None, None], [None, None, 'する', None], ['傍', 'かたわ', None, True], [None, None, 'ら', True], [None, None, '、', None], ['夜', 'よる', None, None], [None, None, 'はバーマンとして', None], ['危険', 'きけん', None, None], ['地域', 'ちいき', None, None], [None, None, 'を', None], ['見回', 'みまわ', None, None], [None, None, 'っている。', None]]
[[None, None, 'いくつかの', None], ['国', 'くに', None, None], [None, None, 'では、', None], ['女性', 'じょせい', None, None], [None, None, 'は', None], ['仕事', 'しごと', None, None], [None, None, 'の', True], ['傍', 'かたわ', None, True], [None, None, 'ら', True], [None, None, '、', None], ['苦労', 'くろう', None, None], [None, None, 'をいとわず', None], ['子供', 'こども', None, None], [None, None, 'を', None], ['育', 'そだ', None, None], [None, None, 'てている。', None], ['立派', 'りっぱ', None, None], [None, None, 'なことだと', None], ['思', 'おも', None, None], [None, None, 'う。', None]]

 81%|████████  | 762/938 [07:56<01:35,  1.85it/s]

[['店', 'みせ', None, None], [None, None, 'の', None], ['移転', 'いてん', None, None], [None, None, 'を', True], ['皮切', 'かわき', None, True], [None, None, 'りとして', True], [None, None, '、', None], ['売上', 'うりあ', None, None], [None, None, 'げがどんどんと', None], ['上', 'あ', None, None], [None, None, 'がっています。', None]]
[[None, None, 'それ', None], [None, None, 'を', True], ['皮切', 'かわき', None, True], [None, None, 'りとして', True], [None, None, '、コンビニは', None], ['相次', 'あいつ', None, None], [None, None, 'いで', None], ['出店', 'しゅってん', None, None], [None, None, 'し', None], ['始', 'はじ', None, None], [None, None, 'めた。', None]]
[['俳優', 'はいゆう', None, None], [None, None, 'の', None], ['伝記', 'でんき', None, None], [None, None, '：「『', None], ['Ｙ', 'ワイ', None, None], [None, None, '-', None], ['ＭＥＮ', 'メン', None, None], [None, None, '』に', None], ['出演', 'しゅつえん', None, None], [None, None, 'した', None], [None, None, 'のを', True], ['皮切', 'かわき', None, True], [None, None, 'りにして', True], [None, None, '、', None], ['多数', 'たすう', None, None], ['出演', 'しゅつえん', None, None], [None, None, '。」', None]]
[['皆川', 'みながわ', None, None], [None, None, 'さんが', None], ['監督', 'かんとく', None, None], [None, None, 'として', None], ['選', 'えら', None, None], [None, None, 'ばれた', None], [None, None, 'のを', True], ['皮切', 'かわき', None, True], [None, None, 'りにして', True], [None, None, '、うちのチームは', None], ['次々', 'つぎつぎ', None, None], [None, None, 'とスポーツの', None], ['成功', 'せいこう', None, None], [None, None, 'を', None], ['掴', 'つか', None, None], [None, None, 'んだ。', None]]
[[None, None, '「レオナルド・ディカプリオはタイタニックの', None], ['主人公', 'しゅじんこう', None, None], [None, None, 'になった', None], [None, None, 'のを', True], ['皮切', 'かわき', None, True], [None, None, 'りにして', True], [None, None, 'スターへの', None], ['道', 'みち', None, None], [None, None, 'を', None], ['歩', 'あゆ', None, None], [None, None, 'み', None], ['始', 'はじ', None, None], [None, None, 'め、', None], ['大', 'だい', None, None], [None, None, 'ヒット', None], ['映画', 'えいが', None, None], [None, None, 'に', None], ['出演', 'しゅつえん', None, None], [None, None, 'している。」', None]]

 81%|████████▏ | 763/938 [07:57<01:42,  1.71it/s]

[['父親', 'ちちおや', None, None], [None, None, 'はパソコンならともかくスマートフォン', None], [None, None, 'に', True], ['至', 'いた', None, True], [None, None, 'っては', True], [None, None, 'まるでお', None], ['手上', 'てあ', None, None], [None, None, 'げらしい。', None]]
[['２０〇〇', 'にせんまるまる', None, None], ['年', 'ねん', None, None], [None, None, 'は', None], ['非常', 'ひじょう', None, None], [None, None, 'に', None], ['乾燥', 'かんそう', None, None], [None, None, 'していた。', None], ['４', 'し', None, None], ['月', 'がつ', None, None], [None, None, 'に', True], ['至', 'いた', None, True], [None, None, 'っては', True], ['２', 'に', None, None], ['回', 'かい', None, None], [None, None, 'しか', None], ['降', 'ふ', None, None], [None, None, 'らなかった。', None]]
[['最近', 'さいきん', None, None], [None, None, 'の', None], ['子供', 'こども', None, None], [None, None, 'は、かろうじて', None], ['ＣＤ', 'シーディー', None, None], [None, None, 'は', None], ['知', 'し', None, None], [None, None, 'っているが、フロッピー', None], [None, None, 'に', True], ['至', 'いた', None, True], [None, None, 'っては', True], ['全', 'まった', None, None], [None, None, 'く', None], ['知', 'し', None, None], [None, None, 'らない', None], ['場合', 'ばあい', None, None], [None, None, 'が', None], ['珍', 'めずら', None, None], [None, None, 'しくない。', None]]
[['一人', 'ひとり', None, None], ['暮', 'ぐ', None, None], [None, None, 'らしをしている', None], ['息子', 'むすこ', None, None], [None, None, 'の', None], ['生活', 'せいかつ', None, None], [None, None, 'は', None], ['荒', 'あ', None, None], [None, None, 'れているようです。', None], ['食', 'しょく', None, None], ['生活', 'せいかつ', None, None], [None, None, 'に', True], ['至', 'いた', None, True], [None, None, 'っては', True], [None, None, '、', None], ['毎日', 'まいにち', None, None], [None, None, 'カップラーメンを', None], ['食', 'た', None, None], [None, None, 'べていると', None], ['聞', 'き', None, None], [None, None, 'きました。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['家族', 'かぞく', None, None], [None, None, 'はみんな', None], ['方向', 'ほうこう', None, None], ['音痴', 'おんち', None, None], [None, None, 'です。', None], ['母', 'はは', None, None], [None, None, 'に', True], ['至', 'いた', None, True], [None, None, 'っては', True], [None, None, 'ナビゲーションアプリを', None], ['使', 'つか', None, None], [None, None, 'っても', None], ['道', 'みち', None, None], [None, None, 'に', None], ['迷', 'まよ', None, None], [None, None, 'ってしまいます。', None]]

 81%|████████▏ | 764/938 [07:58<01:36,  1.80it/s]

[['父', 'ちち', None, None], [None, None, 'が', None], ['出張', 'しゅっちょう', None, None], [None, None, 'から', None], ['帰', 'かえ', None, True], [None, None, 'るなり', True], ['母', 'はは', None, None], [None, None, 'は', None], ['泣', 'な', None, None], [None, None, 'きだした。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'はジョークを', None], ['聞', 'き', None, True], [None, None, 'くなり', True], ['笑', 'わら', None, None], [None, None, 'い', None], ['出', 'だ', None, None], [None, None, 'してしまった。', None]]
[[None, None, 'うちの', None], ['奥', 'おく', None, None], [None, None, 'さんは', None], ['毎日', 'まいにち', None, None], ['起', 'お', None, True], [None, None, 'きるなり', True], [None, None, 'スマホで', None], ['電子', 'でんし', None, None], [None, None, 'メールを', None], ['見', 'み', None, None], [None, None, 'ている。', None]]
[['踊', 'おど', None, None], [None, None, 'りを', None], ['止', 'や', None, True], [None, None, 'めるなり', True], [None, None, '、', None], ['彼女', 'かのじょ', None, None], [None, None, 'が', None], ['急', 'きゅう', None, None], [None, None, 'にキスしてくれたんだ。', None], ['気持', 'きも', None, None], [None, None, 'ちいい。', None]]
[['実家', 'じっか', None, None], [None, None, 'のお', None], ['母', 'かあ', None, None], [None, None, 'さんからの', None], ['電報', 'でんぽう', None, None], [None, None, 'が', None], ['来', 'く', None, True], [None, None, 'るなり', True], [None, None, '、', None], ['山田', 'やまだ', None, None], [None, None, 'さんは', None], ['青', 'あお', None, None], [None, None, 'ざめた。', None]]

 82%|████████▏ | 765/938 [07:58<01:33,  1.86it/s]

[[None, None, 'この', None], ['曲', 'きょく', None, None], [None, None, 'は', None], ['行', 'い', None, None], [None, None, 'きつけのバーでいつも', None], ['流', 'なが', None, None], [None, None, 'れているため、', None], ['覚', 'おぼ', None, None], [None, None, 'える', None], [None, None, 'ともなく', True], ['覚', 'おぼ', None, None], [None, None, 'えてしまった。', None]]
[['隣人', 'りんじん', None, None], [None, None, 'の', None], ['窓', 'まど', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'る', None], [None, None, 'とも', True], ['無', 'な', None, True], [None, None, 'く', True], ['見', 'み', None, None], [None, None, 'ると', None], [None, None, '、', None], ['驚', 'おどろ', None, None], [None, None, 'いたことに', None], ['裸', 'はだか', None, None], [None, None, 'の', None], ['人', 'ひと', None, None], [None, None, 'がいた。', None]]
[['勝者', 'しょうしゃ', None, None], [None, None, 'の', None], ['発表', 'はっぴょう', None, None], [None, None, 'を', None], ['聞', 'き', None, None], [None, None, 'く', None], [None, None, 'とも', True], ['無', 'な', None, True], [None, None, 'く', True], ['聞', 'き', None, None], [None, None, 'いていたら', None], [None, None, '、なんと', None], ['私', 'わたし', None, None], [None, None, 'の', None], ['名前', 'なまえ', None, None], [None, None, 'が', None], ['挙', 'あ', None, None], [None, None, 'がっていた。', None]]
[[None, None, 'ノベル', None], [None, None, '：「', None], ['彼', 'かれ', None, None], [None, None, 'は', None], ['夜遅', 'よるおそ', None, None], [None, None, 'くテレビを', None], ['見', 'み', None, None], [None, None, 'る', None], [None, None, 'とも', True], ['無', 'な', None, True], [None, None, 'く', True], ['見', 'み', None, None], [None, None, 'ている', None], [None, None, 'うちにいつのまにか', None], ['寝入', 'ねい', None, None], [None, None, 'ってしまったようだ。」', None]]
[['昨日', 'きのう', None, None], [None, None, '、', None], ['考', 'かんが', None, None], [None, None, 'える', None], [None, None, 'とも', True], ['無', 'な', None, True], [None, None, 'く', True], ['考', 'かんが', None, None], [None, None, 'えている', None], [None, None, 'ところに、スズメバチにひどく', None], ['刺', 'さ', None, None], [None, None, 'されて「', None], ['痛', 'いた', None, None], [None, None, 'っ！」', None], ['思', 'おも', None, None], [None, None, 'わず', None], ['叫', 'さけ', None, None], [None, None, 'んでしまった。', None]]

 82%|████████▏ | 766/938 [07:59<01:30,  1.90it/s]

[['床', 'ゆか', None, None], [None, None, 'は', None], ['泥', 'どろ', None, None], ['塗', 'まみ', None, True], [None, None, 'れ', True], [None, None, 'になった。', None]]
[['子供', 'こども', None, None], [None, None, 'は', None], ['泥', 'どろ', None, None], ['塗', 'まみ', None, True], [None, None, 'れの', True], [None, None, 'まま', None], ['遊', 'あそ', None, None], [None, None, 'んでいる。', None]]
[['頭', 'あたま', None, None], [None, None, 'から', None], ['汗', 'あせ', None, None], ['塗', 'まみ', None, True], [None, None, 'れになって', True], [None, None, '、', None], ['走', 'はし', None, None], [None, None, 'っている', None], ['選手', 'せんしゅ', None, None], [None, None, 'はすごいと', None], ['思', 'おも', None, None], [None, None, 'います。', None]]
[['仕事', 'しごと', None, None], [None, None, 'で', None], ['油', 'あぶら', None, None], ['塗', 'まみ', None, True], [None, None, 'れ', True], [None, None, 'になったら、', None], ['家', 'いえ', None, None], [None, None, 'に', None], ['帰', 'かえ', None, None], [None, None, 'ってからシャワーを', None], ['浴', 'あ', None, None], [None, None, 'びると', None], ['気持', 'きも', None, None], [None, None, 'ちがいいよね。', None]]
[['先生', 'せんせい', None, None], [None, None, 'の', None], ['田中', 'たなか', None, None], [None, None, 'さんは', None], ['氷', 'こおり', None, None], [None, None, 'で', None], ['滑', 'すべ', None, None], [None, None, 'って', None], ['雪', 'ゆき', None, None], [None, None, 'の', None], ['塊', 'かたまり', None, None], [None, None, 'で', None], ['転', 'ころ', None, None], [None, None, 'び、', None], ['雪', 'ゆき', None, None], ['塗', 'まみ', None, True], [None, None, 'れ', True], [None, None, 'になってしまった。', None]]

 82%|████████▏ | 767/938 [08:00<02:06,  1.35it/s]

[['何', 'なん', None, None], ['年', 'ねん', None, None], [None, None, 'が', None], [None, None, 'かかろうと', True], [None, None, '、ドラゴンボールを', None], ['見', 'み', None, None], [None, None, 'つけるつもりだ！', None]]
[['人', 'ひと', None, None], [None, None, 'が', None], ['何', 'なん', None, None], [None, None, 'と', None], ['言', 'い', None, True], [None, None, 'おうが', True], [None, None, '、ずっとあなたを', None], ['愛', 'あい', None, None], [None, None, 'しています！', None]]
[['商品', 'しょうひん', None, None], [None, None, 'は', None], ['上質', 'じょうしつ', None, None], [None, None, 'であろうが', True], ['悪質', 'あくしつ', None, None], [None, None, 'であろうが', True], [None, None, '、よく', None], ['売', 'う', None, None], [None, None, 'れるものはよく', None], ['売', 'う', None, None], [None, None, 'れる。', None]]
[['友達', 'ともだち', None, None], [None, None, 'が', None], ['生', 'い', None, None], [None, None, 'きてい', None], [None, None, 'ようが', None], ['生', 'い', None, True], [None, None, 'きていまいが', True], [None, None, '、', None], ['私', 'わたし', None, None], [None, None, 'は', None], ['彼', 'かれ', None, None], [None, None, 'らのために', None], ['歌', 'うた', None, None], [None, None, 'い', None], ['続', 'つづ', None, None], [None, None, 'ける。', None]]
[['生徒', 'せいと', None, None], [None, None, 'が', None], ['授業', 'じゅぎょう', None, None], [None, None, 'に', None], ['出席', 'しゅっせき', None, None], [None, None, 'し', None], [None, None, 'ようが', None], ['出席', 'しゅっせき', None, None], [None, None, 'するまいが', True], [None, None, '、', None], ['私', 'わたし', None, None], [None, None, 'はきちんと', None], ['授業', 'じゅぎょう', None, None], [None, None, 'を', None], ['進', 'すす', None, None], [None, None, 'めていく。', None]]

 82%|████████▏ | 768/938 [08:01<02:04,  1.37it/s]

[['僕', 'ぼく', None, None], [None, None, 'には', None], ['１００', 'ひゃく', None, None], ['万円', 'まんえん', None, None], [None, None, 'からの', True], ['腕時計', 'うでどけい', None, None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'う', None], ['余裕', 'よゆう', None, None], [None, None, 'はない。', None]]
[[None, None, 'スタジアムに', None], ['１０万', 'じゅうまん', None, None], ['人', 'にん', None, None], [None, None, 'からの', True], ['人', 'ひと', None, None], [None, None, 'が', None], ['集', 'あつ', None, None], [None, None, 'まったそうだ。', None]]
[[None, None, 'この', None], ['辺', 'あた', None, None], [None, None, 'りはとても', None], ['高', 'たか', None, None], [None, None, 'いよ。', None], ['家賃', 'やちん', None, None], [None, None, 'は', None], ['１０万', 'じゅうまん', None, None], ['円', 'えん', None, None], [None, None, 'からする', True], [None, None, '。', None]]
[[None, None, 'ビルさんは', None], ['彼女', 'かのじょ', None, None], [None, None, 'に', None], ['２００万', 'にひゃくまん', None, None], [None, None, 'ドル', None], [None, None, 'からする', True], ['車', 'くるま', None, None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'ってあげたらしいわ。', None]]
[[None, None, 'アーノルドさんはもう', None], ['７２', 'ななじゅうに', None, None], ['歳', 'さい', None, None], [None, None, 'なのに', None], ['１００', 'ひゃっ', None, None], [None, None, 'キロ', None], [None, None, 'からの', True], [None, None, 'ダンベルを', None], ['持', 'も', None, None], [None, None, 'ち', None], ['上', 'あ', None, None], [None, None, 'げられるよ。', None]]

 82%|████████▏ | 769/938 [08:01<02:00,  1.40it/s]

[['彼', 'かれ', None, None], [None, None, 'はバブルがはじけたことにより', None], ['一夜', 'いちや', None, None], [None, None, 'にして', True], ['破産者', 'はさんしゃ', None, None], [None, None, 'となった。', None]]
[['釈迦', 'しゃか', None, None], [None, None, 'は', None], ['２９', 'にじゅうきゅう', None, None], ['歳', 'さい', None, None], [None, None, 'にして', True], ['初', 'はじ', None, None], [None, None, 'めて、', None], ['宮殿', 'きゅうでん', None, None], [None, None, 'を', None], ['出', 'で', None, None], [None, None, 'た。', None]]
[[None, None, 'これは', None], ['西尾維新', 'にしおいしん', None, None], [None, None, 'のような', None], ['文豪', 'ぶんごう', None, None], [None, None, 'にして', True], ['初', 'はじ', None, None], [None, None, 'めて', None], ['書', 'か', None, None], [None, None, 'ける', None], ['名著', 'めいちょ', None, None], [None, None, 'だ。', None]]
[[None, None, 'ふうかはあきつき', None], ['氏', 'し', None, None], ['夫妻', 'ふさい', None, None], [None, None, 'の', None], ['結婚', 'けっこん', None, None], ['２０', 'にじゅう', None, None], ['年', 'ねん', None, None], ['目', 'め', None, None], [None, None, 'にして', True], ['初', 'はじ', None, None], [None, None, 'めて', None], ['授', 'さず', None, None], [None, None, 'かった', None], ['長女', 'ちょうじょ', None, None], [None, None, 'だった。', None]]
[['宝', 'たから', None, None], [None, None, 'くじに', None], ['当', 'あ', None, None], [None, None, 'たって', None], ['一夜', 'いちや', None, None], [None, None, 'にして', True], ['大金持', 'おおがねも', None, None], [None, None, 'ちになった', None], ['彼', 'かれ', None, None], [None, None, 'が、お', None], ['金', 'かね', None, None], [None, None, 'の', None], ['価値', 'かち', None, None], [None, None, 'を', None], ['理解', 'りかい', None, None], [None, None, 'する', None], ['事', 'こと', None, None], [None, None, 'は', None], ['無', 'な', None, None], [None, None, 'いでしょう。', None]]

 82%|████████▏ | 770/938 [08:02<01:58,  1.42it/s]

[[None, None, '「', None], ['嫌', 'きら', None, None], [None, None, 'いなものがあったなら、そう', None], ['言', 'い', None, None], [None, None, 'ってくれればいい', None], [None, None, 'ものを', True], [None, None, '...」', None]]
[['父', 'ちち', None, None], [None, None, 'は', None], ['息子', 'むすこ', None, None], [None, None, 'に', None], ['言', 'い', None, None], [None, None, 'う', None], [None, None, '：「', None], ['ＲＩＮＥ', 'ライン', None, None], [None, None, 'でメッセージをしてくれたら', None], ['迎', 'むか', None, None], [None, None, 'えに', None], ['行', 'い', None, None], [None, None, 'ってあげた', None], [None, None, 'もんを', True], [None, None, '...」', None]]
[['犯罪', 'はんざい', None, None], [None, None, 'コメディ', None], ['映画', 'えいが', None, None], [None, None, '、トニー', None], [None, None, '：「まったく、ボリス、おとなしく', None], ['死', 'し', None, None], [None, None, 'んでおればいい', None], [None, None, 'ものを', True], [None, None, '...」', None]]
[[None, None, '「もっと', None], ['早', 'はや', None, None], [None, None, 'くタバコをやめれば', None], ['健康問題', 'けんこうもんだい', None, None], [None, None, 'なしに', None], ['済', 'す', None, None], [None, None, 'んだ', None], [None, None, 'ものを', True], [None, None, '、', None], ['手遅', 'ておく', None, None], [None, None, 'れになってしまった。」', None]]
[[None, None, '「', None], ['彼', 'かれ', None, None], [None, None, 'が', None], ['君', 'きみ', None, None], [None, None, 'に', None], ['謝', 'あやま', None, None], [None, None, 'ったのなら', None], ['許', 'ゆる', None, None], [None, None, 'すべき', None], [None, None, 'ものを', True], [None, None, '、', None], ['子供', 'こども', None, None], [None, None, 'じゃあるまいし、', None], ['無視', 'むし', None, None], [None, None, 'するなんてひどすぎるよ。」', None]]

 82%|████████▏ | 771/938 [08:03<01:54,  1.45it/s]

[['誰', 'だれ', None, None], [None, None, 'であれ', True], ['全', 'すべ', None, None], [None, None, 'ての', None], ['人々', 'ひとびと', None, None], [None, None, 'は', None], ['同様', 'どうよう', None, None], [None, None, 'に', None], ['死', 'し', None, None], [None, None, 'ぬ。', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「どのような', None], ['状況', 'じょうきょう', None, None], [None, None, 'であれ', True], [None, None, '、', None], ['逃', 'に', None, None], [None, None, 'げることは', None], ['許', 'ゆる', None, None], [None, None, 'されない。」', None]]
[['何', 'なん', None, None], [None, None, 'であれ', True], [None, None, '、', None], ['両親', 'りょうしん', None, None], [None, None, 'にとっては', None], ['我', 'わ', None, None], [None, None, 'が', None], ['子', 'こ', None, None], [None, None, 'はいつも', None], ['愛', 'あい', None, None], [None, None, 'する', None], ['我', 'わ', None, None], [None, None, 'が', None], ['子', 'こ', None, None], [None, None, '。', None]]
[[None, None, 'たとえ', None], ['小', 'ちい', None, None], [None, None, 'さなもの', None], [None, None, 'であれ', True], ['検察官', 'けんさつかん', None, None], [None, None, 'は', None], ['賄賂', 'わいろ', None, None], [None, None, 'を', None], ['受', 'う', None, None], [None, None, 'け', None], ['取', 'と', None, None], [None, None, 'るわけにはいかない。', None]]
[[None, None, 'たとえ', None], ['氷', 'こおり', None, None], [None, None, 'のように', None], ['純粋', 'じゅんすい', None, None], [None, None, 'であれ', True], [None, None, '、', None], ['世界', 'せかい', None, None], [None, None, 'の', None], ['悪', 'あく', None, None], [None, None, 'からは', None], ['免', 'まぬが', None, None], [None, None, 'れられないだろう。', None]]

 82%|████████▏ | 772/938 [08:03<01:46,  1.56it/s]

[['長年', 'ながねん', None, None], ['付', 'つ', None, None], [None, None, 'き', None], ['合', 'あ', None, None], [None, None, 'ってきたパートナーに', None], ['別', 'わか', None, None], [None, None, 'れを', None], ['切', 'き', None, None], [None, None, 'り', None], ['出', 'だ', None, None], [None, None, 'すのなら', None], ['明日', 'あした', None, None], [None, None, 'をおいて', True], ['他', 'ほか', None, True], [None, None, 'には', True], [None, None, 'ない', None], [None, None, '。', None]]
[['我', 'わ', None, None], [None, None, 'が', None], ['子', 'こ', None, None], [None, None, 'の', None], ['世話', 'せわ', None, None], [None, None, 'を', None], ['安心', 'あんしん', None, None], [None, None, 'して', None], ['任', 'まか', None, None], [None, None, 'せられるのは、', None], ['実', 'じつ', None, None], [None, None, 'の', None], ['両親', 'りょうしん', None, None], [None, None, 'と', None], ['妻', 'つま', None, None], [None, None, 'をおいて', True], ['他', 'ほか', None, True], [None, None, 'には', True], [None, None, 'いません', None], [None, None, '。', None]]
[[None, None, 'もう', None], ['今年', 'ことし', None, None], [None, None, 'で', None], ['四十歳', 'よんじゅっさい', None, None], [None, None, 'になる', None], ['事', 'こと', None, None], [None, None, 'だし、', None], ['結婚', 'けっこん', None, None], [None, None, 'を', None], ['本気', 'ほんき', None, None], [None, None, 'で', None], ['考', 'かんが', None, None], [None, None, 'えているのなら', None], ['次', 'つぎ', None, None], [None, None, 'の', None], ['機会', 'きかい', None, None], [None, None, 'をおいて', True], ['他', 'ほか', None, True], [None, None, 'には', True], [None, None, 'ない', None], [None, None, 'だろう。', None]]
[['日本語', 'にほんご', None, None], [None, None, 'の', None], ['勉強', 'べんきょう', None, None], [None, None, 'を', None], ['始', 'はじ', None, None], [None, None, 'めたばかりの', None], ['初心者', 'しょしんしゃ', None, None], [None, None, 'の', None], ['方', 'かた', None, None], [None, None, 'におすすめするアプリを', None], ['一つ', 'ひとつ', None, None], [None, None, 'あげるとするなら、「', None], ['文', 'ぶん', None, None], [None, None, 'プロ」', None], [None, None, 'を', True], ['措', 'お', None, True], [None, None, 'いて', True], ['他', 'ほか', None, True], [None, None, 'に', True], [None, None, 'ありません', None], [None, None, '。', None]]
[['探偵', 'たんてい', None, None], [None, None, 'は', None], ['容疑者', 'ようぎしゃ', None, None], [None, None, 'に', None], ['言', 'い', None, None], [None, None, 'う', None], [None, None, '：「とぼけないでください。これほど', None], ['事件', 'じけん', None, None], [None, None, 'について', None], ['知', 'し', None, None], [None, None, 'っているのは', None], ['犯人', 'はんにん', None, None], ['自身', 'じしん', None, None], [None, None, 'を', True], ['措', 'お', None, True], [None, None, 'いて', True], ['他', 'ほか', None, True], [None, None, 'に', True], [None, None, 'いない', None], [None, None, 'でしょう。」', None]]

 82%|████████▏ | 773/938 [08:04<01:44,  1.58it/s]

[['以上', 'いじょう', None, None], [None, None, 'をもちまして', True], [None, None, '、', None], ['私', 'わたし', None, None], [None, None, 'のスピーチは', None], ['終', 'お', None, None], [None, None, 'わりとさせて', None], ['頂', 'いただ', None, None], [None, None, 'きます。', None]]
[['会議', 'かいぎ', None, None], [None, None, '、', None], ['問', 'と', None, None], [None, None, 'いかけに', None], ['答', 'こた', None, None], [None, None, 'えた', None], ['後', 'あと', None, None], [None, None, '：「', None], [None, None, 'これ', None], [None, None, 'をもちまして', True], ['質疑応答', 'しつぎおうとう', None, None], [None, None, 'を', None], ['終', 'お', None, None], [None, None, 'わります。ありがとうございます。」', None]]
[['辞令', 'じれい', None, None], [None, None, '：「', None], ['一条', 'いちじょう', None, None], ['蛍', 'ほたる', None, None], ['殿', 'どの', None, None], [None, None, '。', None], ['令和', 'れいわ', None, None], ['２', 'に', None, None], ['年', 'ねん', None, None], ['５', 'ご', None, None], ['月', 'がつ', None, None], ['１日', 'ついたち', None, None], [None, None, 'をもって', True], ['経理部', 'けいりぶ', None, None], ['第', 'だい', None, None], ['５', 'ご', None, None], ['課', 'か', None, None], ['勤務', 'きんむ', None, None], [None, None, 'を', None], ['命', 'めい', None, None], [None, None, 'ずる。」', None]]
[['誠', 'まこと', None, None], [None, None, 'に', None], ['勝手', 'かって', None, None], [None, None, 'ながら「', None], ['可愛', 'かわい', None, None], [None, None, 'い', None], ['店', 'みせ', None, None], [None, None, '」は', None], ['本日', 'ほんじつ', None, None], [None, None, 'をもちまして', True], ['閉店', 'へいてん', None, None], [None, None, 'いたします。', None], ['長', 'なが', None, None], [None, None, 'きに', None], ['渡', 'わた', None, None], [None, None, 'りご', None], ['愛顧', 'あいこ', None, None], [None, None, '、', None], ['誠', 'まこと', None, None], [None, None, 'にありがとうございました。', None]]
[['司会', 'しかい', None, None], [None, None, '：「', None], ['以上', 'いじょう', None, None], [None, None, 'をもちまして', True], [None, None, '、', None], ['２０２１', 'にせんにじゅういち', None, None], ['年度', 'ねんど', None, None], [None, None, 'の', None], ['運動会', 'うんどうかい', None, None], [None, None, 'を', None], ['閉会', 'へいかい', None, None], ['致', 'いた', None, None], [None, None, 'します。」', None]]

 83%|████████▎ | 774/938 [08:04<01:46,  1.54it/s]

[['馬', 'うま', None, None], [None, None, 'は', None], ['肉', 'にく', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べることができる。', None], [None, None, 'とは', True], ['言', 'い', None, True], [None, None, 'え', True], [None, None, '、', None], ['普通', 'ふつう', None, None], [None, None, 'は', None], ['食', 'た', None, None], [None, None, 'べない。', None]]
[['犯人', 'はんにん', None, None], [None, None, 'は', None], ['逮捕', 'たいほ', None, None], [None, None, 'された', None], [None, None, 'とは', True], ['言', 'い', None, True], [None, None, 'え', True], ['有罪', 'ゆうざい', None, None], [None, None, 'と', None], ['宣告', 'せんこく', None, None], [None, None, 'されるまで', None], ['時間', 'じかん', None, None], [None, None, 'がかかるだろう。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['社長', 'しゃちょう', None, None], [None, None, 'とは', True], ['言', 'い', None, True], [None, None, 'え', True], ['名前', 'なまえ', None, None], [None, None, 'ばかりだ。', None], ['権限', 'けんげん', None, None], [None, None, 'は', None], ['取締役会', 'とりしまりやくかい', None, None], [None, None, 'にある。', None]]
[['今', 'いま', None, None], [None, None, 'では、パンデミックの', None], ['進行状況', 'しんこうじょうきょう', None, None], [None, None, 'は', None], ['遅', 'おそ', None, None], [None, None, 'い', None], [None, None, 'とは', True], ['言', 'い', None, True], [None, None, 'え', True], [None, None, '、まだ', None], ['安心', 'あんしん', None, None], [None, None, 'するわけにはいかない。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'があなたにとって', None], ['実', 'じつ', None, None], [None, None, 'の', None], ['母親', 'ははおや', None, None], [None, None, 'である', None], [None, None, 'とは', True], ['言', 'い', None, True], [None, None, 'え', True], [None, None, '、', None], ['礼儀', 'れいぎ', None, None], [None, None, 'を', None], ['欠', 'か', None, None], [None, None, 'くべきではない。', None]]

 83%|████████▎ | 775/938 [08:05<01:44,  1.56it/s]

[[None, None, 'このクリーミーで', None], ['且', 'か', None, None], [None, None, 'つ', None], ['重', 'おも', None, None], [None, None, 'くない', None], ['絶品', 'ぜっぴん', None, None], [None, None, 'のカルボナーラは', None], ['地元', 'じもと', None, None], [None, None, 'の', None], ['名店', 'めいてん', None, None], [None, None, 'ならでは', True], [None, None, 'だ', None], [None, None, '。', None]]
[['食品', 'しょくひん', None, None], ['広告', 'こうこく', None, None], [None, None, '：「おばあさんの', None], ['手作', 'てづく', None, None], [None, None, 'り', None], [None, None, 'ならでは', True], [None, None, 'なかなか', None], ['出', 'だ', None, None], [None, None, 'せない', None], ['味', 'あじ', None, None], [None, None, 'だ。」', None]]
[['求人', 'きゅうじん', None, None], [None, None, 'のサイト、', None], ['求人', 'きゅうじん', None, None], ['情報', 'じょうほう', None, None], [None, None, '：「', None], ['小', 'ちい', None, None], [None, None, 'さいカフェ', None], [None, None, 'ならでは', True], [None, None, 'の', None], ['良', 'よ', None, None], [None, None, 'さが', None], ['溢', 'あふ', None, None], [None, None, 'れています。」', None]]
[['広告', 'こうこく', None, None], [None, None, 'ポスター', None], [None, None, '：「', None], ['沖縄', 'おきなわ', None, None], [None, None, 'ならでは', True], [None, None, 'の、', None], ['普段', 'ふだん', None, None], [None, None, 'は', None], ['見', 'み', None, None], [None, None, 'られない', None], ['透明度', 'とうめいど', None, None], [None, None, 'の', None], ['高', 'たか', None, None], [None, None, 'い', None], ['青', 'あお', None, None], [None, None, 'い', None], ['海', 'うみ', None, None], [None, None, 'は', None], ['必見', 'ひっけん', None, None], [None, None, 'だ。」', None]]
[['求人', 'きゅうじん', None, None], [None, None, 'のサイト、', None], ['店員', 'てんいん', None, None], [None, None, 'コメント', None], [None, None, '：「こうした', None], ['社風', 'しゃふう', None, None], [None, None, 'の', None], ['良', 'よ', None, None], [None, None, 'さは', None], ['当社', 'とうしゃ', None, None], [None, None, 'ならでは', True], [None, None, 'だ', None], [None, None, 'と', None], ['思', 'おも', None, None], [None, None, 'います。」', None]]

 83%|████████▎ | 776/938 [08:06<01:47,  1.51it/s]

[[None, None, 'マンガの', None], ['迷', 'まよ', None, None], [None, None, 'った', None], ['主人公', 'しゅじんこう', None, None], [None, None, '：「', None], ['何日', 'なんにち', None, None], [None, None, 'たったの', None], [None, None, 'か', None], [None, None, 'すら', True], [None, None, '...」', None]]
[['南極大陸', 'なんきょくたいりく', None, None], [None, None, 'では', None], ['夏', 'なつ', None, None], [None, None, 'で', None], [None, None, 'すら', True], ['気温', 'きおん', None, None], [None, None, 'が', None], ['０', 'れい', None, None], ['度', 'ど', None, None], ['以下', 'いか', None, None], [None, None, 'である。', None]]
[['記事', 'きじ', None, None], [None, None, '：「カラスは', None], ['道具', 'どうぐ', None, None], [None, None, 'を', None], ['使用', 'しよう', None, None], [None, None, 'する', None], ['能力', 'のうりょく', None, None], [None, None, 'を', None], ['示', 'しめ', None, None], [None, None, 'したこと', None], [None, None, 'すら', True], [None, None, 'あります。」', None]]
[[None, None, 'ノベル、', None], ['語', 'かた', None, None], [None, None, 'り', None], ['手', 'て', None, None], [None, None, '：「', None], ['負傷', 'ふしょう', None, None], [None, None, 'により、', None], ['走', 'はし', None, None], [None, None, 'るどころかベッドから', None], ['立', 'た', None, None], [None, None, 'ち', None], ['上', 'あ', None, None], [None, None, 'がること', None], [None, None, 'すら', True], [None, None, 'も', None], [None, None, 'できない。」', None]]
[[None, None, 'ノベル、', None], ['語', 'かた', None, None], [None, None, 'り', None], ['手', 'て', None, None], [None, None, '：「', None], ['友達', 'ともだち', None, None], [None, None, 'どころか', None], ['家族', 'かぞく', None, None], [None, None, 'に', None], [None, None, 'すら', True], ['説明', 'せつめい', None, None], [None, None, 'せずに', None], ['旅', 'たび', None, None], [None, None, 'に', None], ['出', 'で', None, None], [None, None, 'た。」', None]]

 83%|████████▎ | 777/938 [08:07<01:56,  1.38it/s]

[['彼', 'かれ', None, None], [None, None, 'が', None], ['大学', 'だいがく', None, None], [None, None, 'をやめるのは、', None], ['何', 'なに', None, None], [None, None, 'か', None], ['理由', 'りゆう', None, None], [None, None, 'が', None], [None, None, 'あっての', True], [None, None, 'こと', None], [None, None, 'だろう。', None]]
[[None, None, '「あなた', None], [None, None, 'あっての', True], [None, None, 'わたしです。あなたがいなければ', None], ['私', 'わたし', None, None], [None, None, 'の', None], ['人生', 'じんせい', None, None], [None, None, 'は', None], ['無意味', 'むいみ', None, None], [None, None, 'ですよ。」', None]]
[['支配人', 'しはいにん', None, None], [None, None, '、', None], ['社員', 'しゃいん', None, None], [None, None, 'に', None], [None, None, '：「ゲスト', None], [None, None, 'あっての', True], ['遊園地', 'ゆうえんち', None, None], [None, None, 'だということを', None], ['忘', 'わす', None, None], [None, None, 'れてはいけません。」', None]]
[['恋愛', 'れんあい', None, None], [None, None, 'は', None], ['相手', 'あいて', None, None], [None, None, 'あっての', True], [None, None, 'こと', None], [None, None, 'だから', None], ['一人', 'ひとり', None, None], [None, None, 'だけでは', None], ['無理', 'むり', None, None], [None, None, 'だ...と', None], ['思', 'おも', None, None], [None, None, 'っていませんか？', None]]
[['部員', 'ぶいん', None, None], [None, None, 'あっての', True], [None, None, 'クラブ', None], ['活動', 'かつどう', None, None], [None, None, 'なんだから、', None], ['部員', 'ぶいん', None, None], [None, None, 'に', None], ['対', 'たい', None, None], [None, None, 'してもっと', None], ['優', 'やさ', None, None], [None, None, 'しくするべきだ。', None]]

 83%|████████▎ | 778/938 [08:07<01:51,  1.44it/s]

[[None, None, 'なんで', None], ['怒', 'おこ', None, None], [None, None, 'っているの？', None], ['私', 'わたし', None, None], [None, None, 'の', None], ['意見', 'いけん', None, None], [None, None, 'を', None], ['言', 'い', None, True], [None, None, 'ったまでのことだ', True], [None, None, '。', None]]
[['Ａ', 'エー', None, None], [None, None, '：「', None], ['助', 'たす', None, None], [None, None, 'けてくれてありがとうございます！」', None], ['Ｂ', 'ビー', None, None], [None, None, '：「いや、', None], ['当然', 'とうぜん', None, None], [None, None, 'のことを', None], [None, None, 'したまでのことです', True], [None, None, '。」', None]]
[['Ａ', 'エー', None, None], [None, None, '：「わぁ、', None], ['日本語', 'にほんご', None, None], ['上手', 'じょうず', None, None], [None, None, 'だね！」', None], ['Ｂ', 'ビー', None, None], [None, None, '：「ただ', None], ['趣味', 'しゅみ', None, None], [None, None, 'で', None], ['勉強', 'べんきょう', None, None], [None, None, 'してたまでのこと', True], [None, None, 'で', None], [None, None, '、まだまだだけどね。」', None]]
[['僕', 'ぼく', None, None], [None, None, 'はただ', None], ['伝言', 'でんごん', None, None], [None, None, 'を', None], ['頼', 'たの', None, None], [None, None, 'まれたから', None], ['伝', 'つた', None, True], [None, None, 'えたまでで', True], [None, None, '、それは', None], ['僕', 'ぼく', None, None], [None, None, 'の', None], ['考', 'かんが', None, None], [None, None, 'えではないからね！', None]]
[['真実', 'しんじつ', None, None], [None, None, 'を', None], ['話', 'はな', None, True], [None, None, 'したまでのこと', True], [None, None, 'なのに、なぜかクラスメイトから', None], ['嘘', 'うそ', None, None], [None, None, 'つきと', None], ['言', 'い', None, None], [None, None, 'われてしまいました。', None]]

 83%|████████▎ | 779/938 [08:08<01:50,  1.44it/s]

[[None, None, 'ベルリンからローマ', None], [None, None, 'を', True], ['経', 'へ', None, True], [None, None, 'て', True], [None, None, 'ブエノスアイレスに', None], ['向', 'む', None, None], [None, None, 'かいます。', None]]
[['数', 'すう', None, None], ['世代', 'せだい', None, None], [None, None, 'を', True], ['経', 'へ', None, True], [None, None, 'ても', True], [None, None, 'なお', None], ['争議', 'そうぎ', None, None], [None, None, 'が', None], ['続', 'つづ', None, None], [None, None, 'いている。', None]]
[[None, None, 'ちとげとらくは、', None], ['約', 'やく', None, None], ['１０', 'じゅう', None, None], ['年', 'ねん', None, None], [None, None, 'の', None], ['交際', 'こうさい', None, None], [None, None, 'を', True], ['経', 'へ', None, True], [None, None, 'て', True], ['結婚', 'けっこん', None, None], [None, None, 'した。', None]]
[['略歴', 'りゃくれき', None, None], [None, None, '：「', None], ['早稲田大学', 'わせだだいがく', None, None], ['理学部', 'りがくぶ', None, None], ['卒業後', 'そつぎょうご', None, None], ['Ｇｏｏｇｌｅ', 'グーグル', None, None], ['勤務', 'きんむ', None, None], [None, None, 'を', True], ['経', 'へ', None, True], [None, None, 'て', True], ['２０', 'にせん', None, None], ['２', 'にー', None, None], ['〇', 'まる', None, None], ['年', 'ねん', None, None], ['独立', 'どくりつ', None, None], [None, None, '。」', None]]
[['新聞', 'しんぶん', None, None], [None, None, '：「', None], ['今後', 'こんご', None, None], ['必要', 'ひつよう', None, None], [None, None, 'な', None], ['手続', 'てつづ', None, None], [None, None, 'き', None], [None, None, 'を', True], ['経', 'へ', None, True], [None, None, 'て', True], [None, None, '、', None], ['鉱山', 'こうざん', None, None], ['買収', 'ばいしゅう', None, None], [None, None, 'は', None], ['完了', 'かんりょう', None, None], [None, None, 'します。」', None]]

 83%|████████▎ | 780/938 [08:09<01:47,  1.46it/s]

[['生', 'い', None, True], [None, None, 'きながら', True], ['焼', 'や', None, None], [None, None, 'かれるところだった。', None]]
[[None, None, 'いつもながら', True], [None, None, 'あなたたちと', None], ['話', 'はな', None, None], [None, None, 'すのは', None], ['楽', 'たの', None, None], [None, None, 'しいですよ。', None]]
[[None, None, 'コナンは', None], ['生', 'う', None, True], [None, None, 'まれながらの', True], [None, None, 'すぐれた', None], ['名探偵', 'めいたんてい', None, None], [None, None, 'だそうだ。', None]]
[[None, None, 'テレワークというのは', None], ['家', 'いえ', None, None], [None, None, 'に', None], ['居', 'い', None, True], [None, None, 'ながら', True], ['働', 'はたら', None, None], [None, None, 'くということだ。', None]]
[[None, None, 'コウタはカエデからの', None], ['手紙', 'てがみ', None, None], [None, None, 'を', None], ['手', 'て', None, None], [None, None, 'に', None], ['取', 'と', None, None], [None, None, 'りつつ、', None], ['涙', 'なみだ', None, True], [None, None, 'ながらに', True], ['喜', 'よろこ', None, None], [None, None, 'んだ。', None]]

 83%|████████▎ | 781/938 [08:09<01:38,  1.60it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], ['腰', 'こし', None, None], [None, None, 'かけた', None], [None, None, 'なり', True], [None, None, 'じっと', None], ['考', 'かんが', None, None], [None, None, 'えていた。', None]]
[['町', 'まち', None, None], [None, None, 'を', None], ['離', 'はな', None, None], [None, None, 'れた', None], [None, None, 'なり', True], ['消息', 'しょうそく', None, None], [None, None, 'は', None], ['途絶', 'とだ', None, None], [None, None, 'えた。', None]]
[['３年', 'さんねん', None, None], ['前', 'まえ', None, None], [None, None, 'に', None], ['涙', 'なみだ', None, None], [None, None, 'ながらに', None], ['家出', 'いえで', None, None], [None, None, 'した', None], [None, None, 'なり', True], [None, None, '、', None], ['帰', 'かえ', None, None], [None, None, 'ってこない。', None]]
[[None, None, 'レース', None], ['後', 'ご', None, None], [None, None, '、', None], ['草', 'くさ', None, None], [None, None, 'の', None], ['上', 'うえ', None, None], [None, None, 'に', None], ['横', 'よこ', None, None], [None, None, 'になった', None], [None, None, 'なり', True], [None, None, '、', None], ['泣', 'な', None, None], [None, None, 'き', None], ['続', 'つづ', None, None], [None, None, 'けた。', None]]
[['宿泊客', 'しゅくはくきゃく', None, None], [None, None, 'の', None], ['一人', 'ひとり', None, None], [None, None, 'がドアを', None], ['開', 'あ', None, None], [None, None, 'けた', None], [None, None, 'なり', True], [None, None, 'にしてあります。', None]]

 83%|████████▎ | 782/938 [08:10<01:39,  1.57it/s]

[[None, None, 'タイトル', None], [None, None, '：「シンプル', None], [None, None, 'の', True], ['極', 'きわ', None, True], [None, None, 'み', True], [None, None, '！', None], ['絶品', 'ぜっぴん', None, None], [None, None, '『ハンバーグ』の', None], ['作', 'つく', None, None], [None, None, 'り', None], ['方', 'かた', None, None], [None, None, '」', None]]
[['地震', 'じしん', None, None], [None, None, 'によってビルに', None], ['閉', 'と', None, None], [None, None, 'じ', None], ['込', 'こ', None, None], [None, None, 'められた', None], ['人々', 'ひとびと', None, None], [None, None, 'は', None], ['混乱', 'こんらん', None, None], [None, None, 'の', True], ['極', 'きわ', None, True], [None, None, 'み', True], [None, None, 'にあった。', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「ダイモス', None], ['王', 'おう', None, None], [None, None, 'はこの', None], ['報道', 'ほうどう', None, None], [None, None, 'を', None], ['聞', 'き', None, None], [None, None, 'いて、', None], ['驚', 'おどろ', None, None], [None, None, 'き', None], [None, None, 'の', True], ['極', 'きわ', None, True], [None, None, 'み', True], [None, None, 'に', None], ['達', 'たっ', None, None], [None, None, 'しました。」', None]]
[['目上', 'めうえ', None, None], [None, None, 'の', None], ['人', 'ひと', None, None], [None, None, 'にはじめて', None], ['出会', 'であ', None, None], [None, None, 'う', None], ['時', 'とき', None, None], [None, None, '：「お', None], ['目', 'め', None, None], [None, None, 'に', None], ['掛', 'か', None, None], [None, None, 'かることができ、', None], ['光栄', 'こうえい', None, None], [None, None, 'の', True], ['極', 'きわ', None, True], [None, None, 'み', True], [None, None, 'です。」', None]]
[['釈迦', 'しゃか', None, None], ['様', 'さま', None, None], [None, None, 'は', None], ['当初', 'とうしょ', None, None], ['贅沢', 'ぜいたく', None, None], [None, None, 'の', True], ['極', 'きわ', None, True], [None, None, 'み', True], [None, None, 'を', None], ['尽', 'つ', None, None], [None, None, 'くした', None], ['生活', 'せいかつ', None, None], [None, None, 'をしていた。', None]]

 83%|████████▎ | 783/938 [08:10<01:34,  1.64it/s]

[[None, None, 'ハリー', None], [None, None, 'にしてみれば', True], [None, None, '、', None], ['優', 'やさ', None, None], [None, None, 'しくしてもらうなど、', None], ['初', 'はじ', None, None], [None, None, 'めての', None], ['経験', 'けいけん', None, None], [None, None, 'だった。', None]]
[['傍', 'はた', None, None], [None, None, 'から', None], ['見', 'み', None, None], [None, None, 'ればただの', None], ['安', 'やす', None, None], [None, None, 'っぽいペンダントだろうが、ラク', None], [None, None, 'にしてみれば', True], ['貴重', 'きちょう', None, None], [None, None, 'な', None], ['思', 'おも', None, None], [None, None, 'い', None], ['出', 'で', None, None], [None, None, 'の', None], ['品', 'しな', None, None], [None, None, 'になっている。', None]]
[['大人', 'おとな', None, None], [None, None, 'には', None], ['非常', 'ひじょう', None, None], [None, None, 'に', None], ['簡単', 'かんたん', None, None], [None, None, 'だが、', None], ['小', 'ちい', None, None], [None, None, 'さな', None], ['子供', 'こども', None, None], [None, None, 'にしてみれば', True], [None, None, 'かなり', None], ['困難', 'こんなん', None, None], [None, None, 'なことかもしれない。', None]]
[['私', 'わたし', None, None], [None, None, 'たちにとっては', None], ['危険', 'きけん', None, None], [None, None, 'すぎるようにみえる', None], ['彼', 'かれ', None, None], [None, None, 'の', None], ['生活', 'せいかつ', None, None], [None, None, 'は、', None], ['彼自身', 'かれじしん', None, None], [None, None, 'にしてみれば', True], [None, None, 'ごく', None], ['普通', 'ふつう', None, None], [None, None, 'のことなのでしょう。', None]]
[['友達', 'ともだち', None, None], ['１', 'いち', None, None], [None, None, 'は', None], ['失敗', 'しっぱい', None, None], [None, None, 'した', None], ['友達', 'ともだち', None, None], ['２', 'に', None, None], [None, None, 'を', None], ['励', 'はげ', None, None], [None, None, 'ます、', None], ['友達', 'ともだち', None, None], ['１', 'いち', None, None], [None, None, '：「たいしたことじゃありませんよ。」', None], ['友達', 'ともだち', None, None], ['２', 'に', None, None], [None, None, '：「いや、わたし', None], [None, None, 'にしてみたら', True], [None, None, '、たいしたことなんだよ。」', None]]

 84%|████████▎ | 784/938 [08:11<01:39,  1.55it/s]

[[None, None, 'ヒナは「', None], ['臭', 'くさ', None, None], [None, None, 'い」', None], [None, None, 'だの', True], [None, None, '「まずい」', None], [None, None, 'だの', True], [None, None, 'と', None], ['文句', 'もんく', None, None], [None, None, 'ばかりを', None], ['言', 'い', None, None], [None, None, 'っている。', None]]
[[None, None, 'ラーメンやカレーが', None], ['嫌', 'きら', None, None], [None, None, 'いな人', None], [None, None, '：「ラーメン', None], [None, None, 'だの', True], [None, None, 'カレー', None], [None, None, 'だの', True], [None, None, 'が', None], ['好', 'す', None, None], [None, None, 'きなやつは', None], ['味', 'あじ', None, None], [None, None, 'のわからんやつだよ。」', None]]
[['妹', 'いもうと', None, None], [None, None, 'にいつもこれが', None], ['欲', 'ほ', None, None], [None, None, 'しい', None], [None, None, 'だの', True], [None, None, 'それが', None], ['欲', 'ほ', None, None], [None, None, 'しい', None], [None, None, 'だの', True], [None, None, 'とうるさくせがまれて', None], ['困', 'こま', None, None], [None, None, 'る。', None]]
[['彼', 'かれ', None, None], [None, None, 'はゲームに', None], ['負', 'ま', None, None], [None, None, 'けるといつも「', None], ['回線', 'かいせん', None, None], [None, None, 'が', None], ['悪', 'わる', None, None], [None, None, 'い」', None], [None, None, 'だの', True], [None, None, '「', None], ['敵', 'てき', None, None], [None, None, 'がチート」', None], [None, None, 'だの', True], [None, None, 'と', None], ['言', 'い', None, None], [None, None, 'い', None], ['訳', 'わけ', None, None], [None, None, 'ばかり', None], ['言', 'い', None, None], [None, None, 'う。', None]]
[['娘', 'むすめ', None, None], [None, None, 'はお', None], ['腹', 'なか', None, None], [None, None, 'が', None], ['痛', 'いた', None, None], [None, None, 'い', None], [None, None, 'だの', True], ['頭', 'あたま', None, None], [None, None, 'が', None], ['痛', 'いた', None, None], [None, None, 'い', None], [None, None, 'だの', True], [None, None, 'よく', None], ['仮病', 'けびょう', None, None], [None, None, 'を', None], ['使', 'つか', None, None], [None, None, 'うので、あまり', None], ['信用', 'しんよう', None, None], ['出来', 'でき', None, None], [None, None, 'ない。', None]]

 84%|████████▎ | 785/938 [08:12<01:34,  1.63it/s]

[['飽', 'あ', None, True], [None, None, 'くまでも', True], [None, None, '、', None], ['不正', 'ふせい', None, None], [None, None, 'に', None], ['立', 'た', None, None], [None, None, 'ち', None], ['向', 'む', None, None], [None, None, 'かおうとします。', None]]
[['飽', 'あ', None, True], [None, None, 'くまでも', True], [None, None, 'やると', None], ['言', 'い', None, None], [None, None, 'うなら、', None], ['私', 'わたし', None, None], [None, None, 'は', None], ['止', 'と', None, None], [None, None, 'めません。', None]]
[['困難', 'こんなん', None, None], [None, None, 'に', None], ['対', 'たい', None, None], [None, None, 'して', None], [None, None, 'あくまでも', True], ['抵抗', 'ていこう', None, None], [None, None, 'した。', None]]
[['被告', 'ひこく', None, None], [None, None, 'は', None], ['飽', 'あ', None, True], [None, None, 'くまでも', True], ['無罪', 'むざい', None, None], [None, None, 'を', None], ['主張', 'しゅちょう', None, None], [None, None, 'するつもりらしい。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['政治的圧力', 'せいじてきあつりょく', None, None], [None, None, 'にも', None], ['関', 'かか', None, None], [None, None, 'わらずその', None], ['新税', 'しんぜい', None, None], [None, None, 'に', None], ['飽', 'あ', None, True], [None, None, 'くまで', True], ['反対', 'はんたい', None, None], [None, None, 'した。', None]]

 84%|████████▍ | 786/938 [08:12<01:28,  1.72it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], ['研修医', 'けんしゅうい', None, None], [None, None, 'と', None], [None, None, 'なるべく', True], [None, None, '、', None], ['５', 'ご', None, None], ['年', 'ねん', None, None], ['以上', 'いじょう', None, None], ['医科大学', 'いかだいがく', None, None], [None, None, 'で', None], ['修練', 'しゅうれん', None, None], [None, None, 'しました。', None]]
[[None, None, 'コーポレートサイト', None], [None, None, '：「クライアントのニーズに', None], ['応', 'こた', None, True], [None, None, 'える', True], ['可', 'べ', None, True], [None, None, 'く', True], [None, None, '、', None], ['我', 'わ', None, None], [None, None, 'が', None], ['社', 'しゃ', None, None], [None, None, 'は', None], ['世界', 'せかい', None, None], [None, None, 'で', None], ['初', 'はじ', None, None], [None, None, 'めて、', None], ['ＡＩ', 'エーアイ', None, None], [None, None, 'カスタマーサポートを', None], ['生', 'う', None, None], [None, None, 'み', None], ['出', 'だ', None, None], [None, None, 'しました。」', None]]
[['大学', 'だいがく', None, None], [None, None, 'ウェブサイト', None], [None, None, '：「', None], ['ＩＺＵ', 'いず', None, None], ['科学技術大学', 'かがくぎじゅつだいがく', None, None], [None, None, 'では、', None], ['予定通', 'よていどお', None, None], [None, None, 'り', None], ['秋期', 'しゅうき', None, None], ['講座', 'こうざ', None, None], [None, None, 'を', None], ['開講', 'かいこう', None, None], [None, None, 'す', True], ['可', 'べ', None, True], [None, None, 'く', True], [None, None, '、', None], ['鋭意', 'えいい', None, None], ['準備', 'じゅんび', None, None], [None, None, 'を', None], ['進', 'すす', None, None], [None, None, 'めてまいりました。」', None]]
[['伝記', 'でんき', None, None], [None, None, '：「ホテル', None], ['業界', 'ぎょうかい', None, None], [None, None, 'での', None], ['有力者', 'ゆうりょくしゃ', None, None], [None, None, 'としての', None], ['地位', 'ちい', None, None], [None, None, 'を', None], ['固', 'かた', None, True], [None, None, 'める', True], ['可', 'べ', None, True], [None, None, 'く', True], [None, None, '、', None], ['海外', 'かいがい', None, None], [None, None, 'でもホテルを', None], ['購入', 'こうにゅう', None, None], [None, None, 'しようとしたが、', None], ['拒否', 'きょひ', None, None], [None, None, 'されてしまった。」', None]]
[['記事', 'きじ', None, None], [None, None, '：「', None], ['ＢｉｇＳｏｆｔ', 'ビッグソフト', None, None], [None, None, 'で', None], ['培', 'つちか', None, None], [None, None, 'った', None], ['経験', 'けいけん', None, None], [None, None, 'を', None], ['最大限', 'さいだいげん', None, None], [None, None, 'に', None], ['生', 'い', None, True], [None, None, 'かす', True], ['可', 'べ', None, True], [None, None, 'く', True], [None, None, '、 ', None], ['会社', 'かいしゃ', None, None], [None, None, 'を', None], ['立', 'た', None, None], [None, None, 'ち', None], ['上', 'あ', None, None], [None, None, 'げて', None], ['独立', 'どくりつ', None, None], [None, None, 'することに', None], ['決', 'き', None, None], [None, None, 'めました。」', None]]

 84%|████████▍ | 787/938 [08:13<01:24,  1.78it/s]

[['先生', 'せんせい', None, None], [None, None, 'からの', None], ['返信', 'へんしん', None, None], [None, None, 'のお', None], ['礼', 'れい', None, None], [None, None, 'を', None], ['言', 'い', None, None], [None, None, 'う', None], [None, None, '：「お', None], ['忙', 'いそが', None, None], [None, None, 'しい', None], [None, None, 'ところ', True], [None, None, '、ご', None], ['返信', 'へんしん', None, None], [None, None, 'ありがとうございます。」', None]]
[['目上', 'めうえ', None, None], [None, None, 'の', None], ['人', 'ひと', None, None], [None, None, 'に', None], ['尋', 'たず', None, None], [None, None, 'ねる', None], [None, None, '：「お', None], ['急', 'いそ', None, None], [None, None, 'ぎ', None], [None, None, 'のところ', True], ['恐縮', 'きょうしゅく', None, None], [None, None, 'ですが、このプロジェクトについてのご', None], ['意見', 'いけん', None, None], [None, None, 'をお', None], ['聞', 'き', None, None], [None, None, 'かせ', None], ['願', 'ねが', None, None], [None, None, 'えませんか。」', None]]
[[None, None, 'メール', None], [None, None, '：「ご', None], ['病気', 'びょうき', None, None], ['中', 'ちゅう', None, None], [None, None, 'のところ', True], ['恐', 'おそ', None, None], [None, None, 'れ', None], ['入', 'い', None, None], [None, None, 'りますが、', None], ['田中', 'たなか', None, None], ['先生', 'せんせい', None, None], [None, None, 'の', None], ['携帯', 'けいたい', None, None], [None, None, 'の', None], ['番号', 'ばんごう', None, None], [None, None, 'を', None], ['教', 'おし', None, None], [None, None, 'えていただけますでしょうか。」', None]]
[['駅', 'えき', None, None], [None, None, 'の', None], ['放送', 'ほうそう', None, None], [None, None, '：「この', None], ['電車', 'でんしゃ', None, None], [None, None, 'は、', None], ['三', 'さん', None, None], ['分', 'ぷん', None, None], ['遅', 'おく', None, None], [None, None, 'れて', None], ['到着', 'とうちゃく', None, None], [None, None, 'いたします。お', None], ['急', 'いそ', None, None], [None, None, 'ぎ', None], [None, None, 'のところ', True], [None, None, '、ご', None], ['迷惑', 'めいわく', None, None], [None, None, 'をおかけいたします。」', None]]
[['会議', 'かいぎ', None, None], [None, None, 'での', None], ['冒頭', 'ぼうとう', None, None], [None, None, 'の', None], ['挨拶', 'あいさつ', None, None], [None, None, '：「', None], ['皆様', 'みなさま', None, None], [None, None, '、', None], ['本日', 'ほんじつ', None, None], [None, None, 'はご', None], ['多忙', 'たぼう', None, None], [None, None, 'のところ', True], [None, None, 'お', None], ['越', 'こ', None, None], [None, None, 'しいただき、ありがとうございます。」', None]]

 84%|████████▍ | 788/938 [08:13<01:28,  1.69it/s]

[['１００', 'ひゃっ', None, None], ['匹', 'ぴき', None, None], [None, None, 'からいる', True], [None, None, 'ネズミをどうやって', None], ['退治', 'たいじ', None, None], [None, None, 'するのか！', None]]
[[None, None, '「', None], ['富士山', 'ふじさん', None, None], [None, None, 'はここから', None], ['２００', 'にひゃっ', None, None], [None, None, 'キロ', None], [None, None, 'からある', True], [None, None, 'のに、よく', None], ['見', 'み', None, None], [None, None, 'えます。」', None]]
[['名探偵', 'めいたんてい', None, None], [None, None, 'ゴナン', None], [None, None, '：「', None], ['犯人', 'はんにん', None, None], [None, None, 'は', None], ['少', 'すく', None, None], [None, None, 'なくとも', None], ['３人', 'さんにん', None, None], [None, None, 'からいます', True], [None, None, '。」', None]]
[[None, None, 'オーストラリアの', None], ['大火事', 'おおかじ', None, None], [None, None, 'で', None], ['１０億', 'じゅうおく', None, None], ['匹', 'ひき', None, None], [None, None, 'からいる', True], ['動物', 'どうぶつ', None, None], [None, None, 'が', None], ['焼死', 'しょうし', None, None], [None, None, 'した。', None]]
[['狼', 'おおかみ', None, None], [None, None, 'は、', None], ['人間', 'にんげん', None, None], [None, None, 'には', None], ['聞', 'き', None, None], [None, None, 'こえない', None], ['音', 'おと', None, None], [None, None, 'が', None], ['聞', 'き', None, None], [None, None, 'こえる。また、', None], ['体重', 'たいじゅう', None, None], [None, None, 'が', None], ['８０', 'はちじゅっ', None, None], [None, None, 'キロ', None], [None, None, 'からある', True], ['個体', 'こたい', None, None], [None, None, 'もある。', None]]

 84%|████████▍ | 789/938 [08:14<01:22,  1.81it/s]

[['紺碧', 'こんぺき', None, None], [None, None, 'にして', True], ['美', 'うつく', None, None], [None, None, 'しい', None], ['海', 'うみ', None, None], [None, None, 'である。', None]]
[[None, None, 'シンプル', None], [None, None, 'にして', True], [None, None, 'かつパワフルなアプリである。', None]]
[['牛', 'うし', None, None], [None, None, 'は', None], ['優美', 'ゆうび', None, None], [None, None, '、', None], ['温和', 'おんわ', None, None], [None, None, 'にして', True], ['頭', 'あたま', None, None], [None, None, 'が', None], ['冴', 'さ', None, None], [None, None, 'えている。', None]]
[['山田', 'やまだ', None, None], ['先生', 'せんせい', None, None], [None, None, 'は', None], ['有名', 'ゆうめい', None, None], [None, None, 'な', None], ['教授', 'きょうじゅ', None, None], [None, None, 'にして', True], ['尊敬', 'そんけい', None, None], [None, None, 'されている', None], ['弁護士', 'べんごし', None, None], [None, None, 'でもある。', None]]
[['田中', 'たなか', None, None], ['総理大臣', 'そうりだいじん', None, None], [None, None, 'は', None], ['稀代', 'きたい', None, None], [None, None, 'の', None], ['政治家', 'せいじか', None, None], [None, None, 'にして', True], ['同時', 'どうじ', None, None], [None, None, 'に', None], ['偉大', 'いだい', None, None], [None, None, 'な', None], ['父', 'ちち', None, None], [None, None, 'でもある。', None]]

 84%|████████▍ | 790/938 [08:14<01:19,  1.87it/s]

[[None, None, 'アリとアリマキは', None], ['持', 'も', None, None], [None, None, 'ち', None], [None, None, 'つ', True], ['持', 'も', None, None], [None, None, 'たれ', None], [None, None, 'つ', True], [None, None, 'の', None], ['関係', 'かんけい', None, None], [None, None, 'にある。', None]]
[['押', 'お', None, None], [None, None, 'し', None], [None, None, 'つ', True], ['押', 'お', None, None], [None, None, 'され', None], [None, None, 'つ', True], [None, None, 'してなんとかそこに', None], ['着', 'つ', None, None], [None, None, 'くことができた。', None]]
[['彼', 'かれ', None, None], [None, None, 'はドアの', None], ['前', 'まえ', None, None], [None, None, 'をしばらく', None], ['不安', 'ふあん', None, None], [None, None, 'げに', None], ['行', 'い', None, None], [None, None, 'き', None], [None, None, 'つ', True], ['戻', 'もど', None, None], [None, None, 'り', None], [None, None, 'つ', True], [None, None, 'していたすえに', None], ['入', 'はい', None, None], [None, None, 'ることにした。', None]]
[['老人', 'ろうじん', None, None], [None, None, 'は', None], ['小枝', 'こえだ', None, None], [None, None, 'の', None], ['浮', 'う', None, None], [None, None, 'き', None], [None, None, 'つ', True], ['沈', 'しず', None, None], [None, None, 'み', None], [None, None, 'つ', True], [None, None, 'を', None], ['眺', 'なが', None, None], [None, None, 'めながら、', None], ['海', 'うみ', None, None], [None, None, 'の', None], ['匂', 'にお', None, None], [None, None, 'いを', None], ['楽', 'たの', None, None], [None, None, 'しんだ。', None]]
[['藤原', 'ふじわら', None, None], ['拓海', 'たくみ', None, None], [None, None, '、', None], ['須藤', 'すどう', None, None], ['京一', 'きょういち', None, None], [None, None, 'など、', None], ['多', 'おお', None, None], [None, None, 'くの', None], ['有名', 'ゆうめい', None, None], [None, None, 'なドライバーが', None], ['抜', 'ぬ', None, None], [None, None, 'き', None], [None, None, 'つ', True], ['抜', 'ぬ', None, None], [None, None, 'かれ', None], [None, None, 'つ', True], [None, None, 'のレースを', None], ['繰', 'く', None, None], [None, None, 'り', None], ['広', 'ひろ', None, None], [None, None, 'げた。', None]]

 84%|████████▍ | 791/938 [08:15<01:23,  1.76it/s]

[['飽', 'あ', None, True], [None, None, 'くまでも', True], [None, None, 'ここだけの', None], ['話', 'はなし', None, None], [None, None, 'ですが、', None], ['課長', 'かちょう', None, None], [None, None, 'は', None], ['部下', 'ぶか', None, None], [None, None, 'と', None], ['付', 'つ', None, None], [None, None, 'き', None], ['合', 'あ', None, None], [None, None, 'っているそうですよ。', None]]
[[None, None, '「', None], ['私', 'わたし', None, None], [None, None, 'は', None], ['飽', 'あ', None, True], [None, None, 'くまでも', True], ['素人', 'しろうと', None, None], [None, None, 'に', None], ['過', 'す', None, None], [None, None, 'ぎませんが、', None], ['計算', 'けいさん', None, None], [None, None, 'に', None], ['誤', 'あやま', None, None], [None, None, 'りがあると', None], ['思', 'おも', None, None], [None, None, 'います。」', None]]
[['今回', 'こんかい', None, None], [None, None, 'の', None], ['件', 'けん', None, None], [None, None, 'の', None], ['決定権', 'けっていけん', None, None], [None, None, 'は', None], ['飽', 'あ', None, True], [None, None, 'くまでも', True], [None, None, 'あなたにあるので、', None], ['自分', 'じぶん', None, None], [None, None, 'でよく', None], ['考', 'かんが', None, None], [None, None, 'えて', None], ['下', 'くだ', None, None], [None, None, 'さいね。', None]]
[['調査', 'ちょうさ', None, None], ['結果', 'けっか', None, None], [None, None, 'とは', None], ['飽', 'あ', None, True], [None, None, 'くまでも', True], ['一', 'ひと', None, None], [None, None, 'つのデータに', None], ['過', 'す', None, None], [None, None, 'ぎないので、そればかり', None], ['気', 'き', None, None], [None, None, 'にするのも', None], ['良', 'よ', None, None], [None, None, 'くありません。', None]]
[['先', 'さき', None, None], [None, None, 'ほどの', None], ['件', 'けん', None, None], [None, None, 'は', None], ['飽', 'あ', None, True], [None, None, 'くまでも', True], ['私', 'わたし', None, None], [None, None, 'と', None], ['君', 'きみ', None, None], [None, None, 'の', None], ['二人', 'ふたり', None, None], [None, None, 'だけの', None], ['秘密', 'ひみつ', None, None], [None, None, 'という', None], ['事', 'こと', None, None], [None, None, 'でよろしくお', None], ['願', 'ねが', None, None], [None, None, 'いしますね。', None]]

 84%|████████▍ | 792/938 [08:16<01:28,  1.64it/s]

[['近代美術', 'きんだいびじゅつ', None, None], [None, None, 'であれ', True], ['伝統芸能', 'でんとうげいのう', None, None], [None, None, 'であれ', True], [None, None, '、', None], ['芸術', 'げいじゅつ', None, None], [None, None, 'は', None], ['芸術', 'げいじゅつ', None, None], [None, None, 'だ。', None]]
[['遺伝情報', 'いでんじょうほう', None, None], [None, None, 'とは、', None], ['人間', 'にんげん', None, None], [None, None, 'であれ', True], [None, None, 'バナナ', None], [None, None, 'であれ', True], [None, None, '、すべて', None], ['同', 'おな', None, None], [None, None, 'じように', None], ['ＤＮＡ', 'ディーエヌエー', None, None], [None, None, 'に', None], ['組', 'く', None, None], [None, None, 'み', None], ['込', 'こ', None, None], [None, None, 'まれているものだ。', None]]
[['人', 'ひと', None, None], [None, None, 'は', None], ['無病息災', 'むびょうそくさい', None, None], [None, None, 'であれ', True], [None, None, '、', None], ['病気', 'びょうき', None, None], [None, None, 'であれ', True], [None, None, '、', None], ['常', 'つね', None, None], [None, None, 'に', None], ['健康', 'けんこう', None, None], [None, None, 'に', None], ['注意', 'ちゅうい', None, None], [None, None, 'が', None], ['必要', 'ひつよう', None, None], [None, None, 'です。', None]]
[['本', 'ほん', None, None], [None, None, 'ウェブサイト、', None], ['故意', 'こい', None, None], [None, None, 'に、オンライン', None], [None, None, 'であれ', True], [None, None, 'オフライン', None], [None, None, 'であれ', True], [None, None, '、ユーザからの', None], ['個人情報', 'こじんじょうほう', None, None], [None, None, 'を', None], ['収集', 'しゅうしゅう', None, None], [None, None, 'しません。', None]]
[['勉強', 'べんきょう', None, None], [None, None, 'であれ', True], [None, None, 'スポーツ', None], [None, None, 'であれ', True], ['何', 'なん', None, None], [None, None, 'であれ', True], [None, None, '、', None], ['結果', 'けっか', None, None], [None, None, 'は', None], ['注', 'そそ', None, None], [None, None, 'いできた', None], ['努力', 'どりょく', None, None], ['次第', 'しだい', None, None], [None, None, 'である。', None]]

 85%|████████▍ | 793/938 [08:16<01:30,  1.60it/s]

[['私', 'わたし', None, None], [None, None, 'の', None], ['彼氏', 'かれし', None, None], [None, None, 'はゲームをいったんやり', None], ['始', 'はじ', None, None], [None, None, 'め', None], [None, None, 'たら', None], ['最後', 'さいご', None, True], [None, None, '、どうしても', None], ['深夜', 'しんや', None, None], [None, None, 'までやめられない。', None]]
[['小説', 'しょうせつ', None, None], [None, None, 'のカスタマーレビュー', None], [None, None, '：「', None], ['綺麗', 'きれい', None, None], [None, None, 'な', None], ['話', 'はなし', None, None], [None, None, 'です。', None], ['読', 'よ', None, None], [None, None, 'みはじめ', None], [None, None, 'たら', None], ['最後', 'さいご', None, True], [None, None, '、', None], ['涙', 'なみだ', None, None], [None, None, 'がとまりません。」', None]]
[['口', 'くち', None, None], [None, None, 'を', None], ['開', 'ひら', None, None], [None, None, 'い', None], [None, None, 'たら', None], ['最後', 'さいご', None, True], [None, None, '、', None], ['自分', 'じぶん', None, None], [None, None, 'の', None], ['意志', 'いし', None, None], [None, None, 'では', None], ['止', 'と', None, None], [None, None, 'められなくて', None], ['何時間', 'なんじかん', None, None], [None, None, 'も', None], ['喋', 'しゃべ', None, None], [None, None, 'り', None], ['続', 'つづ', None, None], [None, None, 'けてしまう。', None]]
[['友達', 'ともだち', None, None], [None, None, 'との', None], ['話', 'はなし', None, None], [None, None, '：「うちの', None], ['犬', 'いぬ', None, None], [None, None, 'ったらいったん', None], ['食', 'た', None, None], [None, None, 'べ', None], ['物', 'もの', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'つけ', None], [None, None, 'たら', None], ['最後', 'さいご', None, True], [None, None, '、いっぺんに', None], ['食', 'た', None, None], [None, None, 'べてしまう。」', None]]
[[None, None, 'その', None], ['民族', 'みんぞく', None, None], [None, None, 'が', None], ['住', 'す', None, None], [None, None, 'む', None], ['島', 'しま', None, None], [None, None, 'には', None], ['行', 'い', None, None], [None, None, 'っ', None], [None, None, 'たら', None], ['最後', 'さいご', None, True], [None, None, '、', None], ['生', 'い', None, None], [None, None, 'きて', None], ['帰', 'かえ', None, None], [None, None, 'れる', None], ['可能性', 'かのうせい', None, None], [None, None, 'は', None], ['無', 'な', None, None], [None, None, 'いだろう。', None]]

 85%|████████▍ | 794/938 [08:17<01:24,  1.71it/s]

[['論文', 'ろんぶん', None, None], [None, None, '：「', None], ['亀', 'かめ', None, None], [None, None, 'とは', None], ['如何', 'いか', None, True], [None, None, 'なる', True], ['魚', 'さかな', None, None], [None, None, 'なのか？」', None]]
[['Ｋａｐｐａｚｏｎ', 'カッパゾン', None, None], [None, None, 'グループは', None], ['如何', 'いか', None, True], [None, None, 'なる', True], ['理由', 'りゆう', None, None], [None, None, 'であろうとも、', None], ['Ｋａｐｐａｚｏｎ', 'カッパゾン', None, None], [None, None, 'ネットショップから', None], ['如何', 'いか', None, True], [None, None, 'なる', True], ['製品', 'せいひん', None, None], [None, None, 'も', None], ['削除', 'さくじょ', None, None], [None, None, 'する', None], ['権利', 'けんり', None, None], [None, None, 'を', None], ['保有', 'ほゆう', None, None], [None, None, 'しています。', None]]
[[None, None, 'シヌラ', None], ['電気動力株式会社', 'でんきどうりょくかぶしきがいしゃ', None, None], [None, None, 'は', None], ['如何', 'いか', None, True], [None, None, 'なる', True], ['第三者', 'だいさんしゃ', None, None], [None, None, 'にも', None], ['顧客', 'こきゃく', None, None], ['情報', 'じょうほう', None, None], [None, None, 'を', None], ['販売', 'はんばい', None, None], [None, None, '、', None], ['配布', 'はいふ', None, None], [None, None, 'いたしません。', None]]
[['如何', 'いか', None, True], [None, None, 'なる', True], ['方', 'かた', None, None], [None, None, 'ともログイン', None], ['情報', 'じょうほう', None, None], [None, None, 'またはパスワードの', None], ['共有', 'きょうゆう', None, None], [None, None, 'はお', None], ['控', 'ひか', None, None], [None, None, 'え', None], ['願', 'ねが', None, None], [None, None, 'います。', None]]
[[None, None, 'パイロットは', None], ['如何', 'いか', None, True], [None, None, 'なる', True], ['事態', 'じたい', None, None], [None, None, 'になろうとも、', None], ['適切', 'てきせつ', None, None], [None, None, 'に', None], ['対処', 'たいしょ', None, None], [None, None, 'せねばならない。', None]]

 85%|████████▍ | 795/938 [08:17<01:25,  1.68it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], ['下手', 'へた', None, None], [None, None, 'なりに', True], ['頑張', 'がんば', None, None], [None, None, 'ってラブレターを', None], ['書', 'か', None, None], [None, None, 'いた。', None]]
[[None, None, 'こまりちゃんは', None], ['小', 'ちい', None, None], [None, None, 'さい', None], [None, None, 'なりに', True], ['両親', 'りょうしん', None, None], [None, None, 'の', None], ['農家', 'のうか', None, None], [None, None, 'を', None], ['手伝', 'てつだ', None, None], [None, None, 'っていた。', None]]
[['会計士', 'かいけいし', None, None], [None, None, 'は', None], ['会計士', 'かいけいし', None, None], [None, None, 'なりに', True], ['頑張', 'がんば', None, None], [None, None, 'って', None], ['全', 'すべ', None, None], [None, None, 'ての', None], ['手段', 'しゅだん', None, None], [None, None, 'を', None], ['尽', 'つ', None, None], [None, None, 'くしましたが、', None], ['解決策', 'かいけつさく', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'つけられませんでした。', None]]
[[None, None, '「その', None], ['問', 'と', None, None], [None, None, 'い', None], ['合', 'あ', None, None], [None, None, 'わせに', None], ['対', 'たい', None, None], [None, None, 'する', None], ['私', 'わたし', None, None], [None, None, 'なりの', True], ['回答', 'かいとう', None, None], [None, None, 'をご', None], ['紹介', 'しょうかい', None, None], [None, None, 'いたします。」', None]]
[['僕', 'ぼく', None, None], [None, None, 'なりに', True], [None, None, 'ベストを', None], ['尽', 'つ', None, None], [None, None, 'くしましたが、', None], ['搬送', 'はんそう', None, None], [None, None, 'されてきた', None], ['患者', 'かんじゃ', None, None], [None, None, 'を', None], ['救', 'すく', None, None], [None, None, 'うことが', None], ['出来', 'でき', None, None], [None, None, 'ませんでした。', None]]

 85%|████████▍ | 796/938 [08:18<01:20,  1.75it/s]

[['聞', 'き', None, True], [None, None, 'かれるままに', True], [None, None, '、', None], ['彼女', 'かのじょ', None, None], [None, None, 'の', None], ['住', 'す', None, None], [None, None, 'んでいる', None], ['場所', 'ばしょ', None, None], [None, None, 'を', None], ['教', 'おし', None, None], [None, None, 'えた。', None]]
[['強盗', 'ごうとう', None, None], [None, None, 'に', None], ['要求', 'ようきゅう', None, None], [None, None, 'されるまま', True], [None, None, '、', None], ['金', 'かね', None, None], [None, None, 'をわたした。', None]]
[[None, None, 'ガイドに', None], ['案内', 'あんない', None, None], [None, None, 'されるまま', True], [None, None, '、', None], ['私', 'わたし', None, None], [None, None, 'たちはパリ', None], ['市内', 'しない', None, None], [None, None, 'を', None], ['観光', 'かんこう', None, None], [None, None, 'した。', None]]
[['先生', 'せんせい', None, None], [None, None, 'に', None], ['教', 'おし', None, True], [None, None, 'えられるままに', True], [None, None, '、', None], ['生徒', 'せいと', None, None], [None, None, 'はその', None], ['発音', 'はつおん', None, None], [None, None, 'を', None], ['繰', 'く', None, None], [None, None, 'り', None], ['返', 'かえ', None, None], [None, None, 'した。', None]]
[['夫', 'おっと', None, None], [None, None, 'は', None], ['娘', 'むすめ', None, None], [None, None, 'に', None], [None, None, 'せがまれる', None], [None, None, 'ままに', True], ['何', 'なん', None, None], [None, None, 'でも', None], ['買', 'か', None, None], [None, None, 'い', None], ['与', 'あた', None, None], [None, None, 'えてしまう。', None]]

 85%|████████▍ | 797/938 [08:18<01:23,  1.69it/s]

[[None, None, 'この', None], ['神社', 'じんじゃ', None, None], [None, None, 'に', True], ['纏', 'まつ', None, True], [None, None, 'わる', True], ['伝説', 'でんせつ', None, None], [None, None, 'や', None], ['神話', 'しんわ', None, None], [None, None, 'は', None], ['数', 'かぞ', None, None], [None, None, 'えきれない。', None]]
[[None, None, 'この', None], ['物語', 'ものがたり', None, None], [None, None, 'は「とある', None], ['魔術', 'まじゅつ', None, None], [None, None, 'の', None], ['禁書', 'きんしょ', None, None], ['目録', 'もくろく', None, None], [None, None, '」', None], [None, None, 'に', True], ['纏', 'まつ', None, True], [None, None, 'わる', True], [None, None, 'ものである。', None]]
[[None, None, 'ブログ', None], ['記事', 'きじ', None, None], [None, None, '：「', None], ['猫', 'ねこ', None, None], [None, None, 'に', True], ['纏', 'まつ', None, True], [None, None, 'わる', True], ['英語', 'えいご', None, None], [None, None, 'の', None], ['慣用表現', 'かんようひょうげん', None, None], ['６選', 'ろくせん', None, None], [None, None, '。」', None]]
[['楊', 'よう', None, None], ['貴妃', 'きひ', None, None], [None, None, 'には', None], ['美貌', 'びぼう', None, None], [None, None, 'に', True], ['纏', 'まつ', None, True], [None, None, 'わる', True], ['漢詩', 'かんし', None, None], [None, None, 'が', None], ['数多', 'かずおお', None, None], [None, None, 'く', None], ['残', 'のこ', None, None], [None, None, 'されている。', None]]
[[None, None, 'アクア', None], ['女神', 'めがみ', None, None], [None, None, 'に', True], ['纏', 'まつ', None, True], [None, None, 'わる', True], ['神話', 'しんわ', None, None], [None, None, 'はこの', None], ['町', 'まち', None, None], [None, None, 'に', None], ['代々', 'だいだい', None, None], ['伝', 'つた', None, None], [None, None, 'えられている。', None]]

 85%|████████▌ | 798/938 [08:19<01:26,  1.62it/s]

[[None, None, 'なんと', None], ['言', 'い', None, None], [None, None, 'っても', None], ['教師', 'きょうし', None, None], [None, None, 'たる', True], ['者', 'もの', None, None], [None, None, 'は、', None], ['情熱', 'じょうねつ', None, None], [None, None, 'が', None], ['必要', 'ひつよう', None, None], [None, None, 'なのである。', None]]
[['学生', 'がくせい', None, None], [None, None, 'たる', True], ['者', 'もの', None, None], [None, None, 'は、アルバイトに', None], ['感', 'かま', None, None], [None, None, 'けすぎて', None], ['学業', 'がくぎょう', None, None], [None, None, 'を', None], ['疎', 'おろそ', None, None], [None, None, 'かにしてはならない。', None]]
[[None, None, '「', None], ['需要', 'じゅよう', None, None], [None, None, 'と', None], ['供給', 'きょうきゅう', None, None], [None, None, 'の', None], ['関係', 'かんけい', None, None], [None, None, 'を', None], ['理解', 'りかい', None, None], [None, None, 'できない', None], ['彼', 'かれ', None, None], [None, None, 'には', None], ['総理大臣', 'そうりだいじん', None, None], [None, None, 'たる', True], ['資格', 'しかく', None, None], [None, None, 'がない', None], [None, None, '。」', None]]
[['職人', 'しょくにん', None, None], [None, None, 'たる', True], [None, None, 'もの', None], [None, None, '、 ', None], ['最新', 'さいしん', None, None], [None, None, 'の', None], ['専門分野', 'せんもんぶんや', None, None], [None, None, 'の', None], ['発達', 'はったつ', None, None], [None, None, 'についていかなければならない。', None]]
[['教師', 'きょうし', None, None], [None, None, 'たる', True], ['者', 'もの', None, None], [None, None, '、', None], ['生徒', 'せいと', None, None], ['一人一人', 'ひとりひとり', None, None], [None, None, 'に', None], ['真摯', 'しんし', None, None], [None, None, 'に', None], ['向', 'む', None, None], [None, None, 'き', None], ['合', 'あ', None, None], [None, None, 'うべきである。', None]]

 85%|████████▌ | 799/938 [08:20<01:22,  1.68it/s]

[['上司', 'じょうし', None, None], [None, None, '：「', None], ['塗', 'ぬ', None, None], [None, None, 'る', None], [None, None, 'なら', None], ['塗', 'ぬ', None, True], [None, None, 'るで', True], [None, None, 'もっと', None], ['丁寧', 'ていねい', None, None], [None, None, 'に', None], ['仕上', 'しあ', None, None], [None, None, 'げなさい。」', None]]
[[None, None, 'イライラした', None], ['妻', 'つま', None, None], [None, None, '、ダラダラ', None], ['食', 'た', None, None], [None, None, 'べる', None], ['夫', 'おっと', None, None], [None, None, 'に', None], [None, None, '：「', None], ['食', 'た', None, None], [None, None, 'べる', None], [None, None, 'なら', None], ['食', 'た', None, True], [None, None, 'べるで', True], [None, None, '、きちんと', None], ['食', 'た', None, None], [None, None, 'べなさい。」', None]]
[['娘', 'むすめ', None, None], [None, None, '：「もう', None], ['空港', 'くうこう', None, None], [None, None, 'で', None], ['１時間', 'いちじかん', None, None], [None, None, 'も', None], ['待', 'ま', None, None], [None, None, 'ってるよ。」', None], ['母', 'はは', None, None], [None, None, '：「もう', None], ['待', 'ま', None, None], [None, None, 'っている', None], [None, None, 'なら', None], ['待', 'ま', None, True], [None, None, 'っているで', True], [None, None, 'もっと', None], ['早', 'はや', None, None], [None, None, 'くケータイを', None], ['鳴', 'な', None, None], [None, None, 'らしてくれたらよかったのに・・・」', None]]
[['彼女', 'かのじょ', None, None], [None, None, '：「', None], ['実', 'じつ', None, None], [None, None, 'はお', None], ['腹', 'なか', None, None], [None, None, 'が', None], ['痛', 'いた', None, None], [None, None, 'いの...」', None], ['彼氏', 'かれし', None, None], [None, None, '：「お', None], ['腹', 'なか', None, None], [None, None, 'が', None], ['痛', 'いた', None, True], [None, None, 'いなら', True], ['痛', 'いた', None, None], [None, None, 'い', None], [None, None, 'で', None], [None, None, '、ベッドで', None], ['寝', 'ね', None, None], [None, None, 'た', None], ['方', 'ほう', None, None], [None, None, 'がいいよ。あとは', None], ['俺', 'おれ', None, None], [None, None, 'に', None], ['任', 'まか', None, None], [None, None, 'せてね。」', None]]
[[None, None, '「', None], ['勝手', 'かって', None, None], [None, None, 'にジュースを', None], ['飲', 'の', None, True], [None, None, 'むなら', True], ['飲', 'の', None, None], [None, None, 'む', None], [None, None, 'で', None], [None, None, '、', None], ['正直', 'しょうじき', None, None], [None, None, 'に', None], ['言', 'い', None, None], [None, None, 'ってたらそんなに', None], ['怒', 'おこ', None, None], [None, None, 'られなかったのに。」', None]]

 85%|████████▌ | 800/938 [08:20<01:17,  1.79it/s]

[['上司', 'じょうし', None, None], [None, None, 'の', None], ['反対', 'はんたい', None, None], [None, None, 'をものともせず', True], ['提案', 'ていあん', None, None], [None, None, 'を', None], ['押', 'お', None, None], [None, None, 'し', None], ['通', 'とお', None, None], [None, None, 'した。', None]]
[['厳', 'きび', None, None], [None, None, 'しい', None], ['経済状況', 'けいざいじょうきょう', None, None], [None, None, 'をものともせず', True], [None, None, '、アンブレラ', None], ['社', 'しゃ', None, None], [None, None, 'の', None], ['株', 'かぶ', None, None], [None, None, 'は', None], ['急騰', 'きゅうとう', None, None], [None, None, 'した。', None]]
[['清瀬', 'きよせ', None, None], ['灰二', 'はいじ', None, None], ['選手', 'せんしゅ', None, None], [None, None, 'は', None], ['肺', 'はい', None, None], [None, None, 'がはげしくあえぐ', None], [None, None, 'のをものともせずに', True], [None, None, '、', None], ['最後', 'さいご', None, None], [None, None, 'まで', None], ['頑張', 'がんば', None, None], [None, None, 'って', None], ['勝利', 'しょうり', None, None], [None, None, 'した。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['政敵', 'せいてき', None, None], [None, None, 'からの', None], ['揶揄', 'やゆ', None, None], [None, None, 'をものともせず', True], ['選挙', 'せんきょ', None, None], [None, None, 'を', None], ['戦', 'たたか', None, None], [None, None, 'い', None], ['抜', 'ぬ', None, None], [None, None, 'き、', None], ['大統領', 'だいとうりょう', None, None], [None, None, 'の', None], ['座', 'ざ', None, None], [None, None, 'を', None], ['勝', 'か', None, None], [None, None, 'ち', None], ['取', 'と', None, None], [None, None, 'った。', None]]
[[None, None, 'ダンディーさんは、', None], ['体長', 'たいちょう', None, None], ['３', 'さん', None, None], [None, None, 'メートルほどもある', None], ['大蛇', 'だいじゃ', None, None], [None, None, 'の', None], ['攻撃', 'こうげき', None, None], [None, None, 'をものともせず', True], [None, None, '、', None], ['器用', 'きよう', None, None], [None, None, 'に', None], ['捕', 'つか', None, None], [None, None, 'まえ、', None], ['素手', 'すで', None, None], [None, None, 'で', None], ['殺', 'ころ', None, None], [None, None, 'したと', None], ['言', 'い', None, None], [None, None, 'う。', None]]

 85%|████████▌ | 801/938 [08:21<01:20,  1.71it/s]

[[None, None, '「', None], ['珍', 'めずら', None, None], [None, None, 'しいことではありません。', None], ['称賛', 'しょうさん', None, None], [None, None, 'には', True], ['当', 'あ', None, True], [None, None, 'たりません', True], [None, None, '。」', None]]
[[None, None, 'いつもよりテストの', None], ['点', 'てん', None, None], [None, None, 'が', None], ['５', 'ご', None, None], ['点', 'てん', None, None], ['低', 'ひく', None, None], [None, None, 'かったからって、そんなに', None], ['落', 'お', None, None], [None, None, 'ち', None], ['込', 'こ', None, None], [None, None, 'む', None], [None, None, 'には', True], ['当', 'あ', None, True], [None, None, 'たらない', True], [None, None, 'よ。', None]]
[[None, None, '「', None], ['結核', 'けっかく', None, None], [None, None, 'は', None], ['予防接種', 'よぼうせっしゅ', None, None], [None, None, 'を', None], ['受', 'う', None, None], [None, None, 'けた', None], ['健康', 'けんこう', None, None], [None, None, 'な', None], ['人', 'ひと', None, None], [None, None, 'なら、', None], ['心配', 'しんぱい', None, None], [None, None, 'する', None], [None, None, 'には', True], ['当', 'あ', None, True], [None, None, 'たらない', True], [None, None, '。」', None]]
[['娘', 'むすめ', None, None], [None, None, 'がまだ', None], ['帰', 'かえ', None, None], [None, None, 'ってきてないけど', None], ['心配', 'しんぱい', None, None], [None, None, 'には', True], ['当', 'あ', None, True], [None, None, 'たりません', True], [None, None, '。だって、いつも', None], ['飲', 'の', None, None], [None, None, 'み', None], ['歩', 'ある', None, None], [None, None, 'いているから…。', None]]
[['少', 'すこ', None, None], [None, None, 'しミスをしたからって', None], ['新入社員', 'しんにゅうしゃいん', None, None], [None, None, 'を', None], ['非難', 'ひなん', None, None], [None, None, 'には', True], ['当', 'あ', None, True], [None, None, 'たらない', True], [None, None, 'よ。', None], ['誰', 'だれ', None, None], [None, None, 'だってミスはするんだから。', None]]

 86%|████████▌ | 802/938 [08:22<01:27,  1.55it/s]

[[None, None, 'セールスマンはクライアントに', None], [None, None, '：「この', None], ['商品', 'しょうひん', None, None], [None, None, 'の', None], ['品質', 'ひんしつ', None, None], [None, None, 'でご', None], ['満足', 'まんぞく', None, None], [None, None, 'いただける', None], [None, None, 'ものと', True], ['思', 'おも', None, True], [None, None, 'います', True], [None, None, '。」', None]]
[[None, None, '「', None], ['可児江', 'かにえ', None, None], [None, None, 'さんを', None], ['支配人', 'しはいにん', None, None], [None, None, 'にすれば、このテーマパークは', None], ['必', 'かなら', None, None], [None, None, 'ず', None], ['成功', 'せいこう', None, None], [None, None, 'する', None], [None, None, 'ものと', True], ['思', 'おも', None, True], [None, None, 'います', True], [None, None, '。」', None]]
[[None, None, 'よしの', None], [None, None, '：「ウサギは', None], ['卵', 'たまご', None, None], [None, None, 'を', None], ['産', 'う', None, None], [None, None, 'まないわ...」', None], [None, None, 'しどう', None], [None, None, '：「でも、', None], ['実際', 'じっさい', None, None], [None, None, 'には', None], ['多', 'おお', None, None], [None, None, 'くの', None], ['人', 'ひと', None, None], [None, None, 'がそんな', None], ['風', 'ふう', None, None], [None, None, 'に', None], ['思', 'おも', None, None], [None, None, 'う', None], [None, None, 'もんと', True], ['思', 'おも', None, True], [None, None, 'う', True], [None, None, 'よ。」', None]]
[['社員', 'しゃいん', None, None], [None, None, 'が', None], ['上司', 'じょうし', None, None], [None, None, 'に', None], ['話', 'はな', None, None], [None, None, 'す', None], [None, None, '：「', None], ['宅配便', 'たくはいびん', None, None], [None, None, 'が', None], ['今日', 'きょう', None, None], [None, None, '、', None], ['約束通', 'やくそくどお', None, None], [None, None, 'りに', None], ['来', 'く', None, None], [None, None, 'る', None], [None, None, 'ものと', True], ['思', 'おも', None, True], [None, None, 'っています', True], [None, None, 'が、', None], ['念', 'ねん', None, None], [None, None, 'の', None], ['為', 'ため', None, None], [None, None, 'に', None], ['電話', 'でんわ', None, None], [None, None, 'をかけてみます。」', None]]
[['財務大臣', 'ざいむだいじん', None, None], [None, None, '：「この', None], ['問題', 'もんだい', None, None], [None, None, 'について、', None], ['政府', 'せいふ', None, None], [None, None, 'と', None], ['産業界', 'さんぎょうかい', None, None], [None, None, 'との', None], ['連携', 'れんけい', None, None], [None, None, 'はやがて', None], ['成果', 'せいか', None, None], [None, None, 'に', None], ['結', 'むす', None, None], [None, None, 'びつく', None], [None, None, 'ものと', True], ['思', 'おも', None, True], [None, None, 'います', True], [None, None, '。」', None]]

 86%|████████▌ | 803/938 [08:22<01:22,  1.64it/s]

[['会社', 'かいしゃ', None, None], [None, None, 'のサイト', None], [None, None, '：「', None], ['国際的', 'こくさいてき', None, None], [None, None, 'な', None], ['基準', 'きじゅん', None, None], [None, None, 'を', True], ['踏', 'ふ', None, True], [None, None, 'まえた', True], ['新製品開発', 'しんせいひんかいはつ', None, None], [None, None, 'に', None], ['懸命', 'けんめい', None, None], [None, None, 'に', None], ['取', 'と', None, None], [None, None, 'り', None], ['組', 'く', None, None], [None, None, 'んでいます。」', None]]
[[None, None, '「', None], ['我々', 'われわれ', None, None], [None, None, 'のアウトソーシング', None], ['分野', 'ぶんや', None, None], [None, None, 'で', None], ['１０', 'じゅう', None, None], ['年', 'ねん', None, None], ['以上', 'いじょう', None, None], [None, None, 'の', None], ['経験', 'けいけん', None, None], [None, None, 'を', True], ['踏', 'ふ', None, True], [None, None, 'まえた', True], ['提案', 'ていあん', None, None], [None, None, 'である。」', None]]
[['前回', 'ぜんかい', None, None], [None, None, 'の', None], ['反省', 'はんせい', None, None], [None, None, 'を', True], ['踏', 'ふ', None, True], [None, None, 'まえて', True], ['今回', 'こんかい', None, None], [None, None, 'のテストに', None], ['挑', 'いど', None, None], [None, None, 'んだのに、', None], ['結果', 'けっか', None, None], [None, None, 'は', None], ['前回', 'ぜんかい', None, None], [None, None, 'よりも', None], ['悪', 'わる', None, None], [None, None, 'かった。', None]]
[[None, None, 'お', None], ['客様', 'きゃくさま', None, None], [None, None, 'の', None], ['意見', 'いけん', None, None], [None, None, 'を', True], ['踏', 'ふ', None, True], [None, None, 'まえて', True], [None, None, '、', None], ['当', 'とう', None, None], [None, None, 'ホテルのチェックアウトの', None], ['時間', 'じかん', None, None], [None, None, 'を', None], ['一時間', 'いちじかん', None, None], ['遅', 'おそ', None, None], [None, None, 'くしました。', None]]
[['彼', 'かれ', None, None], [None, None, 'の', None], ['家庭', 'かてい', None, None], ['環境', 'かんきょう', None, None], [None, None, 'が', None], ['複雑', 'ふくざつ', None, None], [None, None, 'である', None], ['事', 'こと', None, None], [None, None, 'を', True], ['踏', 'ふ', None, True], [None, None, 'まえて', True], [None, None, '、', None], ['破格', 'はかく', None, None], [None, None, 'の', None], ['値段', 'ねだん', None, None], [None, None, 'で', None], ['社員用', 'しゃいんよう', None, None], [None, None, 'の', None], ['寮', 'りょう', None, None], [None, None, 'を', None], ['貸', 'か', None, None], [None, None, 'し', None], ['出', 'だ', None, None], [None, None, 'す', None], ['事', 'こと', None, None], [None, None, 'にしました。', None]]

 86%|████████▌ | 804/938 [08:23<01:16,  1.75it/s]

[[None, None, 'ラテン', None], ['語', 'ご', None, None], [None, None, 'のフレーズ', None], [None, None, '：「', None], ['不合理', 'ふごうり', None, None], ['故', 'ゆえ', None, True], [None, None, 'に', True], [None, None, 'われ', None], ['信', 'しん', None, None], [None, None, 'ず 」', None]]
[['手紙', 'てがみ', None, None], [None, None, '：「', None], ['季節', 'きせつ', None, None], [None, None, 'の', None], ['変', 'か', None, None], [None, None, 'わり', None], ['目', 'め', None, None], ['故', 'ゆえ', None, True], [None, None, '、くれぐれもご', None], ['自愛', 'じあい', None, None], [None, None, 'くださいませ。」', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「ベンジャミンの', None], ['若', 'わか', None, True], [None, None, 'さ', True], ['故', 'ゆえ', None, True], [None, None, 'の', True], ['自信過剰', 'じしんかじょう', None, None], [None, None, 'も', None], ['無知', 'むち', None, None], [None, None, 'もミセス・ロビンソンの', None], ['目', 'め', None, None], [None, None, 'からすれば、', None], ['可愛', 'かわい', None, None], [None, None, 'らしい。」', None]]
[['Ａ', 'エー', None, None], ['⇒', 'ならば', None, None], ['Ｂ', 'ビー', None, None], [None, None, '、', None], ['Ｂ', 'ビー', None, None], ['⇒', 'ならば', None, None], ['Ｃ', 'シー', None, None], ['故', 'ゆえ', None, True], [None, None, 'に', True], ['Ａ', 'エー', None, None], ['⇒', 'ならば', None, None], ['Ｃ', 'シー', None, None], [None, None, ' (', None], ['Ａ', 'エー', None, None], [None, None, 'が', None], ['真', 'しん', None, None], [None, None, 'ならば', None], ['Ｂ', 'ビー', None, None], [None, None, 'も', None], ['真', 'しん', None, None], [None, None, '、', None], ['Ｂ', 'ビー', None, None], [None, None, 'が', None], ['真', 'しん', None, None], [None, None, 'ならば', None], ['Ｃ', 'シー', None, None], [None, None, 'も', None], ['真', 'しん', None, None], [None, None, '。', None], ['故', 'ゆえ', None, True], [None, None, 'に', True], ['Ａ', 'エー', None, None], [None, None, 'が', None], ['真', 'しん', None, None], [None, None, 'ならば', None], ['Ｃ', 'シー', None, None], [None, None, 'も', None], ['真', 'しん', None, None], [None, None, 'である）', None]]
[[None, None, 'ファンタジー', None], ['小説', 'しょうせつ', None, None], [None, None, '：「 ドワーフ', None], ['族', 'ぞく', None, None], [None, None, 'が', None], ['滅', 'ほろ', None, None], [None, None, 'んだのは', None], ['富', 'とみ', None, None], [None, None, 'に', None], ['対', 'たい', None, None], [None, None, 'する', None], ['飽', 'あ', None, None], [None, None, 'くなき', None], ['欲望', 'よくぼう', None, None], ['故', 'ゆえ', None, True], [None, None, 'であった。」', None]]

 86%|████████▌ | 805/938 [08:23<01:13,  1.81it/s]

[[None, None, '「', None], ['今日', 'きょう', None, None], [None, None, 'という', True], ['今日', 'きょう', None, None], [None, None, 'は', None], ['許', 'ゆる', None, None], [None, None, 'さん。」', None]]
[['政治家', 'せいじか', None, None], [None, None, 'という', True], ['政治家', 'せいじか', None, None], [None, None, 'はみんな', None], ['口', 'くち', None, None], [None, None, 'ばっかりだ。', None]]
[[None, None, 'それを', None], ['聞', 'き', None, None], [None, None, 'いて、', None], ['人', 'ひと', None, None], [None, None, 'という', True], ['人', 'ひと', None, None], [None, None, 'が', None], ['一斉', 'いっせい', None, None], [None, None, 'に', None], ['頷', 'うなず', None, None], [None, None, 'いた。', None]]
[['山々', 'やまやま', None, None], [None, None, 'に', None], ['生', 'は', None, None], [None, None, 'えた', None], ['木', 'き', None, None], [None, None, 'という', True], ['木', 'き', None, None], [None, None, 'は', None], ['地', 'じ', None, None], [None, None, 'すべりのため', None], ['根', 'ね', None, None], [None, None, 'こそぎ', None], ['倒', 'たお', None, None], [None, None, 'れていた。', None]]
[['名古屋', 'なごや', None, None], [None, None, 'に', None], ['生', 'う', None, None], [None, None, 'まれて', None], ['名古屋', 'なごや', None, None], [None, None, 'で', None], ['育', 'そだ', None, None], [None, None, 'った。だから、', None], ['町中', 'まちなか', None, None], [None, None, 'の', None], ['道', 'みち', None, None], [None, None, 'という', True], ['道', 'みち', None, None], [None, None, '、', None], ['家', 'いえ', None, None], [None, None, 'という', True], ['家', 'いえ', None, None], [None, None, 'を、すっかり', None], ['知', 'し', None, None], [None, None, 'っている。', None]]

 86%|████████▌ | 806/938 [08:24<01:11,  1.85it/s]

[['共感', 'きょうかん', None, None], [None, None, 'は', None], ['人間', 'にんげん', None, None], [None, None, 'にとどまらず', True], [None, None, '、', None], ['動物', 'どうぶつ', None, None], [None, None, 'にも', None], ['見', 'み', None, None], [None, None, 'られるものである。', None]]
[['先日', 'せんじつ', None, None], [None, None, 'の', None], ['悪夢', 'あくむ', None, None], [None, None, 'が', None], ['夢', 'ゆめ', None, None], [None, None, 'にとどまらず', True], [None, None, '、まさか', None], ['現実', 'げんじつ', None, None], [None, None, 'になってしまうとは…。', None]]
[[None, None, 'ボックスステーション', None], ['７', 'セブン', None, None], [None, None, '、', None], ['日本国内', 'にほんこくない', None, None], [None, None, 'にとどまらず', True], [None, None, '、', None], ['海外', 'かいがい', None, None], [None, None, 'でも', None], ['普及', 'ふきゅう', None, None], [None, None, 'しています。', None]]
[['日本語', 'にほんご', None, None], [None, None, 'の', None], ['学習', 'がくしゅう', None, None], [None, None, 'によって', None], ['語学力', 'ごがくりょく', None, None], [None, None, 'にとどまらず', True], [None, None, '、', None], ['日本風', 'にほんふう', None, None], [None, None, 'の', None], ['考', 'かんが', None, None], [None, None, 'え', None], ['方', 'かた', None, None], [None, None, 'も', None], ['身', 'み', None, None], [None, None, 'に', None], ['着', 'つ', None, None], [None, None, 'ける。', None]]
[['会社', 'かいしゃ', None, None], [None, None, 'ウェブサイト', None], [None, None, '：「', None], ['当社', 'とうしゃ', None, None], [None, None, 'は', None], ['製品', 'せいひん', None, None], [None, None, 'を', None], ['販売', 'はんばい', None, None], [None, None, 'する', None], [None, None, 'にとどまらず', True], [None, None, '、その', None], ['商品', 'しょうひん', None, None], [None, None, 'の', None], ['設計', 'せっけい', None, None], [None, None, 'もいたします。」', None]]

 86%|████████▌ | 807/938 [08:24<01:12,  1.80it/s]

[[None, None, 'いよいよ', None], ['晴', 'は', None, None], [None, None, 'れる', None], [None, None, 'だろう', None], [None, None, 'と', True], ['思', 'おも', None, True], [None, None, 'いきや', True], [None, None, '、たちまち', None], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'り', None], ['出', 'だ', None, None], [None, None, 'してしまった。', None]]
[[None, None, '「やっぱり、', None], ['今度', 'こんど', None, None], [None, None, 'も', None], ['失敗', 'しっぱい', None, None], [None, None, 'したか...」', None], [None, None, 'と', True], ['思', 'おも', None, True], [None, None, 'いきや', True], [None, None, '、', None], ['見事', 'みごと', None, None], ['合格', 'ごうかく', None, None], [None, None, 'だった。', None]]
[[None, None, 'うたげさんが', None], ['小', 'ちい', None, None], [None, None, 'さいから', None], ['同級生', 'どうきゅうせい', None, None], [None, None, 'と', True], ['思', 'おも', None, True], [None, None, 'いきや', True], [None, None, '、', None], ['驚', 'おどろ', None, None], [None, None, 'くことに', None], ['先生', 'せんせい', None, None], [None, None, 'だった。', None]]
[['納豆', 'なっとう', None, None], [None, None, 'はまずそうに', None], ['見', 'み', None, None], [None, None, 'えるから、', None], ['間違', 'まちが', None, None], [None, None, 'いなくまずい', None], [None, None, 'と', True], ['思', 'おも', None, True], [None, None, 'いきや', True], [None, None, '、', None], ['実際', 'じっさい', None, None], [None, None, 'は、そうではなかった。', None]]
[['娘', 'むすめ', None, None], [None, None, 'は', None], ['部屋', 'へや', None, None], [None, None, 'がとても', None], ['静', 'しず', None, None], [None, None, 'かだからきっと', None], ['寝', 'ね', None, None], [None, None, 'ている', None], [None, None, 'と', True], ['思', 'おも', None, True], [None, None, 'いきや', True], [None, None, '、', None], ['意外', 'いがい', None, None], [None, None, 'にも', None], ['勉強', 'べんきょう', None, None], [None, None, 'していた。', None]]

 86%|████████▌ | 808/938 [08:25<01:19,  1.64it/s]

[[None, None, 'あたしがいなきゃ', None], [None, None, 'どうにも', True], [None, None, 'ならない', None], [None, None, 'でしょ？', None]]
[['友達', 'ともだち', None, None], [None, None, 'との', None], ['話', 'はなし', None, None], [None, None, '：「', None], ['後悔', 'こうかい', None, None], [None, None, 'し', None], [None, None, 'たって', None], [None, None, 'もう', None], [None, None, 'どうにも', True], [None, None, 'なん', None], [None, None, 'ない', None], [None, None, '。」', None]]
[[None, None, 'どうにも', True], [None, None, 'でき', None], [None, None, 'ない', None], ['事態', 'じたい', None, None], [None, None, 'に', None], ['陥', 'おちい', None, None], [None, None, 'っ', None], [None, None, 'た', None], [None, None, 'ので', None], ['手', 'て', None, None], [None, None, 'を', None], ['借', 'か', None, None], [None, None, 'り', None], [None, None, 'る', None], [None, None, 'しかない', None], [None, None, '。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['人', 'ひと', None, None], [None, None, 'の', None], ['言', 'い', None, None], [None, None, 'う', None], [None, None, 'こと', None], [None, None, 'を', None], ['聞', 'き', None, None], [None, None, 'か', None], [None, None, 'ない', None], [None, None, 'から', None], [None, None, 'アドバイスし', None], [None, None, 'たところで', None], [None, None, 'どうにも', True], [None, None, 'ならない', None], [None, None, 'よ。', None]]
[[None, None, '「', None], ['都心', 'としん', None, None], [None, None, 'に', None], ['向', 'む', None, None], [None, None, 'かう', None], ['電車', 'でんしゃ', None, None], [None, None, 'の', None], ['中', 'なか', None, None], [None, None, 'は', None], [None, None, '、', None], ['人', 'ひと', None, None], [None, None, 'で', None], [None, None, 'いっぱい。', None], [None, None, 'どうにも', True], ['身動', 'みうご', None, None], [None, None, 'きし', None], [None, None, 'ようがない', None], [None, None, '。」 ', None]]

 86%|████████▌ | 809/938 [08:26<01:22,  1.56it/s]

[['飛行機代', 'ひこうきだい', None, None], [None, None, 'も', None], ['安', 'やす', None, None], [None, None, 'い', None], [None, None, 'ことだし', True], ['天気', 'てんき', None, None], [None, None, 'も', None], [None, None, 'いい', None], [None, None, 'から', None], ['沖縄', 'おきなわ', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'こう', None], [None, None, 'よ', None], [None, None, '。', None]]
[['割引', 'わりびき', None, None], [None, None, 'クーポン', None], [None, None, 'も', None], [None, None, 'ある', None], [None, None, 'ことだし', True], [None, None, '、', None], ['明日', 'あした', None, None], ['映画', 'えいが', None, None], [None, None, 'を', None], ['一緒', 'いっしょ', None, None], [None, None, 'に', None], ['観', 'み', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'か', None], [None, None, 'ない', None], [None, None, '？ ', None]]
[[None, None, 'もう', None], ['夜', 'よる', None, None], [None, None, 'も', None], ['更', 'ふ', None, None], [None, None, 'け', None], [None, None, 'てくる', None], [None, None, 'ことだし', True], [None, None, '、', None], ['今日', 'きょう', None, None], [None, None, 'の', None], [None, None, 'パーティ', None], [None, None, 'は', None], [None, None, 'これ', None], [None, None, 'で', None], [None, None, 'お', None], ['開', 'ひら', None, None], [None, None, 'きにし', None], [None, None, 'よう', None], [None, None, '！', None]]
[['風邪', 'かぜ', None, None], [None, None, 'を', None], ['引', 'ひ', None, None], [None, None, 'いている', None], [None, None, 'ことだし', True], [None, None, '、', None], ['今日', 'きょう', None, None], [None, None, 'くらいは', None], ['何', 'なに', None, None], [None, None, 'もしないでゆっくり', None], ['休', 'やす', None, None], [None, None, 'んだら？', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'のことだし', True], [None, None, '、きっと', None], ['次', 'つぎ', None, None], [None, None, 'の', None], ['試合', 'しあい', None, None], [None, None, 'には', None], ['勝', 'か', None, None], [None, None, 'つ', None], [None, None, 'と', None], [None, None, 'わたし', None], [None, None, 'は', None], ['信', 'しん', None, None], [None, None, 'じ', None], [None, None, 'ている', None], [None, None, 'よ', None], [None, None, '！', None]]

 86%|████████▋ | 810/938 [08:26<01:23,  1.53it/s]

[['昨日', 'きのう', None, None], [None, None, 'の', None], ['帰', 'かえ', None, None], [None, None, 'りが', None], ['遅', 'おそ', None, None], [None, None, 'くなった', None], ['理由', 'りゆう', None, None], [None, None, 'を、', None], ['妻', 'つま', None, None], [None, None, 'に', None], [None, None, 'ガン', True], ['詰', 'づ', None, True], [None, None, 'め', True], [None, None, 'された。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['娘', 'むすめ', None, None], [None, None, 'がいじめられていたなんて、もう', None], ['学校', 'がっこう', None, None], [None, None, 'に', None], [None, None, 'ガン', True], ['切', 'ぎ', None, True], [None, None, 'れ', True], [None, None, 'しに', None], ['行', 'い', None, None], [None, None, 'くしかない。', None]]
[[None, None, 'あれだけ', None], ['彼', 'かれ', None, None], [None, None, 'に', None], ['会', 'あ', None, None], [None, None, 'えることを', None], ['楽', 'たの', None, None], [None, None, 'しみにしていたのだから、', None], ['彼女', 'かのじょ', None, None], [None, None, 'が', None], [None, None, 'ガン', True], ['萎', 'な', None, True], [None, None, 'え', True], [None, None, 'するのも', None], ['無理', 'むり', None, None], [None, None, 'はないと', None], ['思', 'おも', None, None], [None, None, 'う。', None]]
[['犬', 'いぬ', None, None], [None, None, 'が', None], ['主人公', 'しゅじんこう', None, None], [None, None, 'の', None], ['映画', 'えいが', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'たら、', None], ['過去', 'かこ', None, None], [None, None, 'に', None], ['飼', 'か', None, None], [None, None, 'っていた', None], ['愛犬', 'あいけん', None, None], [None, None, 'とその', None], ['犬', 'いぬ', None, None], [None, None, 'を', None], ['重', 'かさ', None, None], [None, None, 'ねてしまって、', None], [None, None, 'ガン', True], ['泣', 'な', None, True], [None, None, 'き', True], [None, None, 'した。', None]]
[[None, None, 'ちょっとした', None], ['冗談', 'じょうだん', None, None], [None, None, 'のつもりだったのに、', None], ['彼女', 'かのじょ', None, None], [None, None, 'にとっては', None], ['地雷', 'じらい', None, None], [None, None, 'だったみたいで、いきなり', None], [None, None, 'ガン', True], ['切', 'ぎ', None, True], [None, None, 'れ', True], [None, None, 'された。', None]]

 86%|████████▋ | 811/938 [08:27<01:22,  1.53it/s]

[['自分', 'じぶん', None, None], [None, None, 'の', None], ['人生', 'じんせい', None, None], [None, None, 'に', None], ['満足', 'まんぞく', None, None], [None, None, 'できる', None], [None, None, 'か', True], ['否', 'いな', None, True], [None, None, 'か', True], [None, None, '、それはあなたの', None], ['頑張', 'がんば', None, None], [None, None, 'り', None], ['次第', 'しだい', None, None], [None, None, 'である。', None]]
[['今', 'いま', None, None], [None, None, 'の', None], ['会社', 'かいしゃ', None, None], [None, None, 'を', None], ['辞', 'や', None, None], [None, None, 'めて', None], ['転職', 'てんしょく', None, None], [None, None, 'する', None], [None, None, 'か', True], ['否', 'いな', None, True], [None, None, 'か', True], [None, None, '、もう', None], ['少', 'すこ', None, None], [None, None, 'し', None], ['悩', 'なや', None, None], [None, None, 'む', None], ['事', 'こと', None, None], [None, None, 'にしよう。', None]]
[[None, None, 'イベントのサイト', None], [None, None, '：「', None], ['参加資格', 'さんかしかく', None, None], [None, None, '： ', None], ['登録', 'とうろく', None, None], [None, None, 'ユーザー', None], [None, None, 'である', None], [None, None, 'か', True], ['否', 'いな', None, True], [None, None, 'か', True], [None, None, 'を', None], ['問', 'と', None, None], [None, None, 'わず、どなたでもご', None], ['参加可能', 'さんかかのう', None, None], [None, None, '」', None]]
[['記事', 'きじ', None, None], [None, None, 'のタイトル', None], [None, None, '：「プロゲーマーは', None], ['真', 'しん', None, None], [None, None, 'のスポーツ', None], ['選手', 'せんしゅ', None, None], [None, None, 'か', True], ['否', 'いな', None, True], [None, None, 'か', True], [None, None, '。', None], ['ｅ', 'イー', None, None], [None, None, 'スポーツ', None], ['業界', 'ぎょうかい', None, None], [None, None, 'が', None], ['直面', 'ちょくめん', None, None], [None, None, 'するビザの', None], ['問題', 'もんだい', None, None], [None, None, '」', None]]
[[None, None, 'サイト、クッキーファイルについて', None], [None, None, '：「', None], ['利用者', 'りようしゃ', None, None], [None, None, 'はそのクッキーを', None], ['受', 'う', None, None], [None, None, 'け', None], ['入', 'い', None, None], [None, None, 'れる', None], [None, None, 'か', True], ['否', 'いな', None, True], [None, None, 'か', True], [None, None, 'を', None], ['決', 'き', None, None], [None, None, 'めることができますし、また、', None], ['全部', 'ぜんぶ', None, None], [None, None, 'のクッキーを', None], ['削除', 'さくじょ', None, None], [None, None, 'することもできます。」', None]]

 87%|████████▋ | 812/938 [08:28<01:20,  1.56it/s]

[[None, None, '「もし', None], ['失敗', 'しっぱい', None, None], [None, None, 'し', None], [None, None, 'たら', None], ['失敗', 'しっぱい', None, True], [None, None, 'したで', True], [None, None, '、また', None], ['最初', 'さいしょ', None, None], [None, None, 'からやり', None], ['直', 'なお', None, None], [None, None, 'そうと', None], ['思', 'おも', None, None], [None, None, 'う。」', None]]
[[None, None, '「', None], ['結婚', 'けっこん', None, None], [None, None, 'したい。」', None], [None, None, '「', None], ['結婚', 'けっこん', None, None], [None, None, 'したら', True], [None, None, 'した', None], [None, None, 'で', None], ['大変', 'たいへん', None, None], [None, None, 'だよ。」', None]]
[[None, None, '「また', None], ['子供', 'こども', None, None], [None, None, 'になりたいな。」', None], [None, None, '「けど、', None], ['子供', 'こども', None, None], [None, None, 'になっ', None], [None, None, 'たら', None], [None, None, 'なったで', True], ['子供', 'こども', None, None], [None, None, 'なりの', None], ['苦労', 'くろう', None, None], [None, None, 'があるよ」', None]]
[[None, None, '「', None], ['金', 'かね', None, None], [None, None, 'は', None], ['沢山', 'たくさん', None, None], [None, None, 'あったら', True], [None, None, 'あった', None], [None, None, 'で', None], ['悩', 'なや', None, None], [None, None, 'みも', None], ['増', 'ふ', None, None], [None, None, 'えるものだよ。」', None], [None, None, '「それはそうだけど、でも、なかっ', None], [None, None, 'たら', None], [None, None, 'ない', None], [None, None, 'で', None], ['困', 'こま', None, None], [None, None, 'るでしょ。」', None]]
[[None, None, '「スーパーとかで', None], ['高', 'たか', None, None], [None, None, 'い', None], ['棚', 'たな', None, None], [None, None, 'に', None], ['手', 'て', None, None], [None, None, 'が', None], ['届', 'とど', None, None], [None, None, 'けばいいんだけど、', None], ['背', 'せ', None, None], [None, None, 'が', None], ['低', 'ひく', None, None], [None, None, 'け', None], [None, None, 'れば', None], ['低', 'ひく', None, True], [None, None, 'いで', True], [None, None, '、なんとかなるはずだ。」', None]]

 87%|████████▋ | 813/938 [08:28<01:19,  1.56it/s]

[[None, None, 'タイトル', None], [None, None, '：「', None], ['俺', 'おれ', None, None], [None, None, 'の', None], ['青春', 'せいしゅん', None, None], [None, None, 'ラブコメはまちがいに', None], [None, None, 'なる', None], [None, None, 'べくして', True], [None, None, 'なった', None], [None, None, '。」', None]]
[['壊', 'こわ', None, None], [None, None, 'れた', None], ['一時停止', 'いちじていし', None, None], ['標識', 'ひょうしき', None, None], [None, None, 'を', None], ['放置', 'ほうち', None, None], [None, None, 'した', None], ['結果', 'けっか', None, None], [None, None, '、', None], ['起', 'お', None, None], [None, None, 'こる', None], [None, None, 'べくして', True], ['起', 'お', None, None], [None, None, 'こった', None], ['交通事故', 'こうつうじこ', None, None], [None, None, 'だ。', None]]
[[None, None, '「これらの', None], ['二人', 'ふたり', None, None], [None, None, 'は、', None], ['専門分野', 'せんもんぶんや', None, None], [None, None, 'も', None], ['年齢', 'ねんれい', None, None], [None, None, 'も', None], ['共', 'とも', None, None], [None, None, 'に', None], ['近', 'ちか', None, None], [None, None, 'いゆえに', None], ['出会', 'であ', None, None], [None, None, 'う', None], [None, None, 'べくして', True], ['出会', 'であ', None, None], [None, None, 'った', None], [None, None, 'と', None], ['言', 'い', None, None], [None, None, 'えるだろう。」', None]]
[['不景気', 'ふけいき', None, None], [None, None, 'か', None], ['否', 'いな', None, None], [None, None, 'かにかかわらず、', None], ['高品質', 'こうひんしつ', None, None], [None, None, 'で', None], ['適正価格', 'てきせいかかく', None, None], [None, None, 'の', None], ['商品', 'しょうひん', None, None], [None, None, 'は', None], ['売', 'う', None, None], [None, None, 'れる', None], [None, None, 'べくして', True], ['売', 'う', None, None], [None, None, 'れている', None], [None, None, '。', None]]
[['好景気', 'こうけいき', None, None], [None, None, 'が', None], ['遅', 'おそ', None, None], [None, None, 'かれ', None], ['早', 'はや', None, None], [None, None, 'かれ', None], ['終', 'お', None, None], [None, None, 'わるのは', None], ['経済学者', 'けいざいがくしゃ', None, None], [None, None, 'にとって', None], ['当然', 'とうぜん', None, None], [None, None, 'のことであったし、そう', None], [None, None, 'なる', None], [None, None, 'べくして', True], [None, None, 'なった', None], [None, None, '。', None]]

 87%|████████▋ | 814/938 [08:29<01:15,  1.64it/s]

[['足', 'あし', None, None], [None, None, 'の', None], ['向', 'む', None, None], [None, None, 'く', None], [None, None, 'ままに', True], [None, None, 'バイクで', None], ['駆', 'か', None, None], [None, None, 'けていたら', None], ['公園', 'こうえん', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'き', None], ['着', 'つ', None, None], [None, None, 'いてしまったのだ。', None]]
[['抽象画家', 'ちゅうしょうがか', None, None], [None, None, 'は', None], ['深', 'ふか', None, None], [None, None, 'く', None], ['考', 'かんが', None, None], [None, None, 'えずに', None], ['形', 'かたち', None, None], [None, None, 'や', None], ['色', 'いろ', None, None], [None, None, 'を', None], ['気', 'き', None, None], [None, None, 'の', None], ['向', 'む', None, None], [None, None, 'く', None], [None, None, 'ままに', True], ['選', 'えら', None, None], [None, None, 'ぶ。', None]]
[['Ａ', 'エー', None, None], [None, None, '：「ジラヤさんはどこ？」', None], ['Ｂ', 'ビー', None, None], [None, None, '：「わからん。どこかに', None], ['行', 'い', None, None], [None, None, 'ったんだ。」', None], ['Ａ', 'エー', None, None], [None, None, '：「', None], ['相変', 'あいか', None, None], [None, None, 'わらず、', None], ['風', 'かぜ', None, None], [None, None, 'の', None], ['吹', 'ふ', None, None], [None, None, 'く', None], [None, None, 'まま', True], [None, None, '、', None], ['赴', 'おもむ', None, None], [None, None, 'くなぁ。」', None]]
[[None, None, 'ふぶき', None], [None, None, '：「そのあと、どうするつもり？」', None], [None, None, 'さいたま', None], [None, None, '：「ただ', None], ['心', 'こころ', None, None], [None, None, 'の', None], ['欲', 'ほっ', None, None], [None, None, 'する', None], [None, None, 'まま', True], [None, None, '、', None], ['自由', 'じゆう', None, None], [None, None, 'に', None], ['生', 'い', None, None], [None, None, 'きる。」', None]]
[[None, None, 'モーガンさん、クリスチャンさんに', None], [None, None, '：「あなたのものですから', None], ['気兼', 'きが', None, None], [None, None, 'ねなく', None], ['自分', 'じぶん', None, None], [None, None, 'の', None], ['思', 'おも', None, None], [None, None, 'う', None], [None, None, 'ままに', True], ['扱', 'あつか', None, None], [None, None, 'ってもいいです。」', None]]

 87%|████████▋ | 815/938 [08:29<01:16,  1.61it/s]

[[None, None, '「こんなにタバコを', None], ['吸', 'す', None, None], [None, None, 'い', None], ['続', 'つづ', None, None], [None, None, 'けては', None], ['遅', 'おそ', None, True], [None, None, 'かれ', True], ['早', 'はや', None, True], [None, None, 'かれ', True], ['病気', 'びょうき', None, None], [None, None, 'になるだろう。」', None]]
[[None, None, 'この', None], ['発見', 'はっけん', None, None], [None, None, 'は', None], [None, None, 'よかれあしかれ', True], [None, None, '、', None], ['大', 'おお', None, None], [None, None, 'きな', None], ['変化', 'へんか', None, None], [None, None, 'をもたらすだろう。', None]]
[['好奇心', 'こうきしん', None, None], [None, None, 'は', None], ['多', 'おお', None, True], [None, None, 'かれすくなかれ', True], ['誰', 'だれ', None, None], [None, None, 'もが', None], ['持', 'も', None, None], [None, None, 'っているものだろう。', None]]
[['遅', 'おそ', None, True], [None, None, 'かれはやかれ', True], ['有人', 'ゆうじん', None, None], ['火星', 'かせい', None, None], ['探査', 'たんさ', None, None], [None, None, 'の', None], ['時代', 'じだい', None, None], [None, None, 'はやってくるはずだ。', None]]
[[None, None, 'よかれあしかれ', True], [None, None, '、', None], ['確', 'たし', None, None], [None, None, 'かに', None], ['社会', 'しゃかい', None, None], [None, None, 'がキャッシュレス', None], ['化', 'か', None, None], [None, None, 'する', None], ['傾向', 'けいこう', None, None], [None, None, 'が', None], ['続', 'つづ', None, None], [None, None, 'いている。', None]]

 87%|████████▋ | 816/938 [08:30<01:12,  1.69it/s]

[['親友', 'しんゆう', None, None], [None, None, 'から', None], ['土下座', 'どげざ', None, None], [None, None, 'をしながら', None], ['頼', 'たの', None, None], [None, None, 'まれては、', None], ['断', 'ことわ', None, True], [None, None, 'るに', True], ['断', 'ことわ', None, True], [None, None, 'れません', True], [None, None, '。', None]]
[['逃', 'に', None, True], [None, None, 'げるに', True], ['逃', 'に', None, True], [None, None, 'げられない', True], ['状況', 'じょうきょう', None, None], [None, None, 'から', None], ['救', 'すく', None, None], [None, None, 'ってくれたのは、いつもは', None], ['厳', 'きび', None, None], [None, None, 'しい', None], ['先輩', 'せんぱい', None, None], [None, None, 'だった。', None]]
[['嫌', 'きら', None, None], [None, None, 'われている', None], ['上司', 'じょうし', None, None], [None, None, 'が', None], ['見事', 'みごと', None, None], [None, None, 'に', None], ['転', 'ころ', None, None], [None, None, 'んでしまった。', None], ['従業員', 'じゅうぎょういん', None, None], [None, None, 'が', None], ['笑', 'わら', None, True], [None, None, 'うに', True], ['笑', 'わら', None, True], [None, None, 'えない', True], [None, None, '、という', None], ['顔', 'かお', None, None], [None, None, 'をしてた。', None]]
[[None, None, '「', None], ['彼', 'かれ', None, None], [None, None, 'はどうして', None], ['学校', 'がっこう', None, None], [None, None, 'に', None], ['戻', 'もど', None, None], [None, None, 'ろうとしないのかな？」', None], [None, None, '「', None], ['何', 'なに', None, None], [None, None, 'があったか', None], ['知', 'し', None, None], [None, None, 'らないけど、', None], ['言', 'い', None, True], [None, None, 'うに', True], ['言', 'い', None, True], [None, None, 'えない', True], ['事情', 'じじょう', None, None], [None, None, 'があるのかな。」', None]]
[[None, None, '「', None], ['彼女', 'かのじょ', None, None], [None, None, 'が', None], ['断', 'ことわ', None, None], [None, None, 'れば', None], ['殺', 'ころ', None, None], [None, None, 'すと', None], ['言', 'い', None, None], [None, None, 'って', None], ['突然', 'とつぜん', None, None], ['断', 'ことわ', None, True], [None, None, 'るに', True], ['断', 'ことわ', None, True], [None, None, 'れない', True], ['状態', 'じょうたい', None, None], [None, None, 'になった。」', None]]

 87%|████████▋ | 817/938 [08:30<01:07,  1.78it/s]

[['名言', 'めいげん', None, None], [None, None, '：「', None], ['努力', 'どりょく', None, None], [None, None, 'なくして', True], ['成功', 'せいこう', None, None], [None, None, 'なし。」', None]]
[['愛', 'あい', None, None], [None, None, 'なくしては', True], ['生', 'い', None, None], [None, None, 'きられないというが、それが', None], ['苦痛', 'くつう', None, None], [None, None, 'になることもある。', None]]
[[None, None, 'トランジスタの', None], ['開発', 'かいはつ', None, None], [None, None, 'なくして', True], [None, None, '、', None], ['現在', 'げんざい', None, None], [None, None, 'の', None], ['世界', 'せかい', None, None], [None, None, 'は', None], ['成立', 'せいりつ', None, None], [None, None, 'しえない。', None]]
[[None, None, '「ノーベル', None], ['賞', 'しょう', None, None], ['受賞', 'じゅしょう', None, None], [None, None, 'はノーベル', None], ['委員会', 'いいんかい', None, None], [None, None, 'に', None], ['是認', 'ぜにん', None, None], [None, None, 'される', None], [None, None, 'ことなくしては', True], [None, None, '、ありえないことであろう。」', None]]
[[None, None, 'スピーチ、', None], ['ＣＥＯ', 'シーイーオー', None, None], [None, None, '：「', None], ['消費者', 'しょうひしゃ', None, None], [None, None, 'の', None], ['皆様', 'みなさま', None, None], [None, None, 'との', None], ['協力', 'きょうりょく', None, None], [None, None, 'なくしては', True], [None, None, 'この', None], ['商品', 'しょうひん', None, None], ['開発', 'かいはつ', None, None], [None, None, 'は', None], ['不可能', 'ふかのう', None, None], [None, None, 'であります。」', None]]

 87%|████████▋ | 818/938 [08:31<01:12,  1.66it/s]

[[None, None, 'お', None], ['母', 'かあ', None, None], [None, None, 'さんが「', None], ['勉強', 'べんきょう', None, None], [None, None, 'しろ」ってうるさい', None], [None, None, 'のなんのって', True], [None, None, '、もう', None], ['家', 'いえ', None, None], [None, None, 'に', None], ['帰', 'かえ', None, None], [None, None, 'りたくないよ…。', None]]
[[None, None, 'あの', None], ['旅館', 'りょかん', None, None], [None, None, 'の', None], ['女将', 'おかみ', None, None], [None, None, 'さんは', None], ['愛想', 'あいそ', None, None], [None, None, 'が', None], ['悪', 'わる', None, None], [None, None, 'い', None], [None, None, 'のなんのって', True], [None, None, '、もう', None], ['二度', 'にど', None, None], [None, None, 'と', None], ['行', 'い', None, None], [None, None, 'くもんか！', None]]
[[None, None, 'ジャングルの', None], ['中', 'なか', None, None], [None, None, 'でワニと', None], ['出', 'で', None, None], [None, None, 'くわした', None], ['時', 'とき', None, None], [None, None, 'は', None], ['焦', 'あせ', None, None], [None, None, 'った', None], [None, None, 'のなんのって', True], [None, None, '、もう', None], ['死', 'し', None, None], [None, None, 'ぬかと', None], ['思', 'おも', None, None], [None, None, 'ったよ！', None]]
[['東京', 'とうきょう', None, None], [None, None, 'の', None], ['夏', 'なつ', None, None], [None, None, 'は', None], ['蒸', 'む', None, None], [None, None, 'し', None], ['暑', 'あつ', None, None], [None, None, 'い', None], [None, None, 'のなんのって', True], [None, None, '、', None], ['少', 'すこ', None, None], [None, None, 'し', None], ['歩', 'ある', None, None], [None, None, 'いただけで', None], ['気持', 'きも', None, None], [None, None, 'ち', None], ['悪', 'わる', None, None], [None, None, 'くなるくらいです。', None]]
[['夫', 'おっと', None, None], [None, None, 'の', None], ['実家', 'じっか', None, None], [None, None, 'は', None], ['広', 'ひろ', None, None], [None, None, 'い', None], [None, None, 'のなんのって', True], [None, None, '、', None], ['庭', 'にわ', None, None], [None, None, 'には', None], ['沢山', 'たくさん', None, None], [None, None, 'の', None], ['木', 'き', None, None], [None, None, 'が', None], ['植', 'う', None, None], [None, None, 'えられていてプールもあるんだよ！', None]]

 87%|████████▋ | 819/938 [08:32<01:16,  1.56it/s]

[[None, None, 'ほむら', None], [None, None, '：「すべてが', None], ['一人', 'ひとり', None, None], [None, None, 'の', None], ['少女', 'しょうじょ', None, None], [None, None, 'の', None], ['選択', 'せんたく', None, None], [None, None, 'にかかっている', True], [None, None, '。」', None]]
[[None, None, 'コーチ', None], [None, None, '：「', None], ['勝', 'か', None, None], [None, None, 'つも', None], ['負', 'ま', None, None], [None, None, 'けるも', None], ['我々', 'われわれ', None, None], [None, None, 'の', None], ['協力', 'きょうりょく', None, None], [None, None, 'にかかっている', True], [None, None, 'から', None], ['頑張', 'かんば', None, None], [None, None, 'ろう。」', None]]
[['明日', 'あした', None, None], ['予定', 'よてい', None, None], ['通', 'どお', None, None], [None, None, 'りにピクニックに', None], ['行', 'い', None, None], [None, None, 'ける', None], [None, None, 'かどうか', None], [None, None, 'は', None], ['明日', 'あした', None, None], [None, None, 'の', None], ['天気', 'てんき', None, None], [None, None, 'にかかっている', True], [None, None, '。', None]]
[['成功', 'せいこう', None, None], [None, None, 'する', None], [None, None, 'かどうか', None], [None, None, 'は', None], ['才能', 'さいのう', None, None], [None, None, 'よりむしろどれだけ', None], ['頑張', 'がんば', None, None], [None, None, 'る', None], [None, None, 'か', None], [None, None, 'にかかっている', True], [None, None, 'と', None], ['言', 'い', None, None], [None, None, 'えるだろう。', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「', None], ['帝国', 'ていこく', None, None], [None, None, 'の', None], ['運命', 'うんめい', None, None], [None, None, 'はターニャの', None], ['作戦', 'さくせん', None, None], [None, None, 'が', None], ['成功', 'せいこう', None, None], [None, None, 'する', None], [None, None, 'か', None], ['否', 'いな', None, None], [None, None, 'か', None], [None, None, 'にかかっている', True], [None, None, '。」', None]]

 87%|████████▋ | 820/938 [08:32<01:10,  1.66it/s]

[['献辞', 'けんじ', None, None], [None, None, '：「', None], ['愛', 'あい', None, True], [None, None, 'してやまない', True], ['妻', 'つま', None, None], [None, None, 'と', None], ['息子', 'むすこ', None, None], [None, None, 'へ」', None]]
[[None, None, 'スピーチ', None], [None, None, '：「', None], ['飢餓', 'きが', None, None], [None, None, 'がこの', None], ['世界', 'せかい', None, None], [None, None, 'から', None], ['駆逐', 'くちく', None, None], [None, None, 'されることを、', None], ['祈', 'いの', None, True], [None, None, 'ってやみません', True], [None, None, '。」', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「', None], ['彼', 'かれ', None, None], [None, None, 'は', None], ['人', 'ひと', None, None], [None, None, 'を', None], ['惹', 'ひ', None, True], [None, None, 'きつけてやまない', True], ['何', 'なに', None, None], [None, None, 'かを', None], ['持', 'も', None, None], [None, None, 'っていると', None], ['言', 'い', None, None], [None, None, 'えるだろう。」', None]]
[[None, None, 'どうして', None], ['科学的', 'かがくてき', None, None], [None, None, 'な', None], ['証拠', 'しょうこ', None, None], [None, None, 'もないのに', None], ['幽霊', 'ゆうれい', None, None], [None, None, 'を', None], ['信', 'しん', None, True], [None, None, 'じてやまない', True], ['人', 'ひと', None, None], [None, None, 'がこんなに', None], ['沢山', 'たくさん', None, None], [None, None, 'いるのかな…。', None]]
[['賛辞', 'さんじ', None, None], [None, None, '：「', None], ['友達', 'ともだち', None, None], [None, None, 'としても', None], ['人', 'ひと', None, None], [None, None, 'としても', None], ['心', 'こころ', None, None], [None, None, 'の', None], ['中', 'なか', None, None], [None, None, 'に', None], ['生涯', 'しょうがい', None, None], ['存在', 'そんざい', None, None], [None, None, 'する', None], ['尊敬', 'そんけい', None, None], [None, None, 'してやまない', True], ['人', 'ひと', None, None], [None, None, 'でした。」', None]]

 88%|████████▊ | 821/938 [08:33<01:10,  1.66it/s]

[[None, None, '「やらずに', None], ['後悔', 'こうかい', None, None], [None, None, 'する', None], [None, None, 'くらいなら', True], [None, None, '、', None], [None, None, 'いっそ', None], [None, None, 'やってみ', None], [None, None, 'なさい', None], [None, None, 'よ。」', None]]
[[None, None, '「 こんなクソゲームを', None], ['買', 'か', None, None], [None, None, 'う', None], [None, None, 'くらいなら', True], [None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'をドブに', None], ['捨', 'す', None, None], [None, None, 'てたほうがよかった・・・」', None]]
[[None, None, '「その', None], ['仕事', 'しごと', None, None], [None, None, 'は', None], ['絶対', 'ぜったい', None, None], [None, None, 'に', None], ['嫌', 'いや', None, None], [None, None, 'だ。それに', None], ['戻', 'もど', None, None], [None, None, 'る', None], [None, None, 'くらいなら', True], ['死', 'し', None, None], [None, None, 'んだ', None], [None, None, 'ほうがましだ', None], [None, None, '。」', None]]
[[None, None, '「', None], ['小', 'ちい', None, None], [None, None, 'さなことに', None], ['目', 'め', None, None], [None, None, 'くじらを', None], ['立', 'た', None, None], [None, None, 'てる', None], ['人', 'ひと', None, None], [None, None, 'と', None], ['一緒', 'いっしょ', None, None], [None, None, 'に', None], ['生活', 'せいかつ', None, None], [None, None, 'する', None], [None, None, 'くらいなら', True], [None, None, 'ホームレスになった', None], [None, None, 'ほうがましだ', None], [None, None, '。」', None]]
[['Ａ', 'エー', None, None], [None, None, '：「', None], ['愛', 'あい', None, None], ['Ｐｈｏｎｅ', 'フォン', None, None], [None, None, 'の', None], ['画面', 'がめん', None, None], [None, None, 'の', None], ['修理', 'しゅうり', None, None], [None, None, 'は', None], ['３', 'さん', None, None], ['万円', 'まんえん', None, None], [None, None, 'からするよ。どうしようかな？」', None], ['Ｂ', 'ビー', None, None], [None, None, '：「とっても', None], ['高', 'たか', None, None], [None, None, 'いよね！', None], ['修理', 'しゅうり', None, None], [None, None, 'する', None], [None, None, 'くらいなら', True], ['新', 'あたら', None, None], [None, None, 'しいのを', None], ['買', 'か', None, None], [None, None, 'っちゃった', None], ['方', 'ほう', None, None], [None, None, 'がいい', None], [None, None, 'かなあ。」', None]]

 88%|████████▊ | 822/938 [08:34<01:12,  1.59it/s]

[['親', 'おや', None, None], [None, None, '：「もっとお', None], ['姉', 'ねえ', None, None], [None, None, 'ちゃんを', None], ['見習', 'みなら', None, None], [None, None, 'いなさい！」', None], ['子供', 'こども', None, None], [None, None, '：「', None], ['見習', 'みなら', None, None], [None, None, 'いたくない', None], [None, None, 'ったら', True], [None, None, '！', None], [None, None, '」', None]]
[['親', 'おや', None, None], [None, None, '：「', None], ['宿題', 'しゅくだい', None, None], [None, None, 'やりなさいよ！」', None], [None, None, 'イライラした', None], ['子供', 'こども', None, None], [None, None, '：「', None], ['今', 'いま', None, None], [None, None, 'からやる', None], [None, None, 'ったら', True], [None, None, '！', None], [None, None, '」', None]]
[['配偶者', 'はいぐうしゃ', None, None], ['１', 'いち', None, None], [None, None, 'がケーキを', None], ['食', 'た', None, None], [None, None, 'べようとしている', None], ['配偶者', 'はいぐうしゃ', None, None], ['２', 'に', None, None], [None, None, 'に「ケーキを', None], ['夕食', 'ゆうしょく', None, None], [None, None, 'の', None], ['前', 'まえ', None, None], [None, None, 'に', None], ['食', 'た', None, None], [None, None, 'べちゃダメ', None], [None, None, 'ったら', True], [None, None, '！', None], [None, None, '」', None]]
[['友達', 'ともだち', None, None], ['１', 'いち', None, None], [None, None, '：「', None], ['俺', 'おれ', None, None], [None, None, 'と', None], ['一緒', 'いっしょ', None, None], [None, None, 'バンジージャンプ、やってみない？」', None], ['友達', 'ともだち', None, None], ['２', 'に', None, None], [None, None, '：「', None], ['興味', 'きょうみ', None, None], [None, None, 'ないんだ。」', None], ['友達', 'ともだち', None, None], ['１', 'いち', None, None], [None, None, '：「', None], ['本当', 'ほんとう', None, None], [None, None, 'に？」', None], ['友達', 'ともだち', None, None], ['２', 'に', None, None], [None, None, '：「やだ', None], [None, None, 'ってば', True], [None, None, '、もう', None], [None, None, '！', None], [None, None, '」', None]]
[['父', 'ちち', None, None], [None, None, '：「', None], ['宿題', 'しゅくだい', None, None], [None, None, 'やったのか？」', None], ['息子', 'むすこ', None, None], [None, None, '：「やったよ〜。」', None], ['父', 'ちち', None, None], [None, None, '：「ふむ…', None], ['本当', 'ほんとう', None, None], [None, None, 'か？」', None], ['息子', 'むすこ', None, None], [None, None, '：「', None], ['本当', 'ほんとう', None, None], [None, None, 'だ', None], [None, None, 'ってば', True], [None, None, '！」', None]]

 88%|████████▊ | 823/938 [08:34<01:13,  1.56it/s]

[['記事', 'きじ', None, None], [None, None, '：「', None], ['植物', 'しょくぶつ', None, None], [None, None, 'は', None], ['動物', 'どうぶつ', None, None], [None, None, 'ならずとも', True], [None, None, 'ある', None], ['種', 'しゅ', None, None], [None, None, 'の', None], ['知覚', 'ちかく', None, None], ['表示', 'ひょうじ', None, None], [None, None, 'をしている。」', None]]
[[None, None, 'ゲーム', None], ['評論', 'ひょうろん', None, None], [None, None, '：「', None], ['ＲＰＧ', 'アールピージー', None, None], [None, None, 'ゲームファン', None], [None, None, 'ならずとも', True], [None, None, '、ウィッチャー ', None], ['３', 'スリー', None, None], [None, None, 'に', None], ['興味', 'きょうみ', None, None], [None, None, 'をひかれずにはいられません。」', None]]
[['記事', 'きじ', None, None], [None, None, '：「アメリカ人とイギリス人は', None], ['他', 'ほか', None, None], [None, None, 'の', None], ['言語', 'げんご', None, None], [None, None, 'を', None], ['学', 'まな', None, True], [None, None, 'ばずとも', True], ['生', 'い', None, None], [None, None, 'きられる', None], ['言語', 'げんご', None, None], ['環境', 'かんきょう', None, None], [None, None, 'に', None], ['居', 'い', None, None], [None, None, 'ます。」', None]]
[['時代小説', 'じだいしょうせつ', None, None], [None, None, '、', None], ['瀕死', 'ひんし', None, None], [None, None, 'の', None], ['親', 'おや', None, None], [None, None, '：「わたしの', None], ['身', 'み', None, None], [None, None, 'の', None], ['心配', 'しんぱい', None, None], [None, None, 'など', None], [None, None, 'せずとも', True], ['良', 'よ', None, None], [None, None, 'い', None], [None, None, '。', None], ['我', 'わ', None, None], [None, None, 'が', None], ['娘', 'むすめ', None, None], [None, None, 'よ。」', None]]
[['妹', 'いもうと', None, None], [None, None, '：「でも、どうやってわかった？」', None], ['兄', 'あに', None, None], [None, None, '：「', None], ['家族', 'かぞく', None, None], [None, None, 'だから', None], ['言', 'い', None, True], [None, None, 'わずとも', True], [None, None, 'わかる', None], [None, None, '。」', None]]

 88%|████████▊ | 824/938 [08:35<01:08,  1.67it/s]

[[None, None, 'いつもより', None], ['講演', 'こうえん', None, None], [None, None, 'の', None], ['参加者', 'さんかしゃ', None, None], [None, None, 'が', None], ['多', 'おお', None, None], [None, None, 'い', None], [None, None, 'とあって', True], [None, None, '、', None], ['発表者', 'はっぴょうしゃ', None, None], [None, None, 'はいつも', None], ['以上', 'いじょう', None, None], [None, None, 'にソワソワしています。', None]]
[[None, None, 'ニュースサイト', None], [None, None, '：「', None], ['日本', 'にほん', None, None], [None, None, 'で', None], ['初', 'はつ', None, None], ['上映', 'じょうえい', None, None], [None, None, 'とあって', True], [None, None, '、', None], ['大人', 'おとな', None, None], [None, None, 'から', None], ['子', 'こ', None, None], [None, None, 'どもまで', None], ['多', 'おお', None, None], [None, None, 'くの', None], ['人', 'ひと', None, None], [None, None, 'が', None], ['集', 'あつ', None, None], [None, None, 'まりました。」', None]]
[['記事', 'きじ', None, None], [None, None, '：「この', None], ['都市', 'とし', None, None], [None, None, 'で', None], ['唯一', 'ゆいいつ', None, None], [None, None, 'のイタリアンが', None], ['食', 'た', None, None], [None, None, 'べれるレストラン', None], [None, None, 'とあって', True], [None, None, '、', None], ['自然', 'しぜん', None, None], [None, None, 'と', None], ['大人気', 'だいにんき', None, None], [None, None, 'になった。」', None]]
[['今日', 'きょう', None, None], [None, None, 'はスーパーの', None], ['特売日', 'とくばいび', None, None], [None, None, 'とあって', True], [None, None, '、', None], ['開店', 'かいてん', None, None], [None, None, 'する', None], ['三十分', 'さんじゅっぷん', None, None], [None, None, 'も', None], ['前', 'まえ', None, None], [None, None, 'から', None], ['長蛇', 'ちょうだ', None, None], [None, None, 'の', None], ['列', 'れつ', None, None], [None, None, 'が', None], ['出来', 'でき', None, None], [None, None, 'ています。', None]]
[[None, None, 'ニュースサイト', None], [None, None, '：「 ', None], ['気軽', 'きがる', None, None], [None, None, 'に', None], ['鹿', 'しか', None, None], [None, None, 'などの', None], ['野生動物', 'やせいどうぶつ', None, None], [None, None, 'が', None], ['撮影', 'さつえい', None, None], [None, None, 'できる', None], [None, None, 'とあって', True], [None, None, '、', None], ['大変', 'たいへん', None, None], ['人気', 'にんき', None, None], [None, None, 'の', None], ['撮影', 'さつえい', None, None], [None, None, 'スポットの', None], ['一', 'ひと', None, None], [None, None, 'つになっています。」', None]]

 88%|████████▊ | 825/938 [08:35<01:03,  1.79it/s]

[[None, None, '「これは', None], ['偶然', 'ぐうぜん', None, None], [None, None, 'でもなんでもない', True], [None, None, 'んです、', None], ['起', 'お', None, None], [None, None, 'こるべくして', None], ['起', 'お', None, None], [None, None, 'こったんです。」', None]]
[['好', 'す', None, None], [None, None, 'き', None], [None, None, 'でもなんでもない', True], [None, None, 'クラスメイトと', None], ['付', 'つ', None, None], [None, None, 'き', None], ['合', 'あ', None, None], [None, None, 'っているという', None], ['噂', 'うわさ', None, None], [None, None, 'を', None], ['流', 'なが', None, None], [None, None, 'されてしまった。', None]]
[['彼氏', 'かれし', None, None], [None, None, 'が', None], ['誕生日', 'たんじょうび', None, None], [None, None, 'でもクリスマス', None], [None, None, 'でもなんでもない', True], [None, None, 'のにペアのネックレスをプレゼントしてくれました。', None]]
[[None, None, '「', None], ['彼', 'かれ', None, None], [None, None, 'は\u200e', None], ['全然', 'ぜんぜん', None, None], ['天才', 'てんさい', None, None], [None, None, 'でもなんでもない', True], [None, None, '。', None], ['人並', 'ひとな', None, None], [None, None, 'み', None], ['以上', 'いじょう', None, None], [None, None, 'の', None], ['努力', 'どりょく', None, None], [None, None, 'をしているから、あれだけの', None], ['結果', 'けっか', None, None], [None, None, 'を', None], ['残', 'のこ', None, None], [None, None, 'せるんだ。」', None]]
[['結婚式', 'けっこんしき', None, None], [None, None, 'の', None], ['前日', 'ぜんじつ', None, None], [None, None, 'に', None], ['私', 'わたし', None, None], [None, None, 'の', None], ['婚約者', 'こんやくしゃ', None, None], [None, None, 'と', None], ['寝', 'ね', None, None], [None, None, 'るなんて…あんなやつ、', None], ['家族', 'かぞく', None, None], [None, None, 'でもなんでもない', True], [None, None, 'わ。', None]]

 88%|████████▊ | 826/938 [08:36<01:00,  1.85it/s]

[[None, None, '「ともさん', None], [None, None, 'と', None], [None, None, 'は', None], ['家族', 'かぞく', None, None], [None, None, 'ぐるみの', True], ['付', 'つ', None, None], [None, None, 'き', None], ['合', 'あ', None, None], [None, None, 'い', None], [None, None, 'です', None], [None, None, '。」 ', None]]
[[None, None, '「', None], ['長年', 'ながねん', None, None], [None, None, '、', None], ['家族', 'かぞく', None, None], [None, None, 'ぐるみで', True], ['親', 'した', None, None], [None, None, 'しくしている', None], ['友達', 'ともだち', None, None], [None, None, 'だ', None], [None, None, 'よ', None], [None, None, '。」 ', None]]
[['組織', 'そしき', None, None], [None, None, 'ぐるみで', True], ['違法', 'いほう', None, None], [None, None, 'な', None], ['売春宿', 'ばいしゅんやど', None, None], [None, None, 'を', None], ['見逃', 'みのが', None, None], [None, None, 'していたと', None], ['知', 'し', None, None], [None, None, 'り、', None], ['組織', 'そしき', None, None], ['全体', 'ぜんたい', None, None], [None, None, 'に', None], ['深', 'ふか', None, None], [None, None, 'く', None], ['失望', 'しつぼう', None, None], [None, None, 'した。', None]]
[['学校', 'がっこう', None, None], [None, None, 'ぐるみで', True], [None, None, 'イジメを', None], ['隠蔽', 'いんぺい', None, None], [None, None, 'しようとした', None], ['結果', 'けっか', None, None], [None, None, '、', None], ['社会', 'しゃかい', None, None], [None, None, 'からさらなる', None], ['批判', 'ひはん', None, None], [None, None, 'を', None], ['浴', 'あ', None, None], [None, None, 'びる', None], ['事', 'こと', None, None], [None, None, 'になった。', None]]
[['国家', 'こっか', None, None], [None, None, 'ぐるみの', True], [None, None, 'ドーピングがばれ、その', None], ['国', 'くに', None, None], [None, None, 'の', None], ['選手', 'せんしゅ', None, None], [None, None, 'の', None], ['大会', 'たいかい', None, None], [None, None, 'への', None], ['出場', 'しゅつじょう', None, None], [None, None, 'は', None], ['禁止', 'きんし', None, None], [None, None, 'されました。', None]]

 88%|████████▊ | 827/938 [08:36<00:58,  1.88it/s]

[['自転車', 'じてんしゃ', None, None], [None, None, 'は', None], ['直', 'なお', None, None], [None, None, 'し', None], [None, None, 'た', None], [None, None, 'そばから', True], ['壊', 'こわ', None, None], [None, None, 'れ', None], [None, None, 'て', None], [None, None, 'しまう', None], [None, None, '。', None]]
[[None, None, 'あなたって', None], ['人', 'ひと', None, None], [None, None, 'は', None], [None, None, '、「やる', None], [None, None, 'な', None], [None, None, '」', None], [None, None, 'と', None], ['言', 'い', None, None], [None, None, 'っ', None], [None, None, 'た', None], [None, None, 'そばから', True], [None, None, 'やる', None], [None, None, 'んだ', None], [None, None, 'から', None], [None, None, '。', None]]
[['教', 'おそ', None, None], [None, None, 'わっ', None], [None, None, 'た', None], [None, None, 'そばから', True], ['同', 'おな', None, None], [None, None, 'じ', None], ['間違', 'まちが', None, None], [None, None, 'い', None], [None, None, 'を', None], [None, None, 'おかし', None], [None, None, 'た', None], [None, None, '。', None]]
[[None, None, 'ケーキ', None], [None, None, 'が', None], ['熱', 'あつ', None, None], [None, None, 'い', None], [None, None, 'から', None], ['触', 'さわ', None, None], [None, None, 'ら', None], [None, None, 'ない', None], [None, None, 'ように言っ', None], [None, None, 'た', None], [None, None, 'そばから', True], [None, None, ' こいつ', None], [None, None, 'は', None], [None, None, '～。', None]]
[['新人', 'しんじん', None, None], ['育成', 'いくせい', None, None], [None, None, 'が', None], [None, None, 'つらい。', None], ['彼', 'かれ', None, None], [None, None, 'ら', None], [None, None, 'は', None], ['言', 'い', None, None], [None, None, 'っ', None], [None, None, 'た', None], [None, None, 'そばから', True], [None, None, 'どんどん', None], ['忘', 'わす', None, None], [None, None, 'れ', None], [None, None, 'て', None], [None, None, 'しまう', None], [None, None, '。', None]]

 88%|████████▊ | 828/938 [08:37<01:04,  1.71it/s]

[['訳', 'わけ', None, True], [None, None, 'あり', True], [None, None, 'だのなんのって、つべこべうるさいんだよ！', None]]
[['数量限定', 'すうりょうげんてい', None, None], [None, None, 'の', None], ['訳', 'わけ', None, True], [None, None, 'あり', True], [None, None, 'アウトレット', None], ['品', 'ひん', None, None], [None, None, 'ですので、お', None], ['早', 'はや', None, None], [None, None, 'めにどうぞ。', None]]
[['私', 'わたし', None, None], [None, None, 'たちは、', None], ['訳', 'わけ', None, True], [None, None, 'あり', True], ['夫婦', 'ふうふ', None, None], [None, None, 'で', None], ['有名', 'ゆうめい', None, None], [None, None, 'だ。', None]]
[['訳', 'わけ', None, True], [None, None, 'あって', True], [None, None, '、', None], ['明日', 'あした', None, None], [None, None, 'から', None], ['海外', 'かいがい', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'きます。', None]]
[[None, None, '「', None], ['実', 'じつ', None, None], [None, None, 'は', None], ['今日', 'きょう', None, None], [None, None, 'デートに', None], ['行', 'い', None, None], [None, None, 'けなかったの、ちょっと', None], ['訳', 'わけ', None, True], [None, None, 'あり', True], [None, None, 'でね……ごめん。」', None]]

 88%|████████▊ | 829/938 [08:38<01:01,  1.78it/s]

[['過労', 'かろう', None, None], [None, None, 'で', None], ['意識', 'いしき', None, None], [None, None, 'を', None], ['失', 'うしな', None, None], [None, None, 'う', None], [None, None, 'に', True], ['至', 'いた', None, True], [None, None, 'って', True], [None, None, '、ようやく', None], ['働', 'はたら', None, None], [None, None, 'きすぎたことがわかった。', None]]
[['私', 'わたし', None, None], [None, None, 'の', None], ['祖父', 'そふ', None, None], [None, None, 'は', None], ['肺', 'はい', None, None], ['不全', 'ふぜん', None, None], [None, None, 'に', True], ['至', 'いた', None, True], [None, None, 'って', True], [None, None, '、いよいよタバコを', None], ['止', 'や', None, None], [None, None, 'めざるをえないことを', None], ['認', 'みと', None, None], [None, None, 'めた。', None]]
[['手', 'て', None, None], [None, None, 'に', None], ['負', 'お', None, None], [None, None, 'えなくなったこの', None], ['段階', 'だんかい', None, None], [None, None, 'に', True], ['至', 'いた', None, True], [None, None, 'って', True], [None, None, 'ようやく', None], ['緊急', 'きんきゅう', None, None], ['事態', 'じたい', None, None], [None, None, 'を', None], ['宣言', 'せんげん', None, None], [None, None, 'しました。', None]]
[['訴', 'うった', None, None], [None, None, 'えられる', None], ['事', 'こと', None, None], [None, None, 'が', None], ['決', 'き', None, None], [None, None, 'まる', None], [None, None, 'に', True], ['至', 'いた', None, True], [None, None, 'って', True], [None, None, 'ようやく、', None], ['彼', 'かれ', None, None], [None, None, 'は', None], ['自分', 'じぶん', None, None], [None, None, 'が', None], ['何', 'なに', None, None], [None, None, 'をしたか', None], ['気', 'き', None, None], [None, None, 'づいたようだ。', None]]
[[None, None, ' ', None], ['記事', 'きじ', None, None], [None, None, '：「', None], ['何', 'なん', None, None], ['千', 'ぜん', None, None], [None, None, 'ものバナナの', None], ['木', 'き', None, None], [None, None, 'が', None], ['枯', 'か', None, None], [None, None, 'れる', None], [None, None, 'に', True], ['至', 'いた', None, True], [None, None, 'って', True], [None, None, '、バナナ', None], ['産業', 'さんぎょう', None, None], [None, None, 'は', None], ['初', 'はじ', None, None], [None, None, 'めてパナマ', None], ['病', 'びょう', None, None], [None, None, 'の', None], ['深刻', 'しんこく', None, None], [None, None, 'さに', None], ['気', 'き', None, None], [None, None, 'が', None], ['付', 'つ', None, None], [None, None, 'いた。」', None]]

 88%|████████▊ | 830/938 [08:38<01:04,  1.66it/s]

[[None, None, 'そのカメレオンは', None], ['外敵', 'がいてき', None, None], [None, None, 'から', None], ['身', 'み', None, None], [None, None, 'を', None], ['隠', 'かく', None, None], [None, None, 'すために', None], ['微動', 'びどう', None, None], [None, None, 'だに', True], [None, None, 'していません', None], [None, None, '。', None]]
[[None, None, ' ', None], [None, None, 'アニメのプロローグ、', None], ['語', 'かた', None, None], [None, None, 'り', None], ['手', 'て', None, None], [None, None, '：「あのとき、', None], ['俺', 'おれ', None, None], [None, None, 'はあんな', None], ['悲劇', 'ひげき', None, None], [None, None, 'が', None], ['待', 'ま', None, None], [None, None, 'ち', None], ['受', 'う', None, None], [None, None, 'けていたなんて、', None], ['夢', 'ゆめ', None, None], [None, None, 'にだに', True], ['思', 'おも', None, None], [None, None, 'わなかった', None], [None, None, '。」', None]]
[[None, None, ' ', None], ['小説', 'しょうせつ', None, None], [None, None, '：「', None], ['彼女', 'かのじょ', None, None], [None, None, 'はソファーに', None], ['座', 'すわ', None, None], [None, None, 'ったままで、まるで', None], ['本物', 'ほんもの', None, None], [None, None, 'の', None], ['人形', 'にんぎょう', None, None], [None, None, 'のように', None], ['微動', 'びどう', None, None], [None, None, 'だに', True], [None, None, 'しない', None], [None, None, '。」', None]]
[[None, None, ' ', None], ['記事', 'きじ', None, None], [None, None, '：「ビットコインがこれほどになるとは', None], ['２００９', 'にせんきゅう', None, None], ['年', 'ねん', None, None], ['始', 'はじ', None, None], [None, None, 'めには', None], ['誰', 'だれ', None, None], [None, None, 'も', None], ['予想', 'よそう', None, None], [None, None, 'だに', True], [None, None, 'しなかった', None], [None, None, '。」', None]]
[[None, None, ' ', None], ['小説', 'しょうせつ', None, None], [None, None, '：「', None], ['彼', 'かれ', None, None], [None, None, 'が', None], ['心', 'こころ', None, None], [None, None, 'の', None], ['中', 'なか', None, None], [None, None, 'にこんな', None], ['暗闇', 'くらやみ', None, None], [None, None, 'を', None], ['抱', 'かか', None, None], [None, None, 'えていたなど、', None], ['勇者', 'ゆうしゃ', None, None], [None, None, 'は', None], ['夢想', 'むそう', None, None], [None, None, 'だに', True], [None, None, 'しなかった', None], [None, None, '。」', None]]

 89%|████████▊ | 831/938 [08:39<01:01,  1.73it/s]

[[None, None, '「', None], ['帰', 'かえ', None, None], [None, None, 'り', None], [None, None, 'がてら', True], ['手紙', 'てがみ', None, None], ['出', 'だ', None, None], [None, None, 'してくるね。」', None]]
[[None, None, '「イノシシの', None], ['散歩', 'さんぽ', None, None], [None, None, 'がてら', True], [None, None, '、ちょっとコンビニまで', None], ['行', 'い', None, None], [None, None, 'ってきます。」', None]]
[[None, None, '「お', None], ['花見', 'はなみ', None, None], [None, None, 'がてら', True], [None, None, '、', None], ['公園', 'こうえん', None, None], [None, None, 'を', None], ['散歩', 'さんぽ', None, None], [None, None, 'しよう。」', None]]
[[None, None, ' ', None], ['回顧録', 'かいころく', None, None], [None, None, '：「ヒースロー', None], ['空港', 'くうこう', None, None], [None, None, 'への', None], ['移動', 'いどう', None, None], [None, None, 'がてら', True], [None, None, '、', None], ['観光', 'かんこう', None, None], [None, None, 'スポットを', None], ['訪', 'おとず', None, None], [None, None, 'れた。」', None]]
[[None, None, ' ', None], ['友達', 'ともだち', None, None], [None, None, 'との', None], ['話', 'はなし', None, None], [None, None, '：「じゃあ', None], ['買', 'か', None, None], [None, None, 'い', None], ['物', 'もの', None, None], [None, None, 'がてら', True], [None, None, '、', None], ['紅葉', 'こうよう', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'かないか？」', None]]

 89%|████████▊ | 832/938 [08:39<01:05,  1.63it/s]

[[None, None, ' ', None], [None, None, 'ソクラテス', None], [None, None, '：「', None], ['生', 'い', None, None], [None, None, 'き', None], [None, None, 'んがために', True], ['食', 'く', None, None], [None, None, 'え、', None], ['食', 'く', None, None], [None, None, 'わ', None], [None, None, 'んがために', True], ['生', 'い', None, None], [None, None, 'きるな」', None]]
[[None, None, ' ', None], ['小説', 'しょうせつ', None, None], [None, None, '：「', None], ['力', 'ちから', None, None], [None, None, 'の', None], ['指輪', 'ゆびわ', None, None], [None, None, 'を', None], ['得', 'え', None, True], [None, None, 'んがための', True], ['戦争', 'せんそう', None, None], [None, None, 'が', None], ['始', 'はじ', None, None], [None, None, 'まった。」', None]]
[['溺', 'おぼ', None, None], [None, None, 'れている', None], ['子供', 'こども', None, None], [None, None, 'を', None], ['助', 'たす', None, True], [None, None, 'けんがために', True], ['川', 'かわ', None, None], [None, None, 'に', None], ['飛', 'と', None, None], [None, None, 'び', None], ['込', 'こ', None, None], [None, None, 'んだ', None], ['人', 'ひと', None, None], [None, None, 'が', None], ['亡', 'な', None, None], [None, None, 'くなってしまったそうです。', None]]
[['僕', 'ぼく', None, None], [None, None, 'はこの', None], ['世', 'よ', None, None], [None, None, 'に', None], ['何', 'なに', None, None], [None, None, 'かを', None], ['為', 'な', None, True], [None, None, 'さんがために', True], ['生', 'う', None, None], [None, None, 'まれてきたはずだが、それが', None], ['何', 'なに', None, None], [None, None, 'かはまだ', None], ['分', 'わ', None, None], [None, None, 'からない。', None]]
[[None, None, ' ', None], ['記事', 'きじ', None, None], [None, None, '：「その', None], ['会社', 'かいしゃ', None, None], [None, None, 'は', None], ['不', 'ふ', None, None], ['良品', 'りょうひん', None, None], [None, None, 'を', None], ['売', 'う', None, True], [None, None, 'らんがために', True], [None, None, '、', None], ['高齢者', 'こうれいしゃ', None, None], [None, None, 'の', None], ['弱', 'よわ', None, None], [None, None, 'みにつけ', None], ['込', 'こ', None, None], [None, None, 'んだ。」', None]]

 89%|████████▉ | 833/938 [08:40<01:00,  1.72it/s]

[['結果', 'けっか', None, None], ['如何', 'いかん', None, True], [None, None, 'を', True], ['問', 'と', None, True], [None, None, 'わず', True], [None, None, '、この', None], ['学校', 'がっこう', None, None], [None, None, 'では', None], ['努力', 'どりょく', None, None], [None, None, 'をした', None], ['生徒', 'せいと', None, None], [None, None, 'を', None], ['褒', 'ほ', None, None], [None, None, 'めるようにしています。', None]]
[[None, None, 'テストの', None], ['形式', 'けいしき', None, None], ['如何', 'いかん', None, True], [None, None, 'を', True], ['問', 'と', None, True], [None, None, 'わず', True], ['自分', 'じぶん', None, None], [None, None, 'の', None], ['力', 'ちから', None, None], [None, None, 'を', None], ['最大限', 'さいだいげん', None, None], ['出', 'だ', None, None], [None, None, 'せるように', None], ['勉強', 'べんきょう', None, None], [None, None, 'しよう。', None]]
[[None, None, 'これまでの', None], ['経歴', 'けいれき', None, None], ['如何', 'いかん', None, True], [None, None, 'を', True], ['問', 'と', None, True], [None, None, 'わず', True], [None, None, '、', None], ['我', 'わ', None, None], [None, None, 'が', None], ['社', 'しゃ', None, None], [None, None, 'は', None], ['多様', 'たよう', None, None], [None, None, 'な', None], ['人材', 'じんざい', None, None], [None, None, 'を', None], ['受', 'う', None, None], [None, None, 'け', None], ['入', 'い', None, None], [None, None, 'れる', None], ['方針', 'ほうしん', None, None], [None, None, 'だ。', None]]
[['僕', 'ぼく', None, None], [None, None, 'は', None], ['勝敗', 'しょうはい', None, None], ['如何', 'いかん', None, True], [None, None, 'を', True], ['問', 'と', None, True], [None, None, 'わず', True], [None, None, '、', None], ['全力', 'ぜんりょく', None, None], [None, None, 'でプレーした', None], ['息子', 'むすこ', None, None], [None, None, 'を', None], ['褒', 'ほ', None, None], [None, None, 'め', None], ['称', 'たた', None, None], [None, None, 'えるつもりです。', None]]
[['発信', 'はっしん', None, None], [None, None, 'する', None], ['内容', 'ないよう', None, None], [None, None, 'の', True], ['如何', 'いかん', None, True], [None, None, 'を', True], ['問', 'と', None, True], [None, None, 'わず', True], [None, None, '、', None], ['私', 'わたし', None, None], [None, None, 'たちは', None], ['自由', 'じゆう', None, None], [None, None, 'に', None], ['発言', 'はつげん', None, None], [None, None, 'する', None], ['権利', 'けんり', None, None], [None, None, 'を', None], ['与', 'あた', None, None], [None, None, 'えられるべきだ。', None]]

 89%|████████▉ | 834/938 [08:40<00:57,  1.79it/s]

[['亡', 'な', None, None], [None, None, 'き', None], ['妻', 'つま', None, None], [None, None, 'の', None], ['笑顔', 'えがお', None, None], [None, None, 'は', None], ['忘', 'わす', None, True], [None, None, 'れようにも', True], ['忘', 'わす', None, None], [None, None, 'れられ', None], [None, None, 'ない', None], [None, None, '。', None]]
[[None, None, 'プロジェクトについて', None], ['心配', 'しんぱい', None, None], [None, None, 'するあまり、', None], ['寝', 'ね', None, True], [None, None, 'ようにも', True], ['寝', 'ね', None, None], [None, None, 'られ', None], [None, None, 'ない', None], [None, None, '。', None]]
[['車', 'くるま', None, None], [None, None, 'がないのなら、', None], ['運転', 'うんてん', None, None], [None, None, 'しようにも', True], ['運転', 'うんてん', None, None], [None, None, 'でき', None], [None, None, 'ない', None], [None, None, 'でしょう？', None]]
[['風邪', 'かぜ', None, None], [None, None, 'をひいて', None], ['喉', 'のど', None, None], [None, None, 'が', None], ['痛', 'いた', None, None], [None, None, 'すぎて、', None], ['返事', 'へんじ', None, None], [None, None, 'を', None], [None, None, 'しようにも', True], ['出来', 'でき', None, None], [None, None, 'ません', None], [None, None, '。', None]]
[[None, None, 'テーマパークには', None], ['行', 'い', None, None], [None, None, 'きたいですが、', None], ['骨折', 'こっせつ', None, None], [None, None, 'をしていて', None], ['歩', 'ある', None, True], [None, None, 'こうにも', True], ['歩', 'ある', None, None], [None, None, 'け', None], [None, None, 'ない', None], [None, None, 'のです。', None]]

 89%|████████▉ | 835/938 [08:41<01:00,  1.71it/s]

[[None, None, '「', None], ['噂', 'うわさ', None, None], [None, None, 'なんて', None], ['全然', 'ぜんぜん', None, None], ['知', 'し', None, True], [None, None, 'りたくもなんともない', True], [None, None, 'けど。」', None]]
[[None, None, '「もうやめない？その', None], ['話', 'はなし', None, None], [None, None, '。', None], ['面白', 'おもしろ', None, True], [None, None, 'くもなんともない', True], [None, None, 'から！」', None]]
[[None, None, 'この', None], ['料理', 'りょうり', None, None], [None, None, 'は', None], ['美味', 'おい', None, True], [None, None, 'しくもなんともない', True], [None, None, 'から、', None], ['感想', 'かんそう', None, None], [None, None, 'は', None], ['何', 'なに', None, None], [None, None, 'もない。', None]]
[['悲', 'かな', None, True], [None, None, 'しくもなんともない', True], [None, None, 'のに', None], ['急', 'きゅう', None, None], [None, None, 'に', None], ['涙', 'なみだ', None, None], [None, None, 'が', None], ['出', 'で', None, None], [None, None, 'てきて', None], ['混乱', 'こんらん', None, None], [None, None, 'しています。', None]]
[['見', 'み', None, True], [None, None, 'たくもなんともない', True], [None, None, 'テレビ', None], ['番組', 'ばんぐみ', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'たら、', None], ['予想通', 'よそうどお', None, None], [None, None, 'りつまらなかった。', None]]

 89%|████████▉ | 836/938 [08:42<01:14,  1.38it/s]

[[None, None, ' ', None], ['記事', 'きじ', None, None], [None, None, '：「', None], ['人間', 'にんげん', None, None], [None, None, 'にとってはダニを', None], ['食', 'た', None, None], [None, None, 'べるのは', None], ['考', 'かんが', None, None], [None, None, 'える', None], [None, None, 'だに', True], [None, None, 'おぞましい。」', None]]
[[None, None, ' ', None], ['小説', 'しょうせつ', None, None], [None, None, '：「クトゥルフは', None], ['見', 'み', None, None], [None, None, 'る', None], [None, None, 'だに', True], ['正気', 'しょうき', None, None], [None, None, 'を', None], ['失', 'うしな', None, None], [None, None, 'ってしまうほどたいへん', None], ['恐', 'おそ', None, None], [None, None, 'ろしい', None], ['化物', 'ばけもの', None, None], [None, None, 'であるらしい。」', None]]
[[None, None, ' ', None], ['記事', 'きじ', None, None], [None, None, '：「その', None], ['映画', 'えいが', None, None], [None, None, 'のワンシーンを', None], ['思', 'おも', None, None], [None, None, 'い', None], ['出', 'だ', None, None], [None, None, 'す', None], [None, None, 'だに', True], [None, None, '、', None], ['胸', 'むね', None, None], [None, None, 'が', None], ['痛', 'いた', None, None], [None, None, 'くなります。」', None]]
[[None, None, ' ', None], ['小説', 'しょうせつ', None, None], [None, None, '：「ただ、その', None], ['事故', 'じこ', None, None], [None, None, 'の', None], ['話', 'はなし', None, None], [None, None, 'を', None], ['聞', 'き', None, None], [None, None, 'く', None], [None, None, 'だに', True], ['古傷', 'ふるきず', None, None], [None, None, 'が', None], ['疼', 'うず', None, None], [None, None, 'く。」', None]]
[[None, None, ' ', None], ['記事', 'きじ', None, None], [None, None, '：「', None], ['太陽', 'たいよう', None, None], [None, None, 'の', None], ['中心', 'ちゅうしん', None, None], [None, None, 'の', None], ['温度', 'おんど', None, None], [None, None, 'は', None], ['想像', 'そうぞう', None, None], [None, None, 'する', None], [None, None, 'だに', True], ['恐', 'おそ', None, None], [None, None, 'ろしい。」', None]]

 89%|████████▉ | 837/938 [08:43<01:07,  1.49it/s]

[[None, None, 'ヨーロッパなら、フランス', None], [None, None, 'なり', True], [None, None, 'イタリア', None], [None, None, 'なり', True], [None, None, '、', None], ['料理', 'りょうり', None, None], [None, None, 'が', None], ['美味', 'おい', None, None], [None, None, 'しいところに', None], ['行', 'い', None, None], [None, None, 'きたい。', None]]
[['完璧', 'かんぺき', None, None], [None, None, 'な', None], ['人', 'ひと', None, None], [None, None, 'はいない。', None], ['大', 'だい', None, None], [None, None, 'なり', True], ['小', 'しょう', None, None], [None, None, 'なり', True], ['欠点', 'けってん', None, None], [None, None, 'はあるものだ。', None]]
[[None, None, 'ご', None], ['飯', 'はん', None, None], [None, None, 'にする', None], [None, None, 'なり', True], ['運動', 'うんどう', None, None], [None, None, 'する', None], [None, None, 'なり', True], ['好', 'す', None, None], [None, None, 'きにすればいいけど、', None], ['早', 'はや', None, None], [None, None, 'く', None], ['寝', 'ね', None, None], [None, None, 'なさいよ。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'が', None], ['彼氏', 'かれし', None, None], [None, None, 'に：', None], [None, None, '「', None], ['電話', 'でんわ', None, None], [None, None, 'なり', True], ['何', 'なん', None, None], [None, None, 'なり', True], [None, None, 'で、', None], ['早', 'はや', None, None], [None, None, 'く', None], ['連絡', 'れんらく', None, None], [None, None, 'しなさいよ。」', None]]
[[None, None, ' ', None], [None, None, 'お', None], ['母', 'かあ', None, None], [None, None, 'さん', None], [None, None, '：「', None], ['私', 'わたし', None, None], [None, None, 'じゃなくて、お', None], ['姉', 'ねえ', None, None], [None, None, 'ちゃん', None], [None, None, 'なり', True], [None, None, 'お', None], ['兄', 'にい', None, None], [None, None, 'ちゃん', None], [None, None, 'なり', True], [None, None, 'に', None], ['質問', 'しつもん', None, None], [None, None, 'して！」', None]]

 89%|████████▉ | 838/938 [08:43<01:01,  1.63it/s]

[[None, None, 'あなたの', None], ['考', 'かんが', None, None], [None, None, 'えが', None], ['分', 'わ', None, True], [None, None, 'からないでもない', True], [None, None, 'けど、', None], ['反対', 'はんたい', None, None], [None, None, 'するね。', None]]
[[None, None, 'パクチーは', None], ['食', 'た', None, True], [None, None, 'べられないでもない', True], [None, None, 'けどさ、', None], ['食', 'た', None, None], [None, None, 'べるとウッてなるんだよ。', None]]
[[None, None, 'この', None], ['洋服', 'ようふく', None, None], [None, None, '、', None], ['着', 'き', None, True], [None, None, 'られないでもない', True], [None, None, 'けど、やっぱりキツイなぁ〜。', None]]
[[None, None, 'トイレに', None], ['行', 'い', None, None], [None, None, 'きたい', None], ['気', 'き', None, None], [None, None, 'が', None], [None, None, 'しないでもない', True], [None, None, 'けど、まだ', None], ['並', 'なら', None, None], [None, None, 'ばなくてもいいかな…。', None]]
[[None, None, 'このブランドのあのバッグは', None], ['１０', 'じゅう', None, None], ['万円', 'まんえん', None, None], [None, None, '？！', None], ['買', 'か', None, True], [None, None, 'えないでもない', True], [None, None, 'けど、', None], ['勇気', 'ゆうき', None, None], [None, None, 'が', None], ['出', 'で', None, None], [None, None, 'ないなぁ〜。', None]]

 89%|████████▉ | 839/938 [08:44<00:57,  1.73it/s]

[[None, None, 'モナ・リザは', None], ['美', 'うつく', None, None], [None, None, 'しい', None], ['画', 'え', None, None], [None, None, 'もさることながら', True], [None, None, '、やはり', None], ['目', 'め', None, None], [None, None, 'を', None], ['引', 'ひ', None, None], [None, None, 'くのは', None], ['神秘的', 'しんぴてき', None, None], [None, None, 'な', None], ['微笑', 'びしょう', None, None], [None, None, 'である。', None]]
[['日頃', 'ひごろ', None, None], [None, None, 'の', None], ['心', 'こころ', None, None], [None, None, 'がけ', None], [None, None, 'もさることながら', True], [None, None, '、', None], ['今回', 'こんかい', None, None], [None, None, 'は', None], ['運', 'うん', None, None], [None, None, 'が', None], ['味方', 'みかた', None, None], [None, None, 'してくれたようだ。', None]]
[['見', 'み', None, None], [None, None, 'た', None], ['目', 'め', None, None], [None, None, 'もさることながら', True], ['性格', 'せいかく', None, None], [None, None, 'も', None], ['素晴', 'すば', None, None], [None, None, 'らしい', None], ['彼', 'かれ', None, None], [None, None, 'がモテるのは', None], ['当然', 'とうぜん', None, None], [None, None, 'のことです。', None]]
[['歌詞', 'かし', None, None], [None, None, 'もさることながら', True], [None, None, 'メロディーもいいのだから、この', None], ['曲', 'きょく', None, None], [None, None, 'はやっぱり', None], ['最高', 'さいこう', None, None], [None, None, 'だ。', None]]
[['美味', 'おい', None, None], [None, None, 'しさ', None], [None, None, 'もさることながら', True], ['見', 'み', None, None], [None, None, 'た', None], ['目', 'め', None, None], [None, None, 'も', None], ['凄', 'すご', None, None], [None, None, 'いこのフレンチレストランは、', None], ['大人気', 'だいにんき', None, None], [None, None, 'です。', None]]

 90%|████████▉ | 840/938 [08:44<01:00,  1.61it/s]

[[None, None, 'てっきり', None], ['漢字', 'かんじ', None, None], [None, None, 'を', None], ['学', 'まな', None, None], [None, None, 'ぶのは', None], ['退屈', 'たいくつ', None, None], [None, None, 'なものと', True], ['思', 'おも', None, True], [None, None, 'っていた', True], [None, None, '。', None]]
[['犬', 'いぬ', None, None], [None, None, 'は', None], ['怖', 'こわ', None, None], [None, None, 'い', None], [None, None, 'ものと', True], ['思', 'おも', None, True], [None, None, 'っていた', True], [None, None, 'けど、', None], ['飼', 'か', None, None], [None, None, 'ってみたら', None], ['思', 'おも', None, None], [None, None, 'ったより', None], ['優', 'やさ', None, None], [None, None, 'しかった。', None]]
[[None, None, 'お', None], ['母', 'かあ', None, None], [None, None, 'さんに', None], ['怒', 'おこ', None, None], [None, None, 'られる', None], [None, None, 'ものと', True], ['思', 'おも', None, True], [None, None, 'っていた', True], [None, None, 'が', None], ['怒', 'おこ', None, None], [None, None, 'られず、', None], ['拍子抜', 'ひょうしぬ', None, None], [None, None, 'けした。', None]]
[['子供', 'こども', None, None], [None, None, 'の', None], ['頃', 'ころ', None, None], [None, None, '、', None], ['森', 'もり', None, None], [None, None, 'の', None], ['中', 'なか', None, None], [None, None, 'で', None], ['迷', 'まよ', None, None], [None, None, 'った。てっきりこのまま', None], ['死', 'し', None, None], [None, None, 'ぬ', None], [None, None, 'ものと', True], ['思', 'おも', None, True], [None, None, 'っていた', True], [None, None, '。（が', None], ['救', 'すく', None, None], [None, None, 'われた）', None]]
[['面接', 'めんせつ', None, None], [None, None, 'に', None], ['合格', 'ごうかく', None, None], [None, None, 'する', None], [None, None, 'ものと', True], ['思', 'おも', None, True], [None, None, 'っていた', True], [None, None, 'が', None], ['不合格', 'ふごうかく', None, None], [None, None, 'となり、', None], ['愕然', 'がくぜん', None, None], [None, None, 'としている。', None]]

 90%|████████▉ | 841/938 [08:45<00:56,  1.72it/s]

[['注射', 'ちゅうしゃ', None, None], [None, None, 'を', None], ['打', 'う', None, None], [None, None, 'った', None], ['後', 'あと', None, None], [None, None, 'にすぐ', None], ['亡', 'な', None, None], [None, None, 'くなった…これがワクチンのせい', None], [None, None, 'でなくてなんだろう', True], [None, None, '。', None]]
[['勉強', 'べんきょう', None, None], [None, None, 'しなかったのにテストで', None], ['１００', 'ひゃく', None, None], ['点', 'てん', None, None], [None, None, 'をとるとは！', None], ['天才', 'てんさい', None, None], [None, None, 'でなくてなんだろう', True], [None, None, '！', None]]
[[None, None, 'まさか', None], ['扉', 'とびら', None, None], [None, None, 'が', None], ['勝手', 'かって', None, None], [None, None, 'に', None], ['開', 'ひら', None, None], [None, None, 'くとは…これが', None], ['心霊', 'しんれい', None, None], ['現象', 'げんしょう', None, None], [None, None, 'でなくてなんだろうか', True], [None, None, '。', None]]
[[None, None, 'ずっと', None], ['一緒', 'いっしょ', None, None], [None, None, 'に', None], ['寄', 'よ', None, None], [None, None, 'り', None], ['添', 'そ', None, None], [None, None, 'いたいと', None], ['思', 'おも', None, None], [None, None, 'うこの', None], ['気持', 'きも', None, None], [None, None, 'ちが', None], ['愛', 'あい', None, None], [None, None, 'でなくてなんだろう', True], [None, None, '。', None]]
[['頼', 'たよ', None, None], [None, None, 'れる', None], ['家族', 'かぞく', None, None], [None, None, 'がいて', None], ['仲', 'なか', None, None], [None, None, 'のいい', None], ['友達', 'ともだち', None, None], [None, None, 'がいて', None], ['愛', 'あい', None, None], [None, None, 'する', None], ['恋人', 'こいびと', None, None], [None, None, 'がいて…これが', None], ['幸', 'しあわ', None, None], [None, None, 'せ', None], [None, None, 'でなくてなんだろう', True], [None, None, '。', None]]

 90%|████████▉ | 842/938 [08:45<00:53,  1.78it/s]

[[None, None, 'それ', None], [None, None, 'はさておき', True], [None, None, '、', None], ['会議', 'かいぎ', None, None], [None, None, 'の', None], ['本題', 'ほんだい', None, None], [None, None, 'に', None], ['移', 'うつ', None, None], [None, None, 'りましょう。', None]]
[['冗談', 'じょうだん', None, None], [None, None, 'はさておき', True], [None, None, '、そろそろ', None], ['真面目', 'まじめ', None, None], [None, None, 'にミーティングをしないと。', None]]
[[None, None, 'この', None], ['映画', 'えいが', None, None], [None, None, 'は', None], ['内容', 'ないよう', None, None], [None, None, 'はさておき', True], [None, None, '、', None], ['映像', 'えいぞう', None, None], [None, None, 'のクオリティは', None], ['最高', 'さいこう', None, None], [None, None, 'でした。', None]]
[['品質', 'ひんしつ', None, None], [None, None, 'はさておき', True], [None, None, '、この', None], ['商品', 'しょうひん', None, None], [None, None, 'のデザインはどこよりも', None], ['優', 'すぐ', None, None], [None, None, 'れています。', None]]
[['目', 'め', None, None], [None, None, 'が', None], ['悪', 'わる', None, None], [None, None, 'いこと', None], [None, None, 'はさておき', True], [None, None, '、それ', None], ['以外', 'いがい', None, None], [None, None, 'は', None], ['僕', 'ぼく', None, None], [None, None, 'の', None], ['体', 'からだ', None, None], [None, None, 'は', None], ['完璧', 'かんぺき', None, None], [None, None, 'だと', None], ['言', 'い', None, None], [None, None, 'ってもいい。', None]]

 90%|████████▉ | 843/938 [08:46<00:55,  1.71it/s]

[[None, None, ' ', None], [None, None, 'メール、', None], ['本社', 'ほんしゃ', None, None], [None, None, 'の', None], ['上司', 'じょうし', None, None], [None, None, 'に', None], [None, None, '：「お', None], ['暇', 'ひま', None, None], [None, None, 'な', True], ['折', 'おり', None, True], [None, None, 'に', True], [None, None, 'ぜひ', None], ['我', 'わ', None, None], [None, None, 'が', None], ['支店', 'してん', None, None], [None, None, 'にお', None], ['越', 'こ', None, None], [None, None, 'しください。」', None]]
[[None, None, ' ', None], ['手紙', 'てがみ', None, None], [None, None, '：「', None], ['新春', 'しんしゅん', None, None], [None, None, 'のお', None], ['支度', 'したく', None, None], [None, None, 'にお', None], ['忙', 'いそが', None, None], [None, None, 'しい', None], ['折', 'おり', None, True], [None, None, 'から、', None], ['風邪', 'かぜ', None, None], [None, None, 'などひかれぬようご', None], ['自愛', 'じあい', None, None], ['下', 'くだ', None, None], [None, None, 'さい。」', None]]
[[None, None, 'お', None], ['近', 'ちか', None, None], [None, None, 'くにいらっしゃる', None], ['折', 'おり', None, True], [None, None, 'には', True], [None, None, '、ぜひうちにご', None], ['飯', 'はん', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べに', None], ['来', 'き', None, None], [None, None, 'てください！', None]]
[['宴会', 'えんかい', None, None], [None, None, 'をする', None], ['折', 'おり', None, True], [None, None, 'には', True], [None, None, '、ぜひうちの', None], ['居酒屋', 'いざかや', None, None], [None, None, 'をご', None], ['利用', 'りよう', None, None], [None, None, 'くださいませ！', None]]
[[None, None, 'オーストラリアへ', None], ['来', 'く', None, None], [None, None, 'る', None], ['折', 'おり', None, True], [None, None, 'には', True], [None, None, '、ぜひカンガルーのお', None], ['肉', 'にく', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べてみてください。', None]]

 90%|████████▉ | 844/938 [08:47<00:52,  1.78it/s]

[[None, None, 'ランナーが', None], ['通', 'とお', None, None], [None, None, 'り、', None], [None, None, 'ここ', None], [None, None, 'ぞ', None], [None, None, 'とばかりに', True], ['声援', 'せいえん', None, None], [None, None, 'を', None], ['送', 'おく', None, None], [None, None, 'りました。', None]]
[[None, None, '「おまえ', None], [None, None, 'も', None], ['黙', 'だま', None, None], [None, None, 'れ」', None], [None, None, 'とばかりに', True], ['手', 'て', None, None], [None, None, 'で', None], [None, None, 'テーブル', None], [None, None, 'を', None], ['叩', 'たた', None, None], [None, None, 'い', None], [None, None, 'た', None], [None, None, '。', None]]
[['盗賊', 'とうぞく', None, None], [None, None, 'たちが', None], ['待', 'ま', None, None], [None, None, 'っていた', None], [None, None, 'とばかりに', True], ['通行人', 'つうこうにん', None, None], [None, None, 'を', None], ['止', 'と', None, None], [None, None, 'めたのです！', None]]
[['桜', 'さくら', None, None], [None, None, 'は、', None], ['今', 'いま', None, None], [None, None, 'この', None], ['時', 'とき', None, None], [None, None, 'を', None], ['待', 'ま', None, None], [None, None, 'っていた', None], [None, None, 'とばかりに', True], ['花', 'はな', None, None], [None, None, 'びらを', None], ['広', 'ひろ', None, None], [None, None, 'げています。', None]]
[['社長', 'しゃちょう', None, None], [None, None, 'に', None], ['呆', 'あき', None, None], [None, None, 'れた', None], [None, None, 'とばかりに', True], [None, None, 'ため', None], ['息', 'いき', None, None], [None, None, 'をつかれて、クビを', None], ['覚悟', 'かくご', None, None], [None, None, 'しました。', None]]

 90%|█████████ | 845/938 [08:47<00:56,  1.65it/s]

[[None, None, '「', None], ['病院', 'びょういん', None, None], [None, None, 'に', None], ['入院', 'にゅういん', None, None], [None, None, 'し', None], [None, None, 'てた', None], ['時', 'とき', None, None], [None, None, '、いろいろ', None], ['検査', 'けんさ', None, None], [None, None, 'し', None], [None, None, 'たら', None], [None, None, 'まあ、', None], ['出', 'で', None, None], [None, None, 'る', None], [None, None, 'わ', True], ['出', 'で', None, None], [None, None, 'る', None], [None, None, 'わ', True], [None, None, '…（', None], ['思', 'おも', None, None], [None, None, 'った', None], ['以上', 'いじょう', None, None], [None, None, 'の', None], [None, None, 'こと', None], [None, None, 'が', None], ['指摘', 'してき', None, None], [None, None, 'され', None], [None, None, 'た', None], [None, None, '）。」', None]]
[[None, None, '「', None], ['新婚', 'しんこん', None, None], ['旅行', 'りょこう', None, None], [None, None, 'から', None], ['戻', 'もど', None, None], [None, None, 'っ', None], [None, None, 'たら', None], [None, None, 'メールボックス', None], [None, None, 'に', None], [None, None, 'は', None], ['郵便物', 'ゆうびんぶつ', None, None], [None, None, 'がある', None], [None, None, 'わ', True], [None, None, 'ある', None], [None, None, 'わ', True], [None, None, '、つかえ', None], [None, None, 'てしま', None], [None, None, 'って', None], ['引', 'ひ', None, None], [None, None, 'っ', None], ['張', 'ぱ', None, None], [None, None, 'る', None], [None, None, 'ことができ', None], [None, None, 'なかった', None], [None, None, '。」', None]]
[[None, None, '「', None], ['子供', 'こども', None, None], [None, None, 'が', None], ['転', 'ころ', None, None], [None, None, 'ん', None], [None, None, 'で', None], ['泣', 'な', None, None], [None, None, 'く', None], [None, None, 'わ', True], ['泣', 'な', None, None], [None, None, 'く', None], [None, None, 'わ', True], [None, None, '。なだめ', None], [None, None, 'る', None], [None, None, 'の', None], ['大変', 'たいへん', None, None], [None, None, 'だった', None], [None, None, '。」', None]]
[[None, None, '「', None], ['先輩', 'せんぱい', None, None], [None, None, 'は', None], ['面白', 'おもしろ', None, None], [None, None, 'い', None], [None, None, 'のなんのって', None], ['喋', 'しゃべ', None, None], [None, None, 'る', None], [None, None, 'と', None], ['笑', 'わら', None, None], [None, None, 'う', None], [None, None, 'わ', True], ['笑', 'わら', None, None], [None, None, 'う', None], [None, None, 'わ', True], [None, None, '。」', None]]
[[None, None, '「ちょっとからかっ', None], [None, None, 'た', None], [None, None, 'だけで', None], [None, None, '、あいつ', None], ['怒', 'おこ', None, None], [None, None, 'る', None], [None, None, 'わ', True], ['怒', 'おこ', None, None], [None, None, 'る', None], [None, None, 'わ', True], [None, None, '。」', None]]

 90%|█████████ | 846/938 [08:48<00:56,  1.64it/s]

[['君', 'きみ', None, None], [None, None, 'に', None], ['迷惑', 'めいわく', None, None], [None, None, 'をかけるぐらいなら、', None], ['自分', 'じぶん', None, None], [None, None, 'なりとも', True], [None, None, 'できることを', None], ['全部', 'ぜんぶ', None, None], [None, None, 'やってみるよ。', None]]
[['近', 'ちか', None, None], [None, None, 'くまで', None], ['来', 'き', None, None], [None, None, 'たなら、', None], ['声', 'こえ', None, None], [None, None, 'なりとも', True], [None, None, 'かけてくれてよかったのに。', None]]
[[None, None, 'ご', None], ['意見', 'いけん', None, None], [None, None, 'なりとも', True], [None, None, 'いただければ', None], ['幸', 'さいわ', None, None], [None, None, 'いです。', None]]
[['詳細', 'しょうさい', None, None], [None, None, 'は', None], ['後日', 'ごじつ', None, None], [None, None, 'でも', None], ['構', 'かま', None, None], [None, None, 'いませんが、', None], ['現段階', 'げんだんかい', None, None], [None, None, 'での', None], ['決定事項', 'けっていじこう', None, None], [None, None, 'なりとも', True], ['先', 'さき', None, None], [None, None, 'に', None], ['教', 'おし', None, None], [None, None, 'えていただけると', None], ['助', 'たす', None, None], [None, None, 'かります。', None]]
[['遅', 'おそ', None, None], [None, None, 'かれ', None], ['早', 'はや', None, None], [None, None, 'かれ、', None], ['誰', 'だれ', None, None], [None, None, 'か', None], [None, None, 'なりとも', True], ['真実', 'しんじつ', None, None], [None, None, 'に', None], ['気', 'き', None, None], [None, None, 'づくときが', None], ['来', 'く', None, None], [None, None, 'るだろう。', None]]

 90%|█████████ | 847/938 [08:48<00:55,  1.64it/s]

[['彼', 'かれ', None, None], [None, None, 'は', None], ['病院', 'びょういん', None, None], [None, None, 'に', None], ['来', 'く', None, None], [None, None, 'る', None], [None, None, 'に', True], ['至', 'いた', None, True], [None, None, 'っても', True], [None, None, '、まだ', None], ['治療', 'ちりょう', None, None], [None, None, 'をすることを', None], ['拒否', 'きょひ', None, None], [None, None, 'していた。', None]]
[['就業時間', 'しゅうぎょうじかん', None, None], [None, None, 'を', None], ['過', 'す', None, None], [None, None, 'ぎる', None], [None, None, 'に', True], ['至', 'いた', None, True], [None, None, 'っても', True], [None, None, '、この', None], ['会議', 'かいぎ', None, None], [None, None, 'は', None], ['終', 'お', None, None], [None, None, 'わりそうにありません。', None]]
[['結婚', 'けっこん', None, None], [None, None, 'する', None], [None, None, 'に', True], ['至', 'いた', None, True], [None, None, 'っても', True], [None, None, '、', None], ['完全', 'かんぜん', None, None], [None, None, 'にお', None], ['互', 'たが', None, None], [None, None, 'いを', None], ['理解', 'りかい', None, None], [None, None, 'し', None], ['合', 'あ', None, None], [None, None, 'えないカップルが', None], ['多', 'おお', None, None], [None, None, 'い。', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「だが、', None], ['事', 'こと', None, None], [None, None, 'ここ', None], [None, None, 'に', True], ['至', 'いた', None, True], [None, None, 'っても', True], [None, None, '、まだ', None], ['謝', 'あやま', None, None], [None, None, 'ることを', None], ['拒否', 'きょひ', None, None], [None, None, 'するほど', None], ['頑固', 'がんこ', None, None], [None, None, 'である」。', None]]
[['記事', 'きじ', None, None], [None, None, '：', None], [None, None, '「', None], ['首相', 'しゅしょう', None, None], [None, None, 'は', None], ['政府', 'せいふ', None, None], [None, None, 'の', None], ['腐敗', 'ふはい', None, None], [None, None, 'を', None], ['暴露', 'ばくろ', None, None], [None, None, 'される', None], [None, None, 'に', True], ['至', 'いた', None, True], [None, None, 'っても', True], [None, None, '、まだ', None], ['詳細', 'しょうさい', None, None], ['情報', 'じょうほう', None, None], [None, None, 'を', None], ['隠', 'かく', None, None], [None, None, 'し', None], ['通', 'とお', None, None], [None, None, 'そうとしていた。」', None]]

 90%|█████████ | 848/938 [08:49<00:51,  1.75it/s]

[[None, None, 'ダイエット', None], [None, None, 'を', True], ['兼', 'か', None, True], [None, None, 'ねて', True], [None, None, '、スポーツジムに', None], ['通', 'かよ', None, None], [None, None, 'っています。', None]]
[['日本語', 'にほんご', None, None], [None, None, 'の', None], ['勉強', 'べんきょう', None, None], [None, None, 'を', True], ['兼', 'か', None, True], [None, None, 'ねて', True], [None, None, '、', None], ['日本', 'にほん', None, None], [None, None, 'のゲームをしています。', None]]
[[None, None, 'リスニングの', None], ['練習', 'れんしゅう', None, None], [None, None, 'を', True], ['兼', 'か', None, True], [None, None, 'ねて', True], [None, None, '、', None], ['日本語', 'にほんご', None, None], [None, None, 'の', None], ['曲', 'きょく', None, None], [None, None, 'を', None], ['聞', 'き', None, None], [None, None, 'くことにしています。', None]]
[['散歩', 'さんぽ', None, None], [None, None, 'を', True], ['兼', 'か', None, True], [None, None, 'ねて', True], ['隣町', 'となりまち', None, None], [None, None, 'まで', None], ['歩', 'ある', None, None], [None, None, 'いて', None], ['買', 'か', None, None], [None, None, 'い', None], ['物', 'もの', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'きました。', None]]
[['小遣', 'こづか', None, None], [None, None, 'い', None], ['稼', 'かせ', None, None], [None, None, 'ぎ', None], [None, None, 'を', True], ['兼', 'か', None, True], [None, None, 'ねて', True], ['趣味', 'しゅみ', None, None], [None, None, 'で', None], ['同人誌', 'どうじんし', None, None], [None, None, 'を', None], ['描', 'えが', None, None], [None, None, 'いている。', None]]

 91%|█████████ | 849/938 [08:50<00:50,  1.75it/s]

[[None, None, 'ダイエットのモチベーションがもっと', None], ['上', 'あ', None, None], [None, None, 'がらない', None], [None, None, 'ものだろうか', True], [None, None, '。', None]]
[['電気', 'でんき', None, None], ['自動車', 'じどうしゃ', None, None], [None, None, 'の', None], ['値段', 'ねだん', None, None], [None, None, 'はもう', None], ['少', 'すこ', None, None], [None, None, 'し', None], ['安', 'やす', None, None], [None, None, 'くでき', None], [None, None, 'ない', None], [None, None, 'ものだろうか', True], [None, None, '。', None]]
[['日傘', 'ひがさ', None, None], [None, None, 'はもっと', None], ['畳', 'たた', None, None], [None, None, 'みやすく、そして', None], ['風', 'かぜ', None, None], [None, None, 'に', None], ['強', 'つよ', None, None], [None, None, 'くならない', None], [None, None, 'ものだろうか', True], [None, None, '。', None]]
[['人間', 'にんげん', None, None], [None, None, 'は', None], ['食', 'た', None, None], [None, None, 'べ', None], ['物', 'もの', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べなくても', None], ['生', 'い', None, None], [None, None, 'きるようにならない', None], [None, None, 'ものだろうか', True], [None, None, '。', None]]
[[None, None, 'ブログ', None], [None, None, '：「', None], ['詐欺', 'さぎ', None, None], [None, None, 'まがいなオンラインショップのことはどうにかならない', None], [None, None, 'ものだろうか', True], [None, None, '。」', None]]

 91%|█████████ | 850/938 [08:50<00:55,  1.57it/s]

[[None, None, '「', None], ['何', 'なに', None, None], [None, None, 'があっても、', None], ['必', 'かなら', None, None], [None, None, 'ずファンの', None], ['期待', 'きたい', None, None], [None, None, 'に', None], ['応', 'こた', None, True], [None, None, 'えて', True], ['見', 'み', None, True], [None, None, 'せます', True], [None, None, '！」', None]]
[[None, None, ' ', None], [None, None, 'ピアニスト', None], [None, None, '：「この', None], ['曲', 'きょく', None, None], [None, None, 'を', None], ['明日', 'あした', None, None], [None, None, 'までに', None], ['弾', 'ひ', None, True], [None, None, 'きこなしてみせる', True], [None, None, '！」', None]]
[[None, None, '「', None], ['今年', 'ことし', None, None], [None, None, 'こそ、', None], ['必', 'かなら', None, None], [None, None, 'ず', None], ['運転', 'うんてん', None, None], ['免許', 'めんきょ', None, None], [None, None, 'を', None], ['取', 'と', None, True], [None, None, 'って', True], ['見', 'み', None, True], [None, None, 'せる', True], [None, None, 'よ。」', None]]
[[None, None, '「どんな', None], ['手', 'て', None, None], [None, None, 'を', None], ['使', 'つか', None, None], [None, None, 'ってでも、', None], ['絶対', 'ぜったい', None, None], [None, None, '、', None], ['成功', 'せいこう', None, None], [None, None, 'して', True], ['見', 'み', None, True], [None, None, 'せる', True], [None, None, '！」', None]]
[['妻', 'つま', None, None], [None, None, 'を', None], ['喜', 'よろこ', None, None], [None, None, 'ばせるような', None], ['美味', 'おい', None, None], [None, None, 'しい', None], ['料理', 'りょうり', None, None], [None, None, 'を', None], ['作', 'つく', None, True], [None, None, 'ってみせる', True], [None, None, '！', None]]

 91%|█████████ | 851/938 [08:51<00:52,  1.65it/s]

[['感動的', 'かんどうてき', None, None], [None, None, 'なシーンと', None], ['ＢＧＭ', 'ビージーエム', None, None], [None, None, 'が', None], ['相', 'あい', None, True], [None, None, 'まって', True], [None, None, '、', None], ['泣', 'な', None, None], [None, None, 'かずにはいられませんでした。', None]]
[['腹痛', 'ふくつう', None, None], [None, None, 'と', None], ['頭痛', 'ずつう', None, None], [None, None, 'が', None], ['相', 'あい', None, True], [None, None, 'まって', True], [None, None, '、まるで', None], ['生', 'い', None, None], [None, None, 'きている', None], ['心地', 'ここち', None, None], [None, None, 'がしませんでした。', None]]
[[None, None, ' ', None], ['小説', 'しょうせつ', None, None], [None, None, '：「', None], ['夕暮', 'ゆうぐ', None, None], [None, None, 'れが', None], ['虹', 'にじ', None, None], [None, None, 'と', None], ['相', 'あい', None, True], [None, None, 'まって', True], ['空', 'そら', None, None], [None, None, 'をある', None], ['種', 'しゅ', None, None], [None, None, 'のキャンディーのように', None], ['見', 'み', None, None], [None, None, 'せた。」', None]]
[['気温', 'きおん', None, None], [None, None, 'の', None], ['高', 'たか', None, None], [None, None, 'さと', None], ['湿度', 'しつど', None, None], [None, None, 'の', None], ['高', 'たか', None, None], [None, None, 'さが', None], ['相', 'あい', None, True], [None, None, 'まって', True], [None, None, '、', None], ['日本', 'にほん', None, None], [None, None, 'の', None], ['夏', 'なつ', None, None], [None, None, 'は', None], ['地獄', 'じごく', None, None], [None, None, 'みたいです。', None]]
[['値段', 'ねだん', None, None], [None, None, 'の', None], ['安', 'やす', None, None], [None, None, 'さと', None], ['質', 'しつ', None, None], [None, None, 'の', None], ['良', 'よ', None, None], [None, None, 'さが', None], ['相', 'あい', None, True], [None, None, 'まって', True], [None, None, '、この', None], ['商品', 'しょうひん', None, None], [None, None, 'は', None], ['売', 'う', None, None], [None, None, 'れに', None], ['売', 'う', None, None], [None, None, 'れている。', None]]

 91%|█████████ | 852/938 [08:51<00:51,  1.69it/s]

[[None, None, 'ロジャー・キントの', None], ['言葉', 'ことば', None, None], [None, None, 'は', None], ['一', 'ひと', None, None], [None, None, 'つとして', None], ['信', 'しん', None, None], [None, None, 'じる', None], [None, None, 'に', True], ['足', 'た', None, True], [None, None, 'りない', True], [None, None, 'ことだ。', None]]
[[None, None, 'こんな', None], ['稚拙', 'ちせつ', None, None], [None, None, 'な', None], ['感想文', 'かんそうぶん', None, None], [None, None, 'なんて、', None], ['発表', 'はっぴょう', None, None], [None, None, 'する', None], [None, None, 'に', True], ['足', 'た', None, True], [None, None, 'りない', True], [None, None, 'ですよ…。', None]]
[['自慢', 'じまん', None, None], [None, None, 'する', None], [None, None, 'に', True], ['足', 'た', None, True], [None, None, 'りない', True], [None, None, 'テストの', None], ['点数', 'てんすう', None, None], [None, None, 'で、しょんぼりとしている。', None]]
[[None, None, 'これは', None], ['因果応報', 'いんがおうほう', None, None], [None, None, 'というやつだから、', None], ['彼女', 'かのじょ', None, None], [None, None, 'には', None], ['同情', 'どうじょう', None, None], [None, None, 'する', None], [None, None, 'に', True], ['足', 'た', None, True], [None, None, 'りません', True], [None, None, '。', None]]
[['信', 'しん', None, None], [None, None, 'じる', None], [None, None, 'に', True], ['足', 'た', None, True], [None, None, 'りない', True], [None, None, 'デタラメを', None], ['信', 'しん', None, None], [None, None, 'じてしまうような', None], ['人', 'ひと', None, None], [None, None, 'が', None], ['心配', 'しんぱい', None, None], [None, None, 'でならない。', None]]

 91%|█████████ | 853/938 [08:52<00:51,  1.65it/s]

[['空気', 'くうき', None, None], [None, None, 'は', None], ['生', 'い', None, None], [None, None, 'きるに', None], ['欠', 'か', None, None], [None, None, 'く', None], [None, None, 'べからざる', True], [None, None, 'ものだ。', None]]
[[None, None, 'ちゃんと', None], ['稼', 'かせ', None, None], [None, None, 'いでいない', None], ['人', 'ひと', None, None], [None, None, 'はご', None], ['馳走', 'ちそう', None, None], [None, None, 'など', None], ['食', 'く', None, None], [None, None, 'う', None], [None, None, 'べからず', True], [None, None, '。', None]]
[['池', 'いけ', None, None], [None, None, 'の', None], ['鯉', 'こい', None, None], [None, None, 'に', None], ['餌', 'えさ', None, None], [None, None, 'をあげる', None], [None, None, 'べからず', True], [None, None, '！', None], ['鯉', 'こい', None, None], [None, None, 'が', None], ['増', 'ふ', None, None], [None, None, 'え', None], ['過', 'す', None, None], [None, None, 'ぎてしまいます！', None]]
[['公園', 'こうえん', None, None], [None, None, 'の', None], ['看板', 'かんばん', None, None], [None, None, '：「', None], ['芝生', 'しばふ', None, None], [None, None, 'にゴミ', None], ['捨', 'す', None, None], [None, None, 'てる', None], [None, None, 'べからず', True], [None, None, '」', None]]
[[None, None, 'ブログ', None], ['記事', 'きじ', None, None], [None, None, '：「', None], ['英語', 'えいご', None, None], [None, None, 'で', None], ['上手', 'じょうず', None, None], [None, None, 'にフォーマルな', None], ['手紙', 'てがみ', None, None], [None, None, 'を', None], ['書', 'か', None, None], [None, None, 'くための『べし・', None], [None, None, 'べからず', True], [None, None, '』', None], ['集', 'しゅう', None, None], [None, None, '」', None]]

 91%|█████████ | 854/938 [08:53<00:51,  1.62it/s]

[['小説', 'しょうせつ', None, None], [None, None, '：「', None], ['割', 'わ', None, True], [None, None, 'れんばかりの', True], ['拍手', 'はくしゅ', None, None], [None, None, 'に', None], ['部屋', 'へや', None, None], [None, None, 'は', None], ['満', 'み', None, None], [None, None, 'たされた。」', None]]
[['溢', 'あふ', None, True], [None, None, 'れんばかりの', True], [None, None, 'この', None], ['気持', 'きも', None, None], [None, None, 'ちを、どうやったら', None], ['伝', 'つた', None, None], [None, None, 'えられるのでしょうか…。', None]]
[[None, None, 'このトリックアートを', None], ['見', 'み', None, None], [None, None, 'ていたら、', None], ['今', 'いま', None, None], [None, None, 'にも', None], ['目', 'め', None, None], [None, None, 'が', None], ['回', 'まわ', None, True], [None, None, 'らんばかりに', True], [None, None, 'フラフラしてきた。', None]]
[['泣', 'な', None, True], [None, None, 'かんばかりに', True], ['口', 'くち', None, None], [None, None, 'をギュッと', None], ['閉', 'と', None, None], [None, None, 'じている', None], ['息子', 'むすこ', None, None], [None, None, 'が、', None], ['愛', 'いと', None, None], [None, None, 'おしくてしかたがありません。', None]]
[['殴', 'なぐ', None, True], [None, None, 'りかからんばかりに', True], ['体', 'からだ', None, None], [None, None, 'をワナワナと', None], ['震', 'ふる', None, None], [None, None, 'わせている', None], ['彼', 'かれ', None, None], [None, None, 'からソッと', None], ['距離', 'きょり', None, None], [None, None, 'をおいた。', None]]

 91%|█████████ | 855/938 [08:53<00:48,  1.70it/s]

[['全', 'すべ', None, None], [None, None, 'ての', None], ['犯罪者', 'はんざいしゃ', None, None], [None, None, 'は、', None], ['法', 'ほう', None, None], [None, None, 'に', True], ['則', 'のっと', None, True], [None, None, 'って', True], ['裁', 'さば', None, None], [None, None, 'かれるべきである。', None]]
[['伝統', 'でんとう', None, None], [None, None, 'に', True], ['則', 'のっと', None, True], [None, None, 'って', True], [None, None, '、', None], ['和装', 'わそう', None, None], [None, None, 'で', None], ['結婚式', 'けっこんしき', None, None], [None, None, 'を', None], ['行', 'おこな', None, None], [None, None, 'いました。', None]]
[['先例', 'せんれい', None, None], [None, None, 'に', True], ['則', 'のっと', None, True], [None, None, 'って', True], ['全', 'すべ', None, None], [None, None, 'てのことをしていては、', None], ['改革', 'かいかく', None, None], [None, None, 'などできない。', None]]
[[None, None, 'もう', None], ['古', 'ふる', None, None], [None, None, 'いやり', None], ['方', 'かた', None, None], [None, None, 'に', True], ['則', 'のっと', None, True], [None, None, 'って', True], ['全', 'すべ', None, None], [None, None, 'てのことを', None], ['行', 'おこな', None, None], [None, None, 'うのはやめようではないか。', None]]
[['原則', 'げんそく', None, None], [None, None, 'に', True], ['則', 'のっと', None, True], [None, None, 'って', True], [None, None, '、', None], ['規則', 'きそく', None, None], [None, None, 'を', None], ['破', 'やぶ', None, None], [None, None, 'った', None], ['社員', 'しゃいん', None, None], [None, None, 'は', None], ['解雇', 'かいこ', None, None], [None, None, 'されることとなりました。', None]]

 91%|█████████▏| 856/938 [08:54<00:46,  1.77it/s]

[[None, None, 'まあ、お', None], ['子', 'こ', None, None], [None, None, 'さんが', None], ['結婚', 'けっこん', None, None], [None, None, 'したの？', None], ['羨', 'うらや', None, None], [None, None, 'ましい', None], ['限', 'かぎ', None, True], [None, None, 'り', True], [None, None, 'だわ。', None]]
[[None, None, 'コスタリカ', None], ['旅行', 'りょこう', None, None], [None, None, 'の', None], ['抽選', 'ちゅうせん', None, None], [None, None, 'に', None], ['当', 'あ', None, None], [None, None, 'たったなんて、うらやましい', None], ['限', 'かぎ', None, True], [None, None, 'り', True], [None, None, 'だよ。', None]]
[['狼人間', 'おおかみにんげん', None, None], [None, None, 'が', None], ['僕', 'ぼく', None, None], [None, None, 'の', None], ['味方', 'みかた', None, None], [None, None, 'なんて、', None], ['心強', 'こころづよ', None, None], [None, None, 'い', None], ['限', 'かぎ', None, True], [None, None, 'り', True], [None, None, 'です。', None]]
[['信頼', 'しんらい', None, None], [None, None, 'していた', None], ['子供', 'こども', None, None], [None, None, 'に', None], ['裏切', 'うらぎ', None, None], [None, None, 'られて、', None], ['悲', 'かな', None, None], [None, None, 'しい', None], ['限', 'かぎ', None, True], [None, None, 'り', True], [None, None, 'です。', None]]
[['子供', 'こども', None, None], [None, None, 'を', None], ['先', 'さき', None, None], [None, None, 'に', None], ['亡', 'な', None, None], [None, None, 'くすなんて、', None], ['本当', 'ほんとう', None, None], [None, None, 'に', None], ['可哀想', 'かわいそう', None, None], [None, None, 'な', True], ['限', 'かぎ', None, True], [None, None, 'り', True], [None, None, 'だ。', None]]

 91%|█████████▏| 857/938 [08:54<00:47,  1.69it/s]

[[None, None, '「ルームメイトはオムライス', None], [None, None, 'は', True], ['疎', 'おろ', None, True], [None, None, 'か', True], [None, None, '、おにぎりさえ', None], ['作', 'つく', None, None], [None, None, 'れない。」', None]]
[['掃除機', 'そうじき', None, None], [None, None, 'をかけること', None], [None, None, 'は', True], ['疎', 'おろ', None, True], [None, None, 'か', True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'はゴミ', None], ['拾', 'ひろ', None, None], [None, None, 'いさえしない。', None]]
[[None, None, 'パスタ', None], [None, None, 'は', True], ['疎', 'おろ', None, True], [None, None, 'か', True], [None, None, 'お', None], ['米', 'こめ', None, None], [None, None, 'さえ', None], ['食', 'た', None, None], [None, None, 'べるのをやめていたら', None], ['痩', 'や', None, None], [None, None, 'せました。', None]]
[['貴重品', 'きちょうひん', None, None], [None, None, 'は', True], ['疎', 'おろ', None, True], [None, None, 'か', True], [None, None, '、', None], ['身', 'み', None, None], [None, None, 'につけていた', None], ['服', 'ふく', None, None], [None, None, 'まで', None], ['奪', 'うば', None, None], [None, None, 'われてしまった。', None]]
[['今月', 'こんげつ', None, None], [None, None, 'の', None], ['生活', 'せいかつ', None, None], [None, None, 'は', True], ['疎', 'おろ', None, True], [None, None, 'か', True], [None, None, '、', None], ['今日', 'きょう', None, None], [None, None, 'でさえ', None], ['生', 'い', None, None], [None, None, 'きていけるか', None], ['分', 'わ', None, None], [None, None, 'かりません。', None]]

 91%|█████████▏| 858/938 [08:55<00:44,  1.78it/s]

[['脅迫', 'きょうはく', None, None], [None, None, 'めいた', True], [None, None, 'メールが', None], ['役所', 'やくしょ', None, None], [None, None, 'に', None], ['届', 'とど', None, None], [None, None, 'いたそうだ。', None]]
[['桜', 'さくら', None, None], [None, None, 'も', None], ['咲', 'さ', None, None], [None, None, 'いてすっかり', None], ['春', 'はる', None, None], [None, None, 'めいて', True], [None, None, 'きました。', None]]
[['作', 'つく', None, None], [None, None, 'り', None], ['物', 'もの', None, None], [None, None, 'めいて', True], ['見', 'み', None, None], [None, None, 'えるほど、', None], ['平穏', 'へいおん', None, None], [None, None, 'で', None], ['美', 'うつく', None, None], [None, None, 'しい', None], ['景色', 'けしき', None, None], [None, None, 'だった。', None]]
[['色', 'いろ', None, None], [None, None, 'めいた', True], ['彼女', 'かのじょ', None, None], [None, None, 'の', None], ['表情', 'ひょうじょう', None, None], [None, None, 'に、', None], ['思', 'おも', None, None], [None, None, 'わずドキッとしました。', None]]
[['芝居', 'しばい', None, None], [None, None, 'めいた', True], ['彼', 'かれ', None, None], [None, None, 'のプレゼンには、あまり', None], ['魅力', 'みりょく', None, None], [None, None, 'を', None], ['感', 'かん', None, None], [None, None, 'じません。', None]]

 92%|█████████▏| 859/938 [08:56<00:46,  1.69it/s]

[[None, None, 'ご', None], ['飯中', 'はんちゅう', None, None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'わず', True], ['会話中', 'かいわちゅう', None, None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'わず', True], ['携帯', 'けいたい', None, None], [None, None, 'を', None], ['手放', 'てばな', None, None], [None, None, 'さない', None], ['娘', 'むすめ', None, None], [None, None, 'が', None], ['心配', 'しんぱい', None, None], [None, None, 'です。', None]]
[['金庫', 'きんこ', None, None], [None, None, 'の', None], ['中', 'なか', None, None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'わず', True], ['冷蔵庫', 'れいぞうこ', None, None], [None, None, 'の', None], ['中', 'なか', None, None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'わず', True], [None, None, '、', None], ['泥棒', 'どろぼう', None, None], [None, None, 'は', None], ['全', 'すべ', None, None], [None, None, 'てを', None], ['盗', 'ぬす', None, None], [None, None, 'んでいったらしい。', None]]
[['子供', 'こども', None, None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'わず', True], ['女性', 'じょせい', None, None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'わず', True], [None, None, '、いつでも', None], ['安全', 'あんぜん', None, None], [None, None, 'に', None], ['暮', 'く', None, None], [None, None, 'らせるようになればいいです。', None]]
[['朝', 'あさ', None, None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'わず', True], ['夜', 'よる', None, None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'わず', True], [None, None, 'ずっとゲームをしていたせいで', None], ['生活', 'せいかつ', None, None], [None, None, 'リズムが', None], ['狂', 'くる', None, None], [None, None, 'ってしまった。', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「', None], ['街灯', 'がいとう', None, None], [None, None, 'は、はるか', None], ['北', 'きた', None, None], [None, None, 'の', None], ['村', 'むら', None, None], [None, None, 'で、', None], ['夜', 'よる', None, None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'わず', True], ['昼', 'ひる', None, None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'わず', True], [None, None, 'ともりつづけた。」', None]]

 92%|█████████▏| 860/938 [08:56<00:44,  1.74it/s]

[[None, None, 'ん？', None], ['熊', 'くま', None, None], [None, None, 'がエイリアンを', None], ['襲', 'おそ', None, None], [None, None, 'ったって？！', None], ['嘘', 'うそ', None, None], [None, None, 'をつく', None], [None, None, 'にもほどがある', True], [None, None, '！', None]]
[[None, None, 'またギャンブルをしたのか…', None], ['金', 'かね', None, None], [None, None, 'を', None], ['無駄遣', 'むだづか', None, None], [None, None, 'いする', None], [None, None, 'にもほどがある', True], [None, None, '。', None]]
[[None, None, 'ここぞという', None], ['時', 'とき', None, None], [None, None, 'に', None], ['頼', 'たよ', None, None], [None, None, 'りにならないなんて、リーダー', None], ['失格', 'しっかく', None, None], [None, None, 'にもほどがある', True], [None, None, '。', None]]
[['毎月', 'まいつき', None, None], ['１０', 'じゅう', None, None], ['万円', 'まんえん', None, None], [None, None, 'もコスメに', None], ['使', 'つか', None, None], [None, None, 'うなんて、', None], ['買', 'か', None, None], [None, None, 'いすぎ', None], [None, None, 'にもほどがある', True], [None, None, 'でしょう！', None]]
[['吐', 'は', None, None], [None, None, 'きそうになる', None], ['料理', 'りょうり', None, None], [None, None, 'を', None], ['作', 'つく', None, None], [None, None, 'れるとは…', None], ['料理', 'りょうり', None, None], [None, None, 'が', None], ['下手', 'へた', None, None], [None, None, 'にもほどがあります', True], [None, None, '。', None]]

 92%|█████████▏| 861/938 [08:57<00:42,  1.82it/s]

[['前', 'まえ', None, None], [None, None, 'にもまして', True], ['元気', 'げんき', None, None], [None, None, 'になって、ようやく', None], ['退院', 'たいいん', None, None], [None, None, 'した。', None]]
[['大学', 'だいがく', None, None], [None, None, 'に', None], ['合格', 'ごうかく', None, None], [None, None, 'したという', None], ['知', 'し', None, None], [None, None, 'らせに、', None], ['誰', 'だれ', None, None], [None, None, 'にもまして', True], ['父', 'ちち', None, None], [None, None, 'が', None], ['喜', 'よろこ', None, None], [None, None, 'びました。', None]]
[['財布', 'さいふ', None, None], [None, None, 'をなくした。それ', None], [None, None, 'にもまして', True], ['困', 'こま', None, None], [None, None, 'ったのは、', None], ['家', 'いえ', None, None], [None, None, 'の', None], ['鍵', 'かぎ', None, None], [None, None, 'をなくしたことだ。', None]]
[['今年', 'ことし', None, None], [None, None, 'の', None], ['花火', 'はなび', None, None], ['大会', 'たいかい', None, None], [None, None, 'は、', None], ['例年', 'れいねん', None, None], [None, None, 'にもまして', True], ['豪華', 'ごうか', None, None], [None, None, 'だったような', None], ['気', 'き', None, None], [None, None, 'がします。', None]]
[[None, None, 'このホテルの', None], ['接客', 'せっきゃく', None, None], [None, None, 'は、どこ', None], [None, None, 'にもまして', True], ['良', 'い', None, None], [None, None, 'いと', None], ['評判', 'ひょうばん', None, None], [None, None, 'になっている。', None]]

 92%|█████████▏| 862/938 [08:57<00:45,  1.68it/s]

[[None, None, 'はやせ', None], [None, None, 'と', None], [None, None, 'なおと', None], [None, None, 'は', None], ['狂', 'くる', None, None], [None, None, 'った', None], [None, None, 'ように', None], ['踊', 'おど', None, None], [None, None, 'っ', None], [None, None, 'て', None], ['踊', 'おど', None, None], [None, None, 'っ', None], [None, None, 'て', None], ['踊', 'おど', None, True], [None, None, 'りまくった', True], [None, None, '。', None]]
[[None, None, '「', None], ['最近', 'さいきん', None, None], [None, None, '、チョコ', None], [None, None, 'を', None], ['食', 'た', None, True], [None, None, 'べまくっている', True], [None, None, 'から', None], [None, None, 'ちょっと', None], ['太', 'ふと', None, None], [None, None, 'っ', None], [None, None, 'た', None], [None, None, '。」', None]]
[['締', 'し', None, None], [None, None, 'め', None], ['切', 'き', None, None], [None, None, 'りが', None], ['近', 'ちか', None, None], [None, None, 'いから、', None], ['原稿', 'げんこう', None, None], [None, None, 'を', None], ['書', 'か', None, True], [None, None, 'きまくった', True], [None, None, '。', None]]
[['時間', 'じかん', None, None], [None, None, 'さえあれば', None], ['走', 'はし', None, True], [None, None, 'りまくっている', True], ['彼', 'かれ', None, None], [None, None, 'の', None], ['足', 'あし', None, None], [None, None, 'はたくましいです。', None]]
[[None, None, 'ストレス', None], ['発散', 'はっさん', None, None], [None, None, 'でメイク', None], ['道具', 'どうぐ', None, None], [None, None, 'を', None], ['買', 'か', None, True], [None, None, 'いまくった', True], [None, None, 'せいで', None], ['金欠', 'きんけつ', None, None], [None, None, 'になった。', None]]

 92%|█████████▏| 863/938 [08:58<00:55,  1.35it/s]

[[None, None, '「', None], ['今朝', 'けさ', None, None], [None, None, 'の', None], ['通勤時', 'つうきんじ', None, None], [None, None, 'は、', None], ['急', 'きゅう', None, None], [None, None, 'に', None], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'っ', None], [None, None, 'てくる', None], [None, None, 'わ', True], ['傘', 'かさ', None, None], [None, None, 'は', None], ['壊', 'こわ', None, None], [None, None, 'れる', None], [None, None, 'わ', True], [None, None, 'で', None], ['大変', 'たいへん', None, None], [None, None, 'だった', None], [None, None, '。」', None]]
[[None, None, '「', None], ['今日', 'きょう', None, None], [None, None, 'は', None], [None, None, 'タンス', None], [None, None, 'に', None], ['小指', 'こゆび', None, None], [None, None, 'を', None], [None, None, 'ぶつけ', None], [None, None, 'る', None], [None, None, 'わ', True], [None, None, '、', None], ['道', 'みち', None, None], [None, None, 'で', None], [None, None, 'つまず', None], [None, None, 'く', None], [None, None, 'わ', True], [None, None, 'で', None], [None, None, '、ついて', None], [None, None, 'なかった', None], [None, None, '。」', None]]
[[None, None, '「', None], ['朝', 'あさ', None, None], [None, None, 'から', None], ['犬', 'いぬ', None, None], [None, None, 'に', None], ['吠', 'ほ', None, None], [None, None, 'えら', None], [None, None, 'れる', None], [None, None, 'わ', True], [None, None, '、', None], ['鳥', 'とり', None, None], [None, None, 'の', None], [None, None, 'ウンチ', None], [None, None, 'が', None], ['頭', 'あたま', None, None], [None, None, 'に', None], ['落', 'お', None, None], [None, None, 'ち', None], [None, None, 'てくる', None], [None, None, 'わ', True], [None, None, 'で', None], [None, None, '…（', None], ['最低', 'さいてい', None, None], [None, None, 'な', None], ['一', 'いち', None, None], ['日', 'にち', None, None], [None, None, 'だった', None], [None, None, 'わ）。」', None]]
[[None, None, '「', None], [None, None, 'あの', None], [None, None, 'レストラン、', None], ['料理', 'りょうり', None, None], [None, None, 'に', None], ['虫', 'むし', None, None], [None, None, 'が', None], ['入', 'はい', None, None], [None, None, 'っ', None], [None, None, 'てる', None], [None, None, 'わ', True], [None, None, '、クレームいっ', None], [None, None, 'たら', None], ['切', 'き', None, None], [None, None, 'れら', None], [None, None, 'れる', None], [None, None, 'わ', True], [None, None, 'で', None], ['最低', 'さいてい', None, None], [None, None, 'だった', None], [None, None, 'の', None], [None, None, '。」', None]]
[[None, None, 'お', None], ['母', 'かあ', None, None], [None, None, 'さんに', None], ['怒', 'おこ', None, None], [None, None, 'られる', None], [None, None, 'わ', True], ['先生', 'せんせい', None, None], [None, None, 'にも', None], ['怒', 'おこ', None, None], [None, None, 'られる', None], [None, None, 'わ', True], [None, None, '、', None], ['気分', 'きぶん', None, None], [None, None, 'が', None], ['悪', 'わる', None, None], [None, None, 'い。', None]]

 92%|█████████▏| 864/938 [08:59<00:53,  1.39it/s]

[['今日', 'きょう', None, None], [None, None, 'の', None], ['午後', 'ごご', None, None], [None, None, 'までに', None], [None, None, 'どうにか', True], ['帰', 'かえ', None, None], [None, None, 'れたらいいんだけど・・・。', None]]
[[None, None, 'どうにか', True], [None, None, 'して', None], ['敵', 'てき', None, None], [None, None, 'の', None], ['攻撃', 'こうげき', None, None], [None, None, 'を', None], ['回避', 'かいひ', None, None], [None, None, 'しなければ！ このままでは', None], ['私', 'わたし', None, None], [None, None, 'たちの', None], ['方', 'ほう', None, None], [None, None, 'が', None], ['先', 'さき', None, None], [None, None, 'に', None], ['滅', 'ほろ', None, None], [None, None, 'びてしまう！', None]]
[[None, None, 'どうにか', True], [None, None, 'ステージの', None], ['後方', 'こうほう', None, None], [None, None, 'まで', None], ['声', 'こえ', None, None], [None, None, 'を', None], ['届', 'とど', None, None], [None, None, 'けてくれないと', None], ['困', 'こま', None, None], [None, None, 'るよ。', None]]
[[None, None, 'どうにか', True], ['明日', 'あした', None, None], [None, None, 'までに', None], ['終', 'お', None, None], [None, None, 'わらせないと。', None]]
[['雨', 'あめ', None, None], [None, None, 'が', None], [None, None, 'どうにか', True], ['止', 'や', None, None], [None, None, 'んでほしいと、', None], ['心', 'こころ', None, None], [None, None, 'から', None], ['願', 'ねが', None, None], [None, None, 'っている。', None]]

 92%|█████████▏| 865/938 [09:00<00:51,  1.43it/s]

[['教室', 'きょうしつ', None, None], [None, None, 'に', None], ['着', 'つ', None, None], [None, None, 'く', None], [None, None, 'や', True], ['否', 'いな', None, True], [None, None, 'や', True], [None, None, 'ランドセルを', None], ['机', 'つくえ', None, None], [None, None, 'に', None], ['置', 'お', None, None], [None, None, 'いた。', None]]
[['１２', 'じゅうに', None, None], ['時', 'じ', None, None], [None, None, 'を', None], ['回', 'まわ', None, None], [None, None, 'る', None], [None, None, 'や', True], ['否', 'いな', None, True], [None, None, 'や', True], [None, None, 'すぐに', None], ['誕生日', 'たんじょうび', None, None], [None, None, 'のメッセージを', None], ['送', 'おく', None, None], [None, None, 'ってくれたのは、お', None], ['母', 'かあ', None, None], [None, None, 'さんだった。', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「', None], ['彼', 'かれ', None, None], [None, None, 'があくびをする', None], [None, None, 'や', True], ['否', 'いな', None, True], [None, None, 'や', True], ['彼女', 'かのじょ', None, None], [None, None, 'もあくびが', None], ['出', 'で', None, None], [None, None, 'てしまった。」', None]]
[['記事', 'きじ', None, None], [None, None, '： 「', None], ['警察官', 'けいさつかん', None, None], [None, None, 'に', None], ['気', 'き', None, None], [None, None, 'が', None], ['付', 'つ', None, None], [None, None, 'く', None], [None, None, 'や', True], ['否', 'いな', None, True], [None, None, 'や', True], ['急', 'きゅう', None, None], [None, None, 'に', None], ['走', 'はし', None, None], [None, None, 'り', None], ['出', 'だ', None, None], [None, None, 'した。」', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「', None], ['焼', 'や', None, None], [None, None, 'き', None], ['立', 'た', None, None], [None, None, 'てのパンが', None], ['皿', 'さら', None, None], [None, None, 'に', None], ['出', 'で', None, None], [None, None, 'てくる', None], [None, None, 'や', True], ['否', 'いな', None, True], [None, None, 'や', True], [None, None, 'すぐに', None], ['彼', 'かれ', None, None], [None, None, 'の', None], ['口', 'くち', None, None], [None, None, 'の', None], ['中', 'なか', None, None], [None, None, 'に', None], ['消', 'き', None, None], [None, None, 'えた。」', None]]

 92%|█████████▏| 866/938 [09:00<00:47,  1.52it/s]

[[None, None, 'お', None], ['見舞', 'みま', None, None], [None, None, 'いに', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, '：「', None], ['先生', 'せんせい', None, None], [None, None, 'が', None], ['倒', 'たお', None, None], [None, None, 'れたと', None], ['耳', 'みみ', None, None], [None, None, 'にしたため、', None], ['直', 'す', None, None], [None, None, 'ぐにこちらへ', None], ['伺', 'うかが', None, None], [None, None, 'った', None], ['次第', 'しだい', None, True], [None, None, 'です', True], [None, None, '。」', None]]
[['先生', 'せんせい', None, None], [None, None, '：「なんで', None], ['遅', 'おく', None, None], [None, None, 'れたんだ？」', None], ['生徒', 'せいと', None, None], [None, None, '：「', None], ['電車', 'でんしゃ', None, None], [None, None, 'が', None], ['遅延', 'ちえん', None, None], [None, None, 'していて', None], ['遅', 'おく', None, None], [None, None, 'れてしまった', None], ['次第', 'しだい', None, True], [None, None, 'です', True], [None, None, '。」', None]]
[['部下', 'ぶか', None, None], [None, None, 'が', None], ['上司', 'じょうし', None, None], [None, None, 'に', None], [None, None, '：「', None], ['吹雪', 'ふぶき', None, None], [None, None, 'の', None], ['影響', 'えいきょう', None, None], [None, None, 'で', None], ['列車', 'れっしゃ', None, None], [None, None, 'の', None], ['運行', 'うんこう', None, None], [None, None, 'ダイヤが', None], ['乱', 'みだ', None, None], [None, None, 'れており、', None], ['出社', 'しゅっしゃ', None, None], [None, None, 'が', None], ['遅', 'おく', None, None], [None, None, 'れた', None], ['次第', 'しだい', None, True], [None, None, 'です', True], [None, None, '。」', None]]
[['陽子', 'ようこ', None, None], [None, None, '：「どうして', None], ['日本語', 'にほんご', None, None], [None, None, 'の', None], ['勉強', 'べんきょう', None, None], [None, None, 'をしているの？」', None], [None, None, 'マット', None], [None, None, '：「', None], ['日本', 'にほん', None, None], [None, None, 'にいずれ', None], ['住', 'す', None, None], [None, None, 'みたいと', None], ['思', 'おも', None, None], [None, None, 'って', None], ['勉強', 'べんきょう', None, None], [None, None, 'を', None], ['始', 'はじ', None, None], [None, None, 'めた', None], ['次第', 'しだい', None, True], [None, None, 'だ', True], [None, None, 'よ。」', None]]
[['辞表', 'じひょう', None, None], [None, None, 'を', None], ['提出', 'ていしゅつ', None, None], [None, None, 'する', None], [None, None, '：「', None], ['母国', 'ぼこく', None, None], [None, None, 'にいる', None], ['身内', 'みうち', None, None], [None, None, 'が', None], ['倒', 'たお', None, None], [None, None, 'れたとの', None], ['連絡', 'れんらく', None, None], [None, None, 'が', None], ['入', 'はい', None, None], [None, None, 'ったため', None], ['帰国', 'きこく', None, None], [None, None, 'する', None], ['事', 'こと', None, None], [None, None, 'にした', None], ['次第', 'しだい', None, True], [None, None, 'です', True], [None, None, '。」', None]]

 92%|█████████▏| 867/938 [09:01<00:45,  1.55it/s]

[['失敗', 'しっぱい', None, None], [None, None, 'の', None], ['原因', 'げんいん', None, None], [None, None, 'は、', None], ['過度', 'かど', None, None], [None, None, 'な', None], ['緊張', 'きんちょう', None, None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'うところ', True], [None, None, 'でしょう。', None]]
[[None, None, 'ストレスによる', None], ['暴飲暴食', 'ぼういんぼうしょく', None, None], [None, None, 'で', None], ['体重', 'たいじゅう', None, None], [None, None, 'が', None], ['増加', 'ぞうか', None, None], [None, None, 'した', None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'うところ', True], [None, None, 'だと', None], ['思', 'おも', None, None], [None, None, 'います。', None]]
[[None, None, 'はなこ', None], [None, None, '：「オリビアの', None], ['日本語', 'にほんご', None, None], [None, None, 'のレベルはどうですか？」', None], [None, None, 'かすみ', None], [None, None, '：「せいぜい', None], ['平均', 'へいきん', None, None], [None, None, 'といったところ', True], [None, None, 'でしょう。」', None]]
[['上司', 'じょうし', None, None], [None, None, '：「', None], ['頼', 'たの', None, None], [None, None, 'んでいた', None], ['仕事', 'しごと', None, None], [None, None, 'はどこまでおわりましたか？」', None], ['部下', 'ぶか', None, None], [None, None, '：「', None], ['７０', 'ななじゅう', None, None], [None, None, '、', None], ['８０', 'はちじゅっ', None, None], [None, None, 'パーセント', None], [None, None, 'というところ', True], [None, None, 'です。」', None]]
[['友達', 'ともだち', None, None], ['１', 'いち', None, None], [None, None, '：「スーパーまで', None], ['行', 'い', None, None], [None, None, 'くのにどれくらいかかる？」', None], ['友達', 'ともだち', None, None], ['２', 'に', None, None], [None, None, '：「たぶん', None], ['２０', 'にじゅっ', None, None], ['分', 'ぷん', None, None], [None, None, 'といったところ', True], [None, None, 'だろう。」', None]]

 93%|█████████▎| 868/938 [09:01<00:45,  1.54it/s]

[['人間', 'にんげん', None, None], [None, None, 'は', None], ['酸素', 'さんそ', None, None], [None, None, 'なしには', None], ['１日', 'いちにち', None, None], [None, None, 'たりとも', True], ['生', 'い', None, None], [None, None, 'きられない。', None]]
[['安全', 'あんぜん', None, None], [None, None, 'や', None], ['生命', 'せいめい', None, None], [None, None, 'を', None], ['脅', 'おびや', None, None], [None, None, 'かすものは', None], ['何', 'なん', None, None], ['人', 'びと', None, None], [None, None, 'たりとも', True], ['許', 'ゆる', None, None], [None, None, 'されない。', None]]
[['今日', 'きょう', None, None], [None, None, 'は', None], ['沢山', 'たくさん', None, None], [None, None, 'の', None], ['仕事', 'しごと', None, None], [None, None, 'があるので、', None], ['一分', 'いっぷん', None, None], [None, None, 'たりとも', True], [None, None, 'ぼーっとして', None], ['過', 'す', None, None], [None, None, 'ごすわけにはいきません。', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「', None], ['一瞬', 'いっしゅん', None, None], [None, None, 'たりとも', True], ['無駄', 'むだ', None, None], [None, None, 'にしないつもりで', None], ['生', 'い', None, None], [None, None, 'きている。」', None]]
[['茜雫', 'せんな', None, None], [None, None, 'の', None], ['死', 'し', None, None], ['以来', 'いらい', None, None], ['１５', 'じゅうご', None, None], ['年', 'ねん', None, None], ['経', 'た', None, None], [None, None, 'ったが、', None], ['彼女', 'かのじょ', None, None], [None, None, 'を', None], ['忘', 'わす', None, None], [None, None, 'れたことは', None], ['一', 'いち', None, None], ['度', 'ど', None, None], [None, None, 'たりとも', True], [None, None, 'なかった。', None]]

 93%|█████████▎| 869/938 [09:02<00:42,  1.63it/s]

[[None, None, 'このラーメンの', None], ['美味', 'おい', None, None], [None, None, 'しさ', None], [None, None, 'ったらない', True], [None, None, '…。ついつい', None], ['食', 'た', None, None], [None, None, 'べてしまうんだ。', None]]
[[None, None, '「', None], ['車', 'くるま', None, None], [None, None, 'のタイヤが', None], ['盗', 'ぬす', None, None], [None, None, 'まれた。', None], ['本当', 'ほんとう', None, None], [None, None, 'に', None], ['腹', 'はら', None, None], [None, None, 'が', None], ['立', 'た', None, None], [None, None, 'つ', None], [None, None, 'ったらない', True], [None, None, '。」', None]]
[[None, None, '「', None], ['校長', 'こうちょう', None, None], [None, None, 'と', None], ['鹿', 'しか', None, None], [None, None, 'との', None], ['戦', 'たたか', None, None], [None, None, 'いを', None], ['見', 'み', None, None], [None, None, 'たときの', None], ['驚', 'おどろ', None, None], [None, None, 'き', None], [None, None, 'といったらない', True], [None, None, 'よ。」', None]]
[[None, None, 'メークした', None], ['時', 'とき', None, None], [None, None, 'の', None], ['星野', 'ほしの', None, None], [None, None, 'の', None], ['変', 'か', None, None], [None, None, 'わり', None], ['様', 'よう', None, None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'ったらなかった', True], [None, None, '。まるで', None], ['別人', 'べつじん', None, None], [None, None, 'のようだった。', None]]
[['数', 'すう', None, None], ['年', 'ねん', None, None], [None, None, 'が', None], ['経', 'た', None, None], [None, None, 'ったのにまだあの', None], ['日', 'ひ', None, None], [None, None, 'の', None], ['日没', 'にちぼつ', None, None], [None, None, 'を', None], ['覚', 'おぼ', None, None], [None, None, 'えている。その', None], ['景色', 'けしき', None, None], [None, None, 'の', None], ['美', 'うつく', None, None], [None, None, 'しさ', None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'ったらなかった', True], [None, None, '。', None]]

 93%|█████████▎| 870/938 [09:03<00:39,  1.72it/s]

[[None, None, 'アルバイトをすることは', None], ['学校', 'がっこう', None, None], [None, None, 'の', None], ['規則', 'きそく', None, None], [None, None, 'に', True], ['照', 'て', None, True], [None, None, 'らして', True], ['規則', 'きそく', None, None], ['違反', 'いはん', None, None], [None, None, 'になる。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'の', None], ['生活', 'せいかつ', None, None], ['習慣', 'しゅうかん', None, None], [None, None, 'に', True], ['照', 'て', None, True], [None, None, 'らして', True], ['罪', 'つみ', None, None], [None, None, 'がないことを', None], ['宣言', 'せんげん', None, None], [None, None, 'された。', None]]
[['我々', 'われわれ', None, None], [None, None, 'の', None], ['基準', 'きじゅん', None, None], [None, None, 'に', True], ['照', 'て', None, True], [None, None, 'らすと', True], [None, None, '、この', None], ['製品', 'せいひん', None, None], [None, None, 'を', None], ['粗悪品', 'そあくひん', None, None], [None, None, 'と', None], ['言', 'い', None, None], [None, None, 'う', None], ['人', 'ひと', None, None], [None, None, 'は', None], ['少', 'すく', None, None], [None, None, 'なくない。', None]]
[['国内', 'こくない', None, None], [None, None, 'の', None], ['状況', 'じょうきょう', None, None], [None, None, 'に', True], ['照', 'て', None, True], [None, None, 'らすと', True], [None, None, '、', None], ['国外', 'こくがい', None, None], [None, None, 'からの', None], ['石油', 'せきゆ', None, None], [None, None, 'の', None], ['購入', 'こうにゅう', None, None], [None, None, 'は', None], ['必要', 'ひつよう', None, None], [None, None, 'である。', None]]
[['社内', 'しゃない', None, None], ['規程', 'きてい', None, None], [None, None, 'に', True], ['照', 'て', None, True], [None, None, 'らして', True], [None, None, '、', None], ['作業員', 'さぎょういん', None, None], [None, None, 'の', None], ['効率性', 'こうりつせい', None, None], [None, None, 'の', None], ['検証', 'けんしょう', None, None], [None, None, 'を', None], ['行', 'おこな', None, None], [None, None, 'う。', None]]

 93%|█████████▎| 871/938 [09:03<00:40,  1.64it/s]

[['息子', 'むそこ', None, None], [None, None, 'のため', None], [None, None, 'とあれば', True], [None, None, '、', None], ['火', 'ひ', None, None], [None, None, 'の', None], ['中', 'なか', None, None], [None, None, 'でも', None], ['飛', 'と', None, None], [None, None, 'び', None], ['込', 'こ', None, None], [None, None, 'みます。', None]]
[['市民', 'しみん', None, None], [None, None, 'の', None], ['願', 'ねが', None, None], [None, None, 'い', None], [None, None, 'とあれば', True], [None, None, 'スーパーヒーローはいつでも', None], ['出動', 'しゅつどう', None, None], [None, None, 'するんだとか。', None]]
[['社員', 'しゃいん', None, None], [None, None, '：「そんな', None], ['会社', 'かいしゃ', None, None], [None, None, 'のトップからの', None], ['誘', 'さそ', None, None], [None, None, 'い', None], [None, None, 'とあれば', True], ['無視', 'むし', None, None], [None, None, 'できない」', None]]
[['母', 'はは', None, None], [None, None, 'はいつも「', None], ['愛', 'あい', None, None], [None, None, 'する', None], ['孫', 'まご', None, None], [None, None, 'のため', None], [None, None, 'とあれば', True], [None, None, '、どんな', None], ['頼', 'たの', None, None], [None, None, 'みも', None], ['聞', 'き', None, None], [None, None, 'くわ」と', None], ['言', 'い', None, None], [None, None, 'っています。', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「', None], ['皇帝', 'こうてい', None, None], ['陛下', 'へいか', None, None], [None, None, 'の', None], ['命令', 'めいれい', None, None], [None, None, 'とあれば', True], [None, None, 'せざるを', None], ['得', 'え', None, None], [None, None, 'ない！」', None]]

 93%|█████████▎| 872/938 [09:04<00:41,  1.60it/s]

[[None, None, '「', None], ['夜勤', 'やきん', None, None], [None, None, 'の', None], ['仕事', 'しごと', None, None], [None, None, 'も', None], [None, None, 'さぞ', True], ['大変', 'たいへん', None, None], [None, None, 'だろう。」', None]]
[[None, None, '「', None], ['長旅', 'ながたび', None, None], [None, None, 'ご', None], ['苦労', 'くろう', None, None], ['様', 'さま', None, None], [None, None, 'です。', None], [None, None, 'さぞ', True], [None, None, 'お', None], ['疲', 'つか', None, None], [None, None, 'れでしょう。」', None]]
[[None, None, '「', None], ['初', 'はじ', None, None], [None, None, 'めての', None], ['赤', 'あか', None, None], [None, None, 'ちゃんのお', None], ['誕生', 'たんじょう', None, None], [None, None, 'に', None], [None, None, 'さぞ', True], ['嬉', 'うれ', None, None], [None, None, 'しいことでしょう。」', None]]
[[None, None, '「', None], ['智子', 'さとこ', None, None], [None, None, 'は', None], ['昇進', 'しょうしん', None, None], [None, None, 'が', None], ['見送', 'みおく', None, None], [None, None, 'られて、', None], [None, None, 'さぞ', True], [None, None, 'がっかりしたに', None], ['違', 'ちが', None, None], [None, None, 'いない。」', None]]
[['料理好', 'りょうりず', None, None], [None, None, 'きの', None], ['旦那', 'だんな', None, None], [None, None, 'さんと', None], ['結婚', 'けっこん', None, None], [None, None, 'されて、', None], [None, None, 'さぞ', True], ['幸', 'しあわ', None, None], [None, None, 'せなことでしょう。', None]]

 93%|█████████▎| 873/938 [09:04<00:40,  1.59it/s]

[[None, None, '「', None], ['義理', 'ぎり', None, None], [None, None, 'の', None], ['母', 'はは', None, None], [None, None, 'ときたら', True], ['私', 'わたし', None, None], [None, None, 'のことをぼやいてばかりよ。」', None]]
[[None, None, '「このプリンター', None], [None, None, 'ときたら', True], [None, None, '、', None], ['忙', 'いそが', None, None], [None, None, 'しい', None], ['時', 'とき', None, None], [None, None, 'に', None], ['限', 'かぎ', None, None], [None, None, 'って', None], ['故障', 'こしょう', None, None], [None, None, 'するぞ！」', None]]
[[None, None, '「', None], ['娘', 'むすめ', None, None], [None, None, 'は', None], ['真面目', 'まじめ', None, None], [None, None, 'に', None], ['勉強', 'べんきょう', None, None], [None, None, 'しているのに、', None], ['息子', 'むすこ', None, None], [None, None, 'ときたら', True], [None, None, '・・・（', None], ['何', 'なに', None, None], [None, None, 'もやらない）」', None]]
[[None, None, '「うちの', None], ['旦那', 'だんな', None, None], [None, None, 'ときたら', True], [None, None, '、', None], ['連休中', 'れんきゅうちゅう', None, None], [None, None, 'うちでゴロゴロばかりで、', None], ['子', 'こ', None, None], [None, None, 'どもの', None], ['面倒', 'めんどう', None, None], [None, None, 'をみてくれないの。」', None]]
[[None, None, '「', None], ['隣', 'となり', None, None], [None, None, 'の', None], ['人', 'ひと', None, None], [None, None, 'ときたら', True], [None, None, '、', None], ['毎日', 'まいにち', None, None], [None, None, '、', None], ['毎日', 'まいにち', None, None], [None, None, '、', None], ['朝', 'あさ', None, None], [None, None, 'の', None], ['６', 'ろく', None, None], ['時', 'じ', None, None], [None, None, 'からラジオを', None], ['聞', 'き', None, None], [None, None, 'くからうるさくて', None], ['眠', 'ねむ', None, None], [None, None, 'れない。」', None]]

 93%|█████████▎| 874/938 [09:05<00:38,  1.68it/s]

[[None, None, '「くみこは', None], ['年', 'とし', None, None], [None, None, 'の', None], ['割', 'わり', None, None], [None, None, 'に', None], ['大人', 'おとな', None, None], [None, None, 'びている', True], [None, None, '。」', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「ヴァミリオは', None], ['大人', 'おとな', None, None], [None, None, 'びて', True], ['見', 'み', None, None], [None, None, 'えるが、', None], ['純粋', 'じゅんすい', None, None], [None, None, 'で、', None], ['表情', 'ひょうじょう', None, None], [None, None, 'がわかりやすい', None], ['少女', 'しょうじょ', None, None], [None, None, 'なのだ。」', None]]
[[None, None, 'プレミアが', None], ['付', 'つ', None, None], [None, None, 'いているせいでこんな', None], ['古', 'ふる', None, None], [None, None, 'びた', True], [None, None, 'レコードが', None], ['三十万円', 'さんじゅうまんえん', None, None], [None, None, 'もするなんて…！', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「', None], ['古', 'ふる', None, None], [None, None, 'びた', True], ['木橋', 'もくきょう', None, None], [None, None, 'は', None], ['足', 'あし', None, None], [None, None, 'を', None], ['踏', 'ふ', None, None], [None, None, 'み', None], ['出', 'だ', None, None], [None, None, 'すたびに', None], ['不穏', 'ふおん', None, None], [None, None, 'な', None], ['音', 'おと', None, None], [None, None, 'がした。」', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「そのテレビは', None], ['本当', 'ほんとう', None, None], [None, None, 'に', None], ['古', 'ふる', None, None], [None, None, 'びた', True], [None, None, 'ものだった。まるで', None], ['昭和', 'しょうわ', None, None], [None, None, 'の', None], ['時代', 'じだい', None, None], [None, None, 'から', None], ['飛', 'と', None, None], [None, None, 'び', None], ['出', 'だ', None, None], [None, None, 'したかのようだった。」', None]]

 93%|█████████▎| 875/938 [09:06<00:36,  1.75it/s]

[['誰', 'だれ', None, None], [None, None, 'にでも', None], ['欠点', 'けってん', None, None], [None, None, 'はある。', None], ['完全', 'かんぜん', None, None], [None, None, 'な', None], ['田中', 'たなか', None, None], [None, None, 'さん', None], [None, None, 'としたって', True], ['同', 'おな', None, None], [None, None, 'じだ。', None]]
[[None, None, '「え？', None], ['倒産', 'とうさん', None, None], [None, None, 'するか', None], ['合併', 'がっぺい', None, None], [None, None, 'するかだって？どちら', None], [None, None, 'にしたって', True], [None, None, '、', None], ['僕', 'ぼく', None, None], [None, None, 'にとってはマズイ', None], ['事', 'こと', None, None], [None, None, 'だ…。」', None]]
[['５', 'ご', None, None], ['人', 'にん', None, None], [None, None, 'の', None], ['子供', 'こども', None, None], [None, None, 'のお', None], ['母', 'かあ', None, None], [None, None, 'さん', None], [None, None, 'にしたところで', True], [None, None, '、まだまだ', None], ['子育', 'こそだ', None, None], [None, None, 'てにおいて', None], ['学', 'まな', None, None], [None, None, 'ぶことがあるだろう。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['非常', 'ひじょう', None, None], [None, None, 'に', None], ['深刻', 'しんこく', None, None], [None, None, 'な', None], ['状態', 'じょうたい', None, None], [None, None, 'だ。', None], ['天才', 'てんさい', None, None], ['医師', 'いし', None, None], [None, None, 'のジャック', None], [None, None, 'にしたところで', True], ['何', 'なに', None, None], [None, None, 'もできない。', None]]
[[None, None, '「ありがとう」や「ごめんなさい」という', None], ['小', 'ちい', None, None], [None, None, 'さな', None], ['言葉', 'ことば', None, None], [None, None, 'にしたって', True], [None, None, '、', None], ['聞', 'き', None, None], [None, None, 'く', None], ['側', 'がわ', None, None], [None, None, 'には', None], ['大', 'おお', None, None], [None, None, 'きな', None], ['意味', 'いみ', None, None], [None, None, 'を', None], ['持', 'も', None, None], [None, None, 'ちます。', None]]

 93%|█████████▎| 876/938 [09:06<00:34,  1.78it/s]

[['悲', 'かな', None, None], [None, None, 'しみが', None], [None, None, 'あればこそ', True], [None, None, '、', None], ['喜', 'よろこ', None, None], [None, None, 'びもある。', None]]
[['失敗', 'しっぱい', None, None], [None, None, 'すればこそ', True], [None, None, '、', None], ['成長', 'せいちょう', None, None], [None, None, 'できるのだと', None], ['思', 'おも', None, None], [None, None, 'う。', None]]
[['日本語', 'にほんご', None, None], [None, None, 'の', None], ['勉強', 'べんきょう', None, None], [None, None, 'は', None], ['難', 'むずか', None, True], [None, None, 'しければこそ', True], [None, None, '、', None], ['却', 'かえ', None, None], [None, None, 'ってやりがいを', None], ['感', 'かん', None, None], [None, None, 'じるのです。', None]]
[['両親', 'りょうしん', None, None], [None, None, 'が', None], ['子', 'こ', None, None], [None, None, 'どもを', None], ['叱', 'しか', None, None], [None, None, 'るのは', None], ['子', 'こ', None, None], [None, None, 'どもの', None], ['幸福', 'こうふく', None, None], [None, None, 'を', None], ['考', 'かんが', None, True], [None, None, 'えればこそ', True], [None, None, 'だ。', None]]
[[None, None, '「', None], ['私', 'わたし', None, None], [None, None, 'たちは', None], ['友達', 'ともだち', None, None], [None, None, 'であればこそ', True], [None, None, '、', None], ['Ｘ', 'エックス', None, None], [None, None, 'さんの', None], ['計画', 'けいかく', None, None], [None, None, 'に', None], ['反対', 'はんたい', None, None], [None, None, 'なんです。」', None]]

 93%|█████████▎| 877/938 [09:07<00:33,  1.84it/s]

[[None, None, '「ミーティングは', None], ['明後日', 'みょうごにち', None, None], [None, None, 'でも', None], ['差', 'さ', None, True], [None, None, 'し', True], ['支', 'つか', None, True], [None, None, 'えありません', True], [None, None, '。」', None]]
[['電車', 'でんしゃ', None, None], [None, None, '：「ここに', None], ['座', 'すわ', None, None], [None, None, 'っても', None], ['差', 'さ', None, True], [None, None, 'し', True], ['支', 'つか', None, True], [None, None, 'えありません', True], [None, None, 'か？」', None]]
[['部下', 'ぶか', None, None], [None, None, '：「', None], ['今日', 'きょう', None, None], [None, None, 'は', None], ['定時', 'ていじ', None, None], [None, None, 'に', None], ['帰', 'かえ', None, None], [None, None, 'っても', None], ['差', 'さ', None, True], [None, None, 'し', True], ['支', 'つか', None, True], [None, None, 'えありません', True], [None, None, 'か？」', None]]
[['医者', 'いしゃ', None, None], [None, None, 'に', None], [None, None, '：「この', None], ['薬', 'くすり', None, None], [None, None, 'とその', None], ['薬', 'くすり', None, None], [None, None, 'を', None], ['一緒', 'いっしょ', None, None], [None, None, 'に', None], ['飲', 'の', None, None], [None, None, 'んでも', None], ['差', 'さ', None, True], [None, None, 'し', True], ['支', 'つか', None, True], [None, None, 'えないでしょう', True], [None, None, 'か？」', None]]
[['営業', 'えいぎょう', None, None], ['担当者', 'たんとうしゃ', None, None], [None, None, '：「', None], ['明日', 'あした', None, None], [None, None, '、お', None], ['電話', 'でんわ', None, None], ['差', 'さ', None, None], [None, None, 'し', None], ['上', 'あ', None, None], [None, None, 'げても', None], ['差', 'さ', None, True], [None, None, 'し', True], ['支', 'つか', None, True], [None, None, 'えございません', True], [None, None, 'か？」', None], [None, None, 'クライアント', None], [None, None, '：「はい、', None], ['問題', 'もんだい', None, None], [None, None, 'ありません。」', None]]

 94%|█████████▎| 878/938 [09:07<00:31,  1.88it/s]

[[None, None, '「', None], ['待', 'ま', None, None], [None, None, 'って、', None], ['私', 'わたし', None, None], [None, None, 'も', None], ['行', 'い', None, None], [None, None, 'くよ。」「いえ、それ', None], [None, None, 'には', True], ['及', 'およ', None, True], [None, None, 'びません', True], [None, None, '。」', None]]
[[None, None, 'リモートワークやオンライン', None], ['会議', 'かいぎ', None, None], [None, None, 'が', None], ['主流', 'しゅりゅう', None, None], [None, None, 'なのに、わざわざ', None], ['会議', 'かいぎ', None, None], [None, None, 'の', None], ['為', 'ため', None, None], [None, None, 'にこちらまでお', None], ['越', 'こ', None, None], [None, None, 'しいただく', None], [None, None, 'には', True], ['及', 'およ', None, True], [None, None, 'びません', True], [None, None, '。', None]]
[[None, None, 'はいだ', None], [None, None, '：「れつこさんの', None], ['顔色', 'かおいろ', None, None], [None, None, 'が', None], ['悪', 'わる', None, None], [None, None, 'いね。」', None], [None, None, 'れつこ', None], [None, None, '：「ご', None], ['心配', 'しんぱい', None, None], [None, None, 'には', True], ['及', 'およ', None, True], [None, None, 'びません', True], [None, None, '。ただちょっと', None], ['元気', 'げんき', None, None], [None, None, 'がないだけです。」', None]]
[['普通', 'ふつう', None, None], [None, None, 'の', None], ['人', 'ひと', None, None], [None, None, '：「', None], [None, None, 'ありがとう', None], [None, None, 'ございました。」', None], ['偉', 'えら', None, None], [None, None, 'い', None], ['人', 'ひと', None, None], [None, None, '：「いや、', None], ['礼', 'れい', None, None], [None, None, 'には', True], ['及', 'およ', None, True], [None, None, 'びません', True], [None, None, '。」', None]]
[['小説', 'しょうせつ', None, None], [None, None, '、バトラー', None], [None, None, '：「', None], ['気', 'き', None, None], [None, None, 'に', None], ['入', 'い', None, None], [None, None, 'ったなら、', None], ['何', 'なに', None, None], [None, None, 'か', None], ['食', 'た', None, None], [None, None, 'べるものでもお', None], ['支度', 'したく', None, None], ['致', 'いた', None, None], [None, None, 'しましょうか。」', None], [None, None, 'ゲスト', None], [None, None, '：「いいえ、それ', None], [None, None, 'には', True], ['及', 'およ', None, True], [None, None, 'びません', True], [None, None, '。」', None]]

 94%|█████████▎| 879/938 [09:08<00:30,  1.92it/s]

[['映画', 'えいが', None, None], [None, None, 'は', None], ['実情', 'じつじょう', None, None], [None, None, 'に', True], ['即', 'そく', None, True], [None, None, 'して', True], ['制作', 'せいさく', None, None], [None, None, 'されたものだ。', None]]
[['経済', 'けいざい', None, None], ['状況', 'じょうきょう', None, None], [None, None, 'に', True], ['即', 'そく', None, True], [None, None, 'して', True], ['課税', 'かぜい', None, None], [None, None, 'を', None], ['調整', 'ちょうせい', None, None], [None, None, 'する', None], ['必要', 'ひつよう', None, None], [None, None, 'がある。', None]]
[['役職', 'やくしょく', None, None], [None, None, 'に', None], ['関', 'かか', None, None], [None, None, 'わらず、ルール', None], [None, None, 'に', True], ['即', 'そく', None, True], [None, None, 'して', True], ['平等', 'びょうどう', None, None], [None, None, 'に', None], ['罰', 'ばっ', None, None], [None, None, 'せられるべきだ。', None]]
[['現実', 'げんじつ', None, None], [None, None, 'に', True], ['即', 'そく', None, True], [None, None, 'して', True], ['撮', 'と', None, None], [None, None, 'られたホラー', None], ['系', 'けい', None, None], [None, None, 'のドキュメンタリーほど', None], ['怖', 'こわ', None, None], [None, None, 'いものはありません。', None]]
[['ＭｃＲｏｎａｌｄ', 'マクロナルド', None, None], ['社', 'しゃ', None, None], [None, None, 'と', None], ['ＳＦＣ', 'エスエフシー', None, None], ['社', 'しゃ', None, None], [None, None, 'との', None], ['抗争', 'こうそう', None, None], [None, None, 'は', None], ['現地', 'げんち', None, None], [None, None, 'の', None], ['法律', 'ほうりつ', None, None], [None, None, 'に', True], ['即', 'そく', None, True], [None, None, 'して', True], ['処理', 'しょり', None, None], [None, None, 'される。', None]]

 94%|█████████▍| 880/938 [09:08<00:32,  1.81it/s]

[[None, None, 'これは', None], ['不可能', 'ふかのう', None, None], [None, None, 'ではない', None], [None, None, 'までも', True], [None, None, '、', None], ['実行', 'じっこう', None, None], [None, None, 'するのは', None], ['困難', 'こんなん', None, None], [None, None, 'である。', None]]
[[None, None, 'クビにはしない', None], [None, None, 'までも', True], [None, None, '、', None], ['確実', 'かくじつ', None, None], [None, None, 'にボーナスは', None], ['減額', 'げんがく', None, None], [None, None, 'するつもりだ。', None]]
[[None, None, 'リザ', None], [None, None, '：「', None], ['大谷', 'おおや', None, None], [None, None, 'は', None], ['一番', 'いちばん', None, None], [None, None, 'ハンサムといわない', None], [None, None, 'までも', True], [None, None, '、かなりカッコいい', None], ['男', 'おとこ', None, None], [None, None, 'だと', None], ['思', 'おも', None, None], [None, None, 'うよ。」', None]]
[['急速', 'きゅうそく', None, None], ['充電', 'じゅうでん', None, None], [None, None, 'はバッテリーを', None], ['直', 'ただ', None, None], [None, None, 'ちに', None], ['駄目', 'だめ', None, None], [None, None, 'にしない', None], [None, None, 'までも', True], [None, None, '、', None], ['性能', 'せいのう', None, None], [None, None, 'をより', None], ['速', 'はや', None, None], [None, None, 'く', None], ['低下', 'ていか', None, None], [None, None, 'させる。', None]]
[['初', 'はじ', None, None], [None, None, 'めて', None], ['ＪＬＰＴ', 'ジェーエルピーティー', None, None], [None, None, ' ', None], ['Ｎ', 'エヌ', None, None], ['１', 'いち', None, None], [None, None, 'を', None], ['受験', 'じゅけん', None, None], [None, None, 'したが、', None], ['合格', 'ごうかく', None, None], [None, None, 'できない', None], [None, None, 'までも', True], [None, None, '、せめて', None], ['８０', 'はちじゅっ', None, None], ['点', 'てん', None, None], [None, None, 'は', None], ['得点', 'とくてん', None, None], [None, None, 'できたい。', None]]

 94%|█████████▍| 881/938 [09:09<00:32,  1.76it/s]

[[None, None, 'メアリーと', None], ['武', 'たけし', None, None], [None, None, 'は', None], ['親', 'おや', None, None], [None, None, 'の', None], ['反対', 'はんたい', None, None], [None, None, 'を', True], ['余所', 'よそ', None, True], [None, None, 'に', True], ['一緒', 'いっしょ', None, None], [None, None, 'になった。', None]]
[['母', 'はは', None, None], [None, None, 'の', None], ['心配', 'しんぱい', None, None], [None, None, 'を', True], ['余所', 'よそ', None, True], [None, None, 'に', True], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'は', None], ['商船', 'しょうせん', None, None], [None, None, 'の', None], ['船員', 'せんいん', None, None], [None, None, 'になった。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['泣', 'な', None, None], [None, None, 'いている', None], ['子猫', 'こねこ', None, None], [None, None, 'を', True], ['余所', 'よそ', None, True], [None, None, 'に', True], [None, None, '、そのまま', None], ['猫', 'ねこ', None, None], [None, None, 'を', None], ['置', 'お', None, None], [None, None, 'き', None], ['去', 'ざ', None, None], [None, None, 'りにして', None], ['行', 'い', None, None], [None, None, 'ったのです。', None]]
[[None, None, 'ピーターは', None], ['周', 'まわ', None, None], [None, None, 'りの', None], ['忠告', 'ちゅうこく', None, None], [None, None, 'を', True], ['余所', 'よそ', None, True], [None, None, 'に', True], [None, None, '、', None], ['ＭＭＯ', 'エムエムオー', None, None], ['ＲＰＧ', 'アールピージー', None, None], [None, None, 'ゲームばかりすることを', None], ['存分', 'ぞんぶん', None, None], [None, None, 'に', None], ['楽', 'たの', None, None], [None, None, 'しんだ。', None]]
[['私', 'わたし', None, None], [None, None, 'たちがその', None], ['衝撃的', 'しょうげきてき', None, None], [None, None, 'な', None], ['言葉', 'ことば', None, None], [None, None, 'の', None], ['意味', 'いみ', None, None], [None, None, 'をまだ', None], ['飲', 'の', None, None], [None, None, 'み', None], ['込', 'こ', None, None], [None, None, 'めてないの', None], [None, None, 'を', True], ['余所', 'よそ', None, True], [None, None, 'に', True], ['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['説明', 'せつめい', None, None], [None, None, 'を', None], ['続', 'つづ', None, None], [None, None, 'けた。', None]]

 94%|█████████▍| 882/938 [09:09<00:32,  1.72it/s]

[['浮気', 'うわき', None, None], [None, None, 'をするのは', None], ['男性', 'だんせい', None, None], [None, None, 'に', True], ['限', 'かぎ', None, True], [None, None, 'ったことではない', True], [None, None, '。', None]]
[['地震', 'じしん', None, None], [None, None, 'が', None], ['頻繁', 'ひんぱん', None, None], [None, None, 'に', None], ['起', 'お', None, None], [None, None, 'きるのは', None], ['日本', 'にほん', None, None], [None, None, 'に', True], ['限', 'かぎ', None, True], [None, None, 'ったことではありません', True], [None, None, '。', None]]
[['不幸', 'ふこう', None, None], [None, None, 'が', None], ['連続', 'れんぞく', None, None], [None, None, 'して', None], ['起', 'お', None, None], [None, None, 'こるのは', None], ['自分', 'じぶん', None, None], [None, None, 'に', True], ['限', 'かぎ', None, True], [None, None, 'ったことではない', True], [None, None, 'と', None], ['信', 'しん', None, None], [None, None, 'じている。', None]]
[['子犬', 'こいぬ', None, None], [None, None, 'にメロメロになるのは', None], ['女', 'おんな', None, None], [None, None, 'の', None], ['子', 'こ', None, None], [None, None, 'に', True], ['限', 'かぎ', None, True], [None, None, 'ったことではない', True], [None, None, '。', None], ['父', 'ちち', None, None], [None, None, 'もメロメロだ。', None]]
[['松岡', 'まつおか', None, None], [None, None, 'さん', None], [None, None, 'が', None], ['宿題', 'しゅくだい', None, None], [None, None, 'を', None], ['忘', 'わす', None, None], [None, None, 'れ', None], [None, None, 'る', None], [None, None, 'の', None], [None, None, 'は', None], ['今日', 'きょう', None, None], [None, None, 'に', True], ['限', 'かぎ', None, True], [None, None, 'ったことではない', True], [None, None, '。', None]]

 94%|█████████▍| 883/938 [09:10<00:33,  1.67it/s]

[['私', 'わたし', None, None], [None, None, 'の', None], ['絵画', 'かいが', None, None], [None, None, 'など', None], ['須', 'す', None, None], [None, None, 'ノ', None], ['宮', 'みや', None, None], [None, None, 'さん', None], [None, None, 'の', None], [None, None, 'とは', True], ['比', 'くら', None, True], [None, None, 'べものにならない', True], [None, None, '。', None]]
[['日本', 'にほん', None, None], [None, None, 'の', None], ['地震', 'じしん', None, None], [None, None, 'の', None], ['多', 'おお', None, None], [None, None, 'さはオーストラリア', None], [None, None, 'とは', True], ['比', 'くら', None, True], [None, None, 'べものにならない', True], [None, None, '。', None]]
[['光', 'ひかり', None, None], [None, None, 'の', None], ['速', 'はや', None, None], [None, None, 'さ', None], [None, None, 'でも', None], [None, None, '、', None], [None, None, 'この', None], ['宇宙', 'うちゅう', None, None], [None, None, 'の', None], ['大', 'おお', None, None], [None, None, 'き', None], [None, None, 'さ', None], [None, None, 'とは', True], ['比', 'くら', None, True], [None, None, 'べものにならない', True], [None, None, '。', None]]
[[None, None, 'この', None], ['寿司', 'すし', None, None], [None, None, 'は', None], ['悪', 'わる', None, None], [None, None, 'く', None], [None, None, 'は', None], [None, None, 'ない', None], [None, None, 'が', None], ['良質', 'りょうしつ', None, None], [None, None, 'の', None], ['寿司', 'すし', None, None], [None, None, 'とは', True], ['比', 'くら', None, True], [None, None, 'べものにならない', True], [None, None, '。', None]]
[['北海道', 'ほっかいどう', None, None], [None, None, 'は', None], ['寒', 'さむ', None, None], [None, None, 'い', None], [None, None, 'といえども', None], [None, None, 'シベリア', None], [None, None, 'とは', True], ['比', 'くら', None, True], [None, None, 'べものにならない', True], [None, None, 'と', None], ['思', 'おも', None, None], [None, None, 'う', None], [None, None, '。', None]]

 94%|█████████▍| 884/938 [09:11<00:33,  1.63it/s]

[[None, None, 'リヒャルトは', None], ['王', 'おう', None, None], [None, None, 'としてあるまじき', True], ['汚名', 'おめい', None, None], [None, None, 'を', None], ['着', 'き', None, None], [None, None, 'せられ、やがて', None], ['廃位', 'はいい', None, None], [None, None, 'された。', None]]
[['言', 'い', None, None], [None, None, 'うまでもないが、', None], ['公金', 'こうきん', None, None], ['横領', 'おうりょう', None, None], [None, None, 'など', None], ['政治家', 'せいじか', None, None], [None, None, 'としてあるまじき', True], ['行為', 'こうい', None, None], [None, None, 'だ。', None]]
[['妻', 'つま', None, None], [None, None, 'を', None], ['下', 'さ', None, None], [None, None, 'げるような', None], ['発言', 'はつげん', None, None], [None, None, 'をするなんて、', None], ['夫', 'おっと', None, None], [None, None, 'にあるまじき', True], ['行為', 'こうい', None, None], [None, None, 'だ。', None]]
[['戦場', 'せんじょう', None, None], [None, None, 'から', None], ['離脱', 'りだつ', None, None], [None, None, 'することは', None], ['武士', 'ぶし', None, None], [None, None, 'にあるまじき', True], ['行為', 'こうい', None, None], [None, None, 'と', None], ['咎', 'とが', None, None], [None, None, 'められ、', None], ['罰', 'ばっ', None, None], [None, None, 'せられた。', None]]
[[None, None, 'ララティーナは', None], ['貴族', 'きぞく', None, None], [None, None, 'にあるまじき', True], ['態度', 'たいど', None, None], [None, None, 'で、', None], ['甘', 'あま', None, None], [None, None, 'やかされた', None], ['子供', 'こども', None, None], [None, None, 'のようなふるまいをした。', None]]

 94%|█████████▍| 885/938 [09:11<00:31,  1.71it/s]

[['演説', 'えんぜつ', None, None], [None, None, '：「', None], ['特別賞', 'とくべつしょう', None, None], [None, None, 'を', None], ['受賞', 'じゅしょう', None, None], [None, None, 'することになり、', None], ['光栄', 'こうえい', None, None], [None, None, 'の', True], ['至', 'いた', None, True], [None, None, 'り', True], [None, None, 'です。」', None]]
[[None, None, '「このような', None], ['小', 'ちい', None, None], [None, None, 'さな', None], ['誤', 'あやま', None, None], [None, None, 'りに', None], ['気', 'き', None, None], [None, None, 'づくのに', None], ['数', 'すう', None, None], ['日', 'じつ', None, None], [None, None, 'もかかるとは、', None], ['赤面', 'せきめん', None, None], [None, None, 'の', True], ['至', 'いた', None, True], [None, None, 'り', True], [None, None, 'です。」', None]]
[['演説', 'えんぜつ', None, None], [None, None, '：「たいそうな', None], ['品', 'しな', None, None], [None, None, 'をいただき、', None], ['恐縮', 'きょうしゅく', None, None], [None, None, 'の', True], ['至', 'いた', None, True], [None, None, 'り', True], [None, None, 'です。」', None]]
[[None, None, 'インタビュー', None], [None, None, '：「ファンや', None], ['映画', 'えいが', None, None], ['評論家', 'ひょうろんか', None, None], [None, None, 'の', None], ['皆', 'みな', None, None], [None, None, 'さまから', None], ['肯定的', 'こうていてき', None, None], [None, None, 'なレビューをいただき、', None], ['感激', 'かんげき', None, None], [None, None, 'の', True], ['至', 'いた', None, True], [None, None, 'り', True], [None, None, 'です」', None]]
[['伝記', 'でんき', None, None], [None, None, '：「', None], ['若気', 'わかげ', None, None], [None, None, 'の', True], ['至', 'いた', None, True], [None, None, 'り', True], [None, None, 'で、', None], ['給料', 'きゅうりょう', None, None], [None, None, 'の', None], ['良', 'よ', None, None], [None, None, 'い', None], ['仕事', 'しごと', None, None], [None, None, 'を', None], ['辞', 'や', None, None], [None, None, 'めて', None], ['独立', 'どくりつ', None, None], ['開業', 'かいぎょう', None, None], [None, None, 'した。」', None]]

 94%|█████████▍| 886/938 [09:12<00:31,  1.65it/s]

[[None, None, 'サハラ', None], ['砂漠', 'さばく', None, None], [None, None, 'の', None], ['名', 'な', None, None], [None, None, 'に', True], ['恥', 'は', None, True], [None, None, 'じない', True], ['天候', 'てんこう', None, None], [None, None, 'だ。', None]]
[['店', 'みせ', None, None], [None, None, 'のウェブサイト', None], [None, None, '：「', None], ['当店', 'とうてん', None, None], [None, None, 'は', None], ['８０', 'はちじゅう', None, None], ['年', 'ねん', None, None], ['培', 'つちか', None, None], [None, None, 'った', None], ['信頼', 'しんらい', None, None], [None, None, 'と', None], ['伝統', 'でんとう', None, None], [None, None, 'に', True], ['恥', 'は', None, True], [None, None, 'じない', True], [None, None, 'サービスをご', None], ['提供致', 'ていきょういた', None, None], [None, None, 'します。」', None]]
[['昇格', 'しょうかく', None, None], [None, None, 'する', None], ['演説', 'えんぜつ', None, None], [None, None, '：「ブランド', None], ['名', 'めい', None, None], [None, None, 'に', True], ['恥', 'は', None, True], [None, None, 'じない', True], [None, None, 'よう、', None], ['精一杯', 'せいいっぱい', None, None], ['努', 'つと', None, None], [None, None, 'めさせていただきます。」', None]]
[[None, None, 'ホテルのウェブサイト', None], [None, None, '：「', None], ['五', 'いつ', None, None], [None, None, 'つ', None], ['星', 'ぼし', None, None], [None, None, 'ホテルの', None], ['名', 'な', None, None], [None, None, 'に', True], ['恥', 'は', None, True], [None, None, 'じない', True], [None, None, 'サービスをお', None], ['客様', 'きゃくさま', None, None], [None, None, 'に', None], ['提供', 'ていきょう', None, None], [None, None, 'しております。」', None]]
[['受賞', 'じゅしょう', None, None], [None, None, 'の', None], ['演説', 'えんぜつ', None, None], [None, None, '：「この', None], ['賞', 'しょう', None, None], [None, None, 'に', True], ['恥', 'は', None, True], [None, None, 'じない', True], [None, None, 'よう、これからも', None], ['最善', 'さいぜん', None, None], [None, None, 'を', None], ['尽', 'つ', None, None], [None, None, 'くすつもりです。」', None]]

 95%|█████████▍| 887/938 [09:12<00:29,  1.73it/s]

[['Ａ', 'エー', None, None], [None, None, '：「', None], ['結局', 'けっきょく', None, None], [None, None, '、', None], [None, None, 'やらずじまい', True], [None, None, 'で', None], ['新', 'しん', None, None], ['学期', 'がっき', None, None], [None, None, 'になっちゃった', None], [None, None, 'よ', None], [None, None, '。」', None], ['Ｂ', 'ビー', None, None], [None, None, '：「なにをやらなかったの？」', None], ['Ａ', 'エー', None, None], [None, None, '：「', None], ['夏休', 'なつやす', None, None], [None, None, 'み', None], [None, None, 'の', None], ['宿題', 'しゅくだい', None, None], [None, None, '…」', None]]
[[None, None, '「', None], ['宇崎', 'うざき', None, None], [None, None, 'さんと', None], ['映画館', 'えいがかん', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'こうと', None], ['思', 'おも', None, None], [None, None, 'っていたけど、', None], ['仕事', 'しごと', None, None], [None, None, 'から', None], ['手', 'て', None, None], [None, None, 'が', None], ['離', 'はな', None, None], [None, None, 'せなくて', None], ['結局', 'けっきょく', None, None], ['行', 'い', None, True], [None, None, 'けずじまい', True], [None, None, 'だった。」', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「', None], ['事故', 'じこ', None, None], [None, None, 'の', None], ['原因', 'げんいん', None, None], [None, None, 'について', None], ['調', 'しら', None, None], [None, None, 'べようとしたが、ついに', None], [None, None, 'わからずじまい', True], [None, None, 'だった。」', None]]
[[None, None, '「', None], ['最新', 'さいしん', None, None], [None, None, 'の', None], ['愛', 'あい', None, None], ['Ｐｈｏｎｅ', 'フォン', None, None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'おうとストアに', None], ['１０', 'じゅう', None, None], ['時間', 'じかん', None, None], ['並', 'なら', None, None], [None, None, 'んだのに、', None], ['自分', 'じぶん', None, None], [None, None, 'の', None], ['番', 'ばん', None, None], [None, None, 'が', None], ['来', 'く', None, None], [None, None, 'る', None], ['頃', 'ころ', None, None], [None, None, 'には', None], ['欲', 'ほ', None, None], [None, None, 'しい', None], ['色', 'いろ', None, None], [None, None, 'がもう', None], ['売', 'う', None, None], [None, None, 'り', None], ['切', 'き', None, None], [None, None, 'れていて', None], ['結局', 'けっきょく', None, None], ['買', 'か', None, True], [None, None, 'えずじまい', True], [None, None, 'だった。」', None]]
[[None, None, '「', None], ['日本語', 'にほんご', None, None], [None, None, 'の', None], ['教科書', 'きょうかしょ', None, None], [None, None, 'をたくさん', None], ['買', 'か', None, None], [None, None, 'ったけど、', None], ['結局', 'けっきょく', None, None], ['使', 'つか', None, True], [None, None, 'わずじまい', True], [None, None, 'だった。」', None]]

 95%|█████████▍| 888/938 [09:13<00:30,  1.62it/s]

[['私', 'わたし', None, None], [None, None, 'に', True], ['言', 'い', None, True], [None, None, 'わせれば', True], [None, None, 'あなたが', None], ['買', 'か', None, None], [None, None, 'ったスマホは', None], ['不', 'ふ', None, None], ['良品', 'りょうひん', None, None], [None, None, 'だよ。もう', None], ['３回', 'さんかい', None, None], [None, None, 'も', None], ['壊', 'こわ', None, None], [None, None, 'れたんだから！', None]]
[[None, None, 'ドイツ', None], ['側', 'がわ', None, None], [None, None, 'に', True], ['言', 'い', None, True], [None, None, 'わせれば', True], [None, None, 'オーストラリア', None], ['企業', 'きぎょう', None, None], [None, None, 'は', None], ['初', 'はじ', None, None], [None, None, 'めは', None], ['経済', 'けいざい', None, None], ['協力', 'きょうりょく', None, None], [None, None, 'に', None], ['反対', 'はんたい', None, None], [None, None, 'していたという。', None]]
[['会社', 'かいしゃ', None, None], [None, None, 'の', None], ['観点', 'かんてん', None, None], [None, None, 'からすれば、', None], ['結果', 'けっか', None, None], [None, None, 'は', None], ['失敗', 'しっぱい', None, None], [None, None, 'とみなされるかもしれないが、', None], ['少', 'すく', None, None], [None, None, 'なくとも', None], ['私', 'わたし', None, None], [None, None, 'に', True], ['言', 'い', None, True], [None, None, 'わせれば', True], [None, None, '、', None], ['完全', 'かんぜん', None, None], [None, None, 'な', None], ['失敗', 'しっぱい', None, None], [None, None, 'というわけではない。', None]]
[['君', 'きみ', None, None], [None, None, 'にとっては', None], ['面白', 'おもしろ', None, None], [None, None, 'いのだろうが、', None], ['私', 'わたし', None, None], [None, None, 'に', True], ['言', 'い', None, True], [None, None, 'わせれば', True], [None, None, '、ただの', None], ['無礼', 'ぶれい', None, None], [None, None, 'にしかすぎない。', None]]
[['武田', 'たけだ', None, None], [None, None, 'さん', None], [None, None, 'に', True], ['言', 'い', None, True], [None, None, 'わせれば', True], [None, None, '、', None], ['最近', 'さいきん', None, None], [None, None, 'の', None], ['若者', 'わかもの', None, None], [None, None, 'はまったくお', None], ['年寄', 'としよ', None, None], [None, None, 'りを', None], ['敬', 'うやま', None, None], [None, None, 'わないとのこと。', None]]

 95%|█████████▍| 889/938 [09:14<00:30,  1.58it/s]

[[None, None, '「', None], ['凹凸', 'おうとつ', None, None], [None, None, 'の', None], ['多', 'おお', None, None], [None, None, 'い', None], ['地形', 'ちけい', None, None], [None, None, 'は', None], ['走', 'はし', None, None], [None, None, 'りにくい', None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'ったらありはしない', True], [None, None, '。」', None]]
[[None, None, '「', None], ['犬', 'いぬ', None, None], [None, None, 'を', None], ['飼', 'か', None, None], [None, None, 'ったのに', None], ['世話', 'せわ', None, None], [None, None, 'をしないなんて、', None], ['無責任', 'むせきにん', None, None], [None, None, 'ったらありゃしない', True], [None, None, '。」', None]]
[['上司', 'じょうし', None, None], [None, None, '：「', None], ['君', 'きみ', None, None], [None, None, 'は', None], ['毎日', 'まいにち', None, None], ['毎日', 'まいにち', None, None], [None, None, '、', None], ['会社', 'かいしゃ', None, None], [None, None, 'に', None], ['遅刻', 'ちこく', None, None], [None, None, 'して', None], ['来', 'き', None, None], [None, None, 'て。', None], ['見苦', 'みぐる', None, None], [None, None, 'しい', None], [None, None, 'ったらありゃしない', True], [None, None, 'ぞ。」', None]]
[[None, None, '「さだおさんの', None], ['企業', 'きぎょう', None, None], [None, None, 'が', None], ['倒産', 'とうさん', None, None], [None, None, 'してからの', None], ['元', 'もと', None, None], ['従業員', 'じゅうぎょういん', None, None], [None, None, 'の', None], ['連中', 'れんちゅう', None, None], [None, None, 'の', None], ['態度', 'たいど', None, None], [None, None, 'と', True], ['言', 'い', None, True], [None, None, 'ったらありゃしない', True], [None, None, '。」', None]]
[[None, None, '「', None], ['昨晩', 'さくばん', None, None], ['遅', 'おそ', None, None], [None, None, 'くに', None], ['帰宅', 'きたく', None, None], [None, None, 'したルームメイトに', None], ['起', 'お', None, None], [None, None, 'こされた。', None], ['腹', 'はら', None, None], [None, None, 'がたつ', None], [None, None, 'ったらありゃしない', True], [None, None, '。」', None]]
[['時代', 'じだい', None, None], ['劇', 'げき', None, None], [None, None, '、', None], ['Ａ', 'エー', None, None], [None, None, '：「あなたのお', None], ['父', 'とう', None, None], [None, None, 'さんによろしくお', None], ['伝', 'つた', None, None], [None, None, 'えください。」', None], ['Ｂ', 'ビー', None, None], [None, None, '：「お', None], ['父', 'とう', None, None], [None, None, 'さんは', None], ['遥', 'はる', None, None], [None, None, 'か', None], ['昔', 'むかし', None, None], [None, None, 'に', None], ['亡', 'な', None, None], [None, None, 'くなりました。」', None], ['Ａ', 'エー', None, None], [None, None, '：「そうでしたか。', None], ['知', 'し', None, None], [None, None, 'らぬ', None], [None, None, 'こととて', True], [None, None, '、', None], ['失礼', 'しつれい', None, None], [None, None, 'をお', None], ['許', 'ゆる', None, None], [None, None, 'しください。」', None]]
[['古', 'ふる', None, None], [None, None, 'い', None], ['手紙', 'てがみ', None, None], [None, None, '：「', None], ['取', 'と', None, None], [None, None, 'り', None], ['込', 'こ', None, None], [None, None, 'み', None], ['中', 'ちゅう', None, None], [None, None, 'の', None], [None, None, 'こととて', True], [None, None, 'ご', None], ['迷惑', 'めいわく', None, None], [None, None, 'をおかけしましたがなにとぞご', None], ['寛容', 'かんよう', None, None], [None, None, 'のほどお', None], ['願', 'ねが', None, None], [None, None, 'い', None], ['申', 'もう', None, None], [None, None, 'し', None], ['上', 'あ', None, None], [None, None, 'げます。」', None]]

 95%|█████████▍| 890/938 [09:15<00:35,  1.36it/s]

[[None, None, '「', None], ['仕事', 'しごと', None, None], [None, None, 'になれぬ', None], [None, None, 'こととて', True], ['間違', 'まちが', None, None], [None, None, 'いをしてしまいました。', None], ['申', 'もう', None, None], [None, None, 'し', None], ['訳', 'わけ', None, None], [None, None, 'ございません。」', None]]
[[None, None, '「', None], ['田舎', 'いなか', None, None], [None, None, 'の', None], [None, None, 'こととて', True], ['年齢', 'ねんれい', None, None], [None, None, 'や', None], ['学年', 'がくねん', None, None], [None, None, 'に', None], ['関係', 'かんけい', None, None], [None, None, 'なく', None], ['生徒', 'せいと', None, None], [None, None, 'が', None], ['勉強', 'べんきょう', None, None], [None, None, 'する', None], ['教室', 'きょうしつ', None, None], [None, None, 'が', None], ['１', 'いち', None, None], ['教室', 'きょうしつ', None, None], [None, None, 'だけしかなかった。」', None]]
[[None, None, '「', None], ['子供', 'こども', None, None], [None, None, 'がやった', None], [None, None, 'こととて', True], [None, None, '、', None], ['親', 'おや', None, None], [None, None, 'としてお', None], ['詫', 'わ', None, None], [None, None, 'び', None], ['申', 'もう', None, None], [None, None, 'し', None], ['上', 'あ', None, None], [None, None, 'げます。」', None]]

 95%|█████████▍| 891/938 [09:15<00:31,  1.49it/s]

[['新聞', 'しんぶん', None, None], [None, None, 'の', None], ['見出', 'みだ', None, None], [None, None, 'し', None], [None, None, '：「', None], ['６月', 'ろくがつ', None, None], ['猛暑', 'もうしょ', None, None], ['記録', 'きろく', None, None], [None, None, 'ずくめ', True], [None, None, '」', None]]
[['規制', 'きせい', None, None], [None, None, 'は', None], ['必要', 'ひつよう', None, None], [None, None, 'であるが', None], ['規則', 'きそく', None, None], [None, None, 'ずくめ', True], [None, None, 'で', None], ['窒息', 'ちっそく', None, None], [None, None, 'しそうな', None], ['社会', 'しゃかい', None, None], [None, None, 'は', None], ['強圧的', 'きょうあつてき', None, None], [None, None, 'ではないだろうか。', None]]
[['２０２０', 'にせんにじゅう', None, None], ['年', 'ねん', None, None], [None, None, 'は', None], ['異例', 'いれい', None, None], [None, None, 'ずくめ', True], [None, None, 'の', None], ['大変', 'たいへん', None, None], [None, None, 'な', None], ['年', 'とし', None, None], [None, None, 'でしたが', None], ['何', 'なん', None, None], [None, None, 'とか', None], ['乗', 'の', None, None], [None, None, 'り', None], ['切', 'き', None, None], [None, None, 'りました。', None]]
[[None, None, 'ツイッターの', None], ['投稿', 'とうこう', None, None], [None, None, '：「', None], ['朝', 'あさ', None, None], [None, None, 'から', None], ['晩', 'ばん', None, None], [None, None, 'まで、ごちそう', None], [None, None, 'ずくめ', True], [None, None, 'で', None], ['結婚', 'けっこん', None, None], [None, None, 'を', None], ['祝', 'いわ', None, None], [None, None, 'う。」', None]]
[['黒', 'くろ', None, None], [None, None, 'ずくめ', True], [None, None, 'のスーツに', None], ['身', 'み', None, None], [None, None, 'を', None], ['包', 'つつ', None, None], [None, None, 'んだ', None], ['男', 'おとこ', None, None], [None, None, 'はベンチに', None], ['座', 'すわ', None, None], [None, None, 'り、', None], ['逆', 'さか', None, None], [None, None, 'さに', None], ['持', 'も', None, None], [None, None, 'った', None], ['新聞', 'しんぶん', None, None], [None, None, 'を', None], ['読', 'よ', None, None], [None, None, 'むふりをしていた。', None]]

 95%|█████████▌| 892/938 [09:16<00:28,  1.60it/s]

[['言', 'い', None, None], [None, None, 'うまでもなく', None], ['真作', 'しんさく', None, None], [None, None, 'には', True], ['及', 'およ', None, True], [None, None, 'ばない', True], [None, None, 'でしょうが、いい', None], ['贋作', 'がんさく', None, None], [None, None, 'です。', None]]
[[None, None, '「', None], ['物理学', 'ぶつりがく', None, None], [None, None, 'では、とてもアルバート', None], [None, None, 'には', True], ['及', 'およ', None, True], [None, None, 'ばない', True], [None, None, '。」', None]]
[['続編', 'ぞくへん', None, None], [None, None, 'は', None], ['立派', 'りっぱ', None, None], [None, None, 'なものの、', None], ['明', 'あき', None, None], [None, None, 'らかに', None], ['最初', 'さいしょ', None, None], [None, None, 'の', None], ['映画', 'えいが', None, None], [None, None, 'には', True], ['及', 'およ', None, True], [None, None, 'ばない', True], [None, None, '。', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「はるこの', None], ['嗅覚', 'きゅうかく', None, None], [None, None, 'は、', None], ['犬', 'いぬ', None, None], [None, None, 'には', True], ['及', 'およ', None, True], [None, None, 'ばない', True], [None, None, 'が、', None], ['普通', 'ふつう', None, None], [None, None, 'の', None], ['人間', 'にんげん', None, None], [None, None, 'のよりはるかにすぐれている。」', None]]
[[None, None, '「どんなに', None], ['練習', 'れんしゅう', None, None], [None, None, 'してもさいたま', None], ['先生', 'せんせい', None, None], [None, None, 'の', None], ['足元', 'あしもと', None, None], [None, None, 'には', True], ['及', 'およ', None, True], [None, None, 'ばない', True], [None, None, '。」', None]]

 95%|█████████▌| 893/938 [09:16<00:26,  1.70it/s]

[['数学', 'すうがく', None, None], [None, None, 'は', None], ['時間', 'じかん', None, None], [None, None, 'の', None], ['無駄', 'むだ', None, None], [None, None, 'だ', None], [None, None, 'とは', True], ['言', 'い', None, True], [None, None, 'うものの', True], [None, None, '、やはり', None], ['基本', 'きほん', None, None], [None, None, 'を', None], ['知', 'し', None, None], [None, None, 'る', None], ['価値', 'かち', None, None], [None, None, 'だってある。', None]]
[['彼', 'かれ', None, None], [None, None, 'はホラー', None], ['作家', 'さっか', None, None], [None, None, 'として', None], ['知', 'し', None, None], [None, None, 'られている', None], [None, None, 'とは', True], ['言', 'い', None, True], [None, None, 'うものの', True], [None, None, '、', None], ['傑作', 'けっさく', None, None], [None, None, 'と', None], ['言', 'い', None, None], [None, None, 'えるものは', None], ['１９８２', 'せんきゅうひゃくはちじゅうに', None, None], ['年', 'ねん', None, None], [None, None, 'に', None], ['出版', 'しゅっぱん', None, None], [None, None, 'された', None], ['犯罪', 'はんざい', None, None], ['小説', 'しょうせつ', None, None], [None, None, 'だ。', None]]
[[None, None, 'チェコの「ストラホフ・スタジアム」は「', None], ['世界', 'せかい', None, None], ['最大', 'さいだい', None, None], [None, None, 'のスポーツスタジアム」', None], [None, None, 'とは', True], ['言', 'い', None, True], [None, None, 'うものの', True], [None, None, '、', None], ['実際', 'じっさい', None, None], [None, None, 'にはスポーツ', None], ['目的', 'もくてき', None, None], [None, None, 'にはほとんど', None], ['使', 'つか', None, None], [None, None, 'われていない。', None]]
[[None, None, 'このカフェは', None], ['人気', 'にんき', None, None], [None, None, 'が', None], ['高', 'たか', None, None], [None, None, 'い', None], [None, None, 'とは', True], ['言', 'い', None, True], [None, None, 'うものの', True], [None, None, '、', None], ['実際', 'じっさい', None, None], [None, None, 'には', None], ['知', 'し', None, None], [None, None, 'る', None], ['人', 'ひと', None, None], [None, None, 'ぞ', None], ['知', 'し', None, None], [None, None, 'る', None], ['所', 'ところ', None, None], [None, None, 'だ。', None]]
[[None, None, 'それは「', None], ['人工', 'じんこう', None, None], ['知能', 'ちのう', None, None], [None, None, '」', None], [None, None, 'とは', True], ['言', 'い', None, True], [None, None, 'うものの', True], [None, None, '、まだ「', None], ['知能', 'ちのう', None, None], [None, None, '」というよりも「コンピューター」に', None], ['近', 'ちか', None, None], [None, None, 'いものだ。', None]]

 95%|█████████▌| 894/938 [09:17<00:27,  1.61it/s]

[[None, None, 'お', None], ['母', 'かあ', None, None], [None, None, 'さんがケーキを', None], ['焼', 'や', None, None], [None, None, 'き', None], ['上', 'あ', None, None], [None, None, 'げる', None], [None, None, 'が', True], ['早', 'はや', None, True], [None, None, 'いか', True], [None, None, '、お', None], ['父', 'とう', None, None], [None, None, 'さんが', None], ['食', 'た', None, None], [None, None, 'べ', None], ['始', 'はじ', None, None], [None, None, 'めた。', None]]
[['黒', 'くろ', None, None], [None, None, 'ずくめの', None], ['男', 'おとこ', None, None], [None, None, 'は', None], ['探偵', 'たんてい', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'つけた', None], [None, None, 'が', True], ['早', 'はや', None, True], [None, None, 'いか', True], [None, None, '、', None], ['疾風', 'しっぷう', None, None], [None, None, 'のごとく', None], ['駆', 'か', None, None], [None, None, 'け', None], ['出', 'だ', None, None], [None, None, 'した。', None]]
[['夜', 'よる', None, None], [None, None, '、', None], ['幼', 'おさな', None, None], [None, None, 'い', None], ['魔法使', 'まほうつか', None, None], [None, None, 'いが', None], ['窓', 'まど', None, None], [None, None, 'を', None], ['開', 'あ', None, None], [None, None, 'ける', None], [None, None, 'が', True], ['早', 'はや', None, True], [None, None, 'いか', True], [None, None, '、', None], ['白', 'しろ', None, None], [None, None, 'フクロウが', None], ['飛', 'と', None, None], [None, None, 'び', None], ['込', 'こ', None, None], [None, None, 'んできた。', None]]
[['自動', 'じどう', None, None], [None, None, 'ドアが', None], ['開', 'ひら', None, None], [None, None, 'く', None], [None, None, 'が', True], ['早', 'はや', None, True], [None, None, 'いか', True], [None, None, '、まもなく', None], ['人々', 'ひとびと', None, None], [None, None, 'は', None], ['電車', 'でんしゃ', None, None], [None, None, 'に', None], ['乗', 'の', None, None], [None, None, 'り', None], ['込', 'こ', None, None], [None, None, 'んだ。', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「', None], ['田中', 'たなか', None, None], [None, None, 'は', None], ['目', 'め', None, None], [None, None, 'が', None], ['覚', 'さ', None, None], [None, None, 'めた', None], [None, None, 'が', True], ['早', 'はや', None, True], [None, None, 'いか', True], [None, None, 'ベッドから', None], ['飛', 'と', None, None], [None, None, 'び', None], ['起', 'お', None, None], [None, None, 'きた。」', None]]

 95%|█████████▌| 895/938 [09:18<00:26,  1.60it/s]

[[None, None, 'ピラミッドが、', None], ['古代人', 'こだいじん', None, None], [None, None, 'に', None], ['畏敬', 'いけい', None, None], [None, None, 'の', None], ['念', 'ねん', None, None], [None, None, 'を', None], ['抱', 'いだ', None, None], [None, None, 'かせたであろうことは、', None], ['想像', 'そうぞう', None, None], [None, None, 'に', True], ['難', 'かた', None, True], [None, None, 'くない', True], [None, None, '。', None]]
[['飛行機', 'ひこうき', None, None], [None, None, 'が', None], ['墜落', 'ついらく', None, None], [None, None, 'すれば', None], ['乗客', 'じょうきゃく', None, None], [None, None, 'に', None], ['何', 'なに', None, None], [None, None, 'が', None], ['起', 'お', None, None], [None, None, 'こるかは', None], ['察', 'さっ', None, None], [None, None, 'する', None], [None, None, 'に', True], ['難', 'かた', None, True], [None, None, 'くない', True], [None, None, '。', None]]
[[None, None, 'その', None], ['日', 'ひ', None, None], [None, None, 'の', None], ['悲惨', 'ひさん', None, None], [None, None, 'な', None], ['出来事', 'できごと', None, None], [None, None, 'が、', None], ['大', 'おお', None, None], [None, None, 'いに', None], ['影響', 'えいきょう', None, None], [None, None, 'していただろうことは', None], ['想像', 'そうぞう', None, None], [None, None, 'に', True], ['難', 'かた', None, True], [None, None, 'くない', True], [None, None, '。', None]]
[['暴力', 'ぼうりょく', None, None], [None, None, 'に', None], ['満', 'み', None, None], [None, None, 'ちているこのゲームが', None], ['９０', 'きゅうじゅう', None, None], ['年代', 'ねんだい', None, None], [None, None, 'に', None], ['論争', 'ろんそう', None, None], [None, None, 'を', None], ['巻', 'ま', None, None], [None, None, 'き', None], ['起', 'お', None, None], [None, None, 'こした', None], ['理由', 'りゆう', None, None], [None, None, 'は', None], ['理解', 'りかい', None, None], [None, None, 'に', True], ['難', 'かた', None, True], [None, None, 'くない', True], [None, None, '。', None]]
[[None, None, 'バスの', None], ['運転手', 'うんてんしゅ', None, None], [None, None, 'がいかに', None], ['大', 'おお', None, None], [None, None, 'きな', None], ['責任', 'せきにん', None, None], [None, None, 'を', None], ['背負', 'せお', None, None], [None, None, 'っているか、', None], ['想像', 'そうぞう', None, None], [None, None, 'に', True], ['難', 'かた', None, True], [None, None, 'くない', True], [None, None, '。', None]]

 96%|█████████▌| 896/938 [09:18<00:25,  1.67it/s]

[['１万', 'いちまん', None, None], ['円', 'えん', None, None], [None, None, 'は', None], ['社会人', 'しゃかいじん', None, None], [None, None, 'ならいざ', True], ['知', 'し', None, True], [None, None, 'らず', True], [None, None, '、', None], ['小学生', 'しょうがくせい', None, None], [None, None, 'にとっては', None], ['想像', 'そうぞう', None, None], [None, None, 'を', None], ['絶', 'ぜっ', None, None], [None, None, 'する', None], ['金額', 'きんがく', None, None], [None, None, 'だ。', None]]
[['１００', 'ひゃく', None, None], ['年', 'ねん', None, None], ['前', 'まえ', None, None], [None, None, 'ならいざ', True], ['知', 'し', None, True], [None, None, 'らず', True], [None, None, '、', None], ['現代', 'げんだい', None, None], [None, None, 'のこの', None], ['国', 'くに', None, None], [None, None, 'においては', None], ['情報', 'じょうほう', None, None], [None, None, 'へのアクセスは', None], ['容易', 'ようい', None, None], [None, None, 'になっているからそのようなことを', None], ['誰', 'だれ', None, None], [None, None, 'でも', None], ['知', 'し', None, None], [None, None, 'っているはずだ。', None]]
[[None, None, '「', None], ['運動', 'うんどう', None, None], [None, None, 'は', None], ['不健康', 'ふけんこう', None, None], [None, None, 'だからしない」と', None], ['最近', 'さいきん', None, None], [None, None, 'よく', None], ['聞', 'き', None, None], [None, None, 'く。プロのスポーツ', None], ['選手', 'せんしゅ', None, None], [None, None, 'ならいざ', True], ['知', 'し', None, True], [None, None, 'らず', True], [None, None, '、', None], ['一般', 'いっぱん', None, None], [None, None, 'の', None], ['人', 'ひと', None, None], [None, None, 'ならば、', None], ['運動', 'うんどう', None, None], [None, None, 'は', None], ['有益', 'ゆうえき', None, None], [None, None, 'である。', None]]
[['Ａ', 'エー', None, None], [None, None, '：「', None], ['子供', 'こども', None, None], [None, None, 'の', None], ['頃', 'ころ', None, None], [None, None, '、ここでザリガニを', None], ['釣', 'つ', None, None], [None, None, 'ったものだ。」', None], [None, None, ' ', None], ['Ｂ', 'ビー', None, None], [None, None, '：「', None], ['昔', 'むかし', None, None], [None, None, 'ならいざ', True], ['知', 'し', None, True], [None, None, 'らず', True], [None, None, '、', None], ['現代', 'げんだい', None, None], [None, None, 'では', None], ['川', 'かわ', None, None], [None, None, 'が', None], ['汚染', 'おせん', None, None], [None, None, 'されているから\u200b\u200b', None], ['無理', 'むり', None, None], [None, None, 'です。」', None]]
[[None, None, '「', None], ['自分', 'じぶん', None, None], ['一人', 'ひとり', None, None], [None, None, 'で', None], ['衣装', 'いしょう', None, None], [None, None, 'を', None], ['着', 'き', None, None], [None, None, 'て', None], ['楽', 'たの', None, None], [None, None, 'しむの', None], [None, None, 'ならいざ', True], ['知', 'し', None, True], [None, None, 'らず', True], [None, None, '、', None], ['人前', 'ひとまえ', None, None], [None, None, 'にコスプレ', None], ['姿', 'すがた', None, None], [None, None, 'で', None], ['出', 'で', None, None], [None, None, 'るのは', None], ['私', 'わたし', None, None], [None, None, 'にとっては', None], ['不可能', 'ふかのう', None, None], [None, None, 'に', None], ['近', 'ちか', None, None], [None, None, 'いです。」', None]]

 96%|█████████▌| 897/938 [09:19<00:23,  1.78it/s]

[[None, None, 'この', None], ['生徒', 'せいと', None, None], [None, None, 'たちは', None], ['流暢', 'りゅうちょう', None, None], [None, None, 'な', None], ['日本語', 'にほんご', None, None], [None, None, 'でニュースについて', None], ['議論', 'ぎろん', None, None], [None, None, 'していたが、', None], ['彼', 'かれ', None, None], [None, None, 'らは', None], ['二', 'に', None, None], ['年', 'ねん', None, None], ['前', 'まえ', None, None], [None, None, 'から', None], ['日本語', 'にほんご', None, None], [None, None, 'を', None], ['勉強', 'べんきょう', None, None], [None, None, 'し', None], ['始', 'はじ', None, None], [None, None, 'めたと', None], ['聞', 'き', None, None], [None, None, 'いて、', None], ['驚', 'おどろ', None, None], [None, None, 'き', None], [None, None, 'を', True], ['禁', 'きん', None, True], [None, None, 'じ', True], ['得', 'え', None, True], [None, None, 'なかった', True], [None, None, '。', None]]
[[None, None, 'この', None], ['不況', 'ふきょう', None, None], [None, None, 'の', None], ['中', 'なか', None, None], [None, None, '、', None], ['政治家', 'せいじか', None, None], [None, None, 'が', None], ['自分', 'じぶん', None, None], [None, None, 'の', None], ['給与', 'きゅうよ', None, None], [None, None, 'を', None], ['上', 'あ', None, None], [None, None, 'げるとの', None], ['報道', 'ほうどう', None, None], [None, None, 'を', None], ['耳', 'みみ', None, None], [None, None, 'にし、', None], ['怒', 'いか', None, None], [None, None, 'り', None], [None, None, 'を', True], ['禁', 'きん', None, True], [None, None, 'じ', True], ['得', 'え', None, True], [None, None, 'ません', True], [None, None, '。', None]]
[['伝記', 'でんき', None, None], [None, None, '：「', None], ['戦争', 'せんそう', None, None], [None, None, 'がこの', None], ['地方', 'ちほう', None, None], [None, None, 'にもたらした', None], ['破壊', 'はかい', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'て、', None], ['涙', 'なみだ', None, None], [None, None, 'を', True], ['禁', 'きん', None, True], [None, None, 'じ', True], ['得', 'え', None, True], [None, None, 'なかった', True], [None, None, '。」', None]]
[['長', 'なが', None, None], [None, None, 'い', None], ['年月', 'としつき', None, None], [None, None, 'の', None], ['後', 'のち', None, None], [None, None, '、', None], ['互', 'たが', None, None], [None, None, 'いに', None], ['抱', 'だ', None, None], [None, None, 'き', None], ['合', 'あ', None, None], [None, None, 'った', None], ['姿', 'すがた', None, None], [None, None, 'に、', None], ['喜', 'よろこ', None, None], [None, None, 'び', None], [None, None, 'を', True], ['禁', 'きん', None, True], [None, None, 'じ', True], ['得', 'え', None, True], [None, None, 'ない', True], [None, None, '。', None]]
[['全', 'すべ', None, None], [None, None, 'てを', None], ['失', 'うしな', None, None], [None, None, 'った', None], ['地震', 'じしん', None, None], [None, None, 'の', None], ['被害者', 'ひがいしゃ', None, None], [None, None, 'に', None], ['同情', 'どうじょう', None, None], [None, None, 'の', None], ['念', 'ねん', None, None], [None, None, 'を', True], ['禁', 'きん', None, True], [None, None, 'じ', True], ['得', 'え', None, True], [None, None, 'ない', True], [None, None, '。', None]]

 96%|█████████▌| 898/938 [09:19<00:21,  1.83it/s]

[[None, None, '「', None], ['花子', 'はなこ', None, None], [None, None, 'ったら', None], ['部', 'ぶ', None, None], ['活動', 'かつどう', None, None], [None, None, 'に', True], ['託', 'かこつ', None, True], [None, None, 'けて', True], [None, None, '、', None], ['部室', 'ぶしつ', None, None], [None, None, 'に', None], ['潜', 'もぐ', None, None], [None, None, 'り', None], ['込', 'こ', None, None], [None, None, 'んでひとり', None], ['遊', 'あそ', None, None], [None, None, 'んでばかりいるよ。」', None]]
[['人', 'ひと', None, None], [None, None, '（', None], ['私', 'わたし', None, None], [None, None, 'も', None], ['含', 'ふく', None, None], [None, None, 'めて）はお', None], ['菓子', 'かし', None, None], [None, None, 'が', None], ['大好', 'だいす', None, None], [None, None, 'きで', None], ['何', 'なに', None, None], [None, None, 'か', None], [None, None, 'に', True], ['託', 'かこつ', None, True], [None, None, 'けて', True], [None, None, 'いつも', None], ['買', 'か', None, None], [None, None, 'ってしまうのではないだろうか。', None]]
[['武田', 'たけだ', None, None], [None, None, '：「', None], ['田中', 'たなか', None, None], [None, None, 'さんったら', None], ['出張', 'しゅっちょう', None, None], [None, None, 'に', True], ['託', 'かこつ', None, True], [None, None, 'けて', True], [None, None, 'パリを', None], ['観光', 'かんこう', None, None], [None, None, 'するつもりね。」', None], ['田中', 'たなか', None, None], [None, None, 'さん', None], [None, None, '：「いやいや、そんなこと。」', None]]
[['Ａ', 'エー', None, None], [None, None, '：「あすかさんと', None], ['会', 'あ', None, None], [None, None, 'いたいけどどうしたらいい？」', None], [None, None, ' ', None], ['Ｂ', 'ビー', None, None], [None, None, '：「プリントを', None], ['渡', 'わた', None, None], [None, None, 'すというの', None], [None, None, 'に', True], ['託', 'かこつ', None, True], [None, None, 'けて', True], ['家', 'いえ', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'ったらどう？」', None]]
[['風邪', 'かぜ', None, None], [None, None, 'に', True], ['託', 'かこつ', None, True], [None, None, 'けて', True], [None, None, '、', None], ['仕事', 'しごと', None, None], [None, None, 'を', None], ['休', 'やす', None, None], [None, None, 'んで', None], ['一', 'いち', None, None], ['日中', 'にちじゅう', None, None], [None, None, 'コーラを', None], ['飲', 'の', None, None], [None, None, 'んだりゲームをしてしまった。', None]]

 96%|█████████▌| 899/938 [09:20<00:20,  1.87it/s]

[[None, None, 'このドレスの', None], ['色', 'いろ', None, None], [None, None, 'は', None], ['見', 'み', None, True], [None, None, 'ようによっては', True], [None, None, '「', None], ['青', 'あお', None, None], [None, None, 'と', None], ['黒', 'くろ', None, None], [None, None, '」か「', None], ['白', 'しろ', None, None], [None, None, 'と', None], ['金', 'きん', None, None], [None, None, '」に', None], ['見', 'み', None, None], [None, None, 'えるかもしれない。', None]]
[[None, None, '「', None], ['結構', 'けっこう', None, None], [None, None, 'です」は', None], ['聞', 'き', None, True], [None, None, 'きようによっては', True], ['肯定', 'こうてい', None, None], [None, None, 'にでも', None], ['否定', 'ひてい', None, None], [None, None, 'にでもどちらにでも', None], ['受', 'う', None, None], [None, None, 'け', None], ['取', 'と', None, None], [None, None, 'れる。', None]]
[['経済', 'けいざい', None, None], ['危機', 'きき', None, None], [None, None, 'は、', None], ['一見', 'いっけん', None, None], ['絶望', 'ぜつぼう', None, None], [None, None, 'しかないように', None], ['見', 'み', None, None], [None, None, 'えるが、', None], ['考', 'かんが', None, True], [None, None, 'えようによっては', True], ['素晴', 'すば', None, None], [None, None, 'らしい', None], ['機会', 'きかい', None, None], [None, None, 'とも', None], ['言', 'い', None, None], [None, None, 'えるかもしれない。', None]]
[['確', 'たし', None, None], [None, None, 'かに、この', None], ['大', 'おお', None, None], [None, None, 'きな', None], ['目', 'め', None, None], [None, None, 'のクモは、', None], ['見', 'み', None, True], [None, None, 'ようによっては', True], ['可愛', 'かわい', None, None], [None, None, 'いらしいと', None], ['言', 'い', None, None], [None, None, 'えなくもない。', None]]
[[None, None, 'このツイートは', None], ['読', 'よ', None, True], [None, None, 'みようによっては', True], ['皮肉', 'ひにく', None, None], [None, None, 'にも', None], ['取', 'と', None, None], [None, None, 'れるだろう。', None]]

 96%|█████████▌| 900/938 [09:20<00:19,  1.92it/s]

[['小説', 'しょうせつ', None, None], [None, None, '：「', None], ['戦力差', 'せんりょくさ', None, None], [None, None, 'は', None], ['歴然', 'れきぜん', None, None], [None, None, 'としているゆえ、まともな', None], ['勝負', 'しょうぶ', None, None], [None, None, 'は', None], ['望', 'のぞ', None, None], [None, None, 'む', None], [None, None, 'べくもない', True], [None, None, '。」', None]]
[[None, None, 'いくら', None], ['頑張', 'がんば', None, None], [None, None, 'ったところで、', None], ['絵', 'え', None, None], [None, None, 'は', None], ['写真', 'しゃしん', None, None], [None, None, 'にはおよぶ', None], [None, None, 'べくもない', True], [None, None, 'のである。', None]]
[['地球', 'ちきゅう', None, None], ['温暖化', 'おんだんか', None, None], [None, None, 'は', None], ['人間', 'にんげん', None, None], ['活動', 'かつどう', None, None], [None, None, 'と', None], ['直接', 'ちょくせつ', None, None], ['関係', 'かんけい', None, None], [None, None, 'があるということは', None], ['疑', 'うたが', None, None], [None, None, 'う', None], [None, None, 'べくもない', True], [None, None, '。', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「', None], ['今回', 'こんかい', None, None], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'は', None], ['危害', 'きがい', None, None], [None, None, 'を', None], ['免', 'まぬか', None, None], [None, None, 'れたにせよ、そのように', None], ['運転', 'うんてん', None, None], [None, None, 'を', None], ['続', 'つづ', None, None], [None, None, 'けていては', None], ['将来', 'しょうらい', None, None], [None, None, 'は', None], ['彼', 'かれ', None, None], [None, None, 'に', None], ['何事', 'なにごと', None, None], [None, None, 'が', None], ['起', 'おこ', None, None], [None, None, 'りかねぬかは、', None], ['知', 'し', None, None], [None, None, 'る', None], [None, None, 'べくもない', True], [None, None, '。」', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「この', None], ['真', 'ま', None, None], ['正直', 'しょうじき', None, None], [None, None, 'な', None], ['少年', 'しょうねん', None, None], [None, None, 'に、', None], ['嘘', 'うそ', None, None], [None, None, 'をつくなど', None], ['望', 'のぞ', None, None], [None, None, 'む', None], [None, None, 'べくもない', True], [None, None, '。」', None]]

 96%|█████████▌| 901/938 [09:21<00:20,  1.79it/s]

[[None, None, '「', None], ['田中', 'たなか', None, None], [None, None, 'さん', None], [None, None, 'が', None], [None, None, 'クビ', None], [None, None, 'になった', None], [None, None, 'と', None], ['聞', 'き', None, None], [None, None, 'いた', None], [None, None, 'よ', None], [None, None, '。」', None], [None, None, '「', None], ['毎日', 'まいにち', None, None], ['遅刻', 'ちこく', None, None], [None, None, 'ときたら', True], [None, None, 'クビ', None], [None, None, 'になる', None], [None, None, 'のは', None], ['当然', 'とうぜん', None, None], [None, None, 'でしょ', None], [None, None, '。」', None]]
[[None, None, 'ドーナツ', None], [None, None, 'ときたら', True], [None, None, 'やっぱり', None], ['牛乳', 'ぎゅうにゅう', None, None], [None, None, 'でしょ', None], [None, None, '！', None]]
[[None, None, 'テスト', None], [None, None, 'で', None], ['毎回', 'まいかい', None, None], ['０', 'れい', None, None], ['点', 'てん', None, None], [None, None, 'を', None], ['取', 'と', None, None], [None, None, 'って', None], [None, None, 'いる', None], [None, None, 'ときたら', True], [None, None, '、', None], [None, None, 'お', None], ['母', 'かあ', None, None], [None, None, 'さん', None], [None, None, 'が', None], ['怒', 'おこ', None, None], [None, None, 'らない', None], [None, None, 'わけがない', None], [None, None, '。', None]]
[['暑', 'あつ', None, None], [None, None, 'い', None], ['日', 'ひ', None, None], [None, None, 'ときたら', True], [None, None, '、', None], [None, None, 'やっぱり', None], ['麦茶', 'むぎちゃ', None, None], [None, None, 'よ', None], [None, None, 'ね', None], [None, None, '。', None]]
[[None, None, 'こんなに', None], ['曇', 'くも', None, None], [None, None, 'って', None], [None, None, 'いる', None], [None, None, 'ときたら', True], [None, None, '、', None], ['雨', 'あめ', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'らない', None], [None, None, 'はずがない', None], [None, None, '。', None]]

 96%|█████████▌| 902/938 [09:21<00:20,  1.73it/s]

[[None, None, 'これ', None], ['以上', 'いじょう', None, None], ['討議', 'とうぎ', None, None], [None, None, 'し', None], [None, None, 'て', None], [None, None, 'も', None], ['進展', 'しんてん', None, None], [None, None, 'は', None], ['見込', 'みこ', None, None], [None, None, 'めない', None], [None, None, 'ものとして', True], [None, None, '、', None], [None, None, 'これ', None], [None, None, 'を', None], [None, None, 'も', None], [None, None, 'って', None], ['会議', 'かいぎ', None, None], [None, None, 'は', None], [None, None, 'お', None], ['開', 'ひら', None, None], [None, None, 'き', None], [None, None, 'と', None], [None, None, 'し', None], [None, None, 'ます', None], [None, None, '。', None]]
[['講師', 'こうし', None, None], [None, None, '：「ご', None], ['質問', 'しつもん', None, None], ['等', 'など', None, None], [None, None, 'は', None], [None, None, 'あ', None], [None, None, 'ります', None], [None, None, 'か', None], [None, None, '？ない', None], ['場合', 'ばあい', None, None], [None, None, 'は', None], ['理解', 'りかい', None, None], [None, None, 'し', None], [None, None, 'た', None], [None, None, 'ものとして', True], ['今日', 'きょう', None, None], [None, None, 'は', None], [None, None, 'ここ', None], [None, None, 'まで', None], [None, None, 'です', None], [None, None, '。」', None]]
[['大学', 'だいがく', None, None], [None, None, 'の', None], [None, None, 'サイト', None], [None, None, '：「', None], ['先生', 'せんせい', None, None], [None, None, 'から', None], [None, None, 'の', None], ['連絡', 'れんらく', None, None], [None, None, 'は', None], ['一度', 'いちど', None, None], ['掲示', 'けいじ', None, None], [None, None, 'され', None], [None, None, 'た', None], ['内容', 'ないよう', None, None], [None, None, 'について', None], [None, None, 'は', None], ['１', 'いっ', None, None], ['週間', 'しゅうかん', None, None], ['後', 'ご', None, None], [None, None, '、', None], ['全', 'ぜん', None, None], ['学生', 'がくせい', None, None], [None, None, 'に', None], ['伝達', 'でんたつ', None, None], [None, None, 'され', None], [None, None, 'た', None], [None, None, 'ものとして', True], ['扱', 'あつか', None, None], [None, None, 'います。」', None]]
[['格闘技', 'かくとうぎ', None, None], [None, None, 'において', None], [None, None, 'は', None], ['選手', 'せんしゅ', None, None], [None, None, 'は', None], ['畳', 'たたみ', None, None], [None, None, 'やマット', None], [None, None, 'を', None], ['３', 'さん', None, None], ['回', 'かい', None, None], ['叩', 'たた', None, None], [None, None, 'くと', None], ['降参', 'こうさん', None, None], [None, None, 'し', None], [None, None, 'た', None], [None, None, 'ものとして', True], [None, None, '、', None], ['試合', 'しあい', None, None], [None, None, 'の', None], ['決着', 'けっちゃく', None, None], [None, None, 'が', None], [None, None, 'つく。', None]]
[[None, None, 'しかし', None], [None, None, 'ながら', None], [None, None, '、', None], ['市長', 'しちょう', None, None], [None, None, 'は', None], [None, None, '、', None], ['住民', 'じゅうみん', None, None], [None, None, 'の', None], ['心配', 'しんぱい', None, None], ['事', 'ごと', None, None], [None, None, 'を', None], [None, None, '、', None], [None, None, 'ありえない', None], [None, None, 'ものとして', True], [None, None, '、', None], ['却下', 'きゃっか', None, None], [None, None, 'し', None], [None, None, 'ました', None], [None, None, '。', None]]

 96%|█████████▋| 903/938 [09:22<00:21,  1.65it/s]

[['私', 'わたし', None, None], [None, None, 'たち', None], [None, None, 'は', None], [None, None, '、', None], ['結婚', 'けっこん', None, None], [None, None, 'を', True], ['前提', 'ぜんてい', None, True], [None, None, 'に', True], ['付', 'つ', None, None], [None, None, 'き', None], ['合', 'あ', None, None], [None, None, 'って', None], [None, None, 'いる。', None]]
[['元々', 'もともと', None, None], [None, None, '、', None], [None, None, ' ', None], ['一人', 'ひとり', None, None], [None, None, 'で', None], ['住', 'す', None, None], [None, None, 'む', None], [None, None, 'こと', None], [None, None, 'を', True], ['前提', 'ぜんてい', None, True], [None, None, 'に', True], [None, None, 'この', None], ['家', 'いえ', None, None], [None, None, 'を', None], ['建', 'た', None, None], [None, None, 'て', None], [None, None, 'た', None], [None, None, 'から', None], [None, None, '、', None], ['時', 'とき', None, None], [None, None, 'が', None], ['経', 'た', None, None], [None, None, 'ったら', None], [None, None, 'ちょっと', None], ['狭', 'せま', None, None], [None, None, 'くなった', None], [None, None, '。', None]]
[['原価', 'げんか', None, None], ['見積', 'みつもり', None, None], [None, None, 'は', None], [None, None, '、', None], ['建材', 'けんざい', None, None], [None, None, 'の', None], ['価格', 'かかく', None, None], [None, None, 'が', None], ['緩', 'ゆる', None, None], [None, None, 'やかに', None], ['上昇', 'じょうしょう', None, None], [None, None, 'する', None], [None, None, 'こと', None], [None, None, 'を', True], ['前提', 'ぜんてい', None, True], [None, None, 'に', True], ['計算', 'けいさん', None, None], [None, None, 'されます', None], [None, None, '。', None]]
[['多', 'おお', None, None], [None, None, 'く', None], [None, None, 'の', None], ['家庭', 'かてい', None, None], ['用', 'よう', None, None], [None, None, 'ゲーム', None], ['機', 'き', None, None], [None, None, 'を', None], ['所有', 'しょゆう', None, None], [None, None, 'し', None], [None, None, 'て', None], [None, None, 'いる', None], ['人', 'ひと', None, None], [None, None, 'は', None], [None, None, 'ゲーム', None], [None, None, 'が', None], ['終', 'お', None, None], [None, None, 'わ', None], [None, None, 'った', None], [None, None, 'ら', None], ['売', 'う', None, None], [None, None, 'る', None], [None, None, 'こと', None], [None, None, 'を', True], ['前提', 'ぜんてい', None, True], [None, None, 'に', True], [None, None, 'その', None], [None, None, 'ゲーム', None], [None, None, 'を', None], ['買', 'か', None, None], [None, None, 'って', None], [None, None, 'いる。', None]]
[['本', 'ほん', None, None], ['教科書', 'きょうかしょ', None, None], [None, None, 'は', None], [None, None, '、', None], ['文法', 'ぶんぽう', None, None], [None, None, 'に', None], ['関', 'かん', None, None], [None, None, 'する', None], ['知識', 'ちしき', None, None], [None, None, 'がある', None], [None, None, 'こと', None], [None, None, 'を', True], ['前提', 'ぜんてい', None, True], [None, None, 'に', True], ['書', 'か', None, None], [None, None, 'かれています。', None]]

 96%|█████████▋| 904/938 [09:23<00:19,  1.71it/s]

[['重要', 'じゅうよう', None, None], [None, None, 'な', None], ['会議', 'かいぎ', None, None], [None, None, 'だから、', None], ['間', 'ま', None, True], [None, None, 'に', True], ['合', 'あ', None, True], [None, None, 'わないではすまない', True], [None, None, '。', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['相談', 'そうだん', None, None], [None, None, 'もなく', None], ['重要', 'じゅうよう', None, None], [None, None, 'な', None], ['道具', 'どうぐ', None, None], [None, None, 'を', None], ['廃棄', 'はいき', None, None], [None, None, 'した。', None], ['首', 'くび', None, None], [None, None, 'に', None], [None, None, 'ならずにはすまない', True], [None, None, 'だろう。', None]]
[['私', 'わたし', None, None], [None, None, 'は', None], ['子犬', 'こいぬ', None, None], [None, None, 'を', None], ['助', 'たす', None, None], [None, None, 'けるためとはいえ、', None], ['無断', 'むだん', None, None], [None, None, 'で', None], ['車', 'くるま', None, None], [None, None, 'の', None], ['窓', 'まど', None, None], [None, None, 'を', None], ['破', 'やぶ', None, None], [None, None, 'った。', None], ['罰', 'ばつ', None, None], [None, None, 'を', None], ['受', 'う', None, True], [None, None, 'けずにはすまない', True], [None, None, 'だろう。', None]]
[[None, None, 'この', None], ['深刻', 'しんこく', None, None], [None, None, 'な', None], ['問題', 'もんだい', None, None], [None, None, 'は', None], ['難', 'むずか', None, None], [None, None, 'しいので、', None], ['上司', 'じょうし', None, None], [None, None, 'に', None], ['話', 'はな', None, True], [None, None, 'さずにはすまない', True], [None, None, 'だろう。', None]]
[['大人', 'おとな', None, None], [None, None, 'なのだから、', None], ['知', 'し', None, True], [None, None, 'らずではすまない', True], [None, None, 'だろう。', None]]

 96%|█████████▋| 905/938 [09:23<00:20,  1.59it/s]

[[None, None, 'くりやまさんの', None], ['歌声', 'うたごえ', None, None], [None, None, 'は', None], ['酷', 'ひど', None, None], [None, None, 'すぎて', None], ['聞', 'き', None, None], [None, None, 'く', None], [None, None, 'に', True], ['堪', 'た', None, True], [None, None, 'えなかった', True], [None, None, '。', None]]
[[None, None, 'このホラー', None], ['映画', 'えいが', None, None], [None, None, 'には', None], ['正視', 'せいし', None, None], [None, None, 'に', True], ['堪', 'た', None, True], [None, None, 'えない', True], [None, None, '、すごく', None], ['残虐', 'ざんぎゃく', None, None], [None, None, 'なシーンが', None], ['多', 'おお', None, None], [None, None, 'い。', None]]
[['最近', 'さいきん', None, None], [None, None, '、', None], ['新聞', 'しんぶん', None, None], [None, None, 'で', None], ['悪', 'わる', None, None], [None, None, 'いニュースばかりが', None], ['続', 'つづ', None, None], [None, None, 'いているから', None], ['読', 'よ', None, None], [None, None, 'む', None], [None, None, 'に', True], ['堪', 'た', None, True], [None, None, 'えない', True], [None, None, '。', None]]
[['嘘', 'うそ', None, None], [None, None, 'をついてばかりいる', None], ['政治家', 'せいじか', None, None], [None, None, 'のインタビューはもう', None], ['聞', 'き', None, None], [None, None, 'く', None], [None, None, 'に', True], ['堪', 'た', None, True], [None, None, 'えない', True], [None, None, '。', None]]
[['中', 'ちゅう', None, None], ['二', 'に', None, None], ['病', 'びょう', None, None], [None, None, 'のころ', None], ['撮', 'と', None, None], [None, None, 'った', None], ['写真', 'しゃしん', None, None], [None, None, 'は', None], ['恥', 'は', None, None], [None, None, 'ずかしすぎて', None], ['見', 'み', None, None], [None, None, 'る', None], [None, None, 'に', True], ['堪', 'た', None, True], [None, None, 'えない', True], [None, None, 'から', None], ['消', 'け', None, None], [None, None, 'した。', None]]

 97%|█████████▋| 906/938 [09:24<00:19,  1.66it/s]

[['武田', 'たけだ', None, None], [None, None, 'さんは', None], ['小', 'ちい', None, None], [None, None, 'さな', None], ['声', 'こえ', None, None], [None, None, 'で', None], ['職場', 'しょくば', None, None], [None, None, 'でハラスメントを', None], ['受', 'う', None, None], [None, None, 'けたことを', None], ['伝', 'つた', None, None], [None, None, 'えてきて、しまいに', None], ['大', 'おお', None, None], [None, None, 'きな', None], ['声', 'こえ', None, None], [None, None, 'で', None], ['泣', 'な', None, None], [None, None, 'き', None], ['出', 'だ', None, None], [None, None, 'す', None], ['始末', 'しまつ', None, True], [None, None, 'だ', True], [None, None, '。', None]]
[[None, None, 'あいつは、', None], ['自分', 'じぶん', None, None], [None, None, 'が', None], ['起', 'お', None, None], [None, None, 'こしたミスなのに、', None], ['謝', 'あやま', None, None], [None, None, 'るどころか', None], ['私', 'わたし', None, None], [None, None, 'のせいにする', None], ['始末', 'しまつ', None, True], [None, None, 'だ', True], [None, None, '。', None]]
[[None, None, 'せっかく', None], ['友達', 'ともだち', None, None], [None, None, 'と', None], ['海', 'うみ', None, None], [None, None, 'へ', None], ['行', 'い', None, None], [None, None, 'く', None], ['計画', 'けいかく', None, None], [None, None, 'を', None], ['立', 'た', None, None], [None, None, 'てたのに、', None], ['田中', 'たなか', None, None], [None, None, 'は', None], ['大事', 'だいじ', None, None], [None, None, 'な', None], ['用', 'よう', None, None], [None, None, 'があって', None], ['行', 'い', None, None], [None, None, 'けないとか、', None], ['武田', 'たけだ', None, None], [None, None, 'もシフトが', None], ['入', 'はい', None, None], [None, None, 'ってたとかで、', None], ['結局', 'けっきょく', None, None], ['私', 'わたし', None, None], ['一', 'ひと', None, None], ['人', 'り', None, None], [None, None, 'だけで', None], ['行', 'い', None, None], [None, None, 'く', None], ['始末', 'しまつ', None, True], [None, None, 'だ', True], [None, None, '。', None]]
[['武田', 'たけだ', None, None], [None, None, '：「', None], ['山田', 'やまだ', None, None], [None, None, 'さん、', None], ['顔色', 'かおいろ', None, None], [None, None, 'が', None], ['悪', 'わる', None, None], [None, None, 'いですけど・・・」', None], ['山田', 'やまだ', None, None], [None, None, '：「', None], ['夜', 'よる', None, None], ['遅', 'おそ', None, None], [None, None, 'くまでゲームをしていたので、おかげでこの', None], ['始末', 'しまつ', None, True], [None, None, 'だ', True], [None, None, '。」', None]]
[['田中', 'たなか', None, None], [None, None, 'には', None], ['二度', 'にど', None, None], [None, None, 'と', None], ['仕事', 'しごと', None, None], [None, None, 'は', None], ['頼', 'たの', None, None], [None, None, 'まないぞ。', None], ['納期', 'のうき', None, None], [None, None, 'は', None], ['守', 'まも', None, None], [None, None, 'らないし', None], ['仕上', 'しあ', None, None], [None, None, 'がりも', None], ['悪', 'わる', None, None], [None, None, 'かったのに、', None], ['言', 'い', None, None], [None, None, 'い', None], ['訳', 'わけ', None, None], [None, None, 'ばかりならべて。', None], ['最後', 'さいご', None, None], [None, None, 'には', None], ['追加', 'ついか', None, None], [None, None, 'の', None], ['料金', 'りょうきん', None, None], [None, None, 'を', None], ['払', 'はら', None, None], [None, None, 'えと', None], ['言', 'い', None, None], [None, None, 'い', None], ['出', 'だ', None, None], [None, None, 'す', None], ['始末', 'しまつ', None, True], [None, None, 'だ', True], [None, None, '。', None]]

 97%|█████████▋| 907/938 [09:24<00:17,  1.75it/s]

[[None, None, 'しのぶさんはとても', None], ['血', 'ち', None, None], [None, None, 'を', None], ['恐', 'おそ', None, None], [None, None, 'れている。', None], ['万', 'まん', None, None], [None, None, 'が', None], ['一', 'いち', None, None], [None, None, '、', None], ['一滴', 'いってき', None, None], [None, None, 'でも', None], ['血', 'ち', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'よう', None], [None, None, 'ものなら', True], ['気絶', 'きぜつ', None, None], [None, None, 'してしまうはずだ。', None]]
[[None, None, 'ブラッド・ピットに', None], ['出逢', 'であ', None, None], [None, None, 'おう', None], [None, None, 'ものなら', True], [None, None, '、', None], ['死', 'し', None, None], [None, None, 'んでしまう。', None]]
[['秘密', 'ひみつ', None, None], [None, None, 'を', None], ['打', 'う', None, None], [None, None, 'ち', None], ['明', 'あ', None, None], [None, None, 'けよう', None], [None, None, 'ものなら', True], [None, None, '、', None], ['彼女', 'かのじょ', None, None], [None, None, 'はすぐに', None], ['他', 'ほか', None, None], [None, None, 'の', None], ['奴', 'やつ', None, None], [None, None, 'らにしゃべってしまうだろう。', None]]
[['万', 'まん', None, None], [None, None, 'が', None], ['一', 'いち', None, None], [None, None, 'このプロジェクトが', None], ['失敗', 'しっぱい', None, None], [None, None, 'しよう', None], [None, None, 'ものなら', True], [None, None, '、', None], ['我々', 'われわれ', None, None], [None, None, 'は', None], ['終', 'お', None, None], [None, None, 'わりだ。', None]]
[[None, None, 'うっかり', None], ['彼', 'かれ', None, None], [None, None, 'のお', None], ['菓子', 'かし', None, None], [None, None, 'を', None], ['食', 'た', None, None], [None, None, 'べよう', None], [None, None, 'ものなら', True], [None, None, '、きっと、ものすごく', None], ['彼', 'かれ', None, None], [None, None, 'にしかられるはずだ。', None]]

 97%|█████████▋| 908/938 [09:25<00:16,  1.85it/s]

[['母親', 'ははおや', None, None], [None, None, 'の', None], ['友達', 'ともだち', None, None], [None, None, 'の', None], ['息子', 'むすこ', None, None], [None, None, 'さんは、', None], ['弁護士', 'べんごし', None, None], [None, None, 'として', None], ['立派', 'りっぱ', None, None], [None, None, 'に', None], ['働', 'はたら', None, None], [None, None, 'いている', None], [None, None, 'のにひきかえ', True], [None, None, '、', None], ['僕', 'ぼく', None, None], [None, None, 'は・・・（まだフリーターだ）。', None]]
[['姉', 'あね', None, None], [None, None, 'は', None], ['積極的', 'せっきょくてき', None, None], [None, None, 'で', None], ['活発', 'かっぱつ', None, None], [None, None, 'な', None], ['性格', 'せいかく', None, None], [None, None, 'にひきかえ', True], [None, None, '、', None], ['弟', 'おとうと', None, None], [None, None, 'の', None], ['健太郎', 'けんたろう', None, None], [None, None, 'はとても', None], ['無気力', 'むきりょく', None, None], [None, None, 'だ。', None]]
[['兄', 'あに', None, None], [None, None, 'は', None], ['優秀', 'ゆうしゅう', None, None], [None, None, 'な', None], ['成績', 'せいせき', None, None], [None, None, 'をおさめている。それ', None], [None, None, 'にひきかえ', True], ['妹', 'いもうと', None, None], [None, None, 'の', None], ['方', 'ほう', None, None], [None, None, 'は', None], ['遊', 'あそ', None, None], [None, None, 'んでばかりだ。', None]]
[['前回', 'ぜんかい', None, None], [None, None, 'のテスト', None], [None, None, 'にひきかえ', True], ['今回', 'こんかい', None, None], [None, None, 'のテストは', None], ['難', 'むずか', None, None], [None, None, 'しい。', None]]
[['隣', 'となり', None, None], [None, None, 'の', None], ['家', 'いえ', None, None], [None, None, 'の', None], ['猫', 'ねこ', None, None], [None, None, 'は', None], ['痩', 'や', None, None], [None, None, 'せていて', None], ['頭', 'あたま', None, None], [None, None, 'がいい', None], [None, None, 'のにひきかえ', True], [None, None, 'うちの', None], ['猫', 'ねこ', None, None], [None, None, 'はぐうたらしてばかりだなあ。', None]]

 97%|█████████▋| 909/938 [09:26<00:17,  1.70it/s]

[['Ａ', 'エー', None, None], [None, None, '：「', None], ['毎日', 'まいにち', None, None], ['毎日', 'まいにち', None, None], ['勉強', 'べんきょう', None, None], [None, None, 'していてとても', None], ['疲', 'つか', None, None], [None, None, 'れてるんだ。', None], ['大学', 'だいがく', None, None], [None, None, 'を', None], ['中退', 'ちゅうたい', None, None], [None, None, 'したい…。」', None], ['Ｂ', 'ビー', None, None], [None, None, '：「でも、もう', None], ['３年生', 'さんねんせい', None, None], [None, None, 'だよ！あきらめてしまったら', None], [None, None, 'それまでだ', True], [None, None, 'よ。」', None]]
[[None, None, 'どんなに', None], ['大', 'おお', None, None], [None, None, 'きな', None], ['家', 'いえ', None, None], [None, None, 'でも、', None], ['誰', 'だれ', None, None], [None, None, 'も', None], ['住', 'す', None, None], [None, None, 'まなければ', None], [None, None, 'それまでだ', True], [None, None, '。', None]]
[[None, None, 'この', None], ['内定', 'ないてい', None, None], [None, None, 'を', None], ['受諾', 'じゅだく', None, None], [None, None, 'することに', None], ['興味', 'きょうみ', None, None], [None, None, 'がないだけと', None], ['言', 'い', None, None], [None, None, 'えば', None], [None, None, 'それまでだ', True], [None, None, 'が、もういちどよく', None], ['考', 'かんが', None, None], [None, None, 'えて', None], ['決', 'き', None, None], [None, None, 'めたほうがいいだろうな。こんなチャンスは', None], ['二度', 'にど', None, None], [None, None, 'とないよ。', None]]
[[None, None, 'ダイエットしている', None], ['友達', 'ともだち', None, None], [None, None, 'へ', None], [None, None, '：「', None], ['頑張', 'がんば', None, None], [None, None, 'って', None], ['運動', 'うんどう', None, None], [None, None, 'しても', None], ['毎日', 'まいにち', None, None], ['食', 'た', None, None], [None, None, 'べ', None], ['過', 'す', None, None], [None, None, 'ぎたら', None], [None, None, 'それまでだ', True], [None, None, 'よ。」', None]]
[[None, None, 'スパイ', None], ['映画', 'えいが', None, None], [None, None, '：「', None], ['敵', 'てき', None, None], [None, None, 'に', None], ['発見', 'はっけん', None, None], [None, None, 'されたら', None], [None, None, 'それまでだ', True], [None, None, '。」', None]]

 97%|█████████▋| 910/938 [09:26<00:16,  1.66it/s]

[[None, None, 'この', None], ['前', 'まえ', None, None], [None, None, '、', None], ['電車', 'でんしゃ', None, None], [None, None, 'を', None], ['乗', 'の', None, None], [None, None, 'り', None], ['違', 'ちが', None, None], [None, None, 'えてしまったんだ。', None], ['僕', 'ぼく', None, None], [None, None, 'はそのとき、', None], ['自分', 'じぶん', None, None], [None, None, 'でもこんなドジをして、', None], ['面白', 'おもしろ', None, None], [None, None, 'い', None], [None, None, 'といおうか', True], [None, None, '、', None], ['困', 'こま', None, None], [None, None, 'っている', None], [None, None, 'といおうか', True], [None, None, '…とにかく', None], ['忘', 'わす', None, None], [None, None, 'れられない', None], ['思', 'おも', None, None], [None, None, 'い', None], ['出', 'で', None, None], [None, None, 'になったよ。', None]]
[['Ａ', 'エー', None, None], [None, None, '：「プチチーズってなんですか。」', None], ['Ｂ', 'ビー', None, None], [None, None, '：「クラッカー', None], [None, None, 'といおうか', True], [None, None, '、チーズとのスナック', None], [None, None, 'といおうか', True], [None, None, '…（うーん、', None], ['的確', 'てきかく', None, None], [None, None, 'な', None], ['言葉', 'ことば', None, None], [None, None, 'が', None], ['思', 'おも', None, None], [None, None, 'い', None], ['浮', 'う', None, None], [None, None, 'かばないなぁ）」', None]]
[[None, None, '「', None], ['彼女', 'かのじょ', None, None], [None, None, 'は', None], ['誰', 'だれ', None, None], [None, None, 'ですか？」', None], [None, None, '「', None], ['彼', 'かれ', None, None], [None, None, 'の', None], ['元', 'もと', None, None], [None, None, 'カノ', None], [None, None, 'といおうか', True], ['友達', 'ともだち', None, None], [None, None, 'といおうか', True], ['複雑', 'ふくざつ', None, None], [None, None, 'ですよ。」', None]]
[['彼', 'かれ', None, None], [None, None, 'は', None], ['穏', 'おだ', None, None], [None, None, 'やか', None], [None, None, 'といおうか', True], [None, None, '、のんびり', None], [None, None, 'といおうか', True], [None, None, '、', None], ['何事', 'なにごと', None, None], [None, None, 'につけてもゆっくりしている。', None]]
[[None, None, 'とうとう', None], ['一人暮', 'ひとりぐ', None, None], [None, None, 'らしを', None], ['始', 'はじ', None, None], [None, None, 'めたのに、', None], ['寂', 'さび', None, None], [None, None, 'しい', None], [None, None, 'といおうか', True], ['嬉', 'うれ', None, None], [None, None, 'しい', None], [None, None, 'といおうか', True], [None, None, '、よくわからない。', None]]

 97%|█████████▋| 911/938 [09:27<00:15,  1.71it/s]

[['小説', 'しょうせつ', None, None], [None, None, '、', None], ['勇者', 'ゆうしゃ', None, None], [None, None, '：「どんな', None], ['手段', 'しゅだん', None, None], [None, None, 'を', None], ['用', 'もち', None, None], [None, None, 'いても、かならず', None], ['魔王', 'まおう', None, None], [None, None, 'を', None], ['倒', 'たお', None, True], [None, None, 'さずにはおかない', True], [None, None, '。」', None]]
[[None, None, '「', None], ['私', 'わたし', None, None], [None, None, 'はきっと', None], ['彼', 'かれ', None, None], [None, None, 'に', None], ['同', 'おな', None, None], [None, None, 'じ', None], ['手', 'て', None, None], [None, None, 'で', None], ['仕返', 'しかえ', None, None], [None, None, 'しを', None], [None, None, 'しないではおかない', True], [None, None, '。」', None]]
[[None, None, '「', None], ['警察', 'けいさつ', None, None], [None, None, 'はすべての', None], ['悪者', 'わるもの', None, None], [None, None, 'に', None], ['必', 'かなら', None, None], [None, None, 'ず', None], ['罰', 'ばつ', None, None], [None, None, 'を', None], ['与', 'あた', None, True], [None, None, 'えずにはおかない', True], [None, None, '。」', None]]
[[None, None, '「', None], ['彼', 'かれ', None, None], [None, None, 'はまた', None], ['私', 'わたし', None, None], [None, None, 'との', None], ['約束', 'やくそく', None, None], [None, None, 'をすっぽかした。', None], ['絶対', 'ぜったい', None, None], [None, None, 'に', None], ['彼', 'かれ', None, None], [None, None, 'に『ごめんなさい』と', None], ['言', 'い', None, True], [None, None, 'わせずにはおかない', True], [None, None, '。」', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「', None], ['探偵', 'たんてい', None, None], [None, None, 'は『この', None], ['残虐', 'ざんぎゃく', None, None], ['行為', 'こうい', None, None], [None, None, 'の', None], ['責任者', 'せきにんしゃ', None, None], [None, None, 'を', None], ['訴追', 'そつい', None, None], [None, None, 'せずにはおかない', True], [None, None, '』と', None], ['意', 'い', None, None], [None, None, 'を', None], ['決', 'けっ', None, None], [None, None, 'する。」', None]]

 97%|█████████▋| 912/938 [09:27<00:14,  1.78it/s]

[['明日', 'あした', None, None], [None, None, 'を', True], ['限', 'かぎ', None, True], [None, None, 'りに', True], ['閉店', 'へいてん', None, None], ['致', 'いた', None, None], [None, None, 'します。', None], ['当店', 'とうてん', None, None], [None, None, 'は', None], ['１９７２', 'せんきゅうひゃくななじゅうに', None, None], ['年', 'ねん', None, None], [None, None, 'に', None], ['開業', 'かいぎょう', None, None], [None, None, 'し、', None], ['４９', 'よんじゅうきゅう', None, None], ['年', 'ねん', None, None], [None, None, 'にわたり', None], ['現在', 'げんざい', None, None], [None, None, 'の', None], ['場所', 'ばしょ', None, None], [None, None, 'で', None], ['営業', 'えいぎょう', None, None], [None, None, 'してまいりました。', None]]
[['異動', 'いどう', None, None], [None, None, '、', None], ['公務員', 'こうむいん', None, None], [None, None, '：「', None], ['今週', 'こんしゅう', None, None], ['限', 'かぎ', None, True], [None, None, 'りで', True], [None, None, '、', None], ['現在', 'げんざい', None, None], [None, None, 'の', None], ['職務', 'しょくむ', None, None], [None, None, 'から', None], ['離', 'はな', None, None], [None, None, 'れることになりました。」', None]]
[['同僚', 'どうりょう', None, None], [None, None, 'との', None], ['話', 'はなし', None, None], [None, None, '：「', None], ['今月', 'こんげつ', None, None], ['限', 'かぎ', None, True], [None, None, 'りで', True], ['田中', 'たなか', None, None], [None, None, 'さんは', None], ['退職', 'たいしょく', None, None], [None, None, 'するつもりって', None], ['聞', 'き', None, None], [None, None, 'いたけど、', None], ['本当', 'ほんとう', None, None], [None, None, 'か？」', None]]
[['今回', 'こんかい', None, None], [None, None, 'を', True], ['限', 'かぎ', None, True], [None, None, 'りに', True], ['武田', 'たけだ', None, None], ['先生', 'せんせい', None, None], [None, None, 'は', None], ['人前', 'ひとまえ', None, None], [None, None, 'では', None], ['演奏', 'えんそう', None, None], [None, None, 'しません。', None]]

 97%|█████████▋| 913/938 [09:28<00:14,  1.72it/s]

[[None, None, 'こう', None], ['寒', 'さむ', None, True], [None, None, 'くてはかなわない', True], [None, None, '。', None]]
[['雨', 'あめ', None, None], [None, None, 'に', None], ['降', 'ふ', None, True], [None, None, 'られてはかなわない', True], [None, None, '。', None]]
[['上', 'うえ', None, None], [None, None, 'の', None], ['部屋', 'へや', None, None], [None, None, 'の', None], ['人', 'ひと', None, None], [None, None, 'が', None], [None, None, 'うるさくてはかなわない', True], [None, None, '。', None]]
[['話', 'はなし', None, None], [None, None, 'をしている', None], ['時', 'とき', None, None], [None, None, '、', None], ['非常識', 'ひじょうしき', None, None], [None, None, 'なひとに', None], ['邪魔', 'じゃま', None, None], [None, None, 'されてはかなわない', True], [None, None, '。', None]]
[['毎日', 'まいにち', None, None], [None, None, 'こんなに', None], ['蒸', 'む', None, True], [None, None, 'し', True], ['暑', 'あつ', None, True], [None, None, 'くてはかなわない', True], [None, None, '。', None]]

 97%|█████████▋| 914/938 [09:28<00:13,  1.79it/s]

[['恩師', 'おんし', None, None], [None, None, 'の', None], ['訪問', 'ほうもん', None, None], [None, None, '：「', None], ['本日', 'ほんじつ', None, None], [None, None, 'は', None], ['当時', 'とうじ', None, None], [None, None, 'のお', None], ['礼', 'れい', None, None], [None, None, 'かたがた', True], [None, None, '、', None], ['卒業', 'そつぎょう', None, None], [None, None, 'して', None], ['以来', 'いらい', None, None], [None, None, 'どうしているかをご', None], ['報告', 'ほうこく', None, None], [None, None, 'しに', None], ['訪', 'たず', None, None], [None, None, 'ねさせていただきました。」', None]]
[[None, None, '\u200b\u200b', None], ['挨拶状', 'あいさつじょう', None, None], [None, None, '：「まずは', None], ['右', 'みぎ', None, None], [None, None, 'ご', None], ['挨拶', 'あいさつ', None, None], [None, None, 'かたがた', True], [None, None, 'お', None], ['知', 'し', None, None], [None, None, 'らせまで。」', None]]
[['結婚', 'けっこん', None, None], [None, None, 'の', None], ['報告', 'ほうこく', None, None], [None, None, 'かたがた', True], [None, None, '、', None], ['妻', 'つま', None, None], [None, None, 'の', None], ['兄弟', 'きょうだい', None, None], [None, None, 'の', None], ['家', 'いえ', None, None], [None, None, 'を', None], ['訪', 'たず', None, None], [None, None, 'ねました。', None]]
[['同', 'おな', None, None], [None, None, 'じ', None], ['会社', 'かいしゃ', None, None], [None, None, 'で', None], ['働', 'はたら', None, None], [None, None, 'く', None], ['上司', 'じょうし', None, None], [None, None, 'へのメール', None], [None, None, '：「ご', None], ['挨拶', 'あいさつ', None, None], [None, None, 'かたがた', True], ['訪問', 'ほうもん', None, None], [None, None, 'をさせて', None], ['頂', 'いただ', None, None], [None, None, 'きたいのですが、', None], ['明日', 'あした', None, None], [None, None, 'のご', None], ['都合', 'つごう', None, None], [None, None, 'はいかがでしょうか。」', None]]
[[None, None, '\u200b\u200b', None], ['同', 'おな', None, None], [None, None, 'じ', None], ['会社', 'かいしゃ', None, None], [None, None, 'で', None], ['働', 'はたら', None, None], [None, None, 'く', None], ['上司', 'じょうし', None, None], [None, None, 'へのメール', None], [None, None, '：「まずはお', None], ['礼', 'れい', None, None], [None, None, 'かたがた', True], [None, None, 'ご', None], ['挨拶', 'あいさつ', None, None], ['申', 'もう', None, None], [None, None, 'し', None], ['上', 'あ', None, None], [None, None, 'げます。」', None]]

 98%|█████████▊| 915/938 [09:29<00:13,  1.73it/s]

[['地球', 'ちきゅう', None, None], ['温暖化', 'おんだんか', None, None], [None, None, 'が、サンタクロースに', None], ['北', 'ほっ', None, None], ['極点', 'きょくてん', None, None], [None, None, 'から', None], ['移転', 'いてん', None, None], [None, None, 'すること', None], [None, None, 'を', True], ['余儀', 'よぎ', None, True], [None, None, 'なくさせた', True], [None, None, '。', None]]
[[None, None, 'パンデミックは', None], ['店', 'みせ', None, None], [None, None, 'や', None], ['学校', 'がっこう', None, None], [None, None, 'の', None], ['閉鎖', 'へいさ', None, None], [None, None, 'を', True], ['余儀', 'よぎ', None, True], [None, None, 'なくさせた', True], [None, None, '。', None]]
[['大', 'だい', None, None], ['洪水', 'こうずい', None, None], [None, None, 'は', None], ['都市', 'とし', None, None], [None, None, 'からの', None], ['撤退', 'てったい', None, None], [None, None, 'を', True], ['余儀', 'よぎ', None, True], [None, None, 'なくさせた', True], [None, None, '。', None]]
[['７０', 'ななじゅう', None, None], ['年代', 'ねんだい', None, None], [None, None, 'のエネルギー', None], ['危機', 'きき', None, None], [None, None, 'は', None], ['政府', 'せいふ', None, None], [None, None, 'にガソリン', None], ['以外', 'いがい', None, None], [None, None, 'の', None], ['代替', 'だいたい', None, None], [None, None, 'エネルギーを', None], ['探', 'さが', None, None], [None, None, 'すこと', None], [None, None, 'を', True], ['余儀', 'よぎ', None, True], [None, None, 'なくさせた', True], [None, None, '。', None]]
[[None, None, 'バブル', None], ['崩壊', 'ほうかい', None, None], [None, None, 'が', None], ['彼', 'かれ', None, None], [None, None, 'に', None], ['会社', 'かいしゃ', None, None], [None, None, 'の', None], ['株式', 'かぶしき', None, None], [None, None, 'の', None], ['売却', 'ばいきゃく', None, None], [None, None, 'を', True], ['余儀', 'よぎ', None, True], [None, None, 'なくさせた', True], [None, None, '。', None]]

 98%|█████████▊| 916/938 [09:30<00:14,  1.57it/s]

[[None, None, ' \u200b\u200b', None], [None, None, 'アクション', None], ['映画', 'えいが', None, None], [None, None, 'の', None], [None, None, 'マッチョな', None], ['主人公', 'しゅじんこう', None, None], [None, None, '：「ぶっ', None], [None, None, 'ころしてやる', True], [None, None, '！」 ', None]]
[[None, None, '\u200b\u200b', None], [None, None, 'お', None], ['金', 'かね', None, None], [None, None, 'が', None], [None, None, 'なくて', None], ['行', 'い', None, None], [None, None, 'き', None], [None, None, 'たい', None], ['大学', 'だいがく', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'け', None], [None, None, 'ない', None], [None, None, 'という', None], ['状況', 'じょうきょう', None, None], [None, None, '：「', None], ['金持', 'かねも', None, None], [None, None, 'ち', None], [None, None, 'に', None], [None, None, 'なってやる', True], [None, None, '！」', None]]
[[None, None, '\u200b\u200b', None], ['低得点', 'ていとくてん', None, None], [None, None, 'で', None], ['馬鹿', 'ばか', None, None], [None, None, 'にさ', None], [None, None, 'れた', None], ['後', 'あと', None, None], [None, None, '：「', None], ['絶対', 'ぜったい', None, None], [None, None, '、', None], ['次', 'つぎ', None, None], [None, None, 'の', None], [None, None, 'テスト', None], [None, None, 'では', None], ['百', 'ひゃく', None, None], ['点', 'てん', None, None], ['取', 'と', None, None], [None, None, 'って', None], [None, None, '、あいつ', None], [None, None, 'を', None], [None, None, 'みかえしてやる', True], [None, None, '。」', None]]
[[None, None, '「', None], ['絶対', 'ぜったい', None, None], [None, None, '、', None], ['合格', 'ごうかく', None, None], [None, None, 'してやる', True], [None, None, '！」', None]]
[[None, None, '\u200b\u200b', None], ['Ａ', 'エー', None, None], ['子', 'こ', None, None], [None, None, '：「こっち', None], [None, None, 'から', None], [None, None, 'あっち', None], [None, None, 'まで', None], ['競走', 'きょうそう', None, None], [None, None, 'し', None], [None, None, 'よ', None], [None, None, '！」', None], [None, None, ' \u200b\u200b', None], ['Ｂ', 'ビー', None, None], ['子', 'こ', None, None], [None, None, '：「', None], [None, None, 'いい', None], [None, None, 'よ', None], [None, None, '、', None], [None, None, 'かってやる', True], [None, None, '!」', None]]

 98%|█████████▊| 917/938 [09:31<00:14,  1.42it/s]

[['Ａ', 'エー', None, None], [None, None, '：「どうやれば', None], ['作家', 'さっか', None, None], [None, None, 'になる', None], ['夢', 'ゆめ', None, None], [None, None, 'を', None], ['実現', 'じつげん', None, None], [None, None, 'する', None], [None, None, 'ことができる', None], [None, None, 'のでしょう', None], [None, None, '？」', None], [None, None, ' ', None], ['Ｂ', 'ビー', None, None], [None, None, '：「', None], [None, None, 'やっぱり', None], [None, None, 'なにごとも', None], ['練習', 'れんしゅう', None, None], [None, None, 'ある', None], [None, None, 'のみだ', True], [None, None, 'な。」 ', None]]
[[None, None, ' 「', None], [None, None, 'できる', None], [None, None, 'だけ', None], [None, None, 'の', None], [None, None, 'こと', None], [None, None, 'を', None], [None, None, 'し', None], [None, None, 'た', None], [None, None, '。', None], [None, None, 'あとは', None], ['降伏', 'こうふく', None, None], [None, None, 'する', None], [None, None, 'のみだ', True], [None, None, '。」', None]]
[['人生', 'じんせい', None, None], [None, None, 'に', None], [None, None, 'は', None], ['後悔', 'こうかい', None, None], [None, None, 'する', None], ['暇', 'ひま', None, None], [None, None, 'なんて', None], [None, None, 'あり', None], [None, None, 'ません', None], [None, None, '。', None], [None, None, 'ただ', None], ['前進', 'ぜんしん', None, None], [None, None, 'ある', None], [None, None, 'のみです', True], [None, None, '。', None]]
[[None, None, 'テスト', None], [None, None, 'を', None], ['受', 'う', None, None], [None, None, 'け', None], [None, None, 'た', None], ['後', 'あと', None, None], [None, None, '、', None], [None, None, 'ただ', None], ['結果', 'けっか', None, None], [None, None, 'を', None], ['待', 'ま', None, None], [None, None, 'つ', None], [None, None, 'のみだ', True], [None, None, '。', None]]
[[None, None, '「', None], [None, None, 'この', None], [None, None, 'ような', None], ['状況', 'じょうきょう', None, None], [None, None, 'で', None], [None, None, 'は', None], [None, None, 'ただ', None], ['前', 'まえ', None, None], [None, None, 'に', None], ['進', 'すす', None, None], [None, None, 'んで', None], ['迎', 'むか', None, None], [None, None, 'えに', None], ['行', 'い', None, None], [None, None, 'く', None], [None, None, 'のみであります', True], [None, None, '。」', None]]

 98%|█████████▊| 918/938 [09:31<00:12,  1.54it/s]

[[None, None, ' ', None], ['契約', 'けいやく', None, None], ['者', 'しゃ', None, None], [None, None, 'は', None], [None, None, '、', None], ['次', 'つぎ', None, None], [None, None, 'に', None], ['掲', 'かか', None, None], [None, None, 'げる', None], ['業務', 'ぎょうむ', None, None], [None, None, 'を', None], ['行', 'おこな', None, None], [None, None, 'う', None], [None, None, 'ものとする', True], [None, None, '。', None]]
[[None, None, ' ', None], ['別表', 'べっぴょう', None, None], ['第', 'だい', None, None], ['七', 'なな', None, None], [None, None, 'に', None], ['定', 'さだ', None, None], [None, None, 'める', None], ['帳簿', 'ちょうぼ', None, None], [None, None, 'は、', None], ['五', 'ご', None, None], ['年間', 'ねんかん', None, None], ['保存', 'ほぞん', None, None], [None, None, 'する', None], [None, None, 'ものとする', True], [None, None, '。', None]]
[[None, None, ' ', None], ['当該', 'とうがい', None, None], ['研究', 'けんきゅう', None, None], [None, None, 'は', None], [None, None, '、', None], ['法令', 'ほうれい', None, None], [None, None, 'の', None], ['範囲', 'はんい', None, None], ['内', 'ない', None, None], [None, None, 'で', None], ['行', 'おこな', None, None], [None, None, 'う', None], [None, None, 'ものとする', True], [None, None, '。', None]]
[[None, None, ' ', None], ['延滞', 'えんたい', None, None], ['金', 'きん', None, None], [None, None, 'は', None], [None, None, '、', None], ['納付', 'のうふ', None, None], ['金', 'きん', None, None], [None, None, 'に', None], ['先立', 'さきだ', None, None], [None, None, 'つ', None], [None, None, 'ものとする', True], [None, None, '。', None]]
[[None, None, ' ', None], ['契約', 'けいやく', None, None], ['書', 'しょ', None, None], [None, None, 'は', None], [None, None, '、', None], ['英語', 'えいご', None, None], [None, None, 'と', None], ['日本語', 'にほんご', None, None], [None, None, 'をもって', None], ['記載', 'きさい', None, None], [None, None, 'する', None], [None, None, 'ものとする', True], [None, None, '。', None]]

 98%|█████████▊| 919/938 [09:32<00:11,  1.63it/s]

[[None, None, ' ', None], ['多', 'おお', None, None], [None, None, 'く', None], [None, None, 'の', None], ['経済', 'けいざい', None, None], ['学者', 'がくしゃ', None, None], [None, None, 'は', None], [None, None, '、', None], ['景気', 'けいき', None, None], [None, None, 'が', None], ['回復', 'かいふく', None, None], [None, None, 'し', None], [None, None, 'つつある', None], [None, None, 'との', True], ['見方', 'みかた', None, None], [None, None, 'を', None], ['維持', 'いじ', None, None], [None, None, 'し', None], [None, None, 'た', None], [None, None, '。', None]]
[[None, None, ' ', None], ['政府', 'せいふ', None, None], ['関係', 'かんけい', None, None], ['者', 'しゃ', None, None], [None, None, 'は', None], ['電気', 'でんき', None, None], ['自動車', 'じどうしゃ', None, None], [None, None, 'の', None], ['普及', 'ふきゅう', None, None], [None, None, 'を', None], ['推進', 'すいしん', None, None], [None, None, 'する', None], [None, None, 'との', True], ['意向', 'いこう', None, None], [None, None, 'を', None], ['強調', 'きょうちょう', None, None], [None, None, 'し', None], [None, None, 'た', None], [None, None, '。', None]]
[[None, None, ' ', None], ['田中', 'たなか', None, None], [None, None, 'さん', None], [None, None, 'は', None], ['新', 'あたら', None, None], [None, None, 'しい', None], ['反', 'はん', None, None], [None, None, 'トラスト', None], ['法', 'ほう', None, None], [None, None, 'が', None], ['抜', 'ぬ', None, None], [None, None, 'け', None], ['穴', 'あな', None, None], [None, None, 'だらけ', None], [None, None, 'との', True], ['意見', 'いけん', None, None], [None, None, 'を', None], ['表明', 'ひょうめい', None, None], [None, None, 'した。', None]]
[[None, None, ' ', None], ['探偵', 'たんてい', None, None], [None, None, 'の', None], ['伝記', 'でんき', None, None], [None, None, '：「', None], ['２００２', 'にせんに', None, None], ['年', 'ねん', None, None], [None, None, '、', None], ['彼', 'かれ', None, None], [None, None, 'は', None], [None, None, '、', None], ['南', 'みなみ', None, None], [None, None, 'アフリカ', None], [None, None, 'に', None], ['連', 'つ', None, None], [None, None, 'れて', None], ['行', 'い', None, None], [None, None, 'っ', None], [None, None, 'た', None], ['男性', 'だんせい', None, None], [None, None, 'の', None], ['家出', 'いえで', None, None], ['人', 'にん', None, None], [None, None, 'を', None], ['探', 'さが', None, None], [None, None, 'し', None], [None, None, 'てほしい', None], [None, None, 'との', True], ['依頼', 'いらい', None, None], [None, None, 'を', None], ['受', 'う', None, None], [None, None, 'け', None], [None, None, 'た', None], [None, None, '。」', None]]
[[None, None, 'あの', None], ['日', 'ひ', None, None], [None, None, '、 ', None], ['雪崩', 'なだれ', None, None], [None, None, 'が', None], ['発生', 'はっせい', None, None], [None, None, 'し', None], [None, None, 'た', None], [None, None, 'との', True], ['報告', 'ほうこく', None, None], [None, None, 'も', None], [None, None, 'あ', None], [None, None, 'っ', None], [None, None, 'た', None], [None, None, 'が', None], [None, None, '、', None], [None, None, 'けが', None], ['人', 'にん', None, None], [None, None, 'が', None], ['出', 'で', None, None], [None, None, 'ている', None], [None, None, 'かどうか', None], [None, None, 'は', None], ['確認', 'かくにん', None, None], [None, None, 'され', None], [None, None, 'ていなかった。', None]]

 98%|█████████▊| 920/938 [09:32<00:10,  1.65it/s]

[[None, None, 'ポイ', None], ['捨', 'す', None, None], [None, None, 'て', None], [None, None, 'は', None], ['法律', 'ほうりつ', None, None], [None, None, 'いぜん', True], [None, None, 'の', None], ['道義', 'どうぎ', None, None], ['的', 'てき', None, None], [None, None, 'な', None], ['問題', 'もんだい', None, None], [None, None, 'だ', None], [None, None, '。', None]]
[[None, None, ' ', None], ['彼', 'かれ', None, None], [None, None, 'は', None], [None, None, '、', None], ['自分', 'じぶん', None, None], [None, None, 'が', None], ['女', 'おんな', None, None], [None, None, 'の', None], ['子', 'こ', None, None], [None, None, 'にモテ', None], [None, None, 'ない', None], [None, None, 'の', None], [None, None, 'は', None], [None, None, 'ファッション', None], [None, None, 'が', None], [None, None, 'ださ', None], [None, None, 'い', None], [None, None, 'から', None], [None, None, 'だと', None], ['思', 'おも', None, None], [None, None, 'ってる', None], [None, None, '。', None], [None, None, 'それ', None], [None, None, 'は', None], ['事実', 'じじつ', None, None], [None, None, 'だけど', None], [None, None, '、', None], [None, None, 'それ', None], [None, None, 'いぜん', True], [None, None, 'の', None], ['問題', 'もんだい', None, None], [None, None, 'として、', None], ['彼', 'かれ', None, None], [None, None, 'は', None], ['性格', 'せいかく', None, None], [None, None, 'に', None], ['問題', 'もんだい', None, None], [None, None, 'がある', None], [None, None, '。', None]]
[[None, None, ' ', None], ['信', 'しん', None, None], [None, None, 'じる', None], ['信', 'しん', None, None], [None, None, 'じ', None], [None, None, 'ない', None], [None, None, 'いぜん', True], [None, None, 'に', None], [None, None, 'もっと', None], ['根本', 'こんぽん', None, None], ['的', 'てき', None, None], [None, None, 'な', None], ['問題', 'もんだい', None, None], [None, None, 'なんだ', None], [None, None, 'よ', None], [None, None, '。', None], ['先', 'ま', None, None], [None, None, 'ず', None], [None, None, 'どうにか', None], ['彼女', 'かのじょ', None, None], [None, None, 'に', None], [None, None, 'この', None], ['事', 'こと', None, None], [None, None, 'を', None], ['伝', 'つた', None, None], [None, None, 'え', None], [None, None, 'なきゃ', None], [None, None, '。', None]]
[[None, None, ' ', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'ずに', None], [None, None, '「ブロッコリー', None], [None, None, 'が', None], ['嫌', 'きら', None, None], [None, None, 'い', None], [None, None, '」という', None], ['人', 'ひと', None, None], [None, None, 'も', None], [None, None, 'います', None], [None, None, '。', None], ['好', 'す', None, None], [None, None, 'き', None], ['嫌', 'きら', None, None], [None, None, 'い', None], [None, None, 'いぜん', True], [None, None, 'に、', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'てみる', None], [None, None, 'こと', None], [None, None, 'が', None], ['大事', 'だいじ', None, None], [None, None, 'なのです', None], [None, None, '。', None], ['食', 'た', None, None], [None, None, 'べ', None], [None, None, 'た', None], ['上', 'うえ', None, None], [None, None, 'で', None], [None, None, '、', None], ['好', 'す', None, None], [None, None, 'き', None], ['嫌', 'きら', None, None], [None, None, 'い', None], [None, None, 'は', None], [None, None, 'ご', None], ['自由', 'じゆう', None, None], [None, None, 'に', None], [None, None, '。', None]]
[[None, None, ' パフォーマンス', None], [None, None, 'いぜん', True], [None, None, 'の', None], ['問題', 'もんだい', None, None], [None, None, 'で、', None], ['基本', 'きほん', None, None], ['的', 'てき', None, None], [None, None, 'な', None], ['機能', 'きのう', None, None], [None, None, 'を', None], ['実装', 'じっそう', None, None], [None, None, 'する', None], ['必要', 'ひつよう', None, None], [None, None, 'があります', None], [None, None, '。', None]]

 98%|█████████▊| 921/938 [09:33<00:10,  1.61it/s]

[[None, None, 'この', None], ['田中', 'たなか', None, None], [None, None, 'さん', None], [None, None, 'ともあろう', True], [None, None, 'ものが', None], [None, None, 'くだらないミスをしてしまった。', None]]
[['大', 'だい', None, None], ['自然', 'しぜん', None, None], [None, None, 'を', None], ['保護', 'ほご', None, None], [None, None, 'することを', None], ['呼', 'よ', None, None], [None, None, 'びかけている', None], ['国会', 'こっかい', None, None], ['議員', 'ぎいん', None, None], [None, None, 'ともあろう', True], [None, None, 'ものが', None], [None, None, '、', None], ['砂浜', 'すなはま', None, None], [None, None, 'にごみを', None], ['散', 'ち', None, None], [None, None, 'らかすとは', None], ['信', 'しん', None, None], [None, None, 'じられない。', None]]
[['乱世', 'らんせい', None, None], [None, None, 'の', None], ['時', 'とき', None, None], [None, None, 'にこんなふざけた', None], ['言動', 'げんどう', None, None], [None, None, 'があるだろうか。', None], ['議員', 'ぎいん', None, None], [None, None, 'ともあろう', True], [None, None, 'ものが', None], [None, None, '…', None]]
[['上司', 'じょうし', None, None], [None, None, 'が', None], ['部下', 'ぶか', None, None], ['坂', 'さか', None, None], ['本', 'もと', None, None], [None, None, 'に', None], [None, None, '：「', None], ['君', 'きみ', None, None], [None, None, 'ともあろう', True], ['優秀', 'ゆうしゅう', None, None], [None, None, 'な', None], ['部下', 'ぶか', None, None], [None, None, 'が', None], [None, None, 'こんなミスをするなんて。なぜあんなことを？」', None]]
[[None, None, 'ファンタジー', None], ['映画', 'えいが', None, None], [None, None, '：「 ', None], ['賢', 'かしこ', None, None], [None, None, 'いウィザード', None], [None, None, 'ともあろう', True], ['者', 'もの', None, None], [None, None, 'が', None], [None, None, 'いつ', None], ['正気', 'しょうき', None, None], [None, None, 'を', None], ['失', 'うしな', None, None], [None, None, 'った？」', None]]

 98%|█████████▊| 922/938 [09:34<00:10,  1.57it/s]

[[None, None, 'セキュリティ', None], ['事故', 'じこ', None, None], [None, None, 'は', None], ['増', 'ふ', None, True], [None, None, 'えこそすれ', True], [None, None, '、', None], ['減', 'へ', None, None], [None, None, 'りはしないだろう。', None]]
[[None, None, ' ', None], ['小説', 'しょうせつ', None, None], [None, None, '：「だが', None], ['実際', 'じっさい', None, None], [None, None, 'は、', None], ['剣士', 'けんし', None, None], [None, None, 'の', None], ['復讐', 'ふくしゅう', None, None], ['心', 'しん', None, None], [None, None, 'は', None], ['火', 'ひ', None, None], [None, None, 'の', None], ['手', 'て', None, None], [None, None, 'を', None], ['強', 'つよ', None, True], [None, None, 'めこそすれ', True], [None, None, '、', None], ['決', 'けっ', None, None], [None, None, 'して', None], ['冷', 'さ', None, None], [None, None, 'めるどころではなかったのである。」', None]]
[['多', 'おお', None, None], [None, None, 'くの', None], ['人', 'ひと', None, None], [None, None, 'にとって、その', None], ['奇妙', 'きみょう', None, None], [None, None, 'な', None], ['現象', 'げんしょう', None, None], [None, None, 'は', None], ['驚', 'おどろ', None, True], [None, None, 'きこそすれ', True], [None, None, '、', None], ['恐怖', 'きょうふ', None, None], [None, None, 'を', None], ['感', 'かん', None, None], [None, None, 'じるほどではなかった。', None]]
[['魔法使', 'まほうつか', None, None], [None, None, 'いへの', None], ['恋情', 'れんじょう', None, None], [None, None, 'は、', None], ['強', 'つよ', None, True], [None, None, 'めこそすれ', True], ['弱', 'よわ', None, None], [None, None, 'めるものではなかった。', None]]
[['感謝', 'かんしゃ', None, True], [None, None, 'こそすれ', True], [None, None, '、', None], ['憎', 'にく', None, None], [None, None, 'しみを', None], ['感', 'かん', None, None], [None, None, 'じるなんてちゃんちゃらおかしいよ。', None]]

 98%|█████████▊| 923/938 [09:34<00:09,  1.56it/s]

[['私', 'わたし', None, None], [None, None, 'の', None], ['妻', 'つま', None, None], [None, None, 'の', None], ['歌', 'うた', None, None], [None, None, 'はプロ', None], ['並', 'な', None, True], [None, None, 'み', True], [None, None, 'だ。', None]]
[[None, None, 'アトランタの', None], ['年間', 'ねんかん', None, None], ['日照', 'にっしょう', None, None], ['時間', 'じかん', None, None], [None, None, 'は、ローマ', None], ['平均', 'へいきん', None, None], ['並', 'な', None, True], [None, None, 'み', True], [None, None, 'である。', None]]
[[None, None, 'チタンは', None], ['鋼鉄', 'こうてつ', None, None], ['並', 'な', None, True], [None, None, 'みの', True], ['丈夫', 'じょうぶ', None, None], [None, None, 'さだが、はるかに', None], ['軽量', 'けいりょう', None, None], [None, None, 'である。', None]]
[[None, None, 'この', None], ['映画', 'えいが', None, None], [None, None, 'はアカデミー', None], ['賞', 'しょう', None, None], ['並', 'な', None, True], [None, None, 'みの', True], ['功績', 'こうせき', None, None], [None, None, 'でした。', None]]
[['統計', 'とうけい', None, None], [None, None, 'から', None], ['推測', 'すいそく', None, None], [None, None, 'すると、', None], ['中国', 'ちゅうごく', None, None], [None, None, 'の', None], ['経済', 'けいざい', None, None], [None, None, 'は', None], ['先進', 'せんしん', None, None], ['国', 'こく', None, None], ['並', 'な', None, True], [None, None, 'み', True], [None, None, 'になってきている。', None]]

 99%|█████████▊| 924/938 [09:35<00:08,  1.65it/s]

[['１７６３', 'せんななひゃくろくじゅうさん', None, None], ['年', 'ねん', None, None], [None, None, 'に、プロイセンは', None], ['他国', 'たこく', None, None], [None, None, 'に', True], ['先駆', 'さきが', None, True], [None, None, 'けて', True], ['近代', 'きんだい', None, None], ['的', 'てき', None, None], [None, None, 'な', None], ['義務', 'ぎむ', None, None], ['教育', 'きょういく', None, None], [None, None, 'を', None], ['導入', 'どうにゅう', None, None], [None, None, 'した。', None]]
[[None, None, 'コンサートのサイト', None], [None, None, '：「ファンクラブでは、', None], ['一般', 'いっぱん', None, None], ['発売', 'はつばい', None, None], [None, None, 'に', True], ['先駆', 'さきが', None, True], [None, None, 'けて', True], [None, None, '、チケットの', None], ['販売', 'はんばい', None, None], [None, None, 'を', None], ['行', 'おこな', None, None], [None, None, 'います。」', None]]
[['広告', 'こうこく', None, None], [None, None, '：「', None], ['世界', 'せかい', None, None], [None, None, 'の', None], ['人々', 'ひとびと', None, None], [None, None, 'に', True], ['先駆', 'さきが', None, True], [None, None, 'けて', True], [None, None, '、', None], ['楽', 'たの', None, None], [None, None, 'しみながら', None], ['学', 'まな', None, None], [None, None, 'ぶ', None], ['体験', 'たいけん', None, None], ['型', 'がた', None, None], ['博物館', 'はくぶつかん', None, None], [None, None, 'を', None], ['訪', 'おとず', None, None], [None, None, 'れてみてはいかがでしょう。」', None]]
[['我', 'わ', None, None], [None, None, 'が', None], ['社', 'しゃ', None, None], [None, None, 'は', None], ['他社', 'たしゃ', None, None], [None, None, 'に', True], ['先駆', 'さきが', None, True], [None, None, 'けて', True], ['世界', 'せかい', None, None], ['初', 'はつ', None, None], [None, None, 'となる', None], ['海流', 'かいりゅう', None, None], ['発電', 'はつでん', None, None], [None, None, 'の', None], ['実証', 'じっしょう', None, None], ['実験', 'じっけん', None, None], [None, None, 'を', None], ['成功', 'せいこう', None, None], [None, None, 'させた。', None]]
[[None, None, 'スプートニク', None], ['１号', 'いちごう', None, None], [None, None, 'は', None], ['世界', 'せかい', None, None], [None, None, 'に', True], ['先駆', 'さきが', None, True], [None, None, 'けて', True], ['打', 'う', None, None], [None, None, 'ち', None], ['上', 'あ', None, None], [None, None, 'げられた', None], ['人工', 'じんこう', None, None], ['衛星', 'えいせい', None, None], [None, None, 'です。', None]]

 99%|█████████▊| 925/938 [09:35<00:07,  1.72it/s]

[['小説', 'しょうせつ', None, None], [None, None, '：「', None], ['３', 'さん', None, None], ['ヶ月', 'かげつ', None, None], ['目', 'め', None, None], [None, None, 'にやっと', None], ['病気', 'びょうき', None, None], [None, None, 'が', None], ['完治', 'かんち', None, None], [None, None, 'し、これ', None], [None, None, 'を', True], ['機', 'き', None, True], [None, None, 'に', True], [None, None, '、', None], ['入院', 'にゅういん', None, None], ['後', 'ご', None, None], ['初', 'はじ', None, None], [None, None, 'めて', None], ['退院', 'たいいん', None, None], [None, None, 'することができた。」', None]]
[['伝記', 'でんき', None, None], [None, None, '：「', None], ['大学', 'だいがく', None, None], ['卒業', 'そつぎょう', None, None], [None, None, 'を', True], ['機', 'き', None, True], [None, None, 'に', True], ['大阪', 'おおさか', None, None], [None, None, 'へ', None], ['移', 'うつ', None, None], [None, None, 'り、プログラミングの', None], ['職', 'しょく', None, None], [None, None, 'を', None], ['得', 'え', None, None], [None, None, 'ることができました。」', None]]
[['演説', 'えんぜつ', None, None], [None, None, '：「', None], ['今回', 'こんかい', None, None], [None, None, 'の', None], ['訪問', 'ほうもん', None, None], [None, None, 'を', True], ['機', 'き', None, True], [None, None, 'に', True], [None, None, '、より', None], ['多', 'おお', None, None], [None, None, 'くのアメリカ', None], ['人', 'じん', None, None], [None, None, 'が', None], ['日本', 'にほん', None, None], [None, None, 'で', None], ['働', 'はたら', None, None], [None, None, 'くことに', None], ['興味', 'きょうみ', None, None], [None, None, 'を', None], ['持', 'も', None, None], [None, None, 'つことを', None], ['願', 'ねが', None, None], [None, None, 'っています。」', None]]
[['小説', 'しょうせつ', None, None], [None, None, '：「', None], ['結婚', 'けっこん', None, None], [None, None, 'を', True], ['機', 'き', None, True], [None, None, 'に', True], [None, None, 'たまひこは', None], ['東京', 'とうきょう', None, None], [None, None, 'を', None], ['離', 'はな', None, None], [None, None, 'れ、', None], ['千葉', 'ちば', None, None], [None, None, 'の', None], ['町', 'まち', None, None], [None, None, 'でゆずきとふたりの', None], ['新', 'しん', None, None], ['生活', 'せいかつ', None, None], [None, None, 'を', None], ['始', 'はじめ', None, None], [None, None, 'じめた。」', None]]
[['伝記', 'でんき', None, None], [None, None, '：「ひろしは', None], ['５６', 'ごじゅうろく', None, None], ['歳', 'さい', None, None], [None, None, 'の', None], ['時', 'とき', None, None], ['故郷', 'こきょう', None, None], [None, None, 'へ', None], ['戻', 'もど', None, None], [None, None, 'ったの', None], [None, None, 'を', True], ['機', 'き', None, True], [None, None, 'に', True], [None, None, '、', None], ['両親', 'りょうしん', None, None], [None, None, 'の', None], ['墓参', 'はかまい', None, None], [None, None, 'りに', None], ['行', 'い', None, None], [None, None, 'った。」', None]]

 99%|█████████▊| 926/938 [09:36<00:07,  1.69it/s]

[['鍵', 'かぎ', None, None], [None, None, 'をなくした…。これは', None], ['弱', 'よわ', None, None], [None, None, 'った', None], [None, None, 'ぞ', True], [None, None, '。', None]]
[[None, None, 'やった〜！', None], ['実験', 'じっけん', None, None], [None, None, 'が', None], ['上手', 'うま', None, None], [None, None, 'くいった', None], [None, None, 'ぞ', True], [None, None, '！', None]]
[[None, None, 'スケジュールより', None], ['遅', 'おく', None, None], [None, None, 'れている。', None], ['急', 'いそ', None, None], [None, None, 'ぐ', None], [None, None, 'ぞ', True], [None, None, '！', None]]
[['走', 'はし', None, None], [None, None, 'るのが', None], ['遅', 'おそ', None, None], [None, None, 'い', None], [None, None, 'ぞ', True], [None, None, '！もっと', None], ['速', 'はや', None, None], [None, None, 'く', None], ['走', 'はし', None, None], [None, None, 'りなさい！', None]]
[[None, None, 'ヒーロー：「あの', None], ['怪物', 'かいぶつ', None, None], [None, None, 'に', None], ['好', 'す', None, None], [None, None, 'き', None], ['勝手', 'かって', None, None], [None, None, 'はさせない', None], [None, None, 'ぞ', True], [None, None, '！」', None]]

 99%|█████████▉| 927/938 [09:37<00:07,  1.53it/s]

[['外', 'そと', None, None], [None, None, 'を', None], ['見', 'み', None, None], [None, None, 'ろ！', None], ['雪', 'ゆき', None, None], [None, None, 'が', None], ['降', 'ふ', None, None], [None, None, 'っている', None], [None, None, 'ぜ', True], [None, None, '！', None]]
[[None, None, 'やっほー！', None], ['計画', 'けいかく', None, None], [None, None, 'が', None], ['上手', 'うま', None, None], [None, None, 'くいった', None], [None, None, 'ぜ', True], [None, None, '！', None]]
[['父', 'ちち', None, None], [None, None, '：「お', None], ['前', 'まえ', None, None], [None, None, 'の', None], ['誕生日', 'たんじょうび', None, None], [None, None, 'に', None], ['遊園地', 'ゆうえんち', None, None], [None, None, 'に', None], ['行', 'い', None, None], [None, None, 'こう', None], [None, None, 'ぜ', True], [None, None, '！」', None]]
[['同僚', 'どうりょう', None, None], [None, None, '：「', None], ['一緒', 'いっしょ', None, None], [None, None, 'にタバコを', None], ['吸', 'す', None, None], [None, None, 'いに', None], ['行', 'い', None, None], [None, None, 'こう', None], [None, None, 'ぜ', True], [None, None, '！」', None]]
[[None, None, 'あの', None], ['先生', 'せんせい', None, None], [None, None, 'は', None], ['怖', 'こわ', None, None], [None, None, 'いから、', None], ['反抗', 'はんこう', None, None], [None, None, 'しない', None], ['方', 'ほう', None, None], [None, None, 'がいい', None], [None, None, 'ぜ', True], [None, None, '！', None]]

 99%|█████████▉| 928/938 [09:37<00:06,  1.56it/s]

[['私', 'わたし', None, None], [None, None, 'もその', None], ['香水', 'こうすい', None, None], [None, None, 'が', None], ['欲', 'ほ', None, None], [None, None, 'しい', None], [None, None, 'わ', True], [None, None, '！', None]]
[['過去', 'かこ', None, None], [None, None, 'の', None], ['彼氏', 'かれし', None, None], [None, None, 'たちのことは', None], ['忘', 'わす', None, None], [None, None, 'れた', None], [None, None, 'わ', True], [None, None, '。', None]]
[[None, None, 'あら、あのキラキラの', None], ['指輪', 'ゆびわ', None, None], [None, None, 'は', None], ['綺麗', 'きれい', None, None], [None, None, 'だ', None], [None, None, 'わ', True], [None, None, '！', None]]
[['私', 'わたし', None, None], [None, None, 'にバラの', None], ['花束', 'はなたば', None, None], [None, None, 'をくれるの？', None], ['素敵', 'すてき', None, None], [None, None, 'だ', None], [None, None, 'わ', True], [None, None, '！', None]]
[['女', 'おんな', None, None], [None, None, 'の', None], ['子', 'こ', None, None], [None, None, 'に', None], ['暴力', 'ぼうりょく', None, None], [None, None, 'を', None], ['振', 'ふ', None, None], [None, None, 'るう', None], ['人', 'ひと', None, None], [None, None, 'は', None], ['嫌', 'きら', None, None], [None, None, 'いだ', None], [None, None, 'わ', True], [None, None, '。', None]]

 99%|█████████▉| 929/938 [09:39<00:07,  1.24it/s]

[['君', 'きみ', None, None], [None, None, 'も', None], ['飲', 'の', None, None], [None, None, 'み', None], ['会', 'かい', None, None], [None, None, 'に', None], ['来', 'く', None, None], [None, None, 'るか', None], [None, None, 'い', True], [None, None, '？', None]]
[['君', 'きみ', None, None], [None, None, 'は', None], ['将来', 'しょうらい', None, None], [None, None, '、', None], ['何', 'なに', None, None], [None, None, 'になりたいんだ', None], [None, None, 'い', True], [None, None, '？', None]]
[['迷子', 'まいご', None, None], [None, None, 'かい？', None], ['一緒', 'いっしょ', None, None], [None, None, 'にお', None], ['母', 'かあ', None, None], [None, None, 'さんを', None], ['探', 'さが', None, None], [None, None, 'すか', None], [None, None, 'い', True], [None, None, '？', None]]
[['何', 'なに', None, None], [None, None, 'を', None], ['悩', 'なや', None, None], [None, None, 'んでいるだ', None], [None, None, 'い', True], [None, None, '？', None], ['僕', 'ぼく', None, None], [None, None, 'に', None], ['相談', 'そうだん', None, None], [None, None, 'しなさい。', None]]
[['何時', 'なんじ', None, None], [None, None, 'までに', None], ['家', 'いえ', None, None], [None, None, 'に', None], ['帰', 'かえ', None, None], [None, None, 'らなくちゃいけないんだ', None], [None, None, 'い', True], [None, None, '？', None]]

 99%|█████████▉| 930/938 [09:39<00:05,  1.33it/s]

[[None, None, 'あいつは', None], ['日本語', 'にほんご', None, None], [None, None, 'が', None], ['分', 'わ', None, None], [None, None, 'か', None], [None, None, 'ん', True], [None, None, 'ない。', None]]
[['赤', 'あか', None, None], [None, None, 'ちゃんはみんな', None], ['言葉', 'ことば', None, None], [None, None, 'を', None], ['喋', 'しゃべ', None, None], [None, None, 'ん', True], [None, None, 'ない。', None]]
[['僕', 'ぼく', None, None], [None, None, 'の', None], ['１５', 'じゅうご', None, None], ['歳', 'さい', None, None], [None, None, 'のシーズーはもう', None], ['走', 'はし', None, None], [None, None, 'ん', True], [None, None, 'ない。', None]]
[['材料', 'ざいりょう', None, None], [None, None, 'を', None], ['計', 'はか', None, None], [None, None, 'ん', True], [None, None, 'ないでケーキを', None], ['作', 'つく', None, None], [None, None, 'ったから', None], ['失敗', 'しっぱい', None, None], [None, None, 'した。', None]]
[[None, None, 'テレビの', None], ['音', 'おと', None, None], [None, None, 'が', None], ['鳴', 'な', None, None], [None, None, 'ん', True], [None, None, 'ないからカスタマーセンターに', None], ['電話', 'でんわ', None, None], [None, None, 'をした。', None]]

 99%|█████████▉| 931/938 [09:40<00:04,  1.41it/s]

[['彼', 'かれ', None, None], [None, None, 'は「もうすぐで', None], ['来', 'く', None, None], [None, None, 'る」', None], [None, None, 'っつ', True], [None, None, 'った。', None]]
[[None, None, 'あの', None], ['人', 'ひと', None, None], [None, None, 'は「', None], ['山田', 'やまだ', None, None], [None, None, '」', None], [None, None, 'つう', True], ['男', 'おとこ', None, None], [None, None, 'だ。', None]]
[[None, None, '「', None], ['俺', 'おれ', None, None], [None, None, 'の', None], ['話', 'はなし', None, None], [None, None, 'を', None], ['聞', 'き', None, None], [None, None, 'け」', None], [None, None, 'つ', True], [None, None, 'ってんだよ。', None]]
[[None, None, 'グランピング', None], [None, None, 'つう', True], [None, None, 'ものをしてみたい。', None]]
[[None, None, '「ここから', None], ['立', 'た', None, None], [None, None, 'ち', None], ['去', 'さ', None, None], [None, None, 'れ」', None], [None, None, 'つ', True], [None, None, 'ってんだよ。', None]]

 99%|█████████▉| 932/938 [09:40<00:04,  1.47it/s]

[[None, None, 'あいつ、', None], ['俺', 'おれ', None, None], [None, None, 'に', None], ['嘘', 'うそ', None, None], [None, None, 'をつき', None], [None, None, 'やがった', True], [None, None, '！', None]]
[[None, None, 'あの', None], ['居酒屋', 'いざかや', None, None], [None, None, 'はぼったくりをし', None], [None, None, 'やがる', True], [None, None, '。', None]]
[[None, None, 'あの', None], ['野郎', 'やろう', None, None], [None, None, '、', None], ['俺', 'おれ', None, None], [None, None, 'にデタラメを', None], ['教', 'おし', None, None], [None, None, 'え', None], [None, None, 'やがった', True], [None, None, '！', None]]
[[None, None, 'あのガキ、', None], ['俺', 'おれ', None, None], [None, None, 'に', None], ['偉', 'えら', None, None], [None, None, 'そうな', None], ['態度', 'たいど', None, None], [None, None, 'をとり', None], [None, None, 'やがる', True], [None, None, '！', None]]
[[None, None, 'あの', None], ['女', 'おんな', None, None], [None, None, '、', None], ['俺', 'おれ', None, None], [None, None, 'を', None], ['騙', 'だま', None, None], [None, None, 'してお', None], ['金', 'かね', None, None], [None, None, 'を', None], ['奪', 'うば', None, None], [None, None, 'い', None], [None, None, 'やがった', True], [None, None, '！', None]]

 99%|█████████▉| 933/938 [09:41<00:03,  1.51it/s]

[[None, None, 'そこの', None], ['君', 'きみ', None, None], [None, None, '、', None], ['喉', 'のど', None, None], [None, None, 'が', None], ['渇', 'かわ', None, None], [None, None, 'いてそうだな。ちょうど', None], ['俺', 'おれ', None, None], [None, None, 'の', None], ['飲', 'の', None, None], [None, None, 'みかけの', None], ['水', 'みず', None, None], [None, None, 'があるからこれでも', None], ['飲', 'の', None, None], [None, None, 'む', None], [None, None, 'がいい', True], [None, None, '。', None]]
[['私', 'わたし', None, None], [None, None, 'に', None], ['着', 'つ', None, None], [None, None, 'いてくる', None], [None, None, 'がいい', True], [None, None, '。', None]]
[['王', 'おう', None, None], [None, None, 'である', None], ['私', 'わたし', None, None], [None, None, 'に', None], ['跪', 'ひざまず', None, None], [None, None, 'く', None], [None, None, 'がよい', True], [None, None, '。', None]]
[[None, None, 'お', None], ['前', 'まえ', None, None], [None, None, 'は', None], ['俺様', 'おれさま', None, None], [None, None, 'に', None], ['仕', 'つか', None, None], [None, None, 'える', None], [None, None, 'がいい', True], [None, None, '。', None]]
[['今日', 'きょう', None, None], [None, None, 'から', None], ['私', 'わたし', None, None], [None, None, 'の', None], ['言', 'い', None, None], [None, None, 'いなりになる', None], [None, None, 'がいい', True], [None, None, '。', None]]

100%|█████████▉| 934/938 [09:42<00:02,  1.54it/s]

[[None, None, 'ブランド', None], ['物', 'もの', None, None], [None, None, 'のあのバッグは', None], ['高', 'たか', None, None], [None, None, 'かろう', True], [None, None, '。', None]]
[['老舗', 'しにせ', None, None], [None, None, 'の', None], ['団子屋', 'だんごや', None, None], [None, None, 'さんの', None], ['団子', 'だんご', None, None], [None, None, 'は', None], ['美味', 'おい', None, None], [None, None, 'し', None], [None, None, 'かろう', True], [None, None, '。', None]]
[['家', 'いえ', None, None], [None, None, 'で', None], ['一人', 'ひとり', None, None], [None, None, 'で', None], ['留守番', 'るすばん', None, None], [None, None, 'をするのは', None], ['寂', 'さみ', None, None], [None, None, 'し', None], [None, None, 'かろう', True], [None, None, '。', None]]
[[None, None, 'このドレスは', None], ['生地', 'きじ', None, None], [None, None, 'がペラペラだから', None], ['安', 'やす', None, None], [None, None, 'かろう', True], [None, None, '。', None]]
[['友達', 'ともだち', None, None], [None, None, 'が', None], ['多', 'おお', None, None], [None, None, 'い', None], ['人', 'ひと', None, None], [None, None, 'は、', None], ['学校', 'がっこう', None, None], [None, None, 'も', None], ['毎日', 'まいにち', None, None], ['楽', 'たの', None, None], [None, None, 'し', None], [None, None, 'かろう', True], [None, None, '。', None]]

100%|█████████▉| 935/938 [09:42<00:01,  1.57it/s]

[['今週', 'こんしゅう', None, None], [None, None, 'は', None], ['先週', 'せんしゅう', None, None], [None, None, 'よりも', None], [None, None, 'やや', True], ['涼', 'すず', None, None], [None, None, 'しいです。', None]]
[[None, None, 'このお', None], ['店', 'みせ', None, None], [None, None, 'は', None], [None, None, 'やや', True], ['高', 'たか', None, None], [None, None, 'めで、', None], ['買', 'か', None, None], [None, None, 'いにくい。', None]]
[['彼女', 'かのじょ', None, None], [None, None, 'の', None], ['殴', 'なぐ', None, None], [None, None, 'り', None], ['書', 'が', None, None], [None, None, 'きは', None], [None, None, 'やや', True], ['読', 'よ', None, None], [None, None, 'みにくいです。', None]]
[['計画', 'けいかく', None, None], [None, None, 'が', None], ['失敗', 'しっぱい', None, None], [None, None, 'して', None], [None, None, 'やや', True], [None, None, 'イライラしています。', None]]
[['商品', 'しょうひん', None, None], [None, None, 'の', None], ['値段', 'ねだん', None, None], [None, None, 'を', None], ['高', 'たか', None, None], [None, None, 'くしたら', None], ['客', 'きゃく', None, None], [None, None, 'が', None], [None, None, 'やや', True], ['減', 'へ', None, None], [None, None, 'った。', None]]

100%|█████████▉| 936/938 [09:43<00:01,  1.63it/s]

[['二人', 'ふたり', None, None], [None, None, 'の', None], ['意見', 'いけん', None, None], [None, None, 'は', None], [None, None, 'いずれも', True], ['熟考', 'じゅっこう', None, None], [None, None, 'する', None], ['価値', 'かち', None, None], [None, None, 'がある。', None]]
[['寿司', 'すし', None, None], [None, None, 'とすき', None], ['焼', 'や', None, None], [None, None, 'き、', None], [None, None, 'いずれも', True], ['日本食', 'にほんしょく', None, None], [None, None, 'である。', None]]
[[None, None, 'それらの', None], ['本', 'ほん', None, None], [None, None, 'は', None], [None, None, 'いずれも', True], ['教育', 'きょういく', None, None], [None, None, 'に', None], ['関', 'かん', None, None], [None, None, 'するものだ。', None]]
[['父', 'ちち', None, None], [None, None, 'と', None], ['母', 'はは', None, None], [None, None, '、', None], [None, None, 'いずれも', True], ['昭和', 'しょうわ', None, None], [None, None, 'に', None], ['生', 'う', None, None], [None, None, 'まれたそうです。', None]]
[[None, None, 'ピンクとオレンジ、', None], [None, None, 'いずれも', True], ['明', 'あか', None, None], [None, None, 'るい', None], ['色', 'いろ', None, None], [None, None, 'です。', None]]

100%|█████████▉| 937/938 [09:44<00:00,  1.32it/s]

[['競馬', 'けいば', None, None], [None, None, 'で', None], ['勝', 'か', None, None], [None, None, 'って、', None], [None, None, 'あわよくば', True], ['大金持', 'おおがねも', None, None], [None, None, 'ちになるぞ。', None]]
[['議員', 'ぎいん', None, None], [None, None, '：「', None], [None, None, 'あわよくば', True], [None, None, 'トップで', None], ['当選', 'とうせん', None, None], [None, None, 'したい。」', None]]
[[None, None, 'あわよくば', True], [None, None, 'ミスコンで', None], ['優勝', 'ゆうしょう', None, None], [None, None, 'したいと', None], ['思', 'おも', None, None], [None, None, 'っている。', None]]
[[None, None, 'この', None], ['詐欺', 'さぎ', None, None], [None, None, 'が', None], ['成功', 'せいこう', None, None], [None, None, 'したら', None], [None, None, 'あわよくば', True], ['裕福', 'ゆうふく', None, None], [None, None, 'になれる。', None]]
[['会社', 'かいしゃ', None, None], [None, None, 'の', None], ['業績', 'ぎょうせき', None, None], [None, None, 'が', None], ['上', 'あ', None, None], [None, None, 'がった。', None], [None, None, 'あわよくば', True], ['僕', 'ぼく', None, None], [None, None, 'の', None], ['給料', 'きゅうりょう', None, None], [None, None, 'も', None], ['上', 'あ', None, None], [None, None, 'がるかも。', None]]

100%|██████████| 938/938 [09:44<00:00,  1.60it/s]

[['世', 'よ', None, None], [None, None, 'の', None], ['流', 'なが', None, None], [None, None, 'れに', None], ['逆', 'さか', None, None], [None, None, 'らはず、', None], ['静', 'しず', None, None], [None, None, 'かに', None], ['身', 'み', None, True], [None, None, 'を', True], ['引', 'ひ', None, True], [None, None, 'かむず', True], [None, None, '。', None]]
[[None, None, 'いかに', None], ['世', 'よ', None, None], [None, None, 'の', None], ['無常', 'むじょう', None, None], [None, None, 'を', None], ['知', 'し', None, None], [None, None, 'るとも、', None], ['誠', 'まこと', None, None], [None, None, 'の', None], ['心', 'こころ', None, None], [None, None, 'だけは', None], ['失', 'うしな', None, None], [None, None, 'はじと', None], ['誓', 'ちか', None, None], [None, None, 'ひ、', None], ['歩', 'あゆ', None, True], [None, None, 'み', True], ['続', 'つづ', None, True], [None, None, 'けむず', True], [None, None, '。', None]]
[['花', 'はな', None, None], [None, None, 'の', None], ['香', 'か', None, None], [None, None, 'に', None], ['誘', 'さそ', None, None], [None, None, 'はれしは、', None], ['春', 'はな', None, None], [None, None, 'の', None], ['精', 'せい', None, None], [None, None, 'ならんず', True], [None, None, '。', None]]
[[None, None, 'この', None], ['花', 'はな', None, None], [None, None, '、', None], ['母', 'はは', None, None], [None, None, 'に', None], ['届', 'とど', None, True], [None, None, 'けむず', True], [None, None, '。', None]]
[['道険', 'みちけわ', None, None], [None, None, 'しくとも、', None], ['志', 'こころざし', None, None], [None, None, 'ひとつにて', None], ['進', 'すす', None, True], [None, None, 'みゆかむず', True], [None, None, '。', None]]

In [89]:
examples_df

,grammar_id,text,grammar_char_locations
0,0,"[[私, わたし, None, None], [None, None, だ, True], ...","[[1, 2]]"
1,0,"[[本, ほん, None, None], [None, None, だ, True], [...","[[1, 2]]"
2,0,"[[猫, ねこ, None, None], [None, None, だ, True], [...","[[1, 2]]"
3,0,"[[学生, がくせい, None, None], [None, None, だ, True]...","[[2, 3]]"
4,0,"[[綺麗, きれい, None, None], [None, None, だ, True],...","[[2, 3]]"
...,...,...,...
4684,937,"[[世, よ, None, None], [None, None, の, None], [流...","[[13, 19]]"
4685,937,"[[None, None, いかに, None], [世, よ, None, None], ...","[[26, 32]]"
4686,937,"[[花, はな, None, None], [None, None, の, None], [...","[[13, 17]]"
4687,937,"[[None, None, この, None], [花, はな, None, None], ...","[[6, 10]]"
4688,937,"[[道険, みちけわ, None, None], [None, None, しくとも、, N...","[[13, 19]]"

In [93]:
examples_df.to_csv('examples.csv', encoding='utf-16', header=False)

In [94]:
df_2 = pd.read_csv('examples.csv', encoding='utf-16', index_col=0 ,names=["grammar_id", "text", "grammar_char_locations"])

df_2

,grammar_id,text,grammar_char_locations
0,0,"[['私', 'わたし', None, None], [None, None, 'だ', T...","[[1, 2]]"
1,0,"[['本', 'ほん', None, None], [None, None, 'だ', Tr...","[[1, 2]]"
2,0,"[['猫', 'ねこ', None, None], [None, None, 'だ', Tr...","[[1, 2]]"
3,0,"[['学生', 'がくせい', None, None], [None, None, 'だ',...","[[2, 3]]"
4,0,"[['綺麗', 'きれい', None, None], [None, None, 'だ', ...","[[2, 3]]"
...,...,...,...
4684,937,"[['世', 'よ', None, None], [None, None, 'の', Non...","[[13, 19]]"
4685,937,"[[None, None, 'いかに', None], ['世', 'よ', None, N...","[[26, 32]]"
4686,937,"[['花', 'はな', None, None], [None, None, 'の', No...","[[13, 17]]"
4687,937,"[[None, None, 'この', None], ['花', 'はな', None, N...","[[6, 10]]"
4688,937,"[['道険', 'みちけわ', None, None], [None, None, 'しくと...","[[13, 19]]"

In [105]:
ex = df_2.loc[1210]

example = ''

ex_text = literal_eval(ex['text'])
print(ex_text)
for i in range(len(ex_text)):
    if ex_text[i][0] is not None:
        example += ex_text[i][0]
    else:
        example += ex_text[i][2]

example

[[None, None, 'スマホ', None], [None, None, 'を', None], ['使', 'つか', None, True], [None, None, 'わせてくれないか', True], [None, None, '？', None]]

'スマホを使わせてくれないか？'